src/datatypes/src/data_type.rs, src/datatypes/src/schema.rs, src/datatypes/src/schema/constraint.rs, src/datatypes/src/types/binary_type.rs, src/datatypes/src/types/boolean_type.rs, src/datatypes/src/types/date_type.rs, src/datatypes/src/types/datetime_type.rs, src/datatypes/src/types/dictionary_type.rs, src/datatypes/src/types/duration_type.rs, src/datatypes/src/types/interval_type.rs, src/datatypes/src/types/list_type.rs, src/datatypes/src/types/null_type.rs, src/datatypes/src/types/primitive_type.rs, src/datatypes/src/types/string_type.rs, src/datatypes/src/types/time_type.rs, src/datatypes/src/types/timestamp_type.rs, src/datatypes/src/value.rs, src/mito2/src/read.rs, src/storage/src/sst/parquet.rs, src/storage/src/sst/pruning.rs, src/store-api/src/metadata.rs
main change:
1. remove `is_timestamp_compatible()` from `datatype` trait.
2. remove `int64` => `timestamp` from match arms.
3. remove `int64` to `timestamp` from mito2.
=> refactor: not allowed int64 type as time index

src/meta-srv/src/handler/node_stat.rs
=> chore: typo

src/frontend/src/instance/otlp.rs, src/servers/src/influxdb.rs, src/servers/src/otlp.rs, src/servers/src/prom_store.rs, src/servers/src/row_writer.rs, tests-integration/src/otlp.rs
This patch adds OTLP histogram data type support, which was left blank in our initial release.
The implementation has been following Prometheus histogram table format:
- A `%metric%_bucket` table including `le` tag that stores bucket upper limit, and `greptime_value` for bucket count
- A `%metric%_sum` table storing sum of samples
- A `%metric%_count` table storing count of samples.
By its Prometheus compatibility, we hope to be able to use prometheus quantile functions on this table.
=> feat: implement storage for OTLP histogram

src/mito2/src/region/opener.rs, src/mito2/src/worker/handle_create.rs, src/mito2/src/worker/handle_open.rs
This PR normalizes region dir in RegionOpener to ensure `region_dir` is always valid.
=> fix(mito): normalize region dir in RegionOpener

tests/cases/standalone/common/alter/add_incorrect_col.result, tests/cases/standalone/common/alter/add_incorrect_col.sql
This PR adds a integration test for issue2437. Very trivial.
Related to https://github.com/GreptimeTeam/greptimedb/pull/2437#discussion_r1329871864
=> chore: add integration test for issue2437

src/servers/src/http.rs, src/servers/src/mysql/writer.rs, src/servers/src/postgres/handler.rs
#2428 removes "source" from error, making user facing interfaces (mysql, pg and http) lack of root cause. 
Take mysql as an example, selecting an not existed table.
Before: 
ERROR 1815 (HY000): Failed to execute query, query: select * from monitor
After:
ERROR 1815 (HY000): Error during planning: Table not found: greptime.public.monitor
=> fix: print root cause error message to user facing interface

src/mito2/src/compaction/output.rs, src/mito2/src/compaction/picker.rs, src/mito2/src/compaction/twcs.rs, src/mito2/src/flush.rs, src/mito2/src/lib.rs, src/mito2/src/memtable.rs, src/mito2/src/memtable/time_series.rs, src/mito2/src/request.rs, src/mito2/src/sst/parquet/reader.rs, src/mito2/src/sst/stream_writer.rs
Remove allow dead_code attributes and remove unused code
=> refactor(mito): remove #[allow(dead_code)]

src/common/time/src/datetime.rs, src/datatypes/src/types/datetime_type.rs, src/datatypes/src/vectors/datetime.rs
- change datetime's default time unit from second to millisecond
=> refactor: datetime time unit

config/datanode.example.toml, src/cmd/src/datanode.rs, src/common/meta/src/distributed_time_constants.rs, src/datanode/src/heartbeat.rs, src/meta-client/src/client.rs, src/meta-client/src/client/ask_leader.rs, src/meta-client/src/error.rs, src/meta-client/src/lib.rs, src/meta-srv/src/election.rs, src/meta-srv/src/election/etcd.rs
If the metasrv leader is dead, the datanode only has a small window(`Datanode Lease - (<Heartbeat interval + Timeout> + <Meta Lease> + <Ask Leader Timeout + Connect Timeout>`)  to resend region stats. We must ensure the small window is greater than 0s. After this PR, the datanode will have a 5.5s~ (13s - 3.5s - 3s - 1s) window to resend the heartbeat.
1. refactor: set meta leader lease secs to 3s (origin: 5s)
2. fix: correct default heartbeat interval
3. refactor: ask the metasrv leader in parallel
4. feat: configure heartbeat client timeout to 500ms
5. fix: trigger to send heartbeat immediately after fail
=> fix: dn doesn't have chance to send a heartbeat to the new leader

src/cmd/src/cli/repl.rs, src/datanode/src/datanode.rs, src/frontend/src/instance.rs, src/operator/src/delete.rs, src/operator/src/req_convert/insert/table_to_region.rs, src/operator/src/statement.rs, src/operator/src/statement/copy_table_from.rs, src/operator/src/statement/dml.rs, src/operator/src/table.rs, src/operator/src/tests/partition_manager.rs, src/query/src/datafusion.rs, src/query/src/error.rs, src/query/src/query_engine.rs, src/query/src/query_engine/state.rs, src/query/src/range_select/plan_rewrite.rs, src/query/src/region_query.rs, src/query/src/table_mutation.rs, src/query/src/tests.rs, src/query/src/tests/query_engine_test.rs, src/query/src/tests/time_range_filter_test.rs, src/script/benches/py_benchmark.rs, src/script/src/python/engine.rs, src/script/src/test.rs, src/servers/src/line_writer.rs, src/servers/tests/mod.rs, src/table/src/requests.rs, src/table/src/table.rs
* Remove calling to table.insert and table.delete, and replace with `TableMutationHandler`
* Clean some dead code
Hopefully, after this patch and #2482, #2445 should done
=> feat: re-support query engine execute dml

src/common/time/src/datetime.rs
=> fix: convert datetime to chrono datetime

Cargo.lock, Cargo.toml, src/common/meta/src/ddl.rs, src/common/meta/src/ddl/create_table.rs, src/common/meta/src/ddl/drop_table.rs, src/common/meta/src/ddl/truncate_table.rs, src/common/meta/src/ddl_manager.rs, src/common/meta/src/metrics.rs, src/common/meta/src/rpc/ddl.rs, src/operator/src/statement/ddl.rs, src/store-api/src/region_request.rs, tests/cases/standalone/common/truncate/truncate.result, tests/cases/standalone/common/truncate/truncate.sql
Implement truncate table in region server.
=> feat: distribute truncate table in region server

Cargo.lock, Cargo.toml, src/catalog/Cargo.toml, src/client/Cargo.toml, src/frontend/Cargo.toml, src/mito2/Cargo.toml, src/mito2/src/cache.rs, src/mito2/src/cache/cache_size.rs, src/mito2/src/cache/test_util.rs, src/mito2/src/config.rs, src/mito2/src/engine.rs, src/mito2/src/lib.rs, src/mito2/src/read/scan_region.rs, src/mito2/src/read/seq_scan.rs, src/mito2/src/region/opener.rs, src/mito2/src/sst/file.rs, src/mito2/src/sst/file_purger.rs, src/mito2/src/sst/parquet/reader.rs, src/mito2/src/worker.rs, src/mito2/src/worker/handle_create.rs, src/mito2/src/worker/handle_open.rs, src/partition/Cargo.toml, tests-integration/tests/http.rs
This PR adds a manager `CacheManager` to cache data for the mito engine. This is the first step to implement a cache component for the engine.
It implements a cache layer `AsyncFileReaderCache` for parquet's `AsyncFileReader` trait so we can return our cached metadata to `ParquetRecordBatchStreamBuilder`. The `AsyncFileReaderCache` also has local cached metadata. It is unused now but is useful when we implement row group readers that require building `ParquetRecordBatchStreamBuilder` multiple times.
Now the `CacheManager` only caches metadata of the parquet file. This might provide less improvement in performance. I'll start refactoring our `ParquetReader` to support caching …
=> feat(mito): Add cache manager

src/mito2/src/engine.rs, src/mito2/src/engine/drop_test.rs, src/mito2/src/engine/flush_test.rs, src/mito2/src/engine/listener.rs, src/mito2/src/engine/truncate_test.rs, src/mito2/src/region/version.rs, src/mito2/src/sst/version.rs, src/mito2/src/test_util.rs, src/mito2/src/worker.rs, src/mito2/src/worker/handle_drop.rs
This PR fixes the following issues while dropping a region
- background later drop task never exits until it exceeds max retry times
- the dropping region map keeps the region that references all SSTs thus we can't purge them. This PR reset the `Version` so the region releases the references to SSTs and purges them.
It also adds a test to check whether the region directory is removed as expected.
closes #2501
=> fix(mito): fix region drop task runs multiple times but never clean the dir

src/common/telemetry/src/macros.rs
Simplify the implementation. Use debug format by default and remove the status code. 
closes https://github.com/GreptimeTeam/greptimedb/issues/2502
=> refactor: simplify `warn!` and `error!` macros

config/datanode.example.toml, config/frontend.example.toml, src/common/grpc/src/channel_manager.rs, src/datanode/src/heartbeat.rs, src/meta-client/src/lib.rs
1. set default connect timeout to 1000 ms
2. re-create heartbeat stream ASAP
#2496
=> fix: re-create heartbeat stream ASAP

src/datanode/src/region_server.rs
Previous `TableProviderFilterPushDown::Unsupported` prevented pushdown
=> feat: push down filters to region engine

src/file-engine/src/query.rs, src/file-engine/src/query/file_stream.rs
If there is a filter, the limit will not be pushed down.
and refactor the `FileToScanRegionStream`.
=> feat: defensively specify limit parameter for file stream

src/cmd/src/error.rs, src/cmd/src/options.rs, src/cmd/src/standalone.rs, src/common/config/src/lib.rs, src/datanode/src/config.rs, src/file-engine/src/config.rs, src/frontend/src/frontend.rs, src/frontend/src/service_config/grpc.rs, src/frontend/src/service_config/influxdb.rs, src/frontend/src/service_config/mysql.rs, src/frontend/src/service_config/opentsdb.rs, src/frontend/src/service_config/otlp.rs, src/frontend/src/service_config/postgres.rs, src/frontend/src/service_config/prom_store.rs, src/meta-client/src/lib.rs, src/mito2/src/config.rs, src/servers/src/heartbeat_options.rs
Run db with
```sh
$ cargo run --bin greptime -- standalone start
```
Logs before:
```
...
region_engine: [
Mito(
...
),
],
...
```
With this patch:
```
...
region_engine: [
Mito(
...
),
File(
EngineConfig,
),
],
...
```
=> fix: missing file engine with default options

src/meta-srv/src/bootstrap.rs, src/meta-srv/src/error.rs, src/servers/src/error.rs, src/servers/src/grpc.rs
Enable `TCP_NODELAY` for internal services by default, enabled by default in `tonic::transport::server::Router::serve_with_shutdown`.  However,`TcpListenerStream` + `TcpListener` didn't. 
For small, sequential requests, Disable `TCP_NODELAY ` is slower ~100x than enabled (used in `TcpIncoming`).
TL; DR. I'm tuning my program and copying some ideas from the greptimedb repo, which has become slower. 
Above(Enable) 
Below(Disable)
=> feat: enable tcp no_delay by default for internal services

src/mito2/src/read.rs, src/mito2/src/read/merge.rs
This PR uses a heap to merge sorted batches in the `BatchMerger` instead of concatenating these batches and uses `sort_and_dedup()`. It also avoids concatenating batches as it introduces additional overhead.
These changes can speed up the merge reader when input batches don't have too many overlapping rows.
On Apple M1 Pro, merging 148797 sorted batches with 100,000,000+ rows took 2.2s before and 358ms now. Note that this only considers the cost of `BatchMerger`, not the whole `MergeReader`.
|  Before  | After |
|  ----  | ----  |
| 2.2s | 358ms |
It also fixes an issue that if a batch is empty after `filter_deleted()`, the reader will return `None` even if there are …
=> perf(mito): Use a heap to merge batches for the same key

src/datatypes/src/data_type.rs, src/datatypes/src/schema.rs, src/datatypes/src/schema/column_schema.rs, src/store-api/src/metadata.rs
- `schema` and `column_metadatas`(in `struct RegionMetadata`) contain the same information for column schma
- the content of `column_schemas` and `arrow_schema`(in `struct Schema`) are very similar
- In debugg, reduce redundant information in the output
=> feat: the schema of RegionMetadata is not output during debug

src/mito2/src/cache.rs, src/mito2/src/config.rs, src/mito2/src/memtable/key_values.rs, src/mito2/src/read/projection.rs, src/mito2/src/read/seq_scan.rs, src/mito2/src/test_util.rs, src/mito2/src/test_util/meta_util.rs, src/mito2/src/worker.rs, tests-integration/tests/http.rs
This PR adds a cache for repeated vectors created in `ProjectionMapper::convert()`.
While returning tags to users, the mito engine needs to flatten tag values into vectors for each primary key. This is CPU expensive.
Before adding the cache, converting `140000+` batches (`700` rows on average) for `4000` timeseries takes `6.8s`. With vector cache, it takes `560ms`.
=> feat(mito): Cache repeated vector for tags

src/query/src/tests/time_range_filter_test.rs, src/table/src/predicate.rs
This PR fixes the bug in building timestamp range predicates when operators do not conform commutative property.
Fixes #2508
=> fix: timestamp range filter

src/mito2/src/engine.rs, src/mito2/src/engine/compaction_test.rs, src/mito2/src/engine/drop_test.rs, src/mito2/src/engine/flush_test.rs, src/mito2/src/engine/prune_test.rs, src/mito2/src/engine/truncate_test.rs, src/mito2/src/flush.rs, src/mito2/src/read/scan_region.rs, src/mito2/src/sst/parquet.rs, src/mito2/src/sst/parquet/format.rs, src/mito2/src/sst/parquet/reader.rs, src/mito2/src/sst/parquet/stats.rs, src/mito2/src/test_util.rs, src/mito2/src/worker.rs, src/mito2/src/worker/handle_alter.rs, src/mito2/src/worker/handle_flush.rs, src/store-api/src/region_request.rs, src/table/src/predicate.rs
This PR implements row group pruning for the new mito engine.
Previous implementation uses the schema of the region to find the index of a column, which is incorrect under the new SST format. Due to the restriction that the row group metadata only contains the min/max values of primary keys, not tags, the `ParquetReader` can only use the first tag in the primary key to prune row groups.
fixes #2524
=> fix(mito): pruning for mito2

src/servers/src/http.rs, src/servers/src/mysql/server.rs, src/servers/src/opentsdb.rs
Enable tcp no delay for mysql, opentsdb, http protocol
close #2528
=> feat: enable no delay for mysql, opentsdb, http

src/servers/src/error.rs, src/servers/src/http.rs, src/servers/src/http/pprof.rs, src/servers/src/http/pprof/nix.rs
This PR fixes the compiler errors under `pprof` and `mem-prof` features
=> fix: compiler errors under `pprof` and `mem-prof` features

src/meta-srv/src/handler.rs
`Receiver` may be closed unexpectedly. It shouldn't be handled in fail fast. Let's check the push result out of the loop.
=> refactor: check push result out of loop

Cargo.lock, src/common/meta/Cargo.toml, src/common/meta/src/rpc/ddl.rs
de/encode protobuf-encoded byte array with base64
close #2542
=> refactor: de/encode protobuf-encoded byte array with base64

Cargo.lock, src/catalog/src/kvbackend/manager.rs, src/common/meta/Cargo.toml, src/common/meta/src/ddl/alter_table.rs, src/common/meta/src/ddl/drop_table.rs, src/common/meta/src/ddl/truncate_table.rs, src/common/meta/src/ddl_manager.rs, src/common/meta/src/key.rs, src/common/meta/src/key/table_info.rs, src/common/meta/src/key/table_route.rs, src/meta-srv/src/procedure/region_failover/activate_region.rs, src/meta-srv/src/procedure/region_failover/update_metadata.rs, src/meta-srv/src/procedure/tests.rs, src/meta-srv/src/selector/load_based.rs, src/meta-srv/src/table_routes.rs, src/partition/src/manager.rs, tests-integration/src/grpc.rs, tests-integration/src/instance.rs
1. Wrap values with `DeserializedValueWithBytes` struct.
2. Compare with origin bytes during the transactions
This PR modifies the persistent structs used in meta's procedures, ensuring all old procedures are finished before starting a new version of metasrv.
close #2198
=> refactor!: compare with origin bytes during the transactions

src/catalog/src/kvbackend/manager.rs, src/common/meta/src/cache_invalidator.rs, src/frontend/src/heartbeat/handler/invalidate_table_cache.rs
1. Remove unused `invalidate_schema` method.
2. Refactor `TableMetadataCacheInvalidator`.
=> refactor: refactor cache invalidator

src/mito2/src/engine/basic_test.rs, src/mito2/src/memtable/key_values.rs, src/mito2/src/request.rs, tests/cases/standalone/common/insert/insert_different_order.result, tests/cases/standalone/common/insert/insert_different_order.sql
This PR fixes an issue that `WriteRequest::check_schema()` doesn't check the schema of remaining columns in `rows` if it finds out that a column is absent but has a default value.
It uses a flag to store whether rows have such a column instead of returning directly.
It also adds some tests for input rows with different column order than the region.
fixes #2547
=> fix: schema validation is skipped once we need to fill a column

src/mito2/src/sst/parquet.rs, src/mito2/src/sst/parquet/reader.rs
Change default batch size and row group size to `1024` and `100 * 1024`.
Arrow aligns its buffer to a multiple of 64 so our old default batch size (1000) wastes some slots.
=> chore(mito): change default batch size/row group size

src/cmd/src/standalone.rs, src/common/config/src/lib.rs
The KV directory has been renamed to metadata to provide more useful info for users.
#2493
=> feat: renaming kv directory to metadata

src/cmd/src/frontend.rs
The doc has this option but missing in the code.
=> fix: adds back http_timeout for frontend subcommand

Cargo.lock, src/mito2/Cargo.toml, src/mito2/src/flush.rs, src/mito2/src/memtable.rs, src/mito2/src/memtable/time_series.rs, src/mito2/src/read/seq_scan.rs, src/mito2/src/test_util/memtable_util.rs, src/table/src/predicate.rs
This PR enables filter pushdown for memtable so that irrelavant time series can be skipped.
=> feat: memtable filter push down

src/mito2/src/metrics.rs, src/mito2/src/region_write_ctx.rs, src/mito2/src/worker/handle_write.rs, src/store-api/src/region_request.rs
This PR adds a flag to the `RegionWriteCtx` to avoid writing to the mutable memtable if the region fails to write to the WAL. The worker sets the flag in `set_error()`.
https://github.com/GreptimeTeam/greptimedb/blob/8bdef9a348d997c51ebf1c2a1626f02cf6296403/src/mito2/src/worker/handle_write.rs#L67-L80
It adds some metrics about the number of rows written.
I removed one TODO about the naming as Put is a common operation in NoSQL databases which is different from `Insert` in relational databases.
=> fix(mito): Do not write to memtables if writing wal is failed

src/meta-srv/src/bootstrap.rs, src/meta-srv/src/metasrv.rs
It also disables region failover feature by default.
=> fix: support multi addrs while using etcd

src/mito2/src/compaction.rs, src/mito2/src/compaction/twcs.rs, src/mito2/src/metrics.rs, src/mito2/src/request.rs, src/mito2/src/worker/handle_compaction.rs
=> feat: add compaction metrics

src/datanode/src/metrics.rs, src/datanode/src/region_server.rs, src/store-api/src/region_request.rs
Add metrics for `region_server.handle_request`
=> feat: add metrics for region server

.github/workflows/release.yml, Cargo.toml
=> chore: bump version to 0.4.0

src/mito2/src/memtable/time_series.rs
=> fix: revert memtable pk rb cache to rwlock

README.md
=> fix: fix to readme document link

.github/workflows/release-dev-builder-images.yaml, .github/workflows/release.yml
ci: seperate the job of building dev-builder images
=> ci: seperate the job of building dev-builder images

.github/actions/build-greptime-binary/action.yml, .github/actions/build-macos-artifacts/action.yml, .github/actions/publish-github-release/action.yml, .github/actions/release-cn-artifacts/action.yaml, .github/actions/upload-artifacts/action.yml, .github/workflows/dev-build.yml, .github/workflows/nightly-build.yml, .github/workflows/release.yml
1. Add new action 'release-cn-artifacts' to make the action of releasing artifacts to cn region idempotent(always can retry);
2. Refine naming: `release-artifacts` -> `publish-github-release`;
=> refactor: add new action 'release-cn-artifacts'

config/datanode.example.toml, config/standalone.example.toml
Fixed the unit in sample config.
=> fix: cache capacity unit in sample config

.github/actions/build-dev-builder-images/action.yml, .github/workflows/release-dev-builder-images.yaml
Refine the process of releasing dev-builder images:
1. Add the new job `release-dev-builder-images-cn` to separate the process of using `skopeo` to push images to ACR;
2. Fix run `skopeo` errors:
- `run:` -> `run: |`(What a stupid mistake);
- Use skopeo stable latest container instead of installing from apt(the version is stale and will have some problems to work with buildx);
- Describe any …
=> ci: refine the process of releasing dev-builder images

.github/actions/build-windows-artifacts/action.yml, .github/actions/upload-artifacts/action.yml, .github/workflows/release.yml
=> ci: release Windows artifacts

.github/actions/release-cn-artifacts/action.yaml
Fix skopeo running errors:
- Use env to inject credentials;
- Use skopeo latest stable container instead of installing from apt;
=> ci: fix skopeo running errors

config/standalone.example.toml, src/cmd/src/options.rs, src/cmd/src/standalone.rs
change the config name `kv_store` to `metadata_store` for standalone
follow up of https://github.com/GreptimeTeam/greptimedb/pull/2549
=> feat!: change config name from kv_store to metadata_store

src/cmd/src/error.rs, src/cmd/src/standalone.rs
=> fix: ensure data_home directory created

docker/buildx/ubuntu/Dockerfile, docker/dev-builder/ubuntu/Dockerfile
ci: downgrade builder version: ubuntu 22.04 -> ubuntu 20.04 for compatible with older version glibc(>=2.31)
=> ci: downgrade builder version: ubuntu 22.04 -> ubuntu 20.04 for compatible with older version glibc(>=2.31)

.github/workflows/apidoc.yml, .github/workflows/dev-build.yml, .github/workflows/develop.yml, .github/workflows/doc-issue.yml, .github/workflows/docs.yml, .github/workflows/license.yaml, .github/workflows/nightly-build.yml, .github/workflows/pr-title-checker.yml, .github/workflows/release-dev-builder-images.yaml, .github/workflows/release.yml
use `ubuntu-20.04-x` instead of `ubuntu-latest-x`
=> build(ci): pin linux runner to ubuntu-20.04

docs/benchmarks/tsbs/v0.4.0.md
Update benchmark result. Including v0.4.0 on PC, Aliyun AMD64 and Aliyun ARM64 results
=> docs(benchmark): update 0.4.0 tsbs result

Cargo.lock, config/datanode.example.toml, config/frontend.example.toml, config/metasrv.example.toml, src/client/src/client.rs, src/cmd/src/datanode.rs, src/cmd/src/frontend.rs, src/cmd/src/options.rs, src/common/grpc/src/channel_manager.rs, src/datanode/src/config.rs, src/datanode/src/heartbeat.rs, src/datanode/src/server.rs, src/frontend/src/heartbeat.rs, src/frontend/src/instance.rs, src/frontend/src/server.rs, src/frontend/src/service_config/grpc.rs, src/meta-client/Cargo.toml, src/meta-client/src/lib.rs, src/servers/src/grpc.rs, src/servers/src/heartbeat_options.rs, tests-integration/tests/http.rs
- Convert to u64 to ReadableSize and Durations
[#2582](https://github.com/GreptimeTeam/greptimedb/issues/2582)
=> fix: convert to ReadableSize & Durations

Cargo.lock, benchmarks/Cargo.toml, benchmarks/src/bin/nyc-taxi.rs, src/client/src/lib.rs
The request created by the nyc-taxi bench is invalid under 0.4. This PR fixes the issue and appends a timestamp to the table name to avoid table name conflicts.
Here is my test result on mbp 14 2021
```
[00:00:04] ############################################################ 2463931/2463931 file "/Users/evenyag/codes/greptime/greptimedb/benchmarks/data/yellow_tripdata_2022-01.parquet" done in 4048msRunning query: SELECT passenger_count, MIN(fare_amount), MAX(fare_amount), SUM(fare_amount) FROM nyc_taxi_1697182595 GROUP BY passenger_count
query fare_amt_by_passenger, iteration 0: 269ms
query fare_amt_by_passenger, iteration 1: 188ms
query fare_amt_by_passenger, iteration 2: …
```
=> fix: make nyc-taxi bench work again

src/cmd/src/standalone.rs
This pr mainly fixed `user_provider` option not working in standalone mode.
TODO(separate pr)
- add more integration tests
- support weekly SDK CI with regression test 
#2578
=> fix: auth in standalone mode

.github/actions/release-cn-artifacts/action.yaml, .github/scripts/copy-image.sh, .github/scripts/upload-artifacts-to-s3.sh, .github/workflows/dev-build.yml, .github/workflows/nightly-build.yml, .github/workflows/release.yml
Refine release-cn-artifacts action:
1. Add `upload-artifacts-to-s3.sh` and `copy-image.sh` to make the release operations decouple from GitHub Actions yaml files(Provide the option to run it locally);
2. Modify the related workflows to adapt the above scripts; 
=> ci: refine release-cn-artifacts action

.github/workflows/dev-build.yml
ci: correct image name of dev build.
=> ci: correct image name of dev build

config/standalone.example.toml, src/cmd/src/datanode.rs, src/cmd/src/options.rs, src/cmd/src/standalone.rs, src/common/config/src/lib.rs, src/datanode/src/datanode.rs
Add Wal dir config back.
#2312
=> feat: add walconfig dir back

src/cmd/src/frontend.rs
As title.
https://github.com/GreptimeTeam/greptimedb/issues/2571
=> fix!: align frontend cmd name to rpc_*

src/cmd/src/cli/export.rs
This pr mainly adds export-data to cli export tool.
e.g
```shell
./greptime cli export --addr=127.0.0.1:4001 --output-dir=/tmp/export/ --target=create-table --database="greptime-*"
./greptime cli export --addr=127.0.0.1:4001 --output-dir=/tmp/export/ --target=table-data --database="greptime-*"
``` 
result
```
/tmp/export
❯ tree
.
├── greptime-public.sql
├── greptime-thello
│   └── monitor.parquet
├── greptime-thello.sql
└── greptime-thello_copy_from.sql
2 directories, 4 files
```
```shell
psql -h 127.0.0.1 -p 4003 -d thello -a -f greptime-thello.sql
psql -h 127.0.0.1 -p 4003 -d thello -a -f greptime-thello_copy_from.sql
mysql -h 127.0.0.1 -P 4002 public < greptime-public.sql …
```
=> chore: add export data to migrate tool

src/cmd/src/error.rs, src/cmd/src/standalone.rs, src/common/greptimedb-telemetry/src/lib.rs, src/common/meta/src/key.rs, src/common/procedure/src/error.rs, src/common/procedure/src/lib.rs, src/common/procedure/src/local.rs, src/common/procedure/src/local/runner.rs, src/common/procedure/src/procedure.rs, src/common/procedure/src/watcher.rs, src/datanode/src/greptimedb_telemetry.rs, src/meta-srv/src/bootstrap.rs, src/meta-srv/src/error.rs, src/meta-srv/src/greptimedb_telemetry.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/test_util.rs, tests-integration/src/standalone.rs
1. Add a `running` flag to `ManagerContext`.
2. Throw an error for the running procedures if `Runner` is stopped.
3. Stop `Procedure Manager` if a new leader is elected. 
4. Start `Procedure Manager` if the meta server becomes a leader.
close #1721
=> feat: stop the procedure manager if a new leader is elected

src/common/base/src/readable_size.rs
make ReadableSize debug format for better readable.
for example:
run `cargo run -- standalone start`, and we can see some log info.
previous format：
```sh
wal: WalConfig {
dir: None,
file_size: ReadableSize(
268435456,
),
purge_threshold: ReadableSize(
4294967296,
),
purge_interval: 600s,
read_batch_size: 128,
sync_write: false,
},
```
current format：
```sh
wal: WalConfig {
dir: None,
file_size: 256.0MiB,
purge_threshold: 4.0GiB,
purge_interval: 600s,
read_batch_size: 128,
sync_write: false,
},
```
=> refactor: make ReadableSize more readable.

src/common/procedure/src/local.rs
Change test_remove_outdated_meta_task sleep time to 40ms
=> chore: change test_remove_outdated_meta_task sleep time to 40ms

src/datatypes/src/value.rs
get the byte size of the internal elements of ValueRef.
=> feat: get internal value size of ValueRef

docker/dev-builder/ubuntu/Dockerfile
Remove the older python version(3.8) and use the python 3.10.
=> ci: remove the old version python

.github/workflows/nightly-ci.yml
By default, only CI creator will receive notification for scheduled tasks. This patch adds slack notifications for failures of our nightly CI tasks
=> ci: add slack notification for nightly ci failure

src/common/meta/src/key.rs, src/common/meta/src/kv_backend.rs, src/common/meta/src/kv_backend/memory.rs, src/common/meta/src/kv_backend/test.rs, src/common/meta/src/rpc/store.rs, src/log-store/Cargo.toml, src/log-store/src/raft_engine/backend.rs
Correct the range behavior in MemoryKvBackend & RaftEngineBackend
close #2616
=> fix: correct the range behavior in MemoryKvBackend & RaftEngineBackend

src/frontend/src/instance/opentsdb.rs, src/servers/src/http/opentsdb.rs, src/servers/src/opentsdb.rs, src/servers/src/opentsdb/codec.rs, src/servers/src/opentsdb/handler.rs, src/servers/src/query_handler.rs, src/servers/tests/http/opentsdb_test.rs, src/servers/tests/opentsdb.rs, tests-integration/src/opentsdb.rs
Support for row inserts in opentsdb
OpenTSDB now uses the row insert protocol as against column inserts
close #2444
=> feat: row protocol support for opentsdb

.github/workflows/size-label.yml
An action to label PR's size automatically and send a suggestion on super large PR.
=> ci: add size labeler

Cargo.lock, src/promql/Cargo.toml, src/promql/src/extension_plan.rs, src/promql/src/extension_plan/histogram_fold.rs, src/promql/src/planner.rs
Part one of prometheus histogram. The next part is about planner and quantile.
`HistogramFold` will fold the conventional (non-native) histogram ([1]) for later
computing. Specifically, it will transform the `le` and `field` column into a complex
type, and samples on other tag columns:
- `le` will become a [ListArray] of [f64]. With each bucket bound parsed
- `field` will become a [ListArray] of [f64]
- other columns will be sampled every `bucket_num` element, but their types won't change.
Due to the folding or sampling, the output rows number will become `input_rows` / `bucket_num`.
`le` should be the same across the entire metric. Thus it can be a `Dict<List<f64>>` to …
=> feat: implement `HistogramFold` plan for prometheus histogram type

src/common/greptimedb-telemetry/src/lib.rs, src/common/runtime/src/lib.rs, src/common/runtime/src/repeated_task.rs
RepeatedTask adds execute-first-wait-later behavior.
=> feat: RepeatedTask adds execute-first-wait-later behavior.

tests/conf/datanode-test.toml.template, tests/conf/standalone-test.toml.template, tests/runner/src/env.rs
Pass config file of datanode in distributed mode with `-c xxx.toml`
=> fix: pass datanode config file in distributed mode sqlness

src/mito2/src/sst/parquet.rs, src/mito2/src/sst/parquet/row_group.rs
This PR copies `InMemoryRowGroup` from [parquet crate](https://github.com/apache/arrow-rs/blob/7e134f4d277c0b62c27529fc15a4739de3ad0afd/parquet/src/arrow/async_reader/mod.rs#L644-L650) and changes its visibility to `pub`.
This is the first step to implementing a row group level reader in our mito engine. There is an [example](https://github.com/apache/arrow-rs/blob/51ac6fec8755147cd6b1dfe7d76bfdcfacad0463/parquet/examples/read_with_rowgroup.rs) that shows how to use [`try_new_with_row_groups()`](https://docs.rs/parquet/latest/parquet/arrow/arrow_reader/struct.ParquetRecordBatchReader.html#method.try_new_with_row_groups) to read by row groups. Our row group level reader will …
=> feat(mito): Ports InMemoryRowGroup from parquet crate

Cargo.lock, src/object-store/Cargo.toml, src/object-store/src/error.rs, src/object-store/src/lib.rs, src/object-store/src/manager.rs, src/object-store/src/object_store_manager.rs
This PR implements `ObjectStoreManager`, which manages multiple object stores. 
I'll implement #919 at a high level like the below code, and this PR is a first step of this plan:
```rust
impl<S: LogStore> RegionWorkerLoop<S> {
pub(crate) async fn handle_create_request(
~
let object_store = if let Some(storage) = request.options.get(STORAGE_KEY) {
self.object_storage_manager: 
.find(storage)
~
} else {
self.object_storage_manager.global_object_store()
};
// Create a MitoRegion from the RegionMetadata.
let region = RegionOpener::new(
~
object_store, 
~
)
~
```
Part of https://github.com/GreptimeTeam/greptimedb/issues/919
=> feat: impl ObjectStoreManager for custom_storage

src/common/error/src/ext.rs, src/common/procedure/src/local/runner.rs, src/query/src/error.rs, src/servers/src/error.rs, src/servers/src/opentsdb/handler.rs, src/servers/tests/http/opentsdb_test.rs, tests/cases/distributed/optimizer/filter_push_down.result, tests/cases/standalone/common/order/order_by_exceptions.result, tests/cases/standalone/common/range/error.result, tests/cases/standalone/common/types/interval/interval.result, tests/cases/standalone/common/types/timestamp/timestamp.result, tests/cases/standalone/common/types/timestamp/timestamp_precision.result
This patch masks error message of any internal error and unknown error from end user, to prevent leak of deployment and other credential information.
=> feat: hide internal error and unknown error message from end user

src/mito2/src/manifest/manager.rs, src/mito2/src/manifest/storage.rs, src/mito2/src/manifest/tests/checkpoint.rs, src/mito2/src/test_util.rs
- use `HashMap<String, u64>` to keep track for every manifest file size in `ManifestObjectStore `.
- we can use `RegionManifestManager::manifest_size()` to get manifest files size.
https://github.com/GreptimeTeam/greptimedb/issues/2551
=> feat: lookup manifest file size

src/mito2/src/engine/create_test.rs, src/mito2/src/region/opener.rs
`create_or_open` will always return a writable region now.
Closes https://github.com/GreptimeTeam/greptimedb/issues/2634
=> refactor: create_or_open always set writable

config/datanode.example.toml, src/mito2/src/config.rs
This PR derives `serde(default)` for `MitoConfig`
=> fix: add serde default to MitoConfig

src/common/greptimedb-telemetry/src/lib.rs
* show version report data only once at db startup
=> chore: show version report data only once at db startup

.github/actions/deploy-greptimedb/action.yml, .github/actions/sqlness-test/action.yml, .github/scripts/deploy-greptimedb.sh, .github/workflows/nightly-funtional-tests.yml
Add the simple CI framework of nightly functional tests(https://github.com/GreptimeTeam/greptimedb/issues/2583). The CI will deploy three different greptimedb on K8s(created by `kind`) by using the **latest release images** and expose different ports to localhost:
1. greptimedb cluster by using local storage(expose `14000-14003`);
2. greptimedb cluster by using s3 storage(expose `24000-24003`);
3. greptimedb standalone by using local storage(expose `34000-34003`);
The actual test cases should be **black box**, which means it only needs the service endpoints. 
The PR doesn't add the real sqlness test that still need to be modified in the future. We will add it in the future. …
=> ci: add the simple framework of nightly functional tests

CONTRIBUTING.md
Improving and optimizing the CONTRIBUTING.md file
This pull request addresses and corrects several grammatical errors found throughout the codebase.
The changes include fixing typos, punctuation, and ensuring proper sentence structure for improved readability and clarity.
=> fix(grammatical): correct typos and improve grammar

src/cmd/src/frontend.rs, src/cmd/src/standalone.rs, src/common/error/src/ext.rs, src/common/procedure/src/local/runner.rs, src/operator/src/error.rs, src/plugins/src/frontend.rs
This patch remove `StatusCode::Unexpected` from masked error code because we are using it for the semantics of *unexpected* input. 
This patch also fixes some lint issue on newer version of rust.
=> fix: remove StatusCode::Unexpected from masked error code set

src/mito2/src/engine.rs, src/mito2/src/engine/basic_test.rs, src/mito2/src/memtable/time_series.rs, src/mito2/src/memtable/version.rs, src/mito2/src/region.rs
- memtable size is more accurate (now include timestamp and op type size)
- use memtable size to estimate wal size.
1. construct different size of rows to insert into or delete from table, and record relevant memtable size and wal size.
2. compute linear regression of these data, and get a rough slope, and use regression line' slope to estimate wal size.
the `slope` is not very accurate, and I also don't think about the `interception` because wal writes some metadata in `WalEntry`, and if the rows size is small, it's inaccurate.
https://github.com/GreptimeTeam/greptimedb/issues/2551
=> feat: estimate region wal size

Cargo.lock, Cargo.toml, src/catalog/src/kvbackend/client.rs, src/common/datasource/Cargo.toml, src/common/meta/src/kv_backend.rs, src/common/meta/src/kv_backend/memory.rs, src/common/meta/src/rpc/store.rs, src/common/meta/src/sequence.rs, src/log-store/src/raft_engine/backend.rs, src/meta-client/src/client.rs, src/meta-client/src/client/store.rs, src/meta-srv/src/service/store.rs, src/meta-srv/src/service/store/cached_kv.rs, src/meta-srv/src/service/store/etcd.rs, src/meta-srv/src/service/store/kv.rs
remove KvBackend's `move_value` method
=> refactor: remove move_value

src/common/time/src/time.rs
Due to [DST](https://en.wikipedia.org/wiki/Daylight_saving_time), some test results are unstable.
=> test: remove unstable timezone test

src/query/src/range_select/plan_rewrite.rs, tests/cases/standalone/common/range/nest.result, tests/cases/standalone/common/range/nest.sql
Make range query can be explain and analyze
- Build Explain and Analyze plan manually when range plan rewrite
- Add Sqlness test
=> fix: explain range query

src/servers/src/otlp/trace.rs
fix `events_to_string` and `links_to_string` via Serializable Struct
=> fix: events or links to string

src/datanode/src/heartbeat.rs, src/datanode/src/region_server.rs, src/datanode/src/tests.rs, src/file-engine/src/engine.rs, src/mito2/src/engine.rs, src/mito2/src/engine/basic_test.rs, src/mito2/src/manifest/manager.rs, src/mito2/src/region.rs, src/mito2/src/sst/version.rs, src/store-api/src/region_engine.rs
- region stat includes memtable(estimated), wal(estimated), sst(accurate), manifest(accurate) .
- engine can invoke `get_region_stat` to get specific region stat.
https://github.com/GreptimeTeam/greptimedb/issues/2551
=> feat: region disk usage statistic

Cargo.lock, Cargo.toml, src/datanode/src/heartbeat.rs, src/datanode/src/region_server.rs, src/datanode/src/tests.rs, src/file-engine/src/engine.rs, src/mito2/src/engine.rs, src/mito2/src/engine/open_test.rs, src/store-api/src/region_engine.rs
Introduce the region's role. Now, we only have two role:
The `RegionRole::Follower`:  Readonly Region(mito2), Readonly Region(file).
The `RegionRole::Leader`: Writable Region(mito2).
**Notes**: We treat all File Region as `RegionRole::Follower`, even if it's the leader peer in the region routes.
#2639
=> feat: introduce the region role

src/cmd/src/frontend.rs, src/cmd/src/standalone.rs
The mut ref is used for modifying contents of the options in function from other distros. Adding `#[allow(clippy::unnecessary_mut_passed)]` to pass clippy check.
=> fix: add back mut ref

src/cmd/src/cli/bench.rs, src/common/meta/src/key.rs, src/common/meta/src/rpc/router.rs, src/frontend/src/instance/standalone.rs, src/meta-srv/src/table_meta_alloc.rs, src/meta-srv/src/test_util.rs, src/operator/src/tests/partition_manager.rs
We should downgrade a Region before deactivating it:
- During the Region Failover Procedure.
- Migrating a Region.
**Notes:** Meta Server will stop renewing the lease for the downgraded [Region].
=> feat: add leader_status for RegionRoute

src/common/grpc/src/channel_manager.rs
According to https://github.com/hyperium/tonic/pull/1454, we would have to use `https` when tls config is present.
=> chore: use https when tls is present

src/mito2/src/error.rs, src/mito2/src/read/scan_region.rs, src/mito2/src/sst/parquet/format.rs, src/mito2/src/sst/parquet/reader.rs, src/mito2/src/sst/parquet/row_group.rs
This PR uses [try_new_with_row_groups()](https://docs.rs/parquet/latest/parquet/arrow/arrow_reader/struct.ParquetRecordBatchReader.html#method.try_new_with_row_groups) to read row groups one by one.
The new implementation is based on this [example](https://github.com/apache/arrow-rs/blob/be093cb44243a23b637754e06b13ccb4de2f6512/parquet/examples/read_with_rowgroup.rs)
- Recovers metadata from the file.
- Prunes row groups and collects row groups in a `VecDeque`
- Computes projection mask according to the projection
- Computes FieldLevels using `parquet_to_arrow_field_levels()`
- Iterates row groups and fetch pages of each row group
- Builds a `InMemoryRowGroup` and use …
=> feat(mito): Reads SST's row groups one by one

src/promql/src/extension_plan/histogram_fold.rs, tests/cases/standalone/common/promql/simple_histogram.result, tests/cases/standalone/common/promql/simple_histogram.sql
to separate time series and le buckets, the input data should be ordered on `<tags>, ts, le` rather than `<tags>, le, ts`
before this change, the result of new sqlness case is
=> fix: sort condition in HistogramFold

src/servers/src/otlp/trace.rs
the result of `Time::new_nanosecond(event.time_unix_nano as i64).to_iso8601_string()` is like `"[TimeNanosecond: 1698826931799930000]"`, which is not a good format for json
=> fix(OTLP/Trace): use Timestamp instead of Time for json

src/meta-srv/src/service/admin/meta.rs
change admin table api response format
```
{"13999":"TableInfoValue { table_info: RawTableInfo { ident: TableIdent { table_id: 13999, version: 0 }, name: \"cpu_metrics\", desc: None, catalog_name: \"q6dj4up5mmriweak_flowers\", schema_name: \"public\", meta: RawTableMeta { schema: RawSchema { column_schemas: [hostname String null, environment String null, usage_user Float64 null, usage_system Float64 null, usage_idle Float64 null, ts Timestamp not null default=Function(\"current_timestamp()\") metadata={\"greptime:time_index\": \"true\"}], timestamp_index: Some(5), version: 0 }, primary_key_indices: [0, 1], value_indices: [], engine: \"mito\", next_column_id: 6, …
```
=> chore: change admin table api return json format

src/datatypes/src/schema/constraint.rs, tests/cases/standalone/common/create/current_timestamp.result, tests/cases/standalone/common/create/current_timestamp.sql
Support `current_timestamp`, `current_timestamp()` and `now()` as PG does
=> feat: support current_timestamp and now as default constrains

src/mito2/src/engine/prune_test.rs, src/mito2/src/memtable/time_series.rs, src/mito2/src/read/scan_region.rs
This PR filters memtables by their time ranges while building the scanner. So we don't need to scan a memtable if doesn't contain the data we need.
It also fixes an issue that `TimeSeriesMemtable` returns incorrect time range in its `stats`.
=> feat(mito): filters memtables by their time ranges

Cargo.lock, Cargo.toml, src/common/meta/Cargo.toml, src/common/meta/src/error.rs, src/common/meta/src/lib.rs, src/common/meta/src/range_stream.rs
Decreases the `page size` if the response size exceeds the limit
#close #2680
=> feat: decrease the `page size` if the response size exceeds the limit

Cargo.lock, Cargo.toml, tests/cases/standalone/common/range/by.result, tests/cases/standalone/common/range/by.sql
Enable case `BY ()` like 
```sql
SELECT 
sum(metrics) RANGE '10m' FILL MAX
FROM t ALIGN '1h' by () FILL NULL;
```
The user explicitly specifies that the aggregation key is empty. In this case, there is no aggregation key.  All data will be aggregated into a group, which is equivalent to using a random constant as the aggregation key. Therefore, in this case, the constant 1 is used directly as the aggregation key. The sql is rewrite by sqlparser to:
```sql
SELECT 
sum(metrics) RANGE '10m' FILL MAX
FROM t ALIGN '1h' by (1) FILL NULL;
```
The work is mainly done by sqlparser. Here we just simply replace the version of sqlparser and add test cases. …
=> feat: enable empty range by

Cargo.lock, Cargo.toml, src/common/decimal/Cargo.toml, src/common/decimal/src/decimal128.rs, src/common/decimal/src/error.rs, src/common/decimal/src/lib.rs
implement `decimal128` type in `common`.
#2682
=> feat: decimal128 type in common

tests/runner/src/env.rs, tests/runner/src/main.rs
Add `--server-addr` in sqlness runner, we can run the tests like:
```console
cargo sqlness --server-addr 127.0.0.1:14001 --test-filter standalone
cargo sqlness --server-addr 127.0.0.1:24001 --test-filter distributed
```
closes https://github.com/GreptimeTeam/greptimedb/issues/2635
=> feat: add '--server-addr' in sqlness runner

docs/rfcs/2023-11-03-inverted-index.md
[rendered](https://github.com/GreptimeTeam/greptimedb/blob/6163cb939aa214fa3ca5bd7d4b39a0779fb72f86/docs/rfcs/2023-11-03-inverted-index.md)
=> docs: rfc of inverted index for SST file

src/cmd/src/cli/export.rs
This pr is a cr issue fix to #2610
=> chore: export tool minor refactor

Cargo.lock, src/cmd/Cargo.toml, src/cmd/src/frontend.rs, src/cmd/src/options.rs, src/cmd/src/standalone.rs, src/frontend/src/error.rs, src/frontend/src/frontend.rs, src/frontend/src/instance.rs, src/frontend/src/server.rs, tests-integration/Cargo.toml, tests-integration/src/standalone.rs, tests-integration/src/test_util.rs, tests-integration/tests/http.rs
Fixes #2584.
This PR makes frontend http-server
* return frontend config when running distributed mode
* return standalone config when running standalone mode
close #2584
=> fix: `GET: /config` return all configurations when running standalone

src/metric-engine/src/test_util.rs
Fix this pipeline https://github.com/GreptimeTeam/greptimedb/actions/runs/6764676664/job/18383347651
Which fails with
```
--- TRY 4 STDERR:        metric-engine engine::test::create_metadata_region ---
thread 'engine::test::create_metadata_region' panicked at src\metric-engine\src\engine.rs:304:61:
called `Result::unwrap()` on an `Err` value: Os { code: 123, kind: InvalidFilename, message: "The filename, directory name, or volume label syntax is incorrect." }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
=> fix: don't assert path under windows

src/operator/src/statement/ddl.rs
This fixes https://github.com/GreptimeTeam/greptimedb/issues/2632.
=> fix: created_on of RawTableMeta should be init with Utc::now

src/cmd/src/standalone.rs
`plugins::setup_frontend_plugins` MUST BE supplied with mut reference
=> fix(plugin): setup frontend plugin with mut reference

src/common/meta/src/rpc/router.rs, src/meta-srv/src/region/lease_keeper.rs, src/meta-srv/src/region/lease_keeper/mito.rs, src/meta-srv/src/region/lease_keeper/utils.rs
I realized we can't simply retain active leader regions and also need to find out the downgraded leader regions.
1. Refactor `find_staled_leader_regions`; now, it can find out the downgraded leader regions.
2. Add `find_staled_follower_regions`, returning upgradable and closable regions.
#2700
=> refactor: refactor region lease keeper

config/metasrv.example.toml, src/cmd/src/metasrv.rs, src/meta-srv/src/failure_detector.rs, src/meta-srv/src/handler/failure_handler.rs, src/meta-srv/src/handler/failure_handler/runner.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/metasrv/builder.rs, tests/conf/datanode-test.toml.template
This closes https://github.com/GreptimeTeam/greptimedb/issues/1738.
Although, `PhiAccrualFailureDetector` seems a deep internal struct. Perhaps we can evaluate if we want to config it in metasrv level.
=> feat: make PhiAccrualFailureDetector configurable 

Cargo.lock, Cargo.toml, src/datanode/src/alive_keeper.rs, src/meta-srv/src/handler/region_lease_handler.rs, src/store-api/src/region_engine.rs
Make heartbeat response contain region role
#2700
close #2639
=> refactor: heartbeat response contains region role

config/datanode.example.toml, src/cmd/src/datanode.rs, src/datanode/src/config.rs, src/mito2/src/compaction.rs, src/mito2/src/compaction/twcs.rs, src/mito2/src/config.rs, src/mito2/src/flush.rs, src/mito2/src/worker/handle_alter.rs, src/mito2/src/worker/handle_compaction.rs, src/mito2/src/worker/handle_flush.rs, src/storage/src/config.rs, src/storage/src/flush.rs, src/storage/src/flush/scheduler.rs, src/storage/src/region/writer.rs, tests-integration/tests/http.rs
This PR enforces all config values for SST writer buffer size to the value in `MitoConfig`. The hard coded config may result `EntityTooSmall` error raised by S3.
fixes #2662
=> fix: unify all sst_write_buffer_size usage

src/query/src/dist_plan/analyzer.rs, src/query/src/query_engine/state.rs
Run `SimplifyExpressions` before the dist planner to distribute more plans.
refer to https://github.com/GreptimeTeam/greptimedb/issues/2720
=> feat: run dist planner after simplify expression rule

src/operator/src/statement.rs, src/operator/src/statement/describe.rs, src/sql/src/statements/describe.rs, src/sql/src/util.rs, tests/cases/standalone/common/create/create_database.result, tests/cases/standalone/common/create/create_database.sql, tests/cases/standalone/common/show/show_databases_tables.result
This patch fixes https://github.com/GreptimeTeam/greptimedb/issues/2595.
~~It's still a quick fix but not a hack. I'm going to go through other similar code path and trying to add a test if possible. But submit this PR for early review if any.~~
=> fix: store raw objname internally

src/common/meta/src/key.rs, src/common/meta/src/rpc/router.rs, src/meta-srv/src/procedure/region_failover/deactivate_region.rs, src/meta-srv/src/procedure/region_failover/update_metadata.rs
This PR will downgrade the failed region before closing during the failover procedure.
#2700
close #2638
=> feat: downgrade failed region before closing

src/servers/src/http.rs, src/servers/src/http/prometheus.rs, src/servers/src/metrics.rs, tests-integration/tests/http.rs
Implement `format_query` endpoint.
```
curl -i 'http://localhost:4000/v1/prometheus/api/v1/format_query?query=foo/bar'
HTTP/1.1 200 OK
content-type: application/json
content-length: 39
date: Fri, 10 Nov 2023 08:56:47 GMT
{"status":"success","data":"foo / bar"}
```
This closes https://github.com/GreptimeTeam/greptimedb/issues/1540.
=> feat: support prometheus format_query endpoint

Cargo.lock, Cargo.toml, src/puffin/Cargo.toml, src/puffin/src/blob_metadata.rs, src/puffin/src/file_metadata.rs, src/puffin/src/lib.rs
Init Puffin crate; add `BlobMetadata` and `FileMetadata`
extract from #2721
https://github.com/GreptimeTeam/greptimedb/issues/2705
=> feat: introduce metadata struct of puffin

src/datatypes/src/schema.rs, src/datatypes/src/schema/constraint.rs, src/sql/src/error.rs, src/sql/src/statements.rs, tests/cases/standalone/common/create/current_timestamp.result, tests/cases/standalone/common/create/current_timestamp.sql
Table created with the following SQL cannot run with `SHOW CREATE`
```sql
CREATE TABLE IF NOT EXISTS cpu_metrics3 (
hostname STRING,
environment STRING,
usage_user DOUBLE,
usage_system DOUBLE,
usage_idle DOUBLE,
ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
TIME INDEX(ts),
PRIMARY KEY(hostname, environment)
);
```
Error:
```
pg:j2qY4ErSyTkM93HyanOBl400@i9ulpzu4mdgf/q6dj4up5mmriweak_flowers-public=> show create table "cpu_metrics3";
error: pq: XX000: sql parser error: Expected (, found: EOF
pg:j2qY4ErSyTkM93HyanOBl400@i9ulpzu4mdgf/q6dj4up5mmriweak_flowers-public=> show create table cpu_metrics3;
error: pq: XX000: sql parser error: Expected (, found: EOF …
```
=> fix: Normalize default constrain fn name

src/mito2/src/config.rs
This sanitizer cannot help when `num_cpus / 2` == 0. Add an additional `.max()` to avoid this.
=> fix: handle if num_cpus / 2 == 0

Cargo.lock, Cargo.toml
The other two, `atty` is in clap 3.x, `lexical` is in mysql-common which is used by opensrv-mysql, will be upgrade separately.
=> fix: upgrade dependency to resolve github security alert

Cargo.lock, src/common/telemetry/Cargo.toml, src/common/telemetry/src/logging.rs
Remove `bunyan` format layer for output docs. JSON formatted logs are hard to use on both loki and log file. Plain text is clearer in both cases.
=> feat: simplify log file output by removing bunyan layer

src/mito2/src/compaction/output.rs, src/mito2/src/error.rs, src/mito2/src/read/seq_scan.rs
This PR temporarily ignores files not found during compaction. We use this to workaround the issue caused by #2746
https://github.com/GreptimeTeam/greptimedb/issues/2746
=> feat: Ignore file not found error temporarily while compacting files

src/metric-engine/src/data_region.rs, src/metric-engine/src/engine.rs, src/metric-engine/src/error.rs, src/metric-engine/src/metadata_region.rs, src/metric-engine/src/metrics.rs, src/metric-engine/src/test_util.rs, src/store-api/src/region_request.rs
Support to alter logical region. And
*A spectre is haunting in my mind -- the spectre of Table Engine. Some Powers of this PR have entered into a holy alliance to exorcise this spectre*
#2070
=> feat: alter logical region in metric region

src/mito2/src/engine/basic_test.rs, src/mito2/src/sst/parquet/writer.rs
This PR disables the dictionary page for timestamp columns since timestamp values seldom repeat and dictionary encoding does nothing but increases SST file size. In some cases, the dictionary page size of timestamp columns will be larger than data page size.
=> perf: disable dictionary of ts columns

Cargo.lock, Cargo.toml, src/puffin/Cargo.toml, src/puffin/src/lib.rs, src/puffin/src/partial_reader.rs, src/puffin/src/partial_reader/async.rs, src/puffin/src/partial_reader/position.rs, src/puffin/src/partial_reader/sync.rs
`PartialReader` is used to read a contiguous segment of bytes from a resource. For the blob format, by providing the offset and size of the blob, one can utilize `PartialReader` to read the content of the Blob.
This PR introduces `PartialReader` and implements `std::io::Read`, `std::io::Seek`, `futures::io::AsyncRead`, and `futures::io::AsyncSeek` for it.
#2705
=> feat(puffin): add partial reader

src/meta-srv/src/procedure/region_failover.rs, src/meta-srv/src/procedure/region_migration.rs, src/meta-srv/src/procedure/region_migration/migration_end.rs, src/meta-srv/src/procedure/region_migration/migration_start.rs, src/meta-srv/src/procedure/utils.rs
Add the skeleton of region migration procedure.
=> feat: add region migration procedure skeleton

src/datatypes/src/vectors/decimal.rs
my bad implement about iterator trait leads that the `iter_data()` function runs forever.
=> fix: iterator bad implement

Cargo.lock, Makefile, src/common/telemetry/src/logging.rs, src/file-engine/Cargo.toml, src/file-engine/src/lib.rs, src/servers/Cargo.toml
This PR fixes compiler errors under non-default features.
It also enables `--all-features` in CI checks.
=> fix: compiler errors under non-default features

src/meta-srv/src/handler/region_lease_handler.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/metasrv/builder.rs, src/meta-srv/src/region/lease_keeper.rs
1. add OpeningRegionKeeper
2. grant lease to opening regions
#2700
=> feat: grant lease to opening regions

src/mito2/src/memtable/time_series.rs
Correct memtable scan cost metrics.
The local variable inside the for loop shadows the start instant outside. I forgot to remove it in the PR introducing iter metrics.
=> fix: correct memtable cost

src/servers/src/grpc/greptime_handler.rs, src/servers/src/grpc/region_server.rs, src/servers/src/http.rs, src/servers/src/mysql/handler.rs, src/servers/src/mysql/writer.rs
This PR fixes the issue that our MySQL handler may not print the error message to users.
It outputs OK but the query actually fails if the error is an internal error.
```
Query OK (0.02 sec)
```
Now users can see the internal error message.
```
ERROR 1815 (HY000): Internal error: 1003
```
=> fix: mysql writer does not print error message in some cases

src/servers/src/error.rs, src/servers/src/http.rs, src/servers/src/http/handler.rs, src/servers/src/http/script.rs, src/servers/tests/http/http_handler_test.rs
Use `output_msg` instead of `Display` to show error messages in HTTP API.
Also, logs the error if `should_log_error` returns true.
=> feat: improve http error message

Cargo.lock, Cargo.toml
Bump greptimedb version v0.4.3
=> chore: bump greptimedb version v0.4.3

src/meta-srv/src/error.rs, src/meta-srv/src/procedure/region_migration.rs, src/meta-srv/src/procedure/region_migration/downgrade_leader_region.rs, src/meta-srv/src/procedure/region_migration/migration_end.rs, src/meta-srv/src/procedure/region_migration/migration_start.rs, src/meta-srv/src/procedure/region_migration/open_candidate_region.rs, src/meta-srv/src/procedure/region_migration/test_util.rs
Add migration start step
- If the expected leader region has been opened on `to_peer`, go to the `MigrationEnd` state.
- If the candidate region has been opened on `to_peer`, go to the `DowngradeLeader` state.
- Else go to the `OpenCandidateRegion` state.
**Behaviors:**
Abort(non-retry):
- TableRoute is not found.
- RegionRoute is not found.
- Leader peer of RegionRoute is not found.
Retry:
- Failed to retrieve the metadata of table.
#2700
=> feat: add migration start step

src/sql/src/statements/create.rs, tests/cases/standalone/common/truncate/truncate.result, tests/cases/standalone/common/truncate/truncate.sql
=> fix: fix exits typos

src/meta-srv/src/error.rs, src/meta-srv/src/procedure/region_migration.rs, src/meta-srv/src/procedure/region_migration/open_candidate_region.rs, src/meta-srv/src/procedure/region_migration/test_util.rs, src/meta-srv/src/region/lease_keeper.rs
This step opens the candidate region on `to_peer`.
**Behaviors:**
Abort(non-retry):
- Table Info is not found.
- The Datanode is unreachable(e.g., Candidate pusher is not found).
- Unexpected instruction reply.
- Another procedure is opening the candidate region.
Retry:
- Exceeded deadline of open instruction.
- Datanode failed to open the candidate region.
#2700 
Waits for #2756
=> feat: add open candidate region step

src/datatypes/src/vectors.rs
add test for vector `data_type()` which implement in `MutableVector` trait
Closes #2754
=> feat: unit test for mutable vector

Cargo.lock, src/meta-client/src/client.rs, src/meta-srv/Cargo.toml, src/meta-srv/src/bootstrap.rs, src/meta-srv/src/error.rs, src/meta-srv/src/handler/collect_stats_handler.rs, src/meta-srv/src/handler/mailbox_handler.rs, src/meta-srv/src/handler/node_stat.rs, src/meta-srv/src/keys.rs, src/meta-srv/src/procedure/region_failover.rs, src/meta-srv/src/procedure/region_failover/failover_start.rs, src/meta-srv/src/selector.rs, src/meta-srv/src/selector/common.rs, src/meta-srv/src/selector/lease_based.rs, src/meta-srv/src/selector/load_based.rs, src/meta-srv/src/selector/weight_compute.rs, src/meta-srv/src/selector/weighted_choose.rs, src/meta-srv/src/table_meta_alloc.rs, tests-integration/src/grpc.rs, tests-integration/src/instance.rs, tests-integration/tests/region_failover.rs
This pr adds random weighted choose in load based selector.
Main changes:
1. Modified the definition of `Selector`.
2. Add `WeightedChoose` trait and default implemention `RandomWeightedChoose`.
3. Add weight compute by region number.
=> feat: add random weighted choose in load_based selector

Cargo.lock, src/cmd/Cargo.toml, src/cmd/src/datanode.rs, src/cmd/src/frontend.rs
Since the currently used clap version is 3.x, which is already outdated for a long time, it will be updated to the latest 4.4.8.
Because the `multiple` is deprecated,  I use `num_args = 1..` to replace.
[#2742](https://github.com/GreptimeTeam/greptimedb/issues/2742)
=> build(cmd): upgrade clap to 4.x

docker/dev-builder/ubuntu/Dockerfile-18.10
ci: add ubuntu:18.10 dev-builder for using old version glibc(>=2.28)
=> ci: add ubuntu:18.10 dev-builder for using old version glibc(>=2.28)

src/meta-srv/src/handler.rs, src/meta-srv/src/handler/failure_handler.rs, src/meta-srv/src/handler/node_stat.rs, src/meta-srv/src/handler/region_lease_handler.rs, src/meta-srv/src/selector/weight_compute.rs
bring back `inactive_region_ids`
=> fix: bring back `inactive_region_ids`

.cargo/config.toml, .github/workflows/apidoc.yml, .github/workflows/develop.yml, .github/workflows/nightly-ci.yml, .github/workflows/release.yml, Cargo.lock, Cargo.toml, rust-toolchain.toml, src/datatypes/src/vectors/binary.rs, src/meta-srv/src/procedure/region_migration.rs
* https://github.com/etcdv3/etcd-client/pull/68
* https://github.com/GreptimeTeam/greptimedb/pull/2734#issuecomment-1813785955
Following I'll create a few follow-ups to improve the code and prepare to add chroot for etcd connection.
=> build: upgrade etcd-client to 0.12.2

src/metric-engine/src/metadata_region.rs, src/mito2/src/engine/projection_test.rs, src/store-api/src/storage/requests.rs
Remove yet another overdesign. 
Remove the sequence number from `ScanRequest`. We won't be using it in the near future.
=> refactor: remove sequence number from ScanRequest

src/common/meta/src/key.rs, src/meta-srv/src/procedure/region_failover/deactivate_region.rs, src/meta-srv/src/procedure/region_migration.rs, src/meta-srv/src/procedure/region_migration/migration_start.rs, src/meta-srv/src/procedure/region_migration/update_metadata.rs
Add update metadata step for downgrading leader region.
**Behaviors:**
Abort(non-retry):
- TableRoute is not found.
Retry:
- Failed to update [TableRouteValue](common_meta::key::table_region::TableRegionValue).
- Failed to retrieve the metadata of table.
**Notes:**
About the failure of updating the [TableRouteValue](common_meta::key::table_region::TableRegionValue):
- There may be another [RegionMigrationProcedure](crate::procedure::region_migration::RegionMigrationProcedure) that is executed concurrently for **other region**.  It will only update **other region** info. Therefore, It's safe to retry after failure.
- There is no other DDL procedure executed concurrently for …
=> feat: add update metadata step for downgrading leader region

Cargo.lock, src/common/time/src/datetime.rs, src/common/time/src/timestamp.rs, src/servers/Cargo.toml, src/servers/src/mysql/writer.rs, tests-integration/Cargo.toml, tests-integration/tests/sql.rs
Fixes timestamp encoding for mysql binary protocol as described in #2796
Fixes #2796
=> fix: correct mysql timestamp encoding for binary protocol

src/datatypes/src/vectors/primitive.rs, src/mito2/src/read.rs
This PR adds a field `put_only` to indicate the batch only contains put operations. In this case, `filter_deleted()` can simply return.
=> feat: add put_only field to skip filtering deletion

src/common/meta/src/kv_backend/chroot.rs, tests-integration/fixtures/etcd/docker-compose-standalone.yml
This follows up #2734 as @MichaelScofield suggested.
=> chore: internal ChrootKvBackend refactor and test

config/standalone.example.toml, src/common/telemetry/src/logging.rs
support sample ratio in trace, add config `tracing_sample_ratio`
- support sample ratio in trace, add config `tracing_sample_ratio`
- fix error config of `manifest_compress_type` in standalone.example.toml
=> feat: support sample ratio in trace

src/mito2/src/engine/basic_test.rs, src/mito2/src/request.rs, src/mito2/src/test_util.rs, tests/cases/standalone/common/delete/delete_non_null.result, tests/cases/standalone/common/delete/delete_non_null.sql
Allow missing fields in delete requests. Before this PR, the engine always checks whether a field column has a suitable default value.
This PR also adds some tests for this case.
https://github.com/GreptimeTeam/greptimedb/issues/2813
=> fix(mito): do not check nullability of fields in delete requests

src/common/meta/Cargo.toml, src/common/meta/src/ddl_manager.rs, src/common/procedure/Cargo.toml, src/common/procedure/src/local.rs, src/frontend/src/error.rs, src/frontend/src/instance.rs, src/meta-srv/src/error.rs, src/meta-srv/src/metasrv/builder.rs, tests-integration/src/standalone.rs
1. Fix procedure loaders not found issue.
2. Add unit test to ensure all loaders are registered.
fix #2823
=> fix: fix procedure loaders not found issue

src/common/procedure/Cargo.toml
=> fix: fix broken CI

src/cmd/src/metasrv.rs, src/cmd/src/standalone.rs
Add `--data-home` / `-d` arg to `greptime [standalone|metasrv] start` command. One can change the standalone, datanode and metasrv instance's working directory from command line from now on.
=> feat: add  arg to standalone start command

Cargo.lock, Cargo.toml
=> chore: bump version to 0.4.4

src/common/meta/src/instruction.rs, src/datanode/src/heartbeat/handler.rs, src/meta-srv/src/procedure/region_migration.rs, src/meta-srv/src/procedure/region_migration/downgrade_leader_region.rs, src/meta-srv/src/procedure/region_migration/migration_start.rs, src/meta-srv/src/procedure/region_migration/open_candidate_region.rs, src/meta-srv/src/procedure/region_migration/test_util.rs, src/meta-srv/src/procedure/region_migration/update_metadata.rs, src/meta-srv/src/procedure/region_migration/upgrade_candidate_region.rs
The `DowngradeLeaderRegion` step downgrades a leader region and utilizes the region lease deadline to ensure the operation always succeeds.
#2700
=> feat: add downgrade leader region step

src/common/meta/src/key.rs, src/meta-srv/src/error.rs, src/meta-srv/src/lib.rs, src/meta-srv/src/procedure/region_failover/update_metadata.rs, src/meta-srv/src/procedure/region_migration.rs, src/meta-srv/src/procedure/region_migration/migration_start.rs, src/meta-srv/src/procedure/region_migration/open_candidate_region.rs, src/meta-srv/src/procedure/region_migration/test_util.rs, src/meta-srv/src/procedure/region_migration/update_metadata.rs, src/meta-srv/src/procedure/region_migration/update_metadata/downgrade_leader_region.rs, src/meta-srv/src/procedure/region_migration/update_metadata/upgrade_candidate_region.rs
Add update metadata step for upgrading candidate region.
It sets the candidate peer as the `leader_peer` and removes the candidate region from `follower_peers` if any.
**Behaviors:**
Abort(non-retry):
- TableRoute or RegionRoute is not found.
Typically, it's impossible, there is no other DDL procedure executed concurrently for the current table.
Retry:
- Failed to update `TableRouteValue`
- Failed to retrieve the metadata of the table.
#2700
=> feat: add update metadata step for upgrading candidate region

src/promql/src/error.rs, src/promql/src/planner.rs, tests/cases/standalone/common/promql/set_operation.result, tests/cases/standalone/common/promql/set_operation.sql
implement `AND` and `UNLESS` for PromQL.
- #1042
=> feat: implement PromQL set op AND/UNLESS

src/catalog/src/information_schema/columns.rs, src/datatypes/src/data_type.rs, src/datatypes/src/types/binary_type.rs, src/datatypes/src/types/boolean_type.rs, src/datatypes/src/types/cast.rs, src/datatypes/src/types/date_type.rs, src/datatypes/src/types/datetime_type.rs, src/datatypes/src/types/decimal_type.rs, src/datatypes/src/types/dictionary_type.rs, src/datatypes/src/types/duration_type.rs, src/datatypes/src/types/interval_type.rs, src/datatypes/src/types/list_type.rs, src/datatypes/src/types/null_type.rs, src/datatypes/src/types/primitive_type.rs, src/datatypes/src/types/string_type.rs, src/datatypes/src/types/time_type.rs, src/datatypes/src/types/timestamp_type.rs, src/query/src/sql.rs, src/servers/src/http.rs, src/store-api/src/metadata.rs
refactor the `name` function return type from `&str` to `String`, 
and we can print `decimal(10, 6)` or some nested type info such as `List<Int64>`, `List<Dictionary<Int32, String>>` etc.
```sql
create table test(
val decimal(10,6),
ts timestamp time index,
);
describe table test;
+--------+----------------------+------+------+---------+---------------+
| Column | Type                 | Key  | Null | Default | Semantic Type |
+--------+----------------------+------+------+---------+---------------+
| val    | Decimal(10, 6)       |      | YES  |         | FIELD         |
| ts     | TimestampMillisecond | PRI  | NO   |         | TIMESTAMP     | …
```
=> refactor: DataType name function

README.md
The docs of getting started will be updated soon,  Please wait for https://github.com/GreptimeTeam/docs/pull/686
=> docs: update getting-started document link

src/mito2/src/read/merge.rs
This PR removes the `BatchMerger` from the `MergeReader` and doesn't concat batches in the `MergerReader` anymore.
It always returns the `batch` if it is not empty after `filter_deleted()`. This can slightly reduce the overhead in the merge phase if each batch (or series) has a small amount of rows.
=> feat: do not concat batches in MergeReader

src/common/meta/src/kv_backend/etcd.rs, src/datanode/src/alive_keeper.rs, src/datanode/src/heartbeat.rs, src/datanode/src/metrics.rs, src/meta-srv/src/handler/region_lease_handler.rs, src/meta-srv/src/metrics.rs, src/meta-srv/src/region/lease_keeper.rs, src/meta-srv/src/service/store/cached_kv.rs
Add some logs and metrics for heartbeat handling
=> chore: add logs and metrics

src/common/meta/src/distributed_time_constants.rs, src/common/meta/src/instruction.rs, src/datanode/src/heartbeat/handler.rs, src/meta-srv/src/procedure/region_migration/downgrade_leader_region.rs, src/meta-srv/src/procedure/region_migration/open_candidate_region.rs, src/meta-srv/src/procedure/region_migration/update_metadata.rs, src/meta-srv/src/procedure/region_migration/upgrade_candidate_region.rs
Add upgrade candidate region step:
It upgrades a candidate region to a leader region with a retry; if all retry fails, it will rollback the metadata.
**Behaviors:**
Retry:
- If `require_ready` is true, but the candidate region returns `ready` is false.
- [MailboxTimeout](error::Error::MailboxTimeout).
Abort:
- The candidate region doesn't exist.
- [PusherNotFound](error::Error::PusherNotFound), The datanode is unreachable.
- [PushMessage](error::Error::PushMessage), The receiver is dropped.
- [MailboxReceiver](error::Error::MailboxReceiver), The sender is dropped without sending (impossible).
- [UnexpectedInstructionReply](error::Error::UnexpectedInstructionReply) …
=> feat: add upgrade candidate region step

tests/cases/standalone/common/types/decimal/decimal_ops.result, tests/cases/standalone/common/types/decimal/decimal_ops.sql
Sort result of multiple lines queries
=> fix: sort result of sqlness case decimal_ops

src/common/meta/src/heartbeat/handler.rs, src/common/meta/src/heartbeat/mailbox.rs, src/datanode/Cargo.toml, src/datanode/src/heartbeat/handler.rs, src/datanode/src/lib.rs, src/datanode/src/region_server.rs, src/datanode/src/tests.rs, src/mito2/src/test_util.rs
1. Handle the downgrade region instruction
2. Add tests for RegionHeartbeatResponseHandler.
#2700
=> feat: handle the downgrade region instruction

Cargo.lock, src/datanode/Cargo.toml, src/datanode/src/store.rs, src/object-store/Cargo.toml, src/object-store/src/layers.rs, src/object-store/src/layers/prometheus.rs, tests-integration/Cargo.toml
Use self implementation of `PrometheusMetricsLayer` to replace `opendal`'s `PrometheusLayer` to solve the crash caused by repeated registration of metrics under multiple `object_store`s ( solve by use  `lazy_static`), and add the `opendal_` prefix to the metric.
=> fix: replace opendal `PrometheusLayer`

src/sql/src/statements.rs, tests/cases/standalone/common/alter/add_col.result
Fixed `alter table [table] add column [new_column] [type] PRIMARY KEY` can't work as expected. The new column is not added as `tag` semantic type.
=> fix: add new column as primary key can't work

src/promql/src/error.rs
Change status code of error types that are caused by invalid input. The previous `Internal` code will prevent it from being unwrap to user.
=> chore: tweak status code of promql errors

config/datanode.example.toml, config/standalone.example.toml
This PR adds examples of custom storage options.
Related to #919.
=> chore: update storage config example

src/servers/tests/mysql/mysql_server_test.rs
As @tisonkun mention #1385 is not reproducible in current HEAD. I bisects the history and find it's already fixed in https://github.com/GreptimeTeam/greptimedb/pull/1677. This PR re-enables the ignored case `test_query_prepared` due to that bug.
- Closes #1385
=> fix: re-enable ignored case test_query_prepared

src/common/meta/src/key/table_route.rs, src/meta-srv/src/procedure/region_migration.rs, src/meta-srv/src/procedure/region_migration/downgrade_leader_region.rs, src/meta-srv/src/procedure/region_migration/migration_abort.rs, src/meta-srv/src/procedure/region_migration/migration_end.rs, src/meta-srv/src/procedure/region_migration/migration_start.rs, src/meta-srv/src/procedure/region_migration/open_candidate_region.rs, src/meta-srv/src/procedure/region_migration/test_util.rs, src/meta-srv/src/procedure/region_migration/update_metadata.rs, src/meta-srv/src/procedure/region_migration/update_metadata/downgrade_leader_region.rs, src/meta-srv/src/procedure/region_migration/update_metadata/rollback_downgraded_region.rs, src/meta-srv/src/procedure/region_migration/update_metadata/upgrade_candidate_region.rs, src/meta-srv/src/procedure/region_migration/upgrade_candidate_region.rs
1. Refactors the `State` of the RegionMigration.
2. Add some basic region migration tests. 
And some remaining tests will be added in the next PR.
#2700
=> test: add tests for region migration procedure

src/servers/src/mysql/federated.rs
This closes https://github.com/GreptimeTeam/greptimedb/issues/2514.
=> chore: ignore MySQL client sent SELECT $$

.github/workflows/nightly-ci.yml
The same to nightly-build.yml.
=> ci: prevent running nightly CI in forks

src/index/src/inverted_index/error.rs, src/index/src/inverted_index/format.rs, src/index/src/inverted_index/format/reader.rs, src/index/src/inverted_index/format/reader/blob.rs, src/index/src/inverted_index/format/writer.rs, src/index/src/inverted_index/format/writer/blob.rs, src/index/src/inverted_index/format/writer/single.rs
Add format writer, accepts stream of values.
#2705
=> feat(inverted_index.format): add writer

.github/workflows/nightly-funtional-tests.yml
Forks cannot reach the secrets in use.
=> ci: prevent running nightly FT in forks

Cargo.toml
Change the default debug level of `release` and `dev` profile to `1`. This change can cut the binary size by half (from 2.1 GB to 1.0 GB)
The panic stack still contains the necessary info under `release` profile
=> feat: set default debug level of release and dev profiles to 1

src/catalog/src/information_schema.rs, src/client/src/database.rs, src/client/src/region.rs, src/common/recordbatch/src/lib.rs, src/frontend/src/server.rs, src/mito2/src/read/seq_scan.rs, src/query/src/dist_plan/merge_scan.rs, src/servers/src/http.rs, src/servers/src/query_handler/grpc.rs, src/servers/src/query_handler/sql.rs, tests-integration/src/test_util.rs
From https://github.com/GreptimeTeam/greptimedb/issues/1665:
>Both `Adaptor` and `Adapter` are used in our codebase. E.g., `DfAccumulatorAdaptor`, `ServerSqlQueryHandlerAdaptor`, `ReadAdapter` and `ProcedureAdapter`. We should unify our naming to avoid ambiguities
Given there are many `*Adapter` and only a few `*Adaptor`, I renamed all `*Adaptor` to `*Adapter` except `DfAccumulatorAdaptor` which has another `or` in `Accumulator`
Closes https://github.com/GreptimeTeam/greptimedb/issues/1665
=> style: rename `*Adaptor` to `*Adapter`

src/sql/src/parser.rs, tests-integration/src/tests/promql_test.rs, tests/cases/standalone/common/select/dummy.result, tests/cases/standalone/common/select/dummy.sql
Because some bug in sqlparser,  sql like `SELECT foo, bar, FROM baz` with tailing commas will be wrongly parse to `SELECT foo, bar, FROM AS baz`
Enable `trailing_commas` in sqlparser to avoid such error.
=> fix: support tailing commas in SQL

src/servers/src/mysql/handler.rs
before: (in server)
2023-12-12T11:39:05.369596Z  WARN servers::mysql::server: Internal error occurred during query exec, server actively close the channel to let client try next time err=0: Expected type: Timestamp(Millisecond(TimestampMillisecondType)), actual: MYSQL_TYPE_VAR_STRING, at src/servers/src/mysql/helper.rs:168:14
after: (in client)
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: err: Expected type: Timestamp(Millisecond(TimestampMillisecondType)), actual: MYSQL_TYPE_VAR_STRING, params: (Value(Bytes([49])), MYSQL_TYPE_VAR_STRING),(Value(Int(1)), MYSQL_TYPE_LONG),(Value(Int(1)), MYSQL_TYPE_LONG),(Value(Int(1)), MYSQL_TYPE_LONG),(Value(Int(1)), …
=> fix: return error to client if prepare stmt param not match

tests/cases/standalone/common/types/interval/interval.result, tests/cases/standalone/common/types/interval/interval.sql
open `date` - `interval` test case which can work now.
Closes #2319 .
=> fix: `date` - `interval` sqlness

src/meta-srv/src/procedure/region_migration.rs, src/meta-srv/src/procedure/region_migration/migration_start.rs, src/meta-srv/src/procedure/region_migration/open_candidate_region.rs, src/meta-srv/src/procedure/region_migration/test_util.rs
1. Add flow test for open candidate region with retryable error
2. Add flow test for upgrade candidate retry failed
3. Add flow test for upgrade candidate with retry
#2700
=> test: add more tests for region migration procedure

src/datatypes/src/scalars.rs, src/datatypes/src/vectors.rs, src/datatypes/src/vectors/binary.rs, src/datatypes/src/vectors/boolean.rs, src/datatypes/src/vectors/decimal.rs, src/datatypes/src/vectors/list.rs, src/datatypes/src/vectors/null.rs, src/datatypes/src/vectors/primitive.rs, src/datatypes/src/vectors/string.rs
main changes:
- add new method named `finish_cloned` in `ScalarVectorBuilder` trait
- add new method named `to_vector_cloned` in `MutableVector` trait.
- some unit tests
=> feat: builder to vector without resetting

src/query/src/range_select/plan.rs
Use linear interpolation to implement range `LINEAR` fill strategy
The previous `LINEAR` strategy of range fill was implemented using the average value. Only the data before and after an null data point are non-empty, and the value of this point will be filled with the average of the two numbers. Now the implementation is changed to linear interpolation. As long as there are more than two non-empty data points in the entire time series, all null data points can be filled in using linear interpolation.
=> fix: use linear interpolation to implement range LINEAR fill strategy

Cargo.lock, src/servers/Cargo.toml, src/servers/src/postgres/handler.rs, src/servers/src/tls.rs, src/servers/tests/postgres/mod.rs
This patch upgrades rustls library family to 0.22, together with pgwire and opensrv-mysql.
=> feat: upgrade rustls library family, opensrv-mysql and pgwire

src/common/error/src/status_code.rs, src/servers/src/http.rs, src/servers/src/http/authorize.rs, src/servers/tests/http/authorize.rs, src/servers/tests/http/influxdb_test.rs
1. change `AsyncRequireAuthorizationLayer` to `middleware::from_fn_with_state` so it's now possible to construct resp body
2. return json body under status code 401 just like other http response
3. minor: change `unsupported` error to debug log level
=> chore: return json body under http status 401

src/script/src/python/ffi_types/pair_tests/sample_testcases.rs
fix a wrong testcase in which in will fail if Python is installed without pyarrow
=> test: fix a wronged test script

Cargo.lock, Cargo.toml, src/api/src/helper.rs, src/common/decimal/src/decimal128.rs, src/common/grpc/src/select.rs, src/common/time/src/interval.rs, src/operator/src/req_convert/common.rs
changes:
- interval typos.
- fix decimal128 and interval bit operations.
=> fix: typos and bit operations

src/query/src/range_select/plan_rewrite.rs, tests/cases/standalone/common/range/to.result, tests/cases/standalone/common/range/to.sql
`Calendar` as an `align to` option has the same effect as leave it empty. Such an option is useless and will cause confusion to users, so remove this option in here.
https://github.com/GreptimeTeam/greptimedb/issues/2894
=> fix!: remove range calendar as `To` option

Cargo.lock, src/mito2/Cargo.toml, src/mito2/src/sst/parquet/reader.rs, src/operator/Cargo.toml, src/operator/src/statement/copy_table_from.rs
Found that Writer in opendal implements `tokio::io::AsyncWrite`, we can remove those reduntant `.compat()`.
=> refactor: remove reduntant `.compat()`

.github/scripts/deploy-greptimedb.sh
When after [this pr](https://github.com/GreptimeTeam/helm-charts/pull/90) merge, not require so many parameters to helm install greptimedb cluster. `accessKeyId` and `secretAccessKey` located in `storage.credentials.accessKeyId`, `storage.credentials.secretAccessKey`.
=> refactor: greptimedb cluster sqlness test scripts

src/object-store/src/layers/prometheus.rs
When I call opendal blocking read api, it goes wrong.
owing to blocking read function `timer` lack of `Operation::BlockingRead.into_static()`
=> fix: blocking read timer lack of parameter

config/metasrv.example.toml
Fixed the link for selector type.
=> fix: wrong link for selector

src/common/grpc-expr/src/insert.rs, src/common/grpc-expr/src/util.rs
fix the bug because of `datatype_extension` missing.
=> fix: auto create datatype_extension missing

Cargo.lock, src/servers/Cargo.toml, src/servers/src/error.rs, src/servers/src/mysql/handler.rs, src/servers/src/mysql/helper.rs, tests-integration/tests/sql.rs
=> fix: correctly decode mysql timestamp binary value

config/metasrv.example.toml, src/meta-srv/src/selector.rs
=> chore: SelectorType use snake_case

src/datanode/src/datanode.rs, src/datanode/src/heartbeat/handler.rs, src/file-engine/src/region.rs, src/mito2/src/engine/alter_test.rs, src/mito2/src/engine/basic_test.rs, src/mito2/src/engine/open_test.rs, src/mito2/src/engine/parallel_test.rs, src/mito2/src/engine/truncate_test.rs, src/mito2/src/region/opener.rs, src/mito2/src/test_util.rs, src/mito2/src/worker/handle_open.rs, src/store-api/src/region_request.rs
The region migration will open the candidate region first(the engine opens the region without replaying the WAL, for now), then upgrade the candidate region to the leader region(catching up on the latest manifest and replaying the WAL).
BTW, the follower region does not automatically synchronize with the changes made to the leader region. The duration of the write-stop window during region migration will be reduced once this feature is implemented.
#2700
=> feat(mito): add `skip_wal_replay` option to OpenRegionRequest

Cargo.toml
Remove `debug = 1` of dev profile
=> chore: remove debug = 1 of dev profile

src/common/meta/src/ddl/alter_table.rs, src/common/meta/src/ddl/drop_table.rs, src/common/meta/src/ddl_manager.rs, src/common/meta/src/key.rs, src/common/meta/src/key/table_route.rs, src/meta-srv/src/procedure/region_failover/deactivate_region.rs, src/meta-srv/src/procedure/region_failover/update_metadata.rs, src/meta-srv/src/procedure/region_migration/migration_start.rs, src/meta-srv/src/procedure/region_migration/test_util.rs, src/meta-srv/src/procedure/region_migration/update_metadata/downgrade_leader_region.rs, src/meta-srv/src/procedure/region_migration/update_metadata/rollback_downgraded_region.rs, src/meta-srv/src/procedure/region_migration/update_metadata/upgrade_candidate_region.rs, src/meta-srv/src/selector/load_based.rs, src/partition/src/manager.rs, tests-integration/src/grpc.rs, tests-integration/src/instance.rs
make `TableRouteValue` an enum to add the variant of MetricsEngine table route
=> feat: MetricsEngine table route (part 1)

.github/workflows/user-doc-label-checker.yml
In order to catching the imapaction of the PRs to [user documentation](https://github.com/GreptimeTeam/docs/), label `Doc update required` or `Doc not needed` should be added before merging.
If the label `Doc update required` is added, the `doc-issue.yml` workflow will add a issue to docs repo.
=> ci: add user-doc label checker

src/cmd/src/standalone.rs, src/common/meta/src/ddl.rs, src/common/meta/src/ddl_manager.rs, src/common/meta/src/rpc/ddl.rs, src/frontend/src/instance/standalone.rs, src/meta-srv/src/table_meta_alloc.rs, tests-integration/tests/grpc.rs
make standalone table metadata allocator able to use explicitly set table id
=> feat: use explicitly set table id

src/table/src/predicate.rs
`prune_row_groups` and `prune_primary_key ` are unused.
=> refactor: remove unused code for pruning row groups

src/datanode/src/region_server.rs, src/metric-engine/src/engine.rs, src/mito2/src/engine.rs, src/mito2/src/engine/catchup_test.rs, src/mito2/src/engine/set_readonly_test.rs, src/mito2/src/error.rs, src/mito2/src/lib.rs, src/mito2/src/manifest/manager.rs, src/mito2/src/manifest/storage.rs, src/mito2/src/region.rs, src/mito2/src/region/opener.rs, src/mito2/src/request.rs, src/mito2/src/test_util.rs, src/mito2/src/worker.rs, src/mito2/src/worker/handle_catchup.rs, src/mito2/src/worker/handle_create.rs, src/mito2/src/worker/handle_open.rs, src/object-store/src/lib.rs, src/store-api/src/region_request.rs
Add CatchupRequest; it makes a readonly region to catch up to leader region changes.
#2700
=> feat: add CatchupRequest to engine

Cargo.lock, src/catalog/Cargo.toml, src/catalog/src/information_schema.rs, src/catalog/src/information_schema/memory_table/tables.rs, src/catalog/src/information_schema/table_names.rs, src/common/catalog/src/consts.rs, tests/cases/standalone/common/show/show_databases_tables.result, tests/cases/standalone/common/system/information_schema.result, tests/cases/standalone/common/system/information_schema.sql
Adds a new table `information_schema.build_info`:
```sql
> select * from information_schema.build_info;
+--------------------+------------------------------------------+------------------+-----------+-------------+
| git_branch         | git_commit                               | git_commit_short | git_dirty | pkg_version |
+--------------------+------------------------------------------+------------------+-----------+-------------+
| feature/build-info | 6e33e9921a89d8577d09f180cbe90b166e87628d | 6e33e99          | true      | 0.4.4       |
+--------------------+------------------------------------------+------------------+-----------+-------------+
1 row in set (0.09 sec) …
```
=> feat: adds build_info table

src/catalog/src/memory/manager.rs, src/common/catalog/src/consts.rs, src/common/meta/src/key.rs, tests-integration/src/tests/instance_test.rs, tests/cases/standalone/common/create/create_database.result, tests/cases/standalone/common/show/show_databases_tables.result
Fixes #2964 
This patch introduces a new built-in default schema as namespace of tables created by greptime applications. We have more information discussed in #2964 . In most cases, I think our user won't need to know about this schema.
=> feat: add a default internal schema

src/mito2/src/sst/parquet/reader.rs, src/mito2/src/sst/parquet/row_group.rs
support concurrently fetch page ranges.
now the policy is that if object store support blocking, use blocking read priorly, 
if not, use concurrently read.
Local PC: mac m2 16G RAM 512 SSD
[storage]
type = S3
region = minipc-0
root = "test-concurrent-read"
bucket = "test-bucket-0"
fetch parquet according to ranges in sequence use develop branch, and this branch is concurrent.
<meta charset="utf-8"><div data-page-id="EeuPdcXHro6ja0xzjflcsWBJn4b" data-docx-has-block-data="true"><div>
Query | Use Sequence Blocking Read（mean） | Use Concurrent Read（mean）
-- | -- | --
cpu-max-all-1 | 1089.73ms | 446.90ms
cpu-max-all-8 | 6287.86ms | 1792.10ms
double-groupby-5 | 4230.23ms | …
=> feat: support fetch ranges in concurrent

src/catalog/src/kvbackend/manager.rs, src/catalog/src/memory/manager.rs, src/common/meta/src/key.rs, tests/cases/standalone/common/system/information_schema.result, tests/cases/standalone/common/system/information_schema.sql
=> fix: duplicate information_schema

src/common/meta/src/instruction.rs, src/datanode/src/heartbeat/handler.rs, src/meta-srv/src/procedure/region_failover.rs, src/meta-srv/src/procedure/region_failover/activate_region.rs, src/meta-srv/src/procedure/region_migration/open_candidate_region.rs
add `skip_wal_replay` to OpenRegion instruction
#2700
=> feat: add `skip_wal_replay` to OpenRegion instruction

src/log-store/src/noop.rs, src/log-store/src/raft_engine/log_store.rs, src/mito2/src/error.rs, src/mito2/src/region_write_ctx.rs, src/mito2/src/wal.rs, src/mito2/src/worker/handle_write.rs, src/store-api/src/logstore.rs, src/store-api/src/logstore/entry.rs, src/store-api/src/logstore/namespace.rs
- Let the `LogStore::append_batch` method return a `last_entry_id` for each region. More specifically, it returns a `HashMap<u64, EntryId>` where the key is a region id while the value is the id of the entry, the last entry of the entries belong to the region, written into the log store.
- For `KafkaLogStore`, the returned entry id for each region is the kafka offset of the last entry belong to the region that are written into the log store. During replay, the passed-in entry id is interpreted to a kafka offset and used to fetch log entries exactly starting from the offset.
- For `RaftEngineLogStore`, the returned entry id for each region is identical with the passed-in …
=> refactor(remote_wal): entry id usage

src/cmd/src/metasrv.rs, src/meta-srv/src/bootstrap.rs, src/meta-srv/src/election/etcd.rs, src/meta-srv/src/lock/etcd.rs, src/meta-srv/src/metasrv.rs
When deploying multiple clusters, it's more convenient and cost-effective to re-use the same etcd cluster.
In this PR, I added `--store-key-prefix` which is specified by the admin in the metasrv to support that multiple metasrv instances can use the same etcd cluster without key confliction.
=> feat: add '--store-key-prefix' to support multiple meta instances can use the same etcd backend

.github/workflows/develop.yml, src/common/meta/src/wal/kafka/topic_manager.rs, tests-integration/fixtures/kafka/docker-compose-standalone.yml
Setup a kafka standalone in CI coverage test
**Get started**
```shell
cd tests-integration/fixtures/kafka 
docker compose -f docker-compose-standalone.yml up
```
=> chore: setup kafka standalone in coverage test

Cargo.lock, src/cmd/src/cli/bench/metadata.rs, src/cmd/src/cli/upgrade.rs, src/common/meta/src/ddl.rs, src/common/meta/src/ddl/alter_table.rs, src/common/meta/src/ddl/create_table.rs, src/common/meta/src/ddl_manager.rs, src/common/meta/src/error.rs, src/common/meta/src/key.rs, src/common/meta/src/key/datanode_table.rs, src/common/meta/src/key/table_info.rs, src/common/meta/src/key/table_name.rs, src/common/meta/src/key/table_region.rs, src/common/meta/src/key/table_route.rs, src/frontend/src/instance/standalone.rs, src/meta-srv/src/handler/region_lease_handler.rs, src/meta-srv/src/procedure/region_migration/migration_start.rs, src/meta-srv/src/procedure/region_migration/open_candidate_region.rs, src/meta-srv/src/procedure/region_migration/test_util.rs, src/meta-srv/src/procedure/region_migration/update_metadata/downgrade_leader_region.rs, src/meta-srv/src/procedure/region_migration/update_metadata/rollback_downgraded_region.rs, src/meta-srv/src/procedure/region_migration/update_metadata/upgrade_candidate_region.rs, src/meta-srv/src/procedure/tests.rs, src/meta-srv/src/region/lease_keeper.rs, src/meta-srv/src/table_meta_alloc.rs, src/meta-srv/src/test_util.rs, src/operator/src/tests/partition_manager.rs
Metric Engine table route, part 2
Next PR will create metric engine table, with its table route.
#2864
=> refactor: hide `RegionRoute` behind `TableRouteValue`

Cargo.lock, src/common/runtime/Cargo.toml, src/common/runtime/src/runtime.rs
export tokio runtime metrics
- use tokio-metric to collect runtime metrics
- use tokio-metric-collector to expose to promethues
close https://github.com/GreptimeTeam/greptimedb/issues/1529
=> feat: export runtime metric to promethues

.github/workflows/release.yml, Cargo.lock, Cargo.toml
=> chore: bump version to 0.5.0

.github/doc-label-config.yml, .github/pull_request_template.md, .github/workflows/doc-label.yml
Add an action job to auto label "Doc not needed" on PR based on the checkbox in "Checklist".
This patch also adds a dedicated checkbox in PR template for "doc not needed"/"doc update required" tuples.
Closes https://github.com/GreptimeTeam/greptimedb/issues/2997
=> chore(ci): auto doc labeler job

src/mito2/src/error.rs, src/mito2/src/sst/parquet.rs, src/mito2/src/sst/parquet/helper.rs, src/mito2/src/sst/parquet/reader.rs, src/mito2/src/sst/parquet/writer.rs
part of #2963 , this pr is pre-work.
support to convert from `FileMetaData` to `ParquetMetaData`.
#2963
=> feat: convert `FileMetaData` to `ParquetMetaData`

.github/workflows/doc-label.yml
Update the label on editing PR, docs: https://github.com/waynexia/greptimedb/pull/new/sync-doc-label
=> fix: update doc label on pr edit

.github/workflows/size-label.yml
=> chore: try to fix size labeller

Cargo.lock, src/servers/Cargo.toml, src/servers/src/postgres.rs, src/servers/src/postgres/handler.rs
This patch upgrades pgwire to 0.18 which corrected implementation of prepared statement caching https://github.com/sunng87/pgwire/pull/140. The statements are now cached with client and dropped when client disconnected.
=> feat: upgrade pgwire to 0.18 for corrected statement caching

src/meta-srv/src/handler/keep_lease_handler.rs, src/meta-srv/src/service/admin.rs, src/meta-srv/src/service/admin/region_migration.rs
Implement param parsing of SubmitRegionMigrationTaskHandler
#2700
=> feat: implement param parsing of `SubmitRegionMigrationTaskHandler`

src/common/meta/src/key/table_route.rs, src/meta-srv/src/error.rs, src/meta-srv/src/procedure/region_migration.rs, src/meta-srv/src/procedure/region_migration/manager.rs, src/meta-srv/src/procedure/region_migration/test_util.rs, src/meta-srv/src/procedure/region_migration/update_metadata/downgrade_leader_region.rs
1. Implement the region migration manager.
More tests of managers will be introduced with integration tests(p.s. Previously, unit tests have covered region migration procedure flow-control tests)
#2700
=> feat: implement region migration manager

config/metasrv.example.toml, src/cmd/src/metasrv.rs, src/meta-srv/src/bootstrap.rs, src/meta-srv/src/election/etcd.rs, src/meta-srv/src/lock/etcd.rs, src/meta-srv/src/metasrv.rs
=> refactor: use string type instead of Option type for '--store-key-prefix'

.github/workflows/size-label.yml
Set the message on xlarge PR to empty string, discussion: https://github.com/CodelyTV/pr-size-labeler/issues/55
=> chore: do not send message for xlarge PR

src/common/meta/src/instruction.rs, src/datanode/src/error.rs, src/datanode/src/heartbeat.rs, src/datanode/src/heartbeat/handler.rs, src/datanode/src/heartbeat/handler/close_region.rs, src/datanode/src/heartbeat/handler/downgrade_region.rs, src/datanode/src/heartbeat/handler/open_region.rs, src/datanode/src/heartbeat/handler/upgrade_region.rs, src/datanode/src/heartbeat/task_tracker.rs, src/datanode/src/region_server.rs, src/datanode/src/tests.rs, src/meta-srv/src/procedure/region_migration/upgrade_candidate_region.rs, src/store-api/src/region_engine.rs
1. Add `TaskTracker`
2. Support region server handling upgrade region instruction
#2700
=> feat: implement handle upgrade region instruction

README.md
Fix CI badge
Fixes broken CI badge
- #3025
- #3026
=> chore: Update CI badge in README.md

Cargo.lock, src/promql/Cargo.toml, src/promql/src/extension_plan.rs, src/promql/src/extension_plan/instant_manipulate.rs, src/promql/src/extension_plan/planner.rs, src/promql/src/extension_plan/test_util.rs, src/promql/src/extension_plan/union_distinct_on.rs, src/promql/src/lib.rs, src/promql/src/planner.rs, tests/cases/standalone/common/promql/set_operation.result, tests/cases/standalone/common/promql/set_operation.sql
This PR implements `OR` operator for PromQL. See `UnionDistinctOn`'s document for detailed explain.
Notice that there are a few unresolved problems in this patch. I'll file another one to resolve them since this PR reaches it size limit
#1042
=> feat: Implement OR for PromQL

src/mito2/src/region/opener.rs
Fixed replay memtable incorrectly. It should replay from `flushed_entry_id + 1.`
=> fix(wal): replay memtable should from `flushed_entry_id + 1`

src/common/meta/src/error.rs, src/common/meta/src/wal/kafka/topic_manager.rs, src/log-store/src/kafka/log_store.rs
Append a noop record after kafka topic initialization.
If the EntryId starts from 0, then the first entry in the mito engine will be dropped after restart. The mito always replays the memtable from the `flushed id + 1`(i.e., 0+1=1). Therefore, The EntryId must start from 1.
close #3039
=> feat(remote_wal): append a noop record after kafka topic initialization

src/cmd/src/standalone.rs, src/common/meta/src/ddl.rs, src/common/meta/src/ddl/table_meta.rs, src/common/meta/src/ddl_manager.rs, src/frontend/src/instance/standalone.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/metasrv/builder.rs, src/meta-srv/src/procedure/region_failover.rs, src/meta-srv/src/procedure/region_failover/failover_start.rs, src/meta-srv/src/selector/common.rs, src/meta-srv/src/selector/lease_based.rs, src/meta-srv/src/selector/load_based.rs, src/meta-srv/src/selector/weight_compute.rs, src/meta-srv/src/table_meta_alloc.rs, tests-integration/src/standalone.rs, tests-integration/tests/region_failover.rs
The two are same except for the peer allocation method. Merge them to reduce code duplication.
=> refactor: merge standalone and metasrv table metadata allocators

src/catalog/src/information_schema.rs, src/catalog/src/information_schema/columns.rs, src/catalog/src/information_schema/schemata.rs, src/catalog/src/information_schema/table_names.rs, src/common/catalog/src/consts.rs, src/datatypes/src/schema/column_schema.rs, tests-integration/src/tests/instance_test.rs, tests/cases/standalone/common/show/show_databases_tables.result, tests/cases/standalone/common/system/information_schema.result, tests/cases/standalone/common/system/information_schema.sql
* Improve `information_schema.columns`, add some missing fields.
* Add `information_schema.schemata` virtual table.See https://docs.pingcap.com/tidb/stable/information-schema-schemata
TODO:
* refactor `columns`, `tables`, and `schemata`, they can use the same framework or helper functions.
#2931
=> feat: adds information_schema.schemata

.github/workflows/doc-label.yml
Fixes duplicated doc issue created on updating pull request.
=> ci: fix duplicatd doc issue

Cargo.lock, Cargo.toml, src/common/config/src/wal/kafka.rs, src/index/src/inverted_index/error.rs, src/index/src/inverted_index/search/fst_apply/intersection_apply.rs, src/mito2/Cargo.toml, src/mito2/src/error.rs, src/mito2/src/row_converter.rs, src/mito2/src/sst/index.rs, src/mito2/src/sst/index/applier.rs, src/mito2/src/sst/index/applier/builder.rs, src/mito2/src/sst/index/applier/builder/between.rs, src/mito2/src/sst/index/codec.rs
This PR accomplishes the following:
1. Primarily, adds preliminary inverted index integration code to the `mito2` crate, currently dealing with the read aspect.
- Introduces `SstIndexApplier`, which will be embedded in `ParquetReaderBuilder` in the future to offer indexing application services.
- Introduces `SstIndexApplierBuilder`, which, as implied by its name, is responsible for constructing `SstIndexApplier`. It does a significant amount of work internally to recognize and transform `Expr` into `Predicate`s understandable by the index crate.
Given the substantial amount of code for the transformation, I plan to submit it in two separate PRs:
- This PR is focused on the …
=> feat(inverted_index): Add applier builder to convert Expr to Predicates (Part 1)

src/log-store/src/kafka/client_manager.rs, src/log-store/src/kafka/log_store.rs
- Rewrite the iteration in `append_batch` to ensure the `region_ids` and `last_entry_ids` coincide.
- Temporarily replace the `DashMap` with `tokio::sync::Mutex` to resolve a known deadlock issue.
=> fix(remote_wal): some known issues

src/common/meta/src/ddl/create_table.rs, src/common/meta/src/instruction.rs, src/common/meta/src/key.rs, src/common/meta/src/key/datanode_table.rs, src/common/meta/src/wal.rs, src/datanode/src/datanode.rs, src/meta-srv/src/error.rs, src/meta-srv/src/procedure/region_failover/activate_region.rs, src/meta-srv/src/procedure/region_failover/update_metadata.rs, src/meta-srv/src/procedure/region_migration.rs, src/meta-srv/src/procedure/region_migration/migration_start.rs, src/meta-srv/src/procedure/region_migration/open_candidate_region.rs, src/meta-srv/src/procedure/region_migration/update_metadata/upgrade_candidate_region.rs
1. Add prepare_wal_option
2. use integer hashmap
3. Unify the injection of WAL option
#2700
=> refactor: unify the injection of WAL option

tests-integration/src/cluster.rs, tests-integration/src/lib.rs, tests-integration/src/standalone.rs, tests-integration/src/test_util.rs, tests-integration/src/tests.rs, tests-integration/src/tests/test_util.rs
Add kafka wal integration test utils
=> feat: add kafka wal integration test utils

src/mito2/Cargo.toml, src/mito2/src/cache.rs, src/mito2/src/cache/file_cache.rs
This PR implements a cache for files in the `WriteCache`. The design is similar to the [`ReadCache`](https://github.com/GreptimeTeam/greptimedb/blob/485a91f49ab5e7db4b71045261389fab6a627688/src/object-store/src/layers/lru_cache/read_cache.rs).
The differences are
- This cache always caches the whole SST file as it serves as a write-through cache
- This cache doesn't read files from remote object stores
This cache has the following features:
- Caches files on local disk (the local store).
- Uses `{region_id}.{file_id}` as cache key and cached file name
- Uses an in-memory LRU cache as file index
- If the LRU cache removes the key, it also evicts the file on the local store.
- …
=> feat(mito): Implement file cache

src/puffin/src/file_format/writer.rs, src/puffin/src/file_format/writer/file.rs, src/puffin/src/tests.rs
Puffin writer to return written bytes, to help the upper layer to track it.
=> feat(puffin): finish return written bytes

src/index/src/inverted_index/search/fst_apply.rs, src/index/src/inverted_index/search/fst_apply/intersection_apply.rs, src/index/src/inverted_index/search/fst_apply/keys_apply.rs, src/index/src/inverted_index/search/index_apply.rs, src/index/src/inverted_index/search/index_apply/predicates_apply.rs
Add `memory_usage` to traits `FstApplier` and `IndexApplier`.
It helps track the memory usage of the index application process.
=> feat(inverted_index): get memory usage of appliers

src/datanode/src/heartbeat/handler.rs, src/datanode/src/heartbeat/handler/open_region.rs, src/meta-srv/src/procedure/region_migration.rs, src/meta-srv/src/procedure/region_migration/manager.rs, tests-integration/src/cluster.rs, tests-integration/src/standalone.rs, tests-integration/src/test_util.rs, tests-integration/tests/region_failover.rs, tests-integration/tests/region_migration.rs
1. Fix heartbeat handler ignore upgrade candidate instruction
2. Fix handler did not inject wal options
3. Expose `RegionMigrationProcedureTask`
4. Add a naive region migration integration test
#2700
=> feat(tests-integration): add a naive region migration integration test

src/common/meta/src/key.rs, src/common/meta/src/key/table_route.rs, src/common/meta/src/rpc/router.rs, src/meta-srv/src/procedure/region_failover/update_metadata.rs, tests-integration/src/grpc.rs, tests-integration/src/instance.rs
remove unnecessary result wrappings 
close #3079
=> chore: remove unnecessary result wrappings

src/meta-srv/src/procedure/region_migration/migration_start.rs, src/meta-srv/src/procedure/region_migration/open_candidate_region.rs
Abort region migration if leader region peer is unexpected
#2700
=> feat: abort region migration if leader region peer is unexpected

src/cmd/src/standalone.rs, src/common/meta/src/ddl/table_meta.rs, src/common/meta/src/ddl_manager.rs, src/common/meta/src/key/table_route.rs, src/common/meta/src/lib.rs, src/common/meta/src/rpc/router.rs, src/datanode/src/error.rs, src/datanode/src/region_server.rs, src/datanode/src/tests.rs, src/file-engine/src/engine.rs, src/frontend/src/instance/region_query.rs, src/meta-srv/src/metasrv/builder.rs, src/meta-srv/src/procedure/region_migration/manager.rs, src/metric-engine/src/engine.rs, src/metric-engine/src/lib.rs, src/mito2/src/engine.rs, src/partition/src/manager.rs, src/partition/src/metrics.rs, src/store-api/src/region_engine.rs, tests-integration/src/standalone.rs
Now metric engine table can be created. Basic insertion is supported:
```text
mysql> create table physical_table(ts timestamp time index) engine = metric with (physical_metric_table = true);
Query OK, 0 rows affected (0.03 sec)
mysql> select * from information_schema.tables where engine = 'metric';
+---------------+--------------+----------------+------------+----------+--------+
| table_catalog | table_schema | table_name     | table_type | table_id | engine |
+---------------+--------------+----------------+------------+----------+--------+
| greptime      | public       | physical_table | BASE TABLE |     1044 | metric | …
```
=> feat: table route for metric engine

src/datanode/src/heartbeat/handler/upgrade_region.rs, src/meta-srv/src/procedure/region_migration/update_metadata/upgrade_candidate_region.rs, src/mito2/src/worker/handle_catchup.rs
Add logs for (region server) upgrading candidate region
Add logs for (procedure) updating metadata
#2700
=> feat: add logs for upgrading candidate region and updating metadata

src/common/meta/src/ddl/table_meta.rs, tests-integration/tests/main.rs, tests-integration/tests/region_migration.rs
Add more region migration integration test
#2700
=> feat(tests-integration): add more region migration integration tests

src/common/meta/src/key/table_route.rs, src/meta-srv/src/region/lease_keeper.rs
Add tests for lease keeper handling logical table.
=> test: add tests for lease keeper with logical table

src/datanode/src/heartbeat.rs, src/datanode/src/region_server.rs, src/metric-engine/src/engine.rs, src/metric-engine/src/engine/alter.rs, src/metric-engine/src/engine/close.rs, src/metric-engine/src/engine/create.rs, src/metric-engine/src/engine/open.rs, src/metric-engine/src/engine/put.rs, src/metric-engine/src/engine/read.rs
Filter out metric region stats
#2070
=> feat(metric): implement `role` and `region_disk_usage`

Cargo.lock, src/catalog/Cargo.toml, src/catalog/src/information_schema.rs, src/catalog/src/information_schema/columns.rs, src/catalog/src/information_schema/key_column_usage.rs, src/catalog/src/information_schema/memory_table.rs, src/catalog/src/information_schema/predicate.rs, src/catalog/src/information_schema/schemata.rs, src/catalog/src/information_schema/tables.rs, tests/cases/standalone/common/system/information_schema.result, tests/cases/standalone/common/system/information_schema.sql
Some tables in `information_schema` will be large in the production when there are many created tables, such as `columns` and `tables` etc.
This PR supports pushing down query filters for some information_schema tables, it would reduce the memory consumption while constructing the result stream and speed up the query.
Currently it supports following filters:
* `Eq`
* `NotEq`
* `InList`
* `expr AND expr`
* `expr OR expr`
* `NOT expr`
* `expr LIKE pattern`
We can support more types in the future. Looks like datafusion doesn't push down `like` expression currently. @waynexia 
https://github.com/GreptimeTeam/greptimedb/issues/2931
=> feat: pushdown filters for some information_schema tables

src/catalog/src/metrics.rs, src/client/src/metrics.rs, src/cmd/src/lib.rs, src/common/meta/src/metrics.rs, src/common/runtime/src/metrics.rs, src/common/telemetry/src/panic_hook.rs, src/datanode/src/metrics.rs, src/frontend/src/metrics.rs, src/meta-srv/src/metrics.rs, src/metric-engine/src/metrics.rs, src/mito2/src/metrics.rs, src/object-store/src/metrics.rs, src/operator/src/metrics.rs, src/partition/src/metrics.rs, src/promql/src/metrics.rs, src/query/src/metrics.rs, src/script/src/python/metric.rs, src/servers/src/metrics.rs
add `greptime_` prefix for every metrics
=> refactor(metrics): add 'greptime_' prefix for every metrics

Cargo.lock, src/common/procedure/src/store/state_store.rs, src/mito2/src/cache/file_cache.rs, src/object-store/Cargo.toml, src/object-store/src/layers/lru_cache.rs, src/object-store/src/layers/lru_cache/read_cache.rs, src/object-store/src/layers/prometheus.rs, src/object-store/src/lib.rs, src/object-store/tests/object_store_test.rs
1. Bump opendal to 0.44
The next minor version(0.44.1), a `BufferReader`(https://github.com/apache/incubator-opendal/issues/3735) will be introduced.
=> chore: bump opendal to 0.44

src/common/meta/src/ddl/alter_table.rs, src/common/meta/src/ddl_manager.rs, src/common/meta/src/key/table_route.rs, src/meta-srv/src/procedure/tests.rs, src/partition/src/manager.rs
1. Support ALTER
2. Procedure to ALTER logical table should acquire lock to physical table
=> feat: metric engine support alter

Cargo.lock, src/log-store/Cargo.toml, src/log-store/src/kafka/util/record.rs, src/log-store/src/kafka/util/test_util.rs
check env before running kafka test
=> fix: check env before running kafka test

Cargo.lock, Cargo.toml
=> chore: bump version to 0.5.1

.github/ISSUE_TEMPLATE/bug_report.yml
Update the issues template to add the greptimedb version when reporting bugs.
=> docs: update issue template

Cargo.lock, src/common/query/src/prelude.rs, src/promql/Cargo.toml, src/promql/src/extension_plan/empty_metric.rs, src/promql/src/planner.rs, src/query/src/sql.rs, src/servers/src/http/prometheus.rs, src/servers/src/opentsdb.rs, src/servers/src/opentsdb/codec.rs, src/servers/src/otlp.rs, src/servers/src/otlp/metrics.rs, src/servers/src/otlp/trace.rs, src/servers/src/prom_store.rs, tests/cases/standalone/common/promql/set_operation.result, tests/cases/standalone/common/promql/set_operation.sql
Implement [`vector`](https://prometheus.io/docs/prometheus/latest/querying/functions/#vector) function from PromQL.
=> feat: support PromQL function `vector`

src/datanode/src/datanode.rs, src/datanode/src/error.rs, src/datanode/src/store.rs, src/datanode/src/store/azblob.rs, src/datanode/src/store/fs.rs, src/datanode/src/store/gcs.rs, src/datanode/src/store/oss.rs, src/datanode/src/store/s3.rs, src/mito2/src/access_layer.rs, src/mito2/src/cache.rs, src/mito2/src/cache/file_cache.rs, src/mito2/src/cache/write_cache.rs, src/mito2/src/config.rs, src/mito2/src/engine.rs, src/mito2/src/error.rs, src/mito2/src/flush.rs, src/mito2/src/read/projection.rs, src/mito2/src/sst/parquet.rs, src/mito2/src/test_util.rs, src/mito2/src/test_util/scheduler_util.rs, src/mito2/src/worker.rs, src/object-store/src/util.rs, tests-integration/tests/http.rs
This PR initializes the `WriteCache` according to the mito config. By default, the write cache is under `DATA_HOME/write_cache` and is disabled.
It addresses an issue that the file cache doesn't use `get()` to access cache entries.
It also refactors some mods to make the integration easier
- Adds a builder for the `CacheManager`
- Recovers the `FileCache` in `WriteCache::new`
- `MitoEngine::new` is an async function now
- Provides a util to attach layers to `ObjectStore`
Now write cache is still an experimental feature so I added prefixes to its config items.
- https://github.com/GreptimeTeam/greptimedb/issues/2965
=> feat(mito): Init the write cache in datanode

src/datanode/src/datanode.rs, src/frontend/src/server.rs, src/servers/src/error.rs, src/servers/src/grpc.rs, src/servers/src/grpc/authorize.rs, src/servers/src/grpc/builder.rs, src/servers/src/grpc/otlp.rs, src/servers/src/grpc/prom_query_gateway.rs, src/servers/src/http/authorize.rs, tests-integration/src/cluster.rs, tests-integration/src/test_util.rs
1. Add support for otlp's grpc protocol.
2. Add grpc auth middleware.
3. Add a GrpcServerBuilder.
=> feat: support grpc for otlp trace and metrics

Cargo.lock, config/standalone.example.toml, src/common/config/src/wal/raft_engine.rs, src/log-store/Cargo.toml, src/log-store/src/raft_engine/log_store.rs, tests-integration/tests/http.rs
This PR adds config to enable log recycle/prefill and periodical log fsync to smooth IO utilization. This change helps both local fs and S3 mode.
- `enable_log_recycle`: true
- `prefill_log_files`: false
- `sync_period`: 1000ms
Before:
After:
Before: 
After:
Fixes #3085
=> feat: add options to enable log recycle and periodical fsync

config/datanode.example.toml, config/standalone.example.toml, src/log-store/src/error.rs, src/log-store/src/raft_engine/log_store.rs, src/mito2/src/config.rs, src/mito2/src/error.rs, src/mito2/src/region/opener.rs, src/mito2/src/worker/handle_catchup.rs, tests-integration/tests/http.rs
This PR adds bound check to RaftEngine logstore so that it won't panic at "memtable has a hole". This will also helps to diagnose some weird out-of-order sequence in some user cases.
Note: this impose extra constraint to prevent concurrent writes with consecutive entry id to the same region when bound check and actual write overlap. But it won't cause false errors in region worker pattern where only one thread writes to some region.
```
check 1  
|    check 2  // this bound check will fail with this patch
|       x 
v       |
write 1    v 
write 2
```
Ran performance regression test in TSBS suite and no noticeable changes observed.
```
// before: 
loaded 1036800000 metrics …
```
=> chore: add bound check for raft-engine logstore

src/mito2/src/access_layer.rs, src/mito2/src/compaction/twcs.rs, src/mito2/src/flush.rs, src/mito2/src/sst/parquet.rs, src/mito2/src/sst/parquet/writer.rs
add parquet metadata to `SstMetaCache` after flush or compact.
Closes #2963
=> feat: add parquet metadata to cache

src/script/src/python/ffi_types/vector/tests.rs, src/script/src/python/pyo3/utils.rs, src/script/src/python/rspython/copr_impl.rs
This relates to https://github.com/GreptimeTeam/greptimedb/discussions/3117 for improving user experience.
=> chore(python): Print Python interpreter version

.github/pull_request_template.md
Change the default "require document update" checkbox to not required. Thus an opt-in workflow (it's sometimes annoying, like https://github.com/GreptimeTeam/greptimedb/pull/3114)
=> chore: change the default doc checkbox to no need

src/servers/src/error.rs, src/servers/src/mysql/writer.rs, src/servers/src/postgres/types.rs
Change the error type on encountering unsupported datatype when writing to MySQL protocol. Makes it easier to understand what's happening
Before:
```sql
ERROR 1815 (HY000): Internal error: 1003
```
After:
```sql
ERROR 1815 (HY000): Unsupported data type: List<String>
```
=> fix: expose unsupported datatype error on mysql protocol

src/catalog/src/table_source.rs, src/frontend/src/instance.rs, src/query/src/datafusion/planner.rs, src/query/src/planner.rs, src/query/src/query_engine/options.rs, src/query/src/query_engine/state.rs, src/query/src/tests/query_engine_test.rs
We was restricting cross-schema query because of our cloud permission system. As we are switching to catalog based service, we start to allow those cross-schema access. This patch updates check to valid catalog only. It enables us to utilize internal schema `greptime_private`.
=> feat: update our cross schema check to cross catalog

Cargo.lock, src/meta-srv/Cargo.toml, src/meta-srv/src/error.rs, src/meta-srv/src/procedure/region_migration.rs, src/meta-srv/src/procedure/region_migration/downgrade_leader_region.rs, src/meta-srv/src/procedure/region_migration/manager.rs, src/meta-srv/src/procedure/region_migration/test_util.rs, src/meta-srv/src/procedure/region_migration/upgrade_candidate_region.rs, src/meta-srv/src/service/admin/region_migration.rs, tests-integration/tests/region_migration.rs
Expose the `replay_timeout` argument in the region migration http API.
#2700
=> feat: expose the region migration `replay_timeout` argument

config/metasrv.example.toml, config/standalone.example.toml, src/common/meta/src/wal.rs
Since we only utilize the partition 0 (the first partition) of each Kafka topic, there's no need to expose the `num_partitions` to users through config file. If it's exposed, some users may set it to be greater than 1 and expect that there're multiple partitions per topic which we cannot provide.
=> chore: stop exposing num_partitions

src/common/function/src/system.rs, src/common/function/src/system/version.rs, src/servers/src/mysql/federated.rs, tests/cases/standalone/common/function/system.result, tests/cases/standalone/common/function/system.sql
This patch rewrites implementation of `select version()` as system function so it will be available for both mysql and postgresql.
Also in order to get compatible with some client drivers like python's mysqlclient, we need to return a version number that makes sense for mysql. 
```
File "/home/sunng/greptime/st-greptimedb-connection/example/.venv/lib/python3.12/site-packages/sqlalchemy/dialects/mysql/base.py", line 2533, in get_isolation_level
if self._is_mysql and self.server_version_info >= (5, 7, 20):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'NoneType' and 'tuple'
```
In next patch, I'm going to see if we can make …
=> refactor:  implement version as built-in function and use fixed mysql version

src/cmd/src/metasrv.rs, src/cmd/src/standalone.rs, src/datanode/src/config.rs, src/meta-srv/src/metasrv.rs
fix: incorrect parsing `broker_endpoints` env variable
=> fix: incorrect parsing `broker_endpoints` env variable

Cargo.lock, src/cmd/src/frontend.rs, src/cmd/src/standalone.rs, src/common/test-util/Cargo.toml, src/common/test-util/src/lib.rs, src/common/test-util/src/recordbatch.rs, src/frontend/src/instance.rs, src/frontend/src/lib.rs, src/frontend/src/server.rs, src/servers/src/grpc.rs, src/servers/src/grpc/builder.rs, tests-integration/src/test_util.rs, tests-integration/src/tests/instance_test.rs, tests-integration/tests/region_failover.rs, tests-integration/tests/region_migration.rs
Also expose grpc server builder for other projects to use.
=> refactor: change how frontend grpc services are orchestrated

src/mito2/src/cache/file_cache.rs, src/mito2/src/cache/test_util.rs, src/mito2/src/cache/write_cache.rs, src/mito2/src/error.rs, src/mito2/src/metrics.rs, src/mito2/src/sst.rs, src/mito2/src/sst/parquet.rs, src/mito2/src/test_util/sst_util.rs
part of #2965
write sst file to cache and upload it to remote object store
#2965
=> feat: write and upload sst

src/meta-srv/src/procedure/region_migration/update_metadata/downgrade_leader_region.rs, src/meta-srv/src/procedure/region_migration/update_metadata/rollback_downgraded_region.rs, src/meta-srv/src/procedure/region_migration/update_metadata/upgrade_candidate_region.rs
save code in `debug_assert!`
#2700
=> fix: save code in `debug_assert!`

config/datanode.example.toml
Remove incorrect comments about wal in config file.
=> fix: remove incorrect wal comments in config file

src/mito2/src/cache/file_cache.rs, src/mito2/src/cache/write_cache.rs, src/mito2/src/sst/parquet.rs, src/mito2/src/sst/parquet/helper.rs, src/mito2/src/sst/parquet/row_group.rs
part of #2965
changes:
- move fetch ranges function to `helper.rs`.
- add `read_ranges` function for `FileCache`.
- support to try reading from write cache first, if failed, read from remote object store directly.
- tiny refactor `usize` to `u64`
#2965
=> feat: read data from write cache

src/common/meta/src/ddl/alter_table.rs, src/common/meta/src/ddl/utils.rs, src/meta-srv/src/error.rs, src/meta-srv/src/procedure/region_failover.rs, src/meta-srv/src/procedure/region_failover/failover_start.rs, src/meta-srv/src/procedure/region_failover/update_metadata.rs, src/meta-srv/src/procedure/region_migration.rs, src/meta-srv/src/procedure/region_migration/downgrade_leader_region.rs, src/meta-srv/src/procedure/region_migration/open_candidate_region.rs, src/meta-srv/src/procedure/region_migration/update_metadata/downgrade_leader_region.rs, src/meta-srv/src/procedure/region_migration/update_metadata/rollback_downgraded_region.rs, src/meta-srv/src/procedure/region_migration/update_metadata/upgrade_candidate_region.rs, src/meta-srv/src/procedure/region_migration/upgrade_candidate_region.rs, src/meta-srv/src/procedure/utils.rs
fix missing detailed error
#2700
fixes #3138
=> fix: print detailed error

src/common/meta/src/key/datanode_table.rs
Before we store all region wal options into table metadata or somewhere, we must store all region wal options.
#2700
=> fix: fix store all wal options

src/promql/src/error.rs, src/promql/src/extension_plan/union_distinct_on.rs, src/promql/src/planner.rs, tests/cases/standalone/common/promql/set_operation.result, tests/cases/standalone/common/promql/set_operation.sql
Now the planner will identify `TIME INDEX` and `FIELD` columns using their semantic type instead of their name. Makes it possible to handle different columns across set operation's inputs
=> fix: handle non-identical time index and field column in PromQL set operation

.github/workflows/release.yml, Cargo.lock, Cargo.toml
=> chore: bump version to 0.6.0

Cargo.lock, Cargo.toml, benchmarks/Cargo.toml, src/cmd/Cargo.toml, src/cmd/src/datanode.rs, src/cmd/src/lib.rs, src/datanode/src/datanode.rs, src/datanode/src/lib.rs, src/datanode/src/service.rs, src/frontend/src/server.rs, src/servers/src/grpc.rs, src/servers/src/grpc/builder.rs, tests-integration/Cargo.toml, tests-integration/src/cluster.rs, tests-integration/src/test_util.rs, tests/runner/Cargo.toml
Sometimes in other projects, we need to add another grpc service to tonic server. This PR refactor the grpc codes to enable that.
=> refactor: make grpc service able to be added dynamically

Cargo.lock, src/servers/Cargo.toml, src/servers/src/postgres/auth_handler.rs, src/servers/src/postgres/handler.rs, src/servers/src/postgres/types.rs
This patch upgrades pgwire to 0.19 which includes some postgresql protocol compatibility improvements.
=> feat: upgrade pgwire to 0.19

src/datatypes/src/types/duration_type.rs, src/datatypes/src/types/primitive_type.rs, src/datatypes/src/vectors/decimal.rs, src/datatypes/src/vectors/helper.rs, src/datatypes/src/vectors/interval.rs, src/mito2/src/cache.rs, src/mito2/src/cache/file_cache.rs, src/mito2/src/cache/write_cache.rs, src/mito2/src/config.rs, src/mito2/src/engine/basic_test.rs, src/mito2/src/sst/parquet.rs, src/operator/src/req_convert/insert/stmt_to_region.rs
- add write cache test for engine 
- remove unused for file cache and write cache
- refactor my code style, use `crate` path instead of `super`
=> test: engine with write cache

docs/rfcs/2023-11-03-inverted-index.md
=> docs: add tracking issue for inverted-index RFC

src/catalog/src/error.rs, src/catalog/src/kvbackend/manager.rs, src/common/meta/src/key/table_name.rs, src/meta-srv/src/error.rs, src/meta-srv/src/service/admin/meta.rs
=> feat: let tables API return a stream

Cargo.lock, Cargo.toml, tests-fuzz/Cargo.toml, tests-fuzz/src/context.rs, tests-fuzz/src/executor.rs, tests-fuzz/src/generator.rs, tests-fuzz/src/lib.rs, tests-fuzz/src/table_creator.rs, tests-fuzz/src/translator.rs
Add the empty tests-fuzz crate
=> feat: add tests-fuzz crate

src/catalog/src/information_schema/columns.rs, src/catalog/src/information_schema/tables.rs, src/catalog/src/kvbackend/manager.rs, src/catalog/src/lib.rs, src/catalog/src/memory/manager.rs
1. Enhanced `CatalogManager`: get tables with stream by catalog and schema
2. Let information_schema.columns & information_schema.tables use stream API to get tables
=> feat: tables stream with CatalogManager

src/servers/src/http/header.rs
This pr mainly changes back `GREPTIME_DB_HEADER_NAME` to its previous key name.
=> fix: change back `GREPTIME_DB_HEADER_NAME` header key name

Cargo.lock, Cargo.toml, src/common/base/src/readable_size.rs, src/common/config/Cargo.toml, src/common/config/src/lib.rs, src/common/config/src/utils.rs, src/mito2/Cargo.toml, src/mito2/src/config.rs, tests-integration/Cargo.toml, tests-integration/tests/http.rs
- according to host memory size to decide the mito's buffer or cache size.
- remove `cpu_nums` crate and use `sysinfo`.
For example, my computer has 16G memory and 8 cpu cores
```
Mito(
MitoConfig {
num_workers: 4,
worker_channel_size: 128,
worker_request_batch_size: 64,
manifest_checkpoint_distance: 10,
compress_manifest: false,
max_background_jobs: 4,
auto_flush_interval: 1800s,
global_write_buffer_size: 256.0MiB,
global_write_buffer_reject_size: 512.0MiB,
sst_meta_cache_size: 64.0MiB,
vector_cache_size: 128.0MiB,
page_cache_size: 128.0MiB,
enable_experimental_write_cache: false,
experimental_write_cache_path: "",
experimental_write_cache_size: 128.0MiB, …
```
=> feat: auto config cache size according to memory size

src/mito2/src/access_layer.rs, src/mito2/src/cache/write_cache.rs, src/mito2/src/compaction/twcs.rs, src/mito2/src/config.rs, src/mito2/src/flush.rs, src/mito2/src/sst/index.rs, src/mito2/src/sst/index/creator.rs, src/mito2/src/sst/index/intermediate.rs, src/mito2/src/sst/index/store.rs, src/mito2/src/sst/parquet/reader.rs, src/mito2/src/worker.rs, tests-integration/tests/http.rs
Set the buffer size for the OpenDAL writer to avoid uploading small parts.
Additionally, ensure that index-related exceptions cause panic in test scenarios.
=> fix(index): S3 `EntityTooSmall` error

Cargo.lock, src/partition/src/partition.rs, tests-fuzz/Cargo.toml, tests-fuzz/src/context.rs, tests-fuzz/src/error.rs, tests-fuzz/src/generator.rs, tests-fuzz/src/generator/alter_expr.rs, tests-fuzz/src/generator/create_expr.rs, tests-fuzz/src/ir.rs, tests-fuzz/src/ir/alter_expr.rs, tests-fuzz/src/ir/create_expr.rs, tests-fuzz/src/lib.rs
1. add CreateTableExprGenerator
2. add AlterTableExprGenerator
#3174
=> feat(tests-fuzz): add CreateTableExprGenerator & AlterTableExprGenerator

src/operator/src/error.rs, src/operator/src/statement/copy_table_from.rs
1. Reduce the number of parquet metadata reads
2. Enable the reader buffer
=> refactor: reduce number of parquet metadata reads and enable reader buffer

src/mito2/src/sst/file.rs, src/mito2/src/sst/parquet.rs, src/mito2/src/sst/parquet/metadata.rs, src/mito2/src/sst/parquet/reader.rs
1. introduce `MetadataLoader`
2. using opendal `read_with` and `range` to read parquet metadata instead of using `reader`.
Closes #3191
=> refactor: read parquet metadata

Cargo.lock
Bump OpenDAL to v0.44.2. 
Now the concurrent writer is available, usage:
```rust
let mut w = op.writer_with(path).concurrent(8).await;
```
See also: 
- https://github.com/apache/opendal/pull/3898
- https://github.com/apache/opendal/pull/3942
- https://github.com/apache/opendal/releases/tag/v0.44.2
=> chore: bump opendal to v0.44.2

src/catalog/src/kvbackend/manager.rs
Each time invoking the `self.system_catalog.table(catalog, schema, table_name)`, the `system_catalog` makes a new `InformationSchemaProvider`, which is time-consuming.
If we execute the `SELECT * FROM information_schema. tables;`, each `self.system_catalog.table(catalog, schema, table_name)` invoking will take ~30ms, resulting in query will spend ~500ms. The key problem here:
```rust
let sys_tables = try_stream!({
// System tables
let sys_table_names = self.system_catalog.table_names(schema);
for table_name in sys_table_names {
if let Some(table) = self.system_catalog.table(catalog, schema, &table_name) { // <- This invoking
yield table;
}
}
});
```
BTW, I checked the …
=> feat: introduce information schema provider cache

src/datatypes/src/vectors.rs, src/metric-engine/src/engine/create.rs, src/mito2/src/memtable/time_series.rs
Lazy create `MutableVector` for `TimeSeries`. This change can save lots of memory when the data's field columns are sparse. In my test scenario where ~90% fields are null, it can cut up to 80% memory consumption:
I also run a tsbs-load benchmark to see if this change slow down the normal case. The result shows it doesn't have bad influence:
before this change:
```
loaded 86400000 rows in 141.686sec with 6 workers (mean rate 609798.27 rows/sec)
```
after this change:
```
loaded 86400000 rows in 140.448sec with 6 workers (mean rate 615174.51 rows/sec)
```
=> feat: lazy initialize vector builder on write

src/promql/src/planner.rs, tests/cases/standalone/common/tql/basic.result, tests/cases/standalone/common/tql/basic.sql
Fix the bug reported by @dekelpilli in https://github.com/GreptimeTeam/greptimedb/issues/1042#issuecomment-1903431191
The `__name__` matcher is not removed after special preprocess logic, resulting in the afterword plan phase treating it as a column name.
=> fix: remove __name__ matcher from processed matcher list

src/metric-engine/src/engine/put.rs, src/metric-engine/src/engine/state.rs
Closes https://github.com/GreptimeTeam/greptimedb/issues/3220
Change the metadata retrieving behavior from read underlying mito to memory state cache. This can alleviate the high CPU usage a lot.
CPU curve afterward:
(There are three flush in this graph)
Closes https://github.com/GreptimeTeam/greptimedb/issues/3220
=> feat: read column and region info from state cache

src/common/datasource/src/buffered_writer.rs, src/common/datasource/src/file_format.rs, src/common/datasource/src/file_format/csv.rs, src/common/datasource/src/file_format/json.rs, src/common/datasource/src/file_format/parquet.rs, src/common/datasource/src/lib.rs, src/common/datasource/src/test_util.rs, src/mito2/src/cache/write_cache.rs, src/mito2/src/sst.rs, src/mito2/src/sst/parquet/writer.rs, src/operator/src/statement/copy_table_to.rs
1. set `DEFAULT_WRITE_CONCURRENT` to 8.
2. Enable concurrent write for `Copy To` and `ParquetWriter`.
=> feat: enable concurrent write

src/common/meta/src/ddl/create_table.rs, tests-integration/src/cluster.rs
Only register region keeper while creating physical table
=> fix: only register region keeper while creating physical table

Cargo.lock, Cargo.toml, src/servers/Cargo.toml, src/servers/src/error.rs, src/servers/src/http.rs, src/servers/src/http/arrow_result.rs, src/servers/src/http/handler.rs
This patch is initial work to add arrow output format for our http sql api. By using arrow output format it is possible to do zero-copy with arrowjs ecosystem, including visualization library vega (with vega-arrow-loader) and many more.
I will be seeking to add streaming support for output types like csv and arrow in future patch.
=> feat: add Arrow IPC output format for http rest api

Cargo.lock
Manually update dependencies as github dependabot failed to create these PRs. 
- Multiple issues involving quote API in shlex (Security 31)
-  Resource exhaustion vulnerability in h2 may lead to Denial of Service (DoS) (Security 30)
=> fix: security update for shlex and h2

src/catalog/Cargo.toml, src/servers/src/http.rs, src/servers/src/http/handler.rs, tests-integration/tests/http.rs
Previously we don't return schema for empty resultset. This patch corrected this for better usability.
=> feat: http sql api return schema on empty resultset

docker/ci/ubuntu/Dockerfile
=> ci: adding `DOCKER_BUILD_ROOT` docker arg for dev build

src/mito2/src/cache.rs, src/mito2/src/cache/file_cache.rs, src/mito2/src/cache/write_cache.rs, src/mito2/src/sst/parquet.rs, src/mito2/src/sst/parquet/metadata.rs, src/mito2/src/sst/parquet/reader.rs, src/mito2/src/test_util.rs, src/mito2/src/test_util/sst_util.rs
- read parquet metadata from write cache.
- refactor some test code.
#2965
=> feat: read metadata from write cache

src/common/meta/src/ddl/create_table.rs, src/common/meta/src/ddl_manager.rs, src/common/meta/src/error.rs, src/common/procedure/src/lib.rs, src/common/procedure/src/procedure.rs, src/common/procedure/src/watcher.rs
fix create table ddl return incorrect table id
fix #3200
=> fix: fix create table ddl return incorrect table id

src/mito2/src/sst/parquet/reader.rs
This PR avoids initializing the reader metrics twice, which resets row group metrics
=> fix: init parquet reader metrics twice

Cargo.lock, Cargo.toml, src/common/meta/src/ddl.rs, src/common/meta/src/ddl/create_logical_tables.rs, src/common/meta/src/ddl/create_table.rs, src/common/meta/src/ddl/create_table_template.rs, src/common/meta/src/ddl/table_meta.rs, src/common/meta/src/ddl/utils.rs, src/common/meta/src/ddl_manager.rs, src/common/meta/src/error.rs, src/common/meta/src/key.rs, src/common/meta/src/key/table_name.rs, src/common/meta/src/key/table_route.rs, src/common/meta/src/metrics.rs, src/common/meta/src/rpc/ddl.rs, src/common/meta/src/rpc/store.rs, src/meta-srv/src/procedure/tests.rs, src/operator/src/error.rs, src/operator/src/metrics.rs, src/operator/src/statement/ddl.rs, src/store-api/src/region_request.rs
Batch create logical tables with procedure
=> feat: batch create ddl

src/common/error/src/status_code.rs, src/common/meta/src/ddl/alter_table.rs, src/metric-engine/src/data_region.rs, src/metric-engine/src/engine/create.rs, src/mito2/src/engine/alter_test.rs, src/mito2/src/error.rs, src/mito2/src/worker/handle_alter.rs, src/servers/src/error.rs
Mito engine returns ok on outdated requests. It confuses the caller to know if the request is actually performed. This PR changes the behavior on outdated alter request. It will now return a new status code `RequestOutdated` instead of an incorrect success.
=> feat: return request outdated error on handling alter

src/metric-engine/src/data_region.rs, src/metric-engine/src/engine/put.rs
Avoid memory problem caused by null fields. By not mapping tag to field in metric engine.
Peak memory drops from ~24GB to ~10GB
=> feat: don't map semantic type in metric engine

Cargo.lock, src/index/Cargo.toml, src/index/src/inverted_index/create/sort/intermediate_rw.rs
`futures_util::forward()` will flush and close the writer when stream is finished. From its document https://docs.rs/futures-util/0.3.30/futures_util/stream/trait.StreamExt.html#method.forward :
>It will complete once the stream is exhausted, the sink has received and flushed all items, and the sink is closed.
Test can pass before because `Vec` won't report errors when it gets closed twice.
=> fix: IntermediateWriter closes underlying writer twice

src/common/meta/src/ddl/create_logical_tables.rs, src/common/meta/src/rpc/ddl.rs, src/operator/src/insert.rs
Batch create tables on prometheus wtrite
=> feat: create tables in batch on prom write

src/servers/src/lib.rs, src/servers/src/mysql/server.rs
This pr prevents tedious log info from MySQL port being scanned 
1. adjusts MySQL connection remote addr log from info to debug
2. stops logging `ConnectionAborted` error
=> chore: adjust MySQL connection log

src/mito2/src/sst/parquet/reader.rs
Min/max index from parquet stats doesn't take efforts if predicates are referencing unprojected column.
=> fix: decouple columns in projection and prune

.github/workflows/develop.yml
=> chore: switch to free machine

src/frontend/src/instance.rs, src/frontend/src/instance/grpc.rs, src/operator/src/expr_factory.rs, src/operator/src/insert.rs, src/operator/src/req_convert/insert/stmt_to_region.rs, src/operator/src/statement.rs, src/operator/src/statement/ddl.rs, src/operator/src/statement/describe.rs, src/operator/src/table.rs, src/sql/src/parsers/create_parser.rs, src/sql/src/statements.rs, tests/cases/standalone/common/alter/alter_table_default.result, tests/cases/standalone/common/alter/alter_table_default.sql, tests/cases/standalone/common/insert/insert_default_timezone.result, tests/cases/standalone/common/insert/insert_default_timezone.sql
真 の Final Piece of #2907 :
* SQL insertion with date/datetime/timestamp literals should respect the session timezone while parsing.
* Create table or alter table that contains column default constraint value aware of session timezone.
#2907
=> fix: SQL insertion and column default constraint aware of timezone

.github/actions/build-greptime-binary/action.yml, .github/actions/upload-artifacts/action.yml, .github/workflows/develop.yml, docker/dev-builder/ubuntu/Dockerfile, tests/runner/src/env.rs, tests/runner/src/main.rs, tests/runner/src/util.rs
Reuse the built GreptimeDB binary in CI. Let's see if it can save some time and money.
=> ci: build GreptimeDB binary for later use

src/mito2/src/sst/version.rs
Make adding same SST file multiple times possible, instead of panic there.
=> refactor: add same SST files

src/common/time/src/datetime.rs
allow parsing Timestampe wiht fraction part like `1970-01-01 00:00:00.042`, which is supported in arrow's  Array cast, so it make sense to maintance consistency
support decimal fraction part in `DateTime::from_str` , i.e. `1970-01-01 00:00:00.042`
=> feat: support fraction part in timestamp

src/cmd/src/standalone.rs
Use `fe_opts` processed by `setup_frontend_plugins` instead of original `MixOptions::FrontendOptions`
=> fix: use `fe_opts` after `setup_frontend_plugins` in standalone

src/common/error/src/status_code.rs
fix incorrect StatusCode parsing
close #3279
=> fix: fix incorrect StatusCode parsing

src/cmd/src/standalone.rs, src/common/catalog/src/lib.rs, src/servers/src/mysql/handler.rs, src/session/src/lib.rs
1. start frontend plugins during startup in standalone mode
2. use current session's catalog if none is provided during MySQL's use statement
=> chore: start plugins during standalone startup & comply with current catalog while changing database

config/frontend.example.toml, src/catalog/src/kvbackend.rs, src/catalog/src/kvbackend/client.rs, src/catalog/src/metrics.rs, src/cmd/src/cli/repl.rs, src/cmd/src/frontend.rs, src/meta-client/src/lib.rs, tests-integration/src/cluster.rs
As title says: this pr mainly support cache for batch_get in CachedMetaKvBackend.
=> feat: support cache for batch_get in CachedMetaKvBackend

src/promql/src/planner.rs
The promql planner is used to construct a table scan plan with inlined filter. But it turns out that (1) not all filters are supported to be in table scan and (2) substrait encoder will discard those inlined filters. Thus this PR put all filters into a dedicated plan to make sure they are executed.
=> feat: put all filter exprs in a filter plan separately

src/mito2/src/error.rs, src/mito2/src/sst/index/creator.rs
Hope it can polish the error message.
=> chore(index): add BiError to fulfil the requirement of returning two errors

Cargo.lock, src/index/src/inverted_index/search/index_apply.rs, src/index/src/inverted_index/search/index_apply/predicates_apply.rs, src/mito2/Cargo.toml, src/mito2/src/access_layer.rs, src/mito2/src/cache/write_cache.rs, src/mito2/src/engine/basic_test.rs, src/mito2/src/metrics.rs, src/mito2/src/sst/index.rs, src/mito2/src/sst/index/applier.rs, src/mito2/src/sst/index/creator.rs, src/mito2/src/sst/parquet.rs, src/mito2/src/sst/parquet/reader.rs, src/mito2/src/sst/parquet/row_selection.rs
Adjusting the segment row count from 102400 (row group size) to 1024 helps provide a finer granularity of filtering than the row group level, which greatly enhances the filtering capability of the inverted index.
In the personal testing scenario, an improvement of over **5x** was achieved.
```
2024-02-06T11:12:47.571445Z DEBUG mito2::sst::parquet::reader: Read parquet 4651449581568(1083, 0) 0ae417c3-8a95-4aa1-a582-db73ad3eaa3e, range: (Timestamp { value: 1707157248569, unit: Millisecond }, Timestamp { value: 1707157257567, unit: Millisecond }), 7/7 row groups, metrics: Metrics { num_row_groups_before_filtering: 7, num_row_groups_inverted_index_filtered: 0, …
```
=> feat(mito): adjust seg size of inverted index to finer granularity instead of row group level

Makefile, src/object-store/src/util.rs
Replaced `opendal::raw::normalize_path` with own implementation of `normalize_path` in order to fix expected behaviour of not trimming leading `'/'`.
Also fixed some typing errors (I believe) when I was reading the Makefile.
Closes #3212
=> fix(util): join_path function should not trim leading `/`

src/promql/src/planner.rs, tests/cases/standalone/common/system/information_schema.result, tests/cases/standalone/common/system/information_schema.sql, tests/cases/standalone/common/tql/case_sensitive.result, tests/cases/standalone/common/tql/case_sensitive.sql
Use `TableReference::bare` to avoid unnecessary escaping or parsing
=> fix: correct the case sensitivity behavior for PromQL

README.md
=> chore: update link to official website link

docker/ci/centos/Dockerfile, docker/ci/ubuntu/Dockerfile
This fixes https://github.com/GreptimeTeam/greptimedb/issues/3298
Start the latest version of the greptime docker image and have an error:
```
Events:
Type     Reason     Age                 From               Message
----     ------     ----                ----               -------
Normal   Scheduled  2m12s               default-scheduler  Successfully assigned default/e2e-cluster-meta-c4b459789-z88zc to kind-control-plane
Normal   Pulled     22s                 kubelet            Successfully pulled image "greptime/greptimedb:latest" in 1m50.002557716s (1m50.002580925s including waiting)
Normal   Created    17s (x2 over 22s)   kubelet            Created container meta …
```
=> fix: $TARGET_BIN not found when docker run the image 

src/mito2/src/config.rs
=> fix(index): sanitize S3 upload buffer size

.github/workflows/develop.yml, tests/cases/standalone/common/function/system.result, tests/cases/standalone/common/function/system.sql
WIP - see why sqlness tests fail.
=> fix: commit_short sqlness test case 

.github/workflows/develop.yml, .github/workflows/docs.yml
Run `docs.yml` and `develop.yml` jobs in draft PR. Only `coverage` is ignored as it uses a large runner.
=> ci: run CI jobs in draft PR

.github/workflows/release.yml
add wait for `build-macos-artifacts`、`build-windows-artifacts` job completes.
upgrade slack-github-action to v1.25.0.
=> ci: add build artifacts needs in notification

src/common/meta/src/error.rs, src/common/meta/src/key/table_route.rs
=> feat: batch get physical table routes

Cargo.lock, src/common/meta/Cargo.toml, src/common/meta/src/ddl/create_logical_tables.rs, src/common/meta/src/key.rs, src/common/meta/src/key/table_info.rs, src/common/meta/src/key/table_route.rs, src/common/meta/src/key/txn_helper.rs, src/common/meta/src/kv_backend/etcd.rs, src/common/meta/src/kv_backend/txn.rs
Creating logical tables requires batch writing metadata by utilizing `txn` for executing a write transaction. However, our txn has a default upper limit of 128 operations due to the constraints set by etcd storage. We prefer not to have users alter the default etcd configuration to maintain user experience.
To work around this limitation, I divide the data before batching it for writing. Even though these operations are not within a single transaction, rest assured that they are secure and will be retried by the `procedure` until all succeed.
Close #3285
=> fix: split write metadata request

src/mito2/src/access_layer.rs, src/mito2/src/cache/write_cache.rs, src/mito2/src/region/options.rs, src/mito2/src/sst/index.rs, src/mito2/src/sst/parquet.rs
Make `segment_row_count` configurable.
=> refactor(index): move option `segment_row_count` from WriteOptions to IndexOptions

src/mito2/src/engine/basic_test.rs, src/mito2/src/error.rs, src/mito2/src/row_converter.rs, src/mito2/src/sst/index/applier/builder.rs, src/mito2/src/sst/index/codec.rs, src/mito2/src/sst/index/creator.rs
Previously, when encoding string keys into an FST using the memcomparable format, additional prefixes and suffixes beyond the original string data were added, which could lead to inaccuracies under certain regex query conditions. This PR specifically addresses the encoding of strings: encoding is now done directly based on the original data.
Additionally, unit tests related to `SstIndexCreator` have been added. These tests link together both the construction and querying of indexes, increasing confidence in their correctness.
=> fix(index): encode string type to original data to enable fst regex to work

src/mito2/src/memtable.rs, src/mito2/src/memtable/merge_tree.rs, src/mito2/src/memtable/merge_tree/data.rs, src/mito2/src/memtable/merge_tree/dict.rs, src/mito2/src/memtable/merge_tree/metrics.rs, src/mito2/src/memtable/merge_tree/partition.rs, src/mito2/src/memtable/merge_tree/shard.rs, src/mito2/src/memtable/merge_tree/shard_builder.rs, src/mito2/src/memtable/merge_tree/tree.rs
This PR defines common structs for a new memtable, the merge tree memtable.
- The merge tree memtable divides a tree into multiple partitions.
- Each partition contains multiple shards.
- Each shard contains a key dictionary and a list of data parts.
- The tree finds a shard by a row's primary key and inserts the row into the mutable data part of the shard.
- It freezes mutable parts into immutable parts and merges them later
It also ports necessary codes to implement the `Memtable` trait from the time series memtable.
- #2804
=> feat: Defines structs in the merge tree memtable

Cargo.lock, src/metric-engine/Cargo.toml, src/metric-engine/src/engine.rs, src/metric-engine/src/engine/create.rs, src/metric-engine/src/engine/open.rs, src/metric-engine/src/engine/options.rs
* ignore building index on column `tsid` to save space.
* set seg row count to 256 to improve query performance of metric engine
=> feat(metric-engine): set index options for data region

Cargo.lock, src/common/telemetry/Cargo.toml, src/common/telemetry/src/logging.rs
Check if stdout is redirected for the logging layer. And disable ansi control char if it's redirected to a non-tty file.
log with `greptime standalone start`:
log with `greptime standalone start > greptime.log`
Closes #3323
=> fix: disable ansi contorl char when stdout is redirected

src/mito2/src/error.rs, src/mito2/src/memtable/merge_tree/data.rs, src/mito2/src/test_util/memtable_util.rs
Add impl for the data buffer related structs for `MergeTreeMemtable`.
- #2804
=> feat: data buffer and related structs

Cargo.lock, src/mito2/Cargo.toml, src/mito2/src/memtable/merge_tree/dict.rs
This PR implements the KeyDictBuilder for the merge tree memtable
- Each builder has fixed capacity
- It interns key and returns an index to get the key from the builder again
- It can scan keys in sorted order from the builder
- It can build a KeyDict by invoking `finish()`
- It will replace pk index with a new value so the pk index has the same order the key
- #2804
=> feat: Implement KeyDictBuilder for the merge tree memtable

scripts/fetch-dashboard-assets.sh
=> chore: support configure GITHUB_PROXY_URL when fetch dashboard assets

.github/actions/build-windows-artifacts/action.yml, .github/workflows/develop.yml, .github/workflows/nightly-ci.yml
> No files were found with the provided path: /home/runner/work/_temp/greptime-*.log. No artifacts will be uploaded.
Try `/tmp/greptime-*.log`.
=> ci: try fix log location

Cargo.lock, tests-integration/Cargo.toml
See https://github.com/cloudwalk/axum-test-helper/pull/8 and compared with https://github.com/cloudwalk/axum-test-helper/compare/main...sunng87:axum-test-helper:patch-1.
=> build(deps): axum-tets-helper has included patch-1

src/mito2/src/memtable/merge_tree/data.rs
Impl `DataBuffer::freeze` method, which sorts rows in `DataBuffer` according to pk weights and replaces pk_index values with pk_weights directly.
=> feat: replace pk index with pk_weight during freeze

.github/actions/build-linux-artifacts/action.yml, .github/actions/build-macos-artifacts/action.yml, .github/actions/build-windows-artifacts/action.yml, .github/workflows/develop.yml, .github/workflows/nightly-ci.yml
=> ci: upgrade actions to node20-based version

src/store-api/src/path_utils.rs
=> chore: remove unused deprecated table_dir_with_catalog_and_schema

src/mito2/src/error.rs, src/mito2/src/memtable/merge_tree/data.rs
- Define `DataPart` and `DataParts`, and add `read` method for it.
- Rename `iter` method in `DataBuffer` to `read` as it no long implements `Iterator` trait.
- #2804
=> feat: merge tree data parts 

Cargo.lock, src/flow/Cargo.toml, src/flow/src/expr/error.rs, src/flow/src/expr/func.rs, src/flow/src/expr/scalar.rs
Add impl for ScalarExpr&Scalar Functions
- Added impl code which eval Unary, Binary and Variadic Func
- Added utilty functions for `ScalarExpr` like get supporting(column being used in expression) column for a ScalarExpr.
- Most importantly, added utility functions for Temporal Filter, which can extract bounding condition including `now()` function and comparsion expression and express sliding windows etc.
useful methods for Scalar Expr, and `eval` method for Scalar function
=> feat(flow): impl ScalarExpr&Scalar Function

Cargo.lock, src/common/datasource/src/object_store.rs, src/operator/Cargo.toml, src/operator/src/statement/copy_database.rs
This PR converts the temp dir path to an object store style path in `list_files_and_parse_table_name`.
The `C:\Users\abc\temp` becomes `C:/Users/abc/temp` which is the supported form of us.
Users who'd like to use copy database on Windows should use unix-like path. See https://github.com/GreptimeTeam/greptimedb/issues/3195
fixes https://github.com/GreptimeTeam/greptimedb/issues/3301
=> test: fix list_files_and_parse_table_name path issue on windows

.github/workflows/docs.yml
(yet another fix for the dumb GHA ruleset)
Align the jobs to `develop.yml`.
=> ci: align docs workflow jobs with develop.yml

Cargo.toml
Fix a typo from https://github.com/GreptimeTeam/greptimedb/pull/3352, which would emit warnings like
I also add a `deny` lint to prevent the same error. It works like
=> fix: typo in lint config

src/common/meta/Cargo.toml, src/common/meta/src/ddl/create_logical_tables.rs, src/common/meta/src/ddl/table_meta.rs, src/common/meta/src/ddl/tests.rs, src/common/meta/src/ddl/tests/create_logical_tables.rs, src/common/meta/src/ddl/truncate_table.rs, src/common/meta/src/key/table_route.rs, src/common/meta/src/rpc/ddl.rs
1. refactor: allocate table ids in the procedure
2. test: add tests for CreateTableLogicalProcedure
#3233
Waits for #3271
=> refactor: allocate table ids in the procedure

src/mito2/src/memtable/key_values.rs, src/mito2/src/request.rs
As the title. Test result:
- Cut put latency by half
- Double put throughput (18w to 42w)
| Before | After |
|--------|--------|
| ![image](https://github.com/GreptimeTeam/greptimedb/assets/15380403/37c1dbe0-c4f1-4348-b98a-850c96a6cfc1) | ![image](https://github.com/GreptimeTeam/greptimedb/assets/15380403/fda37378-2a36-44cc-b809-7d574d19896e) | 
- No regression in TSBS (and somehow has a little improvement...)
Before
```
Summary:
loaded 1036800000 metrics in 190.468sec with 6 workers (mean rate 5443439.71 metrics/sec)
loaded 103680000 rows in 190.468sec with 6 workers (mean rate 544343.97 rows/sec)
```
After
```
Summary:
loaded 1036800000 metrics in 187.196sec with 6 workers …
```
=> feat: skip filling NULL for put and delete requests

src/cmd/src/datanode.rs, src/cmd/src/frontend.rs, src/cmd/src/lib.rs, src/cmd/src/standalone.rs, src/datanode/src/datanode.rs, src/datanode/src/service.rs, src/frontend/src/instance.rs, src/frontend/src/instance/builder.rs, src/frontend/src/server.rs, src/meta-srv/src/bootstrap.rs, src/meta-srv/src/metasrv/builder.rs, src/servers/src/http.rs, src/servers/src/server.rs
... so we can use port 0 in testing. Also make http service not blocking the future.
=> refactor: set the actual bound port in server handler

src/mito2/src/memtable/merge_tree.rs, src/mito2/src/memtable/merge_tree/data.rs, src/mito2/src/memtable/merge_tree/merger.rs
This PR implements the merge reader for `DataParts` that merges data bacthes from all parts inside one `DataParts`, and yield batches according to pk weight and timestamp.
- #2804
=> feat: impl merge reader for DataParts

src/mito2/src/memtable/merge_tree/data.rs, src/mito2/src/memtable/merge_tree/merger.rs, src/mito2/src/memtable/merge_tree/shard_builder.rs
This PR handles different `read`/`freeze` paths of `DataBuffer` in different components 😵‍💫
- For `DataBuffer::read` inside `ShardBuilder`
- `pk_weights` must be present, yielded rows are sorted according to weights
- `replace_pk_index` set to false as pk dict are not frozen yet
- `keep_data` set to true
- For `DataBuffer::freeze` inside `ShardBuilder`
- `pk_weights` must be present, yielded rows are sorted according to weights
- `replace_pk_index` set to true so that yielded `DataPart` contains only weights
- `keep_data` set to false as we need to take the values
- For `DataBuffer::read` inside `Shard`
- `pk_weights` set to None as DataBuffer in Shard has already replaced …
=> feat: distinguish between different read paths

src/sql/src/statements.rs
=> fix: treat "0" and "1" as valid boolean values.

src/mito2/src/memtable/merge_tree/data.rs, src/mito2/src/memtable/merge_tree/merger.rs
This PR removes the associated type `Item` from the `Node` trait of the merger mod. It is helpful to support `?Size` item of a node.
Now the `DataBatch` is a slice of the referencing `RecordBatch`.
- It doesn't own the `RecordBatch`.
- It should only access the range of the `RecordBatch`.
- `DataBatchRange` maintains the range of a `DataBatch`.
This avoids slicing the `RecordBatch` via `RecordBatch::slice()`.
- #2804
=> refactor: Remove Item from merger's Node trait

src/mito2/src/flush.rs, src/mito2/src/memtable.rs, src/mito2/src/memtable/merge_tree.rs, src/mito2/src/memtable/time_series.rs, src/mito2/src/memtable/version.rs, src/mito2/src/read/seq_scan.rs, src/mito2/src/region/opener.rs, src/mito2/src/region/version.rs, src/mito2/src/test_util/memtable_util.rs, src/mito2/src/test_util/version_util.rs, src/mito2/src/worker/handle_flush.rs
This PR changes some APIs of the memtable
- Renames `mark_immutable()` to `freeze()`. `freeze()` turns a mutable memtable into an immutable memtable and this operation is fallible.
- Adds a `fork()` method to create a new mutable memtable from an immutable memtable.
- It allows the new memtable to reuse some data in the old memtable
- The `iter()` method is fallible.
Now the region instead of the memtable builder generates the memtable id. So the memtable builder needs to take a memtable id to build a new memtable.
- #2804
=> feat: Add freeze and fork method to the memtable

src/mito2/src/memtable/merge_tree.rs, src/mito2/src/memtable/merge_tree/data.rs, src/mito2/src/memtable/merge_tree/dedup.rs, src/mito2/src/memtable/merge_tree/merger.rs, src/mito2/src/memtable/merge_tree/partition.rs, src/mito2/src/memtable/merge_tree/shard.rs, src/mito2/src/memtable/merge_tree/shard_builder.rs, src/mito2/src/test_util/memtable_util.rs
This PR:
- adds `dedup` config to `Shard`/`ShardBuilder/DataBuffer` etc. to control whether rows with duplicate ts should be removed
- impls `DedupReader` so that we can remove duplicated rows among different data batches.
- #2804
=> feat: merge tree dedup reader

src/mito2/src/memtable/merge_tree.rs, src/mito2/src/memtable/merge_tree/data.rs, src/mito2/src/memtable/merge_tree/dict.rs, src/mito2/src/memtable/merge_tree/partition.rs, src/mito2/src/memtable/merge_tree/shard.rs, src/mito2/src/memtable/merge_tree/shard_builder.rs, src/mito2/src/memtable/merge_tree/tree.rs
This PR mainly implements the `iter()` method for the new memtable.
- The `iter()` method returns a `TreeIter` to iterate partitions
- The memtable can use filters to prune partitions
- The `TreeIter` read partitions one by one
- For each partition, the iter creates a `PartitionReader`
- The `PartitionReader` merges `DataBatches` from different `ShardReaderImpls` and the `ShardBuilderReaders`
- Each `ShardReader` merges `DataBatches` from different data parts.
Unresolved problem:
- Integrates with the `DedupReader`
- #2804
=> feat: Implement iter for the new memtable

src/mito2/src/test_util/memtable_util.rs
remove unused imports in memtable_util.rs. Clippy does not deny these unused imports as we explicitly allow this.
https://github.com/GreptimeTeam/greptimedb/blob/f81e37f508db98b7ade460f323dbc1640e0520af/src/mito2/src/lib.rs#L23
=> fix: remove unused imports in memtable_util.rs

src/mito2/src/config.rs, src/mito2/src/engine/basic_test.rs, src/mito2/src/memtable/key_values.rs, src/mito2/src/memtable/merge_tree.rs, src/mito2/src/memtable/merge_tree/data.rs, src/mito2/src/memtable/merge_tree/dedup.rs, src/mito2/src/memtable/merge_tree/dict.rs, src/mito2/src/memtable/merge_tree/partition.rs, src/mito2/src/memtable/merge_tree/shard.rs, src/mito2/src/test_util/version_util.rs, src/mito2/src/worker.rs
This PR implements dedup for the new memtable. It adds a config to the `MitoConfig` to enable the new table.
This PR contains some bug fixes while testing the new memtable.
- It fixes an issue that the `PartitionReader` doesn't prune the first entry its underlying source returns.
- It also fixes that the `KeyValue` returns incorrect field num.
- #2804
=> feat: Implement dedup for the new memtable and expose the config

src/mito2/src/memtable.rs, src/mito2/src/memtable/merge_tree/data.rs, src/mito2/src/memtable/merge_tree/dedup.rs, src/mito2/src/memtable/merge_tree/dict.rs, src/mito2/src/memtable/merge_tree/partition.rs, src/mito2/src/memtable/merge_tree/shard.rs, src/mito2/src/memtable/merge_tree/shard_builder.rs, src/mito2/src/memtable/merge_tree/tree.rs
Change the receivers of merge tree components' read methods to `&self` instead of `&mut self` so that `Partition::read` does not need to acquire write lock.
- #2804
=> refactor: change the receivers of merge tree components

src/mito2/src/worker.rs
Change the static region worker mapping method. Remove hashing and use modulo instead.
Hashing mapping is not quite predictable. The new mapping considers table id and region number separately, so regions from one table won't get into the same worker.
This is a workaround and the workload skew problem still exists, and will exist if we don't support mechanisms like work stealing or dynamic mapping.
=> feat: change how region id maps to region worker

Cargo.lock, src/frontend/src/server.rs, src/servers/Cargo.toml, src/servers/src/error.rs, src/servers/src/mysql/server.rs, src/servers/src/postgres/server.rs, src/servers/src/tls.rs, src/servers/tests/mysql/mysql_server_test.rs, src/servers/tests/postgres/mod.rs, tests-integration/src/test_util.rs
Part 1 of implementation for #3255
This patch caches TLS `ServerConfig` in a mutable container to make it possible to update by other threads. `TlsAcceptor` is a lightweight container of `ServerConfig` so it's OK to create for each connnection.
This patch also includes a file system watcher to detect file change of certificates/keys and reload them as needed.
=> feat: make tls certificates/keys reloadable (part 1)

grafana/greptimedb.json
This patch contains two changes to grafana dashboard config:
https://github.com/GreptimeTeam/greptimedb/issues/3262
=> feat(grafana): enable shared tooltip, add raft engine throughput

.github/workflows/release.yml
Notification job cannot get build result in this checker: 
```
if: ${{ needs.release-images-to-dockerhub.outputs.build-image-result == 'success' && needs.build-windows-artifacts.outputs.build-windows-result == 'success' && needs.build-macos-artifacts.outputs.build-macos-result == 'success' }}
```
$GITHUB_OUTPUT share between job but need to define outputs, like [this](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs).
=> ci: add builder result outputs in release action

src/common/meta/src/ddl/create_table.rs
Throw errors instead of panic.
=> fix: throw errors instead of panic

src/mito2/src/memtable/merge_tree/data.rs
This PR enables ZSTD compression and column-wise encodings in `DataPart` in merge tree memtable to save memory up to 90%.
Total memory consumption for freezing a `DataBuffer` with 10M rows to `DataPart` and iterating all batches from that `DataPart`:
> * Elapsed time means the total time for freezing`DataBuffer` with 10 million rows to `DataPart` and iterating that `DataPart`.
|Type| Encoded part size| Elapsed time|
|:-:|:-:|:-:|
|Raw| 315MB (1260%)| 2.98s (102%)|
|Encodings only| 166MB (664%)|2.91s (100%)|
|Zstd only|49MB(196%)|3.80s (131%)|
|Zstd&encodings|25MB(100%) |3.30s (113%)|
- #2804
=> feat: enable zstd compression and encodings in merge tree data part

src/mito2/src/memtable/merge_tree.rs, src/mito2/src/memtable/merge_tree/dict.rs, src/mito2/src/memtable/merge_tree/partition.rs, src/mito2/src/memtable/merge_tree/shard.rs, src/mito2/src/memtable/merge_tree/shard_builder.rs, src/mito2/src/test_util/memtable_util.rs
This PR adds a partition level map to replace the shard level map to look up pk indices. This can improve pk index lookup performance as we don't need to iterate all shards to find the pk index.
- Pk indices inside a dictionary builder can't be compared directly. We collect pk indices after we freeze a dictionary and then write them to the partition level map.
- Now we evict the whole partition once we reach the dictionary memory limit so we can also drop the map on eviction.
This PR also fixes an issue that a key may be written to multiple shards if we find the key before finishing a shard builder.
- #2804
=> feat: Use a partition level map to look up pk index

src/mito2/src/memtable/merge_tree/data.rs, src/mito2/src/memtable/merge_tree/partition.rs, src/mito2/src/memtable/merge_tree/shard_builder.rs, src/mito2/src/memtable/merge_tree/tree.rs, src/mito2/src/metrics.rs
This PR adds following metrics for the read path of MergeTreeMemtable:
MERGE_TREE_DATA_BUFFER_FREEZE_STAGE_ELAPSED
- DataPartEncoder
- drain_data_buffer_to_record_batches (buffer_to_batch)
- ArrowWriter::write (encode)
MERGE_TREE_READ_STAGE_ELAPSED
- TreeIter
- TreeIter::fetch_next_partition (fetch_next_partition)
- TreeIter::next_batch
- PartitionReader::convert_current_batch (partition_data_batch_to_batch)
- PartitionReader::prune_batch_by_key (partition_prune_pk)
- PartitionReader::next (partition_read_source)
- ShardBuilderReader::next (*)
- DataBufferRead::next (read_data_buffer)
- ShardReader::next
- DataPartsReader::next (read_data_parts)
- DataBuffer::read …
=> chore: add metris for memtable read path

scripts/fetch-dashboard-assets.sh
This closes https://github.com/GreptimeTeam/greptimedb/issues/3401.
Mainly, it's because centos7's curl is older than that having this option supported. But if a cURL request hits connrefused, it's highly possibly the network is not connected. So no retry on such situation can be acceptable.
=> build: do not retry for connrefused

src/mito2/src/memtable/merge_tree/partition.rs, src/mito2/src/memtable/merge_tree/tree.rs
Fix some metrics in MergeTreeMemtable read path and add more metrics including partition stats.
=> fix: some read metrics

Cargo.lock, Cargo.toml, src/common/grpc/src/flight.rs
This closes #1445.
Although the issue suggests we enable compression for gRPC services also, I noticed that we are now initiating a lot of gRPC services. We may instead first sort out them so that we can determinate which services can turn on this feature and how their clients communicate with them.
=> feat: enable ArrowFlight compression

src/mito2/src/memtable/merge_tree/data.rs, src/mito2/src/memtable/merge_tree/dedup.rs, src/mito2/src/memtable/merge_tree/merger.rs, src/mito2/src/memtable/merge_tree/partition.rs, src/mito2/src/memtable/merge_tree/shard.rs, src/mito2/src/memtable/merge_tree/shard_builder.rs
This PR moves the costly sort and dedup operation inside `read_data_buffer_to_record_batch` function out of the read lock of `Partition`.
- #2804
=> refactor: move some costly methods in DataBuffer::read out of read lock

src/partition/src/splitter.rs
If a table has multiple regions, then when writing, it is necessary to split the data according to regions, which will incur memory copy overhead.
There is a scenario where the writes of the same client instance usually only contain data from one region (depending on the partition key). In this case, we should avoid memory copying.
=> feat: zero copy on split rows

src/partition/src/manager.rs
The region routes belong to the physical table but are shared among all logical tables.
That it to say, the region id points to the physical table, so we need to use the actual table id (which may be a logical table) to renew the region id when we want construct the `PartitionInfo`.
=> fix: partition region id

config/frontend.example.toml, config/standalone.example.toml, src/frontend/src/server.rs, src/servers/src/tls.rs, src/servers/tests/mysql/mysql_server_test.rs, src/servers/tests/postgres/mod.rs, tests-integration/tests/http.rs
This patch adds configuration item `watch` to `TlsOption` to control notify behaviour. 
part 2 of #3335 , Fixes #3255
=> feat: add configuration for tls watch option

Cargo.lock, src/mito2/Cargo.toml, src/mito2/benches/bench_merge_tree.rs, src/mito2/benches/merge_tree_bench.rs, src/mito2/src/memtable/merge_tree.rs, src/mito2/src/memtable/merge_tree/data.rs, src/mito2/src/memtable/merge_tree/merger.rs, src/mito2/src/memtable/merge_tree/partition.rs, src/mito2/src/memtable/merge_tree/shard.rs, src/mito2/src/memtable/merge_tree/shard_builder.rs, src/mito2/src/memtable/merge_tree/tree.rs, src/mito2/src/test_util/memtable_util.rs
This PR employs spase key encoding to encode primary keys to bytes for primary key to pk id look up.
=> feat: employ sparse key encoding for shard lookup

src/mito2/src/region/opener.rs
Previously, we aggregate all mutations from wal and write them into the memtable in a batching manner. Now, the mutations are written into the memtable in a streaming manner. We believe this transition could mitigate the memory spike issue during startup.
fixes #3226
=> fix: mitigate memory spike during startup

src/frontend/src/instance.rs, src/operator/src/expr_factory.rs, src/operator/src/statement.rs, src/operator/src/statement/ddl.rs, src/operator/src/statement/show.rs, src/query/src/sql.rs, src/session/src/context.rs, src/sql/src/parser.rs, src/sql/src/parsers/create_parser.rs, src/sql/src/statements/create.rs, src/sql/src/statements/statement.rs, tests/cases/standalone/common/create/create.result, tests/cases/standalone/common/create/create.sql
Support: `create table xxx like yyy`
ref: https://dev.mysql.com/doc/refman/8.0/en/create-table-like.html
```shell
public=> CREATE TABLE t1 ( a INT, b STRING, c INT, ts timestamp TIME INDEX);
OK 0
public=> CREATE TABLE t2 LIKE t1;
OK 0
public=> DESCRIBE t2;
Column |         Type         | Key | Null | Default | Semantic Type 
--------+----------------------+-----+------+---------+---------------
a      | Int32                |     | YES  |         | FIELD
b      | String               |     | YES  |         | FIELD
c      | Int32                |     | YES  |         | FIELD
ts     | TimestampMillisecond | PRI | NO   |         | TIMESTAMP
(4 rows)
```
Tips: 
I was using this …
=> feat: support `Create Table ... Like`

src/catalog/src/error.rs, src/catalog/src/kvbackend/client.rs, src/catalog/src/kvbackend/manager.rs, src/common/meta/src/ddl_manager.rs, src/servers/src/http/prom_store.rs, src/servers/src/metrics.rs, src/servers/src/prom_store.rs, src/servers/src/row_writer.rs
=> feat: tableref cache

src/servers/src/influxdb.rs, src/servers/src/prom_store.rs, src/servers/src/row_writer.rs
=> feat: reduce a clone of string

src/catalog/src/information_schema.rs, src/catalog/src/information_schema/schemata.rs, src/catalog/src/information_schema/tables.rs, src/operator/src/statement/show.rs, src/query/src/datafusion.rs, src/query/src/datafusion/planner.rs, src/query/src/error.rs, src/query/src/planner.rs, src/query/src/sql.rs, src/session/src/context.rs, tests-integration/src/tests/instance_test.rs, tests-integration/src/tests/test_util.rs, tests/cases/standalone/common/catalog/schema.result, tests/cases/standalone/common/catalog/schema.sql, tests/cases/standalone/common/create/create_database.result, tests/cases/standalone/common/show/show_databases_tables.result
#3354 
Main changes:
* Make `show tables` and `show databases` to query data from `information_schema` tables.
* Fixed `where` clause can't work properly, `SHOW FULL TABLES WHERE Table_type != 'VIEW'` for example.
=> refactor: show tables and show databases

src/frontend/src/instance.rs, src/frontend/src/instance/grpc.rs, src/frontend/src/instance/script.rs, src/frontend/src/metrics.rs, src/mito2/src/engine.rs, src/mito2/src/memtable/merge_tree/tree.rs, src/mito2/src/metrics.rs, src/mito2/src/read/scan_region.rs, src/mito2/src/read/seq_scan.rs, src/promql/src/metrics.rs, src/query/src/datafusion.rs, src/query/src/dist_plan/merge_scan.rs, src/query/src/lib.rs, src/query/src/metrics.rs, src/query/src/parser.rs, src/servers/src/grpc.rs, src/servers/src/http.rs, src/servers/src/http/handler.rs, src/servers/src/http/prometheus.rs, src/servers/src/metrics.rs, tests-integration/tests/http.rs
This PR improves existing metrics and adds more metrics for scan
- Adds an `attach_timer()` method and an `OnDone` stream adapter to observe the duration to fetch a stream, this fixes
- GRPC_HANDLE_PROMQL_ELAPSED
- GRPC_HANDLE_SQL_ELAPSED
- EXEC_PLAN_ELAPSED
- Removes the `METRIC_` prefix from metrics in query mod
- Move `track_metrics` to metrics mod and rename it
- Removes some metrics under servers mod as we already collect it in the HTTP middleware
- Combine query metrics into a histogram vec
- Register the gRPC metrics middleware
- Add more metrics to track scan cost
=> feat: Correct server metrics and add more metrics for scan

.github/workflows/release.yml
related to: https://github.com/actions/runner/issues/2224
The release notification failed to get `build-windows-result` variables.
=> ci: refine windows output env

src/frontend/src/instance/influxdb.rs, src/frontend/src/instance/otlp.rs, src/frontend/src/instance/prom_store.rs, src/frontend/src/instance/script.rs, src/servers/src/interceptor.rs
This pr mainly checks and adds interceptors for all frontend protocols we have supported. 
discussion: should we use feature gate to cover interceptor logic in OSS build target?
=> fix: complete interceptors for all frontend entry

Cargo.lock, config/datanode.example.toml, config/standalone.example.toml, src/mito2/Cargo.toml, src/mito2/src/config.rs, src/mito2/src/memtable.rs, src/mito2/src/memtable/merge_tree.rs, src/mito2/src/worker.rs, tests-integration/tests/http.rs
#2804 
Though still in experimental stage, we can replace `TimeSeriesMemtable` with `MergeTreeMemtable`.
This PR also modifies some of the default config of `MergeTreeMemtable`.
=> refactor: make MergeTreeMemtable the default choice

.github/workflows/release.yml, Cargo.lock, Cargo.toml
- https://github.com/GreptimeTeam/greptimedb/issues/3427
This PR bumps the db version to v0.7.0.
Wait for #3427 finished.
=> chore: bump version to v0.7.0

src/servers/src/http/authorize.rs, src/servers/tests/http/influxdb_test.rs
This closes #3436 
This pr mainly adds support for influxdb basic authorization. See [authenticate-with-basic-authentication](https://docs.influxdata.com/influxdb/v1/administration/authentication_and_authorization/#authenticate-with-basic-authentication)
=> fix: add support for influxdb basic auth

Makefile
=> chore: add bin opt to build cmd

src/operator/src/statement.rs, src/servers/src/mysql/federated.rs
The "set"s are:
- ignored:
- `set bytea_output` and `set datestyle` (both have issues tracked) from pg
- `set profiling` from mysql. It's not something we will impl (rather we may prefer tracing instead). Plus it's deprecated. See [here](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_profiling)
- validated:
- `set client_encoding` from pg. Must be "utf8" because it's universal and sufficient, and we don't bother to convert bytes around.
=> feat: impl some "set"s to adapt to some client apps

.github/workflows/develop.yml
Each fuzz test will add a new binary target. Therefore, we should specify the binary name in `Cargo build`.
=> chore: specify binary name

tests-fuzz/src/context.rs, tests-fuzz/src/fake.rs, tests-fuzz/src/generator.rs, tests-fuzz/src/generator/alter_expr.rs, tests-fuzz/src/generator/create_expr.rs, tests-fuzz/src/generator/insert_expr.rs, tests-fuzz/src/ir.rs, tests-fuzz/src/ir/alter_expr.rs, tests-fuzz/src/ir/create_expr.rs, tests-fuzz/src/test_utils.rs, tests-fuzz/src/translator/mysql/alter_expr.rs, tests-fuzz/src/translator/mysql/insert_expr.rs, tests-fuzz/src/translator/mysql/select_expr.rs, tests-fuzz/src/translator/postgres/alter_expr.rs
#3174 
Separating the quote char and value allows us to cover more cases easily.
=> refactor: separate the quote char and value

src/cmd/src/cli/bench.rs, src/cmd/src/cli/upgrade.rs, src/cmd/src/metasrv.rs, src/common/meta/src/error.rs, src/common/meta/src/key.rs, src/common/meta/src/key/test_utils.rs, src/common/meta/src/kv_backend/etcd.rs, src/common/meta/src/kv_backend/txn.rs, src/meta-srv/examples/kv_store.rs, src/meta-srv/src/bootstrap.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/mocks.rs, src/operator/src/insert.rs, tests-integration/src/cluster.rs
Add `max_txn_ops` option for metasrv. If using etcd as the store, this value should be less than or equal to the `--max-txn-ops` option value of etcd. If using another store, this option can be ignored.
=> feat: max-txn-ops option

src/mito2/src/memtable/merge_tree.rs, src/mito2/src/memtable/merge_tree/data.rs, src/mito2/src/memtable/merge_tree/dedup.rs, src/mito2/src/memtable/merge_tree/partition.rs, src/mito2/src/memtable/merge_tree/shard.rs, src/mito2/src/memtable/merge_tree/shard_builder.rs, src/mito2/src/row_converter.rs
This PR improves the pruning speed of the new memtable
- Adds `decode_value_at()` method to decode a value at a specific position in the primary key
- It will skip values before the position
- Stores offsets in a buffer so we can reuse them while there are multiple filters to prune
- Adds a `PrimaryKeyFilter` to filter primary keys via `decode_value_at()`
- Pushes down filters to `Shards` and `ShardBuilder` to reduce DataBatch returned to the partition reader
- #2804
=> perf: Reduce decode overhead during pruning keys in the memtable

src/servers/src/http/error_result.rs, tests-integration/tests/http.rs
#2888 
to make HTTP API returns status code, I changed the returning value of `ErrorResponse::into_response` and map `code` to `StatusCode`. Here is the returning mapping:
```rust
Success, Cancelled ==> OK(200);
Unsupported, InvalidArguments, InvalidSyntax, RequestOutdated, 
RegionAlreadyExists, TableColumnExists, TableAlreadyExists, 
DatabaseNotFound, TableNotFound, TableColumnNotFound ==> `BAD_REQUEST`(400);
PermissionDenied, AuthHeaderNotFound, InvalidAuthHeader, 
UserNotFound, UnsupportedPasswordType, UserPasswordMismatch, 
RegionReadonly ==> `UNAUTHORIZED`(401)
AccessDenied ==> `FORBIDDEN`(403)
Internal, Unexpected, Unknown, StorageUnavailable,
RegionNotReady, RegionBusy, …
```
=> refactor: make http api returns non-200 status code

src/common/recordbatch/src/adapter.rs, src/common/recordbatch/src/lib.rs, src/common/recordbatch/src/util.rs, src/file-engine/src/query.rs, src/query/src/metrics.rs, src/script/src/python/engine.rs, src/table/src/table/numbers.rs, src/table/src/table/scan.rs, src/table/src/test_util/memtable.rs
`output_ordering` and `metrics` of `RecordBatchStream` used to have default implementation, which might be left out unconsciously when creating a new stream struct. This pr removes the default implementation.
=> fix: impl `RecordBatchStream` method explicitly

Cargo.toml, src/datatypes/src/value.rs, src/sql/src/parsers/create_parser.rs, src/sql/src/statements.rs, tests/cases/standalone/common/create/create.result, tests/cases/standalone/common/create/create.sql
fix #3479
Enable the `float_roundtrip` of `serde_json`, it makes f64 -> JSON -> f64 produces output identical to the input.
However, this comes at an approximately 2x performance cost for parsing floats compared to the default best-effort precision.
See also: 
- https://github.com/serde-rs/json/blob/master/
- https://github.com/serde-rs/json/issues/536
=> fix: fix f64 has no sufficient precision during parsing

tests-integration/fixtures/etcd/docker-compose-standalone.yml
Try to pull etcd from https://github.com/zcube/bitnami-compat/pkgs/container/bitnami-compat%2Fetcd to avoid rate limit. Another registry we can try is https://quay.io/repository/coreos/etcd?tab=tags&tag=latest
=> ci: use another mirror for etcd image

Cargo.lock, tests-fuzz/src/error.rs, tests-fuzz/src/generator/create_expr.rs, tests-fuzz/src/validator.rs, tests-fuzz/src/validator/column.rs, tests-fuzz/targets/fuzz_create_table.rs
#3174 
Add columns validation step of creating table fuzz tests
=> feat(fuzz): validate columns

src/mito2/src/memtable/merge_tree.rs, src/mito2/src/memtable/merge_tree/data.rs, src/mito2/src/memtable/merge_tree/partition.rs, src/mito2/src/memtable/merge_tree/shard.rs, src/mito2/src/memtable/merge_tree/shard_builder.rs, src/mito2/src/memtable/merge_tree/tree.rs, tests-integration/tests/http.rs
- https://github.com/GreptimeTeam/greptimedb/issues/3467
- https://github.com/GreptimeTeam/greptimedb/issues/2804
This PR fixes an issue that a shard never freezes its data buffer.
- It adds `data_freeze_threshold` to the `Shard` and checks whether the shard needs to freeze in `write_with_pk_id()`.
- It enlarges default data_freeze_threshold to 131072
It also corrects some metrics in the PartitionContext as we share it across partitions.
We might need to test the write performance again after merging this PR.
=> fix: freeze data buffer in shard

src/common/datasource/src/object_store/s3.rs, src/mito2/src/region/opener.rs, src/mito2/src/region/options.rs, src/sql/src/error.rs, src/sql/src/parsers/create_parser.rs, src/sql/src/statements/create.rs, src/store-api/src/lib.rs, src/store-api/src/mito_engine_options.rs, src/table/src/requests.rs, tests-integration/src/tests/instance_test.rs, tests/cases/standalone/common/create/create_with_options.result, tests/cases/standalone/common/create/create_with_options.sql, tests/cases/standalone/common/show/show_create.result, tests/cases/standalone/common/show/show_create.sql
fixes https://github.com/GreptimeTeam/greptimedb/issues/3476
This PR removes the validation for table options in the create parser as different engine might require different extra options.
Now we can specify engine related options via `with` statement. The following statement sets compaction time window to 1 day.
```sql
CREATE TABLE IF NOT EXISTS `test_table` (
`ts` TIMESTAMP(3) NOT NULL DEFAULT current_timestamp(),
`id` INT NULL,
`content` STRING NULL,
TIME INDEX (`ts`),
PRIMARY KEY (`id`)
)
ENGINE=mito
WITH(
'compaction.type' = 'twcs',
'compaction.twcs.time_window' = '1d',
regions = 1
);
```
Note that `compaction.type` is required if we want to set compaction options.
=> fix: allow passing extra table options

src/flow/src/expr.rs, src/flow/src/expr/linear.rs, src/flow/src/expr/relation.rs, src/flow/src/lib.rs, src/flow/src/plan.rs, src/flow/src/plan/join.rs, src/flow/src/plan/reduce.rs
#3187
Added basic plan for dataflow execution, support describe of basic map, reduce and join.
Basic Type defination that will be used in future PRs impl actual execution of those plans
=> feat(flow): plan def

src/common/time/src/timestamp.rs
Similar situation to https://github.com/chronotope/chrono/issues/1289
Fix the underflow and add some helper constant variables about min/max timestamp.
=> fix(common-time): allow building nanos timestamp from parts split from i64::MIN

Cargo.lock, src/common/time/src/timestamp.rs, tests-fuzz/Cargo.toml, tests-fuzz/src/generator/insert_expr.rs, tests-fuzz/src/ir.rs, tests-fuzz/src/ir/insert_expr.rs, tests-fuzz/src/translator/mysql/insert_expr.rs, tests-fuzz/src/validator/column.rs, tests-fuzz/targets/fuzz_insert.rs
#3174
Insert expr generator:
* Allow omitting some columns or omit all columns
* Allow generating null or default
value generator:
* make timestamp, datetime and date to generate valid value
Add insert target
=> feat(fuzz): add insert target

.github/workflows/develop.yml, tests-fuzz/Cargo.toml, tests-fuzz/src/context.rs, tests-fuzz/src/generator/alter_expr.rs, tests-fuzz/src/ir/create_expr.rs, tests-fuzz/src/validator/column.rs, tests-fuzz/targets/fuzz_alter_table.rs, tests-fuzz/targets/fuzz_create_table.rs
=> feat(fuzz): add alter table target 

.github/workflows/develop.yml
Try to setup docker cache to prevent limitation of pulling etcd images.
=> ci: attempt to setup docker cache for etcd

src/servers/src/error.rs, src/servers/src/http/error_result.rs, src/servers/src/http/header.rs
This patch removes `GREPTIME_DB_HEADER_ERROR_MSG` which tries to include error message in http header. Because the error message often contains characters that is invalid for http header, and the message size can also be too long for header.
Panic information:
```
2024-03-13T18:56:39.986929Z ERROR common_telemetry::panic_hook: panicked at greptimedb/src/servers/src/http/error_result.rs:88:41:
malformed error msg: InvalidHeaderValue backtrace=   0: common_telemetry::panic_hook::set_panic_hook::{{closure}}
at home/runner/work/greptimedb-cloud/greptimedb-cloud/greptimedb/src/common/telemetry/src/panic_hook.rs:37:25
1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call …
```
=> fix!: remove error message from http header to avoid panic

src/common/meta/src/sequence.rs
Sometimes the value in the kvbackend that is used to store the sequence could be pre-existed, even before the sequence has been built. If the value is smaller than the set initial of sequence, the sequence will start from the (smaller) value, which violates the intuition that sequence must start from initial. This PR fixes that.
=> fix: correctly generate sequences when the value is pre-existed

Cargo.lock, Cargo.toml
- https://github.com/GreptimeTeam/greptimedb/issues/3509
Bump version to v0.7.1
=> chore: bump version to v0.7.1

docs/benchmarks/tsbs/v0.7.0.md
This PR adds TSBS benchmark results of v0.7
=> docs: add v0.7 TSBS benchmark result

.github/actions/build-windows-artifacts/action.yml
add bin options in the Windows release configuration
=> ci: add bin options to reduce build burden

src/mito2/src/memtable.rs, src/mito2/src/memtable/key_values.rs, src/mito2/src/memtable/merge_tree.rs, src/mito2/src/memtable/merge_tree/tree.rs, src/mito2/src/memtable/time_partition.rs, src/mito2/src/memtable/time_series.rs, src/mito2/src/memtable/version.rs, src/mito2/src/region/opener.rs, src/mito2/src/region/options.rs, src/mito2/src/region/version.rs, src/mito2/src/test_util/memtable_util.rs, src/mito2/src/test_util/version_util.rs
This PR introduces a new struct `TimePartitions` to partition mutable memtables by time.
- It uses the compaction time window (`compaction.twcs.time_window`) as the partition time range
- Each partition holds timestamps between `[start_time, start_time + time_window)`
- We uses the `timestamp / time_window * time_window` to locate the proper partition
- If the compaction time window is not provided, it only has one partition and all timestamps belong to that partition
- Once we freeze a memtable version,  we move all memtables in `TimePartitions` to immutable memtable list.
With this feature, a region can strictly divide data by the time in memory. It also ensures flushed SSTs …
=> feat: Partition memtables by time if compaction window is provided

src/common/meta/src/ddl/create_logical_tables.rs, src/common/meta/src/ddl/create_table.rs, src/meta-srv/src/procedure/region_failover.rs, src/meta-srv/src/procedure/region_migration.rs, src/meta-srv/src/procedure/region_migration/downgrade_leader_region.rs, src/meta-srv/src/procedure/region_migration/manager.rs, src/meta-srv/src/procedure/region_migration/test_util.rs, src/meta-srv/src/procedure/region_migration/upgrade_candidate_region.rs, tests-integration/tests/region_failover.rs
#825 
To implement the `Drop Database` procedure, we must ensure all procedures acquire a lock from the top to the leaf (Ensure that the locks of each procedure intersect).
=> feat: acquire all locks in procedure 

src/frontend/src/instance.rs, src/operator/src/statement.rs, src/sql/src/parsers/create_parser.rs, src/sql/src/parsers/drop_parser.rs, src/sql/src/statements/create.rs, src/sql/src/statements/drop.rs, src/sql/src/statements/statement.rs, tests/cases/standalone/common/catalog/schema.result, tests/cases/standalone/common/system/information_schema.result
- #3516 
- #825 
Implement the drop database parser
=> feat: implement the drop database parser

src/mito2/Cargo.toml, src/mito2/src/engine.rs, src/mito2/src/engine/flush_test.rs, src/mito2/src/flush.rs, src/mito2/src/lib.rs, src/mito2/src/region.rs, src/mito2/src/region/opener.rs, src/mito2/src/test_util.rs, src/mito2/src/time_provider.rs, src/mito2/src/worker.rs, src/mito2/src/worker/handle_flush.rs
This PR checks whether a region should flush periodically and flush it if its last flush time is earlier than `auto_flush_interval`. The previous implementation only triggers the check on flush, which implies the write buffer is full. It might cause the database to hold a large amount of data for a long time if users stop ingesting data.
This PR
- adds a timeout to receive a channel so the worker can handle some tasks periodically
- adds a `TimeProvider` to get the current timestamp and checks elapsed time, this also simplifies test implementation
Each worker will start with a random check delay between `[0, MAX_INITIAL_CHECK_DELAY_SECS)` to avoid them flush together.
=> feat(mito): Checks whether a region should flush periodically

.github/workflows/unassign.yml
This closes https://github.com/GreptimeTeam/greptimedb/issues/3525.
Perhaps we can add more detailed conditions. Welcome to leave a comment :D
=> ci: unassign issues stale 14 days ago

README.md
1. Header style
2. Getting started
3. Project status
[Rendered](https://github.com/tisonkun/greptimedb/blob/more-readme/README.md)
=> docs: readme style and project status

src/api/src/helper.rs, src/store-api/src/logstore.rs
=> docs: improve fn comments

src/common/meta/src/key.rs, src/meta-srv/src/error.rs, src/meta-srv/src/handler/failure_handler.rs, src/meta-srv/src/handler/failure_handler/runner.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/metasrv/builder.rs, src/meta-srv/src/procedure/region_failover.rs, src/meta-srv/src/service/admin.rs, src/meta-srv/src/service/admin/maintenance.rs, src/meta-srv/src/test_util.rs, tests-integration/tests/region_failover.rs
* This closes #2211.
* This closes #1586.
Add "/maintenance" and "/maintenance/set" endpoint on metasrv admin APIs.
Skip failure failed_regions handling if `is_maintenance_mode`.
cc @xifyang
=> feat(metasrv): implement maintenance

src/common/meta/src/key.rs, src/common/meta/src/key/table_info.rs, src/common/meta/src/key/table_name.rs, src/common/meta/src/key/table_route.rs
This PR removed the `removed` prefixed keys; these keys weren't in use.
=> refactor: remove removed-prefixed keys

src/common/function/src/handlers.rs, src/common/function/src/state.rs, src/common/plugins/src/consts.rs, src/common/plugins/src/lib.rs, src/common/query/src/lib.rs, src/frontend/src/instance/influxdb.rs, src/frontend/src/instance/otlp.rs, src/frontend/src/instance/prom_store.rs, src/operator/src/insert.rs, src/operator/src/statement.rs, src/operator/src/statement/copy_database.rs, src/operator/src/statement/copy_table_from.rs, src/operator/src/table.rs, src/query/src/datafusion.rs, src/query/src/dist_plan/merge_scan.rs, src/servers/src/grpc/otlp.rs, src/servers/src/http/handler.rs, src/servers/src/http/header.rs, src/servers/src/http/influxdb.rs, src/servers/src/http/otlp.rs, src/servers/src/http/prom_store.rs, src/servers/src/http/prometheus.rs, src/servers/src/http/prometheus_resp.rs, src/servers/src/query_handler.rs, src/servers/tests/http/influxdb_test.rs, src/servers/tests/http/prom_store_test.rs, tests-integration/src/otlp.rs
This pr is a follow-up of https://github.com/GreptimeTeam/greptimedb/pull/3466. 
Now that we have `OutputMeta`, we can easily bring metrics from execution level up to the HTTP interface and put them into HTTP header. 
This pr covers basically every HTTP entry with read or write request, returning a HTTP header indicating the cost of the request.
=> chore: http header with metrics

src/common/meta/src/ddl/drop_table.rs, src/common/meta/src/ddl/drop_table/executor.rs, src/meta-srv/src/procedure/tests.rs
- #3516 
- #825
Introduce the DropTableExecutor.  The prelude of #825
=> refactor: introduce the DropTableExecutor

src/promql/src/extension_plan/series_divide.rs
Fix the change in #3537. Since `RecordBatch` is all wrapped by `Arc`, cloning it is not that unacceptable.
=> fix: clone data instead of moving it - homemade future is dangerous

src/common/macro/src/range_fn.rs, src/promql/src/functions/aggr_over_time.rs, src/promql/src/functions/changes.rs, src/promql/src/functions/deriv.rs, src/promql/src/functions/resets.rs
Support multi params in promql range function macro
The PromQL's function mark with `#[range_fn]` will generate code like
```rust
#[range_fn(
name = "MultiparamRunc",
ret = "Int64Array",
display_name = "prom_multi_param_func"
)]
pub fn multi_param_func(
_: &TimestampMillisecondArray,
_values: &Float64Array,
_a: &StringArray,
_b: &Int64Array,
) -> Option<i64> {
Some(0)
}
```
```rust
pub struct MultiparamRunc {}
impl MultiparamRunc {
pub const fn name() -> &'static str {
"prom_multi_param_func"
}
pub fn scalar_udf() -> ScalarUDF {
ScalarUDF {
name: Self::name().to_string(),
signature: Signature::new(
TypeSignature::Exact(Self::input_type()),
Volatility::Immutable,
),
return_type: …
```
=> feat: support multi params in promql range function macro

src/mito2/benches/memtable_bench.rs, src/mito2/src/memtable/time_series.rs, src/mito2/src/read.rs
- #2804
- https://github.com/GreptimeTeam/greptimedb/pull/3540
This PR adds support to append-only mode in time-series memtable.
=> feat: support append-only mode in time-series memtable

scripts/fetch-dashboard-assets.sh
=> chore: fix comment in fetch-dashboard-assets.sh

src/catalog/src/kvbackend/manager.rs, src/common/meta/src/cache_invalidator.rs, src/common/meta/src/ddl/alter_table.rs, src/common/meta/src/ddl/drop_table/executor.rs, src/common/meta/src/instruction.rs, src/datanode/src/heartbeat/handler.rs, src/frontend/src/heartbeat/handler/invalidate_table_cache.rs, src/frontend/src/heartbeat/handler/tests.rs, src/meta-srv/src/cache_invalidator.rs, src/meta-srv/src/procedure/region_failover/invalidate_cache.rs, src/meta-srv/src/procedure/region_migration.rs, src/operator/src/statement/ddl.rs
#3516 
fix #2369 
Use the `InvalidateCaches` instruction instead of `InvalidateTableId` and `InvalidateTableName` To avoid some cache inconsistency issues.
=> refactor: refactor CacheInvalidator

src/servers/src/http.rs, src/servers/src/http/arrow_result.rs, src/servers/src/http/authorize.rs, src/servers/src/http/csv_result.rs, src/servers/src/http/error_result.rs, src/servers/src/http/greptime_result_v1.rs, src/servers/src/http/handler.rs, src/servers/src/http/influxdb_result_v1.rs, src/servers/src/http/script.rs, src/servers/src/http/table_result.rs, src/servers/tests/http/influxdb_test.rs
1. Error response doesn't need a format header. Users should know the input and the actual format is always JSON.
2. Thus tidy all other related code.
3. Arrow format can output empty query with empty result.
Perhaps we can further tidy error handling code by `impl <T: ErrorExt> From<T> for ErrorResponse`, but this PR is large enough.
=> refactor: handle error for http format

src/mito2/src/memtable/partition_tree.rs, src/mito2/src/region/options.rs
- fixes #3555
Change the default `fork_dictionary_bytes` config in `PartitionTreeMemtable` to mitigate performance issue.
Ingestion rate
Memory usage
=> fix: performance degradation caused by config change

.github/workflows/unassign.yml
Default GitHub token cannot access members set their org status as private.
=> ci: use a PAT to list all writers

src/flow/src/utils.rs
Fix arrangement's batches's interaction with get by range unaligned with batch boundaries. Related tests are added and commented in details.
=> fix(flow): Arrange get range with batch unaligned

src/promql/src/extension_plan/series_divide.rs
This follows up #3542. Hopefully I don't introduce new subtle issues 🥵
=> refactor: reduce one clone by carefully pass ready boundary

tests-integration/tests/sql.rs
This closes https://github.com/GreptimeTeam/greptimedb/issues/2920
As the title says
=> test: add a parameter type mismatch test case to sql integration test

src/servers/src/http/table_result.rs, src/servers/tests/http/http_handler_test.rs
fixed the problem mentioned in this PR: https://github.com/GreptimeTeam/greptimedb/pull/3539
The table format contains non-ASCII characters, and the content-type does not specify a character set. Although most clients will try to using UTF-8, but we cannot make this assumption and need to explicitly set it.
before:
after:
=> fix: set http response chartset to utf-8 when using table format

.github/workflows/apidoc.yml
- https://github.com/GreptimeTeam/greptimedb/issues/3579
This PR sets `single-commit` to `true` for the `gh-pages` branch. It should reduce the branch size.
=> ci: use single commit on the deployment branch

Cargo.lock, Cargo.toml, src/index/src/inverted_index/error.rs, src/index/src/inverted_index/search/fst_apply/intersection_apply.rs
=> refactor: try upgrade regex-automata

src/common/meta/src/ddl.rs, src/common/meta/src/ddl/alter_logical_tables.rs, src/common/meta/src/ddl/alter_logical_tables/check.rs, src/common/meta/src/ddl/alter_logical_tables/metadata.rs, src/common/meta/src/ddl/alter_logical_tables/region_request.rs, src/common/meta/src/ddl/alter_logical_tables/update_metadata.rs, src/common/meta/src/ddl/alter_table.rs, src/common/meta/src/ddl/create_logical_tables.rs, src/common/meta/src/ddl/drop_table/executor.rs, src/common/meta/src/ddl/test_util.rs, src/common/meta/src/ddl/test_util/alter_table.rs, src/common/meta/src/ddl/test_util/columns.rs, src/common/meta/src/ddl/test_util/create_table.rs, src/common/meta/src/ddl/tests.rs, src/common/meta/src/ddl/tests/alter_logical_tables.rs, src/common/meta/src/ddl/tests/create_logical_tables.rs, src/common/meta/src/ddl/tests/create_table.rs, src/common/meta/src/ddl/utils.rs, src/common/meta/src/ddl_manager.rs, src/common/meta/src/error.rs, src/common/meta/src/key.rs, src/common/meta/src/key/table_route.rs, src/common/meta/src/rpc/ddl.rs, src/meta-srv/src/procedure/tests.rs, src/operator/src/error.rs, src/operator/src/insert.rs, src/operator/src/metrics.rs, src/operator/src/statement/ddl.rs, src/table/src/metadata.rs
=> feat: batch alter logical tables

src/object-store/Cargo.toml
Topic from https://github.com/GreptimeTeam/greptimedb/pull/3582
OpenDAL's default features contain many services that aren't used in our system. Opt them out can reduce the compile time of OpenDAL by half (from 29.31s to 15.07s) and speed up the overall compile time by 2s (out of 151s in total).
This is because OpenDAL lies in the critical path of the entire compile progress, and long compile time would lead to a small hang:
| - | - |
|:-:|:-:|
| Before | <img width="1813" alt="image" src="https://github.com/GreptimeTeam/greptimedb/assets/15380403/42cdaaa1-b4e2-4b0f-86d9-49315aa20333"> |
| After | <img width="1744" alt="image" …
=> chore: limit OpenDAL's feature gates

src/mito2/src/read.rs, src/mito2/src/read/compat.rs, tests/cases/standalone/common/alter/alter_table.result, tests/cases/standalone/common/alter/alter_table.sql
SELECT with a filter will decode the primary key in advance, before compat reader. And compat reader doesn't handle the cache which leads to this error.
=> fix: update pk_cache in compat reader 

src/cmd/build.rs
The build script in `cmd` won't rerun if the current git HEAD is changed, and will likely produce an incorrect result in `--version`.
But our release is not affected as the environment is clear for each release build.
=> fix: incorrect version info in

src/operator/src/statement.rs, tests/cases/standalone/common/copy/copy_to_fs.result, tests/cases/standalone/common/copy/copy_to_fs.sql
This PR adds support for specifying time range to export when executing `COPY <TABLE> TO` statement.
=> feat: support time range in copy table

src/cmd/src/frontend.rs, src/cmd/src/standalone.rs, src/common/meta/src/ddl.rs, src/common/meta/src/ddl/alter_logical_tables.rs, src/common/meta/src/ddl/alter_logical_tables/metadata.rs, src/common/meta/src/ddl/alter_logical_tables/table_cache_keys.rs, src/common/meta/src/ddl/alter_logical_tables/update_metadata.rs, src/common/meta/src/ddl/create_logical_tables.rs, src/common/meta/src/ddl/physical_table_metadata.rs, src/common/meta/src/ddl_manager.rs, src/common/meta/src/error.rs, src/frontend/src/instance/builder.rs, src/meta-srv/src/procedure/tests.rs, src/operator/src/statement/ddl.rs, tests-integration/src/cluster.rs, tests-integration/src/standalone.rs, tests/cases/standalone/common/alter/alter_metric_table.result, tests/cases/standalone/common/alter/alter_metric_table.sql, tests/cases/standalone/common/create/create_metric_table.result, tests/cases/standalone/common/create/create_metric_table.sql
- Update the physical table schema when altering logical tables;
- Invalidate the cache in frontend when schema changed;
- Let the alter logical table from sql console go into the new alter procedure;
- Add sqlness test of alter logical tables.
=> feat: update physical table schema on alter logical tables

src/mito2/src/compaction/twcs.rs, src/mito2/src/engine.rs, src/mito2/src/engine/append_mode_test.rs, src/mito2/src/memtable.rs, src/mito2/src/memtable/time_series.rs, src/mito2/src/read/merge.rs, src/mito2/src/read/scan_region.rs, src/mito2/src/read/seq_scan.rs, src/mito2/src/region/opener.rs, src/mito2/src/region/options.rs, src/mito2/src/worker.rs, src/mito2/src/worker/handle_write.rs
- https://github.com/GreptimeTeam/greptimedb/issues/3480
This PR implements append mode for a mito region.
- By default, `append_mode` is false and the engine removes duplicate rows.
- If `append_mode` is true, the engine keeps all duplicate rows.
It adds a `dedup` flag to the `MergeReader`. The `MergeReader` will keep rows with duplicate keys but still yield rows in sorted order.
=> feat: Implement append mode for a region

src/common/meta/src/ddl/create_table.rs, src/meta-srv/src/procedure/tests.rs
When creating table, the step of `create region` should persist its's status.
=> feat: create regions persist true

src/cmd/src/cli/bench/metadata.rs, src/common/meta/src/ddl/drop_database/cursor.rs, src/common/meta/src/ddl/drop_database/executor.rs, src/common/meta/src/ddl/drop_table.rs, src/common/meta/src/ddl/drop_table/executor.rs, src/common/meta/src/key.rs, src/common/meta/src/key/table_route.rs
#3516 
1. Refactor drop table executor
2. Support to drop metric table (`Drop Database` statement)
=> refactor: refactor drop table executor

src/common/meta/src/ddl/drop_database.rs, src/common/meta/src/ddl/drop_database/cursor.rs, src/common/meta/src/ddl/drop_database/end.rs, src/common/meta/src/ddl/drop_database/executor.rs, src/common/meta/src/ddl/drop_database/metadata.rs, src/common/meta/src/ddl/drop_database/start.rs, src/common/meta/src/ddl/test_util.rs, src/common/meta/src/ddl/tests.rs, src/common/meta/src/ddl/tests/alter_logical_tables.rs, src/common/meta/src/ddl/tests/create_logical_tables.rs, src/common/meta/src/ddl/tests/drop_database.rs
#3516 
add tests for drop databases
=> test: add tests for drop databases

src/cmd/src/standalone.rs, src/common/meta/src/ddl.rs, src/common/meta/src/ddl/create_table.rs, src/common/meta/src/ddl/table_meta.rs, src/common/meta/src/ddl/test_util.rs, src/common/meta/src/ddl/tests/create_logical_tables.rs, src/common/meta/src/ddl_manager.rs, src/common/meta/src/test_util.rs, src/meta-srv/src/metasrv/builder.rs, src/meta-srv/src/procedure/tests.rs, src/meta-srv/src/procedure/utils.rs, tests-integration/src/standalone.rs
As the title said, since we already have the `CreateLogicalTablesProcedure`
=> feat: remove support for logical tables in the create table procedure

src/common/meta/src/instruction.rs, src/frontend/src/heartbeat/handler/invalidate_table_cache.rs, src/frontend/src/heartbeat/handler/tests.rs
It is unnecessary to reply to the broadcast msg from metasrv
=> chore: do not reply for broadcast msg

src/catalog/src/information_schema/memory_table/tables.rs, tests/cases/standalone/common/system/information_schema.result
Adds `metric` engine to `information_schema` engines table.
=> feat: adds metric engine to information_schema engines table

Cargo.lock, src/cmd/src/standalone.rs, src/common/meta/src/ddl_manager.rs, src/meta-srv/src/metasrv/builder.rs, tests-integration/Cargo.toml, tests-integration/src/cluster.rs, tests-integration/src/lib.rs, tests-integration/src/standalone.rs, tests-integration/src/tests/instance_kafka_wal_test.rs, tests-integration/src/tests/test_util.rs, tests-integration/tests/region_migration.rs
=> test: add more integration test for kafka wal

src/servers/src/http/error_result.rs, tests-integration/tests/http.rs
Move some error types out of 500
=> fix: adjust status code to http error code map

Cargo.lock, Cargo.toml, src/common/version/Cargo.toml, src/common/version/src/lib.rs, src/servers/Cargo.toml, src/servers/src/http.rs, src/servers/src/http/prometheus.rs, src/servers/src/http/prometheus_resp.rs, tests-integration/tests/grpc.rs, tests-integration/tests/http.rs
Closes https://github.com/GreptimeTeam/greptimedb/issues/3496
When adding GreptimeDB to Grafana (v9.0) datasource using Prometheus extension, it will send two queries:
```
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on docker0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
15:55:50.899080 IP 172.17.0.3.54034 > 172.17.0.1.4000: Flags [P.], seq 3048369435:3048369718, ack 3792103051, win 251, options [nop,nop,TS val 2511689527 ecr 2125370641], length 283
E..O..@.@.................m.........Yh.....
..W7~...POST /v1/prometheus/api/v1/query HTTP/1.1
Host: 172.17.0.1:4000
User-Agent: Grafana/10.2.3
Content-Length: 18
Content-Type: …
```
=> feat: support `2+2` and `/status/buildinfo`

src/catalog/src/kvbackend/manager.rs, src/cmd/src/cli/repl.rs, src/cmd/src/frontend.rs, src/cmd/src/standalone.rs, src/common/meta/src/cache_invalidator.rs, src/common/meta/src/ddl/alter_table.rs, tests-integration/src/cluster.rs, tests-integration/src/standalone.rs
=> refactor: cache invalidator

src/common/meta/src/ddl/alter_table.rs, src/common/meta/src/ddl_manager.rs, src/common/meta/src/key.rs, src/meta-srv/src/procedure/tests.rs
As the title said, we already have the `AlterLogicalTablesProcedure` for logical tables.
=> feat: let alter table procedure can only alter physical table

src/common/function/src/scalars/timestamp/to_timezone.rs, tests/cases/standalone/common/function/time.result, tests/cases/standalone/common/function/time.sql
https://github.com/GreptimeTeam/greptimedb/issues/3477
updated `to_timezone` logic to support UNIX millisecond timestamp numerical values like `1711508510000`
=> feat(function): add timestamp epoch integer support for to_timezone

src/common/meta/src/ddl/alter_logical_tables.rs, src/common/meta/src/ddl/alter_logical_tables/region_request.rs
Minor improve, group the requests by datanode peer,  it is good for this case: there are multiple regions of one table on the same datanode
=> feat: group requests by peer

src/mito2/src/region/opener.rs, src/mito2/src/worker.rs, src/mito2/src/worker/handle_catchup.rs, src/mito2/src/worker/handle_create.rs, src/mito2/src/worker/handle_open.rs
- #3416
This PR creates a new scheduler for purge jobs instead of reusing the global scheduler. It avoids purge jobs blocking other background jobs, especially flush jobs.
=> fix: run purge jobs in another scheduler

src/operator/src/error.rs, src/operator/src/lib.rs, src/operator/src/statement.rs
This PR adds timestamp validity check to reject invalid timestamps in `copy` statement.
```sql
mysql> copy monitor from '/tmp/export/monitor.parquet' with (format='parquet', START_TIME='2023-12-13 03:05:41', END_TIME='2023-12-13 02:05:51');
ERROR 1815 (HY000): Invalid timestamp range, start: `2023-12-13 03:05:41+0000`, end: `2023-12-13 02:05:51+0000`
```
=> feat: reject invalid timestamp ranges in copy statement

Cargo.lock, config/metasrv.example.toml, src/cmd/src/metasrv.rs, src/common/meta/src/state_store.rs, src/common/procedure/Cargo.toml, src/common/procedure/src/options.rs, src/common/procedure/src/store/util.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/metasrv/builder.rs, tests-integration/src/cluster.rs
1. Enable auto split large value
2. Add `max_value_size` configuration to `[procedure]` section in `metasrv.example.toml`, with default value `1535KiB`.
3. Add `max_value_size` to `ProcedureConfig`, type of `Option<size>` the default value is None(no max size limit).
=> feat(procedure): enable auto split large value

src/mito2/src/compaction/twcs.rs, src/mito2/src/engine.rs, src/mito2/src/engine/compaction_test.rs, src/mito2/src/engine/listener.rs, src/mito2/src/request.rs, src/mito2/src/test_util.rs, src/mito2/src/worker.rs, src/mito2/src/worker/handle_compaction.rs, src/mito2/src/worker/handle_flush.rs
- fixes #3633
This PR fixes the the incorrect behavior that removes compaction inputs instead of outputs on compaction failure.
=> fix: mistakely removes compaction inputs on failure

src/object-store/src/layers/prometheus.rs
#3622
Move timer from read/write function into `PrometheusMetricWrapper` and update data when dropping to get accurate metric.
=> fix: move object store read/write timer into inner

Cargo.lock, Cargo.toml, src/servers/Cargo.toml, src/servers/src/error.rs, src/servers/src/http/prom_store.rs, src/servers/src/prom_store.rs, tests-integration/Cargo.toml, tests-integration/tests/http.rs
This patch enhances our remote write interface to support victoriametrics' remote write variant. 
Basically, the protocol variant is a change from snappy encoding to zstd encoding. For compatibility check, it introduces a new handshake process.
The client sends an empty write request with `get_vm_proto_version`
```
Hypertext Transfer Protocol
POST /api/v1/write?get_vm_proto_version=1 HTTP/1.1\r\n
Host: localhost:8000\r\n
User-Agent: vmagent\r\n
Content-Length: 0\r\n
Content-Encoding: snappy\r\n
Content-Type: application/x-protobuf\r\n
X-Prometheus-Remote-Write-Version: 0.1.0\r\n
Accept-Encoding: gzip\r\n
\r\n
[Full request URI: …
```
=> feat: adding victoriametrics remote write

tests/cases/standalone/common/create/create_database.result, tests/cases/standalone/common/create/create_database.sql, tests/cases/standalone/common/create/upper_case_table_name.result, tests/cases/standalone/common/create/upper_case_table_name.sql, tests/cases/standalone/common/show/show_databases_tables.result, tests/cases/standalone/common/system/information_schema.result, tests/cases/standalone/common/tql/case_sensitive.result, tests/cases/standalone/common/tql/case_sensitive.sql
Release databases after sqlness tests
=> test(sqlness): release databases after tests

.github/workflows/license.yaml
=> ci: bump license header checker action version

cliff.toml
This refers to #3609 
Install `cargo install git-cliff`
Running `GITHUB_TOKEN=*** git cliff v0.6.0..v0.7.0` gives:
(We can then manually add highlights and/or fine-tuning the notes)
```markdown
Release date: March 05, 2024
* feat!: switch prom remote write to metric engine by [@waynexia](https://github.com/waynexia) in [#3198](https://github.com/GreptimeTeam/greptimedb/pull/3198)
* refactor!: rename initialize_region_in_background to init_regions_in_background by [@WenyXu](https://github.com/WenyXu) in [#3216](https://github.com/GreptimeTeam/greptimedb/pull/3216)
* feat!: new partition grammar - parser part by [@waynexia](https://github.com/waynexia) in …
```
=> chore: generate release notes with git-cliff

Cargo.lock, src/mito2/src/manifest/action.rs, src/mito2/src/manifest/manager.rs, src/mito2/src/metrics.rs
https://github.com/GreptimeTeam/greptimedb-enterprise/issues/39
The metrics of the time to operate the manifest, labeled with "op". Label values are "update", "open" and "checkpoint", each represent the corresponding manifest operation.
Screenshot of "/metrics" output:
=> chore: add manifest related metrics

src/mito2/src/engine.rs, src/store-api/src/region_request.rs
This PR adds timers to more mito methods
- edit_region
- set_readonly_gracefully
It also combines `RegionRequest::request_type()` and `RegionRequest::type_name()` into one method.
=> feat: Add timers to more mito methods

Cargo.lock, Cargo.toml
=> chore: bump version to 0.7.2

Cargo.lock, Cargo.toml, src/common/meta/src/ddl.rs, src/common/meta/src/ddl/create_database.rs, src/common/meta/src/ddl_manager.rs, src/common/meta/src/rpc/ddl.rs, src/operator/src/statement/ddl.rs, tests-integration/src/grpc.rs
close #3591
move `create database` to procedure
=> refactor: move create database to procedure

Cargo.lock, Cargo.toml, src/common/meta/src/rpc/procedure.rs, src/common/procedure/src/error.rs, src/common/procedure/src/local.rs, src/common/procedure/src/local/runner.rs, src/common/procedure/src/procedure.rs, src/common/procedure/src/store.rs, src/common/procedure/src/watcher.rs
Support to rollback failed procedures
1. Add the `rollback` method to the `Procedure` trait, the method requires an idempotent implementation.
2. Add `CommitRollback`, `RollingBack` states to `ProcedureState`.
3. Rollback procedures during the recovering.
=> feat(procedure): support to rollback

README.md
fix link of greptimedb-ingester-js in readme.md
=> fix(readme): fix link of Ingester-js

src/mito2/src/worker/handle_write.rs, src/store-api/src/mito_engine_options.rs, tests/cases/standalone/common/insert/append_mode.result, tests/cases/standalone/common/insert/append_mode.sql
- #3480
This PR adds `append_mode` to mito engine's table options. It also adds a sqlness test for append mode.
=> feat: add append mode to table options

.github/workflows/develop.yml, tests-fuzz/Cargo.toml, tests-fuzz/src/error.rs, tests-fuzz/src/generator/create_expr.rs, tests-fuzz/src/ir.rs, tests-fuzz/src/ir/create_expr.rs, tests-fuzz/src/translator/mysql/create_expr.rs, tests-fuzz/targets/fuzz_create_database.rs
As mentioned in https://github.com/GreptimeTeam/greptimedb/pull/3626#issuecomment-2034953097, part of  #3174.
=> feat(fuzz): add create database target

src/common/meta/src/ddl/alter_logical_tables.rs, src/common/meta/src/ddl/alter_logical_tables/metadata.rs, src/common/meta/src/ddl/alter_logical_tables/update_metadata.rs, src/common/meta/src/ddl_manager.rs, src/common/meta/src/key.rs, src/common/meta/src/key/table_info.rs, src/common/meta/src/key/table_route.rs
We shouldn't use the `DeserializedValueWithBytes::from_inner` for non-test purposes.
=> fix: `DeserializedValueWithBytes::from_inner` misusing

config/datanode.example.toml, config/standalone.example.toml, src/datanode/src/config.rs, tests-integration/src/test_util.rs
This PR removes the `global_ttl` config item since its no longer used.
=> chore: remove global_ttl config

src/meta-srv/src/service/admin.rs, src/meta-srv/src/service/admin/health.rs, src/meta-srv/src/service/admin/heartbeat.rs, src/meta-srv/src/service/admin/leader.rs, src/meta-srv/src/service/admin/maintenance.rs, src/meta-srv/src/service/admin/meta.rs, src/meta-srv/src/service/admin/node_lease.rs, src/meta-srv/src/service/admin/region_migration.rs, src/meta-srv/src/service/admin/route.rs
Spotted on https://github.com/GreptimeTeam/docs/pull/878.
This follows up #3527
=> refactor: pass http method to metasrv http handler

src/servers/src/http/prometheus_resp.rs, tests-integration/tests/http.rs
Queries like `count(count(metric))` would generate a result in non-float64 type. In strict Prometheus Compatible mode (via Prometheus HTTP API) this would turn into an error. This patch adds a cast logic to extend the possible field types.
=> feat: treat all number types as field candidates

src/cmd/src/cli/bench/metadata.rs, src/common/meta/src/ddl/alter_logical_tables/update_metadata.rs, src/common/meta/src/ddl/alter_table.rs, src/common/meta/src/ddl/alter_table/check.rs, src/common/meta/src/ddl/alter_table/metadata.rs, src/common/meta/src/ddl/alter_table/region_request.rs, src/common/meta/src/ddl/alter_table/update_metadata.rs, src/common/meta/src/ddl/create_logical_tables/update_metadata.rs, src/common/meta/src/ddl/test_util/alter_table.rs, src/common/meta/src/ddl/test_util/create_table.rs, src/common/meta/src/ddl/tests.rs, src/common/meta/src/ddl/tests/alter_table.rs, src/common/meta/src/ddl_manager.rs, src/common/meta/src/key.rs, src/common/meta/src/rpc/ddl.rs, src/meta-srv/src/procedure/tests.rs
close #3637
1. Fetch the table info during the execution.
2. Refactor alter table procedure
3. Add mores tests
=> refactor: refactor alter table procedure

Cargo.lock, Cargo.toml, src/common/meta/src/rpc/ddl.rs, src/frontend/src/instance/grpc.rs, tests-integration/src/grpc.rs
close #3662 
`database_name` to `schema_name` corresponding to the change in greptime-proto.
=> chore: create database api change in protobuf

.github/workflows/develop.yml, Cargo.lock, src/cmd/Cargo.toml, src/cmd/src/cli/export.rs
close #3681
Solve the problem that running `cli export` with `--target create-table` fails when the `catalog/schema/table` names contain `.` (e.g. `a.b.c`).
=> fix: cli export "create table" with quoted names

src/frontend/src/instance.rs, src/frontend/src/script.rs, src/servers/src/mysql/server.rs, src/servers/src/opentsdb.rs, src/servers/src/postgres/server.rs
This patch enforces check for `should_log_error` to all user-facing APIs, to prevent misinformation while operating greptimedb.
=> refactor: check error type before logging

src/mito2/src/engine/catchup_test.rs, src/mito2/src/error.rs, src/mito2/src/manifest/manager.rs, src/mito2/src/manifest/tests/checkpoint.rs, src/mito2/src/region.rs, src/mito2/src/region/opener.rs, src/mito2/src/worker/handle_alter.rs, src/mito2/src/worker/handle_catchup.rs, src/mito2/src/worker/handle_compaction.rs, src/mito2/src/worker/handle_truncate.rs
https://github.com/GreptimeTeam/greptimedb/issues/3456
This PR is a part of https://github.com/GreptimeTeam/greptimedb/issues/3456
It moves methods in `RegionManifestManagerInner` to `RegionManifestManager`. Now the `MitoRegion` uses a lock to protect the manager. We can use that lock to ensure there is only one task updating manifest and `VersionControl`.
=> refactor: Move manifest manager lock to `MitoRegion`

Cargo.lock, Cargo.toml, src/common/meta/src/cluster.rs, src/meta-client/src/client.rs, src/meta-client/src/client/cluster.rs, src/meta-srv/src/election.rs, src/meta-srv/src/election/etcd.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/service/cluster.rs
As the title said, provide a way to get the metasrvs info:
1. Make that each Metasrv node registers candidate information upon startup, sets the key (`__metasrv_election_candidates/{address}`), and keeps it alive every 300 seconds. The key will be delete when no keep lease.
2. Let the cluster client can get this information via gRPC service
=> feat: get metasrv clusterinfo

src/catalog/Cargo.toml, src/common/meta/src/kv_backend/etcd.rs, src/common/meta/src/kv_backend/memory.rs, src/common/meta/src/kv_backend/test.rs, src/log-store/Cargo.toml, src/log-store/src/raft_engine/backend.rs
close #2618 
For now, `KvBackend` trait has some implements, such as `ChrootKvBackend`, `MemoryKvBackend`, etc. But only `RaftEngineBackend`, `MemoryKvBackend` and `EtcdStore` will directly access the data. PR #2615 has been added  some tests for `RaftEngineBackend` and `MemoryKvBackend`, this PR for `EtcdStore` to ensure all implements have the same behaviors.
Other `KvBackend` trait implements based `RaftEngineBackend`, `MemoryKvBackend` and `EtcdStore` implement，I think it's unnecessary.
Tests mainly for **range、put、batch_put、batch_get、compare_and_put、delete_range、batch_delete**.
=> test: Add tests for KvBackend trait implement

src/mito2/src/engine.rs, src/mito2/src/engine/append_mode_test.rs, src/mito2/src/engine/filter_deleted_test.rs, src/mito2/src/read/merge.rs, src/mito2/src/read/scan_region.rs, src/mito2/src/read/seq_scan.rs, src/mito2/src/test_util.rs, src/mito2/src/test_util/batch_util.rs
- #3416
This PR adds an `filter_deleted` option to `MergeReader` so that it will not remove deletion markers (or tombstones) during merging.
`filter_deleted` is different from `dedup` in that:
- If `dedup` is set to false, then `filter_deleted` will always be false since deletion markers are not expected to present.
- If `dedup` is set to true, then `filter_deleted` decides whether deletion markers should be removed. 
This PR is the predecessor work of #3702.
=> feat: add `filter_deleted` option to avoid removing deletion markers

src/common/datasource/src/buffered_writer.rs, src/common/datasource/src/file_format.rs, src/common/datasource/src/file_format/parquet.rs
This closes https://github.com/GreptimeTeam/greptimedb/issues/2657.
TRIVIAL AS IS. Read the code and see #2657's description.
=> refactor: remove redundant try_flush invocations

src/partition/src/error.rs, src/partition/src/lib.rs, src/partition/src/manager.rs, src/partition/src/multi_dim.rs
#3351
Check the input partition rule set to make sure there is no cavity.
I'll file a follow-up PR to refactor the `partition` crate to remove the old implementation and install the new one directly (without a trait indirection).
=> feat: check partition rule

src/common/meta/src/ddl/alter_table.rs, src/common/meta/src/ddl/test_util/datanode_handler.rs, src/common/meta/src/ddl/tests/alter_table.rs
=> fix(alter_table): ignore request outdated error

src/cmd/src/cli/bench/metadata.rs, src/common/meta/src/ddl/drop_database/cursor.rs, src/common/meta/src/ddl/drop_database/executor.rs, src/common/meta/src/ddl/drop_table.rs, src/common/meta/src/ddl/drop_table/executor.rs, src/common/meta/src/ddl/drop_table/metadata.rs, src/common/meta/src/ddl/tests/drop_table.rs, src/common/meta/src/error.rs, src/common/meta/src/key.rs, src/common/meta/src/key/datanode_table.rs, src/common/meta/src/key/table_info.rs, src/common/meta/src/key/table_name.rs, src/common/meta/src/key/table_route.rs, src/common/meta/src/key/tombstone.rs, src/common/meta/src/key/txn_helper.rs, src/common/meta/src/kv_backend/memory.rs, src/common/meta/src/lib.rs, src/common/meta/src/test_util.rs, src/datanode/src/region_server.rs, tests/cases/standalone/common/create/create_metric_table.result, tests/cases/standalone/common/create/create_metric_table.sql
close #3615
1. Introduce `TombstoneManager`
2. Support to rollback table metadata in drop table procedure
=> feat(drop_table): support to rollback table metadata

.github/workflows/develop.yml, .github/workflows/nightly-ci.yml
Remove the old aws test account and use the new one `greptimedb-ci-tester`.
=> ci: use greptimedb-ci-tester account

src/datatypes/src/value.rs
https://github.com/GreptimeTeam/greptimedb/issues/3221
Assuming `null`s occupy spaces we have opted to use the size of `i64` as an initial approximation.
=> chore(mito): set null value data size to i64

src/catalog/src/kvbackend/client.rs, src/script/src/python/engine.rs
=> chore: cleanup todos that should be panic

CONTRIBUTING.md, docs/style-guide.md
Add GreptimeDB specific style guide.
=> docs: add style guide

tests-fuzz/targets/fuzz_create_database.rs, tests-fuzz/targets/fuzz_create_table.rs
Enable the existing `IF NOT EXISTS` option in fuzz test.
=> feat(fuzz): enable create-if-not-exists option

src/sql/src/statements/transform/type_alias.rs
close #3703 
Add `TINYTEXT`, `MEDIUMTEXT` and `LONGTEXT` as alias of `TEXT` for compatibility with MYSQL.
=> feat: add tinytext, mediumtext and longtext data types

src/common/meta/src/ddl/drop_table/executor.rs, src/common/meta/src/error.rs, src/common/meta/src/key.rs, src/common/meta/src/key/tombstone.rs, src/common/meta/src/key/txn_helper.rs, src/common/meta/src/rpc/store.rs
1. Introduce `move_values` in `TombstoneManager`
2. Ensure all moving values remain unchanged between two transactions
3. Make `delete_table_metadata` and `restore_table_metadata` to be Idempotent.
=> refactor(meta): Ensure all moving values remain unchanged between two transactions

src/table/src/table.rs
As the title said, we do not need  TableIdProvider any more.
=> chore: remove TableIdProvider

src/common/meta/src/key.rs, src/common/meta/src/key/table_info.rs, src/common/meta/src/key/table_route.rs, src/common/meta/src/key/txn_helper.rs
It changes the behaviors to consume the bytes instead of cloning them.
=> refactor: avoid unnecessary cloning

src/operator/src/statement/tql.rs, src/servers/src/http/handler.rs, src/servers/src/http/prometheus.rs
https://github.com/GreptimeTeam/greptimedb/issues/3453
https://github.com/GreptimeTeam/greptimedb/pull/3630
improve the implementation by avoid an allocation if the lookback value is provided.
=> refactor: avoid unnecessary alloc by using unwrap_or_else

Cargo.lock, Cargo.toml
follow up of #3661, use the official greptime-proto
=> chore: update greptime-proto to main

.github/workflows/develop.yml, Cargo.lock, tests/runner/Cargo.toml, tests/runner/src/main.rs
Add `--preserve-state` CLI arg to prevent temp dir from cleaning on exit. Sqlness runner in CI will use it to preserve logs and state.
~~Use `tempdir` because `tempfile` cannot set a prefix on temp dir.~~
=> feat: add preserve arg to sqlness runner

Cargo.lock, src/flow/Cargo.toml, src/flow/src/compute/render.rs, src/flow/src/compute/render/map.rs, src/flow/src/compute/state.rs, src/flow/src/compute/types.rs, src/flow/src/expr/error.rs, src/flow/src/expr/linear.rs, src/flow/src/expr/relation/accum.rs, src/flow/src/expr/relation/func.rs, src/flow/src/plan.rs, src/flow/src/plan/reduce.rs, src/flow/src/repr.rs, src/flow/src/transform/aggr.rs, src/flow/src/utils.rs
As titile says, some minor refactor and doc improvement in flow module
=> refactor(flow): split render.rs and other minor changes

.github/actions/build-windows-artifacts/action.yml
```
Error: C:\a\greptimedb\greptimedb\./.github/actions/build-windows-artifacts\action.yml (Line: 30, Col: 21): Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.GITHUB_TOKEN
```
This default secrets doesn't exist on self-hosted runner. The TOKEN is mainly for avoid rate limitation, but that may not be quite an issue for self-hosted daily cronjob. Remove firstly to unlock the workflow. We can revisit this topic if the rate limit comes back to be an issue.
=> ci: secrets.GITHUB_TOKEN not exist on self-hosted runner

src/common/meta/src/ddl/physical_table_metadata.rs, src/datatypes/src/schema/column_schema.rs, tests/cases/standalone/common/alter/alter_metric_table.result, tests/cases/standalone/common/alter/alter_metric_table.sql, tests/cases/standalone/common/create/create_metric_table.result, tests/cases/standalone/common/insert/logical_metric_table.result
Closes https://github.com/GreptimeTeam/greptimedb/issues/3758
Related to this ticket: https://github.com/GreptimeTeam/greptimedb/issues/2798
Only `time_index` in schema is set before, but forget to set this on column_schema
=> fix: set is_time_index properly on updating physical table's schema

src/common/meta/src/ddl/drop_database/cursor.rs, src/common/meta/src/ddl/drop_database/executor.rs, src/common/meta/src/ddl/drop_table.rs, src/common/meta/src/ddl/test_util.rs, src/common/meta/src/ddl/tests/alter_logical_tables.rs, src/common/meta/src/ddl/tests/drop_database.rs, src/common/meta/src/ddl/tests/drop_table.rs, src/common/meta/src/error.rs, src/common/procedure-test/src/lib.rs
The [failed sqlness test](https://github.com/GreptimeTeam/greptimedb-enterprise/actions/runs/8778950389/job/24086386812?pr=43) shows that there might be some data race on dropping tables: 
After digging into the codes, I think the problem is caused by the implementation that the procedure returned does not mean it's dropped. The logs suggest the same:
This PR fix it.
=> fix: the `dropping_regions` guards should be dropped on procedure done

src/common/meta/src/ddl/create_table.rs, src/common/meta/src/ddl/tests/create_table.rs, src/common/meta/src/ddl/tests/drop_table.rs, src/common/procedure-test/src/lib.rs
Same as #3771, there're data race in creating table procedure.
Other two places that use this operating region guard are drop database procedure and region migration procedure. However, due to the different way of how their procedures are implemented, they are not affected. An interesting side effect.
=> fix: operating region guards should be dropped when procedure is done

src/servers/src/http/prometheus.rs, src/session/src/context.rs, tests-integration/tests/http.rs
Closes https://github.com/GreptimeTeam/greptimedb/issues/3497
Except https://github.com/GreptimeTeam/greptimedb/issues/3497, this patch also fixes the behavior that `db` from params cannot override `x-greptime-db-name` header.
=> fix: consider both db param and extended db header in Prometheus HTTP API

src/mito2/src/compaction/twcs.rs, src/mito2/src/engine/compaction_test.rs, src/mito2/src/test_util.rs
This PR disables deletion marker removal when some window's time range overlaps with another window, so that deletion markers will not be removed, which may cause deleted rows appear again.
=> fix: do not remove deletion markers when window time range overlaps

Cargo.lock
Upgrade jobserver-rs to 0.1.31 so that it can build on platforms with older glibc.
Related issues:
- https://github.com/rust-lang/jobserver-rs/issues/87
=> chore: bump jobserver

src/promql/src/extension_plan/scalar_calculate.rs, tests/cases/standalone/common/promql/scalar.result, tests/cases/standalone/common/promql/scalar.sql
Follow up of https://github.com/GreptimeTeam/greptimedb/pull/3693
ScalarCalculate don't check whether the record batch is empty. When input a empty record batch in ScalarCalculate, it may lead crash of DB.
https://github.com/GreptimeTeam/greptimedb/blob/778e195f07c576a01562f74f9e44bd31088a422b/src/promql/src/extension_plan/scalar_calculate.rs#L414
check the input record batch is empty
=> fix: promql scalar when input empty batch

src/cmd/Cargo.toml, src/cmd/src/bin/greptime.rs, src/cmd/src/lib.rs, src/common/version/src/lib.rs
To make the cli "--version" prints the correct version string. Previously, in a project that embeds greptimedb as a submodule, the project's bins always print the git info of greptimedb, instead of the project's. After this PR, that can be fixed.
=> refactor: move the version string to common

Cargo.lock, Cargo.toml, src/common/error/src/status_code.rs, src/mito2/Cargo.toml, src/mito2/src/compaction.rs, src/mito2/src/compaction/twcs.rs, src/mito2/src/engine/catchup_test.rs, src/mito2/src/engine/compaction_test.rs, src/mito2/src/engine/listener.rs, src/mito2/src/engine/open_test.rs, src/mito2/src/engine/set_readonly_test.rs, src/mito2/src/error.rs, src/mito2/src/flush.rs, src/mito2/src/manifest/manager.rs, src/mito2/src/manifest/tests/checkpoint.rs, src/mito2/src/region.rs, src/mito2/src/region/opener.rs, src/mito2/src/request.rs, src/mito2/src/test_util/scheduler_util.rs, src/mito2/src/worker.rs, src/mito2/src/worker/handle_alter.rs, src/mito2/src/worker/handle_catchup.rs, src/mito2/src/worker/handle_close.rs, src/mito2/src/worker/handle_compaction.rs, src/mito2/src/worker/handle_drop.rs, src/mito2/src/worker/handle_flush.rs, src/mito2/src/worker/handle_manifest.rs, src/mito2/src/worker/handle_truncate.rs, src/script/Cargo.toml
- https://github.com/GreptimeTeam/greptimedb/issues/3456
This PR spawns a background task to write the manifest file.
It replaces the `writable` flag with `RegionState` to represent the state of the region.
```rust
/// State of the region.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum RegionState {
/// The region is opened but is still read-only.
ReadOnly,
/// The region is opened and is writable.
Writable,
/// The region is altering.
Altering,
/// The region is dropping.
Dropping,
/// The region is truncating.
Truncating,
/// The region is handling a region edit.
Editing,
}
```
The region rejects write requests while it is not in the writable state. This avoids the region …
=> feat: write manifests in background tasks

src/mito2/src/region/opener.rs
This changes the behavior during datanode startup in that it will always obsolete wal log entries to `flushed_entry_id` in manifest so that if it can tolerate inserts when the entry id span in logstore < `flushed_entry_id`.
=> chore: always obsolete wal to avoid discontinuous log entries

src/servers/src/http/prometheus.rs, src/table/src/table.rs, tests-integration/tests/http.rs
`/labels` without matcher is handled in another way. This patch fixes the incorrect behavior of two cases.
=> fix: post process result on query full column name of prom labels API

.github/workflows/develop.yml
=> fix: fix fuzz test ci

src/flow/src/compute/render.rs, src/flow/src/compute/render/reduce.rs
add `render_reduce` to render module, which render reduce operator into executable dataflow.
Also added related tests for each case
=> feat(flow): render reduce

Cargo.lock, Cargo.toml, src/api/src/helper.rs, src/common/meta/src/rpc/ddl.rs, src/common/meta/src/table_name.rs, src/frontend/src/instance/grpc.rs
Define `CreateFlowTask` and `DropFlowTask`.
=> feat: define `CreateFlowTask` and `DropFlowTask`

src/frontend/src/instance.rs, src/frontend/src/instance/prom_store.rs, src/servers/src/error.rs, src/servers/src/query_handler/sql.rs, src/sql/src/util.rs
This is a follow-up to #3646 and thus #3744 and #3792.
This can be related to #2144.
=> refactor: log statement on error by Display

licenserc.toml, src/servers/src/http/test_helpers.rs
=> chore: respect axum test client's origin

.github/workflows/develop.yml, tests-fuzz/Cargo.toml, tests-fuzz/src/generator/create_expr.rs, tests-fuzz/src/ir.rs, tests-fuzz/targets/fuzz_create_logical_table.rs
#3741 and #3174
Fuzz test for metric engine. Create some logical tables on the same physical table.
=> feat(fuzz): add create logical table target

Cargo.lock, Cargo.toml, src/client/src/client_manager.rs, src/cmd/src/standalone.rs, src/common/grpc-expr/src/alter.rs, src/common/meta/src/datanode_manager.rs, src/common/meta/src/ddl.rs, src/common/meta/src/ddl/alter_table/region_request.rs, src/common/meta/src/ddl_manager.rs, src/common/meta/src/test_util.rs, src/frontend/src/instance/builder.rs, src/frontend/src/instance/region_query.rs, src/frontend/src/instance/standalone.rs, src/meta-srv/src/metasrv/builder.rs, src/meta-srv/src/procedure/tests.rs, src/meta-srv/src/procedure/utils.rs, src/operator/src/delete.rs, src/operator/src/insert.rs, src/operator/src/request.rs, src/store-api/src/region_request.rs
#3664
1. Rename `DatanodeManager` to `NodeManager`.
2. Add the `flownode` method to `NodeManager`, to retrieve the `Flownode` client.
=> refactor: refactor `DatanodeManager` to `NodeManager`

config/standalone.example.toml, src/datanode/src/error.rs, src/datanode/src/region_server.rs, src/query/src/dummy_catalog.rs, src/query/src/error.rs, src/query/src/lib.rs, src/query/src/optimizer.rs, src/query/src/optimizer/order_hint.rs, src/query/src/optimizer/test_util.rs
- https://github.com/GreptimeTeam/greptimedb/issues/3274
This PR fixes the issue that the region server doesn't push down the order hint of the query to the mito engine. This is the first step to optimize `order by ts` and `order by ts limit` statements.
It moves the `DummyTableProvider` to the `common-query` mod so the `OptimizeRule` can correctly downcast the table provider and attach the `OrderOption` to the provider.
Now we can get the order hint in the mito engine:
```sql
create table order_hint(a int primary key, ts timestamp time index);
select * from order_hint order by ts;
```
Then the debug log shows the hint
```
Scan region 4398046511104(1024, 0), request: ScanRequest …
```
=> fix: push down order hint of the query again

.github/workflows/develop.yml, tests-fuzz/Cargo.toml, tests-fuzz/targets/fuzz_alter_logical_table.rs
#3741 and #3174
Alter a logical table on the same physical table. Mostly the same as previous alter table fuzz test, but on metric engine.
=> feat(fuzz): add alter logical table target

src/servers/src/http.rs, src/servers/src/http/prom_store.rs
To be honest, this part is awful. Four almost identical functions with only two booleans different.
I tried to refactor them with const generic but `axum` doesn't support function handler with const generic yet https://github.com/tokio-rs/axum/pull/1265. Using macro is another option but given this part is not likely to change and macro is also not perfect to my perspective, I leave it as is and only fix the wrong param.
=> fix: wrong handler implementation of prometheus remote write

Cargo.lock, Cargo.toml, src/common/frontend/Cargo.toml, src/common/frontend/src/error.rs, src/common/frontend/src/handler.rs, src/common/frontend/src/lib.rs, src/frontend/Cargo.toml, src/frontend/src/instance.rs
1. Introduce the `FrontendInvoker`
2. `FrontendInvoker` allows the `flownode` to write rows to `datanode` (via frontend)
=> feat: implement the `FrontendInvoker`

Cargo.lock, Cargo.toml, src/api/src/helper.rs, src/common/grpc-expr/src/insert.rs, src/common/grpc/src/select.rs, src/operator/src/req_convert/common.rs
https://github.com/GreptimeTeam/greptime-proto/pull/158
close #3230
=> refactor!: remove duration type from gRPC

.github/workflows/develop.yml
#3741 and #3174
Activate the existing insert fuzz test of the mito engine.
=> ci: add fuzz_insert ci cfg

CONTRIBUTING.md, docs/style-guide.md
Fix the wrong link to style guide in `CONTRIBUTING.md`
=> fix: broken link in contributing guide 

src/common/base/src/secrets.rs, src/servers/src/lib.rs, src/servers/src/repeated_field.rs
=> chore: correct RepeatedField origin

grafana/README.md, grafana/greptimedb-cluster.json
This pr mainly adds a new Grafana config json for cluster monitoring. The result should look like following
Checkout `grafana/README.md` for more detail.
Minimal reproduce steps
1. start a GreptimeDB cluster on local machine (including a running `etcd`)
2. start a Prometheus instance. Config file are shown below.
3. start a Grafana instance.
4. log in to Grafana and config Prometheus data source using `http://localhost:9090` (default address for Prometheus)
5. create a new dashboard and import `grafana/greptimedb-cluster.json`
Prometheus config file
```yml
global:
scrape_interval: 5s
evaluation_interval: 5s
scrape_configs:
- job_name: metasrv
static_configs:
- targets: …
```
=> chore: adding Grafana config for cluster monitor

src/cmd/src/cli/upgrade.rs, src/common/meta/src/cache_invalidator.rs, src/common/meta/src/key.rs, src/common/meta/src/key/catalog_name.rs, src/common/meta/src/key/datanode_table.rs, src/common/meta/src/key/flow.rs, src/common/meta/src/key/flow/flow_info.rs, src/common/meta/src/key/flow/flow_name.rs, src/common/meta/src/key/flow/flownode_flow.rs, src/common/meta/src/key/flow/table_flow.rs, src/common/meta/src/key/schema_name.rs, src/common/meta/src/key/table_info.rs, src/common/meta/src/key/table_name.rs, src/common/meta/src/key/table_region.rs, src/common/meta/src/key/table_route.rs, src/frontend/src/heartbeat/handler/tests.rs, tests-integration/tests/region_failover.rs
Wait for #3835
use `MetaKey` trait instead of `TableMetaKey`.
=> refactor: remove `TableMetaKey` trait

src/query/src/optimizer/count_wildcard.rs, tests/cases/standalone/common/aggregate/count.result, tests/cases/standalone/common/aggregate/count.sql
Fix regressions from https://github.com/GreptimeTeam/greptimedb/pull/3845
Use `TableReference` to avoid unexpected canonicalization. And check if the time index column is valid at the plan to use it.
=> fix: count_wildcard_to_time_index_rule doesn't handle table reference properly

.github/workflows/develop.yml, tests-fuzz/Cargo.toml, tests-fuzz/src/generator/insert_expr.rs, tests-fuzz/src/translator/mysql/insert_expr.rs, tests-fuzz/targets/fuzz_insert.rs, tests-fuzz/targets/fuzz_insert_logical_table.rs
#3741 and #3174
Fuzz test for insertions in the metric engine. Since the order of columns of logical table is not the same as declaration, all the insertions have a explicit column list.
=> feat(fuzz): add insert logical table target

.github/workflows/release.yml
Although forks can disable this workflow at all, let's try to skip this step because forks doesn't have the secrets: https://github.com/tisonkun/greptimedb/actions/runs/8962181455/job/24610696840
=> ci: avoid trying to send slack notification in forks

src/common/meta/src/ddl/create_table.rs, src/common/meta/src/lib.rs, src/common/meta/src/region_keeper.rs, src/meta-srv/src/region/lease_keeper.rs
`RegionLeaseKeeper` should retrieve all operating regions in one operation instead of checking on demand to avoid inconsistencies caused by on-demand checking.
=> fix: retrieve all info instead of checking on demand

src/log-store/src/kafka/log_store.rs, src/log-store/src/noop.rs, src/log-store/src/raft_engine/log_store.rs, src/mito2/src/wal.rs, src/store-api/src/logstore.rs
This PR removes one slice copy in wal encoding.
=> chore: remove one slice copy in wal encoding

tests-fuzz/README.md
Update the fuzz tests document. Run fuzz tests in dev mode with sanitizer disabled to reduce compile time.
=> docs: run fuzz tests in dev mode & disable sanitizer

Cargo.toml
Debug info is unnecessary to `sqlness-runner`. Omit it to save space for CI (https://github.com/GreptimeTeam/greptimedb/actions/runs/8980727729/job/24665718225)
=> build: strip sqlness binary

src/servers/src/error.rs, src/servers/src/http/prometheus.rs, tests-integration/tests/http.rs
The previous implement returns the whole query instead of metric name in result. This patch fixes this behavior
=> fix: return metric name instead of query in Prometheus /series API

src/cmd/src/bin/greptime.rs, src/cmd/src/cli.rs, src/cmd/src/datanode.rs, src/cmd/src/frontend.rs, src/cmd/src/lib.rs, src/cmd/src/metasrv.rs, src/cmd/src/options.rs, src/cmd/src/standalone.rs, tests-integration/src/database.rs
The parsing entry of the current command line is a bit messy and I think we need a cleaner and more unified entry. 
- Add the `Command{}` struct: Unify all the cli options, including subcommand and global options. When we load the cli option, use `Command::parse()`;
- Make the `main()` cleaner by using the following sub-functions:
- Add `setup_human_panic()`;
- Add `start()` to load the options and start the service;
- Rename `CliOptions` to `GlobalOptions`;
Reference: [`uv`](https://github.com/astral-sh/uv/blob/main/crates/uv/src/cli.rs#L21-L43) has a clean entry point.
=> refactor: add the main cli entry point struct `Command{}` and simplify `main()`

.github/workflows/develop.yml
Introduce `cargo-gc-bin` to our CI. I've triggered it manually and it looks good
Example run: https://github.com/GreptimeTeam/greptimedb/actions/runs/8982051140/job/24668825435
=> build: run cargo gc to build binaries

Cargo.lock, Cargo.toml, src/catalog/src/information_schema/cluster_info.rs, src/meta-client/src/client.rs, src/meta-client/src/client/cluster.rs, src/meta-srv/Cargo.toml, src/meta-srv/src/election.rs, src/meta-srv/src/election/etcd.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/service/cluster.rs, tests/cases/distributed/information_schema/cluster_info.result, tests/cases/distributed/information_schema/cluster_info.sql
Allow to get metsrvs' node info (version and git_commit).
proto: https://github.com/GreptimeTeam/greptime-proto/pull/163
Closes: #3843
=> feat: metasrvs nodeinfo

src/common/base/src/lib.rs, src/common/base/src/plugins.rs
It's a minor refactoring for `Plugins` to make it clean.
In this PR:
1. Move `Plugins` from `lib.rs` to the new mod file `plugins.rs`;
2. Add some simple and necessary unit tests for `Plugins`;
3. Use `RwLock` instead of `Mutex` to improve performance;
=> refactor: move `Plugins` to `plugins.rs` and use rwlock

src/log-store/src/kafka.rs, src/log-store/src/noop.rs, src/log-store/src/raft_engine.rs, src/store-api/src/logstore/entry.rs, src/store-api/src/logstore/entry_stream.rs
- Remove `Entry::namespace` method and related asscoiated type.
- Fix the estimated size logic to computing the encoded length of entries.
=> refactor(logstore): remove Entry::namemspace

src/mito2/src/cache.rs, src/mito2/src/engine/basic_test.rs, src/mito2/src/read/projection.rs, tests/cases/standalone/common/insert/nullable_tag.result, tests/cases/standalone/common/insert/nullable_tag.sql
- fixes https://github.com/GreptimeTeam/greptimedb/issues/3869
This PR adds data type to the cache key for repeated vectors. It fixes the issue that different data types use the same null vector in the cache. When the reader gets a null vector from the cache, the data type of the vector might not be the expected type and result in the following error: `column types must match schema types`.
=> fix: add data type to vector cache key

src/servers/src/error.rs, src/servers/src/http/prometheus.rs, src/servers/src/prom_store.rs, src/table/src/table.rs, tests-integration/tests/http.rs
The extended special matcher `__field__` is used to specify which field to query in multi-field scenario. This patch adds support for querying the possible values of `__field__`
It works like
=> feat: support querying field column names in Prometheus HTTP API

Cargo.lock, Cargo.toml, src/meta-client/src/client.rs, src/meta-srv/src/election.rs, src/meta-srv/src/election/etcd.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/metasrv/builder.rs, src/meta-srv/src/service/cluster.rs, tests/cases/distributed/information_schema/cluster_info.result
Add start time to metasrv's node info.
Before:
After:
proto: https://github.com/GreptimeTeam/greptime-proto/pull/167
=> feat: add metasrv start time to node info

src/catalog/src/information_schema/columns.rs, src/catalog/src/information_schema/partitions.rs, src/catalog/src/information_schema/region_peers.rs, src/catalog/src/information_schema/table_constraints.rs, src/catalog/src/information_schema/tables.rs, src/catalog/src/kvbackend/manager.rs, src/catalog/src/lib.rs, src/catalog/src/memory/manager.rs, src/servers/src/http/prometheus.rs
As the title said, the `tables` API does nod need to be an async method since it return a BoxStream
=> chore: avoid double future

src/frontend/src/instance.rs, src/operator/src/statement.rs, src/sql/src/parser.rs, src/sql/src/parsers/create_parser.rs, src/sql/src/parsers/drop_parser.rs, src/sql/src/statements/drop.rs, src/sql/src/statements/statement.rs
Implement `Drop Flow` statement parser
=> feat: implement drop flow parser

src/common/greptimedb-telemetry/src/lib.rs
Remove this:
```rust
let url = Box::leak(format!("{}:{}", "http://localhost", port).into_boxed_str());
```
=> fix: memory leak in unit test of telemetry

Cargo.lock, Cargo.toml
=> chore: bump proto to 219b24

src/mito2/src/sst/parquet.rs, src/mito2/src/sst/parquet/file_range.rs, src/mito2/src/sst/parquet/format.rs, src/mito2/src/sst/parquet/partition.rs, src/mito2/src/sst/parquet/reader.rs
- https://github.com/GreptimeTeam/greptimedb/issues/2806
This PR defines the `FileRange` struct for parquet files and implements a method `build_file_ranges()` to build ranges from a parquet file. A `FileRange` contains a range of rows to read from a parquet file. We can read different ranges in parallel later. Now a `FileRange` is a row group exactly.
```rust
pub struct FileRange {}
impl FileRange {
pub(crate) async fn reader(&self) -> Result<RowGroupReader> {}
}
```
To reuse code, this PR
- Refactors the `ParquetReader`. Now it adds a `RowGroupReader` to read `Batches` from a row group. The `ParquetReader` invokes the `RowGroupReader` to read the parquet file.
- Defines a …
=> feat: Parquet reader builder supports building multiple ranges to read

docs/benchmarks/tsbs/v0.7.0.md
The previous data is "metrics/sec", not "rows/sec" 🥵
=> docs: correct v0.7 benchmark report

src/cmd/src/options.rs, src/cmd/src/standalone.rs, src/common/wal/src/config.rs, tests-integration/src/standalone.rs, tests-integration/src/test_util.rs, tests-integration/src/tests/test_util.rs, tests-integration/tests/http.rs
The original `MixOptions` is similar to `StandaloneOptions`. We should keep one option struct and get equilant function for easy maintenance.
=> refactor: remove MixOptions and use StandaloneOptions only

src/common/meta/src/ddl_manager.rs
Add a `procedure_loader` macro to reduce code duplication
=> refactor: add `procedure_loader` macro

src/datanode/src/heartbeat.rs, src/frontend/src/instance.rs, src/meta-client/examples/meta_client.rs, src/meta-client/src/client.rs, src/meta-client/src/mocks.rs, tests-integration/src/cluster.rs
There are too many options in MetaClient, but the configurations for the same roles when building MetaClient are almost identical. Therefore, it would be better to provide default options for different roles.
Closes #3660
=> feat: metaclient builder options with role

src/common/meta/src/cache.rs, src/common/meta/src/cache/table.rs, src/common/meta/src/cache/table/composite_table_route.rs, src/common/meta/src/cache/table/table_route.rs
1. Implement the `CompositeTableRoute`
The `CompositeTableRoute` stores all level routes of a table:
- Stores `PhysicalTableRouteValue` for logical table.
- Stores `LogicalTableRouteValue`, `PhysicalTableRouteValue` for the logical table.
=> feat: implement the `CompositeTableRoute`

src/cmd/src/datanode.rs, src/cmd/src/frontend.rs
This PR renames `metasrv_addr` to `metasrv_addrs` in start command.
Use the alias mechanism `aliases = ["metasrv-addr"]` to ensure forward compatibility.
=> refactor: rename metasrv_addr to metasrv_addrs

config/config.md, config/datanode.example.toml, config/frontend.example.toml, config/metasrv.example.toml, config/standalone.example.toml, src/cmd/src/bin/greptime.rs, src/cmd/src/datanode.rs, src/cmd/src/frontend.rs, src/cmd/src/metasrv.rs, src/cmd/src/standalone.rs, src/common/telemetry/src/logging.rs, src/datanode/src/config.rs, src/frontend/src/frontend.rs, src/meta-srv/src/metasrv.rs, tests-integration/tests/http.rs
Add tracing options in `{DatanodeOptions, FrontendOptions, MetasrvOptions, StandaloneOptions}`.
There are some reasons for adding the `tracing`:
1. Ensure that the `*Options` structure can hold all the necessary options. It would be convenient if you could pass this structure to another function
2. The users configure `tracing` not only through the command line parameters but also via the environment and configuration file.
=> refactor: add tracing options in xOptions

src/cmd/src/metasrv.rs, src/meta-srv/src/bootstrap.rs, src/meta-srv/src/metasrv.rs
The fish that got away from PR #3921
This PR renames store_addr to store_addrs in start command.
Use the alias mechanism aliases = ["store-addr"] to ensure forward compatibility.
=> chore: store-addr to store-addrs

Cargo.lock, Cargo.toml, src/common/substrait/src/df_substrait.rs, src/common/substrait/src/lib.rs, src/flow/Cargo.toml, src/flow/src/adapter.rs, src/flow/src/adapter/error.rs, src/flow/src/adapter/node_context.rs, src/flow/src/compute.rs, src/flow/src/compute/render.rs, src/flow/src/compute/render/map.rs, src/flow/src/compute/render/reduce.rs, src/flow/src/compute/render/src_sink.rs, src/flow/src/compute/state.rs, src/flow/src/compute/types.rs, src/flow/src/expr/error.rs, src/flow/src/expr/func.rs, src/flow/src/expr/id.rs, src/flow/src/expr/relation/func.rs, src/flow/src/plan.rs, src/flow/src/repr.rs, src/flow/src/repr/relation.rs, src/flow/src/transform.rs, src/flow/src/transform/aggr.rs, src/flow/src/transform/expr.rs, src/flow/src/transform/literal.rs, src/flow/src/transform/plan.rs
Added `render_src/sink` functions to render source/sinks into dataflow, and node context to manage them
- added `render_src/sink` to render source/sink in dataflow, using broadcast receiver in render_src, and unbounded_channel in render_sink
- added Node Context for helping transform sql to flow's execution plan
=> feat(flow): render source/sink

src/log-store/src/raft_engine/backend.rs
fix potential deadlock
see also: https://doc.rust-lang.org/std/sync/struct.RwLock.html
=> fix: potential deadlock

.github/workflows/apidoc.yml, .github/workflows/develop.yml, .github/workflows/nightly-ci.yml, .github/workflows/release.yml, rust-toolchain.toml, src/common/runtime/src/repeated_task.rs, src/mito2/src/sst/index/creator/temp_provider.rs
- https://github.com/GreptimeTeam/greptimedb/issues/3902
- This is likely related to https://github.com/rust-lang/rust/issues/123999
https://github.com/GreptimeTeam/greptimedb/actions/runs/9009678033/job/24754350747
```
Running `target\debug\sqlness-runner.exe`
error: process didn't exit successfully: `target\debug\sqlness-runner.exe` (exit code: 0xc0000142, STATUS_DLL_INIT_FAILED)
Error: Process completed with exit code 1.
```
Upgrading the rust toolchain should fix this.
- https://github.com/GreptimeTeam/greptimedb/actions/runs/9043603077
- https://github.com/GreptimeTeam/greptimedb/actions/runs/9043764916
We also need to release a new dev-builder after this PR: …
=> build: upgrade rust toolchain to fix ci issues on Windows

src/common/meta/src/cache_invalidator.rs, src/common/meta/src/ddl/create_flow.rs, src/common/meta/src/ddl/drop_flow.rs, src/common/meta/src/flow_name.rs, src/common/meta/src/instruction.rs, src/common/meta/src/lib.rs, src/common/meta/src/rpc/ddl.rs
1. Invalidate flow cache in the create flow procedure
2. Invalidate flow cache in the drop flow procedure
=> feat: support to invalidate flow cache

src/catalog/src/kvbackend/client.rs, src/common/meta/src/kv_backend.rs, src/common/meta/src/kv_backend/etcd.rs, src/common/meta/src/kv_backend/memory.rs, src/common/meta/src/kv_backend/txn.rs, src/log-store/src/raft_engine/backend.rs
There is a long story to tell. Initially, we implemented `compare_and_put`, and later incorporated `Txn`.
As a result, there were multiple implementations of `compare_and_put` in our `KvBackend`s that we need to maintain consistent behavior with.
With the introduction of `Txn`, it became easier for us to implement `compare_and_put`. In this PR, I utilized `Txn` for its implementation and removed all other methods.
=> feat: use txn to impl cas

Cargo.lock, src/flow/Cargo.toml, src/flow/src/compute/render.rs, src/flow/src/compute/render/map.rs, src/flow/src/compute/render/reduce.rs, src/flow/src/expr/scalar.rs, src/flow/src/plan.rs, src/flow/src/repr/relation.rs, src/flow/src/transform/aggr.rs, src/flow/src/transform/expr.rs, src/flow/src/transform/plan.rs
Added types(`RelationType`) for every flow plan's variant
Added type info to every plan enum, and also add `typ()` for `ScalarExpr` so to determine expressions' types
=> feat(flow): add types for every plan enum variant

src/mito2/src/memtable/partition_tree.rs, src/mito2/src/memtable/partition_tree/dict.rs, src/mito2/src/memtable/partition_tree/partition.rs, src/mito2/src/memtable/partition_tree/shard.rs, src/mito2/src/memtable/partition_tree/shard_builder.rs, src/mito2/src/test_util/memtable_util.rs
- fixes #3881
This PR fixes the issue where the same primary key gets wrong pk index when dict_builder is frozen. The root cause can be found [here](https://github.com/GreptimeTeam/greptimedb/issues/3881#issuecomment-2109165032).
This PR has little impaction to the ingestion performance of metric engine.
=> fix(metric engine): label mismatch in metric engine

src/common/meta/src/kv_backend/etcd.rs, src/common/meta/src/kv_backend/memory.rs, src/common/meta/src/kv_backend/txn/etcd.rs, src/log-store/src/raft_engine/backend.rs
As the title said:
1. Avoid `clone` in txn
2. Use `KeyValue::from` and remove `convert_key_value` method
3. Use `KeyValue::from` instead of `Into::into` for clearer code
=> chore: minor refactor on etcd kvbackend

Cargo.lock, src/flow/Cargo.toml, src/flow/src/adapter.rs, src/flow/src/adapter/error.rs, src/flow/src/adapter/worker.rs, src/flow/src/compute/render.rs
A simple flow worker that runs on a seperate thread and accept requests accross thread in a blocking style
A flow worker which can create flow, drop flow and trigger flow running
=> feat(flow): flow worker

Cargo.lock, Cargo.toml
Update greptime-proto to a11db14
=> chore: update greptime-proto to a11db14

Cargo.lock, tests-fuzz/Cargo.toml, tests-fuzz/src/generator.rs, tests-fuzz/src/generator/insert_expr.rs, tests-fuzz/src/ir.rs, tests-fuzz/src/ir/insert_expr.rs, tests-fuzz/src/translator/mysql/insert_expr.rs, tests-fuzz/src/validator.rs, tests-fuzz/src/validator/row.rs, tests-fuzz/targets/fuzz_insert.rs, tests-fuzz/targets/fuzz_insert_logical_table.rs
#3174 and #3741
Add validator for inserted rows in fuzz test.
=> feat(fuzz): add validator for inserted rows

src/common/meta/src/key/table_info.rs, src/flow/src/adapter.rs, src/flow/src/adapter/error.rs, src/flow/src/adapter/node_context.rs, src/flow/src/adapter/table_source.rs, src/flow/src/adapter/util.rs, src/flow/src/adapter/worker.rs, src/flow/src/repr.rs, src/flow/src/transform.rs
added `TableSource` to get table name, id and schema from metasrv, and other minor refactor
- added `TableSource` to help flow node get table name, id and schema from metasrv
- refactor `SourceSender` to allow unbounded broadcast
=> feat(flow): query table schema&refactor

src/operator/src/insert.rs, src/operator/src/req_convert/insert/row_to_region.rs
... to eliminate redundant calls to `catalog_manager.table(...)`.
=> perf(operator): reuse table info from table creation

.github/workflows/nightly-ci.yml, src/servers/src/tls.rs
- https://github.com/GreptimeTeam/greptimedb/issues/3902
This PR attempts to **Make Actions Pass Again**, **MAPA** in short.
It switches the default linker to LLVM's lld which has lower memory consumption. It also enables logs for the test `test_tls_file_change_watch`.
The previous action cost 50m to compile tests...... Most time is spent in linking.
https://github.com/GreptimeTeam/greptimedb/actions/runs/9087338152/job/24981188499
=> ci: Use lld linker in windows tests

Cargo.lock, Cargo.toml, src/cmd/Cargo.toml, src/cmd/src/datanode.rs, src/cmd/src/error.rs, src/cmd/src/frontend.rs, src/cmd/src/metasrv.rs, src/cmd/src/options.rs, src/cmd/src/standalone.rs, src/common/config/Cargo.toml, src/common/config/src/config.rs, src/common/config/src/error.rs, src/common/config/src/lib.rs, src/datanode/Cargo.toml, src/datanode/src/config.rs, src/datanode/src/error.rs, src/datanode/src/service.rs, src/frontend/src/error.rs, src/frontend/src/frontend.rs, src/frontend/src/instance.rs, src/frontend/src/server.rs, src/meta-srv/Cargo.toml, src/meta-srv/src/bootstrap.rs, src/meta-srv/src/error.rs, src/meta-srv/src/metasrv.rs, tests-integration/src/test_util.rs
Add the `Configurable` trait to make configuration more general.
1. Add the new module `error.rs` and `config.rs` in `common/config`. Most of the code are from `cmd/`:
- The `load_layer_options()` is from the original `cmd/options.rs`;
- The errors are from `cmd/error.rs`;
3. Add `merge_with_cli_options()` to make `load_options()` more simple;
4. Implement `Configurable` trait and changed some tests for `{DatanodeOptions, FrontendOptions, MetasrvOptions, StandaloneOptions}`;
=> refactor: add `Configurable` trait

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/feature.yml
=> chore: catch up label updates

src/servers/src/tls.rs
Give file change detection test on windows more time.
=> test: give windows file watcher more time

src/cmd/src/cli.rs, src/cmd/src/cli/export.rs, src/cmd/src/lib.rs
Export metric physical tables first
=> feat(cli): export metric physical tables first

src/flow/src/compute/render.rs, src/flow/src/compute/render/reduce.rs, src/flow/src/compute/types.rs, src/flow/src/expr/func.rs, src/flow/src/expr/relation/func.rs, src/flow/src/plan.rs, src/flow/src/repr/relation.rs, src/flow/src/transform/aggr.rs
added `avg` functino support
- added `avg` function support, which will be rewrite to sum(x)/count(x) if count(x)!=0
- fix aggr func's signature's output type to be the real evaled type(i.e. SumUInt* -> u64, SumInt* -> i64)
=> feat(flow): avg func rewrite to sum/count

src/flow/src/adapter/worker.rs, src/flow/src/compute/render.rs, src/flow/src/compute/render/reduce.rs, src/flow/src/compute/state.rs, src/flow/src/utils.rs
set arrangement's expire time with `TypedPlan`'s time index
- Set arrangement's expire time with `TypedPlan`'s time index
- Added expire when to dataflow's state, so `render_reduce` can access it and set arrangement to expire accordingly
=> feat(flow): expire arrange according to time_index type

tests-integration/tests/sql.rs
Some tests of our postgres server failed on macOS
```bash
integration_sql_file_test::test_postgres_parameter_inference ---
thread 'tokio-runtime-worker' panicked at tests-integration/tests/sql.rs:773:26:
called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" }) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
libunwind: stepWithCompactEncoding - invalid compact unwind encoding
```
After adding some logs, I found that the test finished and the server was shut down. We unwrap the result from the connection in tests so the test is panic if the server is shut …
=> test: gracefully shutdown postgres client in sql tests

src/operator/src/statement.rs, src/operator/src/statement/copy_database.rs, src/operator/src/statement/copy_table_from.rs, src/sql/src/error.rs, src/sql/src/parsers/copy_parser.rs, src/sql/src/statements/copy.rs, src/table/src/requests.rs, tests/cases/standalone/common/copy/copy_database_from_fs_parquet.result, tests/cases/standalone/common/copy/copy_database_from_fs_parquet.sql, tests/cases/standalone/common/copy/copy_from_fs_parquet.result, tests/cases/standalone/common/copy/copy_from_fs_parquet.sql
close: #3889
limit total rows copied in COPY TABLE FROM with LIMIT segment
=> feat: limit total rows copied in COPY TABLE FROM with LIMIT segment

Cargo.lock, config/config.md, config/frontend.example.toml, src/cmd/Cargo.toml, src/cmd/src/frontend.rs, src/common/grpc/src/channel_manager.rs, src/frontend/src/service_config/datanode.rs
Don't timeout on gRPC connection from frontend to datanode. For some queries are expected to take a long while.
=> feat: remove timeout in the channel between frontend and datanode

src/mito2/src/compaction/twcs.rs, src/mito2/src/flush.rs, src/mito2/src/worker/handle_flush.rs
Read-only regions cannot be flushed. Skip them on trying to pick one when engine is full
=> feat: skip read-only region when trying to flush on region full

src/meta-srv/src/handler/publish_heartbeat_handler.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/metasrv/builder.rs, src/meta-srv/src/pubsub.rs, src/meta-srv/src/pubsub/publish.rs, src/meta-srv/src/pubsub/subscribe_manager.rs, src/meta-srv/src/pubsub/tests.rs
Refactor the naming of pubsub and use names that are more in line with conventions, for example:
- `publish` / `subscribe` / `unsubscribe`
- `subscription`
...
=> refactor(naming): use the better naming for pubsub

.github/actions/build-windows-artifacts/action.yml, .github/workflows/nightly-ci.yml
- https://github.com/GreptimeTeam/greptimedb/issues/3902
Sets RUSTUP_WINDOWS_PATH_ADD_BIN to 1 to fix the release action, according to https://github.com/nextest-rs/nextest/issues/1493
=> build: add RUSTUP_WINDOWS_PATH_ADD_BIN env

src/operator/src/statement/copy_database.rs
prevent exporting metric physical table data
=> fix: prevent exporting metric physical table data

Cargo.lock, Cargo.toml, src/query/src/range_select/plan_rewrite.rs, tests/cases/standalone/common/range/error.result, tests/cases/standalone/common/range/to.result, tests/cases/standalone/common/range/to.sql
Support use expr can be evaluate at logical plan stage (e.g. `INTERVAL '2' day - INTERVAL '1' day`)
Support case like:
```sql
SELECT
ts, 
min(val) RANGE (now() - (now() - INTERVAL '2' day + INTERVAL '1' day)) 
FROM 
host
ALIGN
(now() - (now() - INTERVAL '2' day + INTERVAL '1' day)) 
TO 
(now() - (now() + INTERVAL '1' hour)) 
by (1) 
ORDER BY ts;
```
- support parse expr in pr  https://github.com/GreptimeTeam/sqlparser-rs/pull/12
- support use `ExprSimplifier` to evaluate expr in range query plan rewrite stage
=> feat: support evaluate expr in range query param

src/sql/src/parsers/alter_parser.rs, src/sql/src/statements/alter.rs, src/sql/src/statements/transform/type_alias.rs
Fixed `alter table modify column` statement change column data type can't process data type alias. For example:
```
alter table monitor modify column host TinyText
```
=> fix: changing column data type can't process type alias

src/sql/src/parsers/tql_parser.rs
I find this occasionally by a typo
And flamegraph tells me there is a dead loop
=> fix: tql parser hang on abnormal input

src/cmd/src/cli/export.rs
prevent exporting physical table data
=> feat(cli): prevent exporting physical table data

config/config-docs-template.md, config/config.md
- Add TOC for config docs
- `Cluster` -> `Distributed`(keep consistent with the code);
=> docs: add toc for config docs

.github/workflows/dev-build.yml, .github/workflows/nightly-build.yml, .github/workflows/nightly-ci.yml, .github/workflows/release.yml, cyborg/bin/report-ci-failure.ts
Create a new issue on CI failure, or comment on an existing issue.
=> ci: report CI failures with creating issues 

docs/benchmarks/tsbs/v0.8.0.md
- https://github.com/GreptimeTeam/greptimedb/issues/3959
Adds v0.8.0 TSBS benchmark results to docs.
There is a regression in the ingest rate compared to v0.7.0. A possible cause is that we switch to the `time_series` memtable but the impact under TSBS should be small. We may need further investigation.
=> docs: add v0.8.0 TSBS report

docker/dev-builder/android/Dockerfile
pin cargo-ndk version to 3.5.4 (Key Tech🥲)
=> chore: pin cargo-ndk to 3.5.4

src/mito2/src/compaction/twcs.rs
This PR passes the cache to the reader built for compaction so the compaction can reuse cached pages and files.
=> feat: use cache in compaction

src/cmd/src/bin/greptime.rs, src/cmd/src/cli.rs, src/cmd/src/datanode.rs, src/cmd/src/frontend.rs, src/cmd/src/lib.rs, src/cmd/src/metasrv.rs, src/cmd/src/options.rs, src/cmd/src/standalone.rs, src/common/telemetry/src/logging.rs, tests-integration/src/database.rs
**NOTE**: The PR is decoupled with draft PR https://github.com/GreptimeTeam/greptimedb/pull/3941, and it's just a simple refactoring based on the original implementation.
- **Remove** `Options{}` and some related methods, and all the building process of options can be in their app(for example, `datanode.rs`/`metasrv.rs`/...);
- **Remove** `SubCommand.build()` and `SubCommand.load_options()` which are unnecessary;
- **Move** `common_telemetry::init_global_logging` into `<app>:build()` which can be easy to receive the arguments;
- **Move** `start_app()` into `App` and rename `run()`;
- Make `common_telemetry::init_global_logging` init once, or it will fail in integration test (what …
=> refactor:  make the command entry cleaner

.github/workflows/release.yml
add `contents: write` permission for github action release workflow.
=> ci: add 'contents: write' permission

.github/workflows/nightly-build.yml
Change the image name of nightly build for avoiding conflict with the release images.
=> ci: change the image name of nightly build

.github/actions/setup-greptimedb-cluster/action.yml
=> fix: try to fix broken CI

src/common/meta/src/ddl/create_view.rs, src/common/procedure/src/local.rs, src/common/procedure/src/store.rs
=> feat: make create view procedure simple as others

src/cmd/src/bin/greptime.rs, src/cmd/src/datanode.rs, src/cmd/src/frontend.rs, src/cmd/src/metasrv.rs, src/cmd/src/standalone.rs
Move `log_version()` into `build()` of `App` to fix no log version on bootstrap since the `common_telemetry::init_global_logging` is in the `build()`.
=> fix: move log_version() into build() of App to fix no log version on bootstrap

tests-fuzz/targets/unstable/fuzz_create_table_standalone.rs
1. ignore `PoolTimedOut` error for now
=> fix: try to fix unstable fuzz test 

src/common/recordbatch/src/filter.rs, src/mito2/src/engine/prune_test.rs, src/mito2/src/error.rs, src/mito2/src/read/scan_region.rs, src/mito2/src/sst/parquet/reader.rs, src/query/src/tests/time_range_filter_test.rs, src/table/src/predicate.rs, src/table/src/table/adapter.rs
- #3944
This PR converts the desired time range into `SimpleFilterContext` while building parquet readers so that the reader can filter out those rows outside the desired time range.
=> feat: respect time range when building parquet reader

Cargo.lock, src/cmd/Cargo.toml, src/cmd/src/cli.rs, src/cmd/src/cli/bench.rs, src/cmd/src/cli/export.rs, src/cmd/src/cli/upgrade.rs, src/cmd/src/datanode.rs, src/cmd/src/frontend.rs, src/cmd/src/metasrv.rs, src/cmd/src/standalone.rs
The bug is caused by https://github.com/GreptimeTeam/greptimedb/pull/3981.
It's a fast fix for adding `guard` in `Instance` to avoid dropping.
I think the elegant way to resolve the problem is to refactor the `init_global_logging()`, split it into multiple functions, and initialize it at the beginning of `main()`.
**We should release the new version of db after the PR is merged**. Fortunately, it's not in the v0.8.0.
=> fix: can't print log because the tracing guard is dropped

tests-fuzz/src/ir.rs, tests-fuzz/src/ir/insert_expr.rs, tests-fuzz/targets/fuzz_insert.rs, tests-fuzz/targets/fuzz_insert_logical_table.rs
close #4000
As title. Correct the failed fuzz seed `FuzzInput { seed: 266, columns: 19, rows: 3995 }`
The time index is treated as one of the primary keys for sorting. To compare the `Value::Default` with other values, all the default values in the `insert_expr` is replaced with its original value.
=> fix(fuzz): sort inserted rows with primary keys and time index

config/config.md, config/datanode.example.toml, config/standalone.example.toml, src/mito2/src/cache/file_cache.rs, src/mito2/src/cache/write_cache.rs, src/mito2/src/config.rs, src/mito2/src/engine/basic_test.rs, src/mito2/src/test_util.rs, src/mito2/src/worker.rs, tests-integration/tests/http.rs
=> chore: add ttl to write_cache

Cargo.lock, Cargo.toml, src/common/function/src/table/flush_compact_table.rs, src/datanode/src/region_server.rs, src/mito2/src/compaction.rs, src/mito2/src/compaction/buckets.rs, src/mito2/src/compaction/task.rs, src/mito2/src/compaction/twcs.rs, src/mito2/src/compaction/window.rs, src/mito2/src/engine/append_mode_test.rs, src/mito2/src/engine/compaction_test.rs, src/mito2/src/error.rs, src/mito2/src/worker.rs, src/mito2/src/worker/handle_compaction.rs, src/mito2/src/worker/handle_flush.rs, src/operator/src/request.rs, src/session/src/table_name.rs, src/sql/src/error.rs, src/store-api/src/region_request.rs, src/table/Cargo.toml, src/table/src/requests.rs
- closes #3882
This PR adds support for manually trigger different types of compactions.
The syntax is:
```sql
SELECT COMPACT_TABLE("<table_name>", ["<compact_type>"], ["<options>"])
```
Currently, `compact_type` supports `regular` and `strict_window`.
- `regular`: regular compaction like those triggered by flush.
- `strict_window`: split SST files strictly by time window.
The `<options>` argument is type-sepecific compaction options. For `strict_window`, the option value is the compaction window in seconds.
=> feat: manual compaction

src/servers/src/http/prom_store.rs, tests-integration/tests/http.rs
Fixes #3929 
Added fallback logic to handle situation when vmagent send wrong content type of data.
=> feat: add fallback logic for vmagent sending wrong content type

.github/actions/setup-etcd-cluster/action.yml, .github/actions/setup-greptimedb-cluster/action.yml, .github/workflows/develop.yml
As the title said, add more etcd, frontend, meta replicas for test.
=> chore(ci): add more replicas

src/mito2/src/metrics.rs, src/mito2/src/worker.rs, src/mito2/src/worker/handle_flush.rs, src/mito2/src/worker/handle_write.rs
fixes https://github.com/GreptimeTeam/greptimedb/issues/4012
This PR notifies all workers once a region is flushed to ensure all stalled write requests can proceed. All workers share the same `watch` channel and they use that channel to notify each other. The worker loop will select both the request receiver and the `watch` channel receiver.
It also changes the `greptime_mito_write_stall_total` metric to a gauge vec for all workers.
=> fix: notifies all workers once a region is flushed

src/partition/src/manager.rs, src/partition/src/partition.rs
`String::from_utf8_lossy` and `serde_json::from_str` are not in-place operations. It's not necessary to clone it and use by ref.
=> feat: remove one clone on constructing partition

src/log-store/src/kafka.rs, src/log-store/src/noop.rs, src/log-store/src/raft_engine.rs, src/mito2/src/wal.rs, src/mito2/src/wal/raw_entry_reader.rs, src/mito2/src/wal/wal_entry_reader.rs, src/store-api/src/logstore/entry.rs, src/store-api/src/logstore/entry_stream.rs
#4026 
Add  `RawEntryReader` and `OneShotWalEntryReader` trait
=> feat: add `RawEntryReader` and `OneshotWalEntryReader` trait

src/common/meta/src/ddl/table_meta.rs, src/meta-srv/src/bootstrap.rs, src/meta-srv/src/cluster.rs, src/meta-srv/src/selector.rs, src/meta-srv/src/selector/lease_based.rs, src/meta-srv/src/selector/round_robin.rs, src/meta-srv/src/table_meta_alloc.rs, src/meta-srv/src/test_util.rs
Implement RoundRobin Selector which selects peers in a completely fair way.
=> feat: round-robin selector

src/mito2/src/error.rs, src/mito2/src/wal/raw_entry_reader.rs, src/store-api/src/logstore/entry.rs
#4026 
1. Implement the `LogStoreRawEntryReader`, which reads undecoded raw WAL entries from the underlying LogStore implementation.
2. Implement the `RawEntryReaderFilter`
=> feat: implement the `LogStoreRawEntryReader` and `RawEntryReaderFilter`

src/operator/src/statement/ddl.rs, src/table/src/requests.rs, tests/cases/standalone/common/create/create.result, tests/cases/standalone/common/create/create.sql
close: #3836
support table level comment
=> feat: support table level comment

src/operator/src/error.rs, src/operator/src/statement/ddl.rs, tests/cases/standalone/common/catalog/schema.result, tests/cases/standalone/common/catalog/schema.sql, tests/cases/standalone/common/create/upper_case_table_name.result, tests/cases/standalone/common/create/upper_case_table_name.sql
https://github.com/GreptimeTeam/greptimedb/issues/4029
check if a database/schema is in use before dropping it.
=> feat(opertor): check if a database is in use before dropping it

src/mito2/src/region.rs
add logs for setting the region to writable
=> chore: add logs for setting the region to writable

src/cmd/src/standalone.rs, src/datanode/src/error.rs, src/servers/src/grpc/builder.rs, src/servers/src/http.rs, tests-integration/src/test_util.rs
In our customer's env, we've observed a lot of "dangling" http connections. They are all in the “established” state, even the client side pods were already destroyed long before. These dangling connections are harmful, somehow they consumed a lot of memory.
For the origin of the dangling connections, my guessing is that the client side pods are not gracefully shutdown, or the bad network. They are both common situations in cloud env, so I decide to add the keepalive option for http server: if the connections are idle for 1 hour, close it actively in the server side.
I'm a little hesitate to expose the keepalive option in the config file. For http connection, if not http2, …
=> feat: enable tcp keepalive for http server

Cargo.toml, src/common/grpc/Cargo.toml, src/frontend/Cargo.toml, src/meta-client/Cargo.toml, src/meta-srv/Cargo.toml, src/servers/Cargo.toml, tests-integration/Cargo.toml
=> build(deps): merge tower deps to workspace

tests-fuzz/targets/unstable/fuzz_create_table_standalone.rs
=> fix(fuzz-tests): avoid to drop in-use database

src/metric-engine/src/engine.rs, src/metric-engine/src/error.rs, tests-fuzz/src/ir.rs, tests-fuzz/src/utils.rs, tests-fuzz/targets/fuzz_insert.rs, tests-fuzz/targets/fuzz_insert_logical_table.rs
close #4046
Invoke `flush_table` and `compact_table` in fuzz tests
=> feat: invoke `flush_table` and `compact_table` in fuzz tests

tests-fuzz/src/generator.rs, tests-fuzz/src/generator/insert_expr.rs, tests-fuzz/src/ir.rs, tests-fuzz/targets/fuzz_insert.rs, tests-fuzz/targets/fuzz_insert_logical_table.rs
=> refactor(fuzz-tests): generate ts value separately

src/datanode/src/heartbeat.rs, src/datanode/src/metrics.rs
add `LAST_SENT_HEARTBEAT_ELAPSED` metric
=> chore: add `LAST_SENT_HEARTBEAT_ELAPSED` metric

src/servers/src/mysql/federated.rs, src/sql/src/parsers/set_var_parser.rs, tests/cases/standalone/common/system/timezone.result, tests/cases/standalone/common/system/timezone.sql, tests/runner/src/env.rs
See https://github.com/GreptimeTeam/greptimedb/issues/3887
The doc PR https://github.com/GreptimeTeam/docs/pull/988
Fix `SET SESSION time_zone='Asia/Shanghai'` or `SET LOCAL time_zone='Asia/Shanghai'`  not work.
=> fix: set local or session time_zone not work

src/flow/src/adapter.rs, src/flow/src/adapter/flownode_impl.rs, src/flow/src/adapter/node_context.rs, src/flow/src/adapter/table_source.rs, src/flow/src/compute/render/map.rs, src/flow/src/compute/render/reduce.rs, src/flow/src/compute/render/src_sink.rs, src/flow/src/expr/error.rs, src/flow/src/expr/func.rs, src/flow/src/expr/scalar.rs, src/flow/src/repr/relation.rs, src/flow/src/transform.rs, src/flow/src/transform/aggr.rs, src/flow/src/transform/expr.rs, src/flow/src/transform/plan.rs, src/flow/src/utils.rs
fix some correctness bugs
- fix reorder of insert requests columns
- fix choose the correct scalar function type
- fix combine of avg&tumble cause transform errors
- fix tumble ts < window start offset by one
=> fix(flow): correctness bugs

src/datanode/src/region_server.rs, src/datanode/src/tests.rs, src/file-engine/src/engine.rs, src/metric-engine/src/engine.rs, src/mito2/src/engine.rs, src/mito2/src/engine/basic_test.rs, src/mito2/src/manifest/manager.rs, src/mito2/src/manifest/storage.rs, src/mito2/src/region.rs, src/mito2/src/region/opener.rs, src/mito2/src/test_util.rs, src/mito2/src/test_util/scheduler_util.rs, src/query/src/optimizer/test_util.rs, src/store-api/src/region_engine.rs
This PR uses `Arc<Atomicu64>` to store the shared value instead of `RwLock`, to avoid acquiring lock during reading value.
The datanode will report the stats (like manifest usage) via heartbeat. Before sending the heartbeat to the metasrv, it collects all stats from the region server. While collecting `disk_usage` will invoke the `manifest_usage` method on the `manifest_manager`, this operation is required to acquire the read lock of the `manifest_manager`. 
```rust
// read manifest_usage
let manifest_usage = self
.manifest_ctx
.manifest_manager
.read()
.await
.manifest_usage();
``` 
```rust
let mut manager = self.manifest_manager.write().await;
// update manifest
// ..
``` …
=> fix: avoid acquiring lock during reading stats

src/operator/src/insert.rs, src/operator/src/metrics.rs
1. Do not spawn to check `source table` since there already has cache for this.
2. Avoid to cloning all requests to mirror.
=> feat: avoid some cloning when mirror requests to flownode

.github/workflows/develop.yml
fuzz test are build in-place and will sometimes out of space: https://github.com/GreptimeTeam/greptimedb/actions/runs/9299629767/job/25594353223
=> ci: cargo gc fuzz test runner

src/common/function/src/scalars/math/clamp.rs, src/common/meta/src/key/datanode_table.rs, src/common/meta/src/key/flow/flownode_flow.rs, src/common/meta/src/key/flow/table_flow.rs, src/common/meta/src/key/table_name.rs, tests/cases/standalone/common/information_schema/tables.result, tests/cases/standalone/common/information_schema/tables.sql
add tailing separator to prefix, otherwise it cannot handle when one schema name is a substring of another.
=> fix: add tailing separator to prefix

src/mito2/src/error.rs, src/mito2/src/test_util.rs, src/mito2/src/test_util/wal_util.rs, src/mito2/src/wal.rs, src/mito2/src/wal/entry_distributor.rs, src/mito2/src/wal/entry_reader.rs
#4026 
1. Implement the `WalEntryDistributor`, which reads and raw WAL entries from the topic and distributes them to `WalEntryReceiver` based on RegionId and `start_id`.
2. Implement the `WalEntryReceiver,` which receives raw WAL entries from the `WalEntryDistributor,` and decodes raw WAL entries into upper-level WAL entries.
~~wait for #4038~~
=> feat: implement `WalEntryDistributor`, `WalEntryReciver`

Cargo.lock, Cargo.toml, src/common/meta/src/ddl_manager.rs, src/common/meta/src/rpc/ddl.rs, src/operator/src/statement/ddl.rs
As the title said, we do not need `table id` any more, `table ids` is enough, the PR of proto is: https://github.com/GreptimeTeam/greptime-proto/pull/175
=> refactor!: remove the tableid in ddl response since tableids is enough

src/flow/src/adapter.rs, src/flow/src/adapter/flownode_impl.rs, src/flow/src/adapter/node_context.rs
make flow's insert request faster to handle
Previously everytime a insert request comes in a exclusive lock on flow node's ctx is acquired, which is unnecessary, hence now it will only acquire a shared read lock, and send rows into flow node
=> feat(flow): make write path faster with shared lock

src/client/src/client.rs, src/client/src/error.rs, src/client/src/region.rs, src/datanode/src/event_listener.rs, src/file-engine/src/engine.rs, src/flow/src/adapter/worker.rs, src/index/src/inverted_index/create/sort/external_sort.rs, src/operator/src/insert.rs, src/servers/src/export_metrics.rs
Change all `error!` usage without debug formatter on `Error`.
=> fix: display error in correct format

src/partition/src/expr.rs
=> feat: implement `Display` for `PartitionExpr`

.github/workflows/develop.yml, Cargo.toml
=> ci: try to free space after fuzz tests

Cargo.toml
enable `strip` for tests-fuzz crate
=> chore: enable `strip` for tests-fuzz crate

Cargo.lock, src/common/error/Cargo.toml, src/common/error/src/status_code.rs, src/datanode/src/error.rs, src/flow/src/adapter/error.rs, src/frontend/src/error.rs, src/meta-srv/src/error.rs, src/operator/Cargo.toml, src/operator/src/error.rs, src/pipeline/src/lib.rs, src/servers/src/error.rs
As title suggests. This enables us to remove `servers` from `operator`'s dep list.
=> refactor: move `define_into_tonic_status` to `common-error`

Cargo.lock, Cargo.toml, src/log-store/src/test_util/log_store_util.rs, src/mito2/Cargo.toml, src/mito2/src/engine/basic_test.rs, src/mito2/src/engine/flush_test.rs, src/mito2/src/test_util.rs, tests-integration/Cargo.toml, tests-integration/src/lib.rs
Run `test_flush_reopen_region` and `test_region_replay` with `KafkaLogStore`
Prelude of #4075
=> test: run `test_flush_reopen_region` and `test_region_replay` with `KafkaLogStore`

src/metric-engine/src/engine/create.rs, src/metric-engine/src/engine/open.rs, src/metric-engine/src/engine/options.rs
During creating physical regions for metric engine, index and memtable options are set manually:
https://github.com/GreptimeTeam/greptimedb/blob/df01ac05a1ec5f7c3c4630eca7b58e8f0b39f8fe/src/metric-engine/src/engine/create.rs#L482-L485
But when open physical regions, only index options are set:
https://github.com/GreptimeTeam/greptimedb/blob/d1838fb28de054c5f4c82ea07683f28acd4871db/src/metric-engine/src/engine/open.rs#L83
=> fix: recover memtable options when opening physical regions

src/flow/src/adapter.rs, src/flow/src/compute/render/map.rs, src/flow/src/repr.rs, src/flow/src/utils.rs
fix a bug that mfp operator will missing rows if run multiple tims in same tick
- fix a bug that mfp operator will missing rows if run multiple tims in same tick
- add related tests
=> fix(flow): mfp operator missing rows

.github/actions/setup-greptimedb-cluster/action.yml, .github/actions/setup-greptimedb-cluster/values.yaml, Cargo.lock, config/config.md, config/datanode.example.toml, config/frontend.example.toml, config/metasrv.example.toml, config/standalone.example.toml, src/cmd/src/datanode.rs, src/cmd/src/frontend.rs, src/cmd/src/metasrv.rs, src/cmd/src/options.rs, src/cmd/src/standalone.rs, src/cmd/tests/load_config_test.rs, src/common/config/src/config.rs, src/common/runtime/Cargo.toml, src/common/runtime/src/global.rs, src/common/runtime/src/lib.rs, src/common/test-util/Cargo.toml, src/common/test-util/src/recordbatch.rs, src/datanode/src/config.rs, src/frontend/src/frontend.rs, src/frontend/src/instance.rs, src/frontend/src/server.rs, src/frontend/src/service_config/datanode.rs, src/meta-srv/src/metasrv.rs, tests-integration/src/test_util.rs, tests-integration/tests/grpc.rs
Originally the size of all global runtimes are hardcoded to 8, which is not flexible enough. For example, edit region requests are executed in the global background runtime. Our customer may emit a large volume of that requests, expecting them to be ran fast, only to find the runtime is saturated.
This PR makes the size of global runtimes configurable, by env var. The reason I choose env var instead of config file entries is because the parameters are not related to any kinds of greptimedb components. Whether it's standalone, frontend or datanode, doesn't matter, all need these parameters. So I don't want to set it in config files. Besides, env vars are good in cloud env, …
=> feat: set global runtime size by config file

src/frontend/src/instance.rs, src/operator/src/statement.rs, src/operator/src/statement/ddl.rs, src/sql/src/parsers/drop_parser.rs, src/sql/src/statements/drop.rs, tests/cases/standalone/common/drop/drop_table.result, tests/cases/standalone/common/drop/drop_table.sql
close #4020 
Implemet dropping multiple tables in the single statement.
If any tables do not exist without IF EXISTS, the statement fails with an error and don`t make any change, referencing MySQL.
It works for SQL requests, not ready for gRPC.
=> feat: implement drop multiple tables

src/operator/src/error.rs, src/operator/src/statement.rs, src/operator/src/statement/show.rs, tests/cases/standalone/common/show/show_create.result, tests/cases/standalone/common/show/show_create.sql
This closes #3980.
Display:
```
$ curl -i -XPOST -H 'Content-Type: application/x-www-form-urlencoded' -d 'sql=SHOW CREATE TABLE numbers' http://localhost:4000/v1/sql
HTTP/1.1 400 Bad Request
Content-Length: 121
Connection: keep-alive
Content-Type: application/json
Date: Mon, 03 Jun 2024 15:04:04 GMT
Keep-Alive: timeout=4
Proxy-Connection: keep-alive
X-Greptime-Err-Code: 1001
X-Greptime-Execution-Time: 0
{"code":1001,"error":"Show create table only for base table. greptime.public.numbers is TEMPORARY","execution_time_ms":0}
```
and
```
mysql> SHOW CREATE TABLE information_schema.columns;
ERROR 1815 (HY000): Show create table only for base table. greptime.information_schema.columns …
```
=> feat: show create table only for base table

Makefile, docker/docker-compose/cluster-with-etcd.yaml
Add `make run-cluster-with-etcd` to run greptimedb cluster by using docker-compose.
=> ci: add 'make run-cluster-with-etcd' to run greptimedb cluster by using docker-compose

src/mito2/src/engine.rs, src/mito2/src/engine/batch_open_test.rs, src/mito2/src/region/opener.rs, src/mito2/src/request.rs, src/mito2/src/test_util.rs, src/mito2/src/wal.rs, src/mito2/src/wal/entry_distributor.rs, src/mito2/src/wal/entry_reader.rs, src/mito2/src/worker.rs, src/mito2/src/worker/handle_catchup.rs, src/mito2/src/worker/handle_open.rs, src/store-api/Cargo.toml, src/store-api/src/region_engine.rs
#4026
1. Add the `handle_batch_open_requests ` method for the `RegionEngine` trait
2. Implement the `handle_batch_open_requests` method for `mito`. It tries to group opening regions by topic and then open regions with the same topic in a batch.
=> feat: implement the `handle_batch_open_requests`

src/pipeline/src/etl/README.md, src/pipeline/src/etl/field.rs, src/pipeline/src/etl/mod.rs, src/pipeline/src/etl/processor/cmcd.rs, src/pipeline/src/etl/processor/csv.rs, src/pipeline/src/etl/processor/date.rs, src/pipeline/src/etl/processor/dissect.rs, src/pipeline/src/etl/processor/epoch.rs, src/pipeline/src/etl/processor/letter.rs, src/pipeline/src/etl/processor/mod.rs, src/pipeline/src/etl/processor/regex.rs, src/pipeline/src/etl/processor/urlencoding.rs, src/pipeline/src/etl/transform/index.rs, src/pipeline/src/etl/transform/mod.rs, src/pipeline/src/etl/transform/transformer/greptime/coerce.rs, src/pipeline/src/etl/transform/transformer/greptime/mod.rs, src/pipeline/src/etl/transform/transformer/mod.rs, src/pipeline/src/etl/transform/transformer/noop.rs, src/pipeline/src/etl/value/array.rs, src/pipeline/src/etl/value/map.rs, src/pipeline/src/etl/value/mod.rs, src/pipeline/src/etl/value/time.rs, src/pipeline/tests/pipeline.rs, typos.toml
This is a pre-pr for https://github.com/GreptimeTeam/greptimedb/pull/4014 to introduce https://github.com/GreptimeTeam/pipeline into `src/pipeline/src/etl`. The code is not referred anywhere now.
=> feat: introduce `pipeline` crate

Cargo.lock, src/cmd/src/standalone.rs, src/frontend/src/server.rs, src/servers/Cargo.toml, src/servers/src/grpc.rs, src/servers/src/grpc/cancellation.rs, src/servers/src/grpc/database.rs, src/servers/src/grpc/greptime_handler.rs, src/servers/src/grpc/region_server.rs, src/servers/tests/grpc/mod.rs, tests-integration/src/test_util.rs
This PR enables gRPC server cancellation support in `RegionServer` and `GreptimeService`.
Closes #3964
=> feat: support gRPC cancellation

Cargo.lock, src/common/function/src/system/procedure_state.rs, src/common/function/src/table/flush_compact_region.rs, src/common/function/src/table/flush_compact_table.rs, src/common/function/src/table/migrate_region.rs, src/common/macro/Cargo.toml, src/common/macro/src/admin_fn.rs, src/common/macro/src/print_caller.rs, src/common/macro/src/range_fn.rs, src/common/macro/src/stack_trace_debug.rs, src/common/macro/src/utils.rs, src/promql/src/functions/aggr_over_time.rs, src/promql/src/functions/changes.rs, src/promql/src/functions/deriv.rs, src/promql/src/functions/resets.rs
This patch fixes an issue that I came across while working on other modules sit in common. Our `macro` module cannot compile by itself.
```
src/common/macro on  main [$] is 📦 v0.8.1 via 🦀 v1.79.0-nightly 
❯ cargo check
Blocking waiting for file lock on build directory
Checking syn v1.0.109
Checking common-macro v0.8.1 (/home/sunng/greptime/greptimedb/src/common/macro)
error[E0432]: unresolved imports `syn::ItemFn`, `syn::Signature`
--> src/common/macro/src/admin_fn.rs:19:57
|
19  |     parse_macro_input, Attribute, AttributeArgs, Ident, ItemFn, Signature, Type, TypePath,
|                                                         ^^^^^^  ^^^^^^^^^ no `Signature` in the root
| …
```
=> fix: macro crate cannot be compiled alone

src/flow/src/adapter.rs, src/flow/src/adapter/flownode_impl.rs, src/flow/src/adapter/node_context.rs, src/flow/src/adapter/table_source.rs, src/flow/src/adapter/worker.rs, src/flow/src/compute/render.rs, src/flow/src/compute/render/map.rs, src/flow/src/compute/render/reduce.rs, src/flow/src/compute/render/src_sink.rs, src/flow/src/expr/linear.rs, src/flow/src/plan.rs, src/flow/src/repr/relation.rs, src/flow/src/transform.rs, src/flow/src/transform/aggr.rs, src/flow/src/transform/expr.rs, src/flow/src/transform/literal.rs, src/flow/src/transform/plan.rs
- fix infer table schema for flow
previously, flow can't correctly infer pk&time index for query with `GROUP BY`& `tumble`, now function to infer those &related tests are added
=> fix(flow): infer table schema correctly
