- src/cmd/tests/load_config_test.rs
fix #4126 
fix the test failure in #4126
> fix: explicitly set config instead of using changable default in tests

- src/mito2/src/wal.rs
- src/mito2/src/wal/entry_distributor.rs
- src/mito2/src/wal/entry_reader.rs
- src/mito2/src/wal/raw_entry_reader.rs
Clean up TODO comments and remove unused code
> chore: remove unused code

- src/common/datasource/src/file_format/parquet.rs
- src/mito2/src/access_layer.rs
- src/mito2/src/cache/write_cache.rs
- src/mito2/src/error.rs
- src/mito2/src/sst/parquet.rs
- src/mito2/src/sst/parquet/format.rs
- src/mito2/src/sst/parquet/writer.rs
- src/operator/src/statement/copy_table_to.rs
This PR simplifies SST writing process by removing the `BufferedWriter`.
The `BufferedWriter` came to solve the problem that arrow's paruqet writer requires `std::io::Write` while opendal only provides async S3 writer that implements `tokio::io::AsyncWrite`.  Now arrow provides `AsyncArrowWriter` so we can remove those structs.
Writing an parquet file with size 1.2GB,
- before: 11143163us
- after: 10507815us
A slight improvement of 6%.
> refactor: simplify parquet writer

- src/client/src/error.rs
It should retry on unknown error (e.g. incurring transport error)
```
2024-06-10T05:01:57.684978Z ERROR LocalManager::submit_root_procedure: common_procedure::local::runner: Failed to execute procedure metasrv-procedure::DropTable-4d04bd3d-3a0f-495c-819d-80b939475fa4, retry: false err=0: Failed to execute procedure due to external error
2024-06-10 13:01:57.685	
1: Failed to operate on datanode: peer-2(greptimedb-datanode-2.greptimedb-datanode.greptimedb:4001), at greptimedb/src/common/meta/src/ddl/utils.rs:33:27
2024-06-10 13:01:57.685	
2: External error, at greptimedb/src/client/src/region.rs:59:31
2024-06-10 13:01:57.685	
3: Failed to request RegionServer …
```
> fix: retry on unknown error

- Cargo.lock
- Cargo.toml
> chore: bump version to v0.8.2

- .github/actions/build-macos-artifacts/action.yml
https://github.com/rust-lang/rust/issues/113783
The PR use `ld_classic` on macOS when releasing macOS artifact.
The latest macOS CI runner image(https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240611.1), its default linker can't get the backtraces properly, which will lead release failed.
```
thread 'selector::weighted_choose::tests::test_random_reverse_weighted_choose_should_panic' panicked at src/meta-srv/src/selector/weighted_choose.rs:173:41:
called `Result::unwrap()` on an `Err` value: 0: Failed to set weight array, at src/meta-srv/src/selector/weighted_choose.rs:87:18
1: NoItem
note: run with `RUST_BACKTRACE=1` environment variable to display a …
```
> fix(ci): use `ld_classic` on macOS

- tests/cases/distributed/information_schema/cluster_info.result
- tests/cases/distributed/information_schema/cluster_info.sql
close #4148
This PR tries to catch different format timestamps in the sqlness case(introduced in #3832); The format of output timestamps may behave inconsistently on different platforms. (e.g., `20240615T04:24:18`, `2024-04-30T06:40:02.074`)
> fix(sqlness): catch different format timestamp

- Cargo.lock
- src/mito2/Cargo.toml
- src/mito2/src/manifest.rs
- src/mito2/src/manifest/checkpointer.rs
- src/mito2/src/manifest/manager.rs
- src/mito2/src/manifest/storage.rs
- src/mito2/src/manifest/tests/checkpoint.rs
Region manifest checkpoint currently requires many object store reads and writes. The checkpoint is performed synchronously in the region manifest update. When the object store is slow, it could easily cause the region manifest update method executes too long. This PR makes the checkpoint ran in the background (performed asynchronously) to solve the problem.
This PR also makes some changes to how the checkpoint is done. Originally the current checkpoint is the last checkpoint merged with all the incremental files. This process has to scan the object store. However, since the checkpoint is actually a snapshot of the current region manifest, which is already present in the memory, …
> refactor: make region manifest checkpoint ran in background

- src/mito2/src/read.rs
- src/mito2/src/read/dedup.rs
- src/mito2/src/read/merge.rs
- src/mito2/src/read/seq_scan.rs
This PR refactors the MergeReader and introduces a new reader `DedupReader`
- The `MergeReader` only merges sorted batches but doesn't dedup rows
- The `DedupReader` fetches batches from the `MergeReader` and dedup them
- The `DedupReader` uses the `DedupStrategy` to perform the actual deduplication
- The default strategy is `LastRow`, which keeps the row with the latest sequence for each key
- We could implement other dedup strategies later
- Removes the `put_only` hint from the `Batch` as it is unused and easy to introduce bugs.
> refactor: Decouple dedup and merge

- src/pipeline/src/etl/processor/gsub.rs
- src/pipeline/src/etl/processor/join.rs
- src/pipeline/src/etl/processor/mod.rs
- src/pipeline/tests/common.rs
- src/pipeline/tests/gsub.rs
- src/pipeline/tests/join.rs
- src/pipeline/tests/on_failure.rs
Porting https://github.com/GreptimeTeam/pipeline/pull/44
Implement [join processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/join-processor.html)
>  feat(pipeline): join processor

- config/config.md
- config/datanode.example.toml
- config/frontend.example.toml
- config/metasrv.example.toml
- config/standalone.example.toml
- src/cmd/tests/load_config_test.rs
- src/common/runtime/src/global.rs
- src/common/runtime/src/lib.rs
- src/datanode/src/heartbeat.rs
- src/frontend/src/heartbeat.rs
#4128 
This patch changes default bg_worker runtime to half of cpu_num, to avoid cpu-intensive tasks to fill up all compute resources
It also use dedicated runtime to host heartbeat tasks, which is of higher priority.
> feat: update default size of bgworkers, add hbworkers

- Cargo.lock
- src/flow/Cargo.toml
- src/flow/src/adapter.rs
- src/flow/src/adapter/node_context.rs
- src/flow/src/expr.rs
- src/flow/src/expr/error.rs
- src/flow/src/expr/func.rs
- src/flow/src/expr/scalar.rs
- src/flow/src/repr/relation.rs
- src/flow/src/transform.rs
- src/flow/src/transform/aggr.rs
- src/flow/src/transform/expr.rs
- src/flow/src/transform/plan.rs
- src/flow/src/utils.rs
support datafusion scalar function
support datafusion scalar function by let datafusion decode substrait proto, and hence build df `PhysicalExpr` to evaluate function
- added `DfScalarFunction` which hold both impl of that scalar function and necessary data to ser/de it
- added path in transform module to translate scalar function to df scalar function when no other functions are available
> feat(flow): support datafusion scalar function

- src/mito2/src/memtable.rs
- src/mito2/src/memtable/partition_tree.rs
- src/mito2/src/memtable/time_series.rs
- src/mito2/src/read/scan_region.rs
- src/mito2/src/read/seq_scan.rs
- src/mito2/src/read/unordered_scan.rs
- src/mito2/src/sst/parquet.rs
- src/mito2/src/sst/parquet/file_range.rs
- src/mito2/src/test_util/memtable_util.rs
- src/table/src/predicate.rs
- tests/cases/distributed/explain/analyze.result
- tests/cases/standalone/common/range/nest.result
- tests/cases/standalone/common/tql-explain-analyze/analyze.result
This PR implements `MemtableRange` to represent a partition (range) of a memtable. This allows iterating the memtable concurrently. The memtable range keeps an `IterBuilder` to build an iterator to read that range.
The `Memtable` trait has a new method `ranges()` to return the list of ranges to read. Both `time_series` and `partition_tree` memtables return just 1 range.
The `ScanPart` now keeps a list of `MemtableRange` instead of `Memtable`.
It also refactors the `FileRange` and extracts a struct `RangeBase` so we can reuse it in other places. The `RangeBase` contains fields to prune batches from a file.
> feat: Implement memtable range

- src/frontend/src/instance/log_handler.rs
- src/pipeline/src/manager/pipeline_operator.rs
- src/pipeline/src/manager/table.rs
- src/servers/src/http/event.rs
- src/servers/src/query_handler.rs
Making "add pipeline" http API return more info about added pipeline.
> chore: enhance add pipeline http api return data

- Cargo.lock
- tests-fuzz/Cargo.toml
- tests-fuzz/src/utils.rs
- tests-fuzz/src/utils/crd.rs
- tests-fuzz/src/utils/crd/common.rs
- tests-fuzz/src/utils/crd/pod.rs
Introduce the chaos-mesh CRDs (Custom Resource Definition) for e2e fuzz tests
> feat: introduce chaos crds

- src/mito2/src/compaction/compactor.rs
- src/mito2/src/compaction/test_util.rs
- src/mito2/src/flush.rs
- src/mito2/src/manifest/tests/checkpoint.rs
- src/mito2/src/sst/file.rs
- src/mito2/src/sst/file_purger.rs
- src/mito2/src/sst/parquet.rs
- src/mito2/src/sst/parquet/writer.rs
- src/mito2/src/test_util/sst_util.rs
- src/mito2/src/test_util/version_util.rs
Add `num_rows` and `num_row_groups` to mito manifest.
> feat: add num_rows and num_row_groups to manifest

- src/datanode/src/region_server.rs
- src/metric-engine/src/engine/catchup.rs
- src/metric-engine/src/engine/open.rs
- tests-integration/tests/region_migration.rs
This PR registers metric logical regions after invoking catchup and fixes metric logical regions not found issues after migrating a physical region.
After replaying the WAL of a metric metadata region, there are two places required to register logical regions manually:
- Metric engine
- RegionServer
> fix: region logical regions after catching up

- .github/actions/release-cn-artifacts/action.yaml
- .github/workflows/nightly-build.yml
Since we use a new namespace for the nightly build image(not the scheduled released version), we can push the latest tag for those images.
Also, it resolves the issue of failing to push nightly images to ACR.
> ci: push latest greptimedb nigthly build image

- Cargo.lock
- src/index/Cargo.toml
- src/index/src/inverted_index.rs
- src/index/src/inverted_index/format/reader/cache.rs
- src/mito2/src/cache.rs
- src/mito2/src/sst/index/applier.rs
- src/mito2/src/sst/index/creator.rs
- Added puffin as a dependency.
- Modified the `InvertedIndexCache` to include a cache for puffin metadata.
- Updated functions to handle the new puffin metadata cache, including adjustments to the `InvertedIndexCache` struct and related methods.
- Adjusted the `SstIndexApplier` and other related components to utilize the new puffin metadata cache.
> feat(index): add puffin metadata cache

- Cargo.lock
OpenDAL 0.47.2 fixes a critical bug, Gcs's RangeWrite doesn't support concurrent write 🥲
See also: 
fix(core): Gcs's RangeWrite doesn't support concurrent write  in https://github.com/apache/opendal/pull/4806
feat(core/gcs): Add concurrent write for gcs back in https://github.com/apache/opendal/pull/4820
> chore: bump OpenDAL to 0.47.2

- src/cmd/src/datanode.rs
- src/cmd/src/frontend.rs
- src/cmd/src/metasrv.rs
- src/cmd/src/standalone.rs
- src/plugins/src/datanode.rs
- src/plugins/src/frontend.rs
- src/plugins/src/meta_srv.rs
**NOTE**: The PR will **break** the `setup_<role>_plugins()` API.
1. Add the `&mut Plugins` argument in the plugins setup API instead of creating `Plugins` inside since we need to add frontend and datanode plugins in standalone mode in one `Plugins`;
2. Remove unnecessary `mut` for `*Options`
I think it's not a good practice to implicitly modify the `*Options` in the plugin setup API. We can modify the `*Options` from layered configuration, for example, environment variables, config file, etc;
> refactor: add `&mut Plugins` argument in plugins setup api and remove unnecessary mut

- src/cmd/src/frontend.rs
- src/cmd/src/standalone.rs
User provider can't be configured by config file or environment variables because it always use cli options.
> fix: user provider can't be configured by config file or environment variables

- src/mito2/src/memtable/bulk/part.rs
- src/mito2/src/sst.rs
- src/mito2/src/sst/parquet/format.rs
This PR changes the dictionary key type to u32. Our default row group size is 100K so it is possible that the key type isn't large enough.
> fix: dictionary key type use u32

- src/mito2/src/worker/handle_drop.rs
This PR handles WAL deletion when dropping regions.
> fix(wal): handle WAL deletion on region drop

- src/auth/src/error.rs
#4359 
`AuthBackend` error is designed to represent errors from authentication data source. It's deleted in #4359 . This patch brings it back and updated its message
> fix: add back AuthBackend which is required by custom auth backend

- src/servers/src/http/event.rs
- src/servers/src/metrics.rs
This pr mainly adds three metrics for monitoring log ingestion
- ingestion elapsed
- ingestion counter
- transform (pipeline engine execution) elapsed
> chore: add metrics for log ingestion

- src/mito2/src/sst/index.rs
- src/mito2/src/sst/index/fulltext_index/creator.rs
Metric `greptime_index_create_elapsed_bucket` reports non-zero values even though no index needs to be built.
This patch fixes it.
> fix(fulltext-index): clean up 0-value timer

- Cargo.toml
- src/cmd/Cargo.toml
- src/frontend/src/error.rs
- src/frontend/src/script.rs
add a "python" flag in `cmd` package so can turn off `python` feature when building `greptime` binary
i.e. `cargo build --release --bin greptime --no-default-feature`, note the `--no-default-feature` which turn off default features which in turn turn off `python` featue, since the only default features in `cmd` is `python`
LIMITATION: user who want to turn off `python` features might need to also figure out is there any features they want to keep because they need to pass `--no-default-features` first to turn off all default features
> chore: add a compile cfg for python in cmd package

- config/config.md
- config/metasrv.example.toml
Add docs for `config/metasrv.example.toml`
> chore: add docs for config file

- src/datanode/src/store.rs
As the [issue](https://github.com/apache/opendal/issues/4918) mentions, we want to print detailed messages when an error occurs to help us troubleshoot.
The PR adds the `PrintDetailedError`, which implements `RetryInterceptor` to print `Error` in `Debug` format in retrying.
@evenyag Do we need a configuration to control whether we add the `RetryInterceptor`?
> refactor: add RetryInterceptor to print detailed error

- src/catalog/src/system_schema/information_schema/tables.rs
- src/catalog/src/system_schema/information_schema/views.rs
- tests/cases/standalone/common/show/show_databases_tables.result
- tests/cases/standalone/common/system/information_schema.result
- tests/cases/standalone/common/view/create.result
Fixed some wrong values in `information_schema.views` and `information_schema.tables`:
* The `is_is_updatable` in `views` should be `NO`.
* The `table_collation` in `tables` should be `utf8_bin`.
> fix: information_schema tables and views column value

- src/datanode/src/alive_keeper.rs
use heartbeat runtime instead of background runtime
> fix: use heartbeat runtime instead of background runtime

- src/common/error/src/ext.rs
- src/servers/src/grpc/greptime_handler.rs
- src/servers/src/http.rs
- src/servers/src/mysql/handler.rs
- src/servers/src/mysql/writer.rs
- src/servers/src/postgres/handler.rs
Display root error information on the error log line, for better log tools integration. For error log like:
```
2024-07-27T03:38:18.634686Z ERROR on_query{protocol="mysql"}: servers::mysql::writer: Failed to handle mysql query, code: Internal, kind: ER_INTERNAL_ERROR err=0: , at greptimedb/src/common/recordbatch/src/adapter.rs:258:55
```
We need to root cause information in this line.
> feat: show root cause and db name on the error line

- src/mito2/src/sst/parquet/reader.rs
- src/mito2/src/sst/parquet/row_selection.rs
Forgot to take the remainder before passing row ids to `prune_row_groups_by_rows`. Fixed it on this patch.
> fix(fulltext-search): prune rows in row group forget to take remainder

- config/config.md
- config/frontend.example.toml
- src/cmd/src/frontend.rs
- src/cmd/src/standalone.rs
- src/frontend/src/frontend.rs
- src/frontend/src/server.rs
Resolve https://github.com/GreptimeTeam/greptimedb/issues/4399.
Remove `Mode` from `FrontendOptions` and determine whether it is Standalone or Distributed mode based on whether the Meta Client is configured.
> refactor!: Remove `Mode` from `FrontendOptions`

- .github/workflows/develop.yml
The new version GreptimeDB operator introduces a check for enabling region failover, which requires passing a value to the `remoteWal` field. However, the current helm chart doesn't allow passing the value to the `remoteWal` field. Therefore, we temporarily disable fuzz chaos tests.
> chore: temporarily disable fuzz chaos tests

- grafana/greptimedb.json
- src/servers/src/http/prometheus.rs
- src/servers/src/metrics.rs
- Add metrics to Prometheus-compatible query endpoints. Those need no computation are ignored.
- Update grafana dashboard correspondingly
> feat: track prometheus HTTP API's query latency 

- src/servers/src/error.rs
- src/servers/src/http/error_result.rs
This pr extracts the greptimedb status code to HTTP status mapping in `impl IntoResponse for ErrorResponse` and reuses it in `impl IntoResponse for Error` so that HTTP handler returning `Result` now shows the correct HTTP status code and msg.
> fix: use status code to http status mapping in error IntoResponse

- src/common/query/src/logical_plan.rs
- src/common/query/src/logical_plan/expr.rs
- src/common/recordbatch/src/adapter.rs
- src/common/recordbatch/src/error.rs
- src/common/recordbatch/src/filter.rs
- src/operator/src/error.rs
- src/operator/src/statement/copy_table_from.rs
- tests/cases/standalone/common/copy/copy_from_fs_csv.result
- tests/cases/standalone/common/copy/copy_from_fs_csv.sql
- tests/cases/standalone/common/copy/copy_from_fs_json.result
- tests/cases/standalone/common/copy/copy_from_fs_json.sql
- tests/cases/standalone/common/copy/copy_from_fs_parquet.result
- tests/cases/standalone/common/copy/copy_from_fs_parquet.sql
Resolve #3511 
Reuse the time range specified in the WITH clause and ensure the data can be filtered based on the 'ts' column.  Hence, `Copy table x from datasource with (start_time='2022-06-15 07:02:37', end_time='2022-06-15 07:02:38');` statement should work properly.
All work based [filter_record_batch](https://docs.rs/datafusion/latest/datafusion/common/arrow/compute/fn.filter_record_batch.html) in file:https://github.com/GreptimeTeam/greptimedb/blob/2ae2a6674e8a780cb93723de …
> feat: support setting time range in Copy From statement

- .github/actions/build-macos-artifacts/action.yml
- .github/actions/build-windows-artifacts/action.yml
- .github/workflows/nightly-ci.yml
- Makefile
The release pipeline runs `make sqlness-test` so it doesn't keep the sqlness log. This PR changes to keep the log by default.
> ci: keep sqlness log by default

- src/query/src/dist_plan/commutativity.rs
- tests/cases/standalone/common/aggregate/multi_regions.result
- tests/cases/standalone/common/aggregate/multi_regions.sql
Comparing qualified and unqualified columns will give incorrect results.
> fix: check_partition uses unqualified name

- src/cmd/src/cli/export.rs
- src/cmd/src/error.rs
Default catalog name to `greptime`
> feat: default export catalog name

- src/mito2/src/read.rs
- src/mito2/src/read/scan_region.rs
- src/mito2/src/read/seq_scan.rs
- src/mito2/src/read/unordered_scan.rs
- src/query/src/dist_plan/merge_scan.rs
- tests/cases/distributed/explain/analyze.result
- tests/cases/distributed/explain/analyze.sql
- tests/cases/standalone/common/aggregate/multi_regions.result
- tests/cases/standalone/common/aggregate/multi_regions.sql
- tests/cases/standalone/common/range/nest.result
- tests/cases/standalone/common/range/nest.sql
- tests/cases/standalone/common/tql-explain-analyze/analyze.result
- tests/cases/standalone/common/tql-explain-analyze/analyze.sql
- tests/cases/standalone/optimizer/last_value.result
- tests/cases/standalone/optimizer/last_value.sql
This PR reduces the parts lock scope. This prevents different streams from blocking each other for too long. Under append mode, this lock prevents part parallelism.
It also improves the scan log.
> perf: reduce lock scope and improve log

- src/servers/src/postgres/auth_handler.rs
- src/servers/src/postgres/handler.rs
- src/servers/src/postgres/types.rs
- src/servers/src/postgres/types/error.rs
https://github.com/GreptimeTeam/greptimedb/issues/4340
- Define enum `PgErrorCode` struct for pgwire.
- Impl `from` trait for mapping `StatusCode` to `PgErrorCode`.
- Impl `to_err_info` to trans PgErrorCode to ErrorInfo.
- Use enum `PgErrorCode` intead of `ErrorInfo::new()`. 
before:
```rust
match output {
Ok(o) => todo!(),
Err(e) => Ok(Response::Error(Box::new(ErrorInfo::new(
"ERROR".to_string(),
"XX000".to_string(),
e.output_msg(),
))))
}
```
after:
```rust
match output {
Ok(o) => todo!(),
Err(e) => Ok(Response::Error(Box::new(
PgErrorCode::from(e.status_code()).to_err_info(e.output_msg())
)))
}
```
> refactor(servers): improve postgres error message

- CONTRIBUTING.md
https://github.com/GreptimeTeam/greptimedb/issues/4467
As title, replace expired links in CONTRIBUTING.md file.
> docs(contributing): replace expired links

- Cargo.lock
- Cargo.toml
- src/common/meta/src/rpc/ddl.rs
- src/operator/src/insert.rs
- src/query/src/dist_plan/merge_scan.rs
- src/servers/src/grpc/authorize.rs
- src/servers/src/grpc/otlp.rs
- src/servers/src/http/authorize.rs
- src/servers/src/http/event.rs
- src/servers/src/http/handler.rs
- src/servers/src/http/influxdb.rs
- src/servers/src/http/opentsdb.rs
- src/servers/src/http/otlp.rs
- src/servers/src/http/prom_store.rs
- src/servers/src/http/prometheus.rs
- src/servers/tests/http/authorize.rs
- src/servers/tests/http/http_handler_test.rs
- src/session/Cargo.toml
- src/session/src/context.rs
- src/session/src/lib.rs
- src/sql/src/dialect.rs
This patch adds a new field `channel` in query context so the execution path now knows which source the query comes from. It also add this channel to meter, by which we can add statistics for w/rcus of each channel.
Upstream changes that has to be merged before this:
- https://github.com/GreptimeTeam/greptime-proto/pull/183
- https://github.com/GreptimeTeam/greptime-meter/pull/24
**Note that** this patch changes QueryContext extension type in axum, from `QueryContextRef` to plain `QueryContext` so that we can modify it in http handlers, to set `channel` field based on different handler.
> feat: track channels with query context and w/rcu

- src/sql/src/statements.rs
- tests/cases/standalone/common/create/create.result
- tests/cases/standalone/common/create/create.sql
#4351
Fixed overflow when parsing default constraints with negative numbers.
Close #4351
> fix: overflow when parsing default value with negative numbers

- src/servers/src/error.rs
- src/servers/src/grpc/prom_query_gateway.rs
- src/servers/src/http/error_result.rs
- src/servers/src/http/prometheus.rs
- src/servers/src/http/prometheus_resp.rs
- tests-integration/tests/grpc.rs
- tests-integration/tests/http.rs
This pr mainly fixes the case where prometheus api returns 200 even if an error is encountered.
Note: `Invalid argument` is now `InvalidArguments`.
> fix: prometheus api only returns 200

- tests-fuzz/targets/fuzz_insert.rs
- tests-fuzz/targets/fuzz_insert_logical_table.rs
fix #4388
Generate unique timestamp for inserting tests
> fix: generate unique timestamp for inserting tests

- src/client/src/database.rs
- src/client/src/error.rs
- src/operator/src/insert.rs
- src/servers/src/grpc/database.rs
- src/servers/src/grpc/flight.rs
- src/servers/src/grpc/greptime_handler.rs
- src/servers/src/grpc/prom_query_gateway.rs
- tests-integration/tests/grpc.rs
This PR closes #4441 
For example, if you need to add a hint during the first write to automatically create a table with the option `merge_mode = "last_non_null"`, then we need to add a hint to the gRPC request header:
```
("x-greptime-hint-merge_mode", "last_non_null")
```
Note, you must use the prefix `x-greptime-hint-`; otherwise, it will not be parsed as a valid hint.
Taking the java ingester client as an example, we modify a line of code in this example to:
https://github.com/GreptimeTeam/greptimedb-ingester-java/blob/4fa729a537df3f49278aef58fa919315ad6a7f88/ingester-example/src/main/java/io/greptime/LowLevelApiWriteQuickStart.java#L76
```
CompletableFuture<Result<WriteOk, …
```
> feat: hint options for gRPC insert

- src/servers/src/grpc/database.rs
As the title said. 
Fixs: https://github.com/GreptimeTeam/greptimedb/pull/4454#discussion_r1699332373
> feat: improve extract hints

- src/cmd/src/cli/export.rs
1. export all schemas and data at once in export tool
2. remove `export table data` cmd, use `database data` instead.
> feat: export all schemas and data at once in export tool

- src/mito2/src/config.rs
https://github.com/GreptimeTeam/greptimedb/issues/4488
Enlarge default page cache size to 1/8 of host memory.
> feat: enlarge default page cache size

- src/sql/src/parsers/create_parser.rs
Queries like this cannot be parsed correctly before:
```sql
CREATE TABLE monitor (
`host_id`    INT,
idc        STRING,
ts         TIMESTAMP,
cpu        DOUBLE DEFAULT 0,
memory     DOUBLE,
TIME INDEX (ts),
PRIMARY KEY (host),
)
PARTITION ON COLUMNS(IdC, host_id) (
idc <= 'hz' AND host_id < 1000,
idc > 'hz' AND idc <= 'sh' AND host_id < 2000,
idc > 'sh' AND host_id < 3000,
idc > 'sh' AND host_id >= 3000,
)";
```
Because the quote style is also included in the equality comparison which is not correct and necessary.
> fix: partition column with mixed quoted and unquoted idents

- src/sql/src/parsers/error.rs
- src/sql/src/parsers/tql_parser.rs
Avoid `.unwrap()` and panic on invalid tql queries.
> fix(tql): avoid unwrap on parsing tql query 

- Cargo.lock
- src/common/datasource/src/object_store/fs.rs
- src/common/datasource/src/object_store/s3.rs
- src/common/datasource/src/test_util.rs
- src/common/procedure/src/local.rs
- src/common/procedure/src/store.rs
- src/common/procedure/src/store/state_store.rs
- src/datanode/src/store.rs
- src/datanode/src/store/azblob.rs
- src/datanode/src/store/fs.rs
- src/datanode/src/store/gcs.rs
- src/datanode/src/store/oss.rs
- src/datanode/src/store/s3.rs
- src/file-engine/src/test_util.rs
- src/metric-engine/src/test_util.rs
- src/mito2/src/access_layer.rs
- src/mito2/src/cache/file_cache.rs
- src/mito2/src/cache/test_util.rs
- src/mito2/src/manifest/storage.rs
- src/mito2/src/sst/file_purger.rs
- src/mito2/src/test_util.rs
- src/mito2/src/test_util/scheduler_util.rs
- src/object-store/Cargo.toml
- src/object-store/src/layers/lru_cache.rs
- src/object-store/src/layers/prometheus.rs
- src/object-store/src/manager.rs
- src/object-store/tests/object_store_test.rs
- src/operator/src/statement/copy_database.rs
- tests-integration/src/test_util.rs
> chore: bump opendal version to 0.48

- src/pipeline/tests/date.rs
- src/pipeline/tests/dissect.rs
- src/pipeline/tests/epoch.rs
- src/pipeline/tests/gsub.rs
- src/pipeline/tests/join.rs
- src/pipeline/tests/letter.rs
- src/pipeline/tests/regex.rs
- src/pipeline/tests/urlencoding.rs
This pr mainly adds more tests on pipeline processors in order to keep consistency with the incoming pipeline engine refactor.
tracking
The current `csv` impl is not a valid working one. We should re-implement it to match [csv processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/csv-processor.html). cc @paomian
> test: more on processors

- Cargo.lock
- Cargo.toml
- src/common/version/Cargo.toml
- src/common/version/build.rs
In our another project with "greptimedb" as its submodule, the git info fetched in building is wrong. This is because the git repo finding ends within the submodule, which should have been the outside repo that owns the submodule.
> chore: bump `shadow-rs` version to set the path to find the correct git repo

- Cargo.lock
- tests-integration/tests/sql.rs
fix #4503
- Bump `postgres-protocol` to `0.6.7`
- Bump `tokio-postgres` to `0.7.11`
- Bump `postgres-types` to `0.2.7`
The `tokio-postgres@0.7.11` introduced a breaking change, the `simple_query` method returns
`SimpleQueryMessage::RowDescription` before the `SimpleQueryMessage::Row`.
> chore: bump rust-postgres to 0.7.11

- src/common/version/build.rs
The change in https://github.com/GreptimeTeam/greptimedb/pull/4494 cause the final generated "shadow.rs" file too large(over 26MB). This PR cancels generating the two largest consts in that file, of which are no use to us. After this PR, the file is small(~14KB) again.
> fix: too large shadow-rs consts

- config/config.md
- config/datanode.example.toml
- config/flownode.example.toml
- config/frontend.example.toml
- config/metasrv.example.toml
- config/standalone.example.toml
- src/cmd/tests/load_config_test.rs
- src/common/telemetry/src/logging.rs
Set default `otlp_endpoint ` in example configuration files.
An empty 'otlp_endpoint' will cause a crash...
```
name = "GreptimeDB"
operating_system = "Ubuntu 23.10.0 (mantic) [64-bit]"
crate_version = "0.9.1"
explanation = """
Panic occurred in file 'src/common/telemetry/src/logging.rs' at line 255
"""
cause = "otlp tracer install failed: ExportFailed(InvalidUri(InvalidUri(InvalidFormat)))"
method = "Panic"
backtrace = """
0: 0x5997c1dc3b23 - <unresolved>
1: 0x5997c1dc4026 - <unresolved>
2: 0x5997c1d321cc - <unresolved>
3: 0x5997c1d62a8a - <unresolved>
4: 0x5997c471f8bd - <unresolved>
5: 0x5997c47b4de6 - <unresolved>
6: 0x5997c4775ef1 - <unresolved>
7: 0x5997c45d259e - …
```
> chore: set default `otlp_endpoint`

- .github/workflows/develop.yml
As title. The rust cache in our CI can be as large as 15GB:
While the disk space of runner "ubuntu-latest" is only 19GB. That could be too limited for our complex workflows like the fuzz tests for greptimedb-cluster. This PR removes some unused software to obtain more disk space for our complex fuzz tests.
It can totally remove 21GB data.
> ci: squeeze some disk space for complex fuzz tests

- .github/actions/build-windows-artifacts/action.yml
- .github/workflows/nightly-ci.yml
https://github.com/GreptimeTeam/greptimedb/issues/4514
Fix sqlness log path
According to https://github.com/GreptimeTeam/greptimedb/actions/runs/10257291884/job/28378064525
The log directory is under `C:\Users\RUNNER~1\AppData\Local\Temp`.
> ci: fix windows temp path

- scripts/install.sh
- fixes #4526
Fixes the issue that install script always selects `v0.9.0-nightly-20240709` instead of the latest nightly.
> fix: install script

- .github/workflows/develop.yml
- Cargo.lock
- src/client/src/flow.rs
- src/client/src/region.rs
- src/common/meta/src/ddl/utils.rs
- src/index/src/inverted_index/create/sort/intermediate_rw/codec_v1.rs
- src/script/src/python/pyo3/copr_impl.rs
In our another project which use greptimedb as a submodule, the snafu version is 0.8.4. However, the snafu version in greptimedb is 0.8.3. A [commit](https://github.com/shepmaster/snafu/commit/298b3c320c9b8aeb4521289651e74cc455c3d3d2) in snafu in between the two versions makes clippy runs fail in that project. So this PR updates the snafu in greptimedb and resolve the clippy issues.
> chore: update snafu to make clippy happy

- src/meta-srv/src/selector.rs
> feat: change the default selector to RoundRobin

- scripts/install.sh
1. Download the latest stable released version by default;
2. Do some small refactoring:
- Add `GITHUB_TOKEN`;
- Code format;
- Add `download_artifact()`;
> ci: download the latest stable released version by default and do some small refactoring

- src/servers/src/mysql/handler.rs
because our customer might report some security issues just by the mysql server version. trying to make them happy. now the default returned 8.4.2 is the latest mysql lts version
> chore: make mysql server version changable

- src/cmd/src/bin/greptime.rs
- src/cmd/src/error.rs
set larger stack size for debug mode, so it doesn't overflow for deep recursive functions. After setting this, `cargo sqlness` doesn't overflow in windows(it can relably reproduce overflow before this fix)
https://github.com/GreptimeTeam/greptimedb/actions/runs/10261340360/job/28388920598
> fix: larger stack size in debug mode

- src/common/meta/src/ddl/drop_table.rs
- src/common/meta/src/ddl/drop_table/metadata.rs
- src/common/meta/src/ddl/test_util.rs
- src/common/meta/src/ddl/test_util/create_table.rs
- src/common/meta/src/ddl/tests/drop_table.rs
Rollback metadata only if dropping the metric physical table fails
> fix: rollback only if dropping the metric physical table fails

- src/promql/src/extension_plan/range_manipulate.rs
A minor refactor to avoid some repeated allocation
> refactor: reuse aligned ts array in range manipulate exec

- grafana/README.md
https://github.com/GreptimeTeam/greptimedb/pull/4540
Forgot to update the readme file. `greptime_pod -> instance`.
It also simplifies the example config.
> docs: update grafana readme

- src/datatypes/src/duration.rs
- src/datatypes/src/interval.rs
- src/datatypes/src/time.rs
- src/datatypes/src/timestamp.rs
- src/datatypes/src/vectors/helper.rs
added a helper function to convert `Vec<Value>` to `VectorRef`, and it's test
> chore: Helper function to convert `Vec<Value>` to VectorRef

- tests/conf/metasrv-test.toml.template
set topic to 3 for sqlness test since it seems CI machine is too slow on opening topic when run `cargo sqlness` and sometimes can't start db in 10s hence failing sqlness Remote WAL test like this:
https://github.com/GreptimeTeam/greptimedb/actions/runs/10380872089/job/28741742298
> chore: set topic to 3 for sqlness test

- src/table/src/table/scan.rs
- tests/cases/distributed/explain/analyze_append_table_count.result
- tests/cases/distributed/explain/analyze_append_table_count.sql
This PR fixes the issue where null count is not initialized in column stats.
> fix: append table stats

- src/log-store/src/kafka/log_store.rs
- src/log-store/src/metrics.rs
- src/log-store/src/raft_engine/log_store.rs
> chore(log_store): remove redundant metrics

- .env.example
- config/config.md
- config/datanode.example.toml
- config/standalone.example.toml
- src/datanode/src/config.rs
- src/datanode/src/store/gcs.rs
- src/object-store/tests/object_store_test.rs
- tests-integration/src/test_util.rs
https://github.com/apache/opendal/blob/main/core/src/services/gcs/backend.rs#L62
Add this field to configure greptimedb gcs storage.
> feat: add GcsConfig credential field

- src/mito2/src/engine.rs
- src/mito2/src/engine/edit_region_test.rs
- src/mito2/src/error.rs
- src/mito2/src/request.rs
- src/mito2/src/worker.rs
- src/mito2/src/worker/handle_manifest.rs
Currently the region edit requests can only be handled one by one. This is because once a region is processing the request, it's set to the "Editing" state, which rejects other concurrent edit requests (require "Writable" state). 
This PR adds a "region edit queue" for temporarily storing the concurrent region edit requests. When concurrent requests come in, and the worker loop finds the region is in "Editing" state, it stores the requests in the queue. Once the current edit request is done, the worker loop checks the queue for a remaining edit request and handles it.
> feat: able to handle concurrent region edit requests

- src/cmd/src/lib.rs
- src/common/version/src/lib.rs
https://github.com/GreptimeTeam/greptimedb/issues/4533
1. Fix `short_version` function to handle empty branch.
2. Fix incorrect assignment between variables `version` and `short_version`.
> fix(common_version): short_version with empty branch

- Cargo.lock
- Cargo.toml
#4575 
Prepare to release v0.9.2
> chore: bump version to v0.9.2

- tests/cases/distributed/explain/analyze_append_table_count.result
- tests/cases/distributed/explain/analyze_append_table_count.sql
- closes #4584
Add SQLNESS replacements for RoundRobinBatch and region patterns etc.
> fix(sqlness): redact all volatile text

- src/query/src/dummy_catalog.rs
- tests/cases/standalone/common/select/prune.result
- tests/cases/standalone/common/select/prune.sql
Simple filter on primary key columns are precisely evaluated and need not to be evaluated again on Filter plan.
This patch has resulted in good performance improvement on my current test case. Before:
After:
> perf: set simple filter on primary key columns to exact filter

- Cargo.toml
- Makefile
This pr mainly change: keep symbol table in `nightly` profile.
> Try compiling on amd64 linux. Currently, the binary size compiled with profile = nightly is 209 MB. After the change, it is 251 MB.
> chore: keep symbol table in nightly profile

- src/sql/src/error.rs
- src/sql/src/parser.rs
- src/sql/src/parsers/copy_parser.rs
- src/sql/src/parsers/create_parser.rs
- src/sql/src/parsers/delete_parser.rs
- src/sql/src/parsers/describe_parser.rs
- src/sql/src/parsers/drop_parser.rs
- src/sql/src/parsers/explain_parser.rs
- src/sql/src/parsers/insert_parser.rs
- src/sql/src/parsers/set_var_parser.rs
- src/sql/src/parsers/show_parser.rs
- src/sql/src/parsers/truncate_parser.rs
- src/sql/src/statements.rs
- tests/cases/standalone/common/alter/alter_table_first_after.result
- tests/cases/standalone/common/copy/copy_from_fs_parquet.result
- tests/cases/standalone/common/create/create_database.result
- tests/cases/standalone/common/create/create_if_not_exists.result
- tests/cases/standalone/common/show/show_columns.result
- tests/cases/standalone/common/show/show_index.result
Don't repeat query SQL in error message.
> feat: remove sql in error desc

- Cargo.lock
- src/cmd/Cargo.toml
- src/common/mem-prof/Cargo.toml
- src/servers/Cargo.toml
This pr mainly bump `tikv-jemalloc*` to "0.6". 
This can fix the compilation error when specifying `lto = “thin”` for `aarch64-linux-android`. Related pr: https://github.com/tikv/jemallocator/pull/83
> chore: bump tikv-jemalloc* to "0.6"

- src/mito2/src/sst/index.rs
https://github.com/GreptimeTeam/greptimedb/issues/4586
- Reduce duplicate `IndexOutput` struct.
- Type `IndexBaseOutput` to `InvertedIndexOutput` and `FulltextIndexOutput`.
> refactor(mito2): reduce duplicate IndexOutput struct

- src/pipeline/src/etl.rs
* fix pipeline prepare loop break detects a conditional error
I'll be adding more detailed tests to the next version of the pipeline, as there will be big changes in the next version.
> fix: pipeline prepare loop break detects a conditional error

- config/config.md
- config/datanode.example.toml
- config/standalone.example.toml
- src/cmd/tests/load_config_test.rs
- src/mito2/src/config.rs
- tests-integration/tests/http.rs
This PR disables the write cache ttl by default. It also updates the example config.
> chore: disable ttl for write cache by default

- config/config.md
- config/metasrv.example.toml
https://github.com/GreptimeTeam/greptimedb/pull/4421 introduced `backend` field in the metasrv configs, this pr adds examples to the `backend` field.
> docs: add example configs introduced by pg_kvbackend

- Cargo.lock
- src/common/datasource/src/object_store/fs.rs
- src/common/datasource/src/object_store/s3.rs
- src/object-store/Cargo.toml
- src/object-store/src/util.rs
> chore: bump opendal version to 0.49

- src/mito2/src/access_layer.rs
- src/mito2/src/worker/handle_manifest.rs
Mainly to lift out an expensive object store read when editing region directly.
By calling region edit from outside, greptimedb fully trust the caller. (Or put it in another way, the guarantee of the manifest correctness is not within the greptimedb itself.) An existence check of the SST files is **less important than** the latency of the interface.
> refactor: skip checking the existence of the SST files 

- src/common/version/build.rs
I found a problem:
Each incremental build compiles the common-version crate and its dependent crates.
This causes each incremental build to take a very long time and puts pressure on my limited disk space.
> fix: incremental compilation always compile the common-version crate 

- .github/workflows/apidoc.yml
- .github/workflows/develop.yml
- .github/workflows/nightly-ci.yml
- .github/workflows/release.yml
- rust-toolchain.toml
- src/common/function/src/scalars/aggregate/scipy_stats_norm_pdf.rs
- src/meta-srv/src/lib.rs
- src/metric-engine/src/error.rs
previous 20240806 has an unexpected behavior which affects the result of float computation.
> chore: bump rust toolchain to 2024-06-06

- Cargo.lock
- Cargo.toml
> chore: bump rskafka to `75535b`

- src/mito2/src/compaction.rs
- src/mito2/src/error.rs
- src/mito2/src/region/options.rs
- src/store-api/src/mito_engine_options.rs
Add `fallback_to_local` to control whether to fall back to local compaction if remote compaction fails.
> refactor: add `fallback_to_local` region option

- src/servers/Cargo.toml
add `stats` feature for `jemalloc-ctl` in servers's toml, or else under certain features flag combination it will report error,
since in v0.6 of `jemalloc-ctl` the `stats` module is behind `stats` feature gate and we are using types in `stats` module
> chore: add `stats` feature for jemalloc-ctl

- src/common/version/build.rs
#4605
https://github.com/GreptimeTeam/greptimedb/pull/4605#discussion_r1726820693
If a project imports greptimedb as a submodule, [this approach](https://github.com/GreptimeTeam/greptimedb/pull/4605) will not work well, and each incremental build will also always compile the common version crate.
This PR mainly solves the above problem.
> chore: optimize common_version build

- src/query/src/promql/planner.rs
Scan in scatter mode if the step is very large. This can gain ~2x performance and lots of memory improvement in local test scenarios.
> perf: acclerate scatter query

- src/common/function/src/system.rs
- src/common/function/src/system/database.rs
- src/common/function/src/system/pg_catalog.rs
- src/common/function/src/system/pg_catalog/version.rs
- src/servers/src/postgres.rs
- src/servers/src/postgres/fixtures.rs
- src/servers/src/postgres/handler.rs
Fixes #4553 
This patch partially improved our compatibility with Superset and Metabase postgres source. Note that we still need hidden table support and more for full compatibility 
- Respond transaction related statements: BEGIN/ROLLBACK/COMMIT/SET TRANSATION .../SHOW TRANSACTION ...
- Add some fixed response for `SHOW ...`
- Add built in function `current_schema()`
- Add built in function `pg_catalog.version()`
- Updated version in postgres startup
> feat: add postgres response for trasaction related statements

- config/config.md
- config/metasrv.example.toml
- config/standalone.example.toml
- src/common/meta/src/wal_options_allocator/kafka/topic_manager.rs
- src/common/wal/src/config.rs
- src/common/wal/src/config/kafka/common.rs
- src/common/wal/src/config/kafka/datanode.rs
- src/common/wal/src/config/kafka/metasrv.rs
> feat: allow skipping topic creation

- .github/actions/build-linux-artifacts/action.yml
- .github/workflows/dev-build.yml
- .github/workflows/nightly-build.yml
- .github/workflows/release-dev-builder-images.yaml
- .github/workflows/release.yml
> ci: add push dev-build images to aws ecr

- .github/actions/build-macos-artifacts/action.yml
- .github/actions/build-windows-artifacts/action.yml
- .github/workflows/apidoc.yml
- .github/workflows/develop.yml
- .github/workflows/nightly-ci.yml
- .github/workflows/release.yml
Update CI files. Write toolchain once, all downstream projects and CI should follow it.
> ci: improve toolchain resolution in ci

- src/cmd/src/datanode.rs
- src/cmd/src/flownode.rs
- src/cmd/src/frontend.rs
- src/cmd/src/lib.rs
- src/cmd/src/metasrv.rs
- src/cmd/src/standalone.rs
Add `app` in `greptime_app_version` metric
> refactor: add `app` in `greptime_app_version` metric

- .github/workflows/release-dev-builder-images.yaml
- .github/workflows/release.yml
- Makefile
- scripts/check-builder-rust-version.sh
Add check-builder-rust-version job in release and change release-dev-builder-images trigger condition
> ci: add check-builder-rust-version job in release and change release-dev-builder-images trigger condition

- src/mito2/src/region/opener.rs
This PR uses the compaction time window as the partition bucket if the region doesn't provide the time window in the compaction options.
Otherwise, the region may always infer the time bucket after re-opening the region.
> fix: fallback to window size in manifest

- src/query/src/optimizer/parallelize_scan.rs
- src/store-api/src/region_engine.rs
- src/table/src/table/scan.rs
Prior to this change, queries will report an error if `scan_parallelism` is greater than the number of CPUs.
> fix: update properties on updating partitions

- src/cmd/tests/load_config_test.rs
fix https://github.com/GreptimeTeam/greptimedb/actions/runs/10580234514
set `selector_result_cache_size` in the unit test
> fix: set `selector_result_cache_size` in unit test

- src/operator/src/statement/copy_database.rs
ignores view and temporary tables in `copy database`
> feat: copy database ignores view and temporary tables

- src/cmd/tests/load_config_test.rs
fix: https://github.com/GreptimeTeam/greptimedb/actions/runs/10607915769/job/29401223051
set `selector_result_cache_size` in unit test again
> fix: set `selector_result_cache_size` in unit test again

- src/mito2/src/cache/write_cache.rs
- src/mito2/src/engine/edit_region_test.rs
- src/mito2/src/engine/listener.rs
- src/mito2/src/error.rs
- src/mito2/src/metrics.rs
- src/mito2/src/worker.rs
- src/mito2/src/worker/handle_manifest.rs
Pre-download the ingested SST files from remote object store to fill the local file cache to accelerate following reads.
> feat: pre-download the ingested sst

- src/cmd/src/cli.rs
- src/cmd/src/cli/database.rs
- src/cmd/src/cli/export.rs
- src/cmd/src/cli/import.rs
Import schema and data with cli tool.
#4276
> feat: import cli tool

- src/mito2/src/cache/write_cache.rs
- src/mito2/src/worker/handle_manifest.rs
Since the file size is known, we don't need to call object store's "stat" on the file. Thx to this [comment](https://github.com/GreptimeTeam/greptimedb/pull/4636#discussion_r1736561254)
> refactor: reduce a object store "stat" call

- src/datanode/src/heartbeat.rs
- src/datanode/src/metrics.rs
- src/frontend/src/heartbeat.rs
- src/frontend/src/metrics.rs
- src/meta-srv/src/metrics.rs
- src/meta-srv/src/service/heartbeat.rs
https://github.com/GreptimeTeam/greptimedb/issues/2848
Adding heartbeat sent/recv counters for frontend, datanode and  heartbeat recv counters by metasrv.
> chore: adding heartbeat sent/recv counts in greptimedb nodes

- src/mito2/src/read/scan_region.rs
- src/mito2/src/read/seq_scan.rs
- src/mito2/src/read/unordered_scan.rs
- src/mito2/src/test_util.rs
- src/query/src/optimizer/parallelize_scan.rs
- src/store-api/src/region_engine.rs
Initialize `PartitionRange`s from `ScanInput` for planner. It only contains a rough time range and number of rows at present.
The next step is to modify the corresponding logic about initializing `StreamContext`.
This patch also fixes the problem that `RegionScanExec` always generates only 1 partition.
> feat: initialize partition range from ScanInput

- src/operator/src/error.rs
- src/operator/src/statement/ddl.rs
- src/sql/src/parsers/create_parser.rs
remove the requirement that partition column must be PK
> feat: remove the requirement that partition column must be PK

- src/catalog/src/kvbackend/manager.rs
- src/datanode/src/region_server.rs
- src/mito2/src/cache/file_cache.rs
- src/mito2/src/cache/write_cache.rs
- src/mito2/src/sst/file_purger.rs
This PR removes files from the write cache explicitly once the purger removes the file.
> feat: remove files from the write cache in purger

- .github/actions/start-runner/action.yml
- .github/actions/stop-runner/action.yml
- .github/workflows/release.yml
1. Disable integration test on macOS when releasing because it's unnecessary and time-consuming;
2. Some minor refactoring;
> ci: disable macos integration test and some minor refactoring

- config/config.md
- config/standalone.example.toml
- src/cmd/src/standalone.rs
- tests-integration/tests/http.rs
expose `init_regions_in_background` and `init_regions_parallelism` opts
> fix: expose missing options for initializing regions

- .github/actions/build-macos-artifacts/action.yml
- .github/actions/build-windows-artifacts/action.yml
Since https://github.com/GreptimeTeam/greptimedb/commit/0b102ef846c9a907e95a9a5cb997e14ef88cfe1b changes the rust setup action from `dtolnay/rust-toolchain` to `actions-rust-lang/setup-rust-toolchain`, we need to resolve some arguments incompatible:
- `dtolnay/rust-toolchain` support both `target` and `targets`: https://github.com/dtolnay/rust-toolchain/blob/master/action.yml#L12-L17;
- `actions-rust-lang/setup-rust-toolchain` only support `target`: https://github.com/actions-rust-lang/setup-rust-toolchain/blob/main/action.yml#L18
Unfortunately, we use `targets` in the original release action.
> fix: use 'target' for 'actions-rust-lang/setup-rust-toolchain' to fix cross build failed

- .github/actions/setup-etcd-cluster/action.yml
> chore(ci): set etcd resources limits

- Cargo.lock
- config/config.md
- config/datanode.example.toml
- config/flownode.example.toml
- config/frontend.example.toml
- config/metasrv.example.toml
- config/standalone.example.toml
- src/common/telemetry/Cargo.toml
- src/common/telemetry/src/logging.rs
- tests-integration/tests/http.rs
1. Add `log_format`, can be `Text` and `Json`;
2. Refactor the `init_global_logging`;
3. Make the file logging can be disabled;
> refactor: make `init_global_logging()` clean and add `log_format`

- src/common/telemetry/src/lib.rs
- src/common/telemetry/src/logging.rs
- src/servers/src/http.rs
- src/servers/src/http/dyn_log.rs
add a http route to dynamic change log level, using the same syntax like `RUST_LOG`, i.e:
```bash
> curl --data "trace;flow=debug" 127.0.0.1:4000/debug/log_level;
Log Level changed from Some("info") to "trace"%
```
will change current log level to `trace;flow=debug` and appiled to logs came after this
Impl-wise, when init global logging, still will first check env `RUST_LOG` and etc, only difference are using `reload::Layer` to allow change log level dynamically.
perf-wise if not contended, logging with reloadable tracing layer is just fast path of acquire Read lock on a `RwLock` which is just one relaxed atomic operation and a few bit op
> feat: change log level dynamically

- src/auth/src/error.rs
- src/auth/src/tests.rs
This pr mainly adds `AuthBackendSnafu` back and adds a test function ref to the error so it won't get deleted in the future.
> fix: ref to auth err

- src/mito2/src/read/scan_region.rs
- src/mito2/src/read/seq_scan.rs
https://github.com/GreptimeTeam/greptimedb/issues/4480
This commit adds more spans into mito engine to give better insights on debugging slow queires.
For reads i enhanced spans on reader building time.
> feat: add more spans to mito engine

- docker/ci/ubuntu/Dockerfile
remove mysql and postgresql clients in greptimedb image
> chore(dockerfile): remove mysql and postgresql clients in greptimedb image

- src/pipeline/benches/processor.rs
- src/pipeline/src/etl.rs
- src/pipeline/src/etl/field.rs
- src/pipeline/src/etl/processor.rs
- src/pipeline/src/etl/processor/cmcd.rs
- src/pipeline/src/etl/processor/csv.rs
- src/pipeline/src/etl/processor/date.rs
- src/pipeline/src/etl/processor/dissect.rs
- src/pipeline/src/etl/processor/epoch.rs
- src/pipeline/src/etl/processor/gsub.rs
- src/pipeline/src/etl/processor/join.rs
- src/pipeline/src/etl/processor/letter.rs
- src/pipeline/src/etl/processor/regex.rs
- src/pipeline/src/etl/processor/timestamp.rs
- src/pipeline/src/etl/processor/urlencoding.rs
- src/pipeline/src/etl/transform.rs
- src/pipeline/src/etl/transform/transformer/greptime.rs
- src/pipeline/src/etl/transform/transformer/greptime/coerce.rs
- src/pipeline/tests/common.rs
- src/pipeline/tests/dissect.rs
- src/pipeline/tests/pipeline.rs
* remove dissect reference keys. because the resulting key is uncertain, it can't be specified by transform; if it is certain, you can use name matching to get the specified key directly.
* make all processors modify the intermediate state of the vec format directly. optimizing performance
* use the builder to build all processors, making the processor build flow easier to understand.
> refactor!: add processor builder and transform buidler

- src/mito2/src/read/scan_region.rs
- src/mito2/src/read/seq_scan.rs
- src/mito2/src/read/unordered_scan.rs
- src/store-api/src/region_engine.rs
- src/table/src/table/scan.rs
- tests/cases/standalone/common/aggregate/count.result
- tests/cases/standalone/common/aggregate/count.sql
Closes #4692
#4545 gives an incorrect impl of `statistics` method, which should consider both projection and filter of the underlying format reader when generating statistics.
> fix: unconditional statistics

- src/common/function/src/system/version.rs
- src/servers/src/postgres.rs
- tests/cases/standalone/common/function/system.result
- tests/cases/standalone/common/function/system.sql
This patch update `version` implementation to return version number according to the channel the client connects with.
> fix: return version string based on request protocol

- Cargo.lock
- config/config.md
- config/datanode.example.toml
- config/standalone.example.toml
- src/cmd/tests/load_config_test.rs
- src/common/wal/Cargo.toml
- src/common/wal/src/config/raft_engine.rs
- src/datanode/src/datanode.rs
- src/log-store/src/raft_engine/log_store.rs
- src/log-store/src/test_util/log_store_util.rs
- tests-integration/tests/http.rs
This PR exposes the WAL recovery parallelism config option which accelerates datanode startup. If this option is not provided, it will be set to the num of CPU cores.
```
2024-09-06T07:15:04.078774Z INFO log: Recovering raft logs takes 12.861302s
2024-09-06T07:17:35.698756Z INFO log: Recovering raft logs takes 7.931731s
```
> feat(wal): increase recovery parallelism

- src/meta-srv/src/procedure/region_migration/downgrade_leader_region.rs
Print downgraded region `last_entry_id`
> chore: print downgraded region last_entry_id

- src/pipeline/src/etl.rs
- src/pipeline/src/etl/processor/dissect.rs
- src/pipeline/tests/dissect.rs
- src/pipeline/tests/regex.rs
* pipeline dissert error is returned directly to the user, instead of printing a warn log
> fix: pipeline dissert error is returned directly to the user, instead of printing a warn log

- tests-fuzz/src/generator/create_expr.rs
- tests-fuzz/src/translator/mysql/create_expr.rs
- tests-fuzz/targets/fuzz_alter_logical_table.rs
- tests-fuzz/targets/fuzz_alter_table.rs
- tests-fuzz/targets/fuzz_create_logical_table.rs
- tests-fuzz/targets/fuzz_create_table.rs
- tests-fuzz/targets/fuzz_insert.rs
- tests-fuzz/targets/fuzz_insert_logical_table.rs
Enable fuzz test for append mode table
> chore: enable fuzz test for append table

- src/common/base/src/range_read.rs
- src/index/src/inverted_index/format/reader/blob.rs
- src/index/src/inverted_index/format/reader/footer.rs
- src/index/src/inverted_index/format/writer/blob.rs
- src/mito2/src/sst/index/inverted_index/applier.rs
#4717 
* Add `RangeReaderAdapter`
* Simplify generic param on `InvertedIndeFooterReader`
> feat(index): add explicit adapter between `RangeReader` and `AsyncRead`

- Cargo.lock
- Cargo.toml
- src/frontend/src/instance/otlp.rs
- src/servers/src/http.rs
- src/servers/src/http/otlp.rs
- tests-integration/Cargo.toml
- tests-integration/src/test_util.rs
- tests-integration/tests/http.rs
1. add `RequestDecompressionLayer::new()` for OTLP HTTP API to support auto `gzip` decompression.
2. change the create type to `log` to enable `append-only` mode upon table creation under `traces` API.
TODO
> chore: add auto-decompression layer for otlp http request

- Cargo.lock
- Cargo.toml
- src/cmd/Cargo.toml
- src/cmd/tests/load_config_test.rs
- tests-integration/Cargo.toml
- tests-integration/tests/http.rs
Resolve https://github.com/GreptimeTeam/greptimedb/issues/4722.
1. Fix config test failed in `cmd` crate by removing some auto configs;
2. Bring https://crates.io/crates/similar-asserts for config string compare;
> fix: config test failed and use `similar_asserts::assert_eq` to replace `assert_eq` for long string compare

- src/mito2/src/engine.rs
- src/mito2/src/region.rs
determine region role by using `is_readonly`
> fix: determine region role by using is_readonly

- Cargo.lock
- Cargo.toml
- src/servers/src/http.rs
- src/servers/src/http/arrow_result.rs
- src/servers/src/http/handler.rs
Add http param for compressing the arrow ipc format.
> feat: add an option to turn on compression for arrow output

- Cargo.lock
- src/catalog/Cargo.toml
- src/catalog/src/kvbackend/manager.rs
- src/common/meta/Cargo.toml
- src/common/meta/src/key/catalog_name.rs
- src/common/meta/src/key/datanode_table.rs
- src/common/meta/src/key/flow/flow_name.rs
- src/common/meta/src/key/flow/flow_route.rs
- src/common/meta/src/key/flow/flownode_flow.rs
- src/common/meta/src/key/flow/table_flow.rs
- src/common/meta/src/key/schema_name.rs
- src/common/meta/src/key/table_name.rs
- src/common/meta/src/range_stream.rs
- src/common/meta/src/state_store.rs
- src/log-store/src/raft_engine/backend.rs
- src/meta-srv/src/service/store/cached_kv.rs
This patch tries to solve some user's complaint about the lag while switching database in mysql cli by enabling concurrent tables iteration in information_schema to accelerate table rehash.
It also introduces some refactor regarding reading table information in kvbackend.
For a database with 100k tables, it cuts `show tables` cost time from 430ms to 200ms.
```
$ time mysql -h 127.0.0.1 -P 4002 -e "show tables" > /dev/null 2>&1
mysql -h 127.0.0.1 -P 4002 -e "show tables" > /dev/null 2>&1  0.01s user 0.00s system 7% cpu 0.432 total
$ time mysql -h 127.0.0.1 -P 4002 -e "show tables" > /dev/null 2>&1
mysql -h 127.0.0.1 -P 4002 -e "show tables" > /dev/null 2>&1  0.01s user 0.00s …
```
> refactor(tables): improve `tables` performance

- src/query/src/datafusion.rs
- src/servers/src/postgres/fixtures.rs
- src/servers/src/postgres/handler.rs
- src/servers/src/postgres/types.rs
This patch improves postgres extended query subprotocol:
- add support for empty query
- add support for statements from `fixtures` module
- improved situation that server failed to inference parameter types (for some temporary tables like information_schema)
- residual issue: it's still impossible to get a valid return value for statement describe request of temporary table.
> feat: improve support for postgres extended protocol

- docker/dev-builder/ubuntu/Dockerfile
alias cc to gcc-10 in dev build dockerfile, so cc_builder wouldn't emit warning about c compiler errors
https://github.com/GreptimeTeam/greptimedb/actions/runs/10935485852/job/30357457188#step:3:7106
says `aws-lc-sys` need higher version of gcc(cc>=10.3.0 or clang) to build, so just alias cc to `gcc-10` which is 10.5.0
> fix: use gcc-10 in release dev build

- Cargo.lock
- Cargo.toml
Since https://github.com/datafuselabs/jsonb/pull/56 has been merged, we can now switch to the original repo :)
> build(deps): use original jsonb repo

- .github/actions/build-dev-builder-images/action.yml
Fixed to: https://github.com/GreptimeTeam/greptimedb/actions/runs/10937322135/job/30364559521
The dev-builder image tag always [DEV_BUILDER_IMAGE_TAG](https://github.com/GreptimeTeam/greptimedb/blob/main/Makefile), we should use `input.version` and `DEV_BUILDER_IMAGE_TAG` field replace it.
> fix: cannot input tag for the dev-builder image

- src/mito2/src/read/scan_region.rs
- tests/cases/standalone/common/select/prune_field.result
- tests/cases/standalone/common/select/prune_field.sql
fixes https://github.com/GreptimeTeam/greptimedb/issues/4736
This PR disables pruning SSTs by fields if the merge mode is `last_non_null`. Pruning rows by fields before the merge phase may remove some useful rows, like #4736
This may have a negative impact on query performance in `last_non_null` mode. We can alleviate this by checking whether SSTs and memtables have overlapping ranges and only remove field filters if they are overlapping. However, we need to refactor the scanner to postpone pruning.
I'll address this later.
> fix: disable field pruning in last non null mode

- src/mito2/src/engine/flush_test.rs
- src/mito2/src/engine/listener.rs
- src/mito2/src/worker.rs
This PR checks all workers to see if we need to flush them after a flush job is finished. An inactive worker may keep a large write buffer but never flush it. Then other workers may flush very frequently since the global write buffer size is still high.
> feat: flush other workers if still need flush

- src/query/src/dist_plan/analyzer.rs
- src/query/src/dist_plan/commutativity.rs
- tests/cases/standalone/common/order/order_by.result
- tests/cases/standalone/common/order/order_by.sql
Support `ORDER BY` in partitioned table
> feat: include order by to commutativity rule set

- src/operator/src/insert.rs
1. Introduce the `get_create_table_expr_on_demand ` function to infer creating table expression. 
2. Unify the styling, which always infers creating/altering table expressions first.
> refactor: unify the styling in `create_or_alter_tables_on_demand`

- src/operator/src/statement.rs
- src/servers/src/postgres/handler.rs
- src/servers/src/postgres/types.rs
- src/servers/src/postgres/types/error.rs
- src/session/src/context.rs
- src/session/src/lib.rs
In order to prevent those unsupported set statement from blocking connection establishment, here I return a warning message instead of hard error for postgres.
```
psql (16.3)
Type "help" for help.
public=> SET statement_timeout = 40000;
WARNING:  Unsupported set variable STATEMENT_TIMEOUT
OK 0
public=> SET statement_timeout to 40000;
WARNING:  Unsupported set variable STATEMENT_TIMEOUT
OK 0
```
> feat: returning warning instead of error on unsupported `SET` statement

- src/pipeline/benches/processor.rs
- src/pipeline/src/etl.rs
- src/pipeline/src/etl/error.rs
- src/pipeline/src/etl/field.rs
- src/pipeline/src/etl/processor.rs
- src/pipeline/src/etl/processor/cmcd.rs
- src/pipeline/src/etl/processor/csv.rs
- src/pipeline/src/etl/processor/date.rs
- src/pipeline/src/etl/processor/dissect.rs
- src/pipeline/src/etl/processor/epoch.rs
- src/pipeline/src/etl/processor/gsub.rs
- src/pipeline/src/etl/processor/join.rs
- src/pipeline/src/etl/processor/letter.rs
- src/pipeline/src/etl/processor/regex.rs
- src/pipeline/src/etl/processor/timestamp.rs
- src/pipeline/src/etl/processor/urlencoding.rs
- src/pipeline/src/etl/transform.rs
- src/pipeline/src/etl/transform/index.rs
- src/pipeline/src/etl/transform/transformer/greptime.rs
- src/pipeline/src/etl/transform/transformer/greptime/coerce.rs
- src/pipeline/src/etl/value.rs
- src/pipeline/src/lib.rs
- src/pipeline/src/manager/error.rs
- src/pipeline/src/manager/table.rs
- src/pipeline/tests/dissect.rs
- src/servers/src/http/event.rs
* Change the error type in the pipeline crate from String to Error
> refactor: Change the error type in the pipeline crate from String to Error

- config/config.md
- config/datanode.example.toml
- config/standalone.example.toml
- src/datanode/src/config.rs
- src/datanode/src/datanode.rs
- src/datanode/src/error.rs
- src/datanode/src/region_server.rs
Adding query parallelism limit in region server to protect datanode from query overload.
> feat: protect datanode with concurrency limit.

- src/frontend/src/instance.rs
- tests/cases/standalone/common/system/information_schema.result
- tests/cases/standalone/common/system/information_schema.sql
#4773 
`is_reserved_schema_name` check should only be done when creating new database/schema.
> fix: use information_schema returns Unknown database 

- Cargo.lock
- src/servers/Cargo.toml
Update pgwire to 0.24.3 which fixes the issue with disconnected clients. Upstream fix: https://github.com/sunng87/pgwire/pull/206
> fix: dead loop on detecting postgres ssl handshake

- Cargo.lock
- src/servers/Cargo.toml
Upstream fix: https://github.com/sunng87/pgwire/pull/207/files
> fix: update pgwire for potential issue with connection establish

- Cargo.lock
- src/common/base/Cargo.toml
- src/common/base/src/plugins.rs
This PR replaces the `anymap` dependency in plugin crate with `anymap2` in that the recent toolchain gives a warning:
```
>    --> /home/lei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anymap-1.0.0-beta.2/src/any.rs:37:40
>     |
> 37  |                 unsafe { Box::from_raw(raw as *mut $t) }
>     |                                        ^^^^^^^^^^^^^^
> ...
> 144 | impl_clone!(dyn CloneAny + Send);
>     | -------------------------------- in this macro invocation
>     |
>     = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
>     = note: for more information, see issue #127323 …
```
> chore: replace anymap with anymap2

- src/meta-srv/src/handler.rs
- src/meta-srv/src/metasrv.rs
- src/meta-srv/src/metasrv/builder.rs
- src/meta-srv/src/service/heartbeat.rs
Introduce the `HeartbeatHandlerGroupBuilder`, make it easier for upper layers to customize handler groups.
> refactor: introduce `HeartbeatHandlerGroupBuilder`

- config/config.md
- config/datanode.example.toml
- config/flownode.example.toml
- config/frontend.example.toml
- config/metasrv.example.toml
- config/standalone.example.toml
- src/common/telemetry/src/logging.rs
- src/log-store/src/kafka/client_manager.rs
- src/script/src/python/rspython/builtins/test.rs
- tests-integration/tests/http.rs
Closes #4777.
Exposed `max_log_files` in `LoggingOptions`, set it to 720 by default, and build `info_log` with this restriction.
Not sure how to test this. It passed CI tho.
> feat: set max log files to 720 by default, info log only

- Cargo.lock
- src/pipeline/Cargo.toml
- src/pipeline/src/etl/error.rs
- src/pipeline/src/etl/transform/transformer.rs
- src/pipeline/src/etl/transform/transformer/greptime.rs
- src/pipeline/src/lib.rs
- src/servers/src/http/event.rs
- tests-integration/tests/http.rs
* If the pipeline parameter is empty, the data is written directly.
> chore: add json write

- src/pipeline/src/etl/error.rs
- src/pipeline/src/etl/transform/transformer/greptime/coerce.rs
- src/pipeline/tests/epoch.rs
- src/pipeline/tests/timestamp.rs
Previously during the transform phase of the pipeline, the timestamp value coerce process ignores the targeting timestamp resolution of the definition.
> fix: ts conversion during transform phase

- src/servers/src/http.rs
- src/servers/src/http/handler.rs
- src/servers/src/http/json_result.rs
- tests-integration/tests/http.rs
Closes #4764.
> Some BI or visualization tools like PowerBI accepts json data from custom web apis.
As explained in #4764, it's better if the http service return a json format that is already supported by other products.
- Added JsonResponse.
- Placed relevant tests.
> feat: add json format output for http interface

- src/query/src/dist_plan.rs
- src/query/src/dist_plan/analyzer.rs
- src/query/src/dist_plan/commutativity.rs
- src/query/src/dist_plan/merge_scan.rs
- src/query/src/dist_plan/merge_sort.rs
- src/query/src/dist_plan/planner.rs
- src/query/src/query_engine/state.rs
- tests/cases/distributed/explain/multi_partitions.result
- tests/cases/standalone/common/order/order_by.result
Add a merge sort logical plan that for now **does the same thing** as before(same physical plan), but means need to do a proper merge sort here in the future
- `MergeSortLogicalPlan` that one day can be use to optimize sort pushdown
- a `MergeSortExtensionPlanner` to make it just translate to `SortExec` physical plan just like before, and this Planner happens after DistExtensionPlanner
- make `Sort` `ConditionalCommutative` so it can be translate to MergeSort
> feat: Merge sort Logical plan

- src/meta-srv/src/procedure/region_migration.rs
- src/meta-srv/src/procedure/region_migration/manager.rs
- src/meta-srv/src/region/supervisor.rs
Expose `RegionMigrationManagerRef` and `tracker` method of `RegionMigrationManagerRef `.
> feat: expose `RegionMigrationManagerRef`

- src/catalog/src/error.rs
- src/catalog/src/kvbackend/manager.rs
- src/catalog/src/system_schema/information_schema.rs
- src/catalog/src/system_schema/information_schema/cluster_info.rs
- src/catalog/src/system_schema/information_schema/procedure_info.rs
- src/catalog/src/system_schema/information_schema/region_statistics.rs
- src/catalog/src/system_schema/utils.rs
- src/catalog/src/table_source.rs
- src/cmd/src/cli/repl.rs
- src/cmd/src/flownode.rs
- src/cmd/src/frontend.rs
- src/cmd/src/lib.rs
- src/cmd/src/standalone.rs
- tests-integration/src/cluster.rs
- tests-integration/src/standalone.rs
Introduce `InformationExtension` trait to provide extension queries for information schema. Currently, the methods provided are `nodes`, `procedures`, and `region_stats`.
> feat: information extension

- src/common/meta/src/ddl/utils.rs
- src/common/meta/src/key/table_name.rs
> fix: correct table name formatting

- src/common/meta/src/error.rs
- src/common/meta/src/leadership_notifier.rs
- src/common/meta/src/lib.rs
- src/common/meta/src/wal_options_allocator.rs
- src/meta-srv/src/lib.rs
- src/meta-srv/src/metasrv.rs
- src/meta-srv/src/procedure.rs
- src/meta-srv/src/region/supervisor.rs
Introduce `LeadershipChangeNotifier` and `LeadershipChangeListener`, allowing the upper layer to register listeners to react to leadership change events.
> feat: introduce `LeadershipChangeNotifier` and `LeadershipChangeListener`

- src/query/src/promql/planner.rs
- tests/cases/standalone/common/tql/basic.result
- tests/cases/standalone/common/tql/basic.sql
Closes https://github.com/GreptimeTeam/greptimedb/issues/4786#top
Make `__field__` in promql case sensitive
> fix: case sensitive for __field__ matcher

- Cargo.lock
- Cargo.toml
- docs/how-to/how-to-profile-cpu.md
- docs/how-to/how-to-profile-memory.md
- src/cmd/Cargo.toml
- src/common/pprof/Cargo.toml
- src/common/pprof/src/lib.rs
- src/common/pprof/src/nix.rs
- src/servers/Cargo.toml
- src/servers/src/error.rs
- src/servers/src/http/pprof.rs
This PR enables prof features by default. We already move prof APIs to behind `/debug` URL and don't expose them as part of public v1 API, so it should be safe to enable them by default.
We can revert this if there are other issues.
> feat: enable prof features by default

- src/metric-engine/src/engine/alter.rs
- src/metric-engine/src/engine/open.rs
- src/metric-engine/src/engine/read.rs
- src/metric-engine/src/engine/region_metadata.rs
- src/metric-engine/src/engine/state.rs
- src/metric-engine/src/metadata_region.rs
Cache logical region's metadata to accelerate query.
Given some metrics are likely never to be used, this cache is loaded lazily.
> feat: cache logical region's metadata

- src/datanode/src/region_server.rs
- src/metric-engine/src/engine.rs
- src/metric-engine/src/engine/close.rs
Tidy some logs in the region server
| before  | after   |
| :-------: | :-------: |
| <img width="711" alt="image" src="https://github.com/user-attachments/assets/1e1d9e85-681b-4ba8-9163-64a99958d0ad">   | Downgraded to debug log   |
| <img width="989" alt="image" src="https://github.com/user-attachments/assets/83e3cbe6-74db-4e0a-ae6e-fe5436095329">   | Downgraded to debug log. With a new info log to display region counter. <img width="282" alt="image" src="https://github.com/user-attachments/assets/d9e180f7-b25b-439f-a2e2-1263dd7dea4a">   |
|  <img width="951" alt="image" src="https://github.com/user-attachments/assets/ab762e50-d128-45d7-a8f9-7622b4f53b71"> | Downgraded to debug …
> refactor: replace info logs with debug logs in region server

- src/cmd/src/metasrv.rs
- src/cmd/src/standalone.rs
- src/common/meta/src/leadership_notifier.rs
- src/meta-srv/src/bootstrap.rs
- src/meta-srv/src/handler.rs
- src/meta-srv/src/handler/failure_handler.rs
- src/meta-srv/src/handler/region_lease_handler.rs
- src/meta-srv/src/metasrv.rs
- src/meta-srv/src/metasrv/builder.rs
- src/meta-srv/src/mocks.rs
- src/meta-srv/src/region/supervisor.rs
- src/meta-srv/src/service/heartbeat.rs
- Added `mut_inner` method to `Instance` and `MetasrvInstance` for mutable access to inner structs.
- Changed `NameCachedHandler` to use `Arc` instead of `Box` for `HeartbeatHandler`.
- Extended `LeadershipChangeNotifier` with a customizer trait to allow listener extensions.
- Made `StandaloneInformationExtension` public for external use.
- Defer  `HeartbeatHandlerGroup` construction.
> feat: defer `HeartbeatHandlerGroup` construction  and enhance `LeadershipChangeNotifier`

- src/cmd/src/metasrv.rs
- src/common/base/src/plugins.rs
- src/common/meta/src/leadership_notifier.rs
- src/meta-srv/src/bootstrap.rs
- src/meta-srv/src/handler.rs
- src/meta-srv/src/handler/filter_inactive_region_stats.rs
1. Introduce `DefaultHeartbeatHandlerGroupBuilderCustomizer` and `DefaultLeadershipChangeNotifierCustomizer`
2. Expose `env_prefix` and `config_file`
> feat: introduce default customizers

- src/common/function/src/scalars/aggregate.rs
Prevent error with `cargo build --no-deafult-features`
> fix: respect feature flags for geo function

- Cargo.lock
- Cargo.toml
update greptime-proto to `b4d3011`
> chore: update greptime-proto to `b4d3011`

- config/config.md
- config/datanode.example.toml
- config/standalone.example.toml
- src/common/wal/src/config/kafka/datanode.rs
- src/log-store/src/kafka/log_store.rs
overwrite entry_id if entry id is less than start_offset
> fix: overwrite entry_id if entry id is less than start_offset

- src/metric-engine/src/engine.rs
- src/metric-engine/src/engine/catchup.rs
- src/metric-engine/src/engine/flush.rs
- src/store-api/src/region_request.rs
Flush metric metadata region as well
> fix: flush metric metadata region

- Cargo.lock
- Cargo.toml
> chore: bump version to 0.9.5

- grafana/greptimedb.json
Changes CPU/Mem panels to time series panels. Bumps version to 16.
> docs: change cpu/mem panel to time-series

- src/catalog/src/system_schema/memory_table.rs
- src/common/recordbatch/src/recordbatch.rs
- src/mito2/src/read.rs
- src/mito2/src/read/projection.rs
- src/mito2/src/read/seq_scan.rs
- src/mito2/src/read/unordered_scan.rs
- src/store-api/src/region_engine.rs
This PR adds an empty batch to the end of the stream for each `PartitionRange`.
It also adds a `BatchChecker` to validate batches in the scanner.
> feat: yields empty batch after reading a range

- src/query/src/lib.rs
- src/query/src/part_sort.rs
- src/query/src/test_util.rs
- src/query/src/window_sort.rs
- add a physical plan that sort within each `PartitionRange` boundary marked by **empty** RecordBatch
- add fuzzy(ish) test for it
> feat: Sort within each PartitionRange

- src/cmd/src/frontend.rs
- src/cmd/tests/load_config_test.rs
- src/meta-srv/src/metasrv.rs
- src/meta-srv/src/metasrv/builder.rs
Updated `DatanodeClientOptions` to use `Duration` for `timeout` and `connect_timeout` with `humantime_serde` serialization.
Modified `MetasrvBuilder` to use the updated `DatanodeClientOptions`.
> fix!: replace timeout_millis and connect_timeout_millis with Duration in DatanodeClientOptions

- src/flow/src/adapter.rs
- tests/cases/standalone/common/flow/flow_basic.result
- tests/cases/standalone/common/flow/flow_basic.sql
adjust flow's column check so that `update_at` column is only appended when possible, and give a better msg when column is mismatched
> chore: better column schema check for flow

- Cargo.lock
- src/cmd/src/datanode.rs
- src/cmd/src/frontend.rs
- src/cmd/src/metasrv.rs
- src/cmd/src/options.rs
- src/cmd/src/standalone.rs
- src/plugins/Cargo.toml
- src/plugins/src/datanode.rs
- src/plugins/src/frontend.rs
- src/plugins/src/lib.rs
- src/plugins/src/meta_srv.rs
- src/plugins/src/options.rs
> feat: introduce the `PluginOptions`

- Cargo.lock
- Cargo.toml
- src/frontend/src/instance/otlp.rs
- src/servers/src/http/otlp.rs
- src/servers/src/otlp/logs.rs
- tests-integration/tests/http.rs
This pr mainly does:
1. add `scope_schema_url` and `resource_schema_url` to the OTLP logs table
2. change column order from bottom up(log -> scope -> resource). see below for detail
3. introduce `ParseContext` for passing data during the parsing process.
4. change span id and trace id to `Field` instead of `Tag`
Before column order
```
scope_name
scope_version
scope_attributes
resource_attributes
log_attributes
timestamp
observed_timestamp
trace_id
span_id
trace_flags
severity_text
severity_number
body
```
After column order
```
timestamp
trace_id
span_id
severity_number
severity_text
body
log_attributes
flags
scope_name
scope_version
scope_attributes
scope_schema_url …
```
> chore: add schema urls to otlp logs

- src/common/greptimedb-telemetry/src/lib.rs
- src/servers/src/error.rs
- src/servers/src/http.rs
exit greacefully instead of panic when failed to bind to http 4000
previously this bind fail will print confusing and alarming long panic msg and not very friendly
> chore: graceful exit on bind fail

- config/config.md
- config/datanode.example.toml
- config/standalone.example.toml
- src/mito2/src/compaction/compactor.rs
- src/mito2/src/config.rs
- src/mito2/src/engine/compaction_test.rs
- src/mito2/src/worker.rs
- tests-integration/tests/http.rs
closes https://github.com/GreptimeTeam/greptimedb/issues/4868
This PR divides the job pool (scheduler) for flushes and compactions.
Now the max_background_jobs options are replaced with `max_background_flushes`, `max_background_compactions` and `max_background_purges`.
> feat!: Divide flush and compaction job pool

- src/mito2/src/cache/cache_size.rs
Follow up of discussion in https://github.com/GreptimeTeam/greptimedb/pull/4857#discussion_r1815835989
Remove the test on struct size as it's subjective to rustc implemetations, and should only be used in interviews to politely reject a candidate.
> chore: remove struct size assertion

- src/script/src/python/ffi_types/pair_tests/sample_testcases.rs
> fix: pyo3 ut

- src/index/src/inverted_index/search/index_apply/predicates_apply.rs
- src/mito2/src/read/scan_region.rs
- src/mito2/src/sst/index.rs
- src/mito2/src/sst/index/inverted_index/applier/builder.rs
- src/mito2/src/sst/index/inverted_index/applier/builder/between.rs
- src/mito2/src/sst/index/inverted_index/applier/builder/comparison.rs
- src/mito2/src/sst/index/inverted_index/applier/builder/eq_list.rs
- src/mito2/src/sst/index/inverted_index/applier/builder/in_list.rs
- src/mito2/src/sst/index/inverted_index/applier/builder/regex_match.rs
- src/mito2/src/sst/index/inverted_index/creator.rs
Respect field columns when building the index. See the `do_update` function in `src/mito2/src/sst/index/inverted_index/creator.rs`
> feat(index): support building inverted index for the field column on Mito

- .github/actions/build-windows-artifacts/action.yml
- .github/workflows/develop.yml
- .github/workflows/nightly-ci.yml
follow up on #4894, since pyarrow no longer install numpy automatically(see https://github.com/apache/arrow/issues/43846), install it manually for testing
> ci: install numpy in CI

- Cargo.lock
- Cargo.toml
- src/api/src/helper.rs
- src/operator/src/req_convert/common.rs
Add json datatype for grpc protocol
wait for #4893
> feat: add json datatype for grpc protocol

- .github/workflows/develop.yml
- tests-fuzz/Cargo.toml
- tests-fuzz/targets/migration/fuzz_migrate_metric_regions.rs
Add fuzz test for metric region migration
> test: add fuzz test for metric region migration

- src/servers/src/mysql/federated.rs
- tests-integration/tests/sql.rs
The  MySQL driver may send some statements such as `set session transaction read only` etc.
https://github.com/mysql/mysql-connector-j/blob/cf2917ea44ae2e43a4514a33771035aa99de73bf/src/main/user-impl/java/com/mysql/cj/jdbc/ConnectionImpl.java#L2442
After we support the `set` statement, these special statements can't work with the JDBC driver.  In this PR, we just ignore them and add a test for it.
> fix: set transaction variables not working in mysql protocol

- Cargo.lock
- Cargo.toml
- src/servers/src/http.rs
- src/servers/src/http/prometheus.rs
- tests-integration/tests/http.rs
Fixes #4839 
This patch adds a new Prometheus 3.0 API for visualizing PromQL AST, like in this type of UI: https://github.com/perses/perses/pull/2344
Please merge https://github.com/GreptimeTeam/promql-parser/pull/94 first.
> feat: implement parse_query api

- src/mito2/src/engine/prune_test.rs
- src/mito2/src/memtable.rs
- src/mito2/src/read/prune.rs
- src/mito2/src/read/scan_util.rs
- src/mito2/src/read/seq_scan.rs
- src/mito2/src/read/unordered_scan.rs
- src/mito2/src/test_util/memtable_util.rs
https://github.com/GreptimeTeam/greptimedb/issues/4828
This PR fixes that memtable may return rows out of the expected time range. The memtable updates the min/max stats so it can yield rows out of the range when there are in-progress rows during query.
It adds a `PruneTimeIterator` to filter batches by time range.
> fix: prune batches from memtable by time range

- src/mito2/src/cache.rs
- src/mito2/src/read/range.rs
- src/mito2/src/sst/file.rs
- src/mito2/src/sst/parquet.rs
- src/mito2/src/sst/parquet/format.rs
https://github.com/GreptimeTeam/greptimedb/issues/4828
This PR tries to get the correct time ranges for each row group from the cached if it is available.
Before this PR (Without cache):
```
explain analyze select * from test_mem order by timestamp limit 1;
|     0 |    0 |  MergeScanExec: peers=[4402341478400(1025, 0), ] metrics=[output_rows: 1, greptime_exec_read_cost: 0, ready_time: 49619816, first_consume_time: 4880361674, finish_time: 4880541784, ]
|
|     1 |    0 |  GlobalLimitExec: skip=0, fetch=1 metrics=[output_rows: 1, elapsed_compute: 18032975, ]
SortPreservingMergeExec: [timestamp@9 ASC NULLS LAST] metrics=[output_rows: 16, elapsed_compute: 52859, ]
WindowedSortExec …
```
> feat: get row group time range from cached metadata

- src/query/src/optimizer/windowed_sort.rs
- src/query/src/part_sort.rs
- src/query/src/window_sort.rs
- src/table/src/table/scan.rs
- tests/cases/standalone/common/order/windowed_sort.result
This patch
- implement a simple limit to `PartSort`
- fixes a old semantic bug
This simple limit mechanism can bring an obvious improvement even though it's not the optimal impl
Before:
```sql
+-------+------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ …
```
> feat: simple limit impl in PartSort

- src/sql/src/parsers/alter_parser.rs
As title. Switch to pattern-matching similar to `create_parser` to increase readability and a little refine about error messages.
> refactor: refactor alter parser

- src/servers/src/mysql/handler.rs
fix violations of `elided_named_lifetimes`
This warning was introduced by https://github.com/rust-lang/rust/pull/129207.
> fix: violations of `elided_named_lifetimes`

- src/meta-srv/src/selector/common.rs
- src/meta-srv/src/selector/lease_based.rs
- src/meta-srv/src/selector/load_based.rs
- src/meta-srv/src/selector/weighted_choose.rs
> chore: minor refactor for weighted choose

- src/flow/src/server.rs
- src/frontend/src/instance.rs
- src/frontend/src/instance/builder.rs
- src/operator/src/statement.rs
- src/servers/src/interceptor.rs
- src/servers/tests/interceptor.rs
- tests-integration/Cargo.toml
Just like the same in the sql execution interceptor, we need to find promql's target object names from its logical plan.
> refactor: pass `LogicalPlan` to promql execution interceptor

- Cargo.lock
- Cargo.toml
- src/servers/src/http/pprof.rs
previous due to lack of maintaince pprof crate is not usable in certain platform. 
Fork and applied a fix which check for null pointer and update ahash crate which now fix pprof for my machine.
The fork is here: https://github.com/GreptimeTeam/pprof-rs
Before this fix, my machine panic on trying to pprof, now it can get a flamegraph(The db is basically idle when doing the pprof): 
> fix: pprof

- docs/how-to/how-to-change-log-level-on-the-fly.md
The log level should be separated by commas
> chore: fix typos in change log level doc

- Cargo.lock
- src/pipeline/Cargo.toml
- src/pipeline/src/etl/error.rs
- src/pipeline/src/etl/processor.rs
- src/pipeline/src/etl/processor/json_path.rs
- src/pipeline/src/etl/value.rs
- src/pipeline/tests/pipeline.rs
* add json path processor for log pipeline
We use the library https://github.com/besok/jsonpath-rust to implement the JsonLike trait for our Value, which implements the ability to search for a Value via a json path.
> chore: add json path for pipeline

- tests-integration/src/cluster.rs
> fix: the region_stats API will return an error in instance test

- src/mito2/src/compaction/twcs.rs
- src/mito2/src/compaction/window.rs
- src/mito2/src/test_util/memtable_util.rs
This PR fixes that twcs compaction picker may pick expired files to compact.
We already set the `compacting` here:
https://github.com/GreptimeTeam/greptimedb/blob/22a662f6bcb811e2c6e36a2a29d035175f4131df/src/mito2/src/compaction/twcs.rs#L218-L222
> fix: do not pick compacting/expired files

- src/metric-engine/src/engine/region_metadata.rs
- src/metric-engine/src/engine/state.rs
This is caused by a concurrent update bug to the metadata cache.
> fix: column already exists

- src/query/src/optimizer/windowed_sort.rs
- src/query/src/part_sort.rs
- src/query/src/window_sort.rs
Supports SQL like `select * from t where a > 0 order by ts limit 1;`. The resulting plan looks like
```
|     1 |    0 |  GlobalLimitExec: skip=0, fetch=1 metrics=[output_rows: 1, elapsed_compute: 27973, ]
SortPreservingMergeExec: [ts@0 DESC] metrics=[output_rows: 8, elapsed_compute: 32000, ]
WindowedSortExec: expr=ts@0 DESC num_ranges=8 fetch=1 metrics=[output_rows: 8, elapsed_compute: 8, ]
PartSortExec: expr=ts@0 DESC num_ranges=8 limit=1 metrics=[output_rows: 8, elapsed_compute: 8, ]
CoalesceBatchesExec: target_batch_size=8192 metrics=[output_rows: 471572, elapsed_compute: 139367822, ]
FilterExec: ts@0 > 1730728703716 metrics=[output_rows: 471572, elapsed_compute: 5743584, ] …
```
> feat: support filter with windowed sort

- Cargo.lock
- Cargo.toml
- src/cmd/Cargo.toml
- src/cmd/tests/load_config_test.rs
- src/common/options/Cargo.toml
- src/common/options/src/datanode.rs
- src/common/options/src/lib.rs
- src/frontend/Cargo.toml
- src/frontend/src/frontend.rs
- src/meta-srv/Cargo.toml
- src/meta-srv/src/metasrv.rs
Fixes #4932
- Unify the datanode options in frontend and metasrv
- Move the `DatanodeClientOptions` into `common/options` crate.
> refactor: consolidate `DatanodeClientOptions`

- src/mito2/src/worker/handle_alter.rs
- src/store-api/src/mito_engine_options.rs
- src/store-api/src/region_request.rs
- src/table/src/metadata.rs
- tests/cases/standalone/common/alter/alter_table_options.result
- tests/cases/standalone/common/alter/alter_table_options.sql
https://github.com/GreptimeTeam/greptimedb/issues/4905
support alter twcs compaction options on sql level
- The approach here is to expand ChangeOption enum with twcs compaction options.
- The key and value type is validated at store-api end.
- If value is missing (empty string) it will be set with default value.
Changes will be reflected on show create table statements.
> feat: support alter twcs compaction options

- src/mito2/src/memtable.rs
- src/mito2/src/memtable/partition_tree.rs
- src/mito2/src/memtable/partition_tree/dict.rs
- src/mito2/src/memtable/partition_tree/partition.rs
- src/mito2/src/memtable/partition_tree/shard.rs
- src/mito2/src/memtable/partition_tree/shard_builder.rs
- src/mito2/src/memtable/partition_tree/tree.rs
- src/mito2/src/memtable/stats.rs
- src/mito2/src/memtable/time_series.rs
Extract the logic to track memtable write metrics and update memtable timestamp ranges into a common mod for reuse.
> refactor(mito): tidy memtable stats

- src/sql/src/parsers/alter_parser.rs
- src/sql/src/statements/alter.rs
- tests/cases/standalone/common/alter/change_col_fulltext_options.result
- tests/cases/standalone/common/alter/change_col_fulltext_options.sql
#4952 
Previously introduced alter fulltext use 
```sql
ALTER TABLE monitor COLUMN <column_name> SET FULLTEXT WITH(enable='false');
```
to disable the fulltext index.
This patch change it to 
```sql
ALTER TABLE monitor COLUMN <column_name> UNSET FULLTEXT;
```
for simplicity and better compatibility with fulltext index settings in `CREATE` stmt.
> refactor: use UNSET instead of enable

- Cargo.lock
- Cargo.toml
https://github.com/databendlabs/jsonb/pull/66 and https://github.com/databendlabs/jsonb/pull/67 have been merged so we can switch to upstream jsonb.
> build(deps): switch to upstream jsonb

- .github/scripts/check-install-script.sh
- .github/workflows/nightly-ci.yml
- scripts/install.sh
When running the `install.sh` on Linux, it has the following errors:
```
curl -fsSL \
https://raw.githubusercontent.com/greptimeteam/greptimedb/main/scripts/install.sh  | sh -s v0.9.5
sh: 18: Syntax error: "(" unexpected
```
1. Use `#!/bin/sh` as shebang for better compatibility;
2. Remove `function` keyword for using `sh`(https://www.shellcheck.net/wiki/SC2112);
3. Check the `install.sh` in nightly CI;
> fix: run `install.sh` error

- grafana/README.md
- grafana/greptimedb-cluster.json
Big changes for the GreptimeDB cluster Grafana dashboard. Here is the screenshot:
1. Refactor the variables(use `greptime_app_version` for pods self-discovery):
- `metrics`: The Prometheus data source;
- `information_schema`: The SQL instance which to expose metadata of the cluster;
- `roles`: Select different roles;
- `pods`: Select different pods;
Base on the above variables, the new dashboard defines the new variables to describe roles: `datanode`/`frontend`/`metasrv`/`flownode`.
2. Add the `Overview` and `Resources`:
- `Overview` is the **summary** of the whole cluster;
- `Resources` is the total CPU and memory for the different roles of the cluster(TODO: I haven't added the …
> refactor(grafana): update cluster dashboard

- grafana/greptimedb-cluster.json
1. Fix `pods` selection error;
2. Add more `Resources` panel:
> chore: update cluster dashboard

- Cargo.lock
- Cargo.toml
- src/common/meta/src/ddl/create_flow.rs
- src/flow/src/adapter/flownode_impl.rs
as title
which added a `or_replace` field for flow's creation
> chore: update greptime-proto to e1070a

- src/mito2/src/cache/write_cache.rs
- src/mito2/src/compaction.rs
- src/mito2/src/compaction/compactor.rs
- src/mito2/src/engine.rs
- src/mito2/src/read/last_row.rs
- src/mito2/src/read/projection.rs
- src/mito2/src/read/range.rs
- src/mito2/src/read/scan_region.rs
- src/mito2/src/read/seq_scan.rs
- src/mito2/src/read/unordered_scan.rs
- src/mito2/src/sst/parquet.rs
- src/mito2/src/sst/parquet/reader.rs
- src/mito2/src/sst/parquet/row_group.rs
#4968
- replace all usage of `Option<CacheManagerRef>` with `CacheMangerRef`.
> refactor: Avoid wrapping Option for CacheManagerRef

- Cargo.lock
- Cargo.toml
- src/common/grpc-expr/src/alter.rs
- src/common/meta/src/ddl/alter_table/region_request.rs
- src/common/meta/src/ddl/alter_table/update_metadata.rs
- src/operator/src/expr_factory.rs
- src/sql/src/parsers/alter_parser.rs
- src/sql/src/statements/alter.rs
- src/sql/src/statements/transform/type_alias.rs
- src/store-api/src/metadata.rs
- src/store-api/src/region_request.rs
- src/table/src/metadata.rs
- src/table/src/requests.rs
proto: https://github.com/GreptimeTeam/greptime-proto/pull/200
Just a rename.
Rename `ChangeColumnType` to `ModifyColumnType` to match it with SQL syntax.
> chore: rename change to modify

- src/datanode/src/heartbeat/handler/downgrade_region.rs
- src/meta-srv/src/procedure/region_migration/downgrade_leader_region.rs
- src/meta-srv/src/procedure/region_migration/open_candidate_region.rs
- src/mito2/src/worker/handle_catchup.rs
- tests-fuzz/targets/migration/fuzz_migrate_mito_regions.rs
Delete obsolete wal entries while opening a migrated region
> fix: obsolete wal entires while opening a migrated region

- tests/cases/standalone/common/subquery/table.result
- tests/cases/standalone/common/subquery/table.sql
- tests/cases/standalone/common/subquery/test_neumann.result
- tests/cases/standalone/common/subquery/test_neumann.sql
#1168 
As titile.
Only a few parts are migrated. Mostly because other parts are not available for greptimedb for these reasons:
1. Datafusion does not support: scalar subquery, exists, pivot ...
2. Different internal pre-defined tables, functions and types:
- **Tables**: orders, lineitem ...
- **Functions**: generate_series, gen_random_uuid ...
- **Types**: array/list type
3. Different grammar: duckdb uses query context differently,
- e.g.`SELECT (SELECT max((SELECT subq_0.c0 AS c1))) FROM (SELECT NULL AS c0) AS subq_0;`
- Seems the correct form for greptimedb is `SELECT (SELECT max((SELECT subq_0.c0 AS c1 FROM (SELECT NULL AS c0) AS subq_0)));`
- (Query above is still not …
> test: subquery test migrated from duckdb

- src/common/meta/src/ddl/create_flow.rs
- src/common/meta/src/ddl_manager.rs
- src/common/meta/src/key/flow.rs
- src/common/meta/src/key/flow/flow_info.rs
- src/common/meta/src/key/flow/flow_name.rs
- src/flow/src/adapter.rs
- src/flow/src/adapter/flownode_impl.rs
- src/flow/src/server.rs
- src/query/src/sql.rs
- tests/cases/standalone/common/flow/flow_basic.result
- tests/cases/standalone/common/flow/show_create_flow.result
- tests/cases/standalone/common/flow/show_create_flow.sql
impl replace flow
- impl replace flow on flownode by drop and create on flownode
- impl replace on metasrv by add a new `update_txn` for flowname&flow info value
- change `show create flow`'s output to contain `IF NOT EXISTS` only to prevent accidently clear internal state if need to run
> feat: CREATE OR REPLACE FLOW

- src/cmd/src/lib.rs
as title, windows remain the same with only ctrl c can close
> feat: also shutdown gracefully on sigterm on unix

- Cargo.lock
- Cargo.toml
- src/common/grpc-expr/src/alter.rs
- src/common/meta/src/ddl/alter_table/region_request.rs
- src/common/meta/src/ddl/alter_table/update_metadata.rs
- src/mito2/src/engine/alter_test.rs
- src/operator/src/expr_factory.rs
- src/sql/src/parsers/alter_parser.rs
- src/sql/src/statements/alter.rs
- src/store-api/src/metadata.rs
- src/store-api/src/region_request.rs
- src/table/src/metadata.rs
- src/table/src/requests.rs
- tests/cases/standalone/common/alter/change_col_fulltext_options.result
- tests/cases/standalone/common/alter/change_col_fulltext_options.sql
proto pr: https://github.com/GreptimeTeam/greptime-proto/pull/199
The patch splits the alter commands of `SET FULLTEXT [WITH <options>]` and `UNSET FULLTEXT` into different enum for simplicity. 
Also forbids to change column fulltext options if it has been set before to avoid unexpected query results, e.g.
```sql
> ALTER TABLE test MODIFY COLUMN message SET FULLTEXT WITH(analyzer = 'Chinese', case_sensitive = 'true');
> ALTER TABLE test MODIFY COLUMN message UNSET FULLTEXT;
> ALTER TABLE test MODIFY COLUMN message SET FULLTEXT WITH(analyzer = 'Engilish', case_sensitive = 'true');
```
will fail, since the third alter will change the analyzer.
> refactor: split up different stmts

- src/cmd/src/cli/database.rs
- src/cmd/src/cli/export.rs
- src/cmd/src/cli/import.rs
- src/servers/src/http.rs
- src/servers/src/http/test_helpers.rs
- src/servers/src/http/timeout.rs
Update the timeout option from `Option<Duration>` to `Duration` . And users can explicitly set the timeout to `0s` to disable server-side timeout configuration.
> chore(cli): set default timeout for cli commands

- Cargo.lock
- Cargo.toml
- src/common/grpc-expr/src/alter.rs
- src/common/grpc-expr/src/error.rs
- src/common/meta/src/ddl/alter_table/region_request.rs
- src/common/meta/src/ddl/alter_table/update_metadata.rs
- src/common/meta/src/ddl/tests/alter_table.rs
- src/mito2/src/worker/handle_alter.rs
- src/operator/src/expr_factory.rs
- src/sql/src/parsers/alter_parser.rs
- src/sql/src/statements/alter.rs
- src/store-api/src/metadata.rs
- src/store-api/src/region_request.rs
- src/table/src/metadata.rs
- src/table/src/requests.rs
- tests/cases/standalone/common/alter/alter_table_options.result
- tests/cases/standalone/common/alter/alter_table_options.sql
close https://github.com/GreptimeTeam/greptimedb/issues/5022
Add unset table options support
> feat: add unset table options support

- src/mito2/src/compaction/twcs.rs
fix issue in finding latest time window.
> fix: find latest window

- src/servers/src/mysql/handler.rs
- tests/cases/standalone/common/prepare/mysql_prepare.result
- tests/cases/standalone/common/prepare/mysql_prepare.sql
#4970 
Datafusion may convert the prepared sql to an optimized plan without initial params, so that we can't confirm if the param is needed when executing the prepared plan.
This patch introduces a workaroud that just drop the optimized plan if the param number mismatches and use the initial sql. It may affect the performance of the sql, but previously these sqls even cannot execute.
e.g.
```SQL
PREPARE stmt FROM 'SELECT ? + 1 WHERE 1 = 0';
EXECUTE stmt USING 1;
```
> fix: prepare param mismatch

- src/servers/src/error.rs
- src/servers/src/mysql/handler.rs
Refactor to simplify the `EXECUTE` stmt in mysql.
Will introduce a change of error code returned: execute non-prepared stmt will now return an `ErrorKind::ER_WRONG_ARGUMENTS` instead of `ErrorKind::ER_UNKNOWN_STMT_HANDLER`.
Also fix a bug when the stmt is not properly prepared and we need to use raw query with param converted to strings. Previously the param of `Date` time will be converted to strings without quote `SELECT 2000-12-20` that is not valid for sql parser.
> refactor: unify mysql execute through cli and protocol

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- tests/cases/distributed/information_schema/cluster_info.result
- tests/cases/distributed/information_schema/cluster_info.sql
- tests/cases/standalone/common/function/system.result
- tests/cases/standalone/common/function/system.sql
- tests/cases/standalone/information_schema/cluster_info.result
- tests/cases/standalone/information_schema/cluster_info.sql
https://github.com/GreptimeTeam/greptimedb/issues/5028
Bump version to v0.10.0
> chore: bump version to 0.10.0

- src/metric-engine/src/engine/create.rs
A quick bad fix for 0.10.1.
Metadata region has a constant 0 as time index column's value. When inheriting TTL from database it will remove all metadata.
> fix: prevent metadata region from inheriting database ttl

- config/config.md
- config/datanode.example.toml
- config/standalone.example.toml
- src/datanode/src/config.rs
- src/datanode/src/store.rs
- src/datanode/src/store/azblob.rs
- src/datanode/src/store/gcs.rs
- src/datanode/src/store/oss.rs
- src/datanode/src/store/s3.rs
- tests-integration/tests/http.rs
Unify the configuring of the http client used in the object store.
> refactor: expose configs for http clients used in object store

- src/metric-engine/src/engine/create.rs
- src/metric-engine/src/engine/open.rs
- typos.toml
#5044
The region options for metadata region in metric engines should stay independent from database options, no matter during opening or creating regions.
> fix(metric-engine): set ttl also on opening metadata regions

- src/catalog/src/kvbackend.rs
- src/catalog/src/kvbackend/client.rs
- src/cmd/src/cli/repl.rs
- src/cmd/src/flownode.rs
- src/cmd/src/frontend.rs
- src/datanode/src/datanode.rs
- src/datanode/src/heartbeat.rs
- src/datanode/src/heartbeat/handler.rs
- src/datanode/src/heartbeat/handler/cache_invalidator.rs
- src/meta-srv/src/cache_invalidator.rs
- tests-integration/src/cluster.rs
Add cache layer for SchemaMetadataManager
> feat: use cache kv manager for SchemaMetadataManager

- Cargo.lock
- Cargo.toml
N/A
Now greptimedb maintains the `release/vX.Y` branch, and the `main` branch should be the next minor version.
> chore: bump version of main branch to v0.11.0

- src/metric-engine/src/data_region.rs
- src/metric-engine/src/engine.rs
- src/metric-engine/src/engine/alter.rs
- src/mito2/src/engine/alter_test.rs
- tests/cases/standalone/common/alter/alter_table_options.result
- tests/cases/standalone/common/alter/alter_table_options.sql
https://github.com/GreptimeTeam/greptimedb/issues/5042
allow set and unset of region options in alter physical region request.
allow Alter/ unset region options by passing the request to DataNode's mito engine. 
> fix: allow physical region alter region options

- src/flow/src/df_optimizer.rs
- src/sql/src/parsers/create_parser.rs
- tests/cases/standalone/common/flow/flow_basic.result
- tests/cases/standalone/common/flow/flow_basic.sql
- fix can't use `count(*)` in flow creation
- fix `SINK` should be case insensitive but not
> fix(flow): minor fix about count(*)&sink keyword

- AUTHOR.md
- README.md
Try to improve readme. Update AUTHOR.md
> docs: tweak readme and AUTHOR

- src/meta-client/src/client/cluster.rs
- src/meta-client/src/client/heartbeat.rs
- src/meta-client/src/client/procedure.rs
- src/meta-client/src/client/store.rs
- src/meta-srv/src/bootstrap.rs
- src/meta-srv/src/lib.rs
- src/meta-srv/src/mocks.rs
Currently, compression is not enabled for MetaSrv RPCs, which can result in errors like:
`Error, message length too large: found 4228291 bytes, the limit is: 4194304 bytes`.
This PR enables zstd compression for the MetaSrv client by default. We retain the default max_recv_message_size of 4 MiB, as it is a reasonable limit. Increasing it could unnecessarily burden the internal connections between cluster nodes.
> feat: enable compression for metasrv client

- .github/cargo-blacklist.txt
- .github/workflows/dependency-check.yml
- Cargo.lock
- tests/runner/Cargo.toml
Remove openssl deps that introduced by `mysql` library
> chore: remove openssl deps

- src/common/meta/src/error.rs
- src/meta-client/src/client.rs
- src/meta-client/src/client/cluster.rs
- src/meta-client/src/error.rs
- src/meta-client/src/mocks.rs
- src/meta-srv/src/mocks.rs
- tests-integration/src/cluster.rs
This PR fixes the behavior of `PaginationStream`, ensuring it automatically adjusts the next request's `page_size` when the range response size from the in-memory store exceeds the size limit.
> fix: correct `is_exceeded_size_limit` behavior for in-memory store

- src/datanode/src/store.rs
- src/mito2/src/cache/file_cache.rs
- src/mito2/src/cache/write_cache.rs
- src/object-store/Cargo.toml
- src/object-store/src/layers/lru_cache.rs
- src/object-store/tests/object_store_test.rs
Recovering the cache index synchronously for a large number of files (potentially in the hundreds of thousands) can be highly time-consuming (e.g., ~10 seconds). This PR addresses the issue by making the cache index recovery process asynchronous, significantly reducing the startup time of the datanode.
> feat: recover file cache index asynchronously

- tests/cases/standalone/common/ttl/alter_table_ttl.result
- tests/cases/standalone/common/ttl/alter_table_ttl.sql
- tests/cases/standalone/common/ttl/basic.result
- tests/cases/standalone/common/ttl/basic.sql
- tests/cases/standalone/common/ttl/database_ttl.result
- tests/cases/standalone/common/ttl/database_ttl.sql
- tests/cases/standalone/common/ttl/database_ttl_with_metric_engine.result
- tests/cases/standalone/common/ttl/database_ttl_with_metric_engine.sql
- tests/cases/standalone/common/ttl/metric_engine_ttl.result
- tests/cases/standalone/common/ttl/metric_engine_ttl.sql
Close #5045 
Adds sqlness tests for TTL behavior including normal table, metric engine table, and database TTL.
> test: adds sqlness test for TTL

- src/mito2/src/read/last_row.rs
This PR takes a new batch to avoid referencing the old last-row batch. This can reduce the memory usage of the selector result cache.
In TSBS, this reduces cache usage from over 1GB to 8.3MB.
> perf: take a new batch to reduce last row cache usage

- docs/how-to/how-to-profile-cpu.md
- docs/how-to/how-to-profile-memory.md
- src/servers/src/http.rs
Remove GET methods for `/debug/log_level`, `/debug/cpu` and `/debug/mem` according to https://github.com/GreptimeTeam/docs/pull/1345#discussion_r1869416449
> feat!: remove GET method in `/debug` path

- docs/how-to/how-to-profile-memory.md
According to the [docs](https://jemalloc.net/jemalloc.3.html#opt.lg_prof_interval), this interval will dump files automatically.
Maybe the example wants to use lg_prof_sample. But we usually don't need to set the sample ratio.
> docs: remove lg_prof_interval from env

- src/servers/src/postgres/fixtures.rs
This patch adds transaction related statement for postgres interface:
- start transaction [isolation level ...]
- abort transaction
- commit transaction
> feat: add more transaction related statement for postgres interface

- src/mito2/src/compaction.rs
- src/mito2/src/config.rs
- src/mito2/src/error.rs
https://github.com/GreptimeTeam/greptimedb/issues/4957
Add a timeout setting for `find_ttl` function.
- Add Custom timeout error and attach to the error context when feteched TTL timeout.
- There is a global const variable to defined the timeout, dont know a better solution exsit or not.
> chore: Add timeout setting for `find_ttl`.

- src/query/src/sql/show_create_table.rs
- src/sql/src/statements/option_map.rs
- tests/cases/standalone/common/alter/alter_table_options.result
Table options such as `compaction.twcs.time_window` and `compaction.type` must be enclosed in quotes when executing `show create table`; otherwise, the result cannot be used as an SQL statement.
> fix: show create table doesn't quote option keys which contains dot

- src/common/function/src/scalars/vector.rs
- src/common/function/src/scalars/vector/distance.rs
- src/common/function/src/scalars/vector/impl_conv.rs
> refactor: extract implicit conversion helper functions of vector type

- src/mito2/src/config.rs
Reduce timeout for fetching database options from 10 sec to 3 sec to avoid potention impact on ingestion rate.
> chore:  Reduce FETCH_OPTION_TIMEOUT from 10 to 3 seconds in config.rs

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
closes https://github.com/GreptimeTeam/greptimedb/issues/5104
Bump the main branch version to 0.12
> chore: bump main branch version to 0.12

- src/servers/src/http.rs
- tests-integration/tests/http.rs
Add `/ready` HTTP endpoint for health checking. See https://grafana.com/docs/loki/latest/reference/loki-http-api/#readiness-probe.
> chore: add `/ready` api for health checking

- .github/cargo-blacklist.txt
- .github/workflows/develop.yml
- Cargo.lock
- src/servers/Cargo.toml
make sure `aws-lc-sys` doesn't compile need to run `cargo tree -i aws-lc-sys -e features --target all`, but previous it's only `cargo tree -i aws-lc-sys -e features`(missing the `--target all` part), fixed that and remove a unused aws-lc-sys depend on Windows
__edited__: add to blacklist instead
> chore: fix aws_lc not in depend tree check in CI

- src/meta-srv/src/bootstrap.rs
- src/meta-srv/src/metasrv.rs
Minor change:
1. Set the `store_key_prefix` option for all KvBackend instances.
2. Print a warning log if the election service is missing on metasrv (this should only occur in testing).
> chore: set store_key_prefix for all kvbackend

- config/config.md
- config/datanode.example.toml
- config/metasrv.example.toml
- config/standalone.example.toml
- src/common/wal/src/config/raft_engine.rs
- tests-integration/tests/http.rs
Close #5106
Adjust the default value of WAL purge configuration.
> feat: adjust WAL purge default configurations

- Cargo.lock
- Cargo.toml
- src/servers/src/error.rs
- src/servers/src/http.rs
- src/servers/src/http/handler.rs
- src/sql/Cargo.toml
- src/sql/src/statements/admin.rs
- src/sql/src/statements/alter.rs
- src/sql/src/statements/copy.rs
- src/sql/src/statements/create.rs
- src/sql/src/statements/cursor.rs
- src/sql/src/statements/delete.rs
- src/sql/src/statements/describe.rs
- src/sql/src/statements/drop.rs
- src/sql/src/statements/explain.rs
- src/sql/src/statements/insert.rs
- src/sql/src/statements/option_map.rs
- src/sql/src/statements/query.rs
- src/sql/src/statements/set_variables.rs
- src/sql/src/statements/show.rs
- src/sql/src/statements/statement.rs
- src/sql/src/statements/tql.rs
- src/sql/src/statements/truncate.rs
- tests-integration/tests/http.rs
Add a new endpoint to parse SQL query (as well as TQL). Provide a structural way to process our query dialect. Let other components like the dashboard understand the query and gain the possibility to perform more user-friendly processing.
Example:
```
curl -v "0:4000/v1/sql/parse?sql=select%20*%20from%20t%3B"
{"Query":{"inner":{"with":null,"body":{"Select":{"distinct":null,"top":null,"projection":[{"Wildcard":{"opt_exclude":null,"opt_except":null,"opt_rename":null,"opt_replace":null}}],"into":null,"from":[{"relation":{"Table":{"name":[{"value":"t","quote_style":null}],"alias":null,"args":null,"with_hints":[],"version":null,"partitio …
```
> feat: implement `v1/sql/parse` endpoint to parse GreptimeDB's SQL dialect

- src/index/src/inverted_index/error.rs
- src/index/src/inverted_index/format/reader/blob.rs
- src/index/src/inverted_index/format/reader/footer.rs
- src/index/src/lib.rs
Add prefetch support to `InvertedIndexFooterReader`, and set the default prefetch size to 1KiB. To reduce the inefficiency of discrete small S3 IO operations.
> feat: add prefetch support to `InvertedIndexFooterReader` for reduced I/O time

- Cargo.lock
- src/mito2/src/cache.rs
- src/mito2/src/config.rs
- src/mito2/src/read/scan_region.rs
- src/mito2/src/sst/file.rs
- src/mito2/src/sst/index/inverted_index/applier.rs
- src/mito2/src/sst/index/inverted_index/applier/builder.rs
- src/mito2/src/sst/index/inverted_index/applier/builder/between.rs
- src/mito2/src/sst/index/inverted_index/applier/builder/comparison.rs
- src/mito2/src/sst/index/inverted_index/applier/builder/eq_list.rs
- src/mito2/src/sst/index/inverted_index/applier/builder/in_list.rs
- src/mito2/src/sst/index/inverted_index/applier/builder/regex_match.rs
- src/mito2/src/sst/index/inverted_index/creator.rs
- src/mito2/src/worker.rs
- src/puffin/Cargo.toml
- src/puffin/src/blob_metadata.rs
- src/puffin/src/file_format/reader/file.rs
- src/puffin/src/file_metadata.rs
- src/puffin/src/puffin_manager.rs
- src/puffin/src/puffin_manager/cache.rs
- src/puffin/src/puffin_manager/fs_puffin_manager.rs
- src/puffin/src/puffin_manager/fs_puffin_manager/reader.rs
Introduce `PuffinMetadataCache`
> feat: introduce `PuffinMetadataCache`

- src/common/base/src/range_read.rs
- src/mito2/src/sst/file.rs
- src/mito2/src/sst/index/inverted_index/applier.rs
- src/mito2/src/sst/index/inverted_index/creator.rs
- src/mito2/src/sst/index/store.rs
- src/mito2/src/sst/parquet/reader.rs
- src/puffin/src/partial_reader/async.rs
- src/puffin/src/puffin_manager.rs
- src/puffin/src/puffin_manager/fs_puffin_manager/reader.rs
Add the `file_size_hint` parameter to `remote_blob_reader` to optimize performance by using the file size from the manifest instead of making an additional remote request. This reduces latency for the first query when reading remote index files without any cache.
> feat(index): add `file_size_hint` for remote blob reader

- src/mito2/src/read/last_row.rs
- src/mito2/src/read/prune.rs
- src/mito2/src/read/scan_util.rs
- src/mito2/src/sst/parquet/reader.rs
This PR collects metrics from prune readers to `PartitionMetrics` so we can get prune metrics in the final debug log.
> feat: collect reader metrics from prune reader

- grafana/greptimedb.json
Adds index-related panels to standalone dashboard.
Also adds panels for object store read cache.
- bytes
- hit rate
> docs: Add index panels to standalone grafana dashboard

- src/servers/src/http/event.rs
- tests-integration/tests/http.rs
* fix loki write row len error
* The previous test passed as is because there was only one record in a request. Either the schema doesn't trigger recapacity, or it doesn't reuse the schema.
> fix: loki write row len error

- .github/workflows/nightly-build.yml
https://github.com/GreptimeTeam/greptimedb/issues/5150
The nightly build action sometimes fails due to oom.
https://github.com/GreptimeTeam/greptimedb/actions/runs/12287191091/job/34288925005
```
Compiling path-slash v0.2.1
Compiling sqlness v0.6.1
Compiling log-query v0.12.0 (/greptimedb/src/log-query)
Compiling tests-fuzz v0.12.0 (/greptimedb/tests-fuzz)
Compiling sqlness-runner v0.12.0 (/greptimedb/tests/runner)
make: *** [Makefile:206: run-it-in-container] Killed
```
> ci: use 4xlarge for nightly build

- Cargo.lock
- src/cache/Cargo.toml
- src/catalog/Cargo.toml
- src/cli/Cargo.toml
- src/client/Cargo.toml
- src/common/catalog/Cargo.toml
- src/common/datasource/Cargo.toml
- src/common/frontend/Cargo.toml
- src/common/function/Cargo.toml
- src/common/runtime/Cargo.toml
- src/file-engine/Cargo.toml
- src/flow/Cargo.toml
- src/frontend/Cargo.toml
- src/metric-engine/Cargo.toml
- src/mito2/Cargo.toml
- src/pipeline/Cargo.toml
- src/promql/Cargo.toml
- src/query/Cargo.toml
- src/script/Cargo.toml
- src/servers/Cargo.toml
- src/store-api/Cargo.toml
Remove unused dependencies using `cargo udeps --workspace --all-targets --all-features`.
> chore: remove unused dep

- .github/actions/setup-greptimedb-cluster/action.yml
- .github/actions/setup-kafka-cluster/action.yml
- .github/workflows/develop.yml
- src/metric-engine/src/engine.rs
- src/metric-engine/src/engine/catchup.rs
- src/mito2/src/worker/handle_catchup.rs
- tests-fuzz/src/utils.rs
This PR fixes the behavior of `set_region_role_state_gracefully`, ensuring it correctly sets the region role state for the metadata region. Additionally, it updates the testing setup and adjusts resource limits.
> fix: correct `set_region_role_state_gracefully` behaviors

- src/mito2/src/read/dedup.rs
- tests/cases/standalone/common/insert/merge_mode.result
- tests/cases/standalone/common/insert/merge_mode.sql
fixes https://github.com/GreptimeTeam/greptimedb/issues/5073
Before this PR, the `LastFieldsBuilder` only updated the deletion flag while initializing the builder. So, a delete op may not prevent previous rows from updating the null fields in the last row.
This PR updates the `contains_deletion` flag in `push_first_row()` to fix this issue.
> fix: deletion between two put may not work in `last_non_null` mode

- Cargo.lock
- src/index/Cargo.toml
- src/index/src/bloom_filter.rs
- src/index/src/bloom_filter/creator.rs
- src/index/src/bloom_filter/error.rs
- src/index/src/lib.rs
#5176
Add basic bloom filter creator implementation (without memory control).
> feat(bloom-filter): add basic bloom filter creator (Part 1)

- src/mito2/src/compaction.rs
- src/mito2/src/compaction/compactor.rs
- src/mito2/src/compaction/window.rs
- src/mito2/src/flush.rs
Refactor compaction from holding whole version to holding only the necessary components including ssts, options, metadata and time window.
• Introduced CompactionVersion struct to encapsulate region version details for compaction, removing dependency on VersionRef.
• Updated CompactionRequest and CompactionRegion to use CompactionVersion.
• Modified open_compaction_region to construct CompactionVersion without memtables.
• Adjusted WindowedCompactionPicker to work with CompactionVersion.
• Enhanced flush logic in WriteBufferManager to improve memory usage checks and logging.
This PR can smooth log ingestion and reduce write stalls and memory usage.
Before
After
> perf: avoid holding memtable during compaction

- src/mito2/src/read.rs
- src/mito2/src/sst/parquet.rs
chore: pub some mods
For outside projects to reuse greptimedb codes:
1. make Batch modifiable by converting it back to its BatchBuilder
2. pub ReadFormat to convert arrow RecordBatch to mito2 Batch
> refactor: produce BatchBuilder from a Batch to modify it again

- src/mito2/src/memtable.rs
- src/mito2/src/memtable/bulk.rs
- src/mito2/src/memtable/partition_tree.rs
- src/mito2/src/memtable/time_series.rs
- src/mito2/src/read/range.rs
- src/mito2/src/read/scan_region.rs
- src/mito2/src/read/scan_util.rs
- src/mito2/src/read/seq_scan.rs
- src/mito2/src/read/unordered_scan.rs
- src/mito2/src/test_util/memtable_util.rs
This PR adds a new struct `MemtableRanges` and lets the `Memtable::ranges()` method return it. Then the `ScanInput` can keep the `MemtableRanges` instead of `MemtableRef`.
This change ensures the scanner won't reference the memtables. The allocated bytes for the memtables can drop after flush. This avoids a long-running query stalling the ingestion.
> feat: do not keep MemtableRefs in ScanInput

- scripts/check-snafu.py
- src/mito2/src/error.rs
- src/mito2/src/read/scan_region.rs
- src/mito2/src/sst/parquet/reader.rs
- src/query/src/tests/time_range_filter_test.rs
- src/table/src/predicate.rs
Don't remove time filters when building time ranges in `ScanRegion`. Then the parquet reader can use the time filters to prune row groups. This PR also removes the time range from the parquet reader.
Now the scanner only uses the time range to find files to scan.
> feat: do not remove time filters in ScanRegion

- tests/cases/standalone/common/subquery/table.result
- tests/cases/standalone/common/subquery/table.sql
The order of UNION statements is not guaranteed.
```sql
mysql> SELECT * FROM (SELECT 42) UNION ALL SELECT * FROM (SELECT 43);
+-----------+
| Int64(42) |
+-----------+
|        42 |
|        43 |
+-----------+
2 rows in set (0.00 sec)
mysql> SELECT * FROM (SELECT 42) UNION ALL SELECT * FROM (SELECT 43);
+-----------+
| Int64(42) |
+-----------+
|        43 |
|        42 |
+-----------+
2 rows in set (0.00 sec)
```
Updated the SQL and result files for subquery union tests to include an ORDER BY clause, ensuring consistent result ordering. This change aligns with the test case from the DuckDB repository.
> fix(sqlness): enforce order in union tests

- grafana/greptimedb.json
https://github.com/GreptimeTeam/greptimedb/pull/5156 moves these panels to outside of the storage components row, which is unexpected.
Moves panels to the storage components row.
> docs: fix grafana dashboard row

- src/cmd/src/datanode.rs
- src/cmd/src/flownode.rs
- src/common/meta/src/cache/table/table_route.rs
- src/common/meta/src/key/table_route.rs
- src/common/meta/src/rpc/router.rs
- src/common/recordbatch/src/lib.rs
- src/common/time/src/util.rs
- src/flow/src/adapter.rs
- src/flow/src/compute/render/src_sink.rs
- src/flow/src/compute/types.rs
- src/flow/src/expr/error.rs
- src/flow/src/expr/linear.rs
- src/flow/src/plan.rs
- src/flow/src/repr/relation.rs
- src/meta-srv/src/metasrv.rs
- src/meta-srv/src/mocks.rs
- src/meta-srv/src/procedure/region_migration.rs
- src/script/src/python/ffi_types/copr.rs
- src/session/src/lib.rs
- src/sql/src/statements.rs
Always find something reporting compile errors but is used nowhere...
> refactor: remove unused symbols

- .github/workflows/develop.yml
- .github/workflows/nightly-ci.yml
- rust-toolchain.toml
- shell.nix
- ensure libgit2 used from nix environment
- use pkg-config to prevent missing library libssl
- use rust-analyzer from current nightly
> chore: make nix compilation environment config more robust

- src/meta-srv/src/procedure/region_migration.rs
- src/meta-srv/src/procedure/region_migration/close_downgraded_region.rs
- src/meta-srv/src/procedure/region_migration/migration_start.rs
- src/meta-srv/src/procedure/region_migration/open_candidate_region.rs
- src/meta-srv/src/procedure/region_migration/test_util.rs
- src/meta-srv/src/procedure/region_migration/update_metadata.rs
- src/meta-srv/src/procedure/region_migration/update_metadata/upgrade_candidate_region.rs
- src/meta-srv/src/procedure/region_migration/upgrade_candidate_region.rs
- tests-fuzz/targets/migration/fuzz_migrate_metric_regions.rs
- tests-fuzz/targets/migration/fuzz_migrate_mito_regions.rs
Although the initial implementation included rollback logic, it wasn't guaranteed to execute in all cases (e.g., when the maximum retry count was exceeded). This PR ensures that metadata rollback is reliably performed even when the maximum retry count is reached, except in rare cases where rollback is impossible, such as etcd failures.
This PR also increases the lock granularity. In multi-partition table scenarios, optimistic metadata updates were not as effective as expected and resulted in broken metadata.
> fix: ensure table route metadata is eventually rolled back on failure

- src/operator/src/insert.rs
- tests-integration/tests/grpc.rs
auto created table also needed to check for ttl==instant
- previous auto created table is not check for ttl==instant which will cause the first batch to create the table to be in the table even if ttl==instant
- fix is to also check for them so ttl=instant table wouldn't have any data anyway 
> fix: auto created table ttl check

- docker/dev-builder/ubuntu/Dockerfile
because the protobuf installed by apt is too old
> ci: install latest protobuf in dev-builder image

- Cargo.lock
- src/index/Cargo.toml
- src/index/src/bloom_filter/creator.rs
- src/index/src/bloom_filter/creator/finalize_segment.rs
- src/index/src/bloom_filter/creator/intermediate_codec.rs
- src/index/src/bloom_filter/error.rs
- src/index/src/error.rs
- src/index/src/external_provider.rs
- src/index/src/inverted_index/create/sort.rs
- src/index/src/inverted_index/create/sort/external_sort.rs
- src/index/src/inverted_index/error.rs
- src/index/src/lib.rs
- src/mito2/src/sst/index/intermediate.rs
- src/mito2/src/sst/index/inverted_index/creator/temp_provider.rs
#5176 
1. Refactor `ExternalTempFileProvider` to adapt to new index intermediates
2. Extract `FinalizedBloomFilterStorage` to a new file
3. Complete TODOs in `FinalizedBloomFilterStorage`:
1. Implement true global memory control by tracking overall memory usage for creating bloom filters through global memory usage
2. Implement disk flushing behavior during memory flush using injected `ExternalTempFileProvider`
3. Update `drain` to return `FinalizedBloomFilterSegment` from both intermediate files and memory as a stream to the upper layer
> feat(bloom-filter): add memory control for creator

- .github/workflows/release.yml
Use 8xlarge runner to avoid omm kill in the release job
https://github.com/GreptimeTeam/greptimedb/actions/runs/12427696387/job/34698091092
> chore: arm64 use 8xlarge runner

- .github/workflows/release.yml
The arm64 release job is easily killed by OOM. Changing the release.yml in the branch doesn't work.
https://github.com/GreptimeTeam/greptimedb/actions/runs/12433239151/job/34714534156
> build: use 8xlarge as arm default

- .github/workflows/nightly-ci.yml
Remove dependencies when copied from `develop.yml`
> ci: fix nightly ci task on nix build

- src/index/src/inverted_index/format/reader.rs
- src/index/src/inverted_index/format/reader/blob.rs
- src/mito2/src/cache.rs
- src/mito2/src/cache/index.rs
- src/mito2/src/cache/index/inverted_index.rs
- src/mito2/src/metrics.rs
- src/mito2/src/read/scan_region.rs
- src/mito2/src/sst/index/inverted_index/applier.rs
- src/mito2/src/sst/index/inverted_index/applier/builder.rs
- src/mito2/src/sst/index/inverted_index/creator.rs
- src/mito2/src/test_util/memtable_util.rs
#5176 
that `bloom_filter` and `inverted_index` can easily reuse the struct.
> feat(index-cache): abstract `IndexCache` to be shared by multi types of indexes

- src/catalog/src/kvbackend/table_cache.rs
- src/common/meta/src/cache/container.rs
- src/common/meta/src/cache/flow/table_flownode.rs
- src/common/meta/src/cache/registry.rs
- src/common/meta/src/cache/table/schema.rs
- src/common/meta/src/cache/table/table_info.rs
- src/common/meta/src/cache/table/table_name.rs
- src/common/meta/src/cache/table/table_route.rs
- src/common/meta/src/cache/table/table_schema.rs
- src/common/meta/src/cache/table/view_info.rs
- src/common/meta/src/key/catalog_name.rs
- src/common/meta/src/key/datanode_table.rs
- src/common/meta/src/key/flow/flow_name.rs
- src/common/meta/src/key/flow/flow_route.rs
- src/common/meta/src/key/flow/flownode_flow.rs
- src/common/meta/src/key/flow/table_flow.rs
- src/common/meta/src/key/schema_name.rs
- src/common/meta/src/key/table_name.rs
- src/common/meta/src/range_stream.rs
- src/common/meta/src/state_store.rs
- src/meta-client/src/client.rs
- src/meta-srv/src/service/store/cached_kv.rs
> refactor: remove unnecessary wrap

- Cargo.lock
- src/object-store/Cargo.toml
Switch opendal to our fork. It's based on `v0.50.2`, with one extra patch https://github.com/apache/opendal/pull/5433.
p.s.: we're not switching to `v0.51.0`, it looks like there are some ongoing huge breaking changes like https://github.com/apache/opendal/pull/3911/files?short_path=4c98752#diff-4c987528946a4644759e4f66b5027dea3cf61540dc64a73fa6c511a66b01a63f. And the concurrent limit of `list()` is missing.
> chore: bump opendal to fork version to fix prometheus layer

- config/config.md
- config/datanode.example.toml
- src/datanode/src/store.rs
- src/mito2/src/cache/file_cache.rs
- src/mito2/src/cache/write_cache.rs
- src/mito2/src/config.rs
- src/mito2/src/test_util.rs
- src/mito2/src/worker.rs
- src/object-store/src/layers.rs
- src/object-store/src/layers/lru_cache.rs
- src/object-store/src/layers/lru_cache/read_cache.rs
- src/object-store/tests/object_store_test.rs
Several changes are included in this patch.
- Change the behavior of read cache and write cache's configuration. Now user only config for the root dir for cache files. Leave the detailed subdir allocation to DB.
- Change the default path to write cache and read cache. In some cases they are considered breaking.
- Fixes the issue that write cache file's UUID are reported in prometheus layers.
Detailed explanation of path config changes:
From now on, user only config the root file for caches, with default path to `data_home`. And DB will allocate proper paths for different caches, instead of letting user to care about this. An …
> fix: correct write cache's metric labels

- src/index/src/bloom_filter/creator.rs
- src/index/src/bloom_filter/creator/finalize_segment.rs
#5176 
Add batch push to improve perf.
> feat(bloom-filter): impl batch push to creator

- .github/actions/build-windows-artifacts/action.yml
`.pdb` file is the windows debug info file(unlike linux is in a separate file)
and cargo copy it to target directory if compile on windows(see [this](https://github.com/rust-lang/cargo/pull/5179) and [cargo's source code](https://github.com/rust-lang/cargo/blob/0c157e0c481e62c09874e0169c28da4c3b1ef406/src/cargo/core/compiler/build_context/target_info.rs#L503))
- very helpful when debuggin on windows
- doesn't take up much space(binary ~238 MB, pdb ~60MB) and merely few MB after compressed
> ci: upload .pdb files too for better windows debug

- config/config.md
- config/frontend.example.toml
- config/standalone.example.toml
- src/cmd/src/standalone.rs
- src/frontend/src/error.rs
- src/frontend/src/frontend.rs
- src/frontend/src/instance.rs
- src/frontend/src/instance/builder.rs
- src/frontend/src/instance/grpc.rs
- src/frontend/src/instance/influxdb.rs
- src/frontend/src/instance/log_handler.rs
- src/frontend/src/instance/opentsdb.rs
- src/frontend/src/instance/otlp.rs
- src/frontend/src/instance/prom_store.rs
- src/frontend/src/lib.rs
- src/frontend/src/limiter.rs
- src/servers/src/error.rs
Introduce the `Limiter` in frontend to limit the requests by in-flight write bytes size.
> feat: introduce the Limiter in frontend to limit the requests by in-flight write bytes size.

- src/flow/src/adapter.rs
- src/flow/src/adapter/flownode_impl.rs
- src/flow/src/compute/types.rs
- src/flow/src/expr/error.rs
- src/flow/src/metrics.rs
- src/flow/src/server.rs
Add some basic metrics for flownode to improve its observability
> feat: add some critical metrics to flownode

- src/servers/src/error.rs
- src/servers/src/http/event.rs
* Add an error message indicating at which stage of pipeline execution the error occurred.
> chore: add more info for pipeline dryrun API

- src/mito2/src/read/prune.rs
- src/mito2/src/sst/parquet/reader.rs
> feat(mito): add bloom filter read metrics

- .github/workflows/develop.yml
- src/common/meta/src/kv_backend/postgres.rs
- src/meta-srv/Cargo.toml
- src/meta-srv/src/bootstrap.rs
- src/meta-srv/src/election.rs
- src/meta-srv/src/election/etcd.rs
- src/meta-srv/src/election/postgres.rs
- src/meta-srv/src/error.rs
- src/meta-srv/src/handler/on_leader_start_handler.rs
As title. Part of #5208 
Previous pr #5201 
A candidate first write a (candidate_key, node info + expire time) pair into the pg kv backend, and regularly check the expire time.
- If the value expired, raise an error and re-registrate
- If not, just renew the expire time
For `all_candidates`, just get all candidate using candidate_key_prefix, and filter the expired value.
> feat: init PgElection with candidate registration

- src/object-store/src/layers.rs
Since switching to openDAL's Prometheus layer, we have not been able to set the layer multiple times, causing the path label to include the index`s uuid symbol, which causes the size of the label to explode.
Disable the path label for now because we're not using it for debugging anyway. We may reopen it later if openDAL supports dynamic path trim or some hook to decide path label dynamically.
> fix: disable path label in opendal for now

- .github/workflows/develop.yml
- src/mito2/src/cache.rs
- src/mito2/src/cache/write_cache.rs
- src/mito2/src/compaction.rs
- src/mito2/src/compaction/compactor.rs
- src/mito2/src/engine.rs
- src/mito2/src/read/last_row.rs
- src/mito2/src/read/projection.rs
- src/mito2/src/read/range.rs
- src/mito2/src/read/scan_region.rs
- src/mito2/src/read/seq_scan.rs
- src/mito2/src/read/unordered_scan.rs
- src/mito2/src/sst/parquet.rs
- src/mito2/src/sst/parquet/file_range.rs
- src/mito2/src/sst/parquet/reader.rs
- src/mito2/src/sst/parquet/row_group.rs
Some changes revert https://github.com/GreptimeTeam/greptimedb/pull/5135/
This PR implements a `CompactionStrategy` to replace `Option<CacheManagerRef>` so we can control how compaction uses caches.
- For queries, the strategy forwards all operations to the cache manager.
- The strategy only uses the write cache and the metadata cache for compactions.
- The `Disabled` strategy means disable all caches.
> fix: implement a CacheStrategy to ensure compaction use cache correctly

- src/mito2/src/cache/index/bloom_filter_index.rs
- src/mito2/src/cache/index/inverted_index.rs
- src/mito2/src/sst/index/bloom_filter/applier.rs
- src/mito2/src/sst/index/inverted_index/applier.rs
#5176 
* skip applying for non-indexed columns
* provide the correct blob size
> fix(bloom-filter): skip applying for non-indexed columns

- src/mito2/src/engine/compaction_test.rs
- src/mito2/src/memtable.rs
- src/mito2/src/memtable/time_partition.rs
- src/mito2/src/memtable/version.rs
- src/mito2/src/region/version.rs
- src/mito2/src/test_util/memtable_util.rs
fixes https://github.com/GreptimeTeam/greptimedb/issues/5098
This PR tries to create a new mutable memtable with the latest compaction time window. It sets the `part_duration` of the `TimePartitions` when a region freezes its memtables.
> feat: update partition duration of memtable using compaction window

- src/mito2/src/access_layer.rs
- src/mito2/src/cache/write_cache.rs
- src/mito2/src/compaction/compactor.rs
- src/mito2/src/compaction/test_util.rs
- src/mito2/src/compaction/twcs.rs
- src/mito2/src/engine/basic_test.rs
- src/mito2/src/flush.rs
- src/mito2/src/manifest/tests/checkpoint.rs
- src/mito2/src/memtable.rs
- src/mito2/src/memtable/key_values.rs
- src/mito2/src/memtable/partition_tree.rs
- src/mito2/src/memtable/time_series.rs
- src/mito2/src/sst/file.rs
- src/mito2/src/sst/file_purger.rs
- src/mito2/src/sst/parquet.rs
- src/mito2/src/sst/parquet/format.rs
- src/mito2/src/sst/parquet/writer.rs
- src/mito2/src/test_util/sst_util.rs
- src/mito2/src/test_util/version_util.rs
The sequence is `u64` and is allocated with write request. They are different from row to row and thus has bad compression efficiency in both CPU and space. We can assign the greatest sequence number to the file to reduce this overhead while keeping this mechanism works.
In TSBS test scenario with 100M rows, it can save 48MB of disk space. And in the metric monitor scenario, it can save up to 50%~60% in file size. We can also observe an (unstable) flush performance improvement.
> feat: override `__sequence` on creating SST to save space and CPU

- .github/actions/build-images/action.yml
- .github/actions/build-linux-artifacts/action.yml
- .github/actions/build-windows-artifacts/action.yml
- .github/workflows/develop.yml
- .github/workflows/nightly-ci.yml
- .github/workflows/release.yml
- docker/buildx/centos/Dockerfile
- docker/buildx/ubuntu/Dockerfile
- docker/ci/centos/Dockerfile
- docker/ci/ubuntu/Dockerfile
This patch removes pyo3 build tasks in release and unit tests. Also removed python dependencies from docker base image. dev-builders stay untouched.
> ci: disable pyo3 build tasks

- src/log-query/src/log_query.rs
- src/query/src/log_query/planner.rs
Implement pagination with limit and offset parameters. A similar use case in Elasticsearch is `/my-index-000001/_search?from=40&size=20`
This is a breaking change but since `log-query` is highly experimental I only categorize it as a normal change.
> feat(log-query): implement pagination with limit and offset parameters

- src/servers/src/hint_headers.rs
Another hint format: `x-greptime-hints: auto_create_table=true, ttl=7d`.
Currently, the following two formats are supported:
1. x-greptime-hint-xxx: value
2. x-greptime-hints: xxx=yyy, aaa=bbb
This PR implements the second format and we may remove support for the first one in the future as it may lead too many keys.
This PR is a continuation of #5128.
> feat: hints all in one

- src/cli/Cargo.toml
- src/common/meta/src/key/schema_metadata_manager.rs
- src/datanode/src/datanode.rs
- src/mito2/src/compaction.rs
- src/mito2/src/engine/alter_test.rs
- src/mito2/src/engine/append_mode_test.rs
- src/mito2/src/engine/compaction_test.rs
- src/mito2/src/engine/drop_test.rs
- src/mito2/src/engine/edit_region_test.rs
- src/mito2/src/engine/filter_deleted_test.rs
- src/mito2/src/engine/flush_test.rs
- src/mito2/src/engine/merge_mode_test.rs
- src/mito2/src/engine/open_test.rs
- src/mito2/src/engine/parallel_test.rs
- src/mito2/src/engine/prune_test.rs
- src/mito2/src/engine/row_selector_test.rs
- src/mito2/src/engine/truncate_test.rs
- src/mito2/src/test_util.rs
These are two cases that `testing` features leaks to production code. For cli, I just make `testing` usable for production. 
To avoid leaking kv_backend into production code in `SchemaMetadataManager`, this patch moves `kv_backend` out of the struct and make it a argument of testing function.
> fix: correct invalid testing feature gate usage

- Cargo.lock
- src/common/runtime/Cargo.toml
close #5263 
- just fix bug to compile successfully
> fix: import tokio-metrics and tokio-metrics-collector

- config/config.md
- config/datanode.example.toml
- config/standalone.example.toml
- src/mito2/src/config.rs
- tests-integration/tests/http.rs
As title. IO size of inverted index content is relatively small, usually single fst/bitmap. With 8MB page size, cache miss is expensive.
> refactor: adjust index cache page size

- src/flow/src/adapter/flownode_impl.rs
- src/flow/src/transform/aggr.rs
- tests/cases/standalone/common/flow/flow_insert.result
- tests/cases/standalone/common/flow/flow_insert.sql
fix a bug where flow misuse the schema to pass in when write requests are reordered
> fix: flow handle reordered inserts

- Cargo.lock
- Cargo.toml
- src/common/grpc-expr/src/alter.rs
- src/common/grpc-expr/src/insert.rs
- src/common/grpc-expr/src/util.rs
- src/common/meta/src/ddl/alter_logical_tables/update_metadata.rs
- src/common/meta/src/ddl/alter_table.rs
- src/common/meta/src/ddl/alter_table/region_request.rs
- src/common/meta/src/ddl/alter_table/update_metadata.rs
- src/common/meta/src/ddl/test_util/alter_table.rs
- src/common/meta/src/ddl/tests/alter_logical_tables.rs
- src/common/meta/src/ddl/tests/alter_table.rs
- src/mito2/src/worker/handle_alter.rs
- src/mito2/src/worker/handle_manifest.rs
- src/operator/src/expr_factory.rs
- src/operator/src/insert.rs
- src/operator/src/statement/ddl.rs
- src/store-api/src/region_request.rs
- src/table/src/metadata.rs
- src/table/src/requests.rs
- tests-integration/src/grpc.rs
- tests-integration/tests/grpc.rs
- fixes https://github.com/GreptimeTeam/greptimedb/issues/5248
- the proto branch: https://github.com/GreptimeTeam/greptime-proto/pull/207
This PR adds the `add_if_not_exists` flag to the AddColumn alter kind and validates the alteration to the table in the prepare step of the AlterTableProcedure. Before this PR, the procedure may not be able to build table info in the update metadata step, which causes regions to have an inconsistent schema with the meta server.
It also fixes an issue that the procedure always alters tables without `add_if_not_exists` which is different from the behavior of auto alteration.
Please convert it to a draft if some of the following conditions are not …
> feat: support add if not exists in the gRPC alter kind

- scripts/check-snafu.py
- src/common/datasource/tests/orc/write.py
This patch mainly to speed up `make fmt-check` from 46s to 4s in my local machine(mac m3 16G)
Two things done for the speed
1. using  from multiprocessing import Pool for the branch_name_snafu check
2. load all the files content to the memory instead of read them twice in the python script
This patch also fmt these two python files in the repo(using black)
about the speed you can check the screenshot below
first using pool from 46 -> 12
then load the content to the memory from 12 -> 4
> fix: better fmt check from 40s to 4s

- src/mito2/src/sst/index/intermediate.rs
- fixes #5269 
- Changed logging level from `warn` to `debug` for unexpected directory entries in index creation.
> chore: suppress list warning

- config/config.md
- config/standalone.example.toml
https://github.com/GreptimeTeam/greptimedb/pull/5227/
https://github.com/GreptimeTeam/greptimedb/pull/5227/ forgot to update the standalone example.
> docs: update standalone example

- src/frontend/src/instance.rs
- src/operator/src/statement.rs
- src/operator/src/statement/copy_query_to.rs
- src/operator/src/statement/copy_table_to.rs
- src/sql/src/parsers/copy_parser.rs
- src/sql/src/statements/copy.rs
- src/table/src/requests.rs
- tests/cases/standalone/common/copy/copy_to_fs.result
- tests/cases/standalone/common/copy/copy_to_fs.sql
https://github.com/GreptimeTeam/greptimedb/issues/5075
support `CopyQueryTo`
```sql
COPY (SELECT * FROM tbl WHERE ...) TO '/xxx/xxx/output.parquet' WITH (FORMAT = 'parquet');
```
example:
```shell
COPY (select host, cpu, ts from demo where host = 'host2') TO '/tmp/export/demo.parquet';
Affected Rows: 1
```
> feat: impl COPY a query resultset to external file

- Cargo.lock
- tests-fuzz/Cargo.toml
- tests-fuzz/targets/failover/fuzz_failover_metric_regions.rs
- tests-fuzz/targets/failover/fuzz_failover_mito_regions.rs
- tests-fuzz/targets/migration/fuzz_migrate_metric_regions.rs
- tests-fuzz/targets/migration/fuzz_migrate_mito_regions.rs
After region migrations, the system needs to wait at most one region lease duration to ensure all regions' leases are renewed.
> fix(fuzz): ensure all regions leases are renewed

- src/pipeline/src/etl/transform/transformer/greptime/coerce.rs
- src/pipeline/tests/timestamp.rs
As title suggests. This patch allows pipeline definition like:
```yaml
processors:
transform:
- fields:
- publisher_id
type: uint16
index: tag
- fields:
- action
- side
type: string
- fields:
- depth
- flags
type: uint8
- fields:
- instrument_id
- size
- sequence
type: uint32
- fields:
- price
type: uint64
- fields:
- ts_event
type: timestamp,nanosecond
index: timestamp
- fields:
- ts_recv
type: timestamp,nanosecond
```
Processors should be no longer required for generating timestamps from integers
> feat(pipeline): allow coerce timestamp from integer values

- docker/dev-builder/ubuntu/Dockerfile
as `aws-lc-sys` is in our blacklist now, there is no need to use a specific gcc version for it, so remove this line of forcing use gcc-10
> chore: cleanup dockerfile

- src/servers/src/http.rs
- tests-integration/tests/http.rs
The default decompression layer will intercept unknown encodings like `snappy`. We have to manually set it to `true` for encodings like `snappy` to pass through.
> fix: pass unknown encoding in decompression layer

- .github/actions/build-linux-artifacts/action.yml
- .github/workflows/nightly-ci.yml
- config/config.md
- config/metasrv.example.toml
- src/cmd/src/metasrv.rs
- src/meta-srv/src/election/postgres.rs
- src/meta-srv/src/metasrv.rs
1. correct `backend` field configuration
2. correct `set idle_in_transaction_session_timeout` statement
3. add `#[serde(rename_all = "snake_case")]` macro to the `BackendImpl` enum
4. enable `pg_backend` by default in releasing
> fix(pg_backend): correct `set idle_in_transaction_session_timeout` statement

- README.md
Since we enable `mem-prof` feature by default, C/C++ building dependencies are mandatory for building GreptimeDB.
> docs: Added C/C++ building essentials to the prerequisites list

- .github/workflows/nightly-ci.yml
Remove the `pg_kvbackend` feature gate in the Windows CI. It is unlikely that anyone would run a distributed GreptimeDB cluster in a Windows environment.
> chore(nightly-ci): remove `pg_kvbackend` feature gate in windows ci

- src/operator/src/insert.rs
- src/operator/src/req_convert/insert/row_to_region.rs
- src/partition/src/splitter.rs
If there's only one region in the table, skip spliting insert request rows by partition rules.
Saves about 0.4% cpu on our testing device.
> refactor: optimize out partition split insert requests

- Cargo.lock
- src/servers/Cargo.toml
- src/servers/benches/loki_labels.rs
- src/servers/src/error.rs
- src/servers/src/http/loki.rs
- tests-integration/tests/http.rs
#5287 
Parse Loki labels directly in protobuf write path instead of converting and decoding using JSON5, roughly 10x better performance-wise while ensuring correctness.
```
loki_labels/json5       time:   [3.9928 µs 3.9939 µs 3.9950 µs]
Found 4 outliers among 100 measurements (4.00%)
2 (2.00%) low mild
2 (2.00%) high severe
loki_labels/hand_parse  time:   [392.19 ns 392.54 ns 392.93 ns]
Found 2 outliers among 100 measurements (2.00%)
1 (1.00%) high mild
1 (1.00%) high severe
```
> perf: parse Loki labels in protobuf write path

- src/common/function/src/system.rs
- src/common/function/src/system/database.rs
- tests/cases/standalone/common/system/pg_catalog.result
- tests/cases/standalone/common/system/pg_catalog.sql
This commit is part of support DBeaver that support function select session_user like postgres did.
first part of https://github.com/GreptimeTeam/greptimedb/issues/5271#issuecomment-2575070285
will support `select pg_catalog.pg_database;` in next patch
screen shot;
> feat: support `select session_user;`

- Cargo.lock
- src/servers/src/elasticsearch.rs
- src/servers/src/error.rs
- src/servers/src/http.rs
- src/servers/src/http/event.rs
- src/servers/src/lib.rs
- src/servers/src/metrics.rs
- src/session/src/context.rs
- tests-integration/tests/http.rs
1. Support elasticsearch `_bulk` API to ingest logs;
2. Mock some elasticsearch APIs that are used for Logstash;
> feat: support elasticsearch `_bulk` API to ingest logs

- config/config.md
- config/metasrv.example.toml
- src/meta-srv/src/bootstrap.rs
- src/meta-srv/src/election/postgres.rs
- src/meta-srv/src/metasrv.rs
#5208 
As title. I init a separate config, but seems it's better to place the table name under the previous kvbackend config?
> feat(config): make table name of pg backend configurable

- README.md
- docker/buildx/centos/Dockerfile
- docker/dev-builder/android/Dockerfile
- docker/dev-builder/centos/Dockerfile
- docker/dev-builder/ubuntu/Dockerfile
- docker/python/requirements.txt
Since all python feature had been dropped from #5321 
Docker side and requirements can be drop too, also drop  `rustpython` mention in doc. 
> fix: drop all python embedding code for docker and doc

- src/meta-srv/Cargo.toml
- src/meta-srv/src/metasrv.rs
- src/servers/Cargo.toml
- src/servers/src/grpc.rs
#5322
Disable local IP detection feature in Android binary
> build: disable local IP detection feature in Android binary

- src/frontend/src/instance.rs
- src/operator/src/statement.rs
- src/operator/src/statement/show.rs
- src/query/src/sql.rs
- src/sql/src/parsers/show_parser.rs
- src/sql/src/statements/show.rs
- src/sql/src/statements/statement.rs
- tests/cases/standalone/common/system/pg_catalog.result
- tests/cases/standalone/common/system/pg_catalog.sql
part of https://github.com/GreptimeTeam/greptimedb/issues/5271
for now `pg_database` is better to hold waiting for the upstream https://github.com/apache/datafusion/pull/13489
this patch support pg `show search_path` for now seems no search path for greptime so use database instead
> feat: add show search_path for pg

- src/operator/src/expr_factory.rs
- src/sql/src/parser.rs
- src/sql/src/parsers/alter_parser.rs
- src/sql/src/parsers/show_parser.rs
- src/sql/src/statements/alter.rs
- src/sql/src/statements/transform/type_alias.rs
- tests-integration/src/tests/instance_test.rs
- tests/cases/standalone/common/alter/add_col.result
- tests/cases/standalone/common/alter/add_col.sql
> feat: support alter add multiple columns

- Cargo.lock
- Cargo.toml
- src/common/wal/Cargo.toml
- src/servers/Cargo.toml
update rustls due to https://github.com/GreptimeTeam/greptimedb/security/dependabot/48
note that is a few depend on even older version of rustls, which will not be update in this PR since they are safe, see
[dep.tree.txt](https://github.com/user-attachments/files/18372417/dep.tree.txt) for detailed depend tree
> chore: update rustls

- src/operator/src/statement.rs
- src/operator/src/statement/set.rs
- tests/cases/standalone/common/system/pg_catalog.result
- tests/cases/standalone/common/system/pg_catalog.sql
other part of https://github.com/GreptimeTeam/greptimedb/pull/5328
> feat: add set search_path to 'xxx' for pg

- src/object-store/src/lib.rs
found when reading the storage code.
the opendal method `pub use opendal::raw::{normalize_path as raw_normalize_path ` seems useless for now.
I search the commit this method bring from https://github.com/GreptimeTeam/greptimedb/pull/1268
and drop from https://github.com/GreptimeTeam/greptimedb/pull/2777
and I `grep` the code base seems there no other place use it, so maybe it can drop now.
> chore: drop useless import raw_normalize_path in object-store lib

- src/mito2/src/sst/index.rs
Skip building indexer when `indexed_column_ids` are empty to avoid unnecessary primary key decoding overhead during index updating.
> fix: skip building indexer when `indexed_column_ids` are empty

- src/servers/src/elasticsearch.rs
- src/servers/src/http.rs
- src/servers/src/http/event.rs
- tests-integration/tests/http.rs
1. Take `_index` from bulk requests as greptimedb table;
2. Add `${index}/_bulk` API;
3. Add `LogIngestRequest` and refactor `ingest_logs_inner` to support ingest logs into multiple tables by one request;
> refactor(elasticsearch): use `_index` as greptimedb table in log ingestion and add `/${index}/_bulk` API

- .github/workflows/develop.yml
- .github/workflows/nightly-ci.yml
- Cargo.lock
- src/common/pprof/Cargo.toml
- tests-fuzz/Cargo.toml
- tests-fuzz/src/utils.rs
- tests-fuzz/src/utils/cluster_info.rs
- tests-fuzz/src/utils/partition.rs
- tests-fuzz/src/validator/column.rs
- tests-fuzz/src/validator/row.rs
- tests-fuzz/src/validator/table.rs
- tests-integration/Cargo.toml
Update sqlx and some other dependencies to fix security report.
This patch also updates CI:
- run `develop.yml` nightly for cache generation on main
- only generate cache on main branch
- cache everything (our code and dependencies)
> fix: security fix, sqlx, hashbrown, idna and CI updates

- .github/workflows/release.yml
- cyborg/bin/bump-doc-version.ts
ci: automatically bump doc version when release GreptimeDB
> ci: automatically bump doc version when release GreptimeDB

- src/common/meta/src/ddl/create_logical_tables.rs
- src/common/meta/src/ddl/create_logical_tables/check.rs
- src/common/meta/src/ddl/create_logical_tables/region_request.rs
- src/common/meta/src/ddl/create_logical_tables/update_metadata.rs
- src/meta-srv/src/procedure/tests.rs
Avoid sending create table requests for already existing tables
> chore: avoid sending create table requests for already existing tables

- src/sql/src/error.rs
- src/sql/src/statements.rs
- tests/cases/standalone/common/insert/insert_wrong_type.result
- tests/cases/standalone/common/insert/insert_wrong_type.sql
close #5338 by ensure on interval type
screen shot after this patch.
> fix: panic and interval when do not have keyword `interval`

- Makefile
Seems fuzz and fuzz-ls do not follow the `make help` show rules, this patch fix it. 
Screenshot
before:
after:
> fix: better makefile help show, show fuzz and fuzz-ls also

- .github/workflows/dependency-check.yml
- .github/workflows/develop.yml
- rust-toolchain.toml
- shell.nix
It takes 50% of time to collect coverage information so in this patch I attempt to disable coverage report for pull request and only update it in merge queue. 
> ci: do not collect coverage from pull request any more

- src/servers/src/http.rs
- src/servers/src/http/dashboard.rs
- tests-integration/tests/http.rs
Our dashboard now requires trailing slash for `/dashboard/` path. This path redirects `/dashboard` to `/dashboard/`.
> fix: redirect /dashboard to /dashboard/

- src/metric-engine/src/metadata_region.rs
- src/mito2/benches/memtable_bench.rs
- src/mito2/src/engine/projection_test.rs
- src/mito2/src/flush.rs
- src/mito2/src/memtable.rs
- src/mito2/src/memtable/bulk.rs
- src/mito2/src/memtable/bulk/part.rs
- src/mito2/src/memtable/bulk/part_reader.rs
- src/mito2/src/memtable/partition_tree.rs
- src/mito2/src/memtable/partition_tree/tree.rs
- src/mito2/src/memtable/time_partition.rs
- src/mito2/src/memtable/time_series.rs
- src/mito2/src/read.rs
- src/mito2/src/read/scan_region.rs
- src/mito2/src/test_util/memtable_util.rs
- src/store-api/src/storage/requests.rs
as title, this allow snapshot read, however the interface for designate whether should snapshot read is not part of this pr
> feat: filter batch by sequence in memtable

- Cargo.lock
- Cargo.toml
- src/api/src/v1/column_def.rs
- src/common/grpc-expr/src/alter.rs
- src/common/grpc-expr/src/error.rs
- src/common/meta/src/ddl/alter_table/region_request.rs
- src/common/meta/src/ddl/alter_table/update_metadata.rs
- src/datatypes/src/schema/column_schema.rs
- src/mito2/src/engine/alter_test.rs
- src/operator/src/expr_factory.rs
- src/query/src/sql/show_create_table.rs
- src/sql/src/parsers/alter_parser.rs
- src/sql/src/statements.rs
- src/sql/src/statements/alter.rs
- src/store-api/src/metadata.rs
- src/store-api/src/region_request.rs
- src/table/src/metadata.rs
- src/table/src/requests.rs
- tests/cases/standalone/common/alter/change_col_inverted_index.result
- tests/cases/standalone/common/alter/change_col_inverted_index.sql
This pr enables `alter table x modify column set/ unset inverted index syntax`.
1. modify index proto has been refactored.
2. parse support the new syntax with refactoring.
3. metadata update with alter inverted index.
> feat: Alter inverted index

- config/config.md
- config/flownode.example.toml
- src/cmd/src/flownode.rs
- src/flow/src/adapter.rs
- src/flow/src/server.rs
- tests/runner/src/env.rs
as title, only have default routers and metrics handler, can `curl` `/health` and `/metrics` and get expected metrics info with flownode
> feat: flow's http server

- src/pipeline/src/etl/error.rs
- src/pipeline/src/etl/field.rs
- src/pipeline/src/etl/processor.rs
- src/pipeline/src/etl/processor/digest.rs
- src/pipeline/tests/pipeline.rs
A new pipeline processor to digest raw log string and output the log template without variables.
> feat: `digest` pipeline processor

- src/servers/src/mysql/federated.rs
Encounter this panic with MySQL client:
```
2025-01-15T09:24:45.917687Z ERROR on_query{protocol="mysql"}:mysql::do_query: common_telemetry::panic_hook: panicked at src/servers/src/mysql/federated.rs:276:32:
byte index 6 is not a char boundary; it is inside '；' (bytes 4..7) of `exit；`
```
Here the query contains a full-width character and causes panic. This is because `str` type in rust doesn't perform utf-8 aware indexing but based on plain bytes.
> fix: panic when received invalid query string

- src/mito2/src/compaction.rs
- src/mito2/src/compaction/compactor.rs
- src/mito2/src/compaction/task.rs
- src/mito2/src/engine/open_test.rs
- src/mito2/src/worker/handle_compaction.rs
Parallel inside one compaction task may increase the memory consumption. This patch changes the default value as a quick fix and a follow-up task exposes it to `ADMIN COMPACT` command. 
> feat: set default compaction parallelism

- tests-integration/tests/http.rs
put content_cache_page_size to correct place
https://github.com/GreptimeTeam/greptimedb/pull/5381 breaks the config api test.
update expected config in `test_config_api`.
> test: fix config api test

- src/metric-engine/src/metrics.rs
- src/mito2/src/metrics.rs
- src/mito2/src/read/scan_util.rs
This PR fixes an issue that `PartitionMetrics` doesn't increase the in progress scan gauge.
It also adjusts some histogram buckets of mito and metric engine.
> fix: increase in progress scan gauge and adjust histogram buckets

- .github/actions/build-linux-artifacts/action.yml
- https://github.com/GreptimeTeam/greptimedb/pull/5256/
- https://github.com/GreptimeTeam/greptimedb/issues/5387
Always build standard greptime binary.
> ci: always build standard db

- src/api/src/v1/column_def.rs
- src/common/grpc-expr/src/util.rs
- src/common/query/src/logical_plan/expr.rs
- src/table/src/metadata.rs
Some of them maybe need to disscuss.
Also using RAPX like #5383 
I try to drop some of un nucessary `clone` like I did in OpenDAL -> https://github.com/apache/opendal/pull/5554
but RAPX seems still have some problems when use `-opt` with greptime, I will try to figure why
some static check warning like below, if you have interest, you can also give a try with my patch
```
| 31 | let ts_type = ts_schema.data_type.clone(); | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ Cloning happens here. 32 | let time_range = time_range?; ... 35 | .and_then(|start| ts_type.try_cast(Value::Timestamp(start))); 36 | let end = time_range | ^ 37 | | .end() 38 | | .and_then(|end| ts_type.try_cast(Value::Timestamp(end))); | |_________________________________________________^ Used here | = help: Use borrowings instead.
```
I …
> refactor: drop useless clone for some better performance using static chek

- src/mito2/src/engine/compaction_test.rs
- src/mito2/src/region/version.rs
This PR always overwrites the compaction time window by the window size in the TWCS options if it is available.
After this PR, a SWCS compaction will not update the time window if we set the TWCS window size option. We always respect the window size specified in the region option.
> feat: overwrites inferred compaction window by region options

- src/mito2/src/region/options.rs
- Modified the default value of `max_output_file_size` in `TwcsOptions` to `Some(ReadableSize::gb(2))` in `src/mito2/src/region/options.rs`.
> chore: change default compaction output size limit to 2GB

- src/flow/src/adapter.rs
previously, if a flow& it's sink table is dropped, but in flownode's output buf there is still leftover for this flow, calling flush_flow here will cause a bug which when send insert request back, can't found the sink table(as expected because sink table is dropped)
this is fixed now by check if table no longer exist and not make send back request failed
related failed test: https://github.com/GreptimeTeam/greptimedb/actions/runs/12825330060/job/35763543123
> fix(flow): deal with flow drop leftover

- Cargo.lock
- config/config.md
- config/datanode.example.toml
- config/standalone.example.toml
- src/cmd/Cargo.toml
- src/cmd/tests/load_config_test.rs
- src/datanode/src/config.rs
- src/datanode/src/datanode.rs
- src/metric-engine/Cargo.toml
- src/metric-engine/src/config.rs
- src/metric-engine/src/engine.rs
- src/metric-engine/src/engine/create.rs
- src/metric-engine/src/lib.rs
- src/metric-engine/src/test_util.rs
#5282 
Introduce `experimental_sparse_primary_key_encoding` to `MetricEngineConfig`
> feat(metric-engine): introduce `experimental_sparse_primary_key_encoding` to `MetricEngineConfig`

- tests/runner/src/main.rs
This patch gives better sqness test show when succeed and failed by replacing `unwrap();`
after this patch:
succeed:
failed:
> fix: better sqlness show, replace the unwarp with better show message

- src/servers/src/http.rs
- src/servers/src/http/authorize.rs
- src/servers/tests/http/authorize.rs
- **Files Modified**: `http.rs`, `authorize.rs`, `authorize.rs` (tests)
- **Key Changes**:
- Introduced a custom authorization header `x-greptime-auth` in `http.rs`.
- Updated authorization logic in `authorize.rs` to support both `x-greptime-auth` and the standard `Authorization` header.
- Enhanced test cases in `authorize.rs` to validate the new custom header functionality.
> chore(http): change authorization header

- src/servers/src/otlp/trace.rs
- src/servers/src/otlp/trace/span.rs
- tests-integration/tests/http.rs
Although OTeL doesn't treat `service.name` differently, the popular GUI tool for displaying traces, [Jaeger](https://www.jaegertracing.io/), seems to have a dedicated API for querying all distinct service names. In that case, we need to extract the `service_name` in advance for indexing.
> chore: extract `service_name` in OTLP traces by default

- src/mito2/src/compaction.rs
- src/mito2/src/error.rs
This PR fixes the issue that manually triggered compaction will be ignored when compaction is in progress.
> fix: avoid suppress manual compaction

- src/mito2/src/memtable/bulk/context.rs
- src/mito2/src/memtable/bulk/part.rs
- src/mito2/src/memtable/partition_tree.rs
- src/mito2/src/memtable/partition_tree/tree.rs
- src/mito2/src/memtable/time_series.rs
- src/mito2/src/read.rs
- src/mito2/src/read/compat.rs
- src/mito2/src/read/projection.rs
- src/mito2/src/read/scan_region.rs
- src/mito2/src/row_converter.rs
- src/mito2/src/row_converter/dense.rs
- src/mito2/src/row_converter/sparse.rs
- src/mito2/src/sst/index/bloom_filter/creator.rs
- src/mito2/src/sst/index/codec.rs
- src/mito2/src/sst/index/inverted_index/creator.rs
- src/mito2/src/sst/parquet/file_range.rs
- src/mito2/src/sst/parquet/format.rs
- src/mito2/src/sst/parquet/reader.rs
- src/mito2/src/test_util/memtable_util.rs
- src/mito2/src/test_util/sst_util.rs
#5282 
1. Replaced `DensePrimaryKeyCodec` with `Arc<dyn PrimaryKeyCodec>` to enable support for various primary key codec implementations.
2. Introduced `RewritePrimaryKey` to ensure backward compatibility.
> feat: replace `DensePrimaryKeyCodec` with `Arc<dyn PrimaryKeyCodec>`

- src/datatypes/src/schema/column_schema.rs
- src/datatypes/src/schema/constraint.rs
- src/flow/src/adapter/flownode_impl.rs
- src/flow/src/adapter/node_context.rs
- src/flow/src/adapter/table_source.rs
- src/flow/src/adapter/util.rs
- src/mito2/src/compaction.rs
- src/mito2/src/compaction/compactor.rs
- src/mito2/src/compaction/task.rs
- src/mito2/src/engine/compaction_test.rs
- src/mito2/src/engine/open_test.rs
- src/mito2/src/error.rs
- src/mito2/src/region/version.rs
- src/mito2/src/request.rs
- src/mito2/src/worker/handle_compaction.rs
- src/operator/src/insert.rs
- src/operator/src/req_convert/insert.rs
- src/operator/src/req_convert/insert/fill_impure_default.rs
- src/operator/src/req_convert/insert/row_to_region.rs
- src/operator/src/req_convert/insert/stmt_to_region.rs
- src/partition/src/splitter.rs
- tests/cases/standalone/common/flow/flow_ins_default.result
- tests/cases/standalone/common/flow/flow_ins_default.sql
https://github.com/GreptimeTeam/greptimedb/issues/5421
Cherry-pick flow & compaction fixes to v0.11.3
Compaction:
- https://github.com/GreptimeTeam/greptimedb/pull/5371
- https://github.com/GreptimeTeam/greptimedb/pull/5396
- https://github.com/GreptimeTeam/greptimedb/pull/5399
Flow:
- https://github.com/GreptimeTeam/greptimedb/pull/5307
- Also need this to avoid conflicts: https://github.com/GreptimeTeam/greptimedb/pull/5298
> fix: cherry-pick flow & compaction fixes

- Cargo.lock
- src/servers/src/http/logs.rs
- tests-integration/Cargo.toml
- tests-integration/src/test_util.rs
- tests-integration/tests/http.rs
https://github.com/GreptimeTeam/greptimedb/issues/5421
Cherry-pick:
- fix(log-query): panic on prometheus (#5429)
> fix: cherry-pick log query fix to v0.11.3

- grafana/greptimedb-cluster.json
- Fixed a typo in the metric name on the default Grafana dashboard to ensure correct display and querying.
- Added a new metric for the Prometheus-compatible API, as only the PromQL endpoint HTTP metric was previously shown. This enhancement provides better visibility and monitoring of the Prometheus-compatible API.
> feat: Address different Metrics for Prometheus queries in the Dashboard and fix typo in metric name

- src/operator/src/insert.rs
- src/operator/src/metrics.rs
Previous implementation will wait for flow to the response before sending request to datanode. This patch makes them fully asynchronously. 
> feat: mirror insert request to flownode in async

- src/servers/src/http/result/prometheus_resp.rs
> chore: avoid necessary cloning

- src/servers/src/postgres/fixtures.rs
since https://github.com/GreptimeTeam/greptimedb/pull/5417 had been merged the case is no longer needed.
just found by https://github.com/GreptimeTeam/greptimedb/pull/5448
> fix: no need for special case since datafusion updated

- src/datatypes/src/vectors/primitive.rs
- src/mito2/src/memtable/time_series.rs
Another 5%+ optimization on TSBS write. Given the new implementation (zero-copy in theory), this patch can also make some queries faster.
We can optimize all non-null columns further in the future.
> perf: optimize writing non-null primitive value

- flake.nix
- rust-toolchain.toml
This change removes rust components from the toolchain file and add them to flake so the dev builders won't need to install components that required for dev and ci.  
> ci: move components to flakes so it won't affect builders

- docs/how-to/how-to-profile-memory.md
for now the memory perf command using `tikv-jemallocator` had been changed
using the doc or blog way get error ` {"error":"Memory profiling is not enabled"}` and very hard to debug.
this patch fix it. about the `greptime blog` side I do not fix
more info:
- blog: https://magiroux.com/posts/rust-jemalloc-profiling
- issue: https://github.com/tikv/jemallocator/issues/65
> docs: fix memory perf command wrong

- src/mito2/src/engine.rs
- src/mito2/src/request.rs
- src/mito2/src/worker.rs
- src/mito2/src/worker/handle_flush.rs
- src/mito2/src/worker/handle_write.rs
As title says. Also with some other changes that reduce some overhead.
We can further pull more logic out of the worker, like primary key encoding or row to column conversion.
> refactor: pull column filling logic out of mito worker loop

- Cargo.lock
- Cargo.toml
- src/pipeline/src/etl.rs
- src/pipeline/src/etl/transform/transformer/greptime.rs
- src/servers/src/http/loki.rs
- src/servers/src/http/otlp.rs
- src/servers/src/otlp/logs.rs
- src/servers/src/otlp/utils.rs
- tests-integration/tests/http.rs
This PR refactors the write path of OTLP Logs insertion. The main change is to eliminate the following three schemas and use one single `SchemaInfo`.
```Rust
let mut extra_resource_schema = SchemaInfo::default();
let mut extra_log_schema = SchemaInfo::default();
let mut extra_scope_schema = SchemaInfo::default();
```
The OTLP Logs request itself has 3 ordered layers: resource, scope, and log, and each has its own attributes. The attributes are stored using JSON datatype. However, we enable users to set `select keys` to find values in the attributes and uplift the values to the top level, which is an independent column, to speed up queries.
The original implementation uses three …
> refactor: otlp logs insertion

- src/mito2/src/worker/handle_drop.rs
- src/mito2/src/worker/handle_open.rs
https://github.com/GreptimeTeam/greptimedb/issues/5070
This PR changes the region gc task to recycle the region directory after gc duration (5min) without considering whether parquet files exist.
This ensures leaking parquet files won't affect the gc task.
> fix: force recycle region dir after gc duration

- Cross.toml
- #5478
Update Cross.toml config file for cross compilation. So now we can change `JEMALLOC_SYS_WITH_LG_PAGE` env var to customize target platform page size when crossing compiling GreptimeDB.
> fix: cross compiling for aarch64 targets and allow customizing page size

- src/cli/src/bench.rs
- src/cli/src/bench/metadata.rs
- src/common/meta/src/ddl/drop_database/executor.rs
- src/common/meta/src/ddl/drop_table.rs
- src/common/meta/src/ddl/drop_table/executor.rs
- src/common/meta/src/ddl/drop_table/metadata.rs
- src/common/meta/src/ddl/utils.rs
- src/common/meta/src/error.rs
- src/common/meta/src/key.rs
- src/common/meta/src/key/datanode_table.rs
- src/common/meta/src/key/tombstone.rs
- src/common/meta/src/key/topic_region.rs
- src/common/meta/src/wal_options_allocator.rs
As title. Waiting for region migration part.
> feat: update topic-region map when create and drop table

- src/servers/src/http.rs
- tests-integration/tests/http.rs
Closes https://github.com/GreptimeTeam/greptimedb/issues/5333
Endpoint changes:
- `v1/events/logs` -> `v1/ingest`. This endpoint will become our universal HTTP ingest endpoint. More formats and scenarios support are on the way
- `v1/events/pipelines/dryrun` -> `v1/pipelines/_dryrun` for escape user pipeline named "dryrun"
- `v1/events/pipelines/<pipeline_name>` -> `v1/pipelines/<pipeline_name>`
All old APIs will remain for a while, so this PR is not breaking.
> feat: move pipelines to the first-class endpoint

- src/mito2/src/read.rs
- src/mito2/src/row_converter.rs
- src/mito2/src/sst/index/bloom_filter/creator.rs
- src/mito2/src/sst/index/codec.rs
- src/mito2/src/sst/index/inverted_index/creator.rs
Previously, the default was to build an index for the tag column, hence the traversal method involved iterating through all tag columns.
Now, this assumption has been invalidated as the process has shifted to building indexes for specified columns. Therefore, it is no longer appropriate to continue traversing all tag columns, especially in scenarios where the number of columns is vast but only a few columns require index construction.
> refactor: change traversal order during index construction

- src/puffin/src/puffin_manager/stager/bounded_stager.rs
The original default strategy (tiny-lfu) might result in too many old entries being unable to be evicted, hence it has been changed to lru.
ref: https://docs.rs/moka/latest/moka/policy/struct.EvictionPolicy.html#impl-EvictionPolicy
> feat: change puffin stager eviction policy

- .github/workflows/nightly-ci.yml
> ci: run nightly jobs only on greptimedb repo

- src/pipeline/src/etl/transform.rs
- src/pipeline/src/etl/transform/transformer/greptime.rs
- src/pipeline/src/etl/transform/transformer/greptime/coerce.rs
- src/pipeline/tests/pipeline.rs
* if not set the timestamp default value use now()
> chore: set now as timestamp field default value

- Cargo.lock
- Cargo.toml
- config/config.md
- config/frontend.example.toml
- config/standalone.example.toml
- src/frontend/src/server.rs
- src/frontend/src/service_config/mysql.rs
- src/frontend/src/service_config/postgres.rs
- src/servers/Cargo.toml
- src/servers/src/mysql/server.rs
- src/servers/src/postgres/server.rs
- src/servers/src/server.rs
- src/servers/tests/mysql/mysql_server_test.rs
- src/servers/tests/postgres/mod.rs
- tests-integration/src/test_util.rs
- tests-integration/tests/http.rs
https://github.com/GreptimeTeam/greptimedb/issues/5493
Add a new option `keep_alive_secs` to MySQL and PostgreSQL protocol for server-side keep-alive. Similar to `tcp_keepalives_idle` and `tcp_keepalives_interval` in PostgreSQL server.
Verified by `tcpdump`:
> feat: support server-side keep-alive for mysql and pg protocols

- .github/workflows/docbot.yml
This docbot tasks requires `pull_request_target` to be able to use secret to create issue.
> ci: docbot requires pull_request_target

- .github/actions/build-greptime-images/action.yml
Resolve https://github.com/GreptimeTeam/greptimedb/issues/5513.
Use the fixed `tonistiigi/binfmt:qemu-v7.0.0-28` image version, which is used in the latest successfully [build](https://github.com/GreptimeTeam/greptimedb/actions/runs/13253038350/job/36997934191) instead of `tonistiigi/binfmt:latest` to avoid segmentation fault.
Upstream issue: https://github.com/tonistiigi/binfmt/issues/240.
The `tonistiigi/binfmt:qemu-v7.0.0-28` is a very old version(2022), although it's the previous "latest" binfmt image. The upstream update this "latest" version [recently](https://github.com/tonistiigi/binfmt/issues/165) and cause https://github.com/GreptimeTeam/greptimedb/issues/5513. Although …
> fix: use fixed `tonistiigi/binfmt:qemu-v7.0.0-28` image version instead of latest version to avoid segmentation fault

- src/servers/src/http/prometheus.rs
- src/servers/src/http/result/prometheus_resp.rs
- tests-integration/tests/http.rs
When `PrometheusJsonResponse` returns an error, the data field (`PrometheusResponse`) is now skipped during serialization to align with Prometheus behavior. This ensures that Grafana displays specific error messages instead of the ambiguous "unknown result type: " message, improving user experience.
Before
After
> fix(query_range): skip data field on errors

- src/query/src/promql/planner.rs
- tests-integration/src/tests/promql_test.rs
- tests/cases/standalone/common/tql/basic.result
- tests/cases/standalone/common/tql/basic.sql
This patch provides an alias `__database__` to current `__schema__` matcher because `database` is more widely used in our sql UI.
> feat: alias database matcher for promql

- src/mito2/src/cache/file_cache.rs
- src/object-store/src/layers/lru_cache/read_cache.rs
- src/puffin/src/puffin_manager/stager/bounded_stager.rs
This PR changes the eviction policy of the read/write cache and also reclaims space eagerly:
- Use LRU policy for read/write cache
- Run all pending tasks of the cache when we put a new entry to the write cache and stager
- This can evict files and directories faster than before
- Run pending tasks in the delete routine of the recycle bin to speed up eviction when there is no request
- The read cache doesn't call `run_pending_tasks()` now as it only caches object ranges that are usually smaller.
Moka maintenance task:
https://github.com/moka-rs/moka/blob/main/MIGRATION-GUIDE.md#the-maintenance-tasks
Before (staging size 3G)
```
$ du -sh …
```
> feat: speed up read/write cache and stager eviction

- src/common/meta/src/ddl/tests/create_view.rs
The typo database seems updated just now
> fix: old typo

- Cargo.lock
- Cargo.toml
Add markers for external workspace dependencies so that we can use shell script to copy them.
> chore: add section marker for extenal dependencies

- src/servers/src/http/jaeger.rs
- tests-integration/tests/http.rs
To compatible with the Jaeger API, if the trace table is not found, return an empty response instead of an error.
> fix(jaeger): return error when no tracing table

- src/query/src/promql/planner.rs
- tests/cases/standalone/common/promql/non_existent_matchers.result
- tests/cases/standalone/common/promql/non_existent_matchers.sql
This PR aligns with VictoriaMetric's behavior by ignoring filters for non-existent labels (columns) instead of returning an error for a column not found.
> fix(promql): ignore filters for non-existent labels

- src/promql/src/extension_plan.rs
- src/promql/src/extension_plan/instant_manipulate.rs
- src/promql/src/extension_plan/normalize.rs
- src/promql/src/extension_plan/range_manipulate.rs
- src/promql/src/extension_plan/series_divide.rs
This change introduces series count metrics for various PromQL extension plan operators, including:
- InstantManipulateStream
- SeriesNormalizeStream
- RangeManipulateStream
- SeriesDivideStream
It looks like 
```
PromInstantManipulateExec: range=[], lookback=[300000], interval=[15000], time index=[greptime_timestamp] metrics=[output_rows: 400, elapsed_compute: 788313, num_series: 20, ]
PromSeriesNormalizeExec: offset=[0], time index=[greptime_timestamp], filter NaN: [false] metrics=[output_rows: 1200, elapsed_compute: 652542, num_series: 20, ]
PromSeriesDivideExec: tags=[] metrics=[output_rows: 1200, elapsed_compute: 480161, num_series: 20, ]
```
Please convert it to a draft if …
> feat(promql): add series count metrics

- src/query/src/promql/planner.rs
- tests/cases/standalone/common/select/tql_filter.result
- tests/cases/standalone/common/select/tql_filter.sql
drop regex filters like `where a =~ .*`
> feat: drop noneffective regex filter

- .github/actions/release-cn-artifacts/action.yaml
- .github/scripts/upload-artifacts-to-s3.sh
- .github/workflows/dev-build.yml
- .github/workflows/nightly-build.yml
- .github/workflows/release.yml
tool: https://github.com/peak/s5cmd
It seems the [download page](https://greptime.cn/download) unnecessary the `dev-build` and `nightly-build` artifacts?  The [docs](https://docs.greptime.cn/nightly/getting-started/installation/greptimedb-standalone) does not contain the use of `nightly-build` and `dev-build` artifacts, I set `upload-to-s3` to false, upload artifacts to s3 when only release.
> ci: use s5cmd upload artifacts

- src/query/src/dist_plan/commutativity.rs
- src/query/src/optimizer/windowed_sort.rs
- tests/cases/distributed/explain/order_by.result
- tests/cases/distributed/explain/order_by.sql
- tests/cases/standalone/common/order/order_by_exceptions.result
- tests/cases/standalone/optimizer/order_by.result
- tests/cases/standalone/optimizer/order_by.sql
closes https://github.com/GreptimeTeam/greptimedb/issues/5463
This PR collects aliases of the time index column in the `ProjectionExec`, so both distributed query and ordering by alias can use window sort.
It also uses the commutativity of `alias.expr` as the commutativity of `Alias` so we can push the plan to the datanode.
> fix: window sort support alias time index

- grafana/greptimedb-cluster.json
- grafana/greptimedb.json
Improve the grafana dashboard as follows:
- Before
- Now
- Before
- Now 
- Before
- Now 
- Before
- Now
`histogram_quantile(0.99, sum by(pod, le) (rate(greptime_servers_postgres_query_elapsed_count{pod=~"$frontend"}[$__rate_interval])))` ->
`histogram_quantile(0.99, sum by(pod, le) (rate(greptime_servers_postgres_query_elapsed_bucket{pod=~"$frontend"}[$__rate_interval])))`
- Before
...
- Now
> chore: improve grafana dashboard

- src/query/src/promql/planner.rs
- tests/cases/standalone/common/promql/simple_histogram.result
- tests/cases/standalone/common/promql/simple_histogram.sql
#5525 
This PR removes the `le` tag in ctx after the planner returns a `HistogramFold` node to ensure consistency with the `HistogramFold` output schema, which also omits the le tag.
> fix(promql-planner): remove le tag in ctx

- src/query/src/promql/planner.rs
- tests/cases/standalone/common/promql/set_operation.result
- tests/cases/standalone/common/promql/set_operation.sql
#5525 
This PR fixes the behavior of the AND/UNLESS operator.
For example: 
```
vector_1 and vector_2
```
The AND operator returns the time series from the left-hand vector (vector_1) in the right-hand vector (vector_2), retaining the values from the left-hand vector.
> fix(promql-planner): correct AND/UNLESS operator behavior

- src/pipeline/src/dispatcher.rs
- src/pipeline/src/etl.rs
- src/pipeline/src/etl/processor.rs
- src/pipeline/src/etl/processor/cmcd.rs
- src/pipeline/src/etl/processor/csv.rs
- src/pipeline/src/etl/processor/date.rs
- src/pipeline/src/etl/processor/decolorize.rs
- src/pipeline/src/etl/processor/digest.rs
- src/pipeline/src/etl/processor/dissect.rs
- src/pipeline/src/etl/processor/epoch.rs
- src/pipeline/src/etl/processor/gsub.rs
- src/pipeline/src/etl/processor/join.rs
- src/pipeline/src/etl/processor/json_path.rs
- src/pipeline/src/etl/processor/letter.rs
- src/pipeline/src/etl/processor/regex.rs
- src/pipeline/src/etl/processor/timestamp.rs
- src/pipeline/src/etl/processor/urlencoding.rs
- src/pipeline/src/etl/transform.rs
- src/pipeline/src/etl/transform/transformer/greptime.rs
- src/pipeline/src/etl/value.rs
- src/pipeline/src/etl/value/map.rs
- src/pipeline/src/lib.rs
- src/servers/src/pipeline.rs
The patch refactors pipeline input type to an alias called `PipelineMap`. This makes it's easier to change the data container in future if we find better data strcuture for this.
> refactor: use global type alias for pipeline input

- src/servers/src/http/loki.rs
- tests-integration/tests/http.rs
Now that we've updated our Loki proto file (see #5484), we can support the `structured metadata` field during ingestion. See the integration test modification for effects.
> chore: support Loki's structured metadata for ingestion

- Cargo.lock
- Cargo.toml
- src/cmd/src/metasrv.rs
- src/common/meta/src/cluster.rs
- src/datanode/Cargo.toml
- src/datanode/src/heartbeat.rs
- src/flow/Cargo.toml
- src/flow/src/heartbeat.rs
- src/frontend/Cargo.toml
- src/frontend/src/heartbeat.rs
- src/meta-srv/src/handler/collect_cluster_info_handler.rs
as title
metasrv then is aware of cluster's total cpus, and able to do something about it further
> feat: submit node's cpu cores number to metasrv in heartbeat

- src/common/meta/src/cache/flow/table_flownode.rs
- src/common/meta/src/ddl/create_flow.rs
- src/common/meta/src/ddl/drop_flow/metadata.rs
- src/common/meta/src/key/flow.rs
- src/common/meta/src/key/flow/flow_route.rs
- src/common/meta/src/key/flow/flownode_addr_helper.rs
- src/common/meta/src/key/flow/table_flow.rs
- src/common/meta/src/key/node_address.rs
- src/flow/src/heartbeat.rs
- src/meta-srv/src/handler.rs
- src/meta-srv/src/handler/collect_stats_handler.rs
- src/meta-srv/src/handler/remap_flow_peer_handler.rs
- src/operator/src/flow.rs
#4673 
Currently, the routing addresses of the flow are written into metadata during flowtask creation. These details are updated during flow migration and failover processes. However,  when the failover is disabled, if a user modifies the flownode port and restarts it, this will not synchronize with the metadata. We need a solution to address this issue. This PR mainly does the following things:
- Identify address changes in the heartbeat information reported by the flownode and store them.
- Map the latest address when querying the route.
> feat: remap flow route address

- src/servers/src/http.rs
- src/servers/src/http/result/prometheus_resp.rs
#5525 
By default, **Grafana executes multiple PromQL queries within a request sequentially**. However, the **VictoriaMetrics datasource plugin executes them in parallel**. When Grafana and the datasource are deployed in different data centers, parallel execution can significantly reduce network latency and improve query efficiency.
This PR aims to minimize retrieval overhead as much as possible.
1. Enable Gzip Compression for Prometheus Query Handlers
- Enables Gzip compression to reduce response payload size, thereby lowering retrieval overhead.
2. Ignore NaN values in Prometheus Responses
- Aligns behavior with VictoriaMetrics and also helps reduce retrieval overhead. …
> feat: enable gzip for prometheus query handlers and ignore NaN values in prometheus response

- src/frontend/src/instance.rs
- src/query/Cargo.toml
- src/query/src/analyze.rs
- src/query/src/datafusion.rs
- src/servers/src/http/hints.rs
- src/session/src/context.rs
- src/sql/src/statements/explain.rs
- tests-integration/tests/http.rs
Now the `/v1/sql` API can generate something like the following for `explain analyze` clause 
It can be turned on with a new HTTP header `x-greptime-analyze-format`
> feat: support to generate json output for explain analyze in http api

- .github/workflows/docbot.yml
- .github/workflows/semantic-pull-request.yml
run labeler job concurrently may incur unexpected result
> fix: avoid run labeler job concurrently

- src/mito2/src/sst/index.rs
- src/mito2/src/test_util/sst_util.rs
- src/store-api/src/metadata.rs
#5486
This PR corrects the behavior of inverted_indexed_column_ids. By default, it no longer treats primary keys as inverted columns.
> fix: correct `inverted_indexed_column_ids` behavior

- src/mito2/src/cache/file_cache.rs
- src/mito2/src/cache/write_cache.rs
This PR removes all uploaded and cached files to release space when the upload process fails. It adds a `UploadTracker` to track uploaded files so we can remove these files on failure.
This fixes a potential resource leak in the write cache.
> fix: remove cached and uploaded files on failure

- Cargo.lock
- Cargo.toml
- src/common/meta/src/ddl/drop_database/executor.rs
- src/common/meta/src/ddl/drop_table.rs
- src/common/meta/src/ddl/drop_table/executor.rs
- src/datanode/src/region_server.rs
- src/metric-engine/src/engine/drop.rs
- src/metric-engine/src/metadata_region.rs
- src/mito2/src/engine/drop_test.rs
- src/mito2/src/request.rs
- src/mito2/src/worker.rs
- src/store-api/src/region_request.rs
After some search and learn the region server found maybe we can skip the drop columns in drop logical region
since all data can be drop in `phy` table I wonder.
because the function `get_all` or `get_all_with_prefix` is very expensive, cost almost all the time for the drop database
before this patch
after this patch
the generate data scripts
```py
import psycopg2
import time
from datetime import datetime, timedelta
DB_HOST = "localhost"
DB_PORT = "4003"
DB_USER = "greptime"
DB_NAME = "public"
SENSORS_PER_LOCATION = 4000
SIMULATION_DURATION_HOURS = 5
INSERT_BATCH_SIZE = 4000
def insert_data_now(simulation_start_time):
conn = create_connection()
try:
with conn.cursor() as cur: …
```
> perf: close issue 4974 by do not delete columns when drop logical region about 100 times faster

- Cargo.lock
- src/servers/Cargo.toml
- src/servers/src/http/result/prometheus_resp.rs
#5525 
This PR fixes an issue where the order of tags was not preserved. Since the results may be processed by sort or sort_desc.
> fix(prom): preserve the order of series in `PromQueryResult`

- src/flow/src/heartbeat.rs
fix a bug when flownode's heartbeat's conn break, it will failed to reconnect. Now flownode's heartbeat logic is similiar to frontend and will keep trying.
> fix: flow heartbeat retry

- src/query/src/promql/planner.rs
- tests/cases/standalone/common/promql/set_operation.result
- tests/cases/standalone/common/promql/set_operation.sql
#5525 
We implement promql binary operations using joins, however, since `NULL != NULL` in a join, columns that are entirely NULL in both tables can result in an empty join output. This PR introduces vector matching keywords(`ignoring`, `on`) to address this issue by allowing explicit ignoring of columns that contain only NULL values.
> feat(promql-planner): introduce vector matching binary operation

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
> chore: bump version to 0.13.0

- src/metric-engine/src/engine/create.rs
- src/metric-engine/src/engine/state.rs
Was introduced in https://github.com/GreptimeTeam/greptimedb/pull/5503
Check if the physical region exist before using, and unwrapping it.
Also remove a connecting flight from Shenzhen to Guangzhou via Shanghai
```rust
pub fn logical_region_exists_filter(
&self,
physical_region_id: RegionId,
) -> impl for<'a> Fn(&'a RegionId) -> bool + use<'_> {
let state = self
.physical_region_states()
.get(&physical_region_id)
.unwrap();
move |logical_region_id| state.logical_regions().contains(logical_region_id)
}
```
> fix: check physical region before use

- tests/runner/src/server_mode.rs
It's soooo overwhelming with full config content. A full run can generate over 5000 lines of logs, making it super hard to find an actual error.
Since the config file is persisted, we can always check the content later when necessary anyway.
> feat: skip printing full config content in sqlness

- src/sql/src/statements/option_map.rs
- tests/cases/standalone/common/show/show_create.result
- tests/cases/standalone/common/show/show_create.sql
- fixes #5631
- **Enhancements in `OptionMap`**:
- Changed formatting from `escape_default` to `escape_debug` for better handling of special characters in `src/sql/src/statements/option_map.rs`.
- Added unit tests to verify the new formatting behavior.
- **Test Cases for CJK Comments**:
- Added test cases for tables with comments in CJK (Chinese, Japanese, Korean) characters in `tests/cases/standalone/common/show/show_create.sql` and `show_create.result`.
> fix: properly display CJK characters in table/column comments

- src/api/src/v1/column_def.rs
- src/common/grpc-expr/src/error.rs
- src/common/grpc-expr/src/util.rs
- src/pipeline/src/etl/transform/index.rs
- src/pipeline/src/etl/transform/transformer/greptime/coerce.rs
- tests-integration/tests/http.rs
This PR mainly supports specifying `skipping` index in pipeline config file. For example
```yaml
transform:
- field: type
type: string
index: skipping
- field: log
type: string
index: fulltext
- field: time
type: time
index: timestamp
```
It converts to the following clause in create table SQL
```SQL
`type` STRING NULL SKIPPING INDEX WITH(granularity = '0', type = 'BLOOM'),
```
> chore: support specifying `skipping` index in pipeline

- src/meta-srv/src/region/supervisor.rs
Prevent failover to the same peer for region
> fix: prevent failover of regions to the same peer

- src/sql/src/statements/transform/type_alias.rs
Close #5629 
Adds `bool` as alias for `boolean`.
> feat: alias for boolean

- src/query/src/dist_plan/analyzer.rs
- tests/cases/standalone/common/order/order_by.result
- tests/cases/standalone/common/range/nest.result
- tests/cases/standalone/common/tql-explain-analyze/explain.result
Introduced in https://github.com/GreptimeTeam/greptimedb/pull/4753
Fix the dist analyzer that would lead to extra columns in its result.
> fix: recover plan schema after dist analyzer

- tests/runner/src/server_mode.rs
This patch fix flaky test in sqlness tests by make sure the random port do not use.
fix: https://github.com/GreptimeTeam/greptimedb/issues/5638
more: https://github.com/yihong0618/greptimedb/actions/runs/13679014304
> fix: flaky test in sqlness by fix random port

- src/query/src/optimizer/windowed_sort.rs
- tests/cases/standalone/common/order/order_by.result
- tests/cases/standalone/common/order/windowed_sort.result
remove `CoalesceBatchesExec` if limit < target_batch_size when optimize window sort, i.e, before removal `CoalesceBatchesExec` will forced to read more rows than necessary before fulfill a batch, causing too much slow down in combination with `FilterExec` which filtered most rows before output.
This shouldn't hurt perf much as limit is usually small enough so the benefits of coalesce batch is not significant.
Before removal:
```mysql
mysql> explain analyze SELECT message,timestamp FROM `logsbench`.`logsbench1` WHERE (message LIKE '%hello%') AND timestamp between '2025-03-05 07:07:55' and '2025-03-06 08:07:55' AND app = 'app-10' order by timestamp desc limit 10; …
```
> perf: rm coalesce batch when target_batch_size > fetch limit

- grafana/greptimedb-cluster.json
Updates the grafana dashboard to fix opendal panels.  Now they are no longer `No Data`.
> docs: update cluster dashboard to make opendal panel works

- src/servers/src/http/jaeger.rs
Quick fix, as the title suggests.
> fix: use `DateTime` instead of `NaiveDateTime`

- src/mito2/src/worker.rs
- src/mito2/src/worker/handle_write.rs
This PR sub the stall count gauge correctly.
> fix: correct stalled count

- src/log-store/src/error.rs
- src/log-store/src/raft_engine/backend.rs
- src/log-store/src/raft_engine/log_store.rs
This PR moves the log file sync operation from `engine.write` to background to avoid synchronous IO operations blocking region worker loop, which may result to ingestion rate fluctuation.
> refactor(mito): move wal sync task to background

- src/frontend/src/error.rs
- src/frontend/src/instance.rs
- src/frontend/src/instance/promql.rs
- src/query/src/dataframe.rs
- src/query/src/parser.rs
- src/query/src/promql.rs
- src/query/src/promql/label_values.rs
- src/query/src/promql/planner.rs
- src/servers/src/error.rs
- src/servers/src/http/prometheus.rs
- src/servers/src/prometheus_handler.rs
- tests-integration/src/test_util.rs
- tests-integration/tests/http.rs
#5525 
This PR optimizes the label values query by using a specified logical plan, eliminating unnecessary overhead from the PromQL plan. This change improves performance by avoiding extra operations like sorting labels and dividing timeseries.
1h time range
PromQL 1.21s vs SQL 0.29s
24h time range
PromQL 4.32s vs SQL 0.75s
```
tql eval(1741183200,1741186800,300) up{job="node_exporter"};
|     0 |    0 |  PromInstantManipulateExec: range=[1741183200000..1741186800000], lookback=[300000], interval=[300000], time index=[greptime_timestamp] metrics=[output_rows: 13057, elapsed_compute: 208885377, num_series: 1057, ]
PromSeriesNormalizeExec: offset=[0], time …
```
> perf(prom): optimize label values query

- Cargo.lock
- Cargo.toml
Update promql-parser to a released version. This includes support for duration literals.
> feat: update promql-parser to 0.5 for duration literal

- src/metric-engine/src/engine/read.rs
- src/mito2/src/read/seq_scan.rs
- src/mito2/src/read/unordered_scan.rs
- src/store-api/src/region_engine.rs
This PR adds a hint `logical_region` to the `ScannerProperties` and sets it in the metric engine to indicate we are scanning a logical region.
> feat: add hint for logical region in RegionScanner

- src/mito2/src/metrics.rs
- src/mito2/src/worker/handle_manifest.rs
Add a gauge for inflight downloading tasks.
> feat: add a gauge for download tasks

- src/common/meta/src/kv_backend/memory.rs
memorykv's Display implementation holding the read lock can block write requests for a long time, which is not ideal.
> chore: make memorykv write happily

- src/mito2/Cargo.toml
- src/mito2/src/error.rs
- src/mito2/src/region/opener.rs
When user changes database wal provider from `raft_engine` to `kafka` without cleaning existing data, datanode will report confusing error while opening regions.
This PR adds simple check before opening regions to warn users of incompatible config changes.
> chore: check region wal provider on startup to avoid inconsistence

- src/common/meta/src/key/flow/flow_info.rs
make the newly added `created_time`&`update_time` field of FlowInfoValue `serde(default)` so can read from old version's metadata
__edited__: local test with create on older version and reboot in newer version now work. P.S. maybe need to run `tests/upgrade-compat` test in a CI later
> fix: FlowInfoValue's compatibility

- config/datanode.example.toml
- config/standalone.example.toml
- src/datanode/src/config.rs
- src/datanode/src/store/s3.rs
- tests-integration/tests/http.rs
This PR expose the `enable_virtual_host_style` flag.
- By default, opendal will send API to https://s3.us-east-1.amazonaws.com/bucket_name
- Enabled, opendal will send API to https://bucket_name.s3.us-east-1.amazonaws.com
> feat: expose virtual_host_style config for s3 storage

- src/servers/src/http/event.rs
- src/servers/src/http/header.rs
The current `application/json`(which is also NDJSON) uses serde's stream deserializer, which stops immediately when an error is encountered, leaving all the following possible valid JSON discarded.
In the real world, the data is often in the format of lines of JSON objects. We can simply skip one line of invalid JSON string and continue parsing.
See test for example difference.
> chore: support `application/x-ndjson` for log ingest

- src/pipeline/src/etl/transform.rs
- src/pipeline/src/etl/transform/transformer/greptime.rs
- src/pipeline/src/etl/transform/transformer/greptime/coerce.rs
- tests-integration/tests/http.rs
Add a `tag` field in the pipeline transform section to specify the tag in the database. `tag` is not an index concept, and now we've separate `tag` with `inverted` index, it's clearer to use a separate field to specify a tag other than an index field. For example: 
```yaml
transform:
- field: type
type: string
index: skipping
tag: true
```
This config translates to the below SQL
```sql
CREATE TABLE IF NOT EXISTS "xx" (
-- other columns
"type" STRING NULL SKIPPING INDEX WITH(granularity = '10240', type = 'BLOOM'),
TIME INDEX ("time"),
PRIMARY KEY ("type")
)
ENGINE=mito
WITH(
append_mode = 'true'
)
```
> chore: support `tag` in transform

- src/api/src/v1/column_def.rs
- src/pipeline/src/etl/transform/index.rs
- src/pipeline/src/etl/transform/transformer/greptime/coerce.rs
- tests-integration/tests/http.rs
Support specifies the `inverted` index in the pipeline. example
```
transform:
- fields:
- id1
- id2
type: int32
index: inverted
- fields:
- logger
type: string
- field: type
type: string
index: skipping
```
> chore: support `inverted` index in pipeline

- src/pipeline/src/etl/processor.rs
- src/pipeline/src/etl/processor/simple_extract.rs
- src/pipeline/tests/simple_extract.rs
This PR introduces `simple_extract` processor, which allows the user to use a key like `a.b` to extract a field from a nested JSON object quickly. The purpose of this processor is to provide a simple yet performant way to extract JSON fields other than `json_path` processor, which is relatively complex and slow.
See the test for usage.
> feat: add simple extract processor

- .gitignore
- README.md
- config/config.md
- config/datanode.example.toml
- config/flownode.example.toml
- config/frontend.example.toml
- config/metasrv.example.toml
- config/standalone.example.toml
- docker/docker-compose/cluster-with-etcd.yaml
- src/cmd/src/datanode.rs
- src/cmd/src/frontend.rs
- src/cmd/src/metasrv.rs
- src/cmd/src/standalone.rs
- src/cmd/tests/load_config_test.rs
- src/common/config/src/config.rs
- src/common/telemetry/src/logging.rs
- src/datanode/src/config.rs
- src/meta-srv/src/metasrv.rs
- src/servers/tests/http/http_handler_test.rs
Fixes #4947 
Change default data location to a relative path: `./greptimedb_data`. A relative path from current directory is almost the best location we can choose which has permission to write.
We will also update our demos and docs to wipe out content using `/tmp`.
Let's say goodbye to our /tmp culture.
> feat: move default data path from /tmp to current directory

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
> chore: bump version to 0.14.0

- config/config.md
- config/datanode.example.toml
- config/flownode.example.toml
- config/frontend.example.toml
- config/standalone.example.toml
- src/cmd/src/frontend.rs
- src/servers/src/http.rs
- src/servers/tests/http/http_handler_test.rs
- tests-integration/tests/http.rs
Fixes #5720 
As described in issue above, this setting becomes annoy when user running analytical query or [benchmark](https://github.com/ClickHouse/JSONBench/pull/24/files#diff-def3a27fbe592e09fa3e5c701938f0a6a3dd5dd71387cc01a5d2311cd742bd84R14).
> feat: disable http timeout

- Cargo.lock
- Cargo.toml
- src/common/meta/src/peer.rs
- src/meta-client/src/client.rs
- src/meta-srv/src/handler/collect_cluster_info_handler.rs
- src/meta-srv/src/handler/remap_flow_peer_handler.rs
close https://github.com/GreptimeTeam/greptimedb/issues/5577
related pr: https://github.com/GreptimeTeam/greptime-proto/pull/222
remove duplicated peer definition
> feat: remove duplicated peer definition

- .github/actions/setup-greptimedb-cluster/action.yml
- .github/workflows/develop.yml
- Cargo.lock
- Cargo.toml
- src/common/meta/src/kv_backend/rds/mysql.rs
- src/meta-srv/Cargo.toml
- src/meta-srv/src/bootstrap.rs
- src/meta-srv/src/election.rs
- src/meta-srv/src/election/mysql.rs
- src/meta-srv/src/election/postgres.rs
- src/meta-srv/src/error.rs
- src/meta-srv/src/metasrv.rs
- tests-fuzz/Cargo.toml
- tests/runner/src/env.rs
- tests/runner/src/main.rs
- tests/runner/src/server_mode.rs
- tests/runner/src/util.rs
> feat: add mysql election logic

- grafana/greptimedb-cluster.json
Add rows count of datanode ingestion to grafana dashboard
> chore: add datanode write rows to grafana dashboard

- src/common/meta/src/kv_backend/rds/mysql.rs
- src/common/meta/src/kv_backend/rds/postgres.rs
- src/meta-srv/src/election/postgres.rs
> fix: wrap table name with ``

- src/mito2/src/error.rs
- src/mito2/src/manifest/manager.rs
- src/mito2/src/manifest/storage.rs
- src/mito2/src/manifest/tests/checkpoint.rs
#5739 
Introduce `install_manifest_to` for `RegionManifestManager` to install latest manifest.
> feat: introduce `install_manifest_to` for `RegionManifestManager`

- src/flow/src/adapter/util.rs
- tests/cases/standalone/common/flow/flow_null.result
- tests/cases/standalone/common/flow/flow_null.sql
flow handle insert now correctly handle nullable column without default value constriant, also add sqlness test(which indeed error out in main branch now)
> fix: handle nullable default value

- src/cmd/src/error.rs
- src/cmd/src/frontend.rs
- src/cmd/src/standalone.rs
- src/frontend/src/frontend.rs
- src/frontend/src/instance.rs
- src/frontend/src/instance/builder.rs
- src/frontend/src/server.rs
- tests-integration/src/cluster.rs
- tests-integration/src/grpc.rs
- tests-integration/src/instance.rs
- tests-integration/src/opentsdb.rs
- tests-integration/src/otlp.rs
- tests-integration/src/prom_store.rs
- tests-integration/src/standalone.rs
- tests-integration/src/test_util.rs
- tests-integration/src/tests.rs
- tests-integration/src/tests/test_util.rs
- tests-integration/tests/region_migration.rs
Currently, it looks like there might be a circular reference like this: [Instance](https://github.com/GreptimeTeam/greptimedb/blob/a0739a96e418147129528e5eff8a689b309a6f9d/src/frontend/src/instance.rs#L116) -> [Servers](https://github.com/GreptimeTeam/greptimedb/blob/a0739a96e418147129528e5eff8a689b309a6f9d/src/frontend/src/instance.rs#L123) -> [Instance](https://github.com/GreptimeTeam/greptimedb/blob/a0739a96e418147129528e5eff8a689b309a6f9d/src/frontend/src/instance.rs#L116). However, digging deeper into the code, find that we maintain two instances, one instance contains all servers, and the other instance does not have any servers. The instance without servers is passed to …
> refactor: make frontend instance clear

- src/servers/src/mysql/handler.rs
- src/servers/src/mysql/helper.rs
- tests/cases/standalone/common/prepare/mysql_prepare.result
properly give placeholder types.
because it seems datafusion will not give data type to placeholder if it need to be cast to certain type(i.e. expr like `cast(placeholder)`, still unknown if this is a feature or a bug. And if a placeholder expr have no data type, datafusion will fail to extract it using `LogicalPlan::get_parameter_types`
After this fix, running the below command with any table in `public`
```
sea-orm-cli generate entity \
-u mysql://root:root@localhost:4002/public \
-o src/entities
```
will only cause `sea-orm-cli` to crash, before this command will cause db's thread to panic
> fix: properly give placeholder types

- Cargo.lock
- Cargo.toml
- src/common/meta/src/rpc/ddl.rs
- src/common/recordbatch/src/adapter.rs
- src/mito2/src/read/scan_region.rs
- src/mito2/src/read/seq_scan.rs
- src/mito2/src/read/unordered_scan.rs
- src/mito2/src/sst/file.rs
- src/query/src/analyze.rs
- src/query/src/datafusion.rs
- src/session/src/context.rs
- tests/cases/standalone/common/order/windowed_sort.result
- tests/cases/standalone/common/order/windowed_sort.sql
- tests/cases/standalone/common/select/tql_filter.result
- tests/cases/standalone/common/tql-explain-analyze/analyze.result
- fixes https://github.com/GreptimeTeam/greptimedb/issues/4408
- https://github.com/GreptimeTeam/greptimedb/pull/5699
- proto: https://github.com/GreptimeTeam/greptime-proto/pull/225
Supports `EXPLAIN ANALYZE VERBOSE` in standalone and distributed mode.
It adds an `ExplainOptions` to the query context so we can get the verbose flag from the context. We may support more explain options in the future.
It also prints more information about the scanner in verbose mode
- projection
- filters
- files, including file id, time range, num rows, file size, index file size
```
SeqScan: region=4440996184064(1034, 0), partition_count=2 (0 memtable ranges, 2 file 2 ranges), projection=["i", …
```
> feat: support explain analyze verbose

- src/log-store/src/kafka/producer.rs
- src/log-store/src/metrics.rs
- src/store-api/src/logstore/entry.rs
- Use actual used data structure's size instead of allocated memory size (`.len()` vs. `.capacity()`)
- Add per-partition traffic and workload metrics
> feat: add/correct some kafka-related metrics

- src/index/src/fulltext_index/create/bloom_filter.rs
- src/index/src/fulltext_index/create/tantivy.rs
- src/mito2/src/sst/index/bloom_filter/applier.rs
- src/mito2/src/sst/index/bloom_filter/creator.rs
- src/mito2/src/sst/index/inverted_index/applier.rs
- src/mito2/src/sst/index/inverted_index/creator.rs
- src/mito2/src/sst/index/puffin_manager.rs
- src/puffin/src/puffin_manager.rs
- src/puffin/src/puffin_manager/fs_puffin_manager/reader.rs
- src/puffin/src/puffin_manager/fs_puffin_manager/writer.rs
- src/puffin/src/puffin_manager/tests.rs
Adds infrastructure support for reading and writing blob metadata properties in the Puffin. This change prepares for future implementations of storing fulltext index configurations in blob metadata.
> feat: utilize blob metadata properties

- src/common/meta/src/ddl/table_meta.rs
- src/common/meta/src/key.rs
- src/common/meta/src/key/topic_region.rs
- src/common/meta/src/wal_options_allocator.rs
- src/common/wal/src/options.rs
- src/mito2/src/engine.rs
- src/mito2/src/region/opener.rs
- src/mito2/src/wal.rs
- src/mito2/src/wal/entry_reader.rs
- src/mito2/src/worker/handle_write.rs
- src/store-api/src/logstore/provider.rs
- src/table/src/requests.rs
- tests/cases/standalone/common/skip_wal.result
- tests/cases/standalone/common/skip_wal.sql
close #1267
Allow users to create tables with `skip_wal` set to true to disable WAL per table.
> feat(mito): allow skipping wal while creating tables

- src/common/meta/src/cluster.rs
- src/meta-client/src/client.rs
Move `list_flow_stats` to `ClusterInfo` trait.
> refactor: move `list_flow_stats` to `ClusterInfo` trait.

- src/operator/src/insert.rs
- src/servers/src/hint_headers.rs
- src/table/src/requests.rs
This is a follow-up PR for #5740, adding support for table options hints during the auto-create table process. 
> chore: accept table options in auto create table from hints

- src/servers/src/http/prometheus.rs
- tests-integration/tests/http.rs
fixes https://github.com/GreptimeTeam/greptimedb/issues/5769
Takes the name matcher and gets the metric name in label_values query.
> fix: support __name__ matcher in label values

- src/flow/src/expr/scalar.rs
> fix: typo variadic

- Cargo.lock
- Cargo.toml
- src/datanode/src/alive_keeper.rs
- src/datanode/src/tests.rs
- src/file-engine/src/engine.rs
- src/meta-srv/src/handler/region_lease_handler.rs
- src/metric-engine/src/engine.rs
- src/metric-engine/src/error.rs
- src/mito2/src/engine.rs
- src/mito2/src/engine/sync_test.rs
- src/mito2/src/error.rs
- src/mito2/src/region.rs
- src/mito2/src/region/version.rs
- src/mito2/src/request.rs
- src/mito2/src/worker.rs
- src/mito2/src/worker/handle_catchup.rs
- src/mito2/src/worker/handle_manifest.rs
- src/mito2/src/worker/handle_write.rs
- src/query/src/optimizer/test_util.rs
- src/store-api/src/region_engine.rs
#5739 
This PR implements the sync region for the mito engine, It adds a `sync_region` method to MitoEngine, which allows a follower region's manifest to update to at least a specified manifest version received from the metasrv.
> feat: implement `sync_region` for mito engine

- config/config.md
- config/metasrv.example.toml
- config/standalone.example.toml
- src/common/procedure/src/error.rs
- src/common/procedure/src/local.rs
- src/common/procedure/src/local/runner.rs
- src/common/procedure/src/options.rs
- src/frontend/src/instance.rs
- src/log-store/src/error.rs
- src/meta-srv/src/metasrv.rs
- src/meta-srv/src/metasrv/builder.rs
- src/mito2/src/error.rs
- tests-integration/src/cluster.rs
- tests-integration/tests/http.rs
#5789
If we do not impose a limit on the number of procedures, certain scenarios may lead to an uncontrolled increase in their count. **e.g.,** When the metric engine is enabled with remote WAL, if remote WAL becomes unavailable, the upper layer continues to return a "storage unavailable" error. In procedures, such errors trigger retries. Since table creation keeps failing, write operations continuously trigger the auto-create table procedure. Eventually, this leads to metasrv running out of memory.
This PR  
- Adds a limit on the number of running procedures.
- Implements ErrorExt::status_code for log-store to allow fine-grained control over error status codes.
Please convert it …
> feat: add limit for the number of running procedures

- config/config.md
- config/datanode.example.toml
- config/flownode.example.toml
- config/standalone.example.toml
- src/cmd/src/datanode.rs
- src/cmd/src/flownode.rs
- src/cmd/src/standalone.rs
- src/datanode/src/config.rs
- src/datanode/src/datanode.rs
- src/flow/src/adapter.rs
- tests-integration/src/cluster.rs
- tests-integration/src/standalone.rs
- tests-integration/src/test_util.rs
- tests-integration/tests/http.rs
This pr mainly remove `mode` option from the configuration file of datanode, standalone and flownode.
For example:
`./greptime datanode start` must be a distributed scenario.
`./greptime standalone start` must be a standalone scenario.
And there is no need for `mode` option to exist.
> refactor: remove mode option in configuration files

- src/partition/src/error.rs
The errors `InvalidTableRouteData` and `FindTableRoutes` should not be classified as `TableUnavailable` (Table is temporarily unable to handle the request.). These errors will persist even after retries, making `Unexpected` (Unexpected error, maybe there is a BUG.) a more appropriate classification. 
And, the error `FindLeader` should be classified as `TableUnavailable`, the error `FindRegionRoutes` should be 
classified as `Unexpected ` instead of `RegionNotReady`.
```rust
ensure!(
!region_routes.is_empty(),
error::FindTableRoutesSnafu { table_id }
);
...
ensure!(
partitions
.windows(2)
.all(|w| w[0].partition.partition_columns() == w[1].partition.partition_columns()), …
```
> fix: correct error status code

- Cargo.lock
- Cargo.toml
- src/pipeline/Cargo.toml
- src/pipeline/src/etl.rs
- src/pipeline/src/etl/value.rs
- src/pipeline/src/lib.rs
- src/servers/Cargo.toml
- src/servers/src/elasticsearch.rs
- src/servers/src/http/event.rs
- src/servers/src/interceptor.rs
- src/servers/src/lib.rs
As the title suggests. For reference, to load 10 x 100M data under the JSONBench scene
- before: 49,502 ms
- after: 37,620 ms
Note ⚠️: For positive integer numbers, `serde_json` will try to convert them into `int64` while `simd_json` will try to convert them into `uint64`. In most cases, we think it's ok.
> perf: introduce `simd_json` for parsing ndjson

- src/servers/src/http.rs
- src/servers/src/http/prom_store.rs
As the title suggests, this PR removes the prom store remote write dispatch using a state struct to wrap the config `bool`s.
> refactor: remove prom store write dispatch

- src/cmd/src/standalone.rs
- src/common/meta/src/datanode.rs
- src/common/meta/src/region_registry.rs
- src/meta-srv/src/handler.rs
- src/meta-srv/src/handler/collect_leader_region_handler.rs
- src/meta-srv/src/handler/failure_handler.rs
- src/meta-srv/src/handler/region_lease_handler.rs
- src/meta-srv/src/selector/weight_compute.rs
- src/metric-engine/src/engine.rs
- src/mito2/src/region.rs
- src/store-api/src/region_engine.rs
This PR introduces the `CollectLeaderRegionHandler`, which collects region manifest versions and flushed entry ids.
> feat: introduce `CollectLeaderRegionHandler`

- Cargo.lock
- Cargo.toml
- src/datanode/src/alive_keeper.rs
- src/datanode/src/datanode.rs
- src/datanode/src/heartbeat.rs
- src/datanode/src/region_server.rs
- src/datanode/src/tests.rs
- src/file-engine/src/engine.rs
- src/metric-engine/src/engine.rs
- src/metric-engine/src/error.rs
- src/mito2/src/engine.rs
- src/mito2/src/engine/sync_test.rs
- src/mito2/src/error.rs
- src/query/src/optimizer/test_util.rs
- src/store-api/src/region_engine.rs
#4672 
Implement `sync_region` for metric engine
> feat: implement `sync_region` for metric engine

- src/pipeline/src/error.rs
- src/pipeline/src/manager.rs
- src/servers/src/http/otlp.rs
- tests-integration/tests/http.rs
This patch propose the minor breaking change for existed trace users. It now requires all trace ingestion call to include a header `x-greptime-pipeline-name`. Legacy users will need to set it to `greptime_trace_v0`.
> refactor!: make pipeline a required parameter when ingesting trace

- config/config.md
- config/datanode.example.toml
- config/metasrv.example.toml
- config/standalone.example.toml
- src/common/meta/src/wal_options_allocator/topic_creator.rs
- src/common/wal/src/config.rs
- src/common/wal/src/config/kafka/common.rs
- src/common/wal/src/config/kafka/datanode.rs
- src/common/wal/src/config/kafka/metasrv.rs
- src/log-store/src/kafka/client_manager.rs
remove kafka wal backoff config
> refactor: remove backoff config

- src/frontend/src/instance/jaeger.rs
- src/servers/src/http/jaeger.rs
- src/servers/src/query_handler.rs
- tests-integration/tests/http.rs
The native Jaeger query API doesn't have a parameter to limit the time range for getting operations(span) for a specific service. When the trace table gets larger, its performance will be terrible.
In this PR, I add the http header `x-greptime-jaeger-time-range-for-operations` to add a time range explicitly. For example:
```
x-greptime-jaeger-time-range-for-operations: 3 days
```
We don't add the time range by default and let the user configure it based on their scenarios.
> refactor: add time range for jager get operations API

- src/cmd/src/flownode.rs
- src/cmd/src/standalone.rs
- src/flow/src/adapter/flownode_impl.rs
- src/flow/src/lib.rs
- src/flow/src/server.rs
make start flownode more clearer, and more similiar to datanode start
> refactor(flow): make start flownode clearer

- src/common/function/Cargo.toml
- src/common/function/src/function.rs
- src/common/function/src/state.rs
- src/common/macro/src/admin_fn.rs
- src/common/macro/src/lib.rs
make `admin_fn` macro usable outside common_function module
> feat: make `admin_fn` macro usable outside common_function module

- src/client/src/error.rs
- src/client/src/region.rs
- src/common/error/src/status_code.rs
- src/meta-client/src/client/cluster.rs
- src/meta-client/src/client/procedure.rs
- src/meta-client/src/error.rs
- src/servers/src/error.rs
- src/servers/src/mysql/writer.rs
- src/servers/src/postgres/types/error.rs
This PR improve error code handling in status code conversion.
We first attempt to extract the status code from gRPC response metadata (`GREPTIME_DB_HEADER_ERROR_CODE`). If not available, we fall back to converting the tonic status code to our internal representation, ensuring proper handling of client-side cancellations and other error states.
> refactor: improve error code handling in status code conversion

- Cargo.toml
- src/log-store/src/raft_engine/backend.rs
> chore: un-allow clippy's "readonly_write_lock"

- src/index/src/fulltext_index.rs
- src/index/src/fulltext_index/create/bloom_filter.rs
- src/index/src/fulltext_index/create/tantivy.rs
- src/index/src/fulltext_index/search/tantivy.rs
- src/index/src/fulltext_index/tests.rs
- src/mito2/src/sst/index/fulltext_index/applier.rs
- src/mito2/src/sst/index/fulltext_index/applier/builder.rs
- src/mito2/src/sst/index/fulltext_index/creator.rs
- src/mito2/src/sst/index/puffin_manager.rs
- src/puffin/src/puffin_manager.rs
- src/puffin/src/puffin_manager/fs_puffin_manager/reader.rs
- src/puffin/src/puffin_manager/fs_puffin_manager/writer.rs
- src/puffin/src/puffin_manager/tests.rs
Add support for applying term-based queries to the tantivy backend. The implementation introduces a streamlined way to filter search results using terms.
The critical functionality is in the `apply_one_column` method, where terms are now properly processed:
```rust
// 2. Apply terms
let query = request.terms_as_query(config.case_sensitive);
if !query.0.is_empty() {
let result = searcher
.search(&query.0)
.await
.context(ApplyFulltextIndexSnafu)?;
if let Some(ids) = row_ids.as_mut() {
ids.retain(|id| result.contains(id));
} else {
row_ids = Some(result);
}
}
```
This implementation:
1. Converts term criteria to query syntax using `terms_as_query()`
2. Respects the index's case …
> feat: apply terms with fulltext tantivy backend

- src/metric-engine/src/engine/create.rs
- src/store-api/src/mito_engine_options.rs
- src/table/src/requests.rs
- **Enhancements**:
- Introduced `SKIP_WAL_KEY` to the metric engine options in `create.rs` and `mito_engine_options.rs`.
- Updated test cases in `create.rs` to include `skip_wal` option and ensure it is removed for metadata regions.
> fix: remove metadata region options

- src/common/meta/src/rpc/router.rs
This commit fixes a bug in the `region_distribution` function where only leader peers were being considered when calculating the distribution of regions to datanodes. The function now properly accounts for follower peers as well.
> fix: include follower peers in region distribution

- Cargo.lock
- src/common/error/Cargo.toml
- src/common/error/src/ext.rs
- src/common/error/tests/ext.rs
- src/common/macro/src/stack_trace_debug.rs
- src/common/recordbatch/src/adapter.rs
- src/common/recordbatch/src/error.rs
- src/query/src/datafusion.rs
- src/query/src/datafusion/planner.rs
- src/query/src/error.rs
- src/query/src/plan.rs
- src/query/src/planner.rs
- src/query/src/range_select/plan.rs
- src/query/src/range_select/plan_rewrite.rs
- src/query/src/sql.rs
#5814 
Some errors are annotated with `#[snafu(display("")]`, which could produce empty result if we accidently call `to_string` on it, like [here](https://github.com/GreptimeTeam/greptimedb/pull/5841/files). So it's not a good practice. This PR is trying to use Snafu's "transparent" attribute to avoid that.
> refactor: avoid empty display in errors

- src/common/function/src/admin/migrate_region.rs
- src/common/meta/src/instruction.rs
- src/datanode/src/heartbeat/handler.rs
- src/datanode/src/heartbeat/handler/downgrade_region.rs
- src/datanode/src/heartbeat/handler/upgrade_region.rs
- src/file-engine/src/engine.rs
- src/meta-srv/src/procedure/region_migration.rs
- src/meta-srv/src/procedure/region_migration/close_downgraded_region.rs
- src/meta-srv/src/procedure/region_migration/downgrade_leader_region.rs
- src/meta-srv/src/procedure/region_migration/upgrade_candidate_region.rs
- src/meta-srv/src/procedure/test_util.rs
- src/metric-engine/src/engine.rs
- src/metric-engine/src/engine/catchup.rs
- src/mito2/src/engine/catchup_test.rs
- src/mito2/src/engine/set_role_state_test.rs
- src/mito2/src/worker.rs
- src/store-api/src/region_engine.rs
- src/store-api/src/region_request.rs
This PR makes the datanode immediately reject write operations while handling downgrade region instructions.
**Previous behavior:**
A region would only transition to a "downgraded leader" state after discovering its downgrade status through heartbeats, creating a potential timing gap.
**New behavior:**
Write operations are now immediately rejected when handling downgrade region instructions, and then flushes the memtable data.
With write operations rejected and memtable data flushed, the upgrade candidate process becomes faster since there's no data that would need to be replayed during the upgrade candidate region operation.
This PR also 
- Changes the default region migration …
> fix: alway rejects write while downgrading region

- .github/scripts/create-version.sh
- .github/workflows/release.yml
Add condition to check push the latest image `${{ github.ref_type == 'tag' && !contains(github.ref_name, 'nightly') && github.event_name != 'schedule' }}`
> ci: not push latest image when schedule release

- src/mito2/src/memtable/time_series.rs
Fix the issue that newly created series would be empty when reading, which causes panic
> fix: memtable panic

- src/pipeline/src/error.rs
- src/pipeline/src/etl/processor.rs
- src/pipeline/src/etl/processor/json_parse.rs
- src/pipeline/src/etl/value.rs
- src/pipeline/src/etl/value/array.rs
- src/pipeline/tests/common.rs
- src/pipeline/tests/json_parse.rs
- src/pipeline/tests/simple_extract.rs
- src/servers/src/http/loki.rs
close #5897 
As the title suggests. For an input JSON like 
```JSON
{
"commit": "{\"commitTime\": \"1573840000.000\", \"commitAuthor\": \"test\"}"
}
```
Use the following config to use `json_parse` processor
```YAML
processors:
- json_parse:
field: commit
```
This would parse the JSON as expected
```JSON
{
"commit": {
"commitTime": "1573840000.000",
"commitAuthor": "test"
}
}
```
> feat: add json parse processor

- src/operator/src/statement/copy_table_from.rs
- tests/cases/standalone/common/copy/copy_from_fs_csv.result
- tests/cases/standalone/common/copy/copy_from_fs_csv.sql
- tests/cases/standalone/common/copy/copy_from_fs_json.result
- tests/cases/standalone/common/copy/copy_from_fs_json.sql
- tests/cases/standalone/common/copy/copy_from_fs_parquet.result
- tests/cases/standalone/common/copy/copy_from_fs_parquet.sql
This PR fixes a schema projection issue in the file format readers (CSV and JSON) used by the `Copy From` statement. The readers were incorrectly applying schema projection twice, which could lead to schema mismatch errors.
> fix: avoid double schema projection in file format readers

- src/meta-srv/Cargo.toml
- src/meta-srv/src/procedure/region_migration/manager.rs
This PR added a validation to check if target peer already has a region follower before migration. It prevents migrating a leader region to a peer that already has a region follower.
> feat: prevent migrating a leader region to a peer that already has a region follower

- src/pipeline/src/etl/transform/transformer/greptime/coerce.rs
close #5934 
As the title suggests, this PR mainly fixes the wrong error message in pipeline execution.
> fix: wrong error msg in pipeline

- .github/actions/setup-greptimedb-cluster/with-remote-wal.yaml
- src/common/wal/src/config/kafka/common.rs
- src/common/wal/src/config/kafka/datanode.rs
- src/common/wal/src/config/kafka/metasrv.rs
- tests/conf/datanode-test.toml.template
- tests/conf/metasrv-test.toml.template
#5474
Enable auto wal prune in ci cluster to trigger test for it.
> test: update configs to enable auto wal prune

- src/meta-srv/src/bootstrap.rs
- src/meta-srv/src/selector.rs
- src/meta-srv/src/selector/common.rs
- src/meta-srv/src/selector/lease_based.rs
- src/meta-srv/src/selector/weight_compute.rs
- src/meta-srv/src/selector/weighted_choose.rs
1. Export `selector::weighted_choose` and `selector::common` to allow implementing custom Selector outside the repository.
2. Enable `metasrv` to build and load a `Selector` via plugin.
> feat: support building `metasrv` with selector from plugins

- src/pipeline/src/etl/transform/transformer/greptime.rs
> chore: use `once_cell` to avoid parse everytime in pipeline exec

- src/common/base/src/plugins.rs
To avoid accidently overwrite same type plugins, which is normally not wanted.
> chore: assert plugin uniqueness

- src/meta-srv/src/error.rs
- src/meta-srv/src/procedure/region_migration/manager.rs
- src/meta-srv/src/region/supervisor.rs
- tests-integration/tests/region_migration.rs
remove obsolete failover detectors after region leader change
> fix: remove obsolete failover detectors after region leader change

- src/servers/src/http/handler.rs
- tests-integration/tests/http.rs
We hope to add support to dump promql query results to csv. This patch adds support for these format parameters from sql api.
> feat: add format support for promql http api (not prometheus)

- src/query/src/window_sort.rs
as title, use random seed for window sort's fuzz(ish) test just in case
> test: use random seed for window sort fuzz test

- src/sql/src/parsers/create_parser.rs
fix flow parse expire after ignore month/days problem, notice use 1 month = 30.44 days to keep in line with https://docs.rs/humantime/latest/humantime/fn.parse_duration.html which we also use in many other places in codebase
> fix: parse flow expire after interval

- src/common/meta/src/region_registry.rs
As title. Should use the maximum of these two since both are prunable offset.
> fix: use max in flushed entry id and topic latest entry id

- src/common/meta/src/cache/flow/table_flownode.rs
- src/common/meta/src/ddl/create_flow.rs
- src/common/meta/src/error.rs
- src/common/meta/src/key/flow.rs
- src/common/meta/src/key/flow/flow_info.rs
- src/common/meta/src/rpc/ddl.rs
- src/flow/src/server.rs
- tests/cases/standalone/common/flow/flow_rebuild.result
- tests/cases/standalone/common/flow/flow_rebuild.sql
#5959
flow need to parse `raw_sql`, ~hence if `schema!=public`, on recover flows it will failed to find correct table if `raw_sql` ref to tables not in `public` schema, fix is to store schema for flows, and when recover flows using it~
hence when recovering flow using `raw_sql`, need the same `QueryContext` so that the sql can be parsed as the same logical plan
- local test confirm upgrade metadata is compatible(the new query context field is `#[serde(default)]`)
> fix: store flow query ctx on creation

- src/cmd/src/metasrv.rs
- src/meta-srv/src/lib.rs
- src/meta-srv/src/node_excluder.rs
- typos.toml
adds a "node excluder" for Metasrv to decide when to exclude some nodes in some situation
> feat: node excluder

- config/config.md
- config/metasrv.example.toml
- src/meta-srv/src/metasrv.rs
- src/meta-srv/src/metasrv/builder.rs
Add `enable_region_failover_force` option to bypass the restriction on region failover for local WAL implementations. 
> feat: allow forced region failover for local WAL

- src/index/src/fulltext_index/tokenizer.rs
trun to `EnglishTokenizer` if ascii-only.
> perf: optimize fulltext zh tokenizer for ascii-only text

- .github/scripts/create-version.sh
- .github/workflows/release.yml
Remove duplicated configuration in github action.
create-version output:
```
GITHUB_EVENT_NAME=schedule NIGHTLY_RELEASE_PREFIX=nightly .github/scripts/create-version.sh
NEXT_RELEASE_VERSION is empty, use version from Cargo.toml
0.15.0-nightly-20250427
```
> ci: read next release version from toml by default

- src/mito2/src/memtable/partition_tree.rs
- src/mito2/src/memtable/stats.rs
- src/mito2/src/memtable/time_series.rs
- src/mito2/src/read/scan_region.rs
- **Refactor timestamp updates**: Simplified timestamp range updates in `PartitionTreeMemtable` and `TimeSeriesMemtable` by replacing `update_timestamp_range` with `fetch_max` and `fetch_min` methods for `max_timestamp` and `min_timestamp`.
- Affected files: `partition_tree.rs`, `time_series.rs`
- **Remove unused code**: Deleted the `update_timestamp_range` method from `WriteMetrics` and removed unnecessary imports.
- Affected file: `stats.rs`
- **Optimize memtable filtering**: Streamlined the check for empty memtables in `ScanRegion` by directly using `time_range`.
- Affected file: `scan_region.rs`
> fix: check if memtable is empty by stats

- src/common/meta/src/key.rs
- src/common/meta/src/key/txn_helper.rs
Since greptime-enterprise depends on `txn_helper` module, so make it public.
> chore: make txn_helper pub

- src/meta-srv/src/region/supervisor.rs
Only consider the datanode that reports the failure
> fix: only consider the datanode that reports the failure

- Cargo.toml
Complex query in substrait will reach this decode limit (default to 32 and is not adjustable). Related code is https://github.com/tokio-rs/prost/blob/bdd03fcb8dbe514a3bc2ecfbc7cb8f335d21436c/prost/src/encoding.rs#L37-L44
Related error is something like
```
EngineExecuteQuery: Failed to decode substrait relation: failed to decode Protobuf message
...
PlanRel.rel_type: Plan.relations: recursion limit reached
```
> fix: disable recursion limit in prost

- src/common/meta/src/instruction.rs
- src/datanode/src/heartbeat/handler.rs
- src/datanode/src/heartbeat/handler/flush_region.rs
- src/datanode/src/heartbeat/task_tracker.rs
- src/meta-srv/src/procedure/region_migration.rs
- src/meta-srv/src/procedure/region_migration/downgrade_leader_region.rs
- src/meta-srv/src/procedure/region_migration/flush_leader_region.rs
- src/meta-srv/src/procedure/region_migration/open_candidate_region.rs
- src/meta-srv/src/procedure/region_migration/test_util.rs
- src/meta-srv/src/procedure/test_util.rs
- src/meta-srv/src/procedure/wal_prune.rs
This change helps the system handle region migration more smoothly. By flushing the leader region before downgrading it, we can:
- Minimize the time window where the region is not writable
- Reduce the impact on write operations during region migration
- Added a new `FlushLeaderRegion` state in the region migration procedure
- Modified the region migration flow to flush the leader region before downgrading it
- Added new metrics for tracking flush leader region operation duration
- Added new test cases for the flush leader region functionality
> feat: flush leader region before downgrading

- .github/scripts/update-dev-builder-version.sh
- .github/workflows/release-dev-builder-images.yaml
1. Add the trigger event for the push event when the PR that modifies the `rust-toolchain.toml` or `docker/dev-builder/**` is merged to main;
2. Add `update-dev-builder-image-tag` job to update the dev-builder image tag and create a PR;
> ci: fix the bugs of release-dev-builder-images and add update-dev-builder-image-tag

- src/meta-srv/src/region/supervisor.rs
- src/meta-srv/src/service/admin.rs
- src/meta-srv/src/service/admin/maintenance.rs
1. **Improved Maintenance Mode Handling**
- Added warning logs when skipping failover in maintenance mode
- Added deregistration of failure detectors when maintenance mode is enabled
- Enhanced logging for maintenance mode state changes
2. **API Improvements**
- Changed maintenance mode API response format to JSON **Breaking Change** (However, no downstream component using it for now)
- Added support for multiple HTTP methods:
- GET (for querying status)
- POST (recommended for setting status)
- PUT (deprecated)
- Added deprecation warnings for:
- GET requests with parameters
- PUT method usage
3. **Testing**
- Added comprehensive tests for maintenance mode API
- Tests cover all …
> feat: enhance maintenance mode API and handling

- src/common/procedure-test/src/lib.rs
- src/common/procedure/src/lib.rs
- src/common/procedure/src/local.rs
- src/common/procedure/src/local/runner.rs
- src/common/procedure/src/procedure.rs
- src/common/procedure/src/rwlock.rs
- src/meta-srv/src/procedure/region_migration.rs
- src/meta-srv/src/procedure/region_migration/close_downgraded_region.rs
- src/meta-srv/src/procedure/region_migration/downgrade_leader_region.rs
- src/meta-srv/src/procedure/region_migration/flush_leader_region.rs
- src/meta-srv/src/procedure/region_migration/migration_abort.rs
- src/meta-srv/src/procedure/region_migration/migration_end.rs
- src/meta-srv/src/procedure/region_migration/migration_start.rs
- src/meta-srv/src/procedure/region_migration/open_candidate_region.rs
- src/meta-srv/src/procedure/region_migration/test_util.rs
- src/meta-srv/src/procedure/region_migration/update_metadata.rs
- src/meta-srv/src/procedure/region_migration/update_metadata/downgrade_leader_region.rs
- src/meta-srv/src/procedure/region_migration/update_metadata/rollback_downgraded_region.rs
- src/meta-srv/src/procedure/region_migration/update_metadata/upgrade_candidate_region.rs
- src/meta-srv/src/procedure/region_migration/upgrade_candidate_region.rs
Initially, the region migration procedure was performed at the region level using optimistic locking. However, we later found that optimistic locking did not work well in certain scenarios, so the procedure was changed to run in parallel at the table level instead. Now, with the introduction of an in-memory locking mechanism, we are able to revert back to region-level parallelism. 
1. Introduced a dynamic locking mechanism to the procedure system:
- Added `acquire_lock` and `clean_lock_keys` methods to `ContextProvider` trait
- Moved `rwlock` module to be a public module
- Added `dynamic_key_lock` to `ManagerContext`
- Added test cases for dynamic locking functionality
2. …
> feat: optimize region migration concurrency with fine-grained table lock

- src/meta-srv/src/handler/region_lease_handler.rs
- src/meta-srv/src/region/lease_keeper.rs
- src/metric-engine/src/repeated_task.rs
This PR introduces a new `RegionLeaseInfo` structure in metasrv to track renewed lease region details. The primary goal is to expose region operating status (such as dropping or opening) to other components.
- Introduced `RegionLeaseInfo` structure containing:
- RegionId
- Operating status (whether the region is under dropping, opening)
- Region role (Leader/Follower)
- Updated `CustomizedRegionLeaseRenewer` to use `RegionLeaseInfo` instead of just region role
- Modified region lease renewal logic to include operating status
- Updated all related tests to work with the new structure
> feat(meta): enhance region lease handling with operating status

- src/operator/src/statement/ddl.rs
- tests/cases/standalone/common/flow/flow_advance_ttl.result
- tests/cases/standalone/common/flow/flow_advance_ttl.sql
fix a unintentional breaking change and use streaming mode for flow when found source table have a ttl=instant
> fix: force streaming mode for instant source table

- src/query/src/promql/error.rs
- src/query/src/promql/label_values.rs
- tests-integration/src/test_util.rs
- tests-integration/tests/http.rs
Use cast to build time filter directly instead of adding a projection, which will cause column not found
- https://github.com/GreptimeTeam/greptimedb/pull/5653
- https://github.com/GreptimeTeam/greptimedb/issues/5907
This PR fixes an issue that `label_values()` returns `No field named` error if the following conditions are met:
- The timestamp of the metrics isn't in millisecond resolution
- There are filters in the matcher.
#5653 introduced the cast plan, but it should have other issues in earlier versions, as the timestamp resolution is invalid.
The previous implementation adds a projection node. This PR casts the timestamp previously and removes the cast and additional …
> fix: do not add projection to cast timestamp in label_values

- src/meta-srv/src/error.rs
- src/meta-srv/src/handler/keep_lease_handler.rs
- src/meta-srv/src/lease.rs
- src/meta-srv/src/metasrv/builder.rs
- src/meta-srv/src/procedure/region_migration.rs
- src/meta-srv/src/procedure/region_migration/downgrade_leader_region.rs
- src/meta-srv/src/procedure/region_migration/migration_start.rs
- src/meta-srv/src/procedure/region_migration/test_util.rs
- src/meta-srv/src/region/supervisor.rs
- src/mito2/src/worker/handle_catchup.rs
- src/mito2/src/worker/handle_manifest.rs
This PR improves the region migration error handling and lease management in the meta server. 
1. **Enhanced Lease Management**
- Added `find_datanode_lease_value` helper to check when a datanode last contacted the meta server
- Improved leader downgrade process:
- If datanode has been disconnected longer than region lease period, skip the sleep wait
- If datanode disconnected recently, adjust sleep time based on remaining lease period
- This ensures we don't wait unnecessarily when the datanode is already considered dead
- Added proper error handling for unreachable datanodes (PusherNotFound)
2. **Better Error Handling**
- Added new `DowngradeLeader` error type for better error …
> fix: improve region migration error handling and optimize leader downgrade with lease check

- src/query/src/promql/planner.rs
- tests/cases/standalone/common/promql/binary_time_fn.result
- tests/cases/standalone/common/promql/binary_time_fn.sql
https://github.com/GreptimeTeam/greptimedb/issues/5998
This PR resets the tags and sets fields correctly when creating the empty metric for prom call.
This avoids errors like a tag column not found in the schema.
> fix: reset tags when creating an empty metric in prom call

- Cargo.lock
- Cargo.toml
- src/common/query/src/request.rs
- src/metric-engine/src/metadata_region.rs
- src/mito2/src/engine.rs
- src/mito2/src/engine/projection_test.rs
- src/mito2/src/engine/scan_test.rs
- src/mito2/src/read/scan_region.rs
- src/query/src/dummy_catalog.rs
- src/session/src/context.rs
- src/store-api/src/storage/requests.rs
add a "minimal sequence" in scan request to filter out some unwanted SST files, useful in our "leader-read" feature
> feat: scan with sst minimal sequence

- src/metric-engine/src/engine/create.rs
- src/metric-engine/src/engine/open.rs
- src/metric-engine/src/engine/state.rs
- tests/cases/standalone/common/alter/alter_table.result
- tests/cases/standalone/common/alter/alter_table.sql
- tests/cases/standalone/common/create/create_metric_table.result
- tests/cases/standalone/common/create/create_metric_table.sql
This PR ensures the logical and physical regions have the same timestamp unit. Otherwise, users can create a logical region without a different time unit but finally get an error when they try to insert a record.
To check the time unit, it stores the unit in the state of the physical region.
> fix: ensures logical and physical region have the same timestamp unit

- src/pipeline/src/etl/processor.rs
- src/pipeline/tests/date.rs
As the title suggests, support renaming syntax in `field`.
> chore: support rename syntax in field

- src/datatypes/src/schema/column_schema.rs
- src/datatypes/src/schema/constraint.rs
- src/mito2/src/error.rs
- src/store-api/src/metadata.rs
- tests-fuzz/src/validator/column.rs
- tests-fuzz/targets/ddl/fuzz_alter_table.rs
- tests/cases/standalone/common/alter/alter_table.result
- tests/cases/standalone/common/alter/alter_table.sql
- fix a bug when alter table modify datatype should also modify default value
- added sqlness for aforementioned bug
- actually insert a row in fuzz_alter_table test
- add a `SELECT *` after alter table in fuzz_alter_table to see if data is ok after alter, to debugging a bug in distributed mode that only occur in CI and is also very rare(can't reproduce yet), see https://github.com/GreptimeTeam/greptimedb/actions/runs/14753095448/job/41415159460 this one still haven't been reproduced
> fix: alter table modify type should also modify default value

- Cargo.lock
- docs/how-to/how-to-profile-memory.md
- src/common/mem-prof/Cargo.toml
- src/common/mem-prof/src/error.rs
- src/common/mem-prof/src/jemalloc.rs
- src/common/mem-prof/src/lib.rs
- src/servers/src/http/mem_prof.rs
as title, also pprof format, might also add gen diff flamegraph in the future if needed, i.e.:
```bash
curl -X POST localhost:4000/debug/prof/mem > greptime.hprof
curl -X POST "localhost:4000/debug/prof/mem?output=flamegraph" > greptime.svg
curl -X POST "localhost:4000/debug/prof/mem?output=proto" > greptime.pprof
```
> feat: mem prof can gen flamegraph directly

- .github/workflows/release.yml
The release tasks may create patch for downstream projects when release failed. This patch fixes the issue. 
Also we don't update website for scheduled nightly release.
> ci: only trigger downstream when release success

- src/operator/src/insert.rs
- src/servers/src/otlp/trace/v1.rs
- tests-integration/tests/http.rs
Duplicated `service_name` in default services table `opentelemetry_traces_services` since it turn on append only mode.
> fix!: disable append mode in trace services table

- src/mito2/src/read/range.rs
- src/mito2/src/read/scan_region.rs
- src/mito2/src/sst/parquet.rs
- src/mito2/src/sst/parquet/reader.rs
- src/mito2/src/sst/parquet/row_selection.rs
Introduce `RowGroupSelection` to replace `row_groups: BTreeMap<usize, Option<RowSelection>>`
> refactor: introduce row group selection

- Cargo.lock
- src/flow/Cargo.toml
- src/flow/src/adapter/flownode_impl.rs
- src/flow/src/batching_mode/engine.rs
- src/flow/src/batching_mode/frontend_client.rs
- src/flow/src/batching_mode/task.rs
- src/flow/src/error.rs
- src/flow/src/server.rs
two fixes in this pr:
- flownode choose frontend randomly in batch mode
- not starve lock and hold&retry then ignore(with warn msg) insert requests until all flows are recovered
> fix: flownode chose fe randomly&not starve lock

- src/mito2/src/read.rs
- src/mito2/src/read/plain_batch.rs
- src/mito2/src/sst.rs
- src/mito2/src/sst/parquet.rs
- src/mito2/src/sst/parquet/plain_format.rs
https://github.com/GreptimeTeam/greptimedb/issues/6078
This PR adds a new internal batch struct that wraps the RecordBatch and implements the necessary methods for it.
The ColumnFiller is a helper struct to fill missing columns for a RecordBatch.
> feat: implement PlainBatch struct

- Cargo.lock
- Cargo.toml
- tests-integration/fixtures/docker-compose.yml
> chore: bump rskafka version

- src/mito2/Cargo.toml
- src/mito2/benches/bench_filter_time_partition.rs
- src/mito2/src/lib.rs
- src/mito2/src/memtable.rs
- src/mito2/src/memtable/bulk/part.rs
- src/mito2/src/memtable/simple_bulk_memtable.rs
- src/mito2/src/memtable/time_partition.rs
- src/mito2/src/worker/handle_bulk_insert.rs
- src/store-api/src/metadata.rs
- #5803
This PR adds multiple time partition support in bulk insert ingestion path.
To exploit the performance of vectored ops, this PR manually implements gt_eq&&lt operation instead of using arrow kernel. The benchmark shows that it can be >20% faster:
```bash
cargo bench --bench 'bench_filter_time_partition' -F testing
filter_by_time_range/arrow_impl
time:   [108.70 µs 108.82 µs 108.96 µs]
change: [-0.1400% -0.0237% +0.0841%] (p = 0.71 > 0.05)
No change in performance detected.
Found 10 outliers among 100 measurements (10.00%)
3 (3.00%) high mild
7 (7.00%) high severe
filter_by_time_range/manual_impl
time:   [88.380 µs 88.454 µs 88.550 µs]
change: [-0.2375% -0.0982% +0.0227%] …
```
> feat(bulk): write to multiple time partitions

- src/promql/src/functions/extrapolate_rate.rs
- src/promql/src/range_array.rs
a little 10% improvement. This can also apply to other range operators, but requires some changes to the `range_fn` macro.
> perf: avoid some atomic operation on array slice

- config/config.md
- config/frontend.example.toml
- src/common/telemetry/src/logging.rs
- tests-integration/tests/http.rs
chore: modify slow_query.threshold from 5s to 30s.
> chore: modify default `slow_query.threshold` from 5s to 30s

- src/datanode/src/store.rs
- src/datanode/src/store/fs.rs
- src/mito2/src/access_layer.rs
Change the atomic write dir from `.tmp` to `tmp`. Sometimes, a hidden dir may cause confusion. This is not a breaking change since this directory is "temporary"
> feat: don't hide atomic write dir

- src/mito2/src/access_layer.rs
- src/mito2/src/cache/file_cache.rs
- src/mito2/src/cache/write_cache.rs
- src/mito2/src/sst/parquet/writer.rs
- src/mito2/src/test_util.rs
https://github.com/GreptimeTeam/greptimedb/pull/6109
The tmp files under the atomic write dir may leak if we can't close the parquet/puffin writer.
There are several challenges to fix this:
- Once we construct the parquet/puffin writer, we move out the opendal writer, so we can't use the opendal writer to abort the tmp file.
- The tmp file has a unique suffix under the atomic write dir that we can't know in advance.
- The `abort()` method of the opendal writer is not designed for this purpose.
This PR scans the tmp files under the atomic dir and deletes the files by matching the file names. Because the file id is an unique uuid, so it is safe to do it outside of the opendal …
> fix: clean files under the atomic write dir on failure

- src/cli/src/export.rs
#6070
-- add `--s3-ddl-local-dir` to export sql to local even when `s3` is set and is exporting parquet data file to s3, this is useful for when export client can't access s3 directly(because the *.sql files is created by export client directly)
-- add `--s3-root` to allow state root path separately 
tested locally with and without `--s3-root` option
> feat: export to s3 add more options

- .github/workflows/release.yml
The last step of release job is broken due to previous change. This patch fixes it by adding allocate-runners in `needs` so we can access its output.
> ci: fix release job dependencies

- README.md
etcd as a kv backend service is neither suitable nor recommended in GreptimeDB's use case. For replacement: https://docs.greptime.com/faq-and-others/faq/#will-metasrv-support-storage-backends-like-mysql-or-postgresql
> chore: remove etcd from acknowledgement as not recommended

- src/flow/src/server.rs
- src/frontend/src/instance/grpc.rs
- src/frontend/src/instance/opentsdb.rs
- src/frontend/src/instance/otlp.rs
- src/frontend/src/instance/prom_store.rs
- src/frontend/src/slow_query_recorder.rs
- src/operator/Cargo.toml
- src/operator/src/insert.rs
- src/operator/src/lib.rs
- src/operator/src/req_convert/delete/table_to_region.rs
- src/operator/src/req_convert/insert/table_to_region.rs
- src/operator/src/tests.rs
- src/operator/src/tests/kv_backend.rs
- src/pipeline/src/manager/table.rs
For protocols with default column names like Prometheus Remote Write, the default name must match the destination table's schema, otherwise it will trigger an auto schema change and leading to unexpected behavior, like having two time index columns.
This patch implements an "accommodate" mode that can overwrite the schema in write request with corresponding column name from table schema that already exists.
> feat: accommodate default column name with pre-created table schema

- grafana/dashboards/metrics/cluster/dashboard.json
- grafana/dashboards/metrics/cluster/dashboard.md
- grafana/dashboards/metrics/cluster/dashboard.yaml
- grafana/dashboards/metrics/standalone/dashboard.json
- grafana/dashboards/metrics/standalone/dashboard.md
- grafana/dashboards/metrics/standalone/dashboard.yaml
- src/mito2/src/flush.rs
- src/mito2/src/metrics.rs
- #5803 
1. rename `greptime_mito_flush_errors_total` metric to `greptime_mito_flush_failure_total` for consistency
2. update grafana dashboard to add following panel:
- compaction input/output bytes
- bulk insert handle elasped time in frontend and region worker
> chore: update flush failure metric name and update grafana dashboard

- README.md
Make the docker mount directory same as [.gitignore](https://github.com/GreptimeTeam/greptimedb/blob/main/.gitignore#L60), and not push the data directory.
> docs: change docker run mount directory

- src/flow/src/adapter/flownode_impl.rs
- src/flow/src/batching_mode/state.rs
- src/flow/src/batching_mode/task.rs
- src/flow/src/batching_mode/time_window.rs
- fix flow task run interval by setting it to half of the time window duration，so that flow task will refresh not that frequent
- fix a bug when flow query went wrong can't shutdown flow exec loop
- correct some log msg
> fix(flow): flow task run interval

- .github/scripts/create-version.sh
Add the missing `v` prefix for `NEXT_RELEASE_VERSION`(bring by https://github.com/GreptimeTeam/greptimedb/pull/5986).
> chore: add the missing `v` prefix for `NEXT_RELEASE_VERSION` variable

- .github/workflows/develop.yml
Sqlness and fuzz test are very unstable recently. This patch turns off fail fast to save retry time.
> ci: turn off fail fast strategy

- Cargo.lock
- Cargo.toml
- src/common/grpc/Cargo.toml
- src/common/grpc/benches/bench_flight_decoder.rs
- src/common/grpc/benches/bench_main.rs
- src/common/grpc/src/error.rs
- src/common/grpc/src/flight.rs
- src/operator/src/bulk_insert.rs
- src/store-api/src/metadata.rs
- src/store-api/src/region_request.rs
- Please don't merge until https://github.com/GreptimeTeam/greptime-proto/pull/240 is merged.
- **Update Flight Decoder**: Enhanced `FlightDecoder` in `flight.rs` to support decoding from schema bytes and added methods for decoding record batches.
- **Modify Bulk Insert Logic**: Updated `bulk_insert.rs` to utilize the new `FlightDecoder` methods for handling schema and payload data.
- **Add Benchmarks**: Introduced a new benchmark for the flight decoder in `bench_flight_decoder.rs` and updated `bench_main.rs` to include it.
If the bulk insert request only involves one region, then we can spare one encode on frontend and postpone the decoding to datanode, which can save x10ms …
> perf: optimize bulk encode decode

- src/meta-srv/src/bootstrap.rs
make metasrv `start` not blocking, so that shutdown can properly happen since `start` use `&mut self` and blocking everything after it
> chore: metasrv starting not blocking

- src/partition/src/expr.rs
- src/servers/src/grpc/greptime_handler.rs
- tests-integration/src/grpc/flight.rs
Fix the problem when bulk ingesting record batch with uppercase columns, GreptimeDB will silently return an "internal error" to client.
> fix: bulk insert case sensitive

- Cargo.lock
- src/client/Cargo.toml
- src/client/src/database.rs
- src/client/src/error.rs
- src/client/src/region.rs
- src/common/grpc/benches/bench_flight_decoder.rs
- src/common/grpc/src/error.rs
- src/common/grpc/src/flight.rs
- src/common/query/src/error.rs
- src/operator/src/bulk_insert.rs
- src/servers/src/grpc/flight/stream.rs
- tests-integration/src/grpc/flight.rs
This PR replaces the `common_recordbatch::RecordBatch` and `datatypes::schema::Schema` in `FlightMessage` with arrow version. The motivation of this refactor is that flight is highly coupled with arrow structs and we should make the layers clear.
- **Add `datatypes` Dependency**: Updated `Cargo.lock` and `Cargo.toml` to include the `datatypes` dependency.
- **Schema Conversion and Error Handling**:
- Updated `src/client/src/database.rs` and `src/client/src/region.rs` to handle schema conversion using `Arc` and added error handling for schema conversion.
- Enhanced error handling in `src/client/src/error.rs` and `src/common/grpc/src/error.rs` by adding `ConvertSchema` error and …
> refactor: replace FlightMessage with arrow `RecordBatch` and `Schema`

- src/query/src/promql/planner.rs
- tests/cases/standalone/common/promql/or_operation.result
- tests/cases/standalone/common/promql/or_operation.sql
This PR fixes the issue with field column projection qualifiers in PromQL. When projecting field columns, we now properly find and use the correct qualifier from the schema instead of using potentially incorrect qualifiers.
The qualifiers might have been removed by previous operations:
```rust
// alias the computation exprs to remove qualifier
self.ctx.field_columns = result_field_columns
.iter()
.map(|expr| expr.schema_name().to_string())
.collect();
let field_columns_iter = result_field_columns
.into_iter()
.zip(self.ctx.field_columns.iter())
.map(|(expr, name)| Ok(DfExpr::Alias(Alias::new(expr, None::<String>, name))));
```
Please convert it to a draft if some of the following …
> fix(promql): handle field column projection with correct qualifier

- .github/workflows/nightly-ci.yml
- flake.lock
- flake.nix
This patch switches our nix flake package index to newly released 25.05.
We also disabled `NIX_HARDENING` to bypass an error from jemalloc, see more: https://github.com/tikv/jemallocator/issues/108
Due to resource limitation, I changed CI to run `cargo check` only.
> chore: switch nix index to 25.05 release

- src/operator/src/statement.rs
- src/servers/src/mysql/federated.rs
- tests-integration/tests/sql.rs
Close #6207
Impl `set @@session.time_zone` for MySQL protocol.
> feat: supports @@session.time_zone for mysql

- Cargo.lock
- Cargo.toml
- src/common/test-util/Cargo.toml
- src/common/test-util/src/flight.rs
- src/common/test-util/src/lib.rs
- src/log-store/src/kafka/log_store.rs
- src/log-store/src/raft_engine/log_store.rs
- src/mito2/Cargo.toml
- src/mito2/benches/bench_filter_time_partition.rs
- src/mito2/src/error.rs
- src/mito2/src/memtable/bulk/part.rs
- src/mito2/src/memtable/simple_bulk_memtable.rs
- src/mito2/src/memtable/time_partition.rs
- src/mito2/src/memtable/time_series.rs
- src/mito2/src/region/opener.rs
- src/mito2/src/region_write_ctx.rs
- src/mito2/src/wal.rs
- src/mito2/src/wal/entry_distributor.rs
- src/mito2/src/wal/entry_reader.rs
- src/mito2/src/wal/raw_entry_reader.rs
- src/mito2/src/worker/handle_bulk_insert.rs
- src/operator/src/bulk_insert.rs
- src/store-api/src/logstore.rs
- src/store-api/src/region_request.rs
Please don't merge until https://github.com/GreptimeTeam/greptime-proto/pull/239 is merged first.
Adds support to writing bulk insert requests into WAL (without re-encoding).
For the same setup, enabling WAL for bulk inserts results in ~90ms increase in latency
But no obvious slow down regarding ingestion rate.
> feat(wal): support bulk wal entries

- config/config.md
- config/frontend.example.toml
- config/standalone.example.toml
- src/frontend/src/server.rs
- src/servers/benches/prom_decode.rs
- src/servers/src/http.rs
- src/servers/src/http/prom_store.rs
- src/servers/src/metrics.rs
- src/servers/src/prom_row_builder.rs
- src/servers/src/proto.rs
- src/servers/tests/http/prom_store_test.rs
- tests-integration/src/test_util.rs
- tests-integration/tests/http.rs
- **Code Enhancements**:                                                                                                                                                                                                                                                                                           
- Updated `src/frontend/src/server.rs` and `src/servers/src/http.rs` to support `PromValidationMode` with options: `strict`(default), `lossy`, and `unchecked`.                                                                                                                                                           
- Modified `src/servers/src/http/prom_store.rs` and …
> feat(http): lossy string validation in prom remote write

- src/pipeline/src/error.rs
- src/pipeline/src/manager.rs
- src/pipeline/src/manager/pipeline_cache.rs
- src/pipeline/src/manager/pipeline_operator.rs
- src/pipeline/src/manager/table.rs
- src/pipeline/src/manager/util.rs
- src/servers/src/http/event.rs
- tests-integration/tests/http.rs
~~As mentioned [here](https://github.com/GreptimeTeam/greptimedb/pull/6141#issuecomment-2894561441), remove the schema in the pipeline information and cache key, so that all databases under the same catalog can access the shared pipelines.~~
~~**Note**: This is a breaking change. If the pipeline is already in use, check if pipelines have the same names but different schemas before upgrading.~~
Allow shared pipeline under the same catalog.
1. The newly created pipeline would be labeled under an empty string schema. **Note**, this would include the 'update' process, which means only the empty string schema is getting 'updated' or created.
2. The query of the pipeline would try to …
> chore: shared pipeline under same catalog with compatibility

- src/servers/src/mysql/federated.rs
- tests-integration/tests/sql.rs
The following PR of #6210 
Forgot to support `select @@session.time_zone` to query the session timezone, which is used by mysql python connector:
https://github.com/mysql/mysql-connector-python/blob/5e47983957b0ba833b9428dd542bbecba8898347/mysql-connector-python/lib/mysql/connector/abstracts.py#L1115
> feat: supports select @@session.time_zone

- src/flow/src/batching_mode.rs
- src/flow/src/batching_mode/state.rs
- src/flow/src/batching_mode/task.rs
- src/flow/src/metrics.rs
as title, limit each flow's batching mode query to a limited time range, so each query can be run to complete within reasonable time
> refactor(flow): limit the size of query

- src/flow/src/server.rs
- src/frontend/src/instance/grpc.rs
- src/frontend/src/instance/opentsdb.rs
- src/frontend/src/instance/otlp.rs
- src/frontend/src/instance/prom_store.rs
- src/frontend/src/slow_query_recorder.rs
- src/operator/src/insert.rs
- src/pipeline/src/manager/table.rs
- tests-integration/src/test_util.rs
- tests-integration/tests/http.rs
https://github.com/GreptimeTeam/greptimedb/issues/6226
InfluxDB line-protocol can ingest multiple fields. We should only accommodate the field (value) name when we ensure the protocol is single-value.
- OpenTSDB, Prometheus Remote Write are single-value protocols
- gRPC, InfluxDB line protocol are multi-value protocols
This PR adds a flag `is_single_value` to indicate whether the protocol is single-value. It also adds a test for the case in #6226
> fix: do not accommodate fields for multi-value protocol

- src/meta-srv/src/procedure/wal_prune/manager.rs
as title, sleep longer for test `test_wal_prune_ticker` so that not all ticks are skipped, hence assert can almost certainly success(also longer interval since windows timer default resolution is 15.6ms)
> chore: test sleep longer

- src/common/recordbatch/src/error.rs
- src/common/recordbatch/src/lib.rs
- src/operator/src/statement/copy_table_to.rs
- src/servers/src/error.rs
- tests/cases/standalone/common/copy/copy_from_fs_csv.result
- tests/cases/standalone/common/copy/copy_from_fs_csv.sql
- tests/cases/standalone/common/copy/copy_from_fs_json.result
- tests/cases/standalone/common/copy/copy_from_fs_json.sql
- tests/cases/standalone/common/copy/copy_from_fs_parquet.result
- tests/cases/standalone/common/copy/copy_from_fs_parquet.sql
- tests/cases/standalone/common/copy/copy_to_fs.result
- tests/cases/standalone/common/copy/copy_to_fs.sql
fixes #6240
This PR fixes the JSON type export in COPY TABLE TO statement. Previously, it directly output the internal representation of JSON type, now it correctly converts JSON type to JSON string format.
- Add `SendableRecordBatchMapper` to handle type conversion in `RecordBatch` stream
- Implement JSON type to JSON string conversion logic
- Updated test cases to verify JSON type export functionality
> fix: convert JSON type to JSON string in COPY TABLE TO statment

- src/cli/src/export.rs
- src/common/datasource/src/object_store.rs
- src/common/datasource/src/object_store/oss.rs
- src/table/src/requests.rs
#6105 
Support export cli export to OSS
Currently, both copying from/to tables/databases and external tables utilize build_backend to create object storage, but only S3 is supported at this time. This PR extends support to OSS.
cli example:
`greptime cli export --addr 127.0.0.1:4000 --oss --oss-bucket <your-bucket> --oss-endpoint <your-endopint> --oss-access-key-id <id> --oss-access-key-secret <secret>`
`greptime cli export --addr 127.0.0.1:4000 --target data --oss --oss-bucket <your-bucket> --oss-endpoint <your-endopint> --oss-access-key-id <id> --oss-access-key-secret <secret>`
`greptime cli export --addr 127.0.0.1:4000 --target schema --oss --oss-bucket <your-bucket> …
> feat: Support export cli export to OSS

- src/frontend/src/instance/jaeger.rs
- src/servers/src/http/jaeger.rs
- src/servers/src/query_handler.rs
- tests-integration/tests/http.rs
Support to get trace ID with a time range.
NOTE: The grafana jaeger plugin disables time parameters by default; you should enable it explicitly
> refactor: support to get trace id with time range

- Cargo.lock
- Cargo.toml
- src/query/src/promql/planner.rs
- tests/cases/standalone/common/promql/set_operation.result
- tests/cases/standalone/common/promql/set_operation.sql
We should consider NULL equals NULL when joining in PromQL. Theoretically, they are simply not considered when comparing two rows, hence "vacant equals vacant".
This patch updates the forked datafusion to include a fix patch where the variable `null_equals_null` are dropped in optimizer.
> fix: null value handling on PromQL's join

- config/config.md
- config/datanode.example.toml
- config/frontend.example.toml
- src/client/src/client.rs
- src/client/src/client_manager.rs
- src/client/src/database.rs
- src/client/src/region.rs
- src/cmd/src/frontend.rs
- src/common/grpc/src/channel_manager.rs
- src/common/grpc/src/flight.rs
- src/datanode/src/datanode.rs
- src/datanode/src/region_server.rs
- src/datanode/src/tests.rs
- src/frontend/src/server.rs
- src/servers/src/grpc.rs
- src/servers/src/grpc/flight.rs
- src/servers/src/grpc/flight/stream.rs
- src/servers/src/grpc/greptime_handler.rs
- tests-integration/src/grpc/flight.rs
- tests-integration/src/test_util.rs
- tests-integration/tests/http.rs
- **Configuration Updates**:
- Added `grpc.flight_compression` option to `config/config.md`, `config/datanode.example.toml`, and `config/frontend.example.toml` to specify compression modes for Arrow IPC service.
- **Code Enhancements**:
- Updated `FlightEncoder` in `src/common/grpc/src/flight.rs` to support compression modes.
- Modified `RegionServer` and `DatanodeBuilder` in `src/datanode/src/datanode.rs` and `src/datanode/src/region_server.rs` to handle `FlightCompression`.
- Integrated `FlightCompression` in `src/servers/src/grpc.rs` and `src/servers/src/grpc/flight.rs` to manage compression settings.
- **Testing and Integration**:
- Updated test utilities and integration …
> chore: add option for arrow flight compression mode

- src/mito2/src/read/scan_region.rs
- src/mito2/src/read/scan_util.rs
- tests/cases/distributed/explain/analyze.result
- tests/cases/distributed/explain/order_by.result
- tests/cases/distributed/optimizer/windowed_sort.result
- tests/cases/distributed/tql-explain-analyze/analyze.result
- tests/cases/standalone/common/aggregate/distinct.result
- tests/cases/standalone/common/aggregate/multi_regions.result
- tests/cases/standalone/common/order/order_by.result
- tests/cases/standalone/common/order/windowed_sort.result
- tests/cases/standalone/common/range/nest.result
- tests/cases/standalone/common/select/prune.result
- tests/cases/standalone/common/select/skipping_index.result
- tests/cases/standalone/common/select/tql_filter.result
- tests/cases/standalone/common/tql/general_table.result
- tests/cases/standalone/common/tql/partition.result
- tests/cases/standalone/optimizer/last_value.result
- tests/cases/standalone/optimizer/order_by.result
- tests/cases/standalone/optimizer/windowed_sort.result
- tests/cases/standalone/tql-explain-analyze/analyze.result
Make it more readable. An example (try copy and format it in your editor):
```json
{"partition_count":0, "num_mem_ranges":0, "num_files":0, "num_file_ranges":0, "projection": ["ts", "log_uid", "log_message", "log_status", "p", "host_id", "host_name", "service_id", "service_name", "service_instance_id", "service_instance_name", "container_id", "container_name", "pod_id", "pod_name", "cluster_id", "cluster_name", "node_id", "node_name", "ns_id", "ns_name", "workload_id", "workload_name"], "metrics_per_partition": [{"partition":0, "metrics":{"prepare_scan_cost":"272.571µs", "build_reader_cost":"0ns", "scan_cost":"0ns", "convert_cost":"0ns", "yield_cost":"0ns", …
```
> feat: organize EXPLAIN ANALYZE VERBOSE's output in JSON format

- src/cmd/tests/load_config_test.rs
Resolve https://github.com/GreptimeTeam/greptimedb/issues/6281.
Fix: always use linux path style in windows platform unit tests. Revert to the original test logic before [6050](https://github.com/GreptimeTeam/greptimedb/pull/6050/files#diff-4dc2f9e84416f3abdbb0b37524f7052d65853d29ec14e9af441982d01ea28eb2).
> fix: always use linux path style in windows platform unit tests

- src/frontend/src/instance.rs
- src/session/src/context.rs
- src/session/src/lib.rs
- #5866 
This update enhances the query context by incorporating connection information, which allows for more detailed session management. Key changes include:
- **`src/frontend/src/instance.rs`**: Updated to utilize `query_ctx.conn_info().to_string()` for retrieving connection information instead of using a placeholder string.
- **`src/session/src/context.rs`**: Added a `conn_info` field to `QueryContext` and introduced a `conn_info()` method for accessing it. The `QueryContextBuilder` was also updated to handle `conn_info`.
- **`src/session/src/lib.rs`**: Adjusted the `Session` to include `conn_info` during the query context construction process.
Now we can display client info …
> chore: add connection info to `QueryContext`

- src/servers/src/http/event.rs
- src/servers/src/http/header.rs
* we need to accept `application/json; charset=utf-8` header
* now we can only handler `UTF-8` charset string. But the header is not forced to be consistent with the body. So I think we can do without the charset restriction.
> fix: event api content type only check type and subtype

- src/promql/src/extension_plan/empty_metric.rs
- src/query/src/promql/planner.rs
- src/servers/src/http/prometheus.rs
- tests-integration/src/tests/promql_test.rs
- tests-integration/tests/http.rs
- tests/cases/standalone/common/promql/set_operation.result
- tests/cases/standalone/common/promql/set_operation.sql
- tests/cases/standalone/common/tql/basic.result
- tests/cases/standalone/common/tql/case_sensitive.result
This PR ignores missing columns and tables in PromQL, especially when using the `OR` set operator. This improves the compatibility of PromQL.
- The planner returns an `EmptyMetric` during planning when it can't find the table. The `EmptyMetric` will return 0 rows.
- The planner checks the label existence and ignores missing labels while planning `AggregateExpr`.
Users may only report some labels or metrics under specific conditions, so their PromQLs may refer to some labels/metrics that are not currently present.
It also modifies the `series` query API to return an empty result when the table to query doesn't exist.
Please convert it to a draft if some of the following conditions …
> fix: ignore missing columns and tables in PromQL

- src/frontend/src/instance.rs
When registering MySQL queries, we should always respect the process id in session context.
> fix: carry process id in query ctx

- src/operator/src/statement/tql.rs
- src/sql/src/parsers/tql_parser.rs
- src/sql/src/statements/tql.rs
- tests/cases/standalone/tql-explain-analyze/analyze.result
- tests/cases/standalone/tql-explain-analyze/analyze.sql
Support `TQL EXPLAIN [VERBOSE] [FORMAT] <format>`. But at present only `ANALYZE` supports changing output format.
> feat: support setting FORMAT in TQL ANALYZE/VERBOSE

- src/metric-engine/src/engine/create.rs
This PR remove `MEMTABLE_TYPE` option from metadata region options to ensure metadata region always use default memtable.
> fix(metric): prevent setting memtable type for metadata region

- src/mito2/src/memtable/time_partition.rs
- src/mito2/src/region/opener.rs
- src/mito2/src/region/version.rs
- src/servers/src/http/handler.rs
- **`time_partition.rs`**: Introduced `series_count` method to calculate the total timeseries count across all time partitions.
- **`opener.rs`**: Enhanced logging to include the total timeseries replayed during WAL replay.
- **`version.rs`**: Added `series_count` method to `VersionControlData` for approximating timeseries count in the current version.
> chore: print series count after wal replay

- src/mito2/src/memtable/partition_tree.rs
- src/mito2/src/memtable/partition_tree/dict.rs
Fixes the kv mismatch issue caused by outdated pk index in dictionary in `PartitionTreeMemtable`.
> fix: reordered write cause incorrect kv

- src/meta-srv/src/bootstrap.rs
- src/meta-srv/src/election/rds/mysql.rs
- src/meta-srv/src/error.rs
This PR enhances the reliability of the MySQL election client by adding timeouts and reconnection mechanisms. The changes address two critical issues:
- The election client not reconnecting after connection loss
- Missing query/execution timeouts causing potential hangs
> fix(meta): enhance mysql election client with timeouts and reconnection

- config/datanode.example.toml
- config/standalone.example.toml
- src/datanode/src/config.rs
- src/datanode/src/store/s3.rs
- tests-integration/tests/http.rs
* feat: expose enable_virtual_host_style for s3 storage
* docs: update examples
* test: fix config test
https://github.com/GreptimeTeam/greptimedb/issues/6373
cherry pick https://github.com/GreptimeTeam/greptimedb/pull/5696
> feat: expose virtual_host_style config for s3 storage (#5696)

- Cargo.lock
- config/config.md
- config/datanode.example.toml
- config/flownode.example.toml
- config/frontend.example.toml
- config/metasrv.example.toml
- config/standalone.example.toml
- src/cmd/tests/load_config_test.rs
- src/common/telemetry/Cargo.toml
- src/common/telemetry/src/logging.rs
Add `otlp_export_protocol` config to support export trace data through gRPC and HTTP protocol.
> refactor: add `otlp_export_protocol` config to support export trace data through gRPC and HTTP protocol

- src/mito2/src/engine.rs
- src/mito2/src/read.rs
- src/mito2/src/read/scan_region.rs
- src/mito2/src/read/scan_util.rs
- src/mito2/src/read/seq_scan.rs
- src/mito2/src/read/series_scan.rs
- src/mito2/src/read/stream.rs
- src/mito2/src/read/unordered_scan.rs
- src/servers/src/grpc/flight/stream.rs
- src/store-api/src/storage/requests.rs
Because sometimes we want to scan out `Batch` directly, instead of getting a `RecordBatch` stream. So this PR split out the `Batch` to `RecordBatch` convention from scan stream.
> refactor: scan `Batch`es directly

- src/servers/src/http.rs
- src/servers/src/http/handler.rs
- src/servers/src/http/result/csv_result.rs
- src/servers/tests/http/http_handler_test.rs
- tests-integration/tests/http.rs
Close #6067 
Close #6333 
* Supports new response formats: `CsvWithNames` and `CsvWithNamesAndTypes`
* Fixed #6333, which is caused by JSON array type in trace data.
Once this PR is merged, we should update the dashboard to use `format=csvWithNames` instead of `format=csv` when downloading result CSVs. @sunchanglong @ZonaHex
> feat: supports CsvWithNames and CsvWithNamesAndTypes formats

- Cargo.lock
- Cargo.toml
- src/common/function/Cargo.toml
- src/common/function/src/aggrs.rs
- src/common/function/src/aggrs/count_hash.rs
- src/common/function/src/function_registry.rs
- src/common/query/src/lib.rs
- tests/cases/standalone/common/function/count_hash.result
- tests/cases/standalone/common/function/count_hash.sql
A new aggregate function `count_hash(<col>)` for computing approximately distinct values. In most cases it should be more accurate than `hll`, if there is no hash collision. And it's faster than both `hll` and `count(distinct)`
> feat: implement count_hash aggr function

- src/servers/src/http.rs
API users may need healthcheck endpoint for validating connections. However, our original `/health` check route is hidden as internal API. This patch duplicate it to `/v1/health` as well.
> feat: introduce /v1/health for healthcheck from external

- src/servers/src/http.rs
- src/servers/src/prom_row_builder.rs
- src/servers/src/proto.rs
- Change how pipeline processor handles string validation according to configured string validaiton mode.
- **Refactor `decode_string` Functionality**:
- Moved `decode_string` logic into `PromValidationMode` as a method `decode_string`.
- Updated all references to use the new method.
- Files affected: `http.rs`, `prom_row_builder.rs`, `proto.rs`.
> fix(http): apply string validation mode to pipeline processor

- src/cli/src/lib.rs
- src/cli/src/metadata/snapshot.rs
CLI tools will print interactive results to stdout(instead of log output). This is particularly necessary when users disable log output via `--log-level=none`, as they still need to see the CLI execution results.
> refactor: move `#[allow(clippy::print_stdout)]` to lib level

- src/catalog/src/process_manager.rs
- src/common/frontend/src/selector.rs
- **Enhance Error Handling in `process_manager.rs`:** Improved error handling by adding a warning log for failing nodes in the `list_process` method. This ensures that the process listing continues even if some nodes fail to respond.
- **Add Error Type Import in `process_manager.rs`:** Included the `Error` type from the `error` module to handle errors more effectively within the `ProcessManager` implementation.
> fix: skip failing nodes when gathering porcess info

- src/pipeline/src/etl/ctx_req.rs
- src/pipeline/src/lib.rs
- src/servers/src/http/loki.rs
- tests-integration/tests/http.rs
close #4800
This PR adds support for the Loki API to run pipelines.
The process becomes a little complicated; see the diagram below for a quick glimpse.
For entering the pipeline process
1. The original ts (in nanosecond timestamp datatype), Loki text line, and all the labels and structure metadata are merged into one big map
2. This map is used as the input data of the pipeline
> feat(pipeline): support Loki API

- Cargo.lock
- Cargo.toml
https://github.com/GreptimeTeam/greptimedb/issues/6354
Bump main repo version to 0.16.0
> chore: bump version to 0.16

- src/meta-srv/src/procedure/region_migration.rs
- src/meta-srv/src/procedure/region_migration/close_downgraded_region.rs
- src/meta-srv/src/procedure/region_migration/downgrade_leader_region.rs
- src/meta-srv/src/procedure/region_migration/manager.rs
- src/meta-srv/src/procedure/region_migration/migration_abort.rs
- src/meta-srv/src/procedure/region_migration/test_util.rs
- src/meta-srv/src/procedure/region_migration/upgrade_candidate_region.rs
- src/meta-srv/src/region/supervisor.rs
- src/meta-srv/src/service/procedure.rs
- tests-integration/tests/region_migration.rs
Add `RegionMigrationTriggerReason` in `RegionMigrationProcedureTask`
> refactor: add `RegionMigrationTriggerReason` in `RegionMigrationProcedureTask`

- src/common/meta/src/key/tombstone.rs
- src/flow/src/adapter.rs
This PR fixes a critical bug(introduced by #3727) in the `TombstoneManager::move_values()` method where the destination keys chunking was incorrectly using source keys instead of destination keys.
> fix: fix dest_keys chunks bug in TombstoneManager

- Cargo.toml
- src/cli/src/lib.rs
> fix: allow clippy::print_stdout in cli crate

- src/catalog/src/kvbackend/manager.rs
- tests/cases/standalone/common/create/metric_engine_partition.result
- tests/cases/standalone/common/create/metric_engine_partition.sql
follow up of https://github.com/GreptimeTeam/greptimedb/pull/6385
Remap the column index to the correct one in logical table's schema. Otherwise it may panic or get an incorrect result when retrieving column from logical table's schema with index from physical table's schema
> fix: remap column indices on overriding logical table partitions

- src/cli/src/bench.rs
- src/common/meta/src/ddl/alter_logical_tables.rs
- src/common/meta/src/ddl/alter_table.rs
- src/common/meta/src/ddl/create_logical_tables.rs
- src/common/meta/src/ddl/create_table.rs
- src/common/meta/src/ddl/physical_table_metadata.rs
- src/common/meta/src/ddl/table_meta.rs
- src/common/meta/src/ddl/test_util.rs
- src/common/meta/src/ddl/test_util/create_table.rs
- src/common/meta/src/ddl/test_util/datanode_handler.rs
- src/common/meta/src/ddl/tests/alter_logical_tables.rs
- src/common/meta/src/ddl/tests/alter_table.rs
- src/common/meta/src/ddl/tests/create_logical_tables.rs
- src/common/meta/src/ddl/tests/create_table.rs
- src/common/meta/src/ddl/utils.rs
- src/common/meta/src/key/table_info.rs
- src/common/meta/src/rpc/ddl.rs
- src/meta-srv/src/procedure/utils.rs
- src/operator/src/statement/ddl.rs
- src/store-api/src/metric_engine_consts.rs
- src/store-api/src/region_engine.rs
- src/table/src/metadata.rs
- src/table/src/table/numbers.rs
#6429
This PR implements the persistence of column ids in table metadata.
- Enhanced `build_new_physical_table_info` with column id handling
- DDL Operations: Update all major DDL operations to handle column ids
- Create table, alter table, create logical tables, alter logical tables
- Testing: Add column ID validation tests for DDL operations
> feat: persist column ids in table metadata

- src/datatypes/src/schema/column_schema.rs
> fix: add backward compatibility for `SkippingIndexOptions` deserialization

- src/cmd/src/frontend.rs
These changes enhance the accessibility of command-related structures and fields, facilitating external usage and integration.
- Made `subcmd` field in `Command` struct public.
- Made `SubCommand` enum public.
- Made `config_file` and `env_prefix` fields in `StartCommand` struct public.
> chore: expose some config

- src/query/src/optimizer/windowed_sort.rs
- src/query/src/part_sort.rs
- tests/cases/standalone/optimizer/windowed_sort.result
- tests/cases/standalone/optimizer/windowed_sort.sql
as title, stricter window sort apply condition:
1. only if underlying region scan's distribution is not PerSeries
2. only if all physical plan between `RegionScanExec` and `SortExec` is either projection/filter or `CoalesceBatchesExec` 
> fix: stricter win sort condition

- src/frontend/src/instance.rs
- tests-integration/tests/sql.rs
Before this patch, empty query will cause the mysql command line hang:
After patching, it will raise an error:
```sql
Invalid SQL, error: empty statements.
```
> fix: empty statements hang

- src/servers/src/proto.rs
Skip the NaN value in Prometheus remote write for pipeline execution.
> fix: skip nan in prom remote write pipeline

- src/mito2/src/memtable/bulk/part.rs
- src/mito2/src/sst/parquet.rs
- src/mito2/src/sst/parquet/format.rs
- src/mito2/src/sst/parquet/reader.rs
- src/mito2/src/test_util.rs
- src/mito2/src/test_util/sst_util.rs
Allow using the sequence in the FileMeta to set the Batch sequence when the sequence stored in the parquet is 0.
> feat: override batch sequence by the sequence in FileMeta

- Cargo.lock
- Cargo.toml
- src/common/meta/Cargo.toml
- src/datanode/Cargo.toml
- src/frontend/Cargo.toml
- src/metric-engine/Cargo.toml
- src/mito2/Cargo.toml
- src/operator/Cargo.toml
- src/query/Cargo.toml
- src/servers/Cargo.toml
These modules are using tracing crate but they didn't declare it as a dependency. This becomes an issue when using them as a library.
> fix: add tracing dependencies

- src/pipeline/src/etl.rs
- src/pipeline/src/etl/transform/transformer/greptime.rs
With pipeline doc version 2, if the transform section is set, then the ts index is calculated in the transform process.
While filling the rest of the columns, we can skip calculating and setting the ts column.
> chore: skip calc ts in doc 2 with transform

- src/pipeline/src/etl.rs
- src/pipeline/src/etl/processor.rs
- src/pipeline/src/etl/processor/filter.rs
- src/servers/src/pipeline.rs
- tests-integration/tests/http.rs
This PR adds a filter processor to filter out lines during pipeline execution.
For now, we only implement string matching. We can extend the functionality later if needed.
A simple config example looks like this
```
processors:
- date:
field: time
formats:
- "%Y-%m-%d %H:%M:%S%.3f"
- filter:
field: name
targets: 
- John
transform:
- field: name
type: string
- field: time
type: time
index: timestamp
```
The filter processor has the following config options:
1. `field`(or `fields`): the variable that is used. It can be a field list; any match would filter the line.
2. `mode`(optional): default to `simple`, which means simple string matching.
3. `match_op`(optional): if the mode is …
> feat(pipeline): filter processor

- .gitignore
- src/servers/src/http.rs
- src/servers/src/http/handler.rs
- src/servers/src/http/result.rs
- src/servers/src/http/result/null_result.rs
- src/servers/tests/http/http_handler_test.rs
- tests-integration/tests/http.rs
Close #6528 
Introduces a `null` format, like ClickHouse's, that concisely displays only the row count and elapsed time, making it useful for evaluating query performance.
```bash
curl -X POST \
-H 'Authorization: Basic {{authorization if exists}}' \
-H 'Content-Type: application/x-www-form-urlencoded' \
-d "sql=SELECT * FROM monitor" \
http://localhost:4000/v1/sql\?db\=public\&format\=null
1 rows in set.
Elapsed: 0.006 ms.
```
> feat: supports null reponse format for http API

- Cargo.lock
- Cargo.toml
- src/common/event-recorder/Cargo.toml
- src/common/event-recorder/src/error.rs
- src/common/event-recorder/src/lib.rs
- src/common/event-recorder/src/recorder.rs
**Adds the following traits to define the event recorder(`src/common/event-recorder`)**
- `Event`: Event trait defines the interface for events that can be recorded and persisted to system tables:
```rust
pub trait Event: Send + Sync + Debug {
/// Returns the type of the event.
fn event_type(&self) -> &str;
/// Returns the timestamp of the event. Default to the current time.
fn timestamp(&self) -> Timestamp {
Timestamp::current_time(TimeUnit::Nanosecond)
}
/// Returns the JSON bytes of the event as the payload.
fn json_payload(&self) -> Result<String>;
/// Add the extra schema to the event with the default schema.
fn extra_schema(&self) -> Vec<ColumnSchema> {
vec![]
}
/// Add the …
```
> feat: introduce common event recorder

- Cargo.lock
- src/client/src/database.rs
- src/client/src/region.rs
- src/common/grpc/Cargo.toml
- src/common/grpc/benches/bench_flight_decoder.rs
- src/common/grpc/src/flight.rs
- src/common/test-util/src/flight.rs
- src/mito2/src/memtable/bulk/part.rs
- src/mito2/src/region/opener.rs
- src/mito2/src/region_write_ctx.rs
- src/mito2/src/worker/handle_write.rs
- src/operator/src/bulk_insert.rs
- src/servers/src/grpc/flight.rs
- src/servers/src/grpc/flight/stream.rs
- tests-integration/src/grpc/flight.rs
Make Flight encode/decode RecordBatch with dictionary arrays.
> feat: Flight supports RecordBatch with dictionary arrays

- src/client/src/database.rs
fix bug when error is not retryable, continue loop again
> fix: breaking loop when not retryable

- src/mito2/src/compaction.rs
- src/mito2/src/compaction/task.rs
- src/mito2/src/flush.rs
- src/mito2/src/metrics.rs
- src/mito2/src/request.rs
- src/mito2/src/schedule/remote_job_scheduler.rs
- src/mito2/src/test_util/scheduler_util.rs
- src/mito2/src/worker.rs
- src/mito2/src/worker/handle_manifest.rs
- src/mito2/src/worker/handle_write.rs
This PR adds a new metric `greptime_mito_request_wait_time` to collect the wait time of requests submitted to the worker.
It also adjusts the write stall metrics:
- greptime_mito_write_stall_total now is the total stalled requests count
- greptime_mito_write_stalling_count is the current stalled requests count in the worker
> feat: add metrics for request wait time and adjust stall metrics

- src/common/meta/src/cache/flow/table_flownode.rs
- src/common/meta/src/cache_invalidator.rs
- src/common/meta/src/instruction.rs
- src/meta-srv/src/handler/remap_flow_peer_handler.rs
fix flow mirror insert cache not updated when flownode's address change
> fix: flow mirror cache

- src/common/event-recorder/src/recorder.rs
Add `sleep(Duration::from_millis(500)).await;` to sleep for a while to let the event be sent to the event handler.
> fix: unit test failed by adding necessary sleep function to ensure the time seqence

- src/common/error/tests/ext.rs
> fix: windows path in error tests

- Cargo.lock
- Cargo.toml
- src/common/grpc-expr/src/alter.rs
- src/common/meta/src/ddl/alter_table/executor.rs
- src/common/meta/src/ddl/alter_table/region_request.rs
- src/metric-engine/src/data_region.rs
- src/mito2/src/engine/alter_test.rs
- src/operator/src/expr_helper.rs
- src/store-api/src/metadata.rs
- src/store-api/src/region_request.rs
- src/table/src/metadata.rs
- src/table/src/requests.rs
This PR refactors the index handling to support multiple index operations (set/unset) in a single alter request.
- Add enum variants in pb: SetIndexes/UnsetIndexes
- Changed data structure of `table::requests::AlterKind` : Single index option -> vectors of index options
- Refactored the logic for setting and unsetting indexes in both `RegionMetadataBuilder` and `TableMeta` 
> refactor: support multiple index operations in single alter region request

- tests/runner/src/env.rs
- tests/runner/src/main.rs
This patch for better experience when sqlness test for regrex
like : 
```cli
cargo sqlness -t simple_histogram
```
start one instance is fine, also make a print message better
> fix: only start one instance one regrex sqlness test

- src/query/src/window_sort.rs
poll result stream more often when window sort and polling for input stream, this should reduce time to first bytes time for many cases, before this window sort would wait for first pending of input stream then to emit result
> feat: poll result stream more often

- config/config.md
- config/frontend.example.toml
- src/cmd/tests/load_config_test.rs
- src/flow/src/adapter.rs
- src/operator/src/statement.rs
- src/operator/src/statement/set.rs
- src/query/src/datafusion.rs
- src/query/src/dist_plan.rs
- src/query/src/dist_plan/analyzer.rs
- src/query/src/dist_plan/analyzer/fallback.rs
- src/query/src/dist_plan/analyzer/test.rs
- src/query/src/metrics.rs
- src/query/src/options.rs
- src/query/src/query_engine/state.rs
- src/session/src/context.rs
- tests-integration/tests/http.rs
add a fallback to only push down table scan when `PlanRewriter` failed to push down as many node as possible, this is useful when we encounter a previously unknown bug in `PlanRewriter` or encounter known but unfixed bugs like alias bug to provide at least some level of usability  
> feat: fallback when failed to push down using `DistPlanner`

- src/servers/src/grpc/prom_query_gateway.rs
- src/servers/src/http/prometheus.rs
- src/servers/src/http/result/prometheus_resp.rs
queries like `metric_a + metric_b` will not have a `__name__` label now
> fix: only return the __name__ label when there is one

- src/mito2/src/access_layer.rs
- src/mito2/src/cache/write_cache.rs
- src/mito2/src/compaction/compactor.rs
- src/mito2/src/flush.rs
- src/mito2/src/metrics.rs
- src/mito2/src/sst/parquet.rs
- src/mito2/src/sst/parquet/writer.rs
Refine metrics that tracks the per-stage cost time during flush and compaction.
> chore: refine metrics tracking the flush/compaction cost time

- Cargo.lock
- src/index/Cargo.toml
This patch maybe can imporve a little performance
as diff:
for jieba-rs: https://github.com/messense/jieba-rs/releases/tag/v0.8.0
for tantivy-jieba: https://github.com/jiegec/tantivy-jieba/commit/003fa13b6e094cef8f0134ae8c04e0551b9a0c41
> chore: update jieba tantivy-jieba and tantivy version

- Cargo.lock
- Cargo.toml
- fix https://github.com/GreptimeTeam/greptimedb/issues/6628
The SIGSEGV is from the `s.into()`, which convert the `Statement`:
- from `sqlparser-rs-6d6510b5e3af714f`
- to `sqlparser-0.54.0`
> fix: bump greptime-sqlparser to avoid convert statement overflow

- config/config.md
- config/datanode.example.toml
- config/standalone.example.toml
- src/mito2/src/config.rs
- src/mito2/src/engine.rs
- src/mito2/src/engine/scan_test.rs
- src/mito2/src/error.rs
- src/mito2/src/read/scan_region.rs
- src/mito2/src/read/seq_scan.rs
- src/mito2/src/read/series_scan.rs
- src/mito2/src/read/unordered_scan.rs
- tests-integration/tests/http.rs
Adds an option `max_concurrent_scan_files` to restrict the maximum number of files allowed to scan.
- For SeqScan, it uses the max files of all partition ranges to evaluate the limit.
- For SeriesScan, it uses all files to evaluate the limit.
Currently, this is a per-query limitation in order to avoid a large query that reads too many files to merge.
> feat: Add option to limit the files reading simultaneously

- src/common/meta/src/sequence.rs
As stated in the comment for the `peek` function
> fix: sequence peek with remote value

- src/log-query/src/log_query.rs
- src/query/src/log_query/planner.rs
`filters` is a Vector of `ColumnFilters`, and inside `ColumnFilters` it requires a column. In `LogExpr::Filter`, it has an `expr` field along with `filter: ContentFilter`. There is some duplication about column reference in these cases. Make it hard to use. This patch made a refactor to how a column is provided to filters
> feat: use column expr with filters in LogQuery

- src/sql/src/parsers/explain_parser.rs
- src/sql/src/statements/statement.rs
Maybe related to https://github.com/GreptimeTeam/greptimedb/pull/6634
I find https://github.com/GreptimeTeam/greptimedb/pull/6645 will stack overflowed on a totally unrelated place (range query test). And from the debugger, `stacker` chooses not to grow the stack size every time.
I suspect this is caused by some large enum or struct. And it turns out this is at least related. Before `Statement` is 1856 size, because of `Explain` which is the same size as well. After boxing it the `Statement`'s size shrinks to 384, and the overflow in #6645 is gone
> fix: box Explain node in Statement to reduce stack size

- src/mito2/benches/memtable_bench.rs
- src/mito2/src/memtable.rs
- src/mito2/src/memtable/bulk/context.rs
- src/mito2/src/memtable/bulk/part.rs
- src/mito2/src/memtable/bulk/part_reader.rs
- src/mito2/src/memtable/bulk/row_group_reader.rs
This PR modifies the EncodedBulkPartIter to support reading RecordBatches from an encoded bulk part.
It also refactors BulkPartEncoder to accept `BulkPart` instead of `Mutation`. This mainly helps create an encoded part for testing the iterator.
> feat: EncodedBulkPartIter iters flat format and returns RecordBatch

- src/common/procedure/src/error.rs
- src/meta-srv/src/error.rs
This PR adjusts the error mappings to ensure that errors with incorrect or overly generic status codes are surfaced with more informative messages. This improves observability and enhances the user experience during debugging.
Previously, `error.output_msg()` would suppress `Internal` and `Unknown` error by default, resulting in vague error messages like:
```
{"status":"Failed","error":"Internal error: 1003"}
```
This often confused users when running sql such as `admin procedure_state('id')`.
> refactor: refine error status code mappings

- src/datatypes/src/timestamp.rs
- src/mito2/src/read.rs
- src/mito2/src/read/flat_merge.rs
- src/mito2/src/sst/parquet/flat_format.rs
https://github.com/GreptimeTeam/greptimedb/issues/6505
This PR implements a sync iterator `MergeIterator` for merging a list of sorted batch iterators.
- The merge algorithm is very close to the existing [MergeReader](https://github.com/GreptimeTeam/greptimedb/blob/bbab35f285fefbb0438d3458c7780aa93eaa48c6/src/mito2/src/read/merge.rs)
- The differences between the `MergeIterator` and `MergeReader` are:
- `MergeIterator` is sync.
- `MergeIterator` uses a `BatchBuilder` ported from datafusion to interleave rows from batches.
- `MergeIterator` supports `RecordBatch`.
- It extracts the heap algorithm into a struct `MergeAlgo`, so we can implement an async version easily later.
- Use …
> feat: Implements an iterator to merge RecordBatches

- src/servers/src/http.rs
- src/servers/src/http/handler.rs
- tests-integration/tests/http.rs
New HTTP endpoint `sql/format?sql=` for formatting SQLs.
It would become prettier in the future https://docs.rs/sqlparser/0.58.0/sqlparser/index.html#pretty-printing
> feat: new HTTP API for formatting SQL

- src/servers/src/http/result/prometheus_resp.rs
#6717 
also fix these on http
histogram_quantile(-0.5, rate(demo_api_request_duration_seconds_bucket[1m]))
histogram_quantile(0.1, rate(demo_api_request_duration_seconds_bucket[1m]))
histogram_quantile(0.5, rate(demo_api_request_duration_seconds_bucket[1m]))
histogram_quantile(0.75, rate(demo_api_request_duration_seconds_bucket[1m]))
histogram_quantile(0.95, rate(demo_api_request_duration_seconds_bucket[1m]))
histogram_quantile(0.90, rate(demo_api_request_duration_seconds_bucket[1m]))
histogram_quantile(0.99, rate(demo_api_request_duration_seconds_bucket[1m]))
histogram_quantile(1, rate(demo_api_request_duration_seconds_bucket[1m]))
histogram_quantile(1.5, …
> fix: http and tql should return the same value for nuknown

- Cargo.lock
- src/store-api/Cargo.toml
- src/store-api/src/region_request.rs
- **Added `num_enum` Dependency**: Updated `Cargo.lock` and `Cargo.toml` to include `num_enum` for enum conversion functionality.
- Files: `Cargo.lock`, `src/store-api/Cargo.toml`
- **Enhanced `PathType` Enum**: Implemented `TryFromPrimitive` for `PathType` to enable conversion from primitive types.
- Files: `src/store-api/src/region_request.rs`
- **Added Unit Tests**: Introduced tests to verify the conversion of `PathType` enum to and from primitive types.
- Files: `src/store-api/src/region_request.rs`
> chore: impl cast from primitives to PathType

- src/log-query/src/log_query.rs
- src/query/src/log_query/planner.rs
* add u64 for EqualValue and set expr is true when filter is empty
> chore: add u64 for EqualValue and set expr is true when filter is empty

- src/mito2/src/manifest/action.rs
##6602
as title, previous pr failed to notice this incompatibility with region truncate action in manifest files, so if you truncate a table in old version, then immediately upgrade to new version, db wouldn't understand the manifest action files(luckily it didn't break manifest checkpoint files), ~so this fix make sure region truncate deser now first try v2(latest version) of itself, then try v1(old version) and convert it to v2~, added `#[serde(flatten)]` and `#[serde(untagged)]` instead
> fix: truncate manifest action compat

- src/mito2/src/read/flat_dedup.rs
https://github.com/GreptimeTeam/greptimedb/issues/6505
Follow-up of https://github.com/GreptimeTeam/greptimedb/pull/6695
Implements the `FlatLastNonNull` strategy for flat format.
The difference between this strategy and `FlatLastRow` is that `FlatLastNonNull` takes the latest non null value for each field.
However, it has to handle deletion specially to avoid a deleted row overriding the latest row's field. It tracks whether the duplicated rows of the last key contain a deletion. If they have, then we should not include non-null fields from the next batch.
It ports all tests from the old dedup strategy.
Please convert it to a draft if some of the following conditions are not …
> feat: Implements last-non-null dedup strategy for flat format

- Cargo.lock
- Cargo.toml
- flake.nix
- src/common/version/Cargo.toml
This patch removes build-time dependency to libgit2, libz and potentially libssl.
> fix: refine shadowrs dependency, remove libgit2, libz and potentally libssl

- .github/scripts/check-version.sh
- .github/workflows/release.yml
https://github.com/GreptimeTeam/greptimedb/releases/tag/v0.15.5
Rename `should-push-latest-tag` to `is-current-version-latest`.
Some pick release should not update the downstream repositories. For example, if the latest version is v0.16.0 and the pick version is v0.15.5, skip the update.
> ci: add `is-current-version-latest` check to `helm-charts/homebrew-greptime` bump jobs

- src/common/function/src/admin.rs
- src/common/function/src/admin/add_region_follower.rs
- src/common/function/src/admin/flush_compact_region.rs
- src/common/function/src/admin/flush_compact_table.rs
- src/common/function/src/admin/migrate_region.rs
- src/common/function/src/admin/reconcile_catalog.rs
- src/common/function/src/admin/reconcile_database.rs
- src/common/function/src/admin/reconcile_table.rs
- src/common/function/src/admin/remove_region_follower.rs
- src/common/function/src/flush_flow.rs
- src/common/function/src/function.rs
- src/common/function/src/function_factory.rs
- src/common/function/src/function_registry.rs
- src/common/function/src/system.rs
- src/common/function/src/system/procedure_state.rs
- src/common/macro/src/admin_fn.rs
- src/common/query/src/signature.rs
- src/operator/src/error.rs
- src/operator/src/statement/admin.rs
- tests/cases/distributed/information_schema/cluster_info.result
- tests/cases/distributed/information_schema/cluster_info.sql
- tests/cases/standalone/common/function/admin/flush_compact_table.result
- tests/cases/standalone/common/function/admin/flush_compact_table.sql
- tests/cases/standalone/common/insert/logical_metric_table.result
- tests/cases/standalone/common/insert/logical_metric_table.sql
- tests/cases/standalone/information_schema/cluster_info.result
- tests/cases/standalone/information_schema/cluster_info.sql
#6749 
* Refactor `admin_fn` macro with DataFusion async udf. Now we can call admin functions with `select`.
* Remove `AsyncFunction` trait.
* Fixed the tests.
FYI. The codebase got larger, but most of the additions are test code.
> refactor: refactor admin functions with async udf

- src/meta-srv/src/metasrv/builder.rs
- src/meta-srv/src/procedure/test_util.rs
- src/meta-srv/src/procedure/wal_prune.rs
- src/meta-srv/src/procedure/wal_prune/manager.rs
- src/meta-srv/src/procedure/wal_prune/utils.rs
#6722
Follow-up to #6741
This PR simplifies the WAL pruning procedure and moves non-critical steps outside the procedure.
> refactor: simplify WAL Pruning procedure part2

- src/common/meta/src/cache/flow/table_flownode.rs
as title, no logging when init table_flow cache unless not empty
> chore: no logging when init table_flow cache if empty

- config/config.md
- config/datanode.example.toml
- config/flownode.example.toml
- config/frontend.example.toml
- config/metasrv.example.toml
- config/standalone.example.toml
- src/common/telemetry/src/logging.rs
Allow custom headers configured for otel exporter. Note this is for collecting traces from GreptimeDB itself.
> feat: support for custom headers in otel exporter

- src/flow/src/batching_mode/state.rs
- src/flow/src/batching_mode/task.rs
as title, so that when query failed(usually due to frontend oom kill or timeout) return dirty windows back and can try again with smaller time window
> feat: provide  plan info when flow exec

- src/frontend/src/frontend.rs
- src/frontend/src/heartbeat.rs
- src/frontend/src/server.rs
- tests-integration/src/cluster.rs
- tests/conf/frontend-test.toml.template
- tests/runner/src/server_mode.rs
as title, so by default oss version wouldn't start a internal port
> chore: make internal grpc optional

- src/metric-engine/src/engine.rs
- src/metric-engine/src/engine/flush.rs
- src/mito2/src/access_layer.rs
- src/mito2/src/engine.rs
- src/mito2/src/engine/basic_test.rs
- src/mito2/src/region.rs
- src/mito2/src/worker.rs
- src/store-api/src/lib.rs
- src/store-api/src/region_engine.rs
- src/store-api/src/sst_entry.rs
* Add `sst_entry::{ManifestSstEntry, StorageSstEntry}`
* Implement `all_ssts_from_manifest` and `all_ssts_from_storage` for mito engine
> feat(mito): list SSTs from manifest and storage

- src/common/function/src/function_factory.rs
* Visibility issues are triggered if the `admin_fn` macro is used in another crate
> chore: modifying the visibility of the ScalarFunctionFactory field

- src/meta-srv/src/lease.rs
- src/meta-srv/src/metasrv.rs
- src/meta-srv/src/selector/lease_based.rs
- src/meta-srv/src/selector/load_based.rs
- src/meta-srv/src/selector/round_robin.rs
- src/meta-srv/src/service/admin/node_lease.rs
- tests-integration/src/cluster.rs
This PR fixes a time unit mismatch bug in the `lookup_frontends` function. The function was accepting `lease_secs: u64` parameter (expecting seconds), but the caller was passing `FRONTEND_HEARTBEAT_INTERVAL_MILLIS`.
> fix: time unit mismatch in `lookup_frontends` function

- src/mito-codec/src/row_converter/sparse.rs
- src/mito2/src/read/compat.rs
- src/mito2/src/sst.rs
- src/mito2/src/sst/parquet/flat_format.rs
- src/mito2/src/sst/parquet/format.rs
- https://github.com/GreptimeTeam/greptimedb/issues/6505
- https://github.com/GreptimeTeam/greptimedb/issues/6078
Implements a struct FlatConvertFormat to convert RecordBatches from the old format to the flat format
- It decodes primary keys according to the projection and adds the decoded array to the record batch
- For sparse encoding, the flat format doesn't store decoded columns now, so this struct can also help convert the record batch.
Adds FlatConvertFormat to FlatReadFormat. The `FlatReadFormat::new()` provides a flag to control whether it `FlatReadFormat` needs to convert record batches.
> feat: add FlatConvertFormat to convert record batches in old format to the flat format

- src/servers/src/http/prometheus.rs
for a query like `sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster="$cluster"}) by (namespace)`, it should not return `__name__` label in the result.
expect:
actual:
> fix: follow promql rule for hanndling label of aggr

- src/client/src/inserter.rs
- src/common/event-recorder/src/recorder.rs
- src/frontend/src/events.rs
- src/meta-srv/src/metasrv/builder.rs
- src/operator/src/insert.rs
- tests-integration/src/grpc.rs
#6721
This PR adds support for configuring TWCS time window through insert operation hints and sets a 1-day time window for the `region_statistic`, `events` table.
> feat: add support for TWCS time window hints in insert operations

- src/mito2/src/memtable.rs
- src/mito2/src/read/prune.rs
- src/mito2/src/read/scan_util.rs
- src/mito2/src/sst/parquet/file_range.rs
- src/mito2/src/sst/parquet/reader.rs
- https://github.com/GreptimeTeam/greptimedb/issues/6505
- https://github.com/GreptimeTeam/greptimedb/issues/6078
Adds some utilities for implementing scanners
- scan_flat_mem_ranges
- scan_flat_file_ranges
Adds the following method to the IterBuilder trait:
- is_record_batch
- build_record_batch_iter
Implements `FlatPruneReader` to filter record batches and `FlatRowGroupReader` to read and convert batches in a row group.
> feat: functions and structs to scan flat format file and mem ranges

- src/meta-srv/src/handler/persist_stats_handler.rs
#6721 
rename `region_statistics` to `region_statistics_history`
> feat: rename `region_statistics` to `region_statistics_history`

- .github/workflows/develop.yml
chore: run `pull-test-deps-images.sh` before docker compose to avoid rate limit.
> chore: run `pull-test-deps-images.sh` before docker compose  to avoid rate limit

- src/common/error/src/status_code.rs
Internal errors are by design discarded on the server side when converting to gRPC status responses. This results in clients only seeing generic "internal error" messages without specific details about what went wrong, making debugging and troubleshooting difficult.
This PR adds error logging in the `define_into_tonic_status` macro to capture detailed error information on the server side before the error details are stripped for the client response.
> chore: add server-side error logging to improve observability in gRPC

- src/mito2/src/compaction/compactor.rs
- src/mito2/src/sst/file_purger.rs
1. Add `stop()` for `LocalFilePurger`;
2. Add `stop_file_purger()` for `CompactionRegion` by using `stop()` of `LocalFilePurger`
> refactor: add stop methods for `LocalFilePurger` and `CompactionRegion`

- src/common/meta/src/error.rs
- src/common/meta/src/wal_options_allocator/topic_creator.rs
- src/log-store/src/error.rs
- src/log-store/src/kafka/client_manager.rs
Introduced in #3379
Saw the error when I was trying to use Azure Event Hubs service (the kafka service on Azure):
```text
2025-08-28T06:51:29.050931Z  WARN rskafka::connection: Failed to connect to broker e=error connecting to broker "10.224.0.6:9093": IO Error: invalid peer certificate: certificate not valid for name "10.224.0.6"; certificate is only valid for DnsName("*.servicebus.windows.net") or DnsName("servicebus.windows.net")
```
> fix: no need to early lookup DNS for kafka broker

- config/config.md
- config/datanode.example.toml
- config/standalone.example.toml
- src/mito2/src/config.rs
- tests-integration/tests/http.rs
This PR enlarges the default max concurrent file limit in mito. In metrics workload, it is easy to have a `1h` time window and a query is easy to reach this limit. Although we may improve the compaction strategy under this workload @v0y4g3r 
> chore: enlarge max file limit to 384

- src/flow/src/batching_mode/engine.rs
- src/flow/src/batching_mode/task.rs
- tests/cases/distributed/flow-tql/flow_tql.result
- tests/cases/standalone/flow-tql/flow_tql.result
- tests/cases/standalone/flow-tql/flow_tql.sql
as title, fix flow use promql query without aggregation node auto created table will be wrong
- now if aggr node is not found using tql, it will determine first f64 column as val column, and all string column as tag
- also change the val column's name from "val" to datafusion's expr name
so that for case which tql eval might return multiple float64 values case(like `count_values`) there wouldn't be multiple same name "val" column
> fix(flow): promql auto create table

- src/common/meta/src/reconciliation/utils.rs
- src/meta-srv/src/region/flush_trigger.rs
This PR contains two bug fixes:
- Ignore Reserved Column IDs: Modified `build_table_meta_from_column_metadatas` to filter out reserved column IDs when calculating the next column ID
- Fix Panic on Empty Regions: Moved the empty check in `RegionFlushTrigger::persist_leader_regions` to prevent panic when chunks() is called on an empty list
> fix: ignore reserved column IDs and prevent panic on chunk_size is zero

- src/mito2/src/access_layer.rs
- src/mito2/src/sst/file_purger.rs
- src/mito2/src/sst/index.rs
- src/mito2/src/sst/index/indexer/abort.rs
- src/mito2/src/sst/index/indexer/finish.rs
- src/mito2/src/sst/index/intermediate.rs
- src/puffin/src/puffin_manager/stager/bounded_stager.rs
* Prune per-SST and per-region intermediate dirs
* Background delete on init; add stager recovery log
> fix: prune intermediate dirs on index finish and region pruge

- .github/actions/setup-greptimedb-cluster/with-remote-wal.yaml
- src/common/error/src/status_code.rs
- src/common/meta/src/instruction.rs
- src/common/meta/src/key/topic_region.rs
- src/datanode/src/heartbeat/handler.rs
- src/datanode/src/heartbeat/handler/open_region.rs
- src/datanode/src/heartbeat/handler/upgrade_region.rs
- src/log-store/src/kafka/log_store.rs
- src/log-store/src/kafka/periodic_offset_fetcher.rs
- src/log-store/src/kafka/worker/fetch_latest_offset.rs
- src/meta-srv/src/metrics.rs
- src/meta-srv/src/procedure/region_migration/open_candidate_region.rs
- src/meta-srv/src/procedure/region_migration/upgrade_candidate_region.rs
- src/meta-srv/src/region/flush_trigger.rs
- src/metric-engine/src/engine/catchup.rs
- src/mito2/src/compaction.rs
- src/mito2/src/engine/catchup_test.rs
- src/mito2/src/manifest/manager.rs
- src/mito2/src/region.rs
- src/mito2/src/region/opener.rs
- src/mito2/src/test_util.rs
- src/mito2/src/test_util/scheduler_util.rs
- src/mito2/src/worker/handle_catchup.rs
- src/store-api/src/logstore/provider.rs
- src/store-api/src/region_request.rs
- tests/cases/standalone/common/information_schema/region_statistics.result
- tests/cases/standalone/common/information_schema/region_statistics.sql
#6722 
This PR addresses incorrect flushed entry ID initialization for remote WAL regions:
- Initialize `RegionManifestManager` with current WAL `latest_entry_id` on creation
Other fixes:
- Set `topic_latest_entry_id` correctly for remote WAL regions with empty memtables(after replay memtable)
- Ensure always persist the newer `ReplayCheckpoint`.
- Update KafkaLogStore to maintain accurate topic statistics
- Simplify region flush logic by removing active/inactive distinction
> fix: initialize remote WAL regions with correct flushed entry IDs

- src/mito2/src/memtable/bulk.rs
- src/mito2/src/memtable/bulk/part.rs
- https://github.com/GreptimeTeam/greptimedb/issues/6505
Initial implementation of the write/read capability for the bulk memtable.
- For performance reasons, the bulk memtable only supports `write_bulk()`.
- The memtable contains raw bulk parts and encoded bulk parts. In this PR, the encoded parts are still unused.
- Implements iterator builders to scan bulk parts and encoded parts.
> feat: implement basic write/read methods for bulk memtable

- .cargo/config.toml
sqlness always recompiles. `ring`'s build script might be the reason. sqlness and greptimedb share the same ring but overlap each other's compile results: `dependency on `build_script_build` is newer than we are 1757023792.664006568s > 1757023474.770973656s`. put sqlness into another dir seems to work for me
> feat: put sqlness into a separated dir

- src/query/src/planner.rs
- tests/cases/standalone/common/tql/tql-cte.result
- tests/cases/standalone/common/tql/tql-cte.sql
- closes #6906
wrap them in a subquery alias so they can be referenced using cte name
> fix: wrap tql cte in a subquery alias

- tests/runner/src/env.rs
- tests/runner/src/util.rs
This PR fixed Nightly CI can't run in Windows operating system, I assume but can't make sure if rust edition was upgrade to 2024 cause this problem, because there not have enough document for it.
Seem like this is an old question of Rust, because document say:
> The search path to be used may be controlled by setting the PATH environment variable on the Command, but this has some implementation limitations on Windows (see issue #37519).
So I am thinking the best solution is using absolute path.
Relates to https://github.com/rust-lang/rust/issues/37519
Relates to https://github.com/GreptimeTeam/greptimedb/commit/c9377e7c5a59eb37fdfc1ef38cd48f611434c262
Nightly CI log link: …
> fix(path): fix program lookup failure on Windows CI

- src/query/src/optimizer/count_wildcard.rs
fallback to use `count(1)` instead of `count(ts)` for `count(*)` when multiple inputs are found
> fix: count(1) instead of count(ts) when >1 inputs

- src/datanode/src/tests.rs
- src/file-engine/src/engine.rs
- src/metric-engine/src/engine.rs
- src/metric-engine/src/engine/read.rs
- src/mito2/src/compaction/compactor.rs
- src/mito2/src/engine.rs
- src/mito2/src/engine/bump_committed_sequence_test.rs
- src/mito2/src/engine/edit_region_test.rs
- src/mito2/src/flush.rs
- src/mito2/src/manifest/action.rs
- src/mito2/src/manifest/manager.rs
- src/mito2/src/manifest/tests/checkpoint.rs
- src/mito2/src/region/opener.rs
- src/mito2/src/region/version.rs
- src/mito2/src/region_write_ctx.rs
- src/mito2/src/request.rs
- src/mito2/src/test_util/version_util.rs
- src/mito2/src/worker/handle_manifest.rs
- src/mito2/src/worker/handle_write.rs
- src/query/src/optimizer/test_util.rs
- src/store-api/src/region_engine.rs
- src/store-api/src/region_request.rs
This PR allows region worker to bump the region sequence while handling region edit requests. That sequence will also be assigned to the files to add in the `RegionEdit` request so that each ingested SST files will have a overriding sequence number assigned by the region worker.
> chore: bump sequence on region edit

- src/log-query/src/log_query.rs
- src/query/src/log_query/planner.rs
> chore: modify  LogExpr AggrFunc

- Cargo.lock
- Cargo.toml
as title, added a extension field to heartbeat request
> chore: update proto

- src/query/src/promql/planner.rs
- tests/cases/standalone/common/tql/case_sensitive.result
- tests/cases/standalone/common/tql/case_sensitive.sql
Haven't figured out why this behavior changed. But I added a sqlness case for it.
> fix: match promql column reference in case sensitive way

- src/auth/src/lib.rs
- src/auth/src/permission.rs
- src/auth/src/user_info.rs
- src/auth/src/user_provider.rs
- src/auth/src/user_provider/static_user_provider.rs
- src/auth/src/user_provider/watch_file_user_provider.rs
- src/plugins/src/frontend.rs
- tests-integration/src/standalone.rs
- tests-integration/src/test_util.rs
- tests-integration/tests/http.rs
- tests-integration/tests/sql.rs
Close #6725 
Adds permission-mode support to the static user provider, enabling role-based access control with read-only, write-only, and read-write permissions.
The provider now accepts `username:permission_mode=password`. The optional `permission_mode` can be `rw`, `ro`, or `wo`, for example:
- `greptime_user=greptime_pwd` or `greptime_user:rw=greptime_pwd`: read-write
- `greptime_user:ro=greptime_pwd`: read-only
- `greptime_user:wo=greptime_pwd`: write-only
Backwards compatible with the old format (default to `rw`).
> feat: supports permission mode for static user provider

- src/common/function/src/aggrs/aggr_wrapper.rs
- src/query/src/dist_plan/analyzer/test.rs
- src/query/src/dist_plan/commutativity.rs
due to bad support in datafusion and substrait, aggr with order by/filter have some issues when using/serde-ing, so disable step aggr for those case for now until those issues get fixed&properly tested:
- disable step aggr for aggr func with order by/filter
- set state function's return type to all nullable for case when input is empty but need a state(which usually will be null)
> fix: not step when aggr have order by/filter

- src/sql/src/parsers/tql_parser.rs
- tests/cases/standalone/common/tql/basic.result
- tests/cases/standalone/common/tql/basic.sql
- tests/cases/standalone/common/tql/tql-cte.result
- tests/cases/standalone/common/tql/tql-cte.sql
#7007 
TQL parameters support complex time expressions (e.g., `date_trunc('day', now() - interval '1' day)`) that evaluate to literal values.
> feat: supports expression in TQL params

- src/auth/src/user_provider.rs
- src/auth/src/user_provider/static_user_provider.rs
- src/auth/src/user_provider/watch_file_user_provider.rs
As the title suggests.
For watch file user provider:
- Before: a not-exist file means no authentication check
- After: throws an error and stop initialization
> chore: disable file not exist on watch_file_user_provider

- src/query/src/dist_plan/analyzer/utils.rs
as title, not warning when encounter unknown plan node when tracking alias
> chore: not warning
