.github/pull_request_template.md
ISSUE_TEMPLATE/bug_report.yml
ISSUE_TEMPLATE/config.yml
ISSUE_TEMPLATE/enhancement.yml
ISSUE_TEMPLATE/feature_request.yml

This pull request intents to help our contributors to open an issue or submit any proposal easier according to the community guidelines
- Add pull request template which incorporates CLA 
- Add issue template:
- disable blank issue creation
- bug report
- feature request
- enhancement

chore: add issue&pr template

---

README.md

Add RustPython's Acknowledgement
add RustPython to README
add RustPython to README

docs: add RustPython to README's acknowledgement

---

README.md

- current blog url response as 404

fix: update blog address in readme

---

.github/workflows/release.yml

- fix nightly build error of missing git tag, the error message is in [5864923014](https://github.com/GreptimeTeam/greptimedb/actions/runs/3501105200/jobs/5864923014);
- fix typo;

fix: fix nightly build error and fix typo

---

.github/workflows/develop.yml
typos.toml

- add spell check with typos in ci workflow
(#589)

ci: add spell check with typos

---

src/datanode/src/server/grpc/ddl.rs
src/sql/src/statements.rs

Added tests for statements parse_column_default_constraint and sql_column_def_to_grpc_column_def
https://github.com/GreptimeTeam/greptimedb/pull/591

test: added tests for statements methods

---

.github/workflows/coverage.yml

Reverts GreptimeTeam/greptimedb#671
It doesn't work 🥲

ci: Revert "ci: change CI unit test trigger"

---

src/common/time/src/timestamp.rs
src/datatypes2/src/arrow_array.rs
src/datatypes2/src/data_type.rs
src/datatypes2/src/lib.rs
src/datatypes2/src/timestamp.rs
src/datatypes2/src/type_id.rs
src/datatypes2/src/types.rs
src/datatypes2/src/types/timestamp_type.rs
src/datatypes2/src/value.rs
src/datatypes2/src/vectors.rs
src/datatypes2/src/vectors/eq.rs
src/datatypes2/src/vectors/timestamp.rs

Impl timestamp datatypes and vectors in datatypes2

feat: impl datatypes2/timestamp

---

.github/pull_request_template.md

Fix pull request template tasks default state to "unfinished"
NA

fix: pr template task default state

---

src/datatypes2/src/scalars.rs
src/datatypes2/src/timestamp.rs
src/datatypes2/src/value.rs
src/datatypes2/src/vectors/eq.rs
src/datatypes2/src/vectors/helper.rs
src/datatypes2/src/vectors/operations/filter.rs
src/datatypes2/src/vectors/operations/find_unique.rs
src/datatypes2/src/vectors/operations/replicate.rs

chore: add more tests for timestamp

---

src/common/function/src/scalars/aggregate/mean.rs
src/common/function/src/scalars/aggregate/polyval.rs
src/common/function/src/scalars/math/pow.rs
src/common/function/src/scalars/numpy/interp.rs

fix compile error for mean/polyval/pow/interp ops

fix: fix compile error for mean/polyval/pow/interp ops

---

src/common/function/src/scalars/aggregate.rs
src/common/function/src/scalars/aggregate/argmin.rs
src/common/function/src/scalars/aggregate/percentile.rs
src/common/function/src/scalars/aggregate/scipy_stats_norm_cdf.rs
src/common/function/src/scalars/aggregate/scipy_stats_norm_pdf.rs
src/common/function/src/scalars/expression/binary.rs
src/common/function/src/scalars/expression/ctx.rs
src/common/function/src/scalars/expression/unary.rs
src/common/function/src/scalars/numpy.rs
src/common/function/src/scalars/numpy/clip.rs
src/common/function/src/scalars/numpy/interp.rs
src/common/query/src/error.rs
src/datatypes/src/types/primitive_type.rs
src/datatypes/src/value.rs

fix argmin/percentile/clip/interp/scipy_stats_norm_pdf compiler errors
- #555

fix: fix argmin/percentile/clip/interp/scipy_stats_norm_pdf errors

---

src/common/function/src/scalars/aggregate/argmax.rs
src/common/function/src/scalars/aggregate/mean.rs
src/common/function/src/scalars/aggregate/polyval.rs
src/common/function/src/scalars/math/pow.rs
src/common/function/src/scalars/numpy/clip.rs
src/common/function/src/scalars/test.rs
src/common/function/src/scalars/timestamp/from_unixtime.rs

fix: fix other compile error in common-function

---

src/sql/src/parsers/create_parser.rs

Give an example CREATE TABLE SQL from the [document](https://docs.greptime.com/getting-started/create-a-time-series-table)
```sql
CREATE TABLE system_metrics (
host STRING,
idc STRING,
ts TIMESTAMP NOT NULL,
PRIMARY KEY(host, idc),
TIME INDEX(ts)
);
```
There are two special column specifications PRIMARY KEY and TIME INDEX. The first one is used to define primary keys (or tags in some systems), and the second is to define which column is the special timestamp column.
For TIMESTAMP column, a simplification is to change the grammar to
ts TIMESTAMP TIME INDEX,
By doing so, it
need not to write NOT NULL, this is implied by TIME INDEX keywords
need not to specify TIME INDEX in …

feat: support timestamp new syntax

---

Cargo.lock
src/cmd/src/frontend.rs
src/cmd/src/standalone.rs
src/servers/Cargo.toml
src/servers/src/tls.rs

Signed-off-by: zyy17 <zyylsxm@gmail.com>
add tls option in frontend cli options

refactor: add tls option in frontend cli options

---

src/catalog/src/error.rs
src/catalog/src/helper.rs
src/catalog/src/local/manager.rs
src/catalog/src/system.rs
src/catalog/src/tables.rs
src/common/query/src/physical_plan.rs
src/mito/src/engine.rs
src/mito/src/manifest/action.rs
src/mito/src/table.rs
src/mito/src/table/test_util/mock_engine.rs

Fix compiler errors in catalog and mito crates.
- #555

fix: Fix compiler errors in catalog and mito crates

---

src/frontend/src/table.rs
src/sql/src/statements.rs
src/storage/Cargo.toml
src/table/Cargo.toml

Change the column's property `is_nullable` to be true by default when creating tables.
#560

feat: change column's default property to nullable

---

Cargo.lock
src/common/error/src/status_code.rs
src/datanode/src/instance/sql.rs
src/frontend/src/instance.rs
src/frontend/src/instance/distributed.rs
src/frontend/src/server.rs
src/servers/src/http.rs
src/servers/src/http/handler.rs
src/servers/src/postgres/auth_handler.rs
src/servers/src/postgres/server.rs
src/servers/src/query_handler.rs
src/servers/tests/http/influxdb_test.rs
src/servers/tests/http/opentsdb_test.rs
src/servers/tests/http/prometheus_test.rs
src/servers/tests/mod.rs
src/servers/tests/postgres/mod.rs
tests-integration/Cargo.toml
tests-integration/tests/http.rs

This patch adds database existence check on http api. It refactors design in #758 and merged `CatalogManager` into `SqlQueryHandler` because these two worked together at most time I feel there is little need to separate them.

feat: check database existence on http api

---

.github/workflows/coverage.yml
src/common/substrait/src/df_logical.rs

Use lld for coverage to avoid OOM in GitHub actions

ci: Use lld for coverage

---

src/meta-srv/src/bootstrap.rs

This pr mainly extract some functions from "bootstrap_meta_srv" function.

chore: extract some functions from "bootstrap_meta_srv" function

---

src/mito/README.md

Today I learned when touching fish: how to align things to the right side.

docs: align Jeremy Clarkson to the right side

---

src/datanode/src/error.rs
src/datanode/src/instance/grpc.rs

fix: remove boilerplate message from GRPC error output

---

src/datanode/src/error.rs

fix: test failure

---

Cargo.lock
src/client/src/database.rs
src/client/src/error.rs
src/common/error/Cargo.toml
src/common/error/src/status_code.rs
src/servers/src/error.rs
tests/cases/standalone/select/dummy.result
tests/runner/Cargo.toml
tests/runner/src/env.rs

Adjust the user-facing error message to make it precise and concrete.

refactor: adjust outermost error message

---

src/promql/src/error.rs
src/promql/src/planner.rs

Support converting normal aggregator (sum, avg, min/max etc) into `LogicalPlan`. This patch also supports planning on `MatrixSelector` but is currently lacking expressions to test.

feat: plan some aggregate expr in PromQL planner

---

Cargo.lock
src/promql/Cargo.toml
src/promql/src/planner.rs
src/query/Cargo.toml
src/query/src/parser.rs

update promql-parser to `fec3c8bcee982b8add2a77d07818d3cbe92b89fe`,  to include https://github.com/GreptimeTeam/promql-parser/pull/23

feat: update promql-parser to commit fec3c8b

---

src/promql/src/error.rs
src/promql/src/functions.rs
src/promql/src/functions/idelta.rs
src/promql/src/functions/increase.rs
src/promql/src/lib.rs
src/promql/src/range_array.rs

Implement PromQL range functions `increase`, `idelta` and `irate`

feat: impl `increase` and `irate`/`idelta` in PromQL

---

Cargo.lock
src/common/error/src/ext.rs
src/promql/Cargo.toml
src/promql/src/error.rs
src/promql/src/extension_plan/normalize.rs
src/promql/src/planner.rs
src/query/Cargo.toml
src/query/src/parser.rs

bump promql-parser to include the latest changes

chore(deps): bump promql-parser

---

tests/README.md

paste it from greptime-docs repo

docs: document sqlness-runner usage

---

docs/rfcs/2023-02-01-table-compaction.md

chore: fix rfc typo

---

src/datanode/src/error.rs
src/datanode/src/instance/grpc.rs
src/datanode/src/sql.rs
src/datanode/src/sql/create.rs
src/frontend/src/instance/distributed.rs
src/frontend/src/instance/distributed/grpc.rs
tests/cases/distributed/catalog/schema.result
tests/cases/distributed/catalog/schema.sql
tests/cases/standalone/catalog/schema.result
tests/cases/standalone/catalog/schema.sql

Support `CREATE [DATABASE | SCHEMA] IF NOT EXISTS db` stmt.
close #789

feat: create database if not exists

---

src/datanode/src/mock.rs

This pr mainly fix: thread that reports the heartbeat panics in unit test.
#1077

fix: thread that reports the heartbeat panics in unit test

---

CONTRIBUTING.md

This tiny PR fixes all markdownlint issues in CONTRIBUTING.md as well as fixes a typo.
- [N/A]  I have written the necessary rustdoc comments.
- [N/A]  I have added the necessary unit tests and integration tests.

style(contributingmd): fix markdown issues and typos

---

src/datanode/src/instance/sql.rs
src/frontend/src/instance.rs
src/sql/src/parsers/copy_parser.rs
src/sql/src/statements/copy.rs

Implement the `Copy From` parser based on #1081 
#1081

feat: implement Copy From parser

---

src/common/grpc-expr/src/insert.rs

support timestamp precision in gRPC service
https://github.com/GreptimeTeam/greptimedb-client-go/pull/27

fix(grpc): support timestamp precision

---

CONTRIBUTING.md

Add description on how to run tests
- [NA]  I have written the necessary rustdoc comments.
- [NA]  I have added the necessary unit tests and integration tests.
Resolves #1119

docs(contributingmd): add run tests commands

---

Cargo.lock
src/datanode/Cargo.toml
src/datanode/src/error.rs
src/datanode/src/instance/sql.rs
src/datanode/src/sql.rs
src/datanode/src/sql/copy_table_from.rs
src/datanode/src/tests/instance_test.rs
src/table/src/requests.rs

We can leave the following tasks to new contributors. It's a good starting for those who want to contribute to the project at university.
```
COPY [<database>.]<table_name>
FROM { '<path>/[<filename>]' }
[ [ WITH ]
(
[ FORMAT =  { parquet } ]
[ PATTERN = '<regex_pattern>' ]
)
]
[ [ CONNECTION ]
(
[ ENDPOINT = '<uri>' ]
[ ACCESS_KEY_ID = '<key_id>' ]
[ SECRET_ACCESS_KEY = '<access_key>' ]
[ SESSION_TOKEN = '<token>' ]
[ REGION = '<region>' ]
[ ENABLE_VIRTUAL_HOST_STYLE = '<boolean>']
..
)
]
```
#1038

feat: implement Copy From

---

Cargo.lock
src/datanode/Cargo.toml
src/datanode/src/sql/copy_table_from.rs

1. Sort `Cargo.toml`
2. Remove dead code.
3. Apply code styling suggestions.
#1064

chore: code styling

---

scripts/install.sh

improve installation script text-copy

chore: update script prompt

---

Cargo.lock
src/client/Cargo.toml
src/client/src/database.rs
src/client/src/error.rs

remove addr from datanode error message
#1132

chore: remove addr from datanode error message

---

src/cmd/src/frontend.rs
src/cmd/src/standalone.rs
src/frontend/src/error.rs
src/frontend/src/frontend.rs
src/frontend/src/instance.rs
src/frontend/src/server.rs
src/servers/src/grpc.rs
src/servers/src/http.rs
src/servers/src/mysql/server.rs
src/servers/src/opentsdb.rs
src/servers/src/postgres/server.rs
src/servers/src/prom.rs
src/servers/src/server.rs
src/servers/tests/grpc/mod.rs

Add `shutdown` method for frontend.
#1158

feat: add shutdown for frontend

---

src/client/src/database.rs
src/datanode/src/error.rs
src/datanode/src/instance/grpc.rs
src/datanode/src/lib.rs
src/datanode/src/server/grpc.rs
src/datanode/src/sql.rs
src/datanode/src/sql/flush_table.rs
src/frontend/src/instance/distributed.rs
src/frontend/src/instance/distributed/grpc.rs
src/frontend/src/instance/grpc.rs
src/frontend/src/tests.rs
src/mito/src/engine.rs
src/mito/src/engine/procedure/create.rs
src/mito/src/engine/tests.rs
src/mito/src/table.rs
src/mito/src/table/test_util.rs
src/mito/src/table/test_util/mock_engine.rs
src/storage/src/region.rs
src/storage/src/region/tests/flush.rs
src/storage/src/region/writer.rs
src/store-api/src/storage/region.rs
src/table/src/engine.rs
src/table/src/requests.rs
src/table/src/table.rs

feat: implement table flush

---

Cargo.lock
Cargo.toml
src/promql/src/planner.rs
src/query/src/optimizer.rs
tests/cases/standalone/common/optimizer/filter_push_down.result

Fix ambiguous column reference on the joined plan. Now use the current table name as qualifier.

fix: ambiguous column reference

---

docs/rfcs/2023-03-08-region-fault-tolerance.md

docs: region failover RFC

---

.env.example
Cargo.lock
src/datanode/Cargo.toml
src/datanode/src/instance/sql.rs
src/datanode/src/sql/copy_table.rs
src/datanode/src/sql/copy_table_from.rs
src/datanode/src/tests/instance_test.rs
src/frontend/src/instance.rs
src/sql/src/parsers/copy_parser.rs
src/sql/src/statements/copy.rs
src/table/src/requests.rs

Implement CONNECTION clause of Copy To
#1081

feat: implement CONNECTION clause of Copy To

---

Cargo.lock
src/api/Cargo.toml
src/client/src/client.rs
src/client/src/database.rs
src/client/src/error.rs
src/frontend/src/table/insert.rs
src/frontend/src/table/scan.rs
src/frontend/src/tests.rs
src/servers/src/grpc.rs
src/servers/src/grpc/database.rs
src/servers/src/grpc/flight.rs
src/servers/src/grpc/handler.rs
src/servers/tests/grpc/mod.rs
tests-integration/tests/grpc.rs

because streaming is too verbose for simple insertion purpose

feat: add GRPC unary call service to our GreptimeDB

---

Cargo.lock
src/api/Cargo.toml
src/servers/src/grpc/database.rs

feat: GRPC client stream interface for insertion

---

src/catalog/src/lib.rs
src/datanode/src/heartbeat.rs

This pr mainly fix:  can not create table in the local distributed environment.
#1205

fix: can not create table in the local distributed environment

---

README.md

Add more explain for how to use binary and compile from source requires

docs: more explain in readme

---

README.md
src/cmd/src/bin/greptime.rs

- add greptimedb.rs to our README.md
- render README.md on the default crate (`greptime` bin)

docs: update document string and site

---

src/servers/src/http/admin.rs

Keep it the same with other HTTP APIs.

chore: rename params in flush api

---

src/promql/src/functions.rs
src/promql/src/functions/changes.rs
src/promql/src/functions/deriv.rs
src/promql/src/functions/resets.rs
src/promql/src/planner.rs

- enable two ignored cases `increase_aggr()` and `count_over_time()`. (they were fixed after the last update of DF)
- add placeholders for some beginner friendly Fns
Closes #1136. This time, for real.

fix: range func tests

---

.github/workflows/release.yml
docker/ci/Dockerfile
docker/ci/requirements.txt

install python requests lib in release container image.

ci: install python requests lib in release container image

---

src/script/src/python/ffi_types/pair_tests.rs
src/script/src/python/ffi_types/pair_tests/sample_testcases.rs
src/script/src/python/pyo3/builtins.rs
src/script/src/python/pyo3/copr_impl.rs

Added testcases from  https://github.com/GreptimeTeam/python-coprocessor-examples/tree/main , and fix some different behaviors

test: align RsPy PyO3 Behavior

---

Cargo.lock
Cargo.toml
src/catalog/Cargo.toml
src/catalog/src/datafusion.rs
src/catalog/src/datafusion/catalog_adapter.rs
src/catalog/src/error.rs
src/catalog/src/information_schema.rs
src/catalog/src/information_schema/tables.rs
src/catalog/src/lib.rs
src/catalog/src/local/manager.rs
src/catalog/src/remote/manager.rs
src/catalog/src/schema.rs
src/catalog/src/table_source.rs
src/catalog/src/tables.rs
src/common/substrait/src/df_logical.rs
src/frontend/src/catalog.rs
src/frontend/src/tests.rs
src/frontend/src/tests/instance_test.rs
src/frontend/src/tests/test_util.rs
src/meta-srv/src/mocks.rs
src/query/src/datafusion.rs
src/query/src/datafusion/error.rs
src/query/src/optimizer.rs
src/query/src/tests/mean_test.rs
src/script/src/python/pyo3/builtins.rs
src/script/src/python/rspython/builtins.rs
tests/cases/standalone/common/system/information_schema.result
tests/cases/standalone/common/system/information_schema.sql
tests/runner/src/env.rs

Add basic support for information schema. Just reuse the one in DataFusion (also update the DataFusion of course).
close #1251
fix #834

feat: information schema

---

README.md

docs: treat slack as the first-class citizen

---

src/datanode/src/sql/alter.rs

The last CI of #1354 ran before #1340 merged. And #1340 renames a function, which caused this compile error after #1354 merged into develop.

fix: compile error in develop branch

---

src/promql/src/functions/predict_linear.rs

chore: fix clippy

---

src/promql/src/functions/deriv.rs
src/promql/src/planner.rs

fix some typo and add deriv to plan in promql

chore: fix some typo and add deriv to plan in promql

---

src/common/substrait/src/df_substrait.rs

This pr mainly fix execute sql query in another catalog.

fix: execute sql query in another catalog

---

Cargo.lock
src/api/Cargo.toml
src/client/src/client.rs
src/servers/src/grpc/prom_query_gateway.rs
src/servers/src/prom.rs
tests-integration/tests/grpc.rs

- implement instant query grpc handler
- add integration tests
follow-up of #1449

feat: impl instant query and add tests

---

src/frontend/src/tests/instance_test.rs

chore: remove info log

---

Cargo.lock
src/meta-client/src/client/router.rs
tests/cases/distributed/alter/rename_table.result
tests/cases/distributed/alter/rename_table.sql
tests/cases/standalone/common/aggregate/distinct_order_by.result
tests/cases/standalone/common/catalog/schema.result
tests/runner/Cargo.toml
tests/runner/src/env.rs
tests/runner/src/main.rs

- bump sqlness to the latest commit dde4b19d7e4a41319d05a0c5bfae5c4422fde14f
- use REPLACE interceptor to remove time from error message
- exit all processes on exit
Closes #1474

feat: adopt REPLACE interceptor and quit all processes on exit

---

.github/workflows/develop.yml
src/frontend/src/tests/instance_test.rs

fix: add s3 region info

---

.env.example
src/storage/src/region/tests/compact.rs
tests-integration/src/test_util.rs

Read region from GT_S3_REGION in tests.

test: Fix s3 region in test

---

src/common/grpc-expr/src/error.rs
src/common/grpc-expr/src/insert.rs

This PR splits IllegalInsertDataSnafu into multiple errors to help developers understand what causes any errors.
close #1451

feat: improve and distinguish different errors for IllegalInsertData

---

Cargo.lock
src/api/Cargo.toml
src/meta-srv/src/error.rs
src/meta-srv/src/handler.rs
src/meta-srv/src/handler/check_leader_handler.rs
src/meta-srv/src/handler/collect_stats_handler.rs
src/meta-srv/src/handler/failure_handler.rs
src/meta-srv/src/handler/keep_lease_handler.rs
src/meta-srv/src/handler/mailbox_handler.rs
src/meta-srv/src/handler/on_leader_start.rs
src/meta-srv/src/handler/persist_stats_handler.rs
src/meta-srv/src/handler/response_header_handler.rs
src/meta-srv/src/metasrv.rs
src/meta-srv/src/metasrv/builder.rs
src/meta-srv/src/service.rs
src/meta-srv/src/service/heartbeat.rs
src/meta-srv/src/service/mailbox.rs

- A mailbox for RPC 
- Add `is_acceptable` to handlers

feat: metasrv mailbox

---

src/common/error/src/status_code.rs
src/servers/src/grpc/handler.rs

This PR adds error logs to the gRPC layer
- Adds `should_log_error` to `StatusCode` to tell callers whether it should log the error in the error level
- Logs errors in `GreptimeRequestHandler`
- #1506

feat: Log error in GreptimeRequestHandler

---

src/catalog/src/remote/manager.rs

Initialize the catalogs and schemas in parallel.
close #1517

feat: open catalogs and schemas in parallel

---

README.md

Add GreptimePlay section in our readme. 
@xtang @apdong2022 You may want add better text copy for Play. [Rendered](https://github.com/GreptimeTeam/greptimedb/blob/chore/add-play/README.md)

docs: add play section

---

src/cmd/src/frontend.rs
src/common/base/src/lib.rs
src/frontend/src/instance.rs
src/frontend/src/server.rs
src/frontend/src/statement.rs
src/frontend/src/statement/copy_table_from.rs
src/query/src/query_engine/state.rs
src/query/src/tests/query_engine_test.rs
src/servers/src/configurator.rs
src/servers/src/http.rs
src/servers/src/lib.rs
src/servers/tests/http/http_test.rs
src/servers/tests/http/influxdb_test.rs
src/servers/tests/http/opentsdb_test.rs
src/servers/tests/http/prometheus_test.rs
tests-integration/src/test_util.rs

* To improve the configurability of the http server. Add configurator component to configure http router

chore: add configurator to http server

---

.github/workflows/release.yml
tests-integration/tests/http.rs

- Seperate different system into different jobs
- disable test on macos
test pipeline: https://github.com/GreptimeTeam/greptimedb/actions/runs/4921801573

build: change release CI to only run test on linux

---

Cargo.lock
src/common/datasource/src/file_format.rs
src/common/datasource/src/file_format/csv.rs
src/common/datasource/src/object_store/s3.rs
src/frontend/src/statement.rs
src/query/src/sql/show.rs
src/sql/Cargo.toml
src/sql/src/parsers/copy_parser.rs
src/sql/src/parsers/create_parser.rs
src/sql/src/statements/copy.rs
src/sql/src/statements/create.rs
src/table/src/requests.rs

Unify the case value of constants

chore: unify code styling

---

src/catalog/src/remote/manager.rs

This patch resolves residual issues from #1499

fix: correct schema/table count in catalog metrics

---

docs/rfcs/2023-05-09-distributed-planner.md

docs: rfc of distributed planner

---

src/catalog/src/table_source.rs

This patch adds check on table source provider to allow cross schema query on information_schema.

fix: allow cross-schema query on information_schema

---

src/catalog/src/local/manager.rs
src/catalog/src/remote/manager.rs
src/catalog/src/system.rs
src/common/meta/src/instruction.rs
src/datanode/src/error.rs
src/datanode/src/heartbeat/handler.rs
src/datanode/src/heartbeat/handler/open_region.rs
src/datanode/src/heartbeat/handler/tests.rs
src/file-table-engine/src/engine/tests.rs
src/mito/src/engine.rs
src/mito/src/engine/tests.rs
src/mito/src/table.rs
src/table/src/error.rs
src/table/src/requests.rs
src/table/src/table.rs

Implement the OpenTableHandler
#1126

feat: implement OpenTableHandler

---

Cargo.lock
src/common/telemetry/Cargo.toml
src/common/telemetry/src/metric.rs

* add a uniform prefix to the metrics using the official recommendation of

chore: add a uniform prefix to the metrics using the official recommendation of

---

src/datatypes/src/value.rs
src/log-store/src/noop.rs
src/storage/src/chunk.rs
src/storage/src/error.rs
src/storage/src/memtable.rs
src/storage/src/memtable/btree.rs
src/storage/src/memtable/tests.rs
src/storage/src/read.rs
src/storage/src/read/windowed.rs
src/storage/src/schema/store.rs
src/storage/src/snapshot.rs

This PR provides an implementation of windowed table scan interface so that we can scan a small section of SST files and memtables to get the most recent records and sort according to sort options.

feat: add WindowedReader

---

src/meta-srv/src/service/admin/meta.rs

* fix meta admin api get catalog table name error
Before. get catalog and db and table name is error.
```
curl -X GET http://localhost:3002/admin/catalogs
["-public"]
```

fix: meta admin API get catalog table name error

---

Cargo.lock
src/cmd/src/cli/repl.rs
src/datanode/src/instance.rs
src/frontend/src/instance.rs
src/frontend/src/table/scan.rs
src/promql/src/extension_plan/planner.rs
src/query/Cargo.toml
src/query/src/datafusion.rs
src/query/src/dist_plan.rs
src/query/src/dist_plan/analyzer.rs
src/query/src/dist_plan/commutativity.rs
src/query/src/dist_plan/merge_scan.rs
src/query/src/dist_plan/planner.rs
src/query/src/dist_plan/utils.rs
src/query/src/lib.rs
src/query/src/query_engine.rs
src/query/src/query_engine/state.rs
src/query/src/tests/function.rs
src/query/src/tests/my_sum_udaf_example.rs
src/query/src/tests/percentile_test.rs
src/query/src/tests/query_engine_test.rs
src/query/src/tests/time_range_filter_test.rs
src/script/benches/py_benchmark.rs
src/script/src/manager.rs
src/script/src/python/engine.rs
src/servers/tests/mod.rs

- Define some fundamental structures
- Add one case for $Project(Filter(Table)))$
- Mark obvious plans' commutative type

feat: distributed planner basic

---

src/meta-srv/src/service/router.rs

We don't need to keep all peers, just truncate it to the number of partitions.

chore: truncate route-table

---

src/servers/src/prom.rs
tests-integration/tests/http.rs

Support `/api/v1/label/<label_name>/values` from Prometheus
close #1542

feat: support `/api/v1/label/<label_name>/values` from Prometheus

---

src/catalog/src/error.rs
src/cmd/src/error.rs
src/common/catalog/src/error.rs
src/common/datasource/src/error.rs
src/common/grpc-expr/src/error.rs
src/common/grpc/src/error.rs
src/common/procedure/src/error.rs
src/common/query/src/error.rs
src/common/substrait/src/error.rs
src/datanode/src/error.rs
src/datatypes/src/error.rs
src/file-table-engine/src/error.rs
src/frontend/src/error.rs
src/meta-client/src/error.rs
src/meta-srv/src/error.rs
src/mito/src/error.rs
src/promql/src/error.rs
src/query/src/error.rs
src/script/src/python/error.rs
src/servers/src/error.rs
src/sql/src/error.rs
src/storage/src/error.rs
src/table/src/error.rs

This PR removes useless error variants.

refactor: remove useless error

---

src/cmd/src/bin/greptime.rs
src/cmd/src/cli.rs
src/cmd/src/datanode.rs
src/cmd/src/frontend.rs
src/cmd/src/metasrv.rs
src/cmd/src/standalone.rs

chore: fix code styling

---

src/datanode/src/heartbeat/handler/open_region.rs
src/file-table-engine/src/engine/immutable.rs
src/file-table-engine/src/table/immutable.rs
src/mito/src/engine.rs
src/mito/src/table.rs
src/mito/src/table/test_util/mock_engine.rs
src/storage/src/engine.rs
src/storage/src/region.rs
src/store-api/src/storage/engine.rs
src/store-api/src/storage/region.rs
src/table/src/engine.rs
src/table/src/requests.rs
src/table/src/table.rs

Fix doesn't release closed regions issue 🥲

fix: fix doesn't release closed regions issue

---

src/frontend/src/instance/grpc.rs
src/servers/src/interceptor.rs
src/servers/tests/interceptor.rs

Greptimedb support both sql and grpc protocol on frontend. Currently we only have `SqlQueryInterceptor` which couldn't interfere with grpc requests.
This pr introduces `GrpcQueryInterceptor`, which is the grpc version of `SqlQueryInterceptor`. It is invoked on frontend's `GrpcQueryHandler - do_query` just like `SqlQueryInterceptor` is invoked on frontend's `SqlQueryHandler`.

chore: add grpc query interceptor

---

Cargo.lock
src/partition/Cargo.toml
src/partition/src/metrics.rs
src/partition/src/route.rs

This pr mainly add metrics for table route getting.

chore: add metrics for table route getting

---

src/common/meta/src/instruction.rs
src/datanode/src/heartbeat.rs
src/datanode/src/heartbeat/handler/close_region.rs
src/frontend/src/error.rs
src/frontend/src/heartbeat.rs
src/frontend/src/heartbeat/handler.rs
src/frontend/src/heartbeat/handler/invalidate_table_cache.rs
src/frontend/src/heartbeat/handler/tests.rs
src/frontend/src/instance.rs

Add invalidate table cache handler 
#1126

feat: add invalidate table cache handler

---

src/datanode/src/tests.rs
src/frontend/src/heartbeat/handler/invalidate_table_cache.rs
src/frontend/src/heartbeat/handler/tests.rs

fix: fix typo

---

src/mito/src/engine.rs
src/mito/src/table.rs

Support to load missing region

feat: support to load missing region

---

Cargo.lock
Cargo.toml
src/common/telemetry/Cargo.toml
src/object-store/Cargo.toml
src/servers/Cargo.toml
src/servers/src/http/handler.rs
src/servers/src/metrics.rs

This PR adds [prometheus style](https://prometheus.io/docs/instrumenting/writing_clientlibs/#process-metrics) process metrics to the server
It also bumps the version of the metrics crate to 0.21 which the [metrics-process](https://github.com/lambdalisue/rs-metrics-process) crate uses. Otherwise, the `metrics-process` crate won't record the metrics.
Generated metrics on macOS
```
greptime_process_max_fds 256
greptime_process_open_fds 49
greptime_process_start_time_seconds 1685019115
greptime_catalog_table_count{db="public"} 1
greptime_process_cpu_seconds_total 0.8672139583333333
greptime_process_virtual_memory_max_bytes 9223372036854776000 …
```

feat: Record process metrics

---

.env.example
src/cmd/src/datanode.rs
src/datanode/src/datanode.rs
src/datanode/src/store.rs
src/datanode/src/store/azblob.rs
src/object-store/tests/object_store_test.rs
tests-integration/README.md
tests-integration/src/test_util.rs
tests-integration/tests/main.rs

Try to fix https://github.com/GreptimeTeam/greptimedb/issues/1610.
Main changes:
- add `ObjectStoreConfig::Azblob` for azblob object storage configurations.
- Create azblob instance in the datanode when configured.
- Add azblob storage tests in tests-integration.
issue: https://github.com/GreptimeTeam/greptimedb/issues/1610 https://github.com/GreptimeTeam/greptimedb/issues/1081

feat: support azblob storage.

---

Cargo.lock
src/servers/Cargo.toml
tests-integration/src/test_util.rs
tests-integration/tests/sql.rs

Followup for #1680 
Upstream fix: https://github.com/sunng87/pgwire/commit/f0c81ba5706f72197897216d2fef3b46985c871f
Test for sqlx on postgres is added as well.

test: fix sqlx compatibility and adds integration test for sqlx

---

.github/workflows/develop.yml

Add a always true condition to upload step

ci: always upload sqlness log

---

src/meta-srv/src/handler/failure_handler/runner.rs
src/meta-srv/src/procedure/region_failover.rs
tests/runner/src/env.rs

This PR fixes sqlness failure caused by region failover wrongly kicks in for dropped or renamed table.

fix: sqlness failed due to region failover

---

Cargo.lock
src/client/Cargo.toml
src/client/src/database.rs
src/client/src/error.rs

feat: insert with stream

---

src/client/src/client_manager.rs
src/client/src/database.rs
src/common/query/src/logical_plan/accumulator.rs
src/common/query/src/physical_plan.rs
src/frontend/src/instance.rs
src/frontend/src/instance/distributed.rs
src/meta-srv/src/handler/failure_handler.rs
src/meta-srv/src/metasrv.rs
src/meta-srv/src/procedure/region_failover/update_metadata.rs
src/query/src/query_engine/state.rs
src/query/src/sql.rs
src/servers/src/mysql/federated.rs
src/servers/src/mysql/handler.rs
src/servers/src/mysql/server.rs
src/servers/src/query_handler/sql.rs

Some of my todos are tracked in github issues. Remove them in codes. Also bump version to `0.3.0`.

chore: clean up some of my todos

---

config/datanode.example.toml
config/standalone.example.toml
src/datanode/src/datanode.rs
src/mito/src/engine.rs
src/object-store/Cargo.toml
src/object-store/src/test_util.rs
src/object-store/tests/object_store_test.rs
src/storage/src/manifest/impl_.rs
src/storage/src/manifest/region.rs

* Test region manifest with s3 storage.
* Change default manifest gc configuration to more reasonable.

test: s3 manifest

---

src/query/src/query_engine/state.rs

To make sure `Sort` is eliminated before generating `SortPreservingMergeExec` plan. 
Result of query `select * from tsdg where ts > 1 order by ts limit 1`:
before (`1 row in set (48.858 sec)`):
```
| Plan with Metrics | GlobalLimitExec: skip=0, fetch=1, metrics=[output_rows=1, elapsed_compute=44.91µs]
SortPreservingMergeExec: [ts@0 ASC NULLS LAST], metrics=[output_rows=8192, elapsed_compute=652.557µs]
SortExec: expr=[ts@0 ASC NULLS LAST], metrics=[output_rows=32768, elapsed_compute=2.940686ms, spill_count=0, spilled_bytes=0]
CoalesceBatchesExec: target_batch_size=8192, metrics=[output_rows=22118400, elapsed_compute=30.39µs]
CoalesceBatchesExec: target_batch_size=8192, …
```

fix: bring EnforceSorting rule forward

---

src/query/src/query_engine/state.rs

https://github.com/GreptimeTeam/greptimedb/pull/1754 makes one sqlness case unstable. It will produce incorrect plan when `ORDER BY` comes with `UNION`. To fix it we should run `EnforceDistribution` before `EnforceSorting`.

fix: unstable order with union operation

---

src/datanode/src/heartbeat.rs
src/frontend/src/heartbeat.rs
src/meta-srv/src/service/heartbeat.rs

chore: add debug log for heartbeat

---

tests-integration/tests/main.rs

feat: enable azblob tests

---

src/datanode/src/instance.rs
src/storage/src/compaction/scheduler.rs
src/storage/src/region/tests/compact.rs

fix: wait for compaction task to finish

---

Cargo.lock
Cargo.toml
src/catalog/src/helper.rs
src/catalog/src/remote.rs
src/catalog/src/remote/region_alive_keeper.rs
src/common/meta/Cargo.toml
src/common/meta/src/heartbeat/handler.rs
src/common/meta/src/heartbeat/handler/parse_mailbox_message.rs
src/common/meta/src/ident.rs
src/datanode/src/heartbeat.rs
src/datanode/src/heartbeat/handler/close_region.rs
src/datanode/src/heartbeat/handler/open_region.rs
src/datanode/src/instance.rs
src/datanode/src/tests.rs
src/frontend/src/heartbeat.rs
src/frontend/src/heartbeat/handler/invalidate_table_cache.rs
src/frontend/src/heartbeat/handler/tests.rs
src/meta-srv/Cargo.toml
src/meta-srv/src/error.rs
src/meta-srv/src/handler.rs
src/meta-srv/src/handler/failure_handler.rs
src/meta-srv/src/handler/region_lease_handler.rs
src/meta-srv/src/metasrv/builder.rs
src/meta-srv/src/procedure/region_failover.rs
src/meta-srv/src/procedure/region_failover/deactivate_region.rs
src/meta-srv/src/table_routes.rs
src/table/src/engine.rs

Part of #1737 .
Please see our internal doc [here](https://greptime.feishu.cn/wiki/YJVTweW8biHdIQkdT3ncjPuSnMb#Gt1LdVNrvow0UYxhKHbcpxmIn3b).

feat: extend region leases in Metasrv

---

.github/workflows/release.yml
Makefile

- Add retries (3 times) to nextest to for flaky UT
- Set `fail-fast` to false. Other jobs within the matrix will continue to run ([doc](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures)).

ci: optimize release progress

---

src/meta-client/src/client.rs
src/meta-srv/src/service/store/etcd.rs

etcd's default configuration cannot execute more than 128 txn at once, this PR is to solve this problem.

feat: deal with more than 128 txn

---

src/meta-client/src/client.rs
src/meta-srv/src/service/store/etcd.rs

minor fix for some later comments in #1799

chore: minor fix

---

src/storage/src/scheduler.rs

Wait background scheduling task before checking scheduled task num
fixes #1788

test(storage): wait task before checking scheduled task num

---

src/meta-srv/src/service/router.rs
src/meta-srv/src/table_routes.rs

feat: table_routes util

---

src/servers/src/http.rs

This PR enlarges the default body limit to 64M.
@etolbakov is working on #1860 to make this configurable.
- #1842 
- #1860

feat(servers): enlarge default body limit to 64M

---

Cargo.lock
Cargo.toml
src/meta-client/src/client.rs
src/meta-client/src/client/ddl.rs
src/meta-client/src/client/heartbeat.rs

feat: add ddl client

---

.github/workflows/release.yml

Support china region download url: `https://download.greptime.cn/releases/${tag}/${binary_name}.tgz`

feat: release binary to aws s3

---

src/meta-srv/src/procedure/create_table.rs

fix: fix broken CI 😢

---

src/catalog/src/helper.rs

This PR supports special characters in table keys.

refactor: support special characters in table keys

---

.github/workflows/docs.yml

Skip sqlness test like other checks when we only update docs.

ci: skip sqlness test on docs update

---

Cargo.lock
Cargo.toml
src/common/meta/Cargo.toml
src/common/meta/src/error.rs
src/common/meta/src/key.rs
src/common/meta/src/key/datanode_table.rs
src/common/meta/src/key/table_name.rs
src/common/meta/src/key/table_route.rs
src/frontend/src/table.rs
src/meta-srv/src/procedure/create_table.rs
src/meta-srv/src/procedure/region_failover/update_metadata.rs
src/meta-srv/src/service/router.rs

The remaining two keys as discussed.
#1728

refactor: TableNameKey and DatanodeTableKey

---

src/client/src/lib.rs
src/common/meta/src/rpc/ddl.rs
src/meta-srv/src/ddl.rs
src/meta-srv/src/error.rs
src/meta-srv/src/lib.rs
src/meta-srv/src/metasrv/builder.rs
src/meta-srv/src/procedure.rs
src/meta-srv/src/procedure/create_table.rs
src/meta-srv/src/procedure/drop_table.rs
src/meta-srv/src/procedure/utils.rs
src/meta-srv/src/service/ddl.rs
src/meta-srv/src/service/router.rs
src/meta-srv/src/table_routes.rs

implement drop table procedure
#1727

feat: implement drop table procedure

---

docs/rfcs/2023-07-06-table-engine-refactor.md

fix: before/after order

---

src/file-table-engine/src/table/format.rs

refactor: remove unused code

---

src/frontend/src/error.rs
src/frontend/src/instance.rs
src/frontend/src/instance/distributed.rs
src/frontend/src/metrics.rs
src/meta-client/src/client.rs
src/meta-client/src/client/ddl.rs
src/meta-srv/src/bootstrap.rs
src/meta-srv/src/ddl.rs
src/meta-srv/src/metasrv/builder.rs
src/meta-srv/src/metrics.rs
src/meta-srv/src/mocks.rs
src/meta-srv/src/procedure/create_table.rs
tests-integration/src/cluster.rs
tests-integration/src/instance.rs

1. Switch to using create table procedure
2. Remove unused code and metrics 
#1727

feat: switch to using create table procedure

---

src/common/error/src/status_code.rs
src/servers/src/error.rs

This pr mainly adds `RateLimited` status code.

chore: add rate limit status code

---

tests-integration/tests/region_failover.rs

fix: fix uncaught error

---

Cargo.lock
src/mito2/Cargo.toml
src/mito2/src/config.rs
src/mito2/src/engine.rs
src/mito2/src/error.rs
src/mito2/src/lib.rs
src/mito2/src/metadata.rs
src/mito2/src/region.rs
src/mito2/src/region/metadata.rs
src/mito2/src/region/version.rs
src/mito2/src/worker.rs

This PR
- adds docs mod and class diagrams
- defines basic structs for MitoEngine

feat(mito2): Define basic structs for MitoEngine

---

src/meta-srv/src/procedure/create_table.rs
src/meta-srv/src/procedure/drop_table.rs

fix uncaught error 🥲
However, We still need to set the client's timeout correctly.

fix: fix uncaught error 🥲

---

Cargo.lock
src/query/src/parser.rs
src/servers/Cargo.toml
src/servers/src/lib.rs
src/servers/src/mysql/handler.rs
src/servers/src/postgres.rs
src/servers/src/postgres/handler.rs
src/servers/src/postgres/server.rs
src/servers/src/postgres/types.rs
src/sql/src/statements/query.rs
tests-integration/tests/sql.rs

Use `LogicalPlan` API for parameter replacement in postgres

feat: add logical plan based prepare statement for postgresql

---

Cargo.lock
tests-integration/src/test_util.rs
tests-integration/tests/http.rs

fix: fix broken CI

---

src/frontend/src/instance.rs

fix frontend meta client option issue

fix: fix frontend meta client option issue

---

Cargo.lock
config/metasrv.example.toml
src/common/procedure/Cargo.toml
src/common/procedure/src/options.rs
src/datanode/src/datanode.rs
src/meta-srv/src/metasrv.rs
src/meta-srv/src/metasrv/builder.rs
tests-integration/src/cluster.rs

1. Exposes meta's procedure options
2. Tunes meta procedure options in tests

feat: meta procedure options

---

Cargo.lock
src/common/meta/src/rpc/ddl.rs
src/frontend/src/error.rs
src/frontend/src/instance/distributed.rs
src/meta-client/src/client/ddl.rs
src/meta-srv/src/ddl.rs
src/meta-srv/src/procedure/drop_table.rs
src/meta-srv/src/procedure/utils.rs

1. Switch to using drop table procedure
2. Remove unused code and metrics
#1727

feat: switch to using drop table procedure

---

Cargo.lock
Cargo.toml
config/frontend.example.toml
src/cmd/src/datanode.rs
src/common/grpc-expr/src/alter.rs
src/common/meta/src/rpc/ddl.rs
src/common/meta/src/rpc/router.rs
src/datanode/src/sql/alter.rs
src/file-table-engine/src/engine/tests.rs
src/frontend/src/error.rs
src/frontend/src/instance.rs
src/frontend/src/instance/distributed.rs
src/frontend/src/table.rs
src/meta-client/src/client.rs
src/meta-client/src/lib.rs
src/meta-srv/Cargo.toml
src/meta-srv/src/ddl.rs
src/meta-srv/src/error.rs
src/meta-srv/src/procedure.rs
src/meta-srv/src/procedure/alter_table.rs
src/meta-srv/src/procedure/utils.rs
src/meta-srv/src/service/ddl.rs
src/meta-srv/src/table_routes.rs
src/mito/src/engine/procedure/alter.rs
src/mito/src/engine/tests.rs
src/mito/src/error.rs
src/mito/src/table/test_util.rs
src/table-procedure/src/alter.rs
src/table/src/engine.rs
src/table/src/requests.rs

implement alter table procedure
#1727

feat: implement alter table procedure

---

src/meta-client/src/client.rs
src/meta-client/src/client/ask_leader.rs
src/meta-client/src/client/ddl.rs
src/meta-client/src/client/heartbeat.rs

DdlClient also needs to use ask_leader, refactor this part to make ask_leader easier to use

feat: ask leader

---

src/datanode/src/instance/grpc.rs

Add DDL idempotent tests of datanode

test: add ddl idempotent tests of datanode

---

src/cmd/src/cli/upgrade.rs

fix: compile error after #1971 is merged

---

src/query/src/sql.rs
tests/cases/standalone/common/catalog/schema.result
tests/cases/standalone/common/catalog/schema.sql

Though I've already implmented `SHOW TABLES WHERE ~` in #1829, I forgot implementing `SHOW DATABASES WHERE ~`😭

feat: support where in show databases

---

src/storage/src/scheduler.rs

Test case test_schedule_duplicate_tasks has a concurrent issue: the handler might consume the request before checking whether the request is duplicate.
This PR blocks the handle to ensure we test the scheduler de-duplicate requests.

test(storage): fix schedule_duplicate_tasks test

---

Cargo.lock
src/datanode/src/error.rs
src/datanode/src/instance/grpc.rs
src/datanode/src/server/grpc.rs
src/datanode/src/sql/alter.rs
src/meta-srv/src/procedure/alter_table.rs

Fix table not found issue while alter procedure (rename) retrying.
fix #1992

fix: alter procedure table not found issue

---

src/promql/src/extension_plan/instant_manipulate.rs

Change the logic in promql instant manipulator that may allocate large intermediate vector on a large time span.

fix: avoid large vector allocation on large query span

---

.github/workflows/release.yml

feat: (upload binary s3)add nightly build tag

---

src/cmd/src/cli/upgrade.rs

fix: etcd range pagenation in table metadata migration tool

---

Makefile

1. Don't set the build jobs when nproc is not found;
2. Use Makefile `ifneq ($(strip $(VAR)),)` to detect whether the variable is empty or not;

refactor: don't set the build jobs when nproc is not found

---

src/datatypes/src/vectors/primitive.rs

If there is a cast error in `try_from_arrow_timestamp_array` and `try_from_arrow_time_array` function, it returns `CastTypeSnafu` now.
Closes https://github.com/GreptimeTeam/greptimedb/issues/2010

chore: return error in arrow array convert function

---

Cargo.lock
Cargo.toml
src/api/src/helper.rs
src/client/examples/stream_ingest.rs
src/common/grpc-expr/src/insert.rs
src/common/grpc/src/writer.rs
src/datanode/src/instance/grpc.rs
src/frontend/src/instance/distributed/inserter.rs
src/frontend/src/table/delete.rs
src/frontend/src/table/insert.rs
src/servers/src/influxdb.rs
src/servers/src/opentsdb/codec.rs
tests-integration/src/grpc.rs
tests-integration/tests/grpc.rs

refactor: common semantic-type

---

src/servers/src/grpc/handler.rs
tests-integration/src/test_util.rs
tests-integration/tests/grpc.rs
tests-integration/tests/http.rs
tests-integration/tests/sql.rs

This pr mainly fixes grpc's authentication not taking effect
#1982

fix: auth in grpc

---

.github/workflows/release.yml

fix incorrect github token secret name.

fix: incorrect github token secret name

---

README.md

docs: update SDK list

---

src/common/meta/src/error.rs
src/common/meta/src/key.rs
src/common/meta/src/key/catalog_name.rs
src/common/meta/src/key/schema_name.rs
src/common/meta/src/lib.rs
src/common/meta/src/range_stream.rs
src/common/meta/src/rpc/store.rs
src/common/meta/src/util.rs

1. Add Range Pagination Stream
2. Add Catalog and Schema Manager
- #2024 
- #1846

feat: add Catalog and Schema Manager

---

src/datanode/src/instance.rs
src/meta-srv/src/metasrv.rs
src/meta-srv/src/metasrv/builder.rs

Fix typo: greptimedb_teleme**rty**_task -> greptimedb_teleme**try**_task

chore: typo

---

.github/workflows/nightly-build.yml

fix: wrong action url prompt

---

docs/rfcs/2023-08-04-tabie-trait-refactor.md

RFC of refactoring the table trait.
[rendered](https://github.com/waynexia/greptimedb/blob/rfc-table-abstract/docs/rfcs/2023-08-04-tabie-trait-refactor.md)
#2065

docs: rfc of refactoring table trait

---

.github/actions/build-images/action.yml
.github/actions/build-linux-artifacts/action.yml
.github/scripts/create-version.sh
.github/workflows/dev-build.yml

Development build only build the debug version of the artifacts manually with given repo and commit.

ci: add dev-build

---

.github/workflows/dev-build.yml

ci: fix error import path

---

.github/workflows/dev-build.yml

ci: fix incorrect variable name

---

.github/actions/build-linux-artifacts/action.yml

fix: var compare error(yet another stupid mistake)

fix: var compare error(yet another stupid mistake)

---

.github/actions/build-images/action.yml
.github/workflows/dev-build.yml

fix: add 'image-name' argument to correct the invalid image namespace(mix with image-name)

fix: add 'image-name' argument to correct the invalid image namespace(mix with image-name)

---

.github/actions/build-dev-builder-image/action.yml
.github/workflows/release.yml

I want to change IMAGE_NAMESPACE, but you are faster than me @zyy17

chore: rename dockerhub registry password

---

src/catalog/Cargo.toml
src/common/meta/src/key/table_info.rs
src/common/recordbatch/Cargo.toml
src/datanode/Cargo.toml
src/frontend/Cargo.toml
src/meta-srv/Cargo.toml
src/table/Cargo.toml
src/table/src/metadata.rs

fix: deserialize TableInfoValue with missing field

---

.github/actions/build-greptime-binary/action.yml
.github/actions/build-linux-artifacts/action.yml
.github/actions/upload-artifacts/action.yml
.github/scripts/create-version.sh
.github/workflows/dev-build.yml

ci: add working dir and some minor changes of create-version.sh

ci: add working dir and some minor changes of create-version.sh

---

tests/runner/src/env.rs

feat: print build output if it's failed in sqlness

---

src/datanode/src/instance/grpc.rs

fix: make "explain" executable in repl

---

src/query/src/dist_plan/merge_scan.rs

Add output rows counter and gRPC timer to merge scan exec plan
before
```sql
MySQL [(none)]> explain analyze SELECT * FROM integers;
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type         | plan                                                                                                                                                                                                      |
+-------------------+------------------------------------------------------------------------------ …
```

feat: implement metric for MergeScanExec

---

src/query/src/dist_plan/merge_scan.rs
src/query/src/dist_plan/planner.rs

Part of https://github.com/GreptimeTeam/greptimedb/issues/2065
At present, `scan_to_stream` will be called on the execution path of Dist Table, and merge scan, not partition exec, is the appropriate physical plan.
Furthermore, calls to Table's `scan` should be avoided, the ultimate goal is to remove this method.
Manually tested.

refactor: prevent dist table from invoking `scan`

---

src/common/meta/src/key.rs
src/common/meta/src/key/datanode_table.rs
src/common/meta/src/key/table_info.rs
src/common/meta/src/key/table_name.rs
src/common/meta/src/key/table_route.rs
src/common/meta/src/kv_backend/txn.rs
src/common/meta/src/rpc/router.rs

refactor table metadata manager
#1715

refactor: refactor table metadata manager

---

Cargo.lock
Cargo.toml
src/api/Cargo.toml
src/api/src/helper.rs
src/client/src/database.rs
src/common/grpc-expr/src/error.rs
src/common/grpc-expr/src/insert.rs
src/common/grpc-expr/src/lib.rs
src/common/grpc-expr/src/util.rs
src/datanode/src/instance/grpc.rs
src/frontend/src/instance/distributed.rs
src/frontend/src/instance/grpc.rs
src/servers/tests/mod.rs

1. Move common type conversions to helper.rs
2. Row protocol to add support for interval type
3. Remove unnecessary unit tests
4.  Move some common function to util.rs (row-protocol and column-protocol both will be used)

refactor: grpc insert

---

src/common/meta/src/key.rs
src/common/meta/src/key/datanode_table.rs
src/common/meta/src/key/table_route.rs
src/meta-srv/src/ddl.rs
src/meta-srv/src/procedure/region_failover.rs

chore: remove allow-unused

---

src/client/src/error.rs

fix: invalid err msg

---

src/catalog/src/information_schema.rs
src/catalog/src/local/manager.rs
src/catalog/src/local/memory.rs
src/catalog/tests/local_catalog_tests.rs
src/datanode/src/instance.rs
src/frontend/src/catalog.rs
src/query/src/datafusion.rs
src/query/src/dist_plan/analyzer.rs
src/query/src/optimizer/order_hint.rs
src/query/src/tests/query_engine_test.rs
src/script/benches/py_benchmark.rs
src/script/src/python/engine.rs
src/table/src/table/numbers.rs

refactor: apply numbers to `ThinTable`

---

src/servers/src/grpc.rs
src/servers/src/grpc/handler.rs
src/servers/src/grpc/prom_query_gateway.rs

This pr mainly adds `auth` to `PrometheusGatewayService`

fix: auth in prometheus gateway service

---

src/common/meta/src/key.rs
src/common/meta/src/key/datanode_table.rs
src/common/meta/src/key/table_info.rs
src/common/meta/src/key/table_name.rs
src/common/meta/src/key/table_region.rs
src/common/meta/src/key/table_route.rs
tests-integration/tests/region_failover.rs

Unite key serialization method

refactor: unite key serialization method

---

src/common/grpc-expr/src/insert.rs
src/common/grpc-expr/src/lib.rs
src/common/grpc-expr/src/util.rs
src/datanode/src/error.rs
src/datanode/src/instance.rs
src/datanode/src/instance/grpc.rs
src/datanode/src/lib.rs
src/datanode/src/row_inserter.rs
src/frontend/src/error.rs
src/frontend/src/expr_factory.rs
src/frontend/src/instance.rs
src/frontend/src/instance/distributed.rs
src/frontend/src/instance/grpc.rs
src/frontend/src/instance/influxdb.rs
src/frontend/src/lib.rs
src/frontend/src/row_inserter.rs
src/meta-srv/src/service/store/etcd.rs
src/servers/src/error.rs
src/servers/src/http/influxdb.rs
src/servers/src/influxdb.rs
src/servers/src/query_handler.rs
src/servers/tests/http/influxdb_test.rs
tests-integration/src/influxdb.rs

1. datanode's row inserter
2. standalone's row inserter
3. influxdb line protocol  row inserter

feat: row write protocol

---

src/servers/src/http/prom_store.rs

This pr mainly adds `user_info` to prom_store handler.

fix: add `user_info` extension to prom_store handler

---

src/cmd/src/cli/upgrade.rs

This pr mainly adds `TableRegionKey` in delete process during upgrading table route key, since it's no longer used after #2172

chore: add table region key to delete in upgrade tool

---

Cargo.lock
Cargo.toml
src/client/src/database.rs
src/client/src/stream_insert.rs
src/frontend/src/instance/distributed.rs
src/frontend/src/instance/distributed/row_inserter.rs
src/frontend/src/instance/influxdb.rs
src/partition/src/manager.rs
src/partition/src/row_splitter.rs
src/servers/src/influxdb.rs

feat: dist row inserter

---

src/mito2/src/engine.rs
src/mito2/src/engine/tests.rs
src/mito2/src/memtable/time_series.rs
src/mito2/src/request.rs
src/mito2/src/worker.rs
src/mito2/src/worker/handle_close.rs
src/mito2/src/worker/handle_create.rs
src/mito2/src/worker/handle_open.rs
src/mito2/src/worker/handle_write.rs

Write to mito2 and return output

chore: write to mito2

---

Cargo.lock
src/common/grpc/Cargo.toml
src/common/grpc/src/error.rs
src/common/grpc/src/writer.rs
src/frontend/src/instance/prom_store.rs
src/servers/src/influxdb.rs
src/servers/src/lib.rs
src/servers/src/prom_store.rs
src/servers/src/row_writer.rs

Prometheus remote write with row-based protocol

feat: prometheus row inserter

---

Cargo.lock
Cargo.toml
src/api/src/helper.rs
src/datanode/src/error.rs
src/datanode/src/region_server.rs
src/datanode/src/server.rs
src/mito2/src/engine.rs
src/servers/src/error.rs
src/servers/src/grpc.rs
src/servers/src/grpc/region_server.rs
src/store-api/src/metadata.rs
src/store-api/src/region_request.rs

Implement RegionEngine for mito. From now on all requests can be passed to the corresponding engine.

feat: impl region engine for mito

---

src/meta-srv/src/service/ddl.rs

fix: fix typoes

---

src/mito2/src/engine.rs
src/mito2/src/engine/tests.rs
src/mito2/src/lib.rs
src/mito2/src/region/opener.rs
src/mito2/src/region/version.rs
src/mito2/src/region_write_ctx.rs
src/mito2/src/region_writer.rs
src/mito2/src/test_util.rs
src/mito2/src/wal.rs
src/mito2/src/worker.rs
src/mito2/src/worker/handle_create.rs
src/mito2/src/worker/handle_open.rs
src/mito2/src/worker/handle_write.rs

This PR adds WAL replay support to mito2.

feat(mito2): WAL replay

---

src/common/meta/src/key.rs
src/common/meta/src/key/schema_name.rs
src/frontend/src/instance/distributed.rs

This pr mainly fixes compatibility issue to existing `null` value of `SchemaNameValue`

fix: json compatibility to `null`

---

Cargo.lock
src/client/Cargo.toml
src/client/src/client_manager.rs
src/client/src/region.rs
src/common/meta/src/cache_invalidator.rs
src/common/meta/src/datanode_manager.rs
src/common/meta/src/error.rs
src/meta-srv/src/cache_invalidator.rs
src/meta-srv/src/ddl.rs
src/meta-srv/src/error.rs
src/meta-srv/src/lib.rs
src/meta-srv/src/metasrv.rs
src/meta-srv/src/metasrv/builder.rs
src/meta-srv/src/procedure/alter_table.rs
src/meta-srv/src/procedure/create_table.rs
src/meta-srv/src/procedure/drop_table.rs
src/meta-srv/src/procedure/utils.rs

refactor: refactor: ddl context

---

src/common/meta/src/ddl_manager.rs
src/common/meta/src/error.rs
src/frontend/src/error.rs
src/frontend/src/instance/distributed.rs
src/meta-client/src/client.rs

refactor: refactor DistInstance

---

Cargo.lock
src/common/meta/Cargo.toml
src/common/meta/src/ddl.rs
src/common/meta/src/ddl/alter_table.rs
src/common/meta/src/ddl/create_table.rs
src/common/meta/src/ddl/drop_table.rs
src/common/meta/src/ddl/utils.rs
src/common/meta/src/error.rs
src/common/meta/src/lib.rs
src/meta-srv/src/ddl.rs
src/meta-srv/src/error.rs
src/meta-srv/src/metrics.rs
src/meta-srv/src/procedure.rs
src/meta-srv/src/procedure/tests.rs
src/meta-srv/src/procedure/utils.rs

refactor: refactor ddl procedure

---

src/cmd/src/metasrv.rs
src/meta-srv/src/handler.rs
src/meta-srv/src/handler/check_leader_handler.rs
src/meta-srv/src/handler/filter_inactive_region_stats.rs
src/meta-srv/src/handler/keep_lease_handler.rs
src/meta-srv/src/handler/mailbox_handler.rs
src/meta-srv/src/handler/node_stat.rs
src/meta-srv/src/handler/on_leader_start_handler.rs
src/meta-srv/src/handler/region_lease_handler.rs
src/meta-srv/src/handler/response_header_handler.rs
src/meta-srv/src/inactive_node_manager.rs
src/meta-srv/src/keys.rs
src/meta-srv/src/lease.rs
src/meta-srv/src/metasrv.rs
src/meta-srv/src/metasrv/builder.rs
src/meta-srv/src/procedure/region_failover.rs
src/meta-srv/src/procedure/region_failover/activate_region.rs
src/meta-srv/src/procedure/region_failover/deactivate_region.rs
src/meta-srv/src/test_util.rs

fix: filter out outdated heartbeat

---

src/meta-srv/src/selector/load_based.rs

fix LoadBase Selector cannot follow the region distribution rules

fix: LoadBase Selector cannot follow the region distribution rules

---

Cargo.lock
Cargo.toml
src/common/greptimedb-telemetry/Cargo.toml
src/datanode/Cargo.toml
src/datanode/src/store.rs
src/datanode/src/store/azblob.rs
src/datanode/src/store/gcs.rs
src/datanode/src/store/oss.rs
src/datanode/src/store/s3.rs
src/object-store/src/lib.rs

Build a custom HTTP client for cloud storage such as s3, azblob etc.
Try to close #1505

feat: build http client for cloud object storage

---

src/mito2/src/error.rs
src/mito2/src/request.rs

Modify error message in `validate_proto_value()`

fix: improve error message in validate_proto_value

---

src/meta-srv/src/handler.rs

Optimize the timeout mechanism of the mailbox

refactor: mailbox timeout

---

src/datatypes/src/vectors/helper.rs

Returns error instead of panic when converting unsupported arrow arrays in `Helper::try_into_vector()`.

fix: panic in try_into_vector()

---

src/datanode/src/heartbeat.rs
src/meta-srv/src/handler/collect_stats_handler.rs
src/meta-srv/src/handler/node_stat.rs

filter out empty heartbeat req

feat: filter out empty heartbeat req

---

tests-integration/src/grpc.rs
tests-integration/src/tests/instance_test.rs
tests-integration/tests/http.rs

tests-integration grpc::test::test_distributed_insert_delete_and_query
tests-integration grpc::test::test_standalone_insert_and_query
tests-integration tests::instance_test::test_execute_insert_by_select::case_1_test_with_standalone
tests-integration tests::instance_test::test_execute_insert_by_select::case_2_test_with_distributed
tests-integration::main integration_http_file_test::test_config_api

test: fix some integration tests

---

src/sql/src/statements/transform/type_alias.rs

chore: type alias typo

---

.github/actions/build-macos-artifacts/action.yml
.github/workflows/release.yml

ci: make upload-to-s3 configurable(for now, it's false)

ci: make upload-to-s3 configurable(for now, it's false)

---

.github/workflows/develop.yml
Cargo.lock
src/common/datasource/Cargo.toml
src/common/datasource/src/error.rs
src/common/datasource/src/lister.rs
src/common/datasource/src/object_store.rs
src/operator/src/statement/copy_table_from.rs
src/operator/src/statement/copy_table_to.rs
tests-integration/src/tests/instance_test.rs
tests-integration/src/tests/test_util.rs

fix: test on windows

---

src/mito2/src/read/merge.rs

The `BatchMerger` doesn't reset the `is_sorted` flag to `true` after merging batches. This PR fixes this issue.

fix(mito): reset is_sorted to true after the merger finishing one series

---

src/cmd/src/cli/upgrade.rs
src/common/meta/src/instruction.rs
src/common/meta/src/key.rs
src/common/meta/src/key/datanode_table.rs
src/datanode/src/datanode.rs
src/datanode/src/heartbeat/handler.rs
src/datanode/src/tests.rs
src/meta-srv/src/procedure/region_failover.rs
src/meta-srv/src/procedure/region_failover/activate_region.rs
src/meta-srv/src/procedure/region_failover/deactivate_region.rs
src/meta-srv/src/procedure/region_failover/update_metadata.rs

Fix open region missing options
fix #2472

fix: open region missing options

---

src/servers/src/mysql/federated.rs
src/servers/src/mysql/handler.rs
src/session/src/context.rs
src/session/src/lib.rs
tests-integration/tests/sql.rs

Fixes #2529 
Bind time zone to session and add tests for this behaviour

fix: mysql timezone settings

---

Cargo.lock
src/common/telemetry/src/metric.rs
src/mito2/src/engine.rs
src/mito2/src/flush.rs
src/mito2/src/metrics.rs
src/mito2/src/request.rs
src/mito2/src/worker/handle_close.rs
src/mito2/src/worker/handle_create.rs
src/mito2/src/worker/handle_drop.rs
src/mito2/src/worker/handle_flush.rs
src/mito2/src/worker/handle_open.rs
src/mito2/src/worker/handle_write.rs
src/store-api/Cargo.toml
src/store-api/src/region_request.rs

This PR adds some basic metrics to the new mito engine.

feat(mito): add metrics to mito engine

---

Cargo.lock
src/promql/Cargo.toml
src/promql/src/extension_plan/series_divide.rs
src/promql/src/metrics.rs
src/query/src/dist_plan/merge_scan.rs
src/query/src/metrics.rs

This PR adds some basic metrics to query components.

feat: add basic metrics to query

---

.github/actions/build-dev-builder-image/action.yml
.github/actions/build-greptime-binary/action.yml
.github/actions/build-linux-artifacts/action.yml
Makefile

chore: add the steps of building android binary

chore: add the steps of building android binary

---

.github/workflows/develop.yml
.github/workflows/nightly-ci.yml

This patch schedules Windows tests to run every night. And removes them from pull request checks in order to reduce its cost.

ci: run windows tests every night instead of every commit

---

Cargo.lock
Cargo.toml

Release new version '0.4.0' -> '0.4.1'

ci: release new version '0.4.0' -> '0.4.1'

---

Cargo.lock
Cargo.toml

chore: upgrade 0.4.2

---

Cargo.lock
Cargo.toml

chore: update greptime-proto to main

---

src/common/meta/src/key/table_info.rs
src/meta-srv/src/bootstrap.rs
src/meta-srv/src/election.rs
src/meta-srv/src/metasrv.rs
src/meta-srv/src/service/admin.rs
src/meta-srv/src/service/admin/heartbeat.rs
src/meta-srv/src/service/admin/meta.rs
src/meta-srv/src/service/admin/route.rs
src/meta-srv/src/service/admin/util.rs

Offer an HTTP service that takes a batch of table IDs as input and returns the metadata for these tables.
#2673

feat: query table meta by ids

---

src/common/meta/src/key.rs
src/common/meta/src/range_stream.rs
src/common/meta/src/rpc/store.rs
src/meta-srv/src/handler/on_leader_start_handler.rs
src/meta-srv/src/lib.rs
src/meta-srv/src/metasrv.rs
src/meta-srv/src/metasrv/builder.rs
src/meta-srv/src/metrics.rs
src/meta-srv/src/service/store/cached_kv.rs
src/meta-srv/src/state.rs

Enable metasrv leader cached kv

feat: enable metasrv leader cached kv

---

src/servers/src/otlp/plugin.rs
src/servers/src/otlp/trace.rs
src/servers/src/otlp/trace/attributes.rs
src/servers/src/otlp/trace/span.rs

impl Serialize for Attributes
- correct json string format

feat(otlp): json attributes via impl Serialeze trait

---

Cargo.lock
Cargo.toml
src/metric-engine/Cargo.toml
src/metric-engine/src/engine.rs
src/metric-engine/src/error.rs
src/metric-engine/src/lib.rs
src/metric-engine/src/metadata_region.rs
src/metric-engine/src/test_util.rs
src/metric-engine/src/utils.rs
src/mito2/Cargo.toml
src/mito2/src/engine.rs
src/mito2/src/engine/flush_test.rs
src/mito2/src/engine/listener.rs
src/mito2/src/engine/truncate_test.rs
src/mito2/src/lib.rs
src/mito2/src/test_util.rs
src/mito2/src/worker.rs
src/store-api/src/storage/descriptors.rs

Define a basic skeleton for metric engine
part of https://github.com/GreptimeTeam/greptimedb/issues/2070

feat: Metric engine skeleton

---

src/mito2/src/engine/create_test.rs
src/mito2/src/engine/drop_test.rs
src/mito2/src/engine/open_test.rs
src/mito2/src/error.rs
src/mito2/src/region/opener.rs
src/mito2/src/region/options.rs
src/mito2/src/test_util.rs
src/mito2/src/worker/handle_create.rs
src/mito2/src/worker/handle_open.rs
src/object-store/src/manager.rs

This PR supports region ddl request for custom storage.
Part of #919

feat: support region ddl for custom_storage

---

src/servers/src/otlp/trace/attributes.rs

Do not include extra `"` for OtlpAnyValue Display of String type

feat: specialize Display for String OtlpAnyValue

---

src/mito2/src/memtable/time_series.rs
src/mito2/src/metrics.rs
src/mito2/src/read/merge.rs
src/mito2/src/read/scan_region.rs
src/mito2/src/read/seq_scan.rs
src/mito2/src/sst/parquet/reader.rs

This PR added some metrics to read path and prints verbose metrics in the debug log.
It also adjusts the level of some logs in the memtable.

feat(mito): Add metrics to read path

---

docs/rfcs/2023-11-07-region-migration.md

Add region migration RFC
[rendered](https://github.com/GreptimeTeam/greptimedb/blob/ff22bab3c8f028a90f79d495ac06a1f231c9dfdb/docs/rfcs/2023-11-07-region-migration.md)
#2700

docs: add region migration RFC

---

docs/rfcs/2023-07-10-metric-engine.md

chore: metric-engine rfc format

---

.github/ISSUE_TEMPLATE/bug_report.yml

1. _Firstly_ require a _minimal_ reproduce.
2. Explicitly ask what is expected and what happen instead.

chore: improve bug report issue template

---

src/servers/build.rs

Add the [`rerun-if-changed`](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed) instruction to reduce unnecessary downloads.

chore: add rerun-if-changed to dashboard feature

---

src/meta-srv/src/handler.rs
src/meta-srv/src/handler/check_leader_handler.rs
src/meta-srv/src/handler/collect_stats_handler.rs
src/meta-srv/src/handler/failure_handler.rs
src/meta-srv/src/handler/filter_inactive_region_stats.rs
src/meta-srv/src/handler/keep_lease_handler.rs
src/meta-srv/src/handler/mailbox_handler.rs
src/meta-srv/src/handler/on_leader_start_handler.rs
src/meta-srv/src/handler/persist_stats_handler.rs
src/meta-srv/src/handler/publish_heartbeat_handler.rs
src/meta-srv/src/handler/region_lease_handler.rs
src/meta-srv/src/handler/response_header_handler.rs
src/meta-srv/src/metasrv.rs
src/meta-srv/src/service.rs
src/meta-srv/src/table_meta_alloc.rs

feat: heartbeat handler control

---

Cargo.lock
src/servers/Cargo.toml
src/servers/src/error.rs
src/servers/src/http/authorize.rs

fix: urldecode when influxdb auth

---

src/catalog/src/kvbackend/manager.rs
src/cmd/src/cli/repl.rs
src/cmd/src/error.rs
src/cmd/src/frontend.rs
src/cmd/src/metasrv.rs
src/cmd/src/standalone.rs
src/frontend/src/error.rs
src/frontend/src/instance.rs
src/frontend/src/instance/builder.rs
src/frontend/src/instance/standalone.rs
src/meta-srv/src/bootstrap.rs
src/meta-srv/src/metasrv/builder.rs
src/meta-srv/src/mocks.rs
tests-integration/src/cluster.rs
tests-integration/src/standalone.rs

Make creating Frontend instance more clearer, and more flexible (for later dual-rw mode usage).

refactor: add builder for Frontend

---

tests-integration/src/cluster.rs

fix: fragile integration tests

---

src/query/src/optimizer/type_conversion.rs

The previous method will result incorrect expr. For input like
```sql
WHERE 0.12345 <= demo_memory_usage_bytes
```
It will switch the two operand, and generate expr 
```
Filter: demo_memory_usage_bytes.greptime_value <= Float64(0.12345)
```
This patch fixes it. Now the result expr is
```
Filter: Float64(0.12345) <= demo_memory_usage_bytes.greptime_value
```

fix: type conversion rule reverses operands

---

src/meta-srv/src/metrics.rs
src/meta-srv/src/region/lease_keeper.rs
src/meta-srv/src/service/store.rs
src/meta-srv/src/service/store/cached_kv.rs

Unify the meta metrics styling

chore: unify the meta metrics styling

---

src/meta-srv/src/service/heartbeat.rs

This closes https://github.com/GreptimeTeam/greptimedb/issues/2885.

fix: handle heartbeat shutdown gracefully

---

src/datanode/src/error.rs
src/frontend/src/error.rs
src/mito2/src/error.rs
src/partition/src/error.rs
src/query/src/error.rs

Cleanup some unused errors. BTW, we have to find some way to find out all these unused errors in CI.

chore: clean up unused errors

---

.github/workflows/dev-build.yml

ci: able to choose cargo profile in dev-build action

---

src/cmd/src/bin/greptime.rs
src/cmd/src/cli.rs
src/cmd/src/cli/bench.rs
src/cmd/src/cli/export.rs
src/cmd/src/cli/upgrade.rs
src/cmd/src/datanode.rs
src/cmd/src/frontend.rs
src/cmd/src/lib.rs
src/cmd/src/metasrv.rs
src/cmd/src/options.rs
src/cmd/src/standalone.rs
src/datanode/src/region_server.rs

to support further integrated into other binaries

refactor: make instance started separately

---

src/common/datasource/src/object_store/fs.rs
src/common/datasource/src/object_store/s3.rs

Add log and tracing layers for Copy From statement

feat: add log and tracing layers for Copy From statement

---

src/cmd/src/standalone.rs
src/common/meta/src/sequence.rs
src/frontend/src/instance/standalone.rs
src/meta-srv/src/handler.rs
src/meta-srv/src/handler/persist_stats_handler.rs
src/meta-srv/src/handler/response_header_handler.rs
src/meta-srv/src/metasrv.rs
src/meta-srv/src/metasrv/builder.rs
src/meta-srv/src/procedure/region_failover.rs
src/meta-srv/src/procedure/region_migration/test_util.rs
src/meta-srv/src/procedure/utils.rs
src/meta-srv/src/test_util.rs
tests-integration/src/standalone.rs

refactor: make sequence bounded with max value

---

src/mito2/src/manifest/manager.rs
src/mito2/src/manifest/storage.rs

fetch manifests in concurrent 🚀🚀🚀

feat: fetch manifests in concurrent

---

src/servers/src/error.rs
src/servers/src/prom_store.rs

fix: correct the error message for snappy compress

---

src/datatypes/src/value.rs

fix decimal128 type from ScalarValue to Value.

fix: decimal128 ScalarValue to Value

---

.github/workflows/apidoc.yml
.github/workflows/develop.yml
.github/workflows/docs.yml
.github/workflows/license.yaml
CONTRIBUTING.md
README.md
src/client/src/stream_insert.rs
src/index/src/inverted_index/format.rs

Change all references from branch `develop` to branch `main`
https://github.com/GreptimeTeam/greptimedb/issues/3025

chore: change all reference from develop to main

---

.github/workflows/doc-label.yml

chore: attempt to add doc issue in label task

---

src/common/meta/src/key/table_route.rs
src/meta-srv/src/procedure/region_failover/update_metadata.rs
src/meta-srv/src/procedure/region_migration/manager.rs
src/meta-srv/src/procedure/region_migration/migration_start.rs
src/meta-srv/src/procedure/region_migration/update_metadata/upgrade_candidate_region.rs
src/partition/src/manager.rs

fix: fix non-physical error msg

---

README.md

Try to update the description of the GreptimeDB project to make it clearer and reflect the latest progress.
@xtang @apdong2022 @fengjiachun @sunng87  Please take a look.

docs: update the description of greptimedb project

---

src/datanode/Cargo.toml
src/datanode/src/lib.rs
src/frontend/src/instance/standalone.rs
src/meta-srv/src/procedure.rs
src/meta-srv/src/procedure/utils.rs

chore: expose some codes to let other projects use them

---

src/common/catalog/src/lib.rs
src/common/meta/src/ddl/alter_table.rs
src/common/meta/src/ddl/create_table.rs
src/common/meta/src/ddl/drop_table.rs
src/common/meta/src/ddl/truncate_table.rs
src/common/meta/src/ddl_manager.rs
src/common/meta/src/lib.rs
src/common/meta/src/lock_key.rs
src/common/procedure/src/lib.rs
src/meta-srv/src/procedure/region_failover.rs
src/meta-srv/src/procedure/region_migration.rs
src/meta-srv/src/procedure/utils.rs

refactor the locks in procedure
#2700

refactor: refactor the locks in the procedure

---

tests/README.md
tests/conf/kafka-cluster.yml
tests/runner/src/env.rs
tests/runner/src/main.rs
tests/runner/src/util.rs

Makes it easier to run sqlness using kafka wal. See `tests/README.md` for usage.

feat: manager kafka cluster in sqlness runner

---

src/metric-engine/src/engine/create.rs
src/object-store/src/util.rs

fix tests failed on windows.
close #3150

fix: fix tests failed on windows

---

tests-integration/src/tests/promql_test.rs

As issue https://github.com/GreptimeTeam/greptimedb/issues/1296 is closed as completed, it's safe to expose promql test to the distributed instance.

chore: expose promql test to distributed instance

---

Cargo.lock
src/client/src/client.rs
src/cmd/Cargo.toml
src/cmd/src/datanode.rs
src/cmd/src/error.rs
src/datanode/src/region_server.rs
src/mito2/src/access_layer.rs
src/mito2/src/engine.rs
src/mito2/src/error.rs
src/mito2/src/region.rs
src/mito2/src/request.rs
src/mito2/src/worker.rs
src/mito2/src/worker/handle_flush.rs

For append sst to work in another project.

refactor: expose region edit in mito engine

---

README.md

update SDK links in README.md
https://github.com/GreptimeTeam/docs/pull/741

docs: update SDK links in README.md

---

docker/dev-builder/ubuntu/Dockerfile

ci: make git's "safe.directory" accept all

---

src/datanode/src/region_server.rs

feat: Only allow inserts and deletes operations to be executed in parallel

---

.github/actions/build-greptime-images/action.yml
.github/actions/publish-github-release/action.yml
.github/actions/release-cn-artifacts/action.yaml
.github/actions/upload-artifacts/action.yml

ci: fix nightly build

---

.github/workflows/develop.yml

chore: share cache corss jobs

---

src/log-store/src/error.rs
src/log-store/src/lib.rs
src/log-store/src/raft_engine/backend.rs

This closes #3322.
Also, enrich the IO error with the checked path.

chore: check dirs before create RaftEngine store

---

Cargo.lock
src/servers/Cargo.toml
src/servers/tests/mysql/mysql_server_test.rs

build(deps): Upgrade opensrv to 0.7.0

---

scripts/fetch-dashboard-assets.sh

This closes https://github.com/GreptimeTeam/greptimedb/issues/3382.

chore: retry fetch dashboard assets

---

codecov.yml
src/common/meta/src/ddl/create_table.rs
src/common/meta/src/key.rs
src/common/meta/src/key/table_route.rs
src/meta-srv/src/procedure/region_failover/deactivate_region.rs
src/meta-srv/src/procedure/region_failover/update_metadata.rs
src/meta-srv/src/procedure/region_migration.rs
src/meta-srv/src/procedure/region_migration/manager.rs
src/meta-srv/src/procedure/region_migration/test_util.rs
src/meta-srv/src/procedure/region_migration/update_metadata/downgrade_leader_region.rs
src/meta-srv/src/procedure/region_migration/update_metadata/rollback_downgraded_region.rs
src/meta-srv/src/procedure/region_migration/update_metadata/upgrade_candidate_region.rs
src/meta-srv/src/procedure/tests.rs
src/meta-srv/src/region/lease_keeper.rs
src/meta-srv/src/selector/load_based.rs
src/meta-srv/src/service/admin/route.rs
tests-integration/src/grpc.rs
tests-integration/src/instance.rs

Introduce a `TableRouteStorage`, and move low levels APIs(`get`, `batch_get`, and txn related methods) into `TableRouteStorage`
close #3321

refactor: refactor TableRouteManager

---

Cargo.lock
src/object-store/Cargo.toml

build(deps): upgrade opendal to 0.45.1

---

docs/rfcs/2023-05-09-distributed-planner.md
src/common/macro/src/admin_fn.rs
src/common/procedure/src/local/runner.rs
src/flow/src/expr/linear.rs
src/mito2/src/cache.rs
src/promql/src/functions/extrapolate_rate.rs
src/store-api/src/region_request.rs

chore: remove repetitive words

---

README.md

docs: revise README file

---

src/promql/src/extension_plan/series_divide.rs

chore: avoid unnecessary cloning

---

Cargo.lock
src/servers/Cargo.toml
src/servers/src/postgres/handler.rs

This patch upgrades `pgwire` to latest 0.20 for improvement of writing resultset to client.
Content of this patch are mostly API change adoption. What actually improves performance for writing data rows are in https://github.com/sunng87/pgwire/pull/165 and https://github.com/sunng87/pgwire/pull/166

feat: update pgwire to 0.20 for improved performance

---

src/auth/src/common.rs
src/auth/src/user_provider/static_user_provider.rs

chore: avoid confusing TryFrom

---

Cargo.lock
src/operator/Cargo.toml

chore: add back core dependency

---

typos.toml

False positive:
https://github.com/GreptimeTeam/greptimedb/actions/runs/8479383890/job/23233296359?pr=3614
Test SQL may contain arbitrary words.

ci: ignore type in sqlness sql and result files

---

src/common/meta/src/ddl/alter_logical_tables.rs
src/common/meta/src/ddl/alter_logical_tables/update_metadata.rs
src/common/meta/src/ddl/create_logical_tables.rs
src/common/meta/src/ddl/create_logical_tables/check.rs
src/common/meta/src/ddl/create_logical_tables/metadata.rs
src/common/meta/src/ddl/create_logical_tables/region_request.rs
src/common/meta/src/ddl/create_logical_tables/update_metadata.rs
src/common/meta/src/error.rs
src/operator/src/statement/ddl.rs

refactor: alter logical tables

---

Cargo.lock
src/flow/Cargo.toml
src/flow/src/compute.rs
src/flow/src/compute/render.rs
src/flow/src/compute/state.rs
src/flow/src/compute/types.rs
src/flow/src/expr/func.rs
src/flow/src/expr/relation/func.rs
src/flow/src/lib.rs
src/flow/src/plan.rs
src/flow/src/repr.rs
src/flow/src/utils.rs

Starting add the ability to "render" and execute dataflow Plan, this PR include simple rendering functions like `render_constant` and `render_mfp`(which renders a MapFilterProject) and comprehensive unit tests are added to test them.

feat(flow): render map&related tests

---

.github/actions/build-windows-artifacts/action.yml
.github/workflows/develop.yml

ci: setup-protoc always with token

---

cliff.toml

@waynexia you can use this generated text now:
```markdown
* [@CookiePieWw](https://github.com/CookiePieWw) made their first contribution in [#3626](https://github.com/GreptimeTeam/greptimedb/pull/3626)
* [@xxxuuu](https://github.com/xxxuuu) made their first contribution in [#3571](https://github.com/GreptimeTeam/greptimedb/pull/3571)
* [@YCCDSZXH](https://github.com/YCCDSZXH) made their first contribution in [#3539](https://github.com/GreptimeTeam/greptimedb/pull/3539)
We would like to thank the following contributors from the GreptimeDB community:
[@CookiePieWw](https://github.com/CookiePieWw), [@J0HN50N133](https://github.com/J0HN50N133), …
```

chore: improve contributor click in git-cliff

---

Makefile

chore: add a fix-clippy Makefile target

---

tests-integration/tests/http.rs

The commented out test has been added back in https://github.com/GreptimeTeam/greptimedb/pull/3473.

chore: remove TODO that has been done

---

config/config.md
config/datanode.example.toml
config/standalone.example.toml

Updates memtable config examples.

docs: update memtable config example

---

src/cmd/src/cli/upgrade.rs
src/common/meta/src/key/catalog_name.rs
src/common/meta/src/key/datanode_table.rs
src/common/meta/src/key/schema_name.rs
src/common/meta/src/range_stream.rs
src/meta-srv/src/service/store/cached_kv.rs

Change signature `PaginationStream<K, V>` to `PaginationStream<T>`

refactor: simplify the PaginationStream

---

src/flow/src/compute/render/map.rs
src/flow/src/compute/state.rs
src/flow/src/lib.rs
src/flow/src/utils.rs

Almost keep the original logic, but try to keep things simple. Also, refine the doc comment for struct `Arrangement` to make it clearer.

refactor(flow): refine comments and code

---

src/meta-srv/src/region/lease_keeper.rs

Add warn log for failed to renew region lease

chore: add warn log for denied to renew region lease 

---

src/common/grpc/src/flight.rs

A net win on performance, although it might be tiny.

chore: try avoid one slice

---

.github/workflows/develop.yml
src/servers/src/http/pprof.rs

ci: align clippy checks and fixup

---

src/operator/src/insert.rs

move mirror insertion tasks to the background runtime

refactor: move mirror insertion tasks to the background runtime

---

src/common/meta/src/cache.rs
src/common/meta/src/cache/container.rs
src/common/meta/src/cache/table.rs
src/common/meta/src/cache/table/table_info.rs
src/common/meta/src/cache/table/table_name.rs
src/common/meta/src/cache/table/table_route.rs
src/common/meta/src/key/table_info.rs
src/common/meta/src/key/table_name.rs
src/common/meta/src/key/table_route.rs

1. Introduce `TableNameCache`
2. Introduce `TableInfoCache`
3. Introduce `TableRouteCache`

feat: introduce `TableNameCache` & `TableInfoCache` & `TableRouteCache`

---

src/common/meta/src/ddl_manager.rs
src/common/meta/src/rpc/ddl.rs
src/operator/src/error.rs
src/operator/src/statement.rs
src/operator/src/statement/ddl.rs

feat: support to drop flow

---

src/common/meta/src/key/flow/flow_info.rs
src/common/meta/src/key/flow/flow_name.rs
src/common/meta/src/key/table_info.rs
src/common/meta/src/key/table_route.rs
src/common/meta/src/key/txn_helper.rs
src/common/meta/src/kv_backend/memory.rs
src/common/meta/src/kv_backend/txn.rs
src/log-store/src/raft_engine/backend.rs

1. Rename a few methods
2. Add the `put_if_not_exists` and `compare_and_put` functions for easier use.

refactor: make txn easy to use

---

src/catalog/src/kvbackend/manager.rs

Keep the same naming style with `exists`

chore: keep the same naming style

---

Cargo.lock
src/common/datasource/Cargo.toml
src/common/datasource/src/error.rs
src/common/datasource/src/file_format/orc.rs

feat: migrate orc-rs to datafusion-orc

---

.github/workflows/release.yml
Cargo.lock
Cargo.toml

chore: bump to v0.8.0

---

.github/workflows/dev-build.yml
.github/workflows/nightly-build.yml
.github/workflows/nightly-ci.yml
.github/workflows/release.yml

CI failure. Try to fix it up. https://github.com/GreptimeTeam/greptimedb/actions/runs/9138897944/workflow

ci: check-status for nightly-ci

---

.github/workflows/nightly-build.yml
cyborg/bin/report-ci-failure.ts

ci: fixup strings in check ci status

---

.github/workflows/release.yml

ci: skip notification for manual releases

---

Cargo.lock
Cargo.toml

chore: bump to v0.8.1

---

src/partition/src/partition.rs
tests/cases/standalone/common/partition.result

fix: display the PartitionBound and PartitionDef correctly

---

.github/workflows/develop.yml

remove redundant sqlness test config

chore(ci): remove redundant sqlness test config

---

src/metric-engine/src/engine.rs
src/metric-engine/src/engine/put.rs
src/metric-engine/src/engine/state.rs
src/operator/src/error.rs
src/operator/src/insert.rs
src/operator/src/statement/ddl.rs

1. remove unnecessary checking from creating logical tables
2. avoid to do same thing (hash get) in a for loop

chore: reduce some burden on the write path

---

src/common/macro/Cargo.toml

https://github.com/GreptimeTeam/greptimedb/pull/4130
A very small fix. We already enabled the `full` features and it includes most features we listed in the `Cargo.toml`.

chore(common-macro): remove features covered by full

---

.github/actions/build-greptime-binary/action.yml
.github/actions/build-linux-artifacts/action.yml

chore(ci): switch to aws registry

---

.github/workflows/docs.yml

ci: align docs with develop

---

src/meta-srv/src/service/heartbeat.rs

As the title said, handling heartbeat is the most important work in metasrv(Processing heartbeats and generating scheduling instructions require substantial computation.), so we better to use the write runtime.

feat: use the write runtime to handle the heartbeats

---

src/metric-engine/src/metadata_region.rs
src/mito2/src/cache.rs
src/mito2/src/engine/projection_test.rs
src/mito2/src/read.rs
src/mito2/src/read/first_last.rs
src/mito2/src/read/scan_region.rs
src/mito2/src/read/seq_scan.rs
src/mito2/src/read/unordered_scan.rs
src/mito2/src/sst/parquet/file_range.rs
src/mito2/src/sst/parquet/reader.rs
src/query/src/dummy_catalog.rs
src/query/src/optimizer.rs
src/query/src/optimizer/first_last.rs
src/query/src/query_engine/state.rs
src/store-api/src/storage.rs
src/store-api/src/storage/requests.rs

A experimental implementation for pushing down last value

feat: test pushing down last value

---

Cargo.lock

Bringing two fixes and other reactors. Hopefully free lunch.
See https://github.com/apache/opendal/releases/tag/v0.47.3.

build(deps): upgrade opendal to 0.47.3

---

src/mito2/src/read/last_row.rs

- Replaced `last_batch` in `LastRowReader` with `LastRowSelector`.
Extracts the last row selection logic to a common struct.

refactor: LastRowReader to use LastRowSelector

---

src/common/error/src/status_code.rs

None
* fix: format comments end with . symbol
* docs: add commnet for RegionReadonly
* fix: comment error for DatabaseAlreadyExists

docs(common_error): format enum StatusCode docs

---

README.md

Update project status to encourage developers to try it.

docs: update project status

---

src/frontend/src/instance/prom_store.rs
src/servers/src/interceptor.rs

fix: missing `pre_write` check on prometheus remote write

---

docker/docker-compose/cluster-with-etcd.yaml

Make docker compose image configurable

ci: make docker image args configurable from env vars

---

.github/workflows/develop.yml

chore: reduce fuzz tests in CI

---

v0.9.1.md

Add v0.9.1 tsbs benchmark report.

docs: add v0.9.1 bench result

---

src/common/function/src/table/flush_compact_table.rs

Support `swcs` as the short name for `strict_window` when triggering manually compaction.
Ref: https://github.com/GreptimeTeam/docs/pull/1121#discussion_r1704944956

chore: support swcs as the short name for strict window compaction

---

src/mito2/src/sst/parquet/helper.rs

close #3072 
Merge small byte ranges for optimized fetching. 
BTW, For our use case, each row group limit of 102400 rows, the size is typically very small (i.e. ~1MiB).

perf: merge small byte ranges for optimized fetching

---

config/config.md
config/metasrv.example.toml
src/cmd/tests/load_config_test.rs

Fixes example for metasrv config about selector

fix: configuration example for selector

---

.github/workflows/nightly-ci.yml

chore: upload kind logs

---

Cargo.lock
Cargo.toml
src/servers/src/http/event.rs

This pr does
- update meter-crate version
- adjust `LogValidator`'s signature for constructing a `HttpResponse` requires async

chore: update validator signature

---

src/datanode/src/error.rs
src/frontend/src/error.rs
src/meta-srv/src/error.rs

Add `SetupPlugin` and `StartPlugin` error.

refactor(plugin): add SetupPlugin and StartPlugin error

---

docs/benchmarks/log/README.md
docs/benchmarks/log/create_table.sql
docs/benchmarks/log/query.md
docs/benchmarks/log/query.sql
docs/benchmarks/log/structured_vector.toml
docs/benchmarks/log/unstructured_vector.toml

Add docs for log benchmark configuration.

docs: log benchmark

---

README.md

chore: add commerial support section

---

.github/workflows/release-dev-builder-images.yaml

Correct toolchain file name in yaml

fix: change toolchain file name

---

.github/workflows/release-dev-builder-images.yaml

fix: failed to get version

---

.github/workflows/release-dev-builder-images.yaml
Makefile

https://github.com/GreptimeTeam/greptimedb/actions/runs/10570476518
Add `-e`, `-v` flag inject auth configuration to skopeo container.
Change Makefile and use this dev-build image tag: https://github.com/GreptimeTeam/greptimedb/actions/runs/10570476518/job/29285912511.

chore: setting docker authentication in dev-build image

---

Cargo.lock
src/common/procedure/Cargo.toml
src/common/procedure/src/local/runner.rs

build(deps): bump backon to 1.0

---

src/query/src/dist_plan/merge_scan.rs
src/session/src/context.rs

Trivial changes. Reported by @WenyXu

feat: remove some redundent clone/conversion on constructing MergeScan stream

---

src/common/telemetry/src/logging.rs

Correct otlp endpoint formatting

fix: correct otlp endpoint formatting

---

src/operator/src/insert.rs

* Supports TTL hint for gRPC writing.

feat: grpc writing supports TTL hint

---

src/cmd/src/cli/export.rs
src/cmd/src/cli/import.rs
src/cmd/src/error.rs
src/servers/src/http/handler.rs

1. export `create database` SQL
2. create the database before importing
3. fix a bug (unset `db` parameter) for HTTP SQL server

feat: export import database

---

src/common/meta/src/cache_invalidator.rs
src/common/meta/src/error.rs
src/common/meta/src/key.rs
src/common/meta/src/key/catalog_name.rs
src/common/meta/src/key/datanode_table.rs
src/common/meta/src/key/flow.rs
src/common/meta/src/key/flow/flow_info.rs
src/common/meta/src/key/flow/flow_name.rs
src/common/meta/src/key/flow/flow_route.rs
src/common/meta/src/key/flow/flownode_flow.rs
src/common/meta/src/key/flow/table_flow.rs
src/common/meta/src/key/schema_name.rs
src/common/meta/src/key/table_info.rs
src/common/meta/src/key/table_name.rs
src/common/meta/src/key/table_route.rs
src/common/meta/src/key/txn_helper.rs
src/common/meta/src/key/view_info.rs
src/frontend/src/heartbeat/handler/tests.rs

chore: refactor metadata key value trait

---

config/config.md
config/datanode.example.toml
config/standalone.example.toml
src/mito2/src/compaction.rs
src/mito2/src/config.rs
src/mito2/src/engine/edit_region_test.rs
src/mito2/src/engine/flush_test.rs
src/mito2/src/engine/listener.rs
src/mito2/src/region.rs
src/mito2/src/region/opener.rs
src/mito2/src/worker.rs
src/mito2/src/worker/handle_catchup.rs
src/mito2/src/worker/handle_compaction.rs
src/mito2/src/worker/handle_create.rs
src/mito2/src/worker/handle_flush.rs
src/mito2/src/worker/handle_manifest.rs
src/mito2/src/worker/handle_open.rs
tests-integration/tests/http.rs

feat: schedule compaction when adding sst files by editing region

---

docker/ci/ubuntu/Dockerfile

Good for debugging purpose. The downside is larger image, but less important for now.

build: add mysql and postgresql clients to greptimedb image

---

src/meta-srv/src/handler/collect_stats_handler.rs
src/meta-srv/src/handler/response_header_handler.rs
src/meta-srv/src/metasrv.rs
src/meta-srv/src/metasrv/builder.rs
src/meta-srv/src/procedure/region_migration.rs
src/meta-srv/src/procedure/region_migration/test_util.rs

feat: invalidate cache via invalidator on region migration

---

Cargo.lock
Cargo.toml

- closes #4663
Bump version to v0.9.3

chore: bump version v0.9.3

---

src/mito2/src/read/dedup.rs

- https://github.com/GreptimeTeam/greptimedb/issues/4686
fixes last fields builder that may not been initialized if fields to read is empty

fix: last non null iter not init

---

README.md

https://github.com/GreptimeTeam/docs/pull/1174
Update the dead link

chore: update the document link in README.md

---

src/operator/src/insert.rs
src/table/src/requests.rs

feat: gRPC auto create table hint

---

src/common/grpc-expr/src/insert.rs
src/common/grpc-expr/src/lib.rs

chore: remove unused method

---

src/mito2/src/read/scan_region.rs

Parallelize in row group level under append mode. This can give a higher parallelism. But this is not viable in `SeqScan` mode as it relies on the sequence among one file.

feat: parallel in row group level under append mode

---

src/operator/src/insert.rs

chore: avoid schema check when auto_create_table_hint is disabled

---

src/operator/src/insert.rs

chore: remove `validate_request_with_table`

chore: remove `validate_request_with_table`

---

Cargo.toml

fix: sort cargo toml

---

src/frontend/src/instance/log_handler.rs
src/frontend/src/server.rs
src/pipeline/src/etl/processor/dissect.rs
src/servers/src/http.rs
src/servers/src/http/event.rs
src/servers/src/interceptor.rs
tests-integration/src/test_util.rs

This pr mainly adds `LogIngestInterceptor` to intercept execution before the pipeline and ingestion.

chore: add log ingest interceptor

---

tests/cases/standalone/common/copy/copy_database_from_fs_parquet.result
tests/cases/standalone/common/copy/copy_database_from_fs_parquet.sql
tests/cases/standalone/common/copy/copy_from_fs_csv.result
tests/cases/standalone/common/copy/copy_from_fs_csv.sql
tests/cases/standalone/common/copy/copy_from_fs_json.result
tests/cases/standalone/common/copy/copy_from_fs_json.sql
tests/cases/standalone/common/copy/copy_from_fs_parquet.result
tests/cases/standalone/common/copy/copy_from_fs_parquet.sql
tests/cases/standalone/common/copy/copy_to_fs.result
tests/cases/standalone/common/copy/copy_to_fs.sql
tests/runner/src/env.rs
tests/runner/src/main.rs

- fixes #4779
Fix the isolation issue of sqlness test suite.

fix(sqlness): sqlness isolation

---

src/meta-srv/src/error.rs
src/meta-srv/src/handler.rs
src/meta-srv/src/lib.rs
src/meta-srv/src/metasrv/builder.rs

feat: add `add_handler_after`, `add_handler_before`, `replace_handler` for `HeartbeatHandlerGroupBuilder`

feat: add `add_handler_after`, `add_handler_before`, `replace_handler`

---

Cargo.lock
Cargo.toml

closes #4830 
bump version to v0.9.4

chore: bump version v0.9.4

---

docs/benchmarks/log/README.md

fix the dead link
ref: https://github.com/GreptimeTeam/docs/pull/1220

fix: dead links

---

src/meta-srv/src/metrics.rs
src/meta-srv/src/procedure/region_migration.rs
src/meta-srv/src/procedure/region_migration/manager.rs

add more metrics for region migration

chore: add more metrics for region migration

---

src/common/meta/src/rpc/router.rs

fix metadata forward compatibility issue

fix: fix metadata forward compatibility issue

---

Cargo.lock
Cargo.toml

Bump greptime-meter crate version.

chore: bump greptime-meter

---

src/common/runtime/src/runtime.rs

fix: fix broken import

---

Cargo.lock
Cargo.toml

update proto to [fc45ac](https://github.com/GreptimeTeam/greptime-proto/commit/fc45ac4cce7e91c9438c2e5a497a4d99531397f1)

chore: update proto depend

---

config/datanode.example.toml
config/flownode.example.toml
config/frontend.example.toml
config/metasrv.example.toml
config/standalone.example.toml

Fix UT under `cargo nextest run --all-features`.

fix(config): update tracing section headers in example TOML files

---

src/mito2/src/read.rs
tests-fuzz/targets/migration/fuzz_migrate_mito_regions.rs

This PR provides more info in the BatchChecker error messages to help diagnose issues.

chore: provide more info in check batch message

---

src/meta-srv/src/error.rs
src/meta-srv/src/selector/common.rs
src/meta-srv/src/selector/lease_based.rs
src/meta-srv/src/selector/load_based.rs
src/meta-srv/src/selector/weight_compute.rs
src/meta-srv/src/selector/weighted_choose.rs

refactor: simplify WeightedChoose

---

docs/how-to/how-to-change-log-level-on-the-fly.md

chore: short desc markdown about change log level

---

src/meta-srv/src/handler.rs
src/meta-srv/src/handler/collect_stats_handler.rs
src/meta-srv/src/metasrv.rs
src/meta-srv/src/metasrv/builder.rs
tests/cases/standalone/common/information_schema/region_statistics.result
tests/cases/standalone/common/information_schema/region_statistics.sql
tests/conf/metasrv-test.toml.template

feat: heartbeat_flush_threshold option

---

Cargo.lock
src/common/grpc-expr/src/util.rs
src/frontend/src/instance/grpc.rs
src/operator/Cargo.toml
src/operator/src/delete.rs
src/operator/src/error.rs
src/operator/src/insert.rs
src/operator/src/req_convert/common.rs
tests-integration/src/grpc.rs

Support to insert json data via grpc protocol

feat: support to insert json data via grpc protocol

---

src/common/meta/src/key.rs
src/common/meta/src/key/maintenance.rs
src/meta-srv/src/error.rs
src/meta-srv/src/metasrv.rs
src/meta-srv/src/metasrv/builder.rs
src/meta-srv/src/region/supervisor.rs
src/meta-srv/src/service/admin.rs
src/meta-srv/src/service/admin/maintenance.rs

introduce `MaintenanceModeManager`

refactor: introduce `MaintenanceModeManager`

---

src/common/meta/src/key/maintenance.rs

correct `unset_maintenance_mode` behavior

fix: correct `unset_maintenance_mode` behavior

---

Cargo.lock
src/common/function/Cargo.toml

fix: android build failed due to simsimd

---

Cargo.lock
Cargo.toml

chore: bump version to v0.10.1

---

src/pipeline/src/etl/processor.rs
src/pipeline/src/etl/processor/cmcd.rs
src/pipeline/src/etl/processor/decolorize.rs
src/pipeline/src/etl/processor/dissect.rs
src/pipeline/tests/pipeline.rs

Implement the `decolorize` processor similar to the one from Loki https://grafana.com/docs/loki/latest/query/log_queries/#removing-color-codes
Also remove some dead code BTW

feat: add decolorize processor

---

src/frontend/src/instance.rs
src/frontend/src/instance/log_handler.rs
src/servers/src/http.rs
src/servers/src/http/event.rs
src/servers/src/query_handler.rs

Refactor the internal symbol's names. Lift up "Pipeline" as a first-class concept. Treat `insert_log` into the pipeline as using the pipeline to perform transformation.
This patch doesn't contains breaking change.

refactor: replace LogHandler with PipelineHandler

---

Cargo.lock
src/servers/Cargo.toml
src/servers/src/postgres.rs
src/servers/src/postgres/auth_handler.rs
src/servers/src/postgres/fixtures.rs
src/servers/src/postgres/handler.rs
src/servers/src/postgres/types/bytea.rs

Mostly minor bugfixes and API changes.

feat: update pgwire to 0.28

---

.github/actions/setup-greptimedb-cluster/action.yml

ci: set meta replicas to 1

---

src/frontend/src/instance/log_handler.rs
src/pipeline/benches/processor.rs
src/pipeline/src/etl.rs
src/pipeline/src/manager/pipeline_operator.rs
src/pipeline/src/manager/table.rs
src/pipeline/tests/common.rs
src/pipeline/tests/dissect.rs
src/pipeline/tests/pipeline.rs
src/servers/src/http.rs
src/servers/src/http/event.rs
src/servers/src/query_handler.rs
tests-integration/tests/http.rs

* pipeline dryrun api can currently receives pipeline raw content
```
curl -X "POST" "http://localhost:4000/v1/events/pipelines/v1/dryrun?db=public" \
-H 'Content-Type: application/json; charset=utf-8' \
-d $'{
"pipeline_name": "apach_test",
"data": [
"145.251.205.39 - devankoshal [29/Oct/2024:17:51:29 +0800] \\"DELETE /booper/bopper/mooper/mopper HTTP/1.1\\" 304 43420"
]
}'
{"rows":[[{"data_type":"STRING","key":"ip_address","semantic_type":"TAG","value":"145.251.205.39"},{"data_type":"STRING","key":"http_method","semantic_type":"TAG","value":"DELETE"},{"data_type":"STRING","key":"http_version","semantic_type":"TAG","value":"1.1"},{"data_type":"INT32","key":"status_code","semantic …
```

chore: pipeline dryrun api can currently receives pipeline raw content

---

tests/cases/standalone/common/flow/flow_rebuild.result
tests/cases/standalone/common/flow/flow_rebuild.sql

add some tests related to flow's rebuild. Which will become more useful once flow refill(recover of internal state) is implemented.

test: flow rebuild

---

Cargo.lock
src/metric-engine/Cargo.toml
src/mito2/Cargo.toml
src/store-api/Cargo.toml

https://github.com/GreptimeTeam/greptimedb/pull/5163
Adds aquamarine back.
Otherwise, docs ci will fail
https://github.com/GreptimeTeam/greptimedb/actions/runs/12352863566/job/34470766661

chore: add aquamarine to dep lists

---

src/servers/src/grpc/database.rs
src/servers/src/hint_headers.rs
src/servers/src/http.rs
src/servers/src/http/hints.rs
src/servers/src/lib.rs

feat: extract hints from http header

---

.github/actions/setup-greptimedb-cluster/with-minio-and-cache.yaml
.github/actions/setup-greptimedb-cluster/with-minio.yaml
.github/actions/setup-greptimedb-cluster/with-remote-wal.yaml
tests-fuzz/src/utils.rs

chore: adjust fuzz tests cfg

---

.github/workflows/dev-build.yml
.github/workflows/nightly-build.yml

I tried to update the builder default value for other yaml files....... Hope it can work.

chore: update all arm64 builders

---

README.md

Add greptimedb-operator project link in 'Tools & Extensions' and other small improvements

docs: add greptimedb-operator project link in 'Tools & Extensions' and other small improvements

---

.github/actions/build-greptime-binary/action.yml
.github/actions/build-macos-artifacts/action.yml
.github/actions/build-windows-artifacts/action.yml
.github/actions/upload-artifacts/action.yml

Support to pack multiple files in upload-artifacts action

ci: support to pack multiple files in upload-artifacts action

---

src/mito2/src/region.rs

add log for region role converting. it's useful for troubleshooting.

chore: add log for converting region to follower

---

.github/workflows/develop.yml
.github/workflows/nightly-ci.yml

Make sure clippy and format passes. To reduce unwanted test runs

ci: make sure clippy passes before running tests

---

src/servers/src/mysql/helper.rs

This PR supports converting the time string(for example, `2024-12-26 10:00:25.899`) to the `Timestamp` type in `convert_value()`.  It fixes the insert data error when users insert timestamp in string format by using a prepared statement. The logic is compatible with native MySQL.

refactor: support to convert time string to timestamp in `convert_value()`

---

shell.nix

- switch to nix stable release
- add `libz` as dependency
- add `curl` if we need to build dashboard in future

ci: update nix setup

---

src/cmd/src/datanode.rs
src/cmd/src/flownode.rs

Bring back functions deleted in #5193 and required by downstream projects.

fix: brings back functions required by downstream projects

---

grafana/greptimedb-cluster.json
grafana/greptimedb.json

update grafana config against the new opendal metrics layer.
The cluster version is manually modified directly on the JSON model. The standalone version is regenerated with my local grafana

feat: update standalone grafana with new metric name

---

.github/workflows/develop.yml

ci: do not trigger tests when there is a merge conflict

---

.github/workflows/develop.yml

Try to speedup test build with mold

ci: use mold for tests

---

.github/workflows/develop.yml
.github/workflows/nightly-ci.yml

- We only have 10GB quota for cache so here we need to optimise it for most effective tasks: clippy, build and test
- Cache created in pull requests are only available to further commits of this PR. Cache created in merge group MAY NOT (to be confirmed) be available to pull requests. So here I created a nightly test on main branch just for creating cache that will be available to all pull requests.

ci: disable cache for some tasks, create cache in nightly build

---

src/cmd/src/metasrv.rs
src/meta-srv/src/metasrv.rs

@WenyXu @sunng87 
This patch finish https://github.com/GreptimeTeam/greptimedb/issues/5322
android build still failed after https://github.com/GreptimeTeam/greptimedb/pull/5327 
need very tiny fix, this patch did it.
error:
make build-android-bin
```cli
Compiling meta-srv v0.12.0 (/greptimedb/src/meta-srv)
Compiling datanode v0.12.0 (/greptimedb/src/datanode)
Compiling cli v0.12.0 (/greptimedb/src/cli)
Compiling frontend v0.12.0 (/greptimedb/src/frontend)
Compiling flow v0.12.0 (/greptimedb/src/flow)
Compiling plugins v0.12.0 (/greptimedb/src/plugins)
Compiling cmd v0.12.0 (/greptimedb/src/cmd)
error[E0599]: no method named `detect_server_addr` found for struct …
```

fix: android build

---

src/meta-srv/src/election/postgres.rs

The unit test may fail due to concurrent `CREATE TABLE IF NOT EXISTS` calls. This patch use different table names to avoid it.

fix(test): use different table name

---

Cargo.lock
src/common/procedure/src/store/state_store.rs
src/mito2/src/cache/file_cache.rs
src/mito2/src/manifest/storage.rs
src/mito2/src/worker/handle_drop.rs
src/object-store/Cargo.toml
src/object-store/src/layers/lru_cache.rs
src/object-store/src/layers/lru_cache/read_cache.rs
src/object-store/src/lib.rs

Bump opendal to pinned version. Addressed all breaking changes that introduced in `0.51`.

refactor: Bump opendal to 0.51.1

---

src/log-store/src/raft_engine/log_store.rs
src/pipeline/src/etl/processor.rs

Minor fixes:
- wrong pipeline content may cause panic
- verbose logstore log

fix: improve error handling in pipeline and log in log store

---

src/mito2/src/memtable/partition_tree.rs
src/mito2/src/memtable/partition_tree/partition.rs
src/mito2/src/memtable/partition_tree/primary_key_filter.rs
src/mito2/src/memtable/partition_tree/shard.rs
src/mito2/src/memtable/partition_tree/shard_builder.rs
src/mito2/src/row_converter.rs
src/mito2/src/row_converter/dense.rs
src/mito2/src/row_converter/sparse.rs
src/mito2/src/test_util/memtable_util.rs
src/mito2/src/test_util/sst_util.rs

#5282 
1. introduce `SparsePrimaryKeyCodec`
2. refactor `DensePrimaryKeyFilter` and introduce `SparsePrimaryKeyFilter`

feat: introduce `SparsePrimaryKeyCodec` and `SparsePrimaryKeyFilter`

---

Cargo.lock
Cargo.toml

#5131 and https://github.com/GreptimeTeam/greptime-proto/pull/204
As title. Forget to update rev QAQ.

chore: update proto rev

---

config/config.md
config/datanode.example.toml
config/standalone.example.toml
src/mito2/src/cache.rs
src/mito2/src/config.rs
src/mito2/src/read/scan_region.rs
src/mito2/src/sst/index/inverted_index/applier/builder.rs
src/mito2/src/sst/index/inverted_index/creator.rs
src/mito2/src/worker.rs

fix!: correct index cache config

---

src/flow/src/adapter.rs
src/flow/src/adapter/node_context.rs
src/flow/src/adapter/stat.rs
src/flow/src/adapter/util.rs
src/flow/src/server.rs

fix a bug that flow worker didn't actually run in parallel due to a wrong blocking operation

fix: make flow worker actually run in parallel

---

src/pipeline/src/dispatcher.rs
src/pipeline/src/etl.rs
src/pipeline/src/etl/error.rs
src/pipeline/src/etl/transform.rs
src/pipeline/src/etl/transform/transformer/greptime.rs
src/pipeline/src/lib.rs

This is patch adds dispatcher definition to pipeline yaml, as the part 1 of pipeline dispatcher #5326 
The implementation is slight different from what I described in the issue. The default rule is removed and current pipeline will be treated as the default one.

feat: pipeline dispatch part 1, add definition

---

.github/workflows/develop.yml

Test if arm builders are capable for running tests.

ci: use arm builders for tests

---

.github/workflows/develop.yml

ci: revert coverage runner

---

src/cmd/src/cli.rs

#5414 
better error msg when can't found http addr(or other errors)

chore: better error msg

---

grafana/greptimedb-cluster.json

Notable changes:
Adjust header:
New flownode row:
Flownode-related resources

feat(grafana): update cluster dashboard to include flow-related metrics

---

Cargo.lock
src/servers/src/http/logs.rs
tests-integration/Cargo.toml
tests-integration/src/test_util.rs
tests-integration/tests/http.rs

Fix a panic from prometheus metric registry. Add integration test to cover this endpoint

fix(log-query): panic on prometheus

---

src/mito2/src/sst/index/bloom_filter/applier.rs

fix: unexpected warning on applying bloom

---

docker/dev-builder/android/Dockerfile

fix: install x86-64 protoc on android dev-builder

---

Cargo.lock
src/servers/Cargo.toml
src/servers/src/http.rs
src/servers/src/http/test_helpers.rs
tests-integration/Cargo.toml
tests-integration/tests/http.rs

This allows our dashboard to send request from tauri.

feat: add CORS headers for http interfaces

---

README.md

Happy new year and new roadmap

docs: the year is better to show in 2025

---

Cargo.lock
Cargo.toml
src/servers/Cargo.toml

update `pprof-rs` as they provide offical fix for alignment issue(https://github.com/tikv/pprof-rs/pull/255)

chore: update pprof

---

README.md
config/config.md
config/datanode.example.toml
docker/docker-compose/cluster-with-etcd.yaml
src/cmd/tests/cli.rs
src/cmd/tests/load_config_test.rs
tests/runner/src/env.rs

This PR is a continuation of #5457, where the old parameters passed the test. In this PR, we will change the startup parameter to a new name.

refactor!: unify the option names across all components part2

---

src/datanode/src/region_server.rs

Happy new year.
after some debugging for #5466 just found that
the second `drop table` is from short cut in handle_request:
```rs
let region_change = match &request {
RegionRequest::Create(create) => {
let attribute = parse_region_attribute(&create.engine, &create.options)?;
RegionChange::Register(attribute)
}
RegionRequest::Open(open) => {
let attribute = parse_region_attribute(&open.engine, &open.options)?;
RegionChange::Register(attribute)
}
RegionRequest::Close(_) => RegionChange::Deregisters,
RegionRequest::Put(_)
| RegionRequest::Drop(_)
| RegionRequest::Delete(_)
| RegionRequest::Alter(_)
| RegionRequest::Flush(_)
| RegionRequest::Compact(_)
| RegionRequest::Truncate(_) => …
```

fix: close issue #5466 by do not shortcut the drop command

---

src/common/meta/src/kv_backend/postgres.rs

learned from https://github.com/GreptimeTeam/greptimedb/pull/5309
before this patch:
after this patch

fix: refactor pgkv using prepare_cache about 10% better

---

src/puffin/src/puffin_manager.rs
src/puffin/src/puffin_manager/fs_puffin_manager/reader.rs

feat: add metadata method to puffin reader

---

.github/workflows/apidoc.yml
.github/workflows/dependency-check.yml
.github/workflows/dev-build.yml
.github/workflows/develop.yml
.github/workflows/docbot.yml
.github/workflows/docs.yml
.github/workflows/nightly-build.yml
.github/workflows/nightly-ci.yml
.github/workflows/release-dev-builder-images.yaml
.github/workflows/release.yml
.github/workflows/schedule.yml
.github/workflows/semantic-pull-request.yml

close: #5281
more info:
https://woodruffw.github.io/zizmor/trophy-case/
my case:
https://github.com/yihong0618/running_page/pull/774
before:
after:

ci: safe ci using zizmor check

---

src/promql/src/extension_plan/union_distinct_on.rs

fix: drop useless clone and for loop second

---

src/cli/src/bench.rs
src/common/meta/Cargo.toml
src/common/meta/src/error.rs
src/common/meta/src/kv_backend.rs
src/common/meta/src/kv_backend/rds.rs
src/common/meta/src/kv_backend/rds/postgres.rs
src/meta-srv/src/bootstrap.rs
src/meta-srv/src/election/postgres.rs

As title. Mostly split original `postgres.rs` to `rds.rs` and `postgres.rs`.

refactor: refactor pg kvbackend impl in preparation for other rds kvbackend

---

.github/actions/build-greptime-images/action.yml
.github/actions/build-images/action.yml
.github/workflows/nightly-build.yml
.github/workflows/release.yml

ci: don't push nightly latest image

---

src/log-query/src/log_query.rs
src/query/src/log_query/planner.rs

feat(log-query): support specifying exclusive/inclusive for between filter

---

src/mito2/src/metrics.rs
src/mito2/src/sst/index/puffin_manager.rs

Collect cache and read metrics for the stager.

feat: collect stager metrics

---

src/common/meta/src/ddl/create_flow.rs

feat: flow type on creating procedure

---

AUTHOR.md

An unexpected change from https://github.com/GreptimeTeam/greptimedb/pull/5575

fix: broken link in AUTHOR.md

---

src/meta-srv/src/handler/check_leader_handler.rs

fix: all heartbeat channel need to check leader

---

src/promql/src/extension_plan/histogram_fold.rs
tests/cases/standalone/common/promql/simple_histogram.result
tests/cases/standalone/common/promql/simple_histogram.sql

feat(promql): ignore invalid input in histogram plan

---

docs/benchmarks/tsbs/v0.12.0.md

update tsbs benchmark on write&query in cloud

docs: tsbs update

---

typos.toml

more can check: https://github.com/GreptimeTeam/greptimedb/actions/runs/13602606442/job/38030299777?pr=5620

fix: update typos rules to fix ci

---

.cargo/config.toml

This patch speed up build and clippy first time and min the cargo cache
because for now there are quite some git repo in Cargo.toml and some of them has
a huge history like datafusion
after some search found there's an arg for cargo can use sallow clone and speed up the build
both in ci and local so choose to add them in .cargo
the arg is unstable one but greptimedb also used unstable toolchain so maybe its fine.
more to check issues in cargo(also can search `-Zgitoxide -Zgit` in GitHub 
https://github.com/rust-lang/cargo/issues/13285
cc @sunng87 
without this patch
with this patch

fix: speed up cargo build using sallow clone

---

src/index/src/bloom_filter/applier.rs
src/index/src/bloom_filter/creator.rs

If the last segment was all null, it wound not be written into the bloom filter index. Now fix it.

fix: out of bound during bloom search

---

src/log-query/src/log_query.rs
src/query/src/log_query/planner.rs

Implement:
- Alias for scalar function, aggregate function and as an expr itself
- Compound filter

feat(log-query): implement compound filter and alias expr

---

src/catalog/src/kvbackend/manager.rs
src/catalog/src/lib.rs
src/catalog/src/memory/manager.rs

feat: get tables by ids in catalog manager

---

src/frontend/src/instance/jaeger.rs
src/servers/src/http/jaeger.rs
src/servers/src/otlp/trace.rs
src/servers/src/otlp/trace/span.rs
src/servers/src/otlp/trace/v0.rs
src/servers/src/otlp/trace/v1.rs
tests-integration/tests/http.rs

This PR mainly improves the content and format of Jaeger's trace API response. It should now be identical to Jaeger's response, to the best of my ability.
Before
After

chore: improve `/v1/jaeger/api/trace/{trace_id}`'s resp

---

src/query/src/dist_plan/analyzer.rs

Overrides #5670
Use a more semantic way to compare columns

fix: update column requirements to use Column type instead of String

---

src/mito2/src/compaction.rs
src/mito2/src/memtable.rs
src/mito2/src/memtable/bulk.rs
src/mito2/src/memtable/partition_tree.rs
src/mito2/src/memtable/time_series.rs
src/mito2/src/read/prune.rs
src/mito2/src/read/scan_region.rs
src/mito2/src/sst/parquet/reader.rs
src/mito2/src/test_util/memtable_util.rs
src/query/src/dummy_catalog.rs
tests/cases/standalone/common/order/windowed_sort.result
tests/cases/standalone/common/select/tql_filter.result
tests/cases/standalone/common/tql-explain-analyze/analyze.result

This PR supports filtering on the time index column exactly.

feat: support exact filter on time index column

---

.github/workflows/grafana.yml
grafana/check.sh
grafana/greptimedb-cluster.json
grafana/summary.sh

Add description for each panel of our cluster dashboard.
Feel free to correct/enrich.

feat: add description for each grafana panel

---

.github/workflows/dev-build.yml

Echo the corresponding image tag

feat: add Docker image tag information to step summary in dev-build workflow

---

src/common/recordbatch/src/filter.rs
tests/cases/standalone/optimizer/filter_push_down.result
tests/cases/standalone/optimizer/filter_push_down.sql

Gain 20~30% end to end performance improvements in test scenarios (`WHERE xxx IN (.....)`)

perf: support in list in simple filter

---

src/servers/src/http/event.rs

As the title suggests, preventing checking input that contains non-UTF8 bytes leads to the failure of auto conversion to string for the whole bulk in the framework layer.

chore: use `Bytes` instead of string in bulk ingestion

---

Cargo.lock
Cargo.toml
tests-integration/Cargo.toml
tests/runner/Cargo.toml

This reverts commit a5df3954f39fd479959dbd7064cdf3a87a50b05a.
revert the commit and leave an issue https://github.com/rust-lang/flate2-rs/issues/478
waiting for the response

chore: revert commit update flate2 version (#5706)"

---

src/frontend/src/instance/logs.rs
src/servers/src/query_handler.rs

* add some method to LogQueryHandler for some enterprise functionals.

chore: add some method for log query handler

---

src/datanode/src/lib.rs
src/datanode/src/store.rs
src/datanode/src/store/fs.rs
src/metric-engine/src/lib.rs
src/metric-engine/src/row_modifier.rs
src/mito2/src/access_layer.rs
src/mito2/src/config.rs
src/mito2/src/error.rs
src/mito2/src/lib.rs
src/mito2/src/region.rs
src/mito2/src/region/opener.rs
src/mito2/src/row_converter/sparse.rs
src/mito2/src/sst/index.rs
src/mito2/src/sst/index/intermediate.rs
src/mito2/src/sst/parquet.rs

and other tweaks to allow easier manually ingest sst

feat: load manifest manually in mito engine

---

src/servers/src/mysql/helper.rs

also deal with bool value when preparing query and replace query parameters

fix: mysql prepare bool value

---

README.md

docs: adds news to readme

---

src/pipeline/benches/processor.rs
src/pipeline/src/error.rs
src/pipeline/src/etl.rs
src/pipeline/src/etl/transform/transformer/greptime.rs
src/pipeline/src/etl/value/time.rs
src/pipeline/src/lib.rs
src/pipeline/src/manager.rs
src/pipeline/tests/common.rs
src/pipeline/tests/dissect.rs
src/pipeline/tests/pipeline.rs
src/servers/src/elasticsearch.rs
src/servers/src/http/event.rs
src/servers/src/otlp/logs.rs
src/servers/src/pipeline.rs
tests-integration/tests/http.rs

chore: support custom time index selector for identity pipeline

---

src/meta-srv/src/bootstrap.rs
src/meta-srv/src/election/mysql.rs
src/meta-srv/src/election/postgres.rs

Unit test for mysql election, also fixed a bug found by ut.

chore: ut and some fix

---

docs/rfcs/2025-02-06-remote-wal-purge.md
docs/rfcs/2025-2-6-remote-wal-purge.md

#5474 
As title. [rendered](https://github.com/GreptimeTeam/greptimedb/blob/9cc01661f8285d2d44d7548a92c97ff7174c51f0/docs/rfcs/2025-02-06-remote-wal-purge.md)

docs: rfc for wal purge

---

src/client/src/lib.rs
src/common/grpc/src/channel_manager.rs
src/flow/src/lib.rs
src/flow/src/recording_rules.rs
src/flow/src/recording_rules/frontend_client.rs

add a simple frontend client so flownode can send query to frontend for execution

feat(flow): frontend client for handle sql

---

src/frontend/src/instance/log_handler.rs
src/pipeline/benches/processor.rs
src/pipeline/src/etl.rs
src/pipeline/src/etl/transform.rs
src/pipeline/src/etl/transform/transformer/greptime.rs
src/pipeline/src/lib.rs
src/pipeline/src/manager.rs
src/pipeline/src/manager/pipeline_operator.rs
src/pipeline/src/manager/table.rs
src/pipeline/tests/common.rs
src/pipeline/tests/dissect.rs
src/pipeline/tests/pipeline.rs
src/servers/src/http/event.rs
src/servers/src/pipeline.rs
src/servers/src/query_handler.rs

As the title suggests, this PR mainly removes the `Transformer` trait, which is a technique debt.

chore: remove `Transformer` trait

---

Cargo.lock
src/cmd/src/datanode.rs
src/cmd/src/flownode.rs
src/cmd/src/frontend.rs
src/common/meta/src/ddl.rs
src/meta-client/Cargo.toml
src/meta-client/src/client.rs
src/meta-client/src/lib.rs

#5739 
Expose `AskLeader` struct and introduce `RegionFollowerClient` trait

feat: introduce `RegionFollowerClient` trait

---

src/common/function/src/admin.rs
src/common/function/src/admin/add_region_follower.rs
src/common/function/src/admin/remove_region_follower.rs
src/common/function/src/handlers.rs
src/common/function/src/state.rs
src/operator/src/procedure.rs

#5739 
Add admin functions `add_region_follower`,`remove_region_follower`.

feat: add `AddRegionFollower` and `RemoveRegionFollower` admin fn

---

src/cmd/src/frontend.rs
src/cmd/src/standalone.rs
src/frontend/src/frontend.rs

In #5754, some methods needed by the greptimedb enterprise were accidentally deleted.
This PR adds back these methods needed by the greptime enterprise that were accidentally deleted.

chore: expose some methods

---

src/datatypes/src/vectors.rs
src/datatypes/src/vectors/dictionary.rs
src/datatypes/src/vectors/helper.rs

A very basic implementation of DictionaryVector. Mostly a placeholder.

feat: simple implementation of DictionaryVector

---

src/mito2/src/memtable/time_series.rs
src/mito2/src/read.rs

... when scanning time-series memtable.
Gains about 20% memtable scan speed for me:
before:
```text
greptime_mito_read_stage_elapsed_bucket{stage="scan_memtable",le="0.01"} 0
greptime_mito_read_stage_elapsed_bucket{stage="scan_memtable",le="0.1"} 0
greptime_mito_read_stage_elapsed_bucket{stage="scan_memtable",le="1"} 62
greptime_mito_read_stage_elapsed_bucket{stage="scan_memtable",le="10"} 62
greptime_mito_read_stage_elapsed_bucket{stage="scan_memtable",le="100"} 62
greptime_mito_read_stage_elapsed_bucket{stage="scan_memtable",le="1000"} 62
greptime_mito_read_stage_elapsed_bucket{stage="scan_memtable",le="10000"} 62
greptime_mito_read_stage_elapsed_bucket{stage="scan_memtable",le= …
```

refactor: skip re-taking arrays in memtable if possible

---

.github/actions/build-windows-artifacts/action.yml
.github/workflows/nightly-ci.yml

This patch close issue #3902 sicne upstream https://github.com/nextest-rs/nextest/issues/1493
had beed fixed and for greptimedb ci checked the code  cargo-nextest seems use the 
latest version, so wating the ci
- Describe if this PR will break **API or data compatibility**  (optional)
-->
Please convert it to a draft if some of the following …

fix: close issue #3902 since upstream fixed

---

src/flow/src/adapter.rs
src/flow/src/adapter/util.rs
src/flow/src/error.rs
src/flow/src/recording_rules.rs
src/flow/src/recording_rules/time_window.rs
src/flow/src/recording_rules/utils.rs

recording rule's time window expr handling functions

feat(flow): time window expr

---

src/meta-srv/Cargo.toml
src/meta-srv/src/handler.rs
src/meta-srv/src/lib.rs
src/meta-srv/src/procedure.rs
src/meta-srv/src/procedure/test_util.rs

chore: expose modules

---

tests/cases/standalone/common/flow/flow_view.result
tests/cases/standalone/common/flow/flow_view.sql

looser condition in sqlness to prevent test failure when it shouldn't fail

test: looser condition

---

src/sql/src/parser.rs
src/sql/src/parsers/insert_parser.rs
tests/cases/standalone/common/insert/insert.result
tests/cases/standalone/common/insert/insert.sql

Our put operation is similar to MySQL's `REPLACE INTO`.
This PR allows the database handling `REPLACE INTO` like regular insert requests.

feat: support REPLACE INTO statement

---

README.md

Initially there was what I think was a typo: `s/archive/achieve` Then I thought some clarification might be nice on this great achievement.
Simple text change on the README to be clear and correct.

clear message for an awesome achievement

---

Cargo.lock
Cargo.toml
src/servers/Cargo.toml
tests-integration/Cargo.toml
tests/runner/Cargo.toml

chore: remove patch.crates-io for rustls

---

src/mito2/src/sst/index/fulltext_index/applier.rs
src/mito2/src/sst/index/fulltext_index/applier/builder.rs
src/mito2/src/sst/index/fulltext_index/creator.rs

* intro `FulltextRequest` which contains `queries` and `terms`
* extract `FulltextRequest` in applier builder

feat: add term as fulltext index request

---

src/promql/src/extension_plan/range_manipulate.rs

One more check for some dumb cases. Like missing one number in the timestamp...
Before
After

feat: shorten possible wrong query range

---

src/servers/src/tls.rs

Update how we read TLS private key with rustls_pem API. Also added support for Sec1 key.

refactor: simplify tls key read code and add sec1 key support

---

src/datanode/src/store.rs

chore: remove obsolete way of passing http configurations through env

---

Cargo.lock
src/common/function/Cargo.toml
src/common/function/src/handlers.rs
src/common/function/src/state.rs
src/frontend/src/instance/builder.rs
src/operator/src/procedure.rs

Add `catalog_manager` to `ProcedureServiceHandler`

feat: add `catalog_manager` to `ProcedureServiceHandler`

---

Cargo.lock
src/common/grpc/Cargo.toml
src/common/grpc/src/channel_manager.rs

#5874
This pr mainly do two things:
1. fix gRPC connection pool leak.
2. refactor the ChannelManager to make clone more lightweight.

fix: gRPC connection pool leak

---

tests-integration/tests/http.rs

This patch adds json object and array in integration tests to ensure the behaviour

test: add tests to ensure nested data structure for identity pipeline

---

config/config.md
config/datanode.example.toml
config/frontend.example.toml
config/standalone.example.toml
src/datanode/src/config.rs
src/datanode/src/datanode.rs
src/flow/src/adapter.rs
src/flow/src/server.rs
src/flow/src/test_utils.rs
src/flow/src/transform.rs
src/frontend/src/frontend.rs
src/frontend/src/instance/builder.rs
src/query/src/datafusion.rs
src/query/src/lib.rs
src/query/src/options.rs
src/query/src/query_engine.rs
src/query/src/query_engine/context.rs
src/query/src/query_engine/default_serializer.rs
src/query/src/query_engine/state.rs
src/query/src/range_select/plan_rewrite.rs
src/query/src/tests.rs
src/query/src/tests/query_engine_test.rs
src/query/src/tests/time_range_filter_test.rs
src/servers/tests/mod.rs

Add `[query]` section to frontend/datanode/flownode config

feat: add query engine options

---

src/datanode/src/metrics.rs
src/datanode/src/region_server.rs

- Add `region_id` label to `greptime_datanode_handle_region_request_elapsed` metric
- Add new metric `greptime_datanode_region_changed_row_count` with per-region insert/delete row count

feat: report per-region metrics on region server

---

Cargo.toml
src/cmd/src/flownode.rs
src/cmd/src/standalone.rs
src/common/meta/src/ddl/create_flow.rs
src/flow/src/adapter.rs
src/flow/src/adapter/flownode_impl.rs
src/flow/src/batching_mode.rs
src/flow/src/batching_mode/engine.rs
src/flow/src/batching_mode/state.rs
src/flow/src/batching_mode/task.rs
src/flow/src/engine.rs
src/flow/src/error.rs
src/flow/src/lib.rs
src/flow/src/server.rs
src/meta-client/src/client.rs
tests-integration/src/standalone.rs

- add `FlowDualEngine` for manage both stream/batch engine
- add `FlowEngine` trait and impl for all three engine
- other refactors

feat(flow): dual engine

---

src/frontend/src/instance/promql.rs
tests-integration/src/test_util.rs
tests-integration/tests/http.rs

closes https://github.com/GreptimeTeam/greptimedb/issues/5909
Fix a panic introduced in https://github.com/GreptimeTeam/greptimedb/pull/5653

fix: label values potential panic

---

src/common/meta/src/datanode.rs
src/meta-srv/src/handler/extract_stat_handler.rs
src/meta-srv/src/metrics.rs

chore: add heartbeat metrics

---

Cargo.toml

remove accidentally added dev profile opt level 3 for depend, which slowdown CI

chore: rm dev opt level 3

---

src/meta-srv/src/metrics.rs

chore: better buckets for heartbeat stat size histogram

---

src/flow/src/adapter.rs

chore: remove unused attribute

---

.github/workflows/develop.yml
src/meta-srv/src/procedure/wal_prune.rs

try see if it's offset by one
edit: after 3 try on CI Remote WAL-fuzz_failover_metric_regions, none failed, seems like it's the problem

fix: try prune one less

---

src/meta-srv/src/region/supervisor.rs

This PR adds failover attempt tracking to the region supervisor to improve region migration reliability.

feat: track region failover attempts and adjust timeout

---

src/meta-srv/src/bootstrap.rs
src/meta-srv/src/metasrv/builder.rs
src/meta-srv/src/node_excluder.rs
src/meta-srv/src/selector.rs
src/meta-srv/src/selector/lease_based.rs
src/meta-srv/src/selector/load_based.rs
src/meta-srv/src/selector/round_robin.rs

enhance selector with node exclusion support

feat: enhance selector with node exclusion support

---

src/meta-srv/src/metrics.rs
src/meta-srv/src/procedure/region_migration.rs
src/meta-srv/src/procedure/region_migration/close_downgraded_region.rs
src/meta-srv/src/procedure/region_migration/downgrade_leader_region.rs
src/meta-srv/src/procedure/region_migration/migration_abort.rs
src/meta-srv/src/procedure/region_migration/migration_end.rs
src/meta-srv/src/procedure/region_migration/open_candidate_region.rs
src/meta-srv/src/procedure/region_migration/upgrade_candidate_region.rs

improve observability of region migration procedure

feat: improve observability of region migration procedure

---

Cargo.lock
Cargo.toml
src/common/function/src/scalars/uddsketch_calc.rs
src/flow/src/batching_mode.rs
src/flow/src/batching_mode/frontend_client.rs
src/flow/src/batching_mode/task.rs
src/flow/src/batching_mode/time_window.rs
src/flow/src/batching_mode/utils.rs
src/flow/src/df_optimizer.rs
src/query/src/lib.rs
tests/cases/standalone/common/flow/flow_step_aggr.result
tests/cases/standalone/common/flow/flow_step_aggr.sql

some fixes for flow, including:
- add a 3s conn timeout for grpc
- refactor for better error message when rewrite failed
- fix `udd_calc` panic by checking for empty first, before this fix a empty input(or a null array input) will cause panic when calling `udd_calc`
- add sqlness for `udd_calc` and `hll`
- add retry for frontend client so network fluctuate won't affect flow execution (also when recovering flow, this retry make it more resistant in case frontend is still starting) 
- fix datafusion to substrait encode by replace `cast(null, <data type>)` to Typed Null in substrait, see https://github.com/waynexia/arrow-datafusion/pull/116 and new unit test
- use the same analyzer …

fix: conn timeout&refactor: better err msg

---

flake.lock
flake.nix

update nix files for toolchain change

chore: update nix for new toolchain

---

src/cmd/src/metasrv.rs
src/common/meta/src/kv_backend.rs
src/common/meta/src/kv_backend/util.rs
src/meta-srv/src/metasrv.rs

fix: sanitize_connection_string

---

src/common/meta/src/lock_key.rs

chore: rename parameter from "table" to "flow_name" 

---

src/datanode/src/datanode.rs

- fixes #6014
Always creates mito/file/metric engine regardless of config file.

fix: always create mito engine

---

.github/workflows/nightly-ci.yml

The nix CI task has been broken for a while, this patch updates nix action to see if it helps.

ci: nix action update

---

.github/scripts/update-dev-builder-version.sh
.github/workflows/release-dev-builder-images.yaml
Cargo.lock
Cargo.toml
src/client/src/database.rs
src/cmd/src/metasrv.rs
src/common/meta/src/kv_backend.rs
src/common/meta/src/kv_backend/util.rs
src/datanode/src/datanode.rs
src/flow/src/adapter/flownode_impl.rs
src/flow/src/batching_mode.rs
src/flow/src/batching_mode/engine.rs
src/flow/src/batching_mode/frontend_client.rs
src/flow/src/error.rs
src/flow/src/server.rs
src/meta-srv/src/metasrv.rs
src/operator/src/statement/ddl.rs
tests/cases/standalone/common/flow/flow_advance_ttl.result
tests/cases/standalone/common/flow/flow_advance_ttl.sql
tests/cases/standalone/common/flow/flow_auto_sink_table.result
tests/cases/standalone/common/flow/flow_auto_sink_table.sql
tests/cases/standalone/common/flow/flow_basic.result
tests/cases/standalone/common/flow/flow_basic.sql
tests/cases/standalone/common/flow/flow_rebuild.result
tests/cases/standalone/common/flow/flow_rebuild.sql
tests/cases/standalone/common/flow/show_create_flow.result
tests/cases/standalone/common/flow/show_create_flow.sql

closes #6033
bump version to 0.14.2, mainly for #6031, but also cherry-picked other fixes

chore: bump version to 0.14.2

---

.github/workflows/release.yml
README.md
cyborg/bin/bump-website-version.ts

Depends on https://github.com/GreptimeTeam/website/pull/1056
Learned from #5343 

ci: update website greptimedb version when releasing automatically

---

src/cmd/src/datanode.rs
src/cmd/src/frontend.rs
src/cmd/src/standalone.rs
src/common/config/src/config.rs
src/common/config/src/lib.rs
src/datanode/src/datanode.rs
src/datanode/src/greptimedb_telemetry.rs
src/frontend/src/server.rs
src/servers/src/lib.rs
src/servers/tests/http/http_handler_test.rs

as title
compatibility is checked in https://github.com/GreptimeTeam/greptimedb/pull/5809

refactor: remove the "mode" configuration item completely

---

Cargo.lock
src/flow/Cargo.toml

should fix #6024 and close #6046

chore: rm unnecessary depend for flow

---

.github/workflows/nightly-ci.yml
Cargo.lock
src/servers/Cargo.toml
src/servers/src/postgres/server.rs

This patch includes pgwire 0.29 which brings a minor bugfix to prevent panic.

feat: update pgwire to 0.29

---

.github/workflows/develop.yml

Don't run cron schedule in personal repository, alway failure.

ci: run only in the `GreptimeTeam/greptimedb` repository

---

src/client/src/database.rs
src/client/src/error.rs
src/common/meta/src/key/table_route.rs
src/datanode/src/datanode.rs
src/servers/src/error.rs
src/servers/src/grpc/flight.rs
src/servers/src/grpc/greptime_handler.rs
src/servers/src/grpc/prom_query_gateway.rs
src/servers/src/hint_headers.rs
src/servers/src/server.rs
src/session/src/context.rs

feat: set read-preference for grpc client

---

.github/scripts/update-helm-charts-version.sh
.github/workflows/release.yml

Need to configure github secret: `HELM_CHARTS_REPO_TOKEN`

ci: automatically update helm-charts when release

---

src/common/mem-prof/Cargo.toml

chore: mv anyhow depend out of cfg

---

.github/scripts/update-homebrew-greptme-version.sh
.github/workflows/release.yml

wait for: https://github.com/GreptimeTeam/homebrew-greptime/pull/36

ci: update homebrew greptime version when release

---

src/common/mem-prof/src/lib.rs

more cfg for compile on windows

chore: more cfg stuff on windows

---

src/servers/src/http/mem_prof.rs

fix clippy error by feature-gating Query import

chore: fix clippy error by feature-gating Query import

---

src/meta-srv/src/region/lease_keeper.rs

Prevents redundant metadata collection for tables with multiple regions

fix: table metadata collection

---

.github/workflows/nightly-ci.yml

The nix CI goes oom on linking. This patch switch to mold to see if it helps.

ci: update nix build linker

---

src/client/src/database.rs
src/client/src/region.rs
src/common/grpc/src/flight.rs
src/operator/src/bulk_insert.rs
src/partition/src/multi_dim.rs
src/partition/src/partition.rs
src/partition/src/splitter.rs
src/servers/src/grpc/flight/stream.rs
src/store-api/src/region_request.rs

- #5803 
- **Refactor `try_decode` Method**: Updated the `try_decode` method in `FlightDecoder` to accept a reference to `FlightData` instead of consuming it. This change affects `database.rs`, `region.rs`, `flight.rs`, `bulk_insert.rs`, `stream.rs`, and `region_request.rs`.                                         
- **Optimize Bulk Insert Handling**: Implemented a fast path for handling bulk inserts when only one region is involved in `bulk_insert.rs`. This includes changes to the handling of `RegionRequest` and `RegionMask`.                                                                                            
- **Enhance Partitioning Logic**: Introduced `RegionMask` to …

fix: fast path for single region bulk insert

---

src/pipeline/src/error.rs
src/pipeline/src/etl.rs
src/servers/src/http/event.rs
tests-integration/tests/http.rs

* Add more data format support to the pipeline dryrun api.
* Add the `data_type` field to specify the format of the data content.
* The `data` field must be of type string
**This pr is a breaking change to the dry_run API.**

chore: Add more data format support to the pipeline dryrun api.

---

.github/workflows/semantic-pull-request.yml

Adds write permission to the semantic check job so we can add labels to the PR.
Tested in https://github.com/evenyag/greptimedb/pull/19
However, we might have to merge this into the main branch to see if it really works.

ci: add pull requests permissions to semantic check job

---

.github/CODEOWNERS
.github/scripts/create-version.sh
.github/scripts/deploy-greptimedb.sh
.github/scripts/upload-artifacts-to-s3.sh
.github/workflows/develop.yml
.github/workflows/release.yml
.gitignore

This PR enables typo checking for the `.github` folder and fixes various typos.

chore: enable github folder typo check and fix typos

---

Cargo.toml
flake.nix
rust-toolchain.toml
src/common/function/src/aggr/uddsketch_state.rs
src/common/function/src/scalars/ip/cidr.rs
src/common/function/src/scalars/ip/ipv6.rs
src/common/meta/src/key/flow/flow_route.rs
src/flow/src/compute/state.rs
src/meta-srv/src/lease.rs
src/operator/src/req_convert/common.rs
src/operator/src/statement/ddl.rs
src/promql/src/functions.rs
src/query/src/window_sort.rs

chore: update toolchain to 2025-05-19

---

src/common/meta/src/key/datanode_table.rs

chore: reduce unnecessary txns in alter operations

---

src/operator/src/statement/ddl.rs
src/servers/src/prom_store.rs
tests-integration/tests/http.rs

The procedure only handles one physical at a time. This patch add an extra grouping logic before submitting alter logical tables procedure

feat: support altering multiple logical table in one remote write request

---

.github/actions/setup-greptimedb-cluster/with-remote-wal.yaml
src/common/wal/src/config.rs
tests/conf/datanode-test.toml.template
tests/conf/standalone-test.toml.template

related to https://github.com/GreptimeTeam/greptimedb/pull/5808
Remove some outdated things

chore: remove stale wal config entries

---

tests-integration/tests/grpc.rs

**Refactor gRPC Test Assertions in `grpc.rs`**
- Updated test assertions for `test_prom_gateway_query` to improve clarity and maintainability.
- Replaced direct comparison with expected `PrometheusJsonResponse` objects with individual field assertions.
- Added sorting for `vector` and `matrix` results to ensure consistent test outcomes.

fix: flaky prom gateway test

---

src/mito2/src/worker/handle_write.rs

- Updated logic to account for both `write_requests` and `bulk_requests` when adjusting `stalled_count`.
- Modified `reject_region_stalled_requests` and `handle_region_stalled_requests` to correctly subtract the combined length of `requests` and `bulk` from `stalled_count`.

fix: region worker stall metrics

---

.github/workflows/semantic-pull-request.yml

fixed to: https://github.com/GreptimeTeam/greptimedb/actions/runs/15155518237/job/42610589439

ci: add issues write permission

---

src/operator/src/statement/set.rs
tests/cases/standalone/common/system/pg_catalog.result
tests/cases/standalone/common/system/pg_catalog.sql

fix: ident value in set search_path

---

src/metric-engine/src/engine/read.rs

chore: change info to debug for scanning physical table

---

src/common/meta/src/kv_backend/rds.rs
src/common/meta/src/kv_backend/rds/mysql.rs
src/common/meta/src/kv_backend/rds/postgres.rs
src/common/meta/src/lib.rs
src/common/meta/src/metrics.rs

* add metrics for rds kv backend

chore: add metrics for rds kv backend

---

src/cli/src/meta_snapshot.rs
src/common/meta/src/kv_backend.rs
src/meta-srv/src/metasrv.rs

fix feature gates for pg and mysql kvbackend

chore: fix feature gates for pg and mysql kvbackend

---

licenserc.toml
src/frontend/Cargo.toml
src/frontend/src/instance.rs
src/operator/Cargo.toml
src/operator/src/error.rs
src/operator/src/statement.rs
src/operator/src/statement/ddl.rs
src/sql/Cargo.toml
src/sql/src/error.rs
src/sql/src/parsers/create_parser.rs
src/sql/src/parsers/create_parser/trigger.rs
src/sql/src/statements/create.rs
src/sql/src/statements/create/trigger.rs
src/sql/src/statements/statement.rs

The design detail see https://github.com/GreptimeTeam/greptimedb-enterprise/issues/195

feat: support parsing trigger create sql

---

Cargo.lock
src/servers/Cargo.toml
src/servers/src/postgres/handler.rs

Update pgwire to latest release so it doesn't require chrono 0.4.40, which is only compatible with later version of arrow/datafusion ecosystem.

feat: update pgwire to 0.30

---

config/config.md
config/metasrv.example.toml

chore: example of http config in metasrv

---

src/common/meta/src/ddl/alter_logical_tables.rs
src/common/meta/src/ddl/alter_logical_tables/table_cache_keys.rs

chore: clear metadata filed after updating metadata

---

docs/how-to/how-to-profile-memory.md

docs: fix bad link

---

.github/workflows/dev-build.yml

ci: add option to choose whether upload artifacts to S3 in the development build

---

src/cli/Cargo.toml

fix: add missing features

---

Cargo.lock
Cargo.toml
src/flow/Cargo.toml
src/flow/src/adapter/worker.rs
src/flow/src/batching_mode/engine.rs
src/flow/src/batching_mode/task.rs
src/flow/src/batching_mode/utils.rs
src/flow/src/compute/render.rs
src/flow/src/compute/render/map.rs
src/flow/src/compute/render/reduce.rs
src/flow/src/compute/render/src_sink.rs
src/flow/src/compute/state.rs
src/flow/src/compute/types.rs
src/flow/src/expr/scalar.rs
src/flow/src/server.rs
src/frontend/src/instance/grpc.rs
src/frontend/src/instance/opentsdb.rs
src/frontend/src/instance/otlp.rs
src/frontend/src/instance/prom_store.rs
src/metric-engine/src/data_region.rs
src/mito2/src/memtable/time_series.rs
src/operator/src/insert.rs
src/pipeline/src/manager/table.rs
tests-integration/src/test_util.rs
tests-integration/tests/http.rs
tests/cases/standalone/common/alter/alter_physical_table.result
tests/cases/standalone/common/alter/alter_physical_table.sql

close https://github.com/GreptimeTeam/greptimedb/issues/6241
release v0.14.4

chore: bump version to 0.14.4

---

src/cli/src/bench.rs
src/cli/src/error.rs
src/cli/src/export.rs
src/cli/src/import.rs
src/cli/src/lib.rs
src/cli/src/meta_snapshot.rs
src/cmd/src/cli.rs
src/common/meta/src/snapshot.rs
src/common/meta/src/snapshot/file.rs
src/plugins/src/cli.rs

**BREAKING** This PR may break existing user import/export scripts
* Reorganized subcommand 
* add info command to explore meta snapshot file
https://github.com/GreptimeTeam/docs/pull/1825

refactor(cli)!: reorganize cli subcommands

---

.github/actions/setup-greptimedb-cluster/action.yml
.github/scripts/deploy-greptimedb.sh

related to: 
- https://github.com/GreptimeTeam/helm-charts/blob/main/charts/greptimedb-cluster/values.yaml#L463
- https://docs.greptime.com/nightly/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations/#using-etcd-as-backend-storage

ci: use the new meta backendStorage etcd structure

---

grafana/README.md

https://github.com/GreptimeTeam/docs/pull/1831
fix a doc link

fix: doc links

---

src/query/src/datafusion.rs

as title, check for non-zero parallelism

fix: check for zero parallelism

---

Cargo.lock
Cargo.toml
src/client/src/flow.rs
src/common/meta/src/node_manager.rs
src/common/meta/src/test_util.rs
src/flow/src/adapter.rs
src/flow/src/adapter/flownode_impl.rs
src/flow/src/batching_mode/engine.rs
src/flow/src/batching_mode/state.rs
src/flow/src/batching_mode/task.rs
src/flow/src/metrics.rs
src/flow/src/server.rs
src/frontend/src/instance/grpc.rs
src/operator/src/bulk_insert.rs
src/operator/src/error.rs
src/operator/src/insert.rs
src/servers/src/grpc/greptime_handler.rs
src/servers/src/query_handler/grpc.rs
src/servers/tests/mod.rs

This PR implements dirty window notification mechanism in bulk insert path to notify flownode the recently update time windows so flownode can rerun batch tasks.

feat: bulk support flow batch

---

src/cmd/src/flownode.rs
src/flow/src/server.rs
src/meta-srv/src/metasrv.rs
src/meta-srv/src/metasrv/builder.rs

refactor: make flownode gRPC services able to be added dynamically

---

src/pipeline/src/error.rs
src/pipeline/src/etl/transform.rs
src/pipeline/src/etl/transform/transformer/greptime.rs
src/pipeline/src/lib.rs
src/pipeline/tests/gsub.rs
src/servers/src/elasticsearch.rs
src/servers/src/http/event.rs
src/servers/src/http/loki.rs
src/servers/src/pipeline.rs
tests-integration/tests/http.rs

chore: add skip error for pipeline skip error log

---

src/flow/src/adapter/flownode_impl.rs

as title, clean up unused impl, and support use mark dirty time window in standalone

chore: clean up unused impl &standalone use mark dirty

---

src/cmd/src/datanode/builder.rs
src/cmd/src/flownode.rs
src/cmd/src/frontend.rs
src/common/grpc/src/channel_manager.rs
src/common/grpc/src/error.rs
src/datanode/src/service.rs
src/frontend/src/server.rs
src/meta-client/src/client.rs
src/meta-client/src/client/ask_leader.rs
src/meta-client/src/client/cluster.rs
src/meta-client/src/client/heartbeat.rs
src/meta-client/src/client/procedure.rs
src/meta-client/src/lib.rs
src/meta-srv/src/error.rs
src/servers/src/grpc.rs

A dynamic metasrv leader finder can be useful in testing.

refactor: make finding leader in metasrv client dynamic

---

Cargo.lock
src/common/telemetry/Cargo.toml
src/common/telemetry/src/logging.rs

Resolves some of the Rust related security warnings.
- ring
- crossbeam-channel
- atty

chore: security updates

---

src/cmd/src/flownode.rs
src/flow/src/batching_mode/frontend_client.rs

This pr mainly do two things:
1. add `sql` method in `frontend_client`, mainly used by flownode to offload sql queries to frontend and obtain query results.
2. add `Components` in Instance, it is convenient for us to expand the instance of flownode.

feat: support execute sql in frontend_client

---

src/metric-engine/src/engine/create.rs
src/metric-engine/src/engine/open.rs
src/store-api/src/mito_engine_options.rs

We have encountered a few errors with current opt-out approach #5852, #6340 . This patch is to change it to an opt-in way hopefully it gets easier to maintain in long term.
Please add other options to opt-in. @waynexia @WenyXu 

refactor: make metadata region option opt-in

---

README.md

docs: added YouTube link to documentation

---

.github/CODEOWNERS
.github/actions/build-dev-builder-images/action.yml
.github/actions/build-linux-artifacts/action.yml
.github/actions/build-windows-artifacts/action.yml
.github/actions/release-cn-artifacts/action.yaml
.github/actions/setup-greptimedb-cluster/action.yml
.github/actions/setup-greptimedb-cluster/with-remote-wal.yaml
.github/actions/start-runner/action.yml
.github/actions/stop-runner/action.yml
.github/labeler.yaml
.github/scripts/create-version.sh
.github/scripts/deploy-greptimedb.sh
.github/scripts/update-dev-builder-version.sh
.github/scripts/update-helm-charts-version.sh
.github/scripts/update-homebrew-greptme-version.sh
.github/scripts/upload-artifacts-to-s3.sh
.github/workflows/apidoc.yml
.github/workflows/dev-build.yml
.github/workflows/develop.yml
.github/workflows/docbot.yml
.github/workflows/docs.yml
.github/workflows/nightly-build.yml
.github/workflows/nightly-ci.yml
.github/workflows/pr-labeling.yaml
.github/workflows/release-dev-builder-images.yaml
.github/workflows/release.yml
.github/workflows/semantic-pull-request.yml
.gitignore
typos.toml

https://github.com/GreptimeTeam/greptimedb/issues/6373
Update `.github` to latest version
Except:
- Remove mysql_backend feature from `cargo build`
- Remove workflows/grafana.json

ci: update 0.12 ci to latest

---

src/cmd/src/standalone.rs
src/common/meta/src/ddl_manager.rs
src/meta-srv/src/metasrv/builder.rs
tests-integration/Cargo.toml
tests-integration/src/standalone.rs

Avoid adding features to parameters that may cause semver-incompatible changes

refactor: avoid adding feature to parameter

---

src/cmd/src/standalone.rs

This pr mainly change: a component field is added to the standalone instance to make it easier to expand.

chore: add components for standalone instance

---

src/catalog/src/kvbackend/manager.rs

feat: override logical table's partition key indices

---

config/config.md
config/datanode.example.toml
config/metasrv.example.toml
src/meta-srv/src/metasrv.rs

chore: correct typo in configuration

---

src/servers/src/elasticsearch.rs

1. The original implementation passes the pipeline name from the URL parameter, but it's not general if the collector (for example, Telegraf) doesn't support configuring it. This PR modifies the logic of extracting the pipeline name from the HTTP header.
2. Get DB from query context;

refactor: pass pipeline name through http header and get db from query context

---

src/common/error/src/status_code.rs
src/servers/src/error.rs
src/servers/src/mysql/writer.rs
src/servers/src/postgres/types/error.rs

This pr added two trigger-related error code.
```rust
TriggerAlreadyExists = 9000,
TriggerNotFound = 9001,
```

feat: add trigger-related error code

---

src/client/src/database.rs
src/client/src/error.rs
src/client/src/region.rs
src/common/error/src/status_code.rs
src/meta-client/src/error.rs
src/mito2/src/memtable.rs

refactor: extract the common method for errors into tonic status

---

Cargo.lock
src/catalog/src/kvbackend/manager.rs
src/common/meta/src/key/tombstone.rs
src/common/recordbatch/src/error.rs
src/frontend/Cargo.toml
src/frontend/src/error.rs
src/frontend/src/instance.rs
src/operator/src/error.rs
src/operator/src/statement.rs
src/pipeline/src/etl/ctx_req.rs
src/pipeline/src/lib.rs
src/servers/src/http/loki.rs
tests-integration/tests/http.rs
tests/cases/standalone/common/create/metric_engine_partition.result
tests/cases/standalone/common/create/metric_engine_partition.sql

https://github.com/GreptimeTeam/greptimedb/issues/6354
Pick necessary fixes to 0.15
- logical table partitions
- dest_keys chunks
- max_execution_time support
Pick Loki pipeline supports to 0.15

chore: cherry pick #6385, #6390, #6432, #6446, #6444 to 0.15 branch

---

src/flow/src/adapter.rs
src/partition/src/checker.rs
src/partition/src/collider.rs
src/partition/src/error.rs
src/partition/src/lib.rs
src/partition/src/multi_dim.rs
tests/cases/standalone/common/partition.result
tests/cases/standalone/common/partition.sql

follow up of #6399 
Implement a new point matrix based rule checker to replace the previous AxisRuleChecker. The new checker is more robust. It can recognize bad cases can't be handled before, and won't have false negatives for correct cases.
This new checker will check for both completeness and uniqueness. I.e., we don't need a mechanism like "default region" before as the rule will guarantee all values has a declared region. And we also don't rely on the rule apply order as all region won't non-overlapping with others.
Moreover, the error message is also improved. It will give the uncovered or overlapped value range for invalid …

feat!: point matrix based partition rule checker

---

src/cmd/src/standalone.rs
src/common/meta/src/ddl_manager.rs
src/meta-srv/src/metasrv/builder.rs
tests-integration/Cargo.toml
tests-integration/src/standalone.rs

* refactor: avoid adding feature to parameter
* avoid `cfg(not(feature = ...))` block

chore: cherry pick pr 6391 to release/v0.15

---

src/operator/src/statement/ddl.rs
src/partition/benches/bench_split_record_batch.rs
src/partition/src/checker.rs
src/partition/src/manager.rs
src/partition/src/multi_dim.rs

Part of https://github.com/GreptimeTeam/greptimedb/issues/6450
Skip checking rule on ingestion

feat: skip rule checker on ingestion

---

src/frontend/src/instance.rs
src/operator/src/statement/ddl.rs
src/partition/benches/bench_split_record_batch.rs
src/partition/src/checker.rs
src/partition/src/collider.rs
src/partition/src/error.rs
src/partition/src/expr.rs
src/partition/src/lib.rs
src/partition/src/manager.rs
src/partition/src/multi_dim.rs
src/partition/src/partition.rs
src/query/src/promql/error.rs
src/query/src/promql/planner.rs
src/sql/src/statements/statement.rs
tests/cases/standalone/common/partition.result
tests/cases/standalone/common/partition.sql
tests/cases/standalone/common/promql/label.result
tests/cases/standalone/common/promql/label.sql
tests/cases/standalone/common/promql/simple_histogram.result
tests/cases/standalone/common/promql/simple_histogram.sql

https://github.com/GreptimeTeam/greptimedb/issues/6354
Cherry-pick some fixes and features:
- The new partition rule checker
- label_replace and label_join fix
- more statements support for MAX_EXECUTION_TIME

chore: pick #6399, #6443, #6431, #6453, #6454 to v0.15

---

Cargo.lock
Cargo.toml
src/datatypes/src/schema/column_schema.rs
src/datatypes/src/timestamp.rs
src/mito2/src/error.rs
src/mito2/src/worker/handle_bulk_insert.rs
src/operator/src/bulk_insert.rs

Pick the following fixes to v0.15.0
- #6458 
- #6459 
Bump version to v0.15.1

chore: pick #6458, #6459 to v0.15 and bump version to v0.15.1

---

src/common/time/src/range.rs
src/datanode/src/error.rs
src/datanode/src/tests.rs
src/mito2/src/extension.rs
src/mito2/src/read/scan_region.rs
src/mito2/src/read/scan_util.rs

also add two convenient `From`s for creating the `TimestampRange`

feat: display extension ranges in "explain"

---

Cargo.lock
Cargo.toml
src/query/src/dist_plan/analyzer.rs
tests/cases/standalone/tql-explain-analyze/analyze.result
tests/cases/standalone/tql-explain-analyze/analyze.sql

https://github.com/GreptimeTeam/greptimedb/issues/6507
Cherry pick #6484 to v0.15 branch. Bump version to v0.15.2

chore: cherry pick #6484 and bump version to v0.15.2

---

src/servers/src/export_metrics.rs
src/servers/src/http/prom_store.rs
src/servers/src/metrics.rs

* add db label for PROM_STORE_REMOTE_WRITE_SAMPLES
* add layer to count authenticated requests

chore: add prom store metrics

---

src/pipeline/src/etl/transform/transformer/greptime.rs
src/servers/src/proto.rs

This PR does
1. remove clone in Prometheus to pipeline conversion
2. add comments for `need_calc_ts` and skip ts col name check

chore: minor update for using pipeline with prometheus

---

Cargo.lock
config/config.md
config/flownode.example.toml
src/cmd/src/flownode.rs
src/flow/Cargo.toml
src/flow/src/adapter.rs
src/flow/src/adapter/flownode_impl.rs
src/flow/src/batching_mode.rs
src/flow/src/batching_mode/engine.rs
src/flow/src/batching_mode/frontend_client.rs
src/flow/src/batching_mode/state.rs
src/flow/src/batching_mode/task.rs
src/flow/src/server.rs
tests-integration/tests/http.rs

as title, make batching mode constants into configs

refactor: expose flow batching mode constants to config

---

Cargo.lock
Cargo.toml

https://github.com/GreptimeTeam/greptimedb/issues/6565
bump to v0.15.3

chore: bump version to 0.15.3

---

src/query/src/promql/planner.rs
tests/cases/standalone/common/promql/simple_histogram.result
tests/cases/standalone/common/promql/simple_histogram.sql

https://github.com/GreptimeTeam/greptimedb/issues/6565
Cherry pick https://github.com/GreptimeTeam/greptimedb/pull/6569

chore: cherry pick #6569 to v0.15

---

src/common/meta/src/ddl/table_meta.rs
src/common/meta/src/rpc/ddl.rs
src/common/meta/src/rpc/router.rs
src/operator/src/error.rs
src/operator/src/statement/ddl.rs
src/operator/src/tests/partition_manager.rs
src/partition/src/expr.rs
src/partition/src/partition.rs
tests-fuzz/src/context.rs
tests-fuzz/src/generator/create_expr.rs
tests-fuzz/src/ir/create_expr.rs
tests-fuzz/src/translator/mysql/create_expr.rs

refactor: remove unused PartitionDef

---

src/mito2/src/read/scan_region.rs
src/mito2/src/region/opener.rs
src/mito2/src/sst/index/bloom_filter/applier.rs
src/mito2/src/sst/index/bloom_filter/applier/builder.rs
src/mito2/src/sst/index/fulltext_index/applier.rs
src/mito2/src/sst/index/fulltext_index/applier/builder.rs
src/mito2/src/sst/index/fulltext_index/creator.rs
src/mito2/src/sst/index/inverted_index/applier.rs
src/mito2/src/sst/index/inverted_index/applier/builder.rs
src/mito2/src/sst/index/inverted_index/applier/builder/between.rs
src/mito2/src/sst/index/inverted_index/applier/builder/comparison.rs
src/mito2/src/sst/index/inverted_index/applier/builder/eq_list.rs
src/mito2/src/sst/index/inverted_index/applier/builder/in_list.rs
src/mito2/src/sst/index/inverted_index/applier/builder/regex_match.rs
src/mito2/src/sst/index/inverted_index/creator.rs
src/mito2/src/sst/parquet.rs
src/mito2/src/worker/handle_catchup.rs
src/mito2/src/worker/handle_create.rs
src/mito2/src/worker/handle_open.rs

https://github.com/GreptimeTeam/greptimedb/issues/6409
some follow-up work of #6410

refactor: explicitly accept path type as param

---

Cargo.lock
src/common/meta/src/key/schema_name.rs
src/operator/src/statement/ddl.rs
src/sql/src/parsers/create_parser.rs
src/store-api/src/mito_engine_options.rs
src/table/Cargo.toml
src/table/src/requests.rs
tests/cases/standalone/common/create/create_database_opts.result
tests/cases/standalone/common/create/create_database_opts.sql

feat: supports more db options

---

docs/rfcs/2025-06-20-repartition.md

https://github.com/GreptimeTeam/greptimedb/issues/6558
🖥️ [Rendered](https://github.com/waynexia/greptimedb/blob/repartition-rfc/docs/rfcs/2025-06-20-repartition.md)

docs(rfc): repartition

---

src/api/src/helper.rs
src/common/grpc/src/select.rs
src/datatypes/src/data_type.rs
src/datatypes/src/type_id.rs
src/datatypes/src/types.rs
src/datatypes/src/types/struct_type.rs
src/datatypes/src/value.rs
src/datatypes/src/vectors.rs
src/datatypes/src/vectors/eq.rs
src/datatypes/src/vectors/helper.rs
src/datatypes/src/vectors/struct_vector.rs
src/mito-codec/src/row_converter/dense.rs
src/servers/src/postgres/types.rs
src/sql/src/statements.rs

add struct vector, a thin wrapper around arrow struct array, useful for push down step aggr

feat: struct vector

---

src/common/meta/src/error.rs
src/common/meta/src/reconciliation.rs
src/common/meta/src/reconciliation/reconcile_catalog.rs
src/common/meta/src/reconciliation/reconcile_catalog/end.rs
src/common/meta/src/reconciliation/reconcile_catalog/reconcile_databases.rs
src/common/meta/src/reconciliation/reconcile_catalog/start.rs
src/common/meta/src/reconciliation/reconcile_database/reconcile_logical_tables.rs
src/common/meta/src/reconciliation/utils.rs

#6429 
This PR implements a reconcile catalog procedure, which iterates over schemas and triggers database reconciliation procedures.

feat: introduce reconcile catalog procedure

---

Cargo.lock
Cargo.toml
src/common/function/Cargo.toml
src/flow/Cargo.toml
src/query/Cargo.toml
src/sql/Cargo.toml
src/sql/src/parsers/create_parser.rs
src/sql/src/statements/create.rs

as title, add time unit in show create flow, also add more testcases

fix: show create flow's expire after

---

src/promql/src/extension_plan/instant_manipulate.rs

Prevent running too long from dumb queries (like start timestamp has one less number)

feat: use real data to truncate manipulate range

---

Cargo.lock
src/index/Cargo.toml
src/index/benches/tokenizer_bench.rs
src/index/src/fulltext_index/create/bloom_filter.rs
src/index/src/fulltext_index/tokenizer.rs
src/mito2/src/cache/index/bloom_filter_index.rs
src/mito2/src/cache/index/inverted_index.rs
src/query/src/optimizer/constant_term.rs

https://github.com/GreptimeTeam/greptimedb/issues/6627

chore: pick #6660, #6651 to release/0.16

---

src/query/src/promql/planner.rs
tests/cases/standalone/common/promql/label.result
tests/cases/standalone/common/promql/label.sql

fix: label_join should work with unknown

---

Cargo.lock
src/common/base/src/serde.rs
src/common/telemetry/Cargo.toml
src/common/telemetry/src/logging.rs

#6697 
This PR improves slow query options deserialization by adding better handling for empty strings and missing fields in configuration options, making them more robust when deserializing from JSON.
* Adds serde attributes to handle empty strings as default values for enum fields
* Introduces default functions for `SlowQueryOptions` fields to improve maintainability
* Adds comprehensive test coverage for deserialization edge cases

feat: improve slow queries options deserialization

---

.github/scripts/update-dev-builder-version.sh

ci: add Signed-off-by in update-dev-builder-version script

---

Cargo.lock
Cargo.toml
config/config.md
config/datanode.example.toml
config/flownode.example.toml
config/frontend.example.toml
config/metasrv.example.toml
config/standalone.example.toml
src/common/telemetry/Cargo.toml
src/common/telemetry/src/logging.rs

This patch updates opentelemetry toolset to 0.30.
It also includes an update of our loki protocol.

feat: update opentelemetry family

---

Cargo.lock
src/store-api/Cargo.toml
src/store-api/src/metadata.rs

chore: improve error message when there are more than one time index

---

Cargo.lock
Cargo.toml
src/object-store/Cargo.toml
src/object-store/src/factory.rs
src/object-store/src/layers/lru_cache.rs
src/object-store/src/layers/lru_cache/read_cache.rs

#6749 
Upgrade opendal to v0.54.0

feat: bump opendal to v0.54

---

src/cmd/src/frontend.rs

This is required for greptime operator to use internal grpc.

feat: add cli option for internal grpc

---

.github/scripts/check-version.sh
.github/workflows/develop.yml
.github/workflows/release.yml
.github/workflows/semantic-pull-request.yml
cyborg/bin/bump-versions.ts
cyborg/bin/follow-up-docs-issue.ts
scripts/install.sh
src/index/src/bloom_filter/applier.rs
src/index/src/bloom_filter/creator.rs

1. Update release action
2. pick #5625

chore: cherry pick #5625 to v0.12 branch

---

Cargo.lock
Cargo.toml
src/flow/src/adapter/flownode_impl.rs
src/flow/src/heartbeat.rs
src/frontend/src/heartbeat.rs
src/meta-srv/src/service/heartbeat.rs

This PR picks #6821 to v0.12 branch and bumps version to v0.12.2

chore: cherry pick #6821 and bump version to v0.12.2

---

src/meta-srv/src/service/admin.rs
src/meta-srv/src/service/admin/health.rs
src/meta-srv/src/service/admin/heartbeat.rs
src/meta-srv/src/service/admin/leader.rs
src/meta-srv/src/service/admin/maintenance.rs
src/meta-srv/src/service/admin/node_lease.rs
src/meta-srv/src/service/admin/procedure.rs
src/meta-srv/src/service/admin/recovery.rs
src/meta-srv/src/service/admin/sequencer.rs
src/meta-srv/src/service/admin/util.rs

This PR refactors the admin service implementation by migrating from the legacy HTTP handler pattern to native Axum handlers.

refactor(meta): refactor admin service to use modern axum handlers

---

docs/rfcs/2025-08-16-async-index-build.md

https://github.com/GreptimeTeam/greptimedb/issues/6756
As titile. :mouse: [Rendered](https://github.com/SNC123/greptimedb/blob/rfc/async_index_build/docs/rfcs/2025-08-16-async-index-build.md)

docs(rfc): async index build

---

docker/dev-builder/android/Dockerfile

ci: install ssh for Android dev-builder

---

src/datatypes/src/vectors/dictionary.rs
src/datatypes/src/vectors/helper.rs

- https://github.com/GreptimeTeam/greptimedb/issues/6078
This PR supports all dictionary key types in arrow for the `DictionaryVector`. Then we can use `Helper::try_into_vector` to convert more `DictionaryArrays`.

feat: Support more key types for the DictionaryVector

---

Cargo.lock
src/common/function/src/scalars/math/clamp.rs
src/common/function/src/scalars/udf.rs
src/common/query/src/columnar_value.rs
src/datatypes/src/vectors/helper.rs
src/flow/src/batching_mode/task.rs
src/flow/src/batching_mode/utils.rs
src/flow/src/df_optimizer.rs
src/flow/src/test_utils.rs
src/flow/src/transform.rs
src/operator/src/error.rs
src/operator/src/statement/admin.rs
src/query/src/datafusion.rs
src/session/Cargo.toml
src/session/src/context.rs
tests/cases/standalone/common/function/arithmetic.result
tests/cases/standalone/common/promql/scalar.result

#6749 
Refactor query configuration options by introducing a centralized method to create DataFusion ConfigOptions from the QueryContext, ensuring consistent timezone configuration across the system.

refactor: query config options

---

src/mito-codec/benches/bench_sparse_encoding.rs
src/mito-codec/src/row_converter/sparse.rs
src/servers/src/repeated_field.rs

chore: change encode raw values signature

---

src/mito2/src/region/version.rs

chore: fix typo

---

Cargo.lock
Cargo.toml

chore: bump main branch version to 0.18

---

src/flow/src/batching_mode/engine.rs
src/flow/src/batching_mode/state.rs
src/flow/src/batching_mode/task.rs
src/flow/src/batching_mode/utils.rs

chore: pick #6880

---

config/config.md
config/metasrv.example.toml
src/meta-srv/src/handler/persist_stats_handler.rs
src/meta-srv/src/lib.rs
src/meta-srv/src/metasrv.rs

chore: pick #6900

---

src/mito2/src/access_layer.rs
src/mito2/src/cache/write_cache.rs
src/mito2/src/compaction/compactor.rs
src/mito2/src/flush.rs
src/mito2/src/metrics.rs
src/mito2/src/sst/parquet.rs
src/mito2/src/sst/parquet/writer.rs

Pick #6630 to help debug flush costs.

chore: pick #6630 to 0.15

---

src/mito2/src/sst/index/intermediate.rs

fix: clean intm ignore notfound

---

src/common/function/src/scalars/date/date_add.rs
src/common/function/src/scalars/date/date_sub.rs
src/common/function/src/scalars/geo/geohash.rs
src/common/function/src/scalars/geo/h3.rs
src/common/function/src/scalars/geo/helpers.rs
src/common/function/src/scalars/matches.rs
src/common/function/src/scalars/math.rs
src/common/function/src/scalars/math/clamp.rs
src/common/function/src/scalars/vector.rs
src/common/function/src/scalars/vector/convert/vector_to_string.rs
src/common/function/src/scalars/vector/distance.rs
src/common/function/src/scalars/vector/elem_product.rs
src/common/function/src/scalars/vector/elem_sum.rs
src/common/function/src/scalars/vector/impl_conv.rs
src/common/function/src/scalars/vector/scalar_add.rs
src/common/function/src/scalars/vector/scalar_mul.rs
src/common/function/src/scalars/vector/vector_add.rs
src/common/function/src/scalars/vector/vector_dim.rs
src/common/function/src/scalars/vector/vector_div.rs
src/common/function/src/scalars/vector/vector_kth_elem.rs
src/common/function/src/scalars/vector/vector_mul.rs
src/common/function/src/scalars/vector/vector_norm.rs
src/common/function/src/scalars/vector/vector_sub.rs
src/common/function/src/scalars/vector/vector_subvector.rs
src/query/src/tests/vec_product_test.rs
src/query/src/tests/vec_sum_test.rs
tests/cases/standalone/common/function/arithmetic.result
tests/cases/standalone/common/function/geo.result
tests/cases/standalone/common/promql/scalar.result
tests/cases/standalone/common/types/vector/vector.result

refactor: rewrite some UDFs to DataFusion style (part 2)

---

src/meta-srv/src/procedure/wal_prune/manager.rs

chore: improve error logging in WAL prune manager

---

src/frontend/src/instance.rs
src/frontend/src/instance/builder.rs
src/operator/src/error.rs
src/operator/src/statement.rs
src/operator/src/statement/show.rs
src/sql/src/parsers/show_parser.rs
src/sql/src/parsers/show_parser/trigger.rs
src/sql/src/statements/show/trigger.rs
src/sql/src/statements/statement.rs

This pr mainly support sql parse about `SHOW CREATE TRIGGER`. 
The syntax is as follows:
```
SHOW CREATE TRIGGER <trigger-name>
```

feat: sql parse about show create trigger 

---

src/common/function/src/helper.rs
src/common/function/src/scalars/date/date_format.rs
src/common/function/src/scalars/json/json_get.rs
src/common/function/src/scalars/json/json_is.rs
src/common/function/src/scalars/json/json_path_exists.rs
src/common/function/src/scalars/json/json_path_match.rs
src/common/function/src/scalars/json/json_to_string.rs
src/common/function/src/scalars/json/parse_json.rs
src/common/function/src/scalars/matches_term.rs
src/common/function/src/scalars/math/rate.rs
src/common/function/src/scalars/timestamp/to_unixtime.rs
src/common/function/src/scalars/vector/convert/parse_vector.rs
src/common/function/src/scalars/vector/convert/vector_to_string.rs
src/common/function/src/scalars/vector/distance.rs
src/common/function/src/scalars/vector/elem_product.rs
src/common/function/src/scalars/vector/elem_sum.rs
src/common/function/src/scalars/vector/impl_conv.rs
src/common/function/src/scalars/vector/scalar_add.rs
src/common/function/src/scalars/vector/scalar_mul.rs
src/common/function/src/scalars/vector/vector_add.rs
src/common/function/src/scalars/vector/vector_div.rs
src/common/function/src/scalars/vector/vector_mul.rs
src/common/function/src/scalars/vector/vector_norm.rs
src/common/function/src/scalars/vector/vector_sub.rs
src/common/function/src/system/pg_catalog/version.rs
src/common/query/src/error.rs
src/query/src/datafusion.rs
tests/cases/standalone/common/types/json/json.result

refactor: rewrite some UDFs to DataFusion style (final part)

---

Cargo.lock
src/cmd/src/frontend.rs
src/common/mem-prof/Cargo.toml
src/sql/src/statements/create/trigger.rs
tests/runner/src/main.rs

1. improve the display of create trigger for clarity.
2. cargo update -p tempfile
3. cargo update -p mappings

chore: improve create trigger display

---

src/cli/src/metadata/control/get.rs
src/cli/src/metadata/control/utils.rs
src/common/function/src/aggrs/aggr_wrapper.rs
src/common/telemetry/src/tracing_context.rs
src/flow/src/plan/join.rs
src/meta-client/src/client.rs
src/meta-srv/src/election/rds/mysql.rs
src/meta-srv/src/election/rds/postgres.rs
src/mito2/src/manifest/manager.rs
src/promql/src/extension_plan/scalar_calculate.rs
src/query/src/dist_plan/planner.rs
src/servers/src/http/event.rs
src/sql/src/statements/truncate.rs
tests-integration/tests/http.rs

Fixes typos blocking #7033 's CI. 
It also includes a fix in API output data, the downstream update is here: https://github.com/GreptimeTeam/dashboard/pull/577

fix: various typos reported by CI

---

Cargo.lock
src/servers/Cargo.toml
src/servers/src/postgres/fixtures.rs
src/servers/src/postgres/handler.rs

feat: pgwire 0.33 update
