GreptimeTeam/greptimedb

.github/pull_request_template.md
- `task list` syntax in markdown has a leading dash
#523
=> fix: `task list` syntax error in pull_request_template

src/object-store/tests/object_store_test.rs, src/query/src/expr.rs
We are using repository secrets to store object storage credentials. However fork repository does not have access to these secrets. This is causing tests failure for contributors. This patch ignored empty config and skip these tests.
Expected to resolve failures in #524
=> test: ignore empty s3 bucket config and fix tests from forked repo

README.md
Changes in README.md:
- Move the Documents Section under Resources. Hope it makes the structure clearer
=> docs: move Docs section under Resources

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Remove title prefix (like `[Enhancement]` or `[Bug]`) as they are included in lables.
=> chore: remote issue title prefix from template

src/api/greptime/v1/database.proto
This pr fix the field number of **InsertExpr** proto.
=> fix: field number of InsertExpr proto

.github/workflows/coverage.yml
Remove the job "clean disk", it takes lots of time and we now have enough space to build.
=> chore: remove clean disk job

src/cmd/src/datanode.rs, src/datanode/src/datanode.rs, src/datanode/src/error.rs, src/datanode/src/instance.rs, src/datanode/src/mock.rs, src/frontend/src/table.rs
When datanode starts, it reads metasrv addr and node id from command line args to determine running mode, but it does not respect config in config files. This PR is to fix this by:
First read all options from config file,  override node id/metasrv addr with command line args if present. After all opts are set, checks if options are valid, 
- if mode is standalone, node id can be left absent.
- if mode is distribitede, node id must be present.
metasrv is no longer mandatory, since it has a default value.
Fixes #537
=> fix: respect node id and metasrv addr in config file

README.md
Split the  SQL and its output in README. So the user can copy the SQL and run it directly.
=> fix: split code and output in README

src/catalog/src/error.rs, src/catalog/src/remote/manager.rs, src/common/catalog/src/helper.rs, src/frontend/src/catalog.rs, src/frontend/src/instance/distributed.rs, src/frontend/src/table.rs, src/meta-srv/src/service/router.rs
close #536
Implement `table_info()` for `DistTable`. Originally `unimplemented!()`.
Store `TableInfo` in `TableGlobalValue`, which is later stored in Meta for retrieval.
#536
=> feat: Implement `table_info()` for `DistTable` (#536)

src/api/greptime/v1/admin.proto, src/datanode/src/server/grpc/ddl.rs, src/datanode/src/sql/alter.rs, src/datanode/src/tests/instance_test.rs, src/mito/src/engine.rs, src/mito/src/table.rs, src/sql/src/parsers/alter_parser.rs, src/sql/src/statements/alter.rs, src/table/src/metadata.rs, src/table/src/requests.rs
Try to fix #466, which supports `alter table drop column [name]`:
```sh
mysql> create table test(host STRING, ts timestamp, time index(ts));
Query OK, 1 row affected (0.03 sec)
mysql> insert into test values('a', 1);
Query OK, 1 row affected (0.03 sec)
mysql> insert into test values('b', 2);
Query OK, 1 row affected (0.04 sec)
mysql> select * from test;
+------+---------------------+
| host | ts                  |
+------+---------------------+
| a    | 1970-01-01 00:00:00 |
| b    | 1970-01-01 00:00:00 |
+------+---------------------+
2 rows in set (0.01 sec)
mysql> alter table test drop column host;
Query OK, 0 rows affected (0.03 sec)
mysql> select * from test; …
```
=> feat: drop column for alter table

.github/workflows/release.yml
Add GitHub nightly build. The GitHub Action will be scheduled at 00:00 everyday to build the `develop` branch and release artifacts for using tag `0.1.0-alpha-<YYYYMMDD>-nightly`.
Modify the `release.yaml`:
- Add GitHub Action cron;
- Using the different formats of the tag for different trigger event('scheduled' or normal release);
=> ci: add nightly build job

Cargo.lock, src/catalog/Cargo.toml, src/object-store/Cargo.toml, src/object-store/src/backend/azblob.rs, src/object-store/src/backend/fs.rs, src/object-store/src/backend/memory.rs, src/object-store/src/backend/s3.rs, src/object-store/src/lib.rs, src/object-store/src/util.rs, src/object-store/tests/object_store_test.rs, src/storage/src/manifest/storage.rs
Signed-off-by: Xuanwo <github@xuanwo.io>
Bump OpenDAL to v0.20 for bug fixes and new features.
Read [CHANGELOG](https://github.com/datafuselabs/opendal/blob/main/CHANGELOG.md) for more details.
=> chore: Bump OpenDAL to v0.20

README.md
State the `protoc` version requirement in README.
Refer to #563
=> docs: specify protoc version requirement

config/datanode.example.toml, config/standalone.example.toml, src/cmd/src/datanode.rs, src/cmd/src/standalone.rs, src/datanode/src/datanode.rs
Signed-off-by: azhmesoso zzhncut123@163.com
Right now the datanode listens on 127.0.0.1:3306 for MySQL connections, it may conflict with the user's MySQL server, so I should change this default address to 127.0.0.1:4406.
updata mysql default listen port to 4406.
=> feat: update mysql default listen port to 4406

Cargo.lock, src/datanode/src/instance/sql.rs, src/datanode/src/sql.rs, src/datatypes/src/schema/constraint.rs, src/datatypes/src/value.rs, src/frontend/src/instance.rs, src/frontend/src/instance/distributed.rs, src/query/Cargo.toml, src/query/src/datafusion/planner.rs, src/query/src/error.rs, src/query/src/sql.rs, src/sql/src/parser.rs, src/sql/src/statements.rs, src/sql/src/statements/describe.rs, src/sql/src/statements/statement.rs
Support DESC[RIBE] TABLE sql clause. Returns following info about table columns: name, type, nullable, default, semantic type.
Not sure about `Display for Value` implementation. Perhaps it should be more sql-ish
Resolves #534
=> feat: implement DESCRIBE TABLE

.github/workflows/release.yml
- Remove GitHub Container Registry;
It's no need to maintain multiple container registry with different image name; 
- Add UCloud Container Registry;
For better network performance.
=> ci: modify image registry in `release.yml`

src/sql/src/statements.rs
Fix bug https://github.com/GreptimeTeam/greptimedb/issues/364
Make nullable as default when alter table.
Make nullable as default when alter table
=> fix: make nullable as default when alter table

config/standalone.example.toml, src/cmd/src/standalone.rs
Remove `datanode_mysql_addr`/`datanode_mysql_runtime_size` from `StandaloneOptions`.
NA
=> fix: remove datanode mysql options in standalone mode

src/common/base/src/bit_vec.rs, src/common/base/src/lib.rs, src/datatypes/src/vectors/boolean.rs, src/datatypes/src/vectors/operations.rs, src/datatypes/src/vectors/operations/find_unique.rs, src/storage/src/read.rs, src/storage/src/read/dedup.rs, src/storage/src/schema/projected.rs
This PR replaces some usage of MutableBitmap by `BitVec`:
- `VectorOp::find_unique()`
- `BatchOp::find_unique()`
- `DedupReader` now buffers the `BitVec` and resets it before each iteration.
As the official arrow doesn't have a mutable bitmap struct, this PR could help reduce some migration work.
Note that the `ListVectorBuilder` still requires `MutableBitmap`.
- #555
=> refactor: replace some usage of MutableBitmap by BitVec

.gitignore, src/datanode/src/instance.rs, src/datanode/src/instance/sql.rs, src/datanode/src/mock.rs, src/datanode/src/sql.rs, src/datanode/src/sql/create.rs, src/datanode/src/tests/test_util.rs, src/frontend/src/instance.rs, src/frontend/src/instance/distributed.rs, src/query/src/datafusion/planner.rs, src/query/src/sql.rs, src/sql/src/parser.rs, src/sql/src/statements.rs, src/sql/src/statements/explain.rs, src/sql/src/statements/statement.rs
Support explain syntax like this:
```SQL
explain select * from foo
```
Closes #531
=> feat: support `explain` syntax

Cargo.lock, src/datanode/Cargo.toml, src/datanode/src/instance.rs, src/object-store/Cargo.toml
Adds more layers to opendal object-store:
* `MetricsLayer` and `TracingLayer` for better observability
* `RetryLayer` with exponential backoff strategy, prepares for s3 storage testing.
=> feat: adds metrics, tracing and retry layer to object-store

config/datanode.example.toml, config/standalone.example.toml, src/catalog/src/error.rs, src/catalog/src/lib.rs, src/catalog/src/local/manager.rs, src/catalog/src/local/memory.rs, src/catalog/src/remote/manager.rs, src/catalog/tests/remote_catalog_tests.rs, src/cmd/src/standalone.rs, src/datanode/src/datanode.rs, src/datanode/src/instance.rs, src/frontend/src/catalog.rs
- **API change** Add `memory_catalog_enable` option to `standalone start` command
- Add new method `deregister_table` to trait `CatalogManager`
- Implement `deregister_table` for `MemoryCatalogManager`
Part of #497, also related to #614
=> feat: deregister table for MemoryCatalogManager

.github/workflows/release.yml
Based on the current development speed, **the PR will modify the nightly release to a weekly release**.
Moreover, the PR refine the naming of some variables without the hard-coded period message:
- `NIGHTLY_BUILD_VERSION_PREFIX` -> `SCHEDULED_BUILD_VERSION_PREFIX`;
-  Add `SCHEDULED_PERIOD`(set `weekly` now);
=> ci: change scheduled release from nigthly to weekly

Cargo.lock, config/frontend.example.toml, config/standalone.example.toml, src/cmd/src/frontend.rs, src/cmd/src/standalone.rs, src/datanode/src/tests/http_test.rs, src/frontend/src/frontend.rs, src/frontend/src/server.rs, src/servers/Cargo.toml, src/servers/src/http.rs, src/servers/tests/http/influxdb_test.rs, src/servers/tests/http/opentsdb_test.rs, src/servers/tests/http/prometheus_test.rs
- Use toml configured timeout instead of hard code
- Add one more timeout together with http_addr to build a HttpOptions struct
(#463)
=> chore: able to config axum timeout in toml

src/catalog/Cargo.toml, src/catalog/src/error.rs, src/catalog/src/lib.rs, src/catalog/src/local/manager.rs, src/catalog/src/local/memory.rs, src/catalog/src/remote/manager.rs, src/catalog/tests/local_catalog_tests.rs, src/common/catalog/src/helper.rs, src/datanode/src/sql/create.rs, src/frontend/src/catalog.rs, src/frontend/src/error.rs, src/frontend/src/instance/distributed.rs, src/meta-srv/src/service/router.rs, src/table/src/table/numbers.rs
Implement concurrency control for catalog manager.
- In local catalog manager, check if registering table's id is the same with existing table, and return an error if not. The check is guarded by a mutex to prevent concurrent register.
- In remote catalog manager, use kvbackend's compare and set API to prevent registering tables with  same name but different id.
Fixes #617
=> fix: add concurrency control for catalog manager

src/cmd/src/standalone.rs, src/datanode/src/datanode.rs
- Break datanode startup process into "start components" and "start services"
- When running in standalone mode, start datanode components before frontend services, to avoid receiving request under a initializing state,
=> fix: start datanode instance before frontend services

Cargo.lock, src/catalog/Cargo.toml, src/catalog/src/system.rs, src/datanode/src/error.rs, src/object-store/Cargo.toml, src/object-store/src/lib.rs, src/object-store/src/util.rs, src/object-store/tests/object_store_test.rs, src/storage/src/error.rs, src/storage/src/manifest/storage.rs, src/storage/src/sst/parquet.rs
Signed-off-by: Xuanwo <github@xuanwo.io>
This PR will bump OpenDAL to v0.21.1.
Recent changes:
- https://github.com/datafuselabs/opendal/discussions/1004
- https://github.com/datafuselabs/opendal/discussions/1008
Please take a review on the error related changes. Thanks in advance!
=> chore: Bump OpenDAL to v0.21.1

src/mito/src/engine.rs
- append table id to table name as data directory, format like: /{schema_name}/{table_name}_{table_id}/
(#631)
=> fix: append table id to table data dir

Cargo.lock, src/catalog/Cargo.toml, src/datanode/src/instance.rs, src/object-store/tests/object_store_test.rs
Enable atomic write for file object storage. Opendal [0.21](https://github.com/datafuselabs/opendal/releases/tag/v0.21.0) has already implemented it.
Fixes #613
=> feat: enable atomic write for file object storage

Cargo.lock, src/cmd/Cargo.toml, src/cmd/build.rs, src/cmd/src/bin/greptime.rs
- Add `--version` command line option to `greptimedb` for build information.
#550
=> feat: add --version command line option

Cargo.lock, src/datatypes2/Cargo.toml, src/datatypes2/src/data_type.rs, src/datatypes2/src/macros.rs, src/datatypes2/src/scalars.rs, src/datatypes2/src/types.rs, src/datatypes2/src/types/primitive_type.rs, src/datatypes2/src/value.rs, src/datatypes2/src/vectors.rs, src/datatypes2/src/vectors/binary.rs, src/datatypes2/src/vectors/boolean.rs, src/datatypes2/src/vectors/eq.rs, src/datatypes2/src/vectors/helper.rs, src/datatypes2/src/vectors/operations.rs, src/datatypes2/src/vectors/operations/filter.rs, src/datatypes2/src/vectors/operations/find_unique.rs, src/datatypes2/src/vectors/operations/replicate.rs, src/datatypes2/src/vectors/primitive.rs
This PR implements PrimitiveType and PrimitiveVector for `datatypes2` crate.
- Renames the `Primitive` to `NativeType`, and adds the `ArrowNativeType` trait bound to it.
- Introduces `WrapperType` to represent wrappers like `Date`, `Timestamp` to allow the primitive vector returns a wrapper type.
- Replaces `PrimitiveElement` with `LogicalPrimitiveType`.
- Implements the `PrimitiveVector`, using the official arrow's `PrimitiveArray`.
- Passes more tests.
Now we can use the `LogicalPrimitiveType` to associate the arrow's `ArrowPrimitiveType` with our `NativeType` and `WrapperType`.
```rust
pub trait LogicalPrimitiveType: 'static + Sized {
/// Arrow primitive type of this …
```
=> feat: Implements PrimitiveType and PrimitiveVector for datatypes2

.github/workflows/doc-issue.yml
The change introduces a github action to respond the label: `doc update required`.
When any issue or pull request labelled, it automatically creates an issue in https://github.com/GrepTimeTeam/docs/ to track the doc change.
=> ci: add action to create doc issue when change labelled

src/script/src/python/coprocessor.rs, src/script/src/python/vector.rs
When executing a coprocessor, we always create a new python interpreter for every execution. It's unnecessary and make the execution really slow.
In this PR, we cache the interpreter in TLS, looks like it can improve the performance significantly.
Before patched:
```
$ curl  -XPOST "http://localhost:4000/v1/run-script?name=system_status"
{"code":0,"output":..., "execution_time_ms":2156}
```
After patched:
```
{"code":0,"output":...., "execution_time_ms":3}
```
And reuse the interpreter in `test_execute_script` too, it only runs about 2 seconds right now(almost 20 seconds before).
- []  I have added the necessary unit tests …
=> perf: cache python interpreter in TLS

.github/workflows/doc-issue.yml
Fixes #648 and add label action to pull requests too
=> ci: add doc label support for pr too

src/mito/src/engine.rs, tests/runner/src/env.rs, tests/runner/src/main.rs, tests/runner/src/util.rs
Improvements:
- Able to run under project root dir with `cargo run --bin sqlness-runner`
- Force to run with the newest DB build.
- Hook build output. Redirect server log to file.
- No orphan process will leave.
=> feat: UI improvement for integration test runner

Cargo.lock, Cargo.toml, src/datanode/src/lib.rs, src/datanode/src/tests.rs, src/servers/src/http.rs, tests-integration/Cargo.toml, tests-integration/src/lib.rs, tests-integration/src/test_util.rs, tests-integration/tests/grpc.rs, tests-integration/tests/http.rs
While cleanup residual code review suggestions in #474 , I just realized this `http_test` is no longer suitable to sit in `datanode` module:
- it uses an integration test methodology that calls http api directly, which is not a *unit test*
- the functionality is no longer full contained in `datanode`, it covers logic from `servers`, `datanode` to `frontend`
- it prevents us from further decoupling `datanode` and `frontend` in terms of dependency
This PR creates a dedicated tests-integration module to hold tests like `http_test`. It will depend on `datanode`, `frontend` and `meta` in future. **if this idea sounds good to you**, I'm going to move forward:
N/A
=> refactor: add tests-integration module

src/datatypes2/src/data_type.rs, src/datatypes2/src/scalars.rs, src/datatypes2/src/types.rs, src/datatypes2/src/types/date_type.rs, src/datatypes2/src/types/primitive_type.rs, src/datatypes2/src/value.rs, src/datatypes2/src/vectors.rs, src/datatypes2/src/vectors/date.rs, src/datatypes2/src/vectors/eq.rs, src/datatypes2/src/vectors/operations.rs, src/datatypes2/src/vectors/operations/filter.rs, src/datatypes2/src/vectors/operations/find_unique.rs, src/datatypes2/src/vectors/operations/replicate.rs
This PR
- implements DateType and DateVector for the `datatypes2` crate (`date_type.rs` and `vectors/date.rs`)
- enables more test cases for `Value` and `ConcreteDataType`
Now implementing `Vector` for a wrapper type is more convenient, taking `Date` as an example
- Adds `DateType`
- Implements `DataType` and `LogicalPrimitiveType` for `DateType`
- Implements `WrapperType` for `Date`
- Adds Alias for `DateVector` and `DateVectorBuilder`
- #555
=> feat: Implements DateType and DateVector

src/servers/src/mysql/server.rs, src/servers/tests/mysql/mysql_server_test.rs
Fix a bug that cause two or more mysql clients to block. Formerly I mistakenly `await` on a spawned mysql listening task (that loop endlessly). 
Also a unit test was mis-interpret, revert.
=> fix: correctly detach spawned mysql listener task

.github/workflows/doc-issue.yml
OMG this is my 3rd attempt to make this action running. 
When using `pull_request` event, the action has no access to secrets. Here we changes event type to `pull_request_target` and action runs against original repo.
=> ci: fix doc label task on forked repo

.github/workflows/doc-issue.yml
4th attempt, we cannot specify assignee because it's not allowed.
=> ci: remove assignees which is causing error

src/storage/src/error.rs
The previous sequence in the error message should be greater than or equal to next sequence.
NA
=> chore: fix SequenceNotMonotonic error message

src/datatypes2/src/data_type.rs, src/datatypes2/src/scalars.rs, src/datatypes2/src/types.rs, src/datatypes2/src/types/datetime_type.rs, src/datatypes2/src/types/primitive_type.rs, src/datatypes2/src/vectors.rs, src/datatypes2/src/vectors/date.rs, src/datatypes2/src/vectors/datetime.rs, src/datatypes2/src/vectors/eq.rs, src/datatypes2/src/vectors/helper.rs, src/datatypes2/src/vectors/operations/filter.rs, src/datatypes2/src/vectors/operations/find_unique.rs, src/datatypes2/src/vectors/operations/replicate.rs, src/datatypes2/src/vectors/primitive.rs
- Implement types and vector for `DateTimeVector`.
- Add `Into<serde_json::Value>` trait bound to `WrapperType` to enable customized serialization of wrapper type.
- Add more tests for DateTime and serialization.
=> feat: datatypes2 datetime

src/datatypes2/src/data_type.rs, src/datatypes2/src/types.rs, src/datatypes2/src/types/null_type.rs, src/datatypes2/src/vectors.rs, src/datatypes2/src/vectors/eq.rs, src/datatypes2/src/vectors/null.rs, src/datatypes2/src/vectors/operations.rs, src/datatypes2/src/vectors/operations/filter.rs, src/datatypes2/src/vectors/operations/find_unique.rs, src/datatypes2/src/vectors/operations/replicate.rs
This PR implements NullType and NullVector for the datatypes2 crate.
- #555
=> feat: Implements NullType and NullVector

Cargo.lock, src/datanode/Cargo.toml, src/servers/Cargo.toml, src/servers/src/http.rs, tests-integration/Cargo.toml
- bump axum 0.6 from rc; refactor the way to nest routes and with_state
- ref: https://docs.rs/axum/0.6.1/axum/routing/struct.Router.html#method.with_state
(#642)
=> refactor: bump axum 0.6, use recommended way to nest routes

.github/workflows/coverage.yml
There are some S3-related unit tests that need our secret to run. But the secret is not reachable in a forked repo. I find this [article](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks) from github's blog which says change `pull_request` to `pull_request_target` can solve this problem:
>In order to solve this, we’ve added a new pull_request_target event, which behaves in an almost identical way to the pull_request event with the same set of filters and payload. However, instead of running against the workflow and code from the merge …
=> ci: change CI unit test trigger

README.md
A roadmap link in the README file is helpful for contributors to know about the upcoming plans of GreptimeDB.
=> docs: add a roadmap link in README

src/servers/src/http.rs, src/servers/src/http/handler.rs, src/servers/tests/http/http_handler_test.rs, tests-integration/tests/http.rs
Add `/health` http api for healthy check purpose.
Users are able to visit the api using either `GET` or `POST` methods. Both of them return same response.
The response of this api currently is simply an empty json `{}` with `200 OK` http status code.
[#636 ](https://github.com/GreptimeTeam/greptimedb/issues/636)
=> feat: add http `/health` api

src/servers/src/postgres/handler.rs, src/servers/tests/postgres/mod.rs
This patch add postgresql support for new `QueryContext` api in #672
=> feat: inject current database/schema into query context for postgres protocol

.pre-commit-config.yaml, Cargo.toml, src/api/Cargo.toml, src/catalog/Cargo.toml, src/client/Cargo.toml, src/cmd/Cargo.toml, src/common/function/Cargo.toml, src/common/grpc-expr/Cargo.toml, src/common/grpc/Cargo.toml, src/datanode/Cargo.toml, src/frontend/Cargo.toml, src/object-store/Cargo.toml, src/script/Cargo.toml, src/servers/Cargo.toml, src/sql/Cargo.toml
1. remove `--print` param of cargo sort in `.pre-commit-config.yaml` file
2. rerun pre-commit to sort all `Cargo.toml` files
=> fix: cargo sort in pre-commit

Cargo.lock, src/servers/Cargo.toml
As mysql_async updated, we are switching back to upstream version.
=> refactor: use updated mysql_async client

src/datatypes2/src/data_type.rs, src/datatypes2/src/lib.rs, src/datatypes2/src/schema.rs, src/datatypes2/src/schema/column_schema.rs, src/datatypes2/src/schema/constraint.rs, src/datatypes2/src/schema/raw.rs, src/datatypes2/src/types/binary_type.rs, src/datatypes2/src/types/boolean_type.rs, src/datatypes2/src/types/date_type.rs, src/datatypes2/src/types/datetime_type.rs, src/datatypes2/src/types/list_type.rs, src/datatypes2/src/types/null_type.rs, src/datatypes2/src/types/primitive_type.rs, src/datatypes2/src/types/string_type.rs, src/datatypes2/src/types/timestamp_type.rs
This PR implements schema mod for `datatypes2` crate.
- Ports `Schema`, `ColumnSchema` and `RawSchema` from `datatypes`
- Adds the `is_timestamp_compatible()` method to the `DataType` trait.
- #555
=> feat: Implements schema for datatypes2

src/common/recordbatch/src/recordbatch.rs, src/datatypes2/src/arrow_array.rs, src/datatypes2/src/data_type.rs, src/datatypes2/src/scalars.rs, src/datatypes2/src/timestamp.rs, src/datatypes2/src/type_id.rs, src/datatypes2/src/value.rs, src/datatypes2/src/vectors.rs, src/datatypes2/src/vectors/eq.rs, src/datatypes2/src/vectors/helper.rs, src/datatypes2/src/vectors/list.rs, src/datatypes2/src/vectors/operations.rs, src/datatypes2/src/vectors/operations/filter.rs, src/datatypes2/src/vectors/operations/replicate.rs
Implements helper methods for vectors/values, including
- `is_xxx()` in ConcreteDataType
- `arrow_array_get()`
- `LogicalTypeId::data_type()`
- `TryFrom<ScalarValue> for Value`
- methods in `Helper`
Also passes all test cases
- #555
=> feat: Implements helper methods for vectors/values

src/servers/tests/mysql/mysql_server_test.rs
fix test case `tls handshake eof` bug
increase tokio test worker thread number
https://github.com/GreptimeTeam/greptimedb/issues/677
=> fix: test_server_require_secure_client_secure

Cargo.lock, src/script/Cargo.toml, src/script/src/python/builtins/test.rs, src/script/src/python/coprocessor.rs, src/script/src/python/coprocessor/compile.rs, src/script/src/python/coprocessor/parse.rs, src/script/src/python/error.rs, src/script/src/python/test.rs, src/script/src/python/testcases.ron, src/script/src/python/vector.rs
Update RustPython to a newer fork, so it doesn't block other depends from update, currently commit of RustPython require `crossbeam-utils` of `=0.8.9`, relaxed it to `0.8.9` using my forked and tweaked version of RustPython(https://github.com/discord9/RustPython branch:rspy4gpdb this branch is basically a rebase of this PR(https://github.com/RustPython/RustPython/pull/4293) to a pre 1.65 version of rustpython), so we can update it to newer version (and main branch) later when we update to rust 1.65.
=> chore: update RustPython dependence(With a tweaked fork)

src/common/query/src/error.rs, src/common/query/src/logical_plan.rs, src/common/query/src/logical_plan/udaf.rs, src/common/query/src/physical_plan.rs, src/common/recordbatch/src/util.rs
Fixes errors in `common-query` except those around "accumulator".
- remove one usage of `AsyncRecordBatchAdapter`
- other minors
Ref to #555
=> fix: common-query subcrate

Cargo.lock, src/cmd/src/error.rs, src/cmd/src/frontend.rs, src/cmd/src/standalone.rs, src/common/grpc/src/select.rs, src/common/recordbatch/src/lib.rs, src/datanode/Cargo.toml, src/frontend/Cargo.toml, src/frontend/src/catalog.rs, src/frontend/src/error.rs, src/frontend/src/frontend.rs, src/frontend/src/instance.rs, src/frontend/src/instance/distributed.rs, src/frontend/src/instance/opentsdb.rs, src/frontend/src/instance/prometheus.rs, src/frontend/src/table.rs, src/frontend/src/tests.rs, src/script/src/python/builtins/mod.rs, src/script/src/python/builtins/test.rs, src/script/src/python/test.rs, src/script/src/python/vector.rs, src/session/src/context.rs, tests-integration/src/test_util.rs, tests-integration/tests/grpc.rs
This PR removes the GRPC invocations between frontend and datanode in standalone mode.
In standalone mode, frontend is started with datanode instance, proxy most of the request to datanode instance, via the "QueryHandler" traits.
> "most" is not included the insertion, which has some "table creation upon insertion" mechanism, needs some special care.
`DistInstance` has implemented the "QueryHandler" traits, for the unification of some code logic.
Also note that some GRPC related codes are not updated as well, because we are facing the fundamental rewrite of whole GRPC framework, and the related codes will be rewritten from there.
#682 
close #584
=> refactor: directly invoke Datanode methods in standalone mode (part 1)

src/cmd/build.rs, src/cmd/src/bin/greptime.rs
Signed-off-by: Zheming Li <nkdudu@126.com>
Discussed in https://github.com/GreptimeTeam/greptimedb/pull/632#issuecomment-1335171406
- use default value `unknown` for git info when fail to get to avoid panic in `build.rs`.
- add `CARGO_PKG_VERSION` in `-V` output.
=> fix: set default value when fail to get git info instead of panic

Cargo.lock, src/datanode/src/instance.rs, src/datatypes2/Cargo.toml, src/object-store/Cargo.toml, src/script/Cargo.toml
Bump opendal to 0.22, refer to https://github.com/datafuselabs/opendal/releases
We want to improve temp file organization when enabling atomic write in the file backend.
=> feat: bump opendal version to 0.22

src/common/grpc-expr/src/insert.rs, src/datatypes/src/vectors.rs, src/frontend/src/instance.rs, src/servers/src/http.rs, src/servers/src/http/influxdb.rs, src/servers/src/influxdb.rs, src/servers/src/line_writer.rs, src/servers/src/opentsdb/codec.rs, src/servers/src/prometheus.rs, src/storage/src/sst/parquet.rs, tests-integration/tests/grpc.rs, tests/runner/src/util.rs
Fix compile errors in `servers`.
Those errors in `#[test]` are not fixed because it depends on `table`. And clippy warnings are the same.
=> fix: Fix compile error in server subcrate

src/mito/src/engine.rs
using table id as the table data path to support RENAME TABLE, the relevant logic has already been validated in the unit test `test_open_table`.
more details in #660
=> refactor(mito): change the table path to `schema/table_id`

src/catalog/src/system.rs, src/common/grpc-expr/src/insert.rs, src/common/time/src/date.rs, src/common/time/src/timestamp.rs, src/common/time/src/util.rs, src/datanode/src/sql.rs, src/datatypes/src/value.rs, src/script/src/python/vector.rs, src/script/src/table.rs, src/servers/src/line_writer.rs, src/storage/benches/memtable/mod.rs, src/storage/src/memtable/inserter.rs
- fix errors in `common-grpc-expr`
- rename `Timestamp` constructors
- fix warnings in `common-time`
=> fix: Fix common grpc expr

Makefile
Add Makefile to aggregate the commands that developers always use.
Run `make help`, it will output the following targets:
```console
$ make help
Usage:
make <target>
Build
build                 Build debug version greptime.
release               Build release version greptime.
fmt                   Format all the rust code.
docker-image          Build Docker image.
Test
integration-test      Run integation test.
check                 Cargo check all the targets.
clippy                Check Clippy rules.
fmt-check             Check code format.
General
help                  Display help messages.
```
=> feat: add Makefile to aggregate the commands that developers always use

src/cmd/src/standalone.rs, src/datanode/src/mock.rs, src/datanode/src/tests/instance_test.rs, src/frontend/src/instance.rs, src/frontend/src/instance/opentsdb.rs, src/frontend/src/instance/prometheus.rs, src/frontend/src/tests.rs, src/servers/src/postgres/server.rs, tests-integration/src/test_util.rs
minor refactor of repaying 2 todos, and others
- get `CatalogManager` from the instance on constructing, rather than set it later
- move mock constructor to test utils
=> refactor(frontend): minor changes around `FrontendInstance` constructor 

src/storage/src/write_batch.rs, src/storage/src/write_batch/codec.rs
This PR refactors the write_batch mod
- moves the `write_batch::codec` mod and its tests to a separate file without changing the logic.
- makes some test functions private.
=> refactor(storage): Move write_batch::codec to a separate file

benchmarks/src/bin/nyc-taxi.rs, src/api/greptime/v1/admin.proto, src/api/greptime/v1/column.proto, src/api/src/v1/column_def.rs, src/client/examples/logical.rs, src/client/src/admin.rs, src/common/grpc-expr/src/alter.rs, src/common/grpc-expr/src/insert.rs, src/datanode/src/instance/grpc.rs, src/datanode/src/server/grpc.rs, src/frontend/src/expr_factory.rs, src/frontend/src/instance.rs, src/frontend/src/instance/distributed.rs, src/sql/src/statements.rs, src/sql/src/statements/alter.rs, tests-integration/tests/grpc.rs
Remove `optional` from protos, because the `optional` relies on a higher version of proto (supported in 3.15.0), which often causes some problems for users, e.g. (#616 #737 ), and I think we can avoid using this feature.
#616 #737
=> refactor: remove optional from the protos

src/common/recordbatch/src/adapter.rs, src/common/recordbatch/src/error.rs, src/common/recordbatch/src/lib.rs
`test_dist_table_scan` could be blocking for multiple reasons:
1.  the tasks that were producing the RecordBatch result items ignored the sending error
-  `test_dist_table_scan` uses `CoalescePartitionsExec` to merge partitions data
-  `CoalescePartitionsExec` will spawn multiple tasks that each of which gathers one partition's RecordBatch result to a final output stream, through a mpsc channel
- the task ignores the sending error, thus even if the receiver has decided to quit, the sender(the task) don't care (fixed in this PR: https://github.com/apache/arrow-datafusion/pull/3276/files)
- the task thus keeps polling the stream, in a `while let Some` loop
2. the stream being …
=> fix: `test_dist_table_scan` block

tests/runner/src/env.rs, tests/runner/src/util.rs
The previous patch #763 doesn't consider the behavior of `null_mask`'s iterator, especially with the tailing `0` bits. This fix adds a function call to set its length.
=> fix: fill NULL based on row_count

src/servers/src/auth.rs, src/servers/src/auth/user_provider.rs
This pr removes `#[cfg(test)]` on `UserInfo::new` so that the constructor can be called outside the original crate.
=> chore: open userinfo constructor

src/meta-srv/src/election.rs, src/meta-srv/src/lib.rs
This pr mainly make `election mod` publlic.
=> chore: make election mod public

src/servers/src/mysql/handler.rs, src/sql/src/parser.rs
Since we've upgrade to newer version of sqlparser, we can use the "USE" keyword. Eliminate a TODO.
=> refactor: use "USE" keyword

src/cmd/src/frontend.rs, src/cmd/src/standalone.rs, src/frontend/src/frontend.rs, src/frontend/src/instance.rs, src/frontend/src/lib.rs, src/servers/Cargo.toml, src/servers/src/interceptor.rs, src/servers/src/lib.rs, src/servers/tests/interceptor.rs, src/servers/tests/mod.rs
This patch is to further enhance the foundation for our cloud service.
1. Make `plugins` available to frontend `Instance`, which can be accessed from various handler
2. Add a `SqlQueryInterceptor` to customize query handler behaviour on cloud
=> feat: sql query interceptor and plugin refactoring

Cargo.lock, src/sql/Cargo.toml, src/sql/src/statements.rs
Support `varbinary` for table creation  and record insertion
https://github.com/GreptimeTeam/greptimedb/issues/709
=> feat: support varbinary

Cargo.lock, Cargo.toml, src/api/greptime/v1/database.proto, src/api/src/result.rs, src/client/src/database.rs, src/client/src/error.rs, src/common/grpc/Cargo.toml, src/common/grpc/src/error.rs, src/common/grpc/src/flight.rs, src/common/grpc/src/lib.rs, src/common/grpc/src/select.rs, src/datanode/Cargo.toml, src/datanode/src/error.rs, src/datanode/src/instance.rs, src/datanode/src/instance/flight.rs, src/datanode/src/instance/flight/stream.rs, src/datanode/src/instance/grpc.rs, src/frontend/src/error.rs, src/frontend/src/instance.rs, src/frontend/src/table.rs, src/frontend/src/table/insert.rs, src/frontend/src/table/scan.rs, tests-integration/Cargo.toml, tests-integration/tests/grpc.rs, tests/runner/src/env.rs
This PR is part of a series of changes to gradually adopt the Arrow Flight, and remove the old GRPC interface finally.
This PR implement Arrow Flight Service for Datanode instance. 
However, instead of creating a new GRPC server and listening a new port, I reuse the old GRPC server, bridge some methods (`do_get` in Arrow Flight vs `do_query` in old GRPC) and datatypes (`FlightData` in Arrow Flight vs `ObjectResult` in old GRPC). 
The actual Arrow Flight server that is started using Tonic will be done in the following PRs.
#381
=> feat: Implement Arrow Flight Service (except gRPC server) for selection

src/cmd/src/frontend.rs, src/servers/src/auth.rs, src/servers/src/auth/user_provider.rs
- minor change to `auth_mysql`: add `pub` and return `Result<(), Error>` instead of `UserInfo` directly
- add `AuthBackend: BoxedError` for general auth failed scenarios
=> feat: pub `auth_mysql` & add auth boxed err

Cargo.toml, benchmarks/Cargo.toml, src/catalog/Cargo.toml, src/client/Cargo.toml, src/cmd/Cargo.toml, src/common/base/Cargo.toml, src/common/catalog/Cargo.toml, src/common/function-macro/Cargo.toml, src/common/function/Cargo.toml, src/common/grpc-expr/Cargo.toml, src/common/query/Cargo.toml, src/common/recordbatch/Cargo.toml, src/common/runtime/Cargo.toml, src/common/substrait/Cargo.toml, src/datanode/Cargo.toml, src/datatypes/Cargo.toml, src/frontend/Cargo.toml, src/log-store/Cargo.toml, src/meta-client/Cargo.toml, src/meta-srv/Cargo.toml, src/mito/Cargo.toml, src/object-store/Cargo.toml, src/query/Cargo.toml, src/script/Cargo.toml, src/servers/Cargo.toml, src/storage/Cargo.toml, src/store-api/Cargo.toml, src/table/Cargo.toml, tests-integration/Cargo.toml, tests/runner/Cargo.toml
In https://github.com/GreptimeTeam/greptimedb/pull/782 @MichaelScofield changes arrow/parquet/datafusion into workspace dependencies. As discussed in https://github.com/GreptimeTeam/greptimedb/pull/782#issuecomment-1362816554, I count other deps we are using:
```
➜  greptimedb git:(dev) ✗ sort deps | uniq -cd | sort -nr
11 tokio v1.23.0 (*)
10 snafu v0.7.3 (*)
7 serde v1.0.151 (*)
5 futures v0.3.25 (*)
5 async-trait v0.1.60 (proc-macro) (*)
4 paste v1.0.11 (proc-macro)
4 datafusion v15.0.0 (https://github.com/apache/arrow-datafusion.git?rev=4917235a398ae20145c87d20984e6367dc1a0c1e#4917235a) (*)
3 tempdir v0.3.7 (*)
3 …
```
=> chore: util workspace deps in more places

src/api/greptime/v1/database.proto, src/client/src/database.rs, src/datanode/src/instance/flight.rs, src/datanode/src/instance/grpc.rs, src/frontend/src/instance.rs
fix: ease the restriction of the original "SelectExpr" since we used to pass SQLs other than selection in the related GRPC interface
fix https://github.com/GreptimeTeam/greptimedb/pull/770#issuecomment-1365667080
=> fix: ease the restriction of the original "SelectExpr"

Cargo.lock, src/datatypes/src/schema.rs, src/datatypes/src/schema/column_schema.rs, src/promql/Cargo.toml, src/promql/src/extension_plan.rs, src/promql/src/extension_plan/normalize.rs, src/promql/src/lib.rs
Add `SeriesNormalize` plan described in the [RFC](https://github.com/GreptimeTeam/greptimedb/blob/develop/docs/rfcs/2022-12-20-promql-in-rust/rfc.md).
It only biases the timestamp column with "offset" and sorts the input.
#596
=> feat: Prom `SeriesNormalize` plan

docker/Dockerfile, docker/ci/Dockerfile
install ca-certificates in docker image building
=> build: install ca-certificates in docker image building

Cargo.lock, src/script/Cargo.toml, src/script/src/python/coprocessor/compile.rs, src/script/src/python/vector.rs
Update RustPython dependences to newest fork with Garbage collect implemented(It passes corrsponding CI tests of RustPython https://github.com/RustPython/RustPython/pull/4180). This should prevent memory leak even when python scripts executing cause ref loop
=> chore: Update RustPython(With GC)

src/datatypes/src/vectors.rs, src/mito/src/table/test_util/mock_engine.rs, src/storage/benches/wal/util/mod.rs, src/storage/benches/wal/util/write_batch_util.rs, src/storage/src/error.rs, src/storage/src/memtable/inserter.rs, src/storage/src/memtable/tests.rs, src/storage/src/proto/wal.rs, src/storage/src/read.rs, src/storage/src/read/dedup.rs, src/storage/src/region.rs, src/storage/src/region/tests.rs, src/storage/src/region/tests/basic.rs, src/storage/src/region/tests/projection.rs, src/storage/src/schema/projected.rs, src/storage/src/schema/store.rs, src/storage/src/sst/parquet.rs, src/storage/src/test_util/write_batch_util.rs, src/storage/src/wal.rs, src/storage/src/write_batch.rs, src/storage/src/write_batch/codec.rs, src/storage/src/write_batch/compat.rs, src/store-api/src/storage/requests.rs, src/store-api/src/storage/types.rs
This PR implements deletion for the storage engine.
It adds the `delete()` method to the `WriteRequest` which allows us to delete a row by its row key.
```rust
pub trait WriteRequest: Send {
...
/// Delete rows by `keys`.
///
/// `keys` are the row keys, in columnar format, of the rows to delete.
fn delete(&mut self, keys: HashMap<String, VectorRef>) -> Result<(), Self::Error>;
}
```
The `OpType` adds a new variant for deletion
```rust
pub enum OpType {
/// Delete operation.
Delete = 0,
/// Put operation.
Put = 1,
}
```
The `WriteBatch` takes the `row_key_end` from `StoreSchema` to check whether the input of `delete()` contains all key columns.
```rust
impl WriteBatch {
pub …
```
=> feat: Implement delete for the storage engine

src/promql/src/extension_plan.rs, src/promql/src/extension_plan/instant_manipulate.rs, src/promql/src/extension_plan/instant_manipulator.rs, src/promql/src/extension_plan/normalize.rs
Implement `InstantSelector` for PromQL. This plan can align input data based on `interval` and `lookback`, to simulate the behavior of `InstantSelector` in PromQL. This plan can then be used by instant operators in PromQL like those unary or binary operators.
=> feat: impl `InstantManipulator` for PromQL extension

src/catalog/src/error.rs, src/common/error/src/ext.rs, src/datanode/src/error.rs, src/frontend/src/table.rs, src/mito/src/engine.rs, src/mito/src/error.rs, src/mito/src/table.rs, src/promql/src/error.rs, src/query/src/datafusion.rs, src/query/src/datafusion/catalog_adapter.rs, src/query/src/datafusion/error.rs, src/query/src/datafusion/planner.rs, src/query/src/error.rs, src/query/src/sql.rs, src/query/tests/query_engine_test.rs, src/script/src/python/error.rs, src/table/src/error.rs
`define_opaque_error` provides a convenient way to define opaque error type. It's useful for util shim type like `BoxedError`, but it also gets confused when applied to normal errors. It creates a way to bypass pre-defined error enumerations, and place an arbitrary source error into one type.
This might be useful when trying to expose an error type in the trait method, but it can also be done by defining a generic error type that accepts `BoxedError`, like `QueryExecution`.
=> refactor: remove macro `define_opaque_error` 

src/promql/src/extension_plan/instant_manipulate.rs
#803 doesn't update the license header. It CI was passed last year.
=> fix: update license header for instant manipulate

src/api/greptime/v1/ddl.proto, src/common/grpc-expr/src/alter.rs, src/datanode/src/sql/alter.rs, src/mito/src/engine.rs, src/mito/src/table.rs, src/sql/src/statements/alter.rs, src/table/src/metadata.rs, src/table/src/requests.rs
implement renaming table in mito table engine
#723
=> feat: implement rename table

src/servers/src/error.rs, src/servers/src/mysql/handler.rs, src/servers/tests/mysql/mysql_server_test.rs
This patch removes auto use upon mysql connection, to make it more flexible to initial session context.
=> refactor: do not call use upon mysql connection

src/cmd/src/standalone.rs, src/cmd/src/toml_loader.rs, src/datanode/src/datanode.rs, src/datanode/src/instance.rs, src/frontend/src/frontend.rs, src/meta-srv/src/metasrv.rs, tests-integration/src/test_util.rs
Main changes:
* Adds `#[serde(default)]` attribute to all config options.
* Adds `region` and `endpoint` config for s3 storage.
=> feat: endpoint and region config for s3 storage

src/catalog/src/helper.rs, src/frontend/src/error.rs, src/frontend/src/instance.rs, src/frontend/src/instance/distributed.rs, src/frontend/src/instance/distributed/flight.rs, src/frontend/src/instance/flight.rs, src/frontend/src/instance/grpc.rs, src/frontend/src/instance/opentsdb.rs, src/frontend/src/instance/prometheus.rs, src/frontend/src/sql.rs, src/frontend/src/table.rs, src/frontend/src/tests.rs
This PR is part of a series of changes to gradually adopt the Arrow Flight, and remove the old GRPC interface finally.
This PR implements Query and DDL functionality of Arrow Flight service (handles `QueryRequest` and `DdlRequest` in `do_get`) for Frontend instance.
Also add more the tests for distribute mode.
#381
=> feat: Impl Query and DDL functionality of Arrow Flight service for Frontend Instance

src/mito/src/engine.rs, src/mito/src/table.rs, src/table/src/error.rs, src/table/src/requests.rs, src/table/src/table.rs
This PR adds `delete()` method to the `Table` trait and implements it for `mito` engine.
```rust
pub struct DeleteRequest {
pub key_column_values: HashMap<String, VectorRef>,
}
#[async_trait]
pub trait Table: Send + Sync {
// ...
async fn delete(&self, _request: DeleteRequest) -> Result<usize> {
UnsupportedSnafu {
operation: "DELETE",
}
.fail()?
}
}
```
It adds the Unsupported error. The default implementation of `insert`/`alter`/`delete` returns this error instead of panic.
- This PR is based on #777 
- Parts of #755
=> feat: Implement delete for table

src/common/substrait/src/types.rs, src/frontend/src/error.rs, src/frontend/src/instance.rs, src/frontend/src/instance/influxdb.rs, src/frontend/src/instance/opentsdb.rs, src/frontend/src/instance/prometheus.rs, src/servers/src/influxdb.rs, src/servers/src/opentsdb/codec.rs, src/servers/src/prometheus.rs
This PR is part of a series of changes to gradually adopt the Arrow Flight, and remove the old GRPC interface finally.
This PR refactors how Frontend instance handles the read/write of influxdb, opentsdb and prometheus protocols. Now they all go through the GRPC interface, greatly unify and simplify the Frontend instance either in standalone or distributed mode. 
Should be ready when #827 is merged.
=> refactor: simplify how Frontend instance handles other protocols

src/datanode/src/error.rs, src/datanode/src/instance.rs, src/datanode/src/mock.rs, src/log-store/src/noop.rs, src/log-store/src/raft_engine/log_store.rs, src/log-store/src/test_util/log_store_util.rs, src/script/src/manager.rs, src/storage/src/error.rs, src/storage/src/test_util/config_util.rs, src/storage/src/wal.rs, src/store-api/src/logstore.rs
- Remove `start` from `LogStore` trait.
- Call start as soon as `RaftEngineLogStore` is instantiated.
- Fix some error message
=> fix: remove start from LogStore; fix error message

.github/workflows/release.yml, .pre-commit-config.yaml, Cargo.toml
Our weekly build is now over 200MB in size. Here I add strip and lto for weekly build.
This patch also disable `cargo-sort` until it's support for new workspace toml lands.
=> ci: add lto and strip to weekly build

Cargo.lock, src/object-store/Cargo.toml, src/object-store/src/lib.rs, src/storage/src/sst/parquet.rs
Signed-off-by: Xuanwo <github@xuanwo.io>
This PR will bump OpenDAL to the latest v0.24 version.
Changes include:
- refactor: Use dep: to make our features more clean (#1153)
- fix: ghac shall return ObjectAlreadyExists for writing the same path (#1156)
- fix: futures read_to_end will lead to performance regression (#1158)
- fix: Allow range_read to be retired (#1149)
- Add support for SAS tokens in Azure blob storage (#1124)
- feat: Add github action cache service support (#1111)
- docs: Add docs for ghac service (#1126)
- feat: Implement offset seekable reader for zero cost read (#1133)
- feat: Implement fuzz test on ObjectReader (#1140)
- chore(deps): update quick-xml …
=> feat: Bump OpenDAL to 0.24 for better seekable support

src/datanode/src/instance/sql.rs, src/datanode/src/tests/instance_test.rs, src/frontend/src/instance.rs, src/frontend/src/instance/distributed.rs, src/query/src/sql.rs, src/servers/src/http.rs, src/servers/src/http/handler.rs, src/servers/src/http/script.rs, src/servers/src/lib.rs, src/servers/src/postgres.rs, src/servers/src/postgres/auth_handler.rs, src/servers/src/postgres/handler.rs, src/servers/tests/postgres/mod.rs, src/session/src/context.rs, tests-integration/tests/http.rs
This patch resolves catalog from dbname, for postgres and http rest api, as described in #798, 
To be implemented in next patches:
- Mysql support is to be implemented in next patch because it has slightly difference with how postgres uses database context.
- influxdb
- opentsdb
- gRPC
=> feat: add catalog name resolution for postgres and http interface

src/storage/src/sst/parquet.rs
Use parquet official row group pruning instead of zipping streams with pruning predicate.
=> fix: parquet native row group pruning support

src/api/greptime/v1/meta/heartbeat.proto, src/catalog/src/lib.rs, src/datanode/src/heartbeat.rs, src/datanode/src/instance.rs, src/datanode/src/mock.rs, src/meta-srv/src/handler.rs, src/meta-srv/src/handler/node_stat.rs, src/meta-srv/src/handler/persist_stats_handler.rs, src/meta-srv/src/keys.rs, src/meta-srv/src/lib.rs
1. Datanode support report the number of regions to metasrv.
2. Meta put the number of regions to store.
=> feat: datanode support report number of regions to meta

.github/workflows/release.yml
This is a bug introduced in my previous introduction of `weekly` profile #841 . Our release script uses the output dir and with the new profile it has been changed to `weekly`.
=> ci: fix release task by correcting output dir

src/meta-srv/src/election.rs, src/meta-srv/src/election/etcd.rs, src/meta-srv/src/handler.rs, src/meta-srv/src/handler/check_leader_handler.rs, src/meta-srv/src/handler/collect_stats_handler.rs, src/meta-srv/src/handler/initialize_memory_handler.rs, src/meta-srv/src/handler/keep_lease_handler.rs, src/meta-srv/src/handler/node_stat.rs, src/meta-srv/src/handler/on_leader_start.rs, src/meta-srv/src/handler/persist_stats_handler.rs, src/meta-srv/src/handler/response_header_handler.rs, src/meta-srv/src/keys.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/service/store/etcd.rs, src/meta-srv/src/service/store/kv.rs, src/meta-srv/src/service/store/memory.rs
- Add in memory storage for meta leader, which can be used to temporarily store heartbeat data in the future. Followers and third parties can use the gRPC service to obtain the data.
- Optimize the election process to make the logs look clearer.
- Refactor some From/Into impl
=> feat: in memory storage on meta leader

Cargo.lock, config/datanode.example.toml, config/standalone.example.toml, src/cmd/src/datanode.rs, src/cmd/src/standalone.rs, src/common/base/Cargo.toml, src/common/base/src/lib.rs, src/common/base/src/readable_size.rs, src/datanode/Cargo.toml, src/datanode/src/datanode.rs, src/datanode/src/instance.rs, src/datanode/src/mock.rs, src/datanode/src/tests/test_util.rs, src/frontend/src/tests.rs, src/log-store/src/config.rs, src/log-store/src/raft_engine/log_store.rs, src/log-store/src/test_util/log_store_util.rs, tests-integration/src/test_util.rs
- Allow users to config wal parameters thru config files.
=> feat: expose wal config

src/promql/src/extension_plan.rs, src/promql/src/extension_plan/range_manipulate.rs, src/promql/src/range_array.rs
Implement `RangeManipulate" plan, which collapses range vectors for range function to calculate. Section in RFC: https://github.com/GreptimeTeam/greptimedb/blob/develop/docs/rfcs/2022-12-20-promql-in-rust/rfc.md#plan-and-expression 
#596
=> feat: implement RangeManipulate

src/common/telemetry/src/logging.rs
add custom log level support for `common_telemetry::init_default_ut_logging()`
=> chore: add custom log level support for `common_telemetry::init_default_ut_logging()`

src/storage/src/error.rs, src/storage/src/flush.rs, src/storage/src/manifest/test_utils.rs, src/storage/src/sst.rs, src/storage/src/sst/parquet.rs
First step towards support pruning SST files accroding to time range in query: extract the time ranges of SST files on flush to manifest.
#846
=> feat: record sst file time range in FileMeta

src/servers/src/http.rs, src/servers/src/http/authorize.rs
This pr mainly add path check to http auth function, to allow paths without http api version prefix like `/health` and `/metrics` can be queried without auth
=> chore: add path check to http auth

.github/workflows/release.yml
run `make unit-test integration-test sqlness-test` in the weekly test pipeline to ensure the artifact can work.
=> ci: run tests on weekly release build

src/catalog/src/error.rs, src/catalog/src/lib.rs, src/catalog/src/local/manager.rs, src/catalog/src/local/memory.rs, src/catalog/src/remote/manager.rs, src/catalog/src/schema.rs, src/catalog/src/system.rs, src/catalog/src/tables.rs, src/catalog/tests/local_catalog_tests.rs, src/datanode/src/error.rs, src/datanode/src/mock.rs, src/datanode/src/sql.rs, src/datanode/src/sql/alter.rs, src/datanode/src/tests/instance_test.rs, src/datanode/src/tests/test_util.rs, src/frontend/src/catalog.rs, src/frontend/src/instance/distributed.rs, src/frontend/src/table.rs, src/frontend/src/tests.rs, src/mito/src/engine.rs, src/mito/src/table.rs, src/query/src/datafusion/catalog_adapter.rs, src/table/src/requests.rs, src/table/src/table.rs
support renaming table in the catalog manger
#723
=> feat: support renaming table in the catalog manger

Cargo.lock, src/common/query/src/error.rs, src/script/Cargo.toml, src/script/src/manager.rs, src/script/src/python/coprocessor.rs, src/script/src/python/coprocessor/parse.rs, src/script/src/python/engine.rs, src/script/src/python/test.rs, src/script/src/python/testcases.ron, src/servers/tests/mod.rs, src/servers/tests/py_script/mod.rs
So now you can use sql query like this:
```sql
mysql> select system_status(cpu_util, memory_util, disk_util) from system_metrics;
+--------------------------------------------------------------------------------------------+
| system_status(system_metrics.cpu_util,system_metrics.memory_util,system_metrics.disk_util) |
+--------------------------------------------------------------------------------------------+
| green                                                                                      |
| yellow                                                                                     |
| red …
```
=> feat: use Python Script as UDF in SQL

src/datanode/src/error.rs, src/datanode/src/sql/insert.rs, src/datatypes/src/schema/column_schema.rs, src/frontend/src/error.rs, src/frontend/src/sql.rs, src/sql/src/error.rs, src/sql/src/statements.rs, src/sql/src/statements/insert.rs
support default value when inserting data.
- Change `Identifier` without quoted to `Placeholder` instead of `SingleQuotedString` when inserting data.
- Replace `Placeholder` with `default` and `DEFAULT` value to the default value of corresponding column if possible.
#759
=> feat: support default value when inserting data

src/servers/tests/py_script/mod.rs
Fixed compilation error after merge #839 , it's not rebased with the lastest develop branch.
=> fix: compile error in test

Cargo.lock, src/common/time/Cargo.toml, src/common/time/src/range.rs, src/common/time/src/timestamp.rs, src/servers/src/mysql/writer.rs, src/sql/src/error.rs, src/sql/src/statements.rs, src/table/Cargo.toml
- Reimplement total order for `Timestamp`
- Fix overflow and rounding issue for `Timestamp`
- Rename `TimeRange` to `GenericRange`, and add `and`/`or` methods for `GenericRange`
This is the prerequisite of #846
=> fix: impl total order for Timestamp

Cargo.lock, config/metasrv.example.toml, src/cmd/src/error.rs, src/cmd/src/metasrv.rs, src/meta-srv/Cargo.toml, src/meta-srv/src/bootstrap.rs, src/meta-srv/src/error.rs, src/meta-srv/src/handler.rs, src/meta-srv/src/handler/node_stat.rs, src/meta-srv/src/handler/persist_stats_handler.rs, src/meta-srv/src/handler/response_header_handler.rs, src/meta-srv/src/keys.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/selector.rs, src/meta-srv/src/selector/load_based.rs, src/meta-srv/src/service/router.rs
1. add load_based selector. (Now it is mainly based on the number of regions of the datanode)
2. add a attrs filed in Context, which used to pass some paramters to `Selector`.
3. fix wrong error display.
How to use `load_based` or `lease_based` selector? Default `lease_based`.
```
cargo run -- metasrv start --selector LoadBased
cargo run -- metasrv start --selector LeaseBased 
```
=> feat: add load_based selector in meta

config/datanode.example.toml, src/cmd/src/datanode.rs, src/datanode/src/datanode.rs, src/datanode/src/heartbeat.rs, src/datanode/src/instance.rs, src/datanode/src/mock.rs
At the moment, we stored datanode's grpc IP address in meta. However when this address changes, via a deployment in k8s for example, it's impossible for frontend to find that datanode again. This patch adds a new start option `--rpc-hostname` to `datanode` startup command and it will use value to report to meta.
- this option is optional and it fallback to `--rpc-addr`, this behaviour is completely same to current
- as its name suggests, you can configure hostname and it resolves port from `--rpc-addr`
- user has to guarantee that the `--rpc-hostname` resolves to `--rpc-addr` so that frontend can call datanode via this hostname. User can use `0.0.0.0` in `--rpc-addr` as an …
=> feat: add --rpc-hostname option to datanode for a persist address to store in meta

src/meta-srv/src/error.rs
This pr mainly add an opaque error type in meta, to facilitate error handling in extension modules
=> chore: add an opaque error type in meta

Cargo.lock, src/cmd/src/frontend.rs, src/cmd/src/standalone.rs, src/common/error/src/status_code.rs, src/datanode/src/server.rs, src/frontend/src/frontend.rs, src/frontend/src/server.rs, src/servers/Cargo.toml, src/servers/src/auth.rs, src/servers/src/auth/user_provider.rs, src/servers/src/error.rs, src/servers/src/http.rs, src/servers/src/http/authorize.rs, src/servers/src/http/handler.rs, src/servers/src/mysql/handler.rs, src/servers/src/mysql/server.rs, src/servers/src/postgres/auth_handler.rs, src/servers/src/postgres/server.rs, src/servers/tests/auth.rs, src/servers/tests/http/authorize.rs, src/servers/tests/http/http_handler_test.rs, src/servers/tests/http/influxdb_test.rs, src/servers/tests/http/mod.rs, src/servers/tests/mod.rs, src/servers/tests/mysql/mysql_server_test.rs, src/servers/tests/postgres/mod.rs, tests-integration/tests/http.rs
- change method name from `auth` to `authenticate` in `UserProvider`
- add `authorize` method to `UserProvider ` to check user request's access permission to database(framework logic, no implementation yet)
- extract `MysqlRuntimeOption` to aggregate mysql pass-through options
- **BREAK**: rename `database` to `db` in http's `SqlQuery` to better align with InfluxDB and promethues
- add and modify necessary unit test
todo
=> feat: add `authorize` to `UserProvider` trait

src/datanode/src/tests/instance_test.rs, src/mito/src/engine.rs
Fix bug: table cannot be created after renaming
Fixes #892
=> fix: create table after rename table

.github/workflows/release.yml, Cargo.toml
This patch fixes #893 by assigning our ubuntu 20.04 runners to release tasks. We also changed `lto` to `thin`  to speed up binary building.
=> ci: use ubuntu 2004 to build weekly

src/servers/tests/mysql/mysql_server_test.rs
Fixes compilation error on default branch.
=> fix: mysql tests error

Cargo.lock, src/common/time/Cargo.toml, src/common/time/src/error.rs, src/common/time/src/range.rs, src/common/time/src/timestamp.rs, src/common/time/src/timestamp_millis.rs, src/datatypes/Cargo.toml, src/datatypes/src/value.rs, src/query/tests/time_range_filter_test.rs, src/storage/src/chunk.rs, src/storage/src/sst.rs, src/table/src/predicate.rs
- Extract time range predicate from filters in SQL queries
- Prune SST files according to file time range and predicate
Future work: we may need to benchmark this feature against a large dataset.
#846
=> feat: prunine sst files according to time range in filters

src/servers/src/auth.rs, src/servers/src/mysql/handler.rs
This pr mainly adds human-friendly return msg to mysql client if `authorize` method fails.
=> chore: return `authorize` err msg to mysql client

Cargo.lock, Cargo.toml, src/cmd/Cargo.toml, src/common/catalog/Cargo.toml, src/common/query/Cargo.toml, src/common/recordbatch/Cargo.toml, src/common/substrait/Cargo.toml, src/log-store/Cargo.toml, src/mito/Cargo.toml, src/promql/Cargo.toml, src/query/Cargo.toml, src/script/Cargo.toml, src/store-api/Cargo.toml, src/table/Cargo.toml
Bump tokio to `1.24.2` to resolve a [dependabot alert](https://github.com/GreptimeTeam/greptimedb/security/dependabot/5) (which won't be triggered in our project). And migrate some `Cargo.toml` files to workspace dependence style (only on for tokio).
Closes #899
=> build(deps): bump tokio to 1.24.2

src/api/greptime/v1/database.proto, src/common/grpc/src/flight.rs
Because official Java Flight client has some limitations (not exposing FlightData), change how AffectedRows is carried in flight stream to accommodate it.
=> refactor: accommodate java flight client

Cargo.lock, config/standalone.example.toml, src/cmd/src/standalone.rs, src/datanode/src/server.rs, src/frontend/src/mysql.rs, src/frontend/src/server.rs, src/servers/Cargo.toml, src/servers/src/auth/user_provider.rs, src/servers/src/mysql/handler.rs, src/servers/src/mysql/server.rs, src/servers/src/postgres/auth_handler.rs, src/servers/tests/mysql/mysql_server_test.rs
- upgrade `openers-mysql` to main branch to allow `reject_connection_on_dbname_absence` option
- refactor `MysqlServer` struct
- create `MysqlSpawnRef` and `MysqlSpawnConfig` to holds fields that are originally stored in `MysqlServer`
- `MysqlSpawnRef` stores `Arc<Ref>`s which are to be passed to `MysqlInstanceShim` while accepting each tcp stream
- `MysqlSpawnConfig` stores config values which are used to initializing `MysqlInstanceShim`
- modify relating tests
=> feat: add mysql `reject_no_database`

src/common/error/Cargo.toml, src/common/time/src/range.rs
- Fix `TimestampRange::new_inclusive`, add emptiness check.
- Add `std` and `derive` feature to strum dep in common-error crate.
=> fix: TimestampRange::new_inclusive and  strum dependency 

src/promql/src/planner.rs
Plan PromQL `Binary` expression to datafusion `LogicalPlan`. Plan and expression are mixed in PromQL, so translating this part might not be very straightforward:
- Literals should be processed separately because they are not plan in DF. 
- Binary ops on columns are translated to an `INNER JOIN ON TIME INDEX`, with operator applied to each value-column.
=> feat: PromQL binary expr planner

.env.example, Cargo.lock, src/cmd/src/datanode.rs, src/datanode/src/datanode.rs, src/datanode/src/instance.rs, src/datanode/src/tests/test_util.rs, src/frontend/src/tests.rs, src/object-store/Cargo.toml, src/object-store/tests/object_store_test.rs, tests-integration/README.md, tests-integration/src/test_util.rs, tests-integration/tests/main.rs
- Adds ObjectStoreConfig::OSS for OSS object storage configurations.
- Create oss object-store instance in the datanode when configured.
- Introduced Config Structs for ObjectStoreConfig
- Added support for OSS storage according to this issue GreptimeTeam/greptimedb/issues/823
GreptimeTeam/greptimedb/issues/823
=> feat: oss storage support

src/frontend/src/error.rs
Since the `SqlQueryHandler` implementation uses `frontend::error::Error` in [`do_query`](https://github.com/GreptimeTeam/greptimedb/blob/a7dc86ffe5c7be47e65c399b124c33222431aade/src/frontend/src/instance.rs#L421) and `do_statement_query`, error returned by interceptor should be able to convert to frontend error.
This pr adds `SqlExecIntercepted` snafu in `frontend::error::Error` to enable conversion.
=> chore: add interceptor err in `frontend::error::Error`

Cargo.lock, Cargo.toml, src/common/error/Cargo.toml, src/common/procedure/Cargo.toml, src/common/procedure/src/error.rs, src/common/procedure/src/lib.rs, src/common/procedure/src/procedure.rs, src/object-store/Cargo.toml, src/storage/Cargo.toml, tests-integration/Cargo.toml
This PR ports the traits needed by the procedure framework from the [PoC branch](https://github.com/evenyag/greptimedb/tree/poc/procedure-api). The [RFC](https://github.com/GreptimeTeam/greptimedb/pull/836) explains the concept of `Procedure`, `ProcedureId`, and `ProcedureManager`.
Additionally, the `Procedure` trait has a `lock_key()` method that returns a `LockKey` struct to tell the `ProcedureManager` to acquire lock.
```rust
#[async_trait]
pub trait Procedure: Send + Sync {
/// Type name of the procedure.
fn type_name(&self) -> &str;
// ......
/// Returns the [LockKey] if this procedure needs to acquire lock.
fn lock_key(&self) -> Option<LockKey>;
}
```
Note that …
=> feat: Define procedure related traits

Cargo.lock, src/servers/Cargo.toml, src/servers/src/postgres.rs, src/servers/src/postgres/auth_handler.rs, src/servers/src/postgres/handler.rs, src/servers/src/postgres/server.rs, src/servers/tests/postgres/mod.rs
This patch updates pgwire to 0.8 and make our `PostgresServerHandler` stateful (one handler per connection). This is prerequisite for upcoming prepared statement support.
=> refactor: make postgres handler stateful

.github/workflows/develop.yml
Background: https://github.com/GreptimeTeam/greptimedb/pull/916#issuecomment-1408190700
It's hard to debug sqlness failure without those log files. This patch uploads log files after sqlness run is finished as CI artifacts. Those log files' TTL is set to 3 days, it might not be too large.
=> build(ci): upload sqlness log files

Cargo.lock, Cargo.toml, src/frontend/Cargo.toml, src/frontend/src/catalog.rs, src/frontend/src/error.rs, src/frontend/src/instance.rs, src/frontend/src/instance/distributed.rs, src/frontend/src/lib.rs, src/frontend/src/spliter.rs, src/frontend/src/table.rs, src/frontend/src/table/insert.rs, src/frontend/src/tests.rs, src/partition/Cargo.toml, src/partition/src/columns.rs, src/partition/src/error.rs, src/partition/src/lib.rs, src/partition/src/manager.rs, src/partition/src/partition.rs, src/partition/src/range.rs, src/partition/src/route.rs, src/partition/src/splitter.rs
Move partition rule related code to partition manager.
#901
=> refactor: move partition related code to partition manager

docs/rfcs/2023-01-03-procedure-framework.md
This PR adds an RFC for the procedure framework
[Rendered](https://github.com/evenyag/greptimedb/blob/docs%2Fprocedure-rfc/docs/rfcs/2023-01-03-procedure-framework.md)
I implement the prototype in [this branch](https://github.com/evenyag/greptimedb/tree/poc/procedure-api)
- #286
=> docs: Add procedure framework RFC

Cargo.lock, src/common/procedure/Cargo.toml, src/common/procedure/src/error.rs, src/common/procedure/src/lib.rs, src/common/procedure/src/procedure.rs, src/common/procedure/src/store.rs, src/common/procedure/src/store/state_store.rs
This PR implements the storage layer for the procedure framework.
The `ProcedureStore` stores procedures on the object store, using the following directory structure
```
/path/to/procedures/{PROCEDURE_ID}/0000000000.step
/path/to/procedures/{PROCEDURE_ID}/0000000001.step
/path/to/procedures/{PROCEDURE_ID}/0000000002.commit
```
The content of the `step` file is a JSON object serialized from `ProcedureMessage`
```rust
struct ProcedureMessage {
type_name: String,
data: String,
parent_id: Option<ProcedureId>,
}
```
e.g.
```json
{
"type_name":"TestMessage",
"data":"no parent id",
"parent_id":"9f805a1f-05f7-490c-9f91-bd56e3cc54c1"
}
```
The `StateStore` trait is an abstraction for …
=> feat: Implement ProcedureStore

README.md
Adds dashboard repo link to resources section in README.
=> docs: add dashboard to resources in README

Cargo.lock, src/script/src/python/coprocessor.rs, src/script/src/python/coprocessor/parse.rs, src/script/src/python/engine.rs, src/script/src/python/test.rs
Allow query with sql in python coprocessor, just like this:
```python
def test(a):
return query.sql("select * from numbers")[0][0][1]
```
`sql` call return a Python List, a List[List[PyVector]] to be exactly, where the inner `List[PyVector]` corrseponding to the `RecordBatch`, the outer List corrseponding to `RecordBatches`
- How does this PR work? 
Because RustPython is sync, we have to spawn a thread and a new tokio Runtime everytime `sql` is called, for not knowing if being called in a async context(call stack could be like async -> sync -> async or just sync->async)
- Describe any limitations of the current code
Calling `sql` block current task, might create a new tokio …
=> feat: Query using sql inside python script

src/common/procedure/src/lib.rs, src/common/procedure/src/local.rs, src/common/procedure/src/local/lock.rs
This PR introduces a lock component for ProcedureManager. To implement lock, it also needs a `ProcedureMeta` struct to track the metadata of a procedure in the manager.
`LockMap` manages all locks and it uses struct `Lock` to represent a lock entry.
```rust
struct Lock {
/// Current lock owner.
owner: ProcedureMetaRef,
/// Waiter procedures.
waiters: VecDeque<ProcedureMetaRef>,
}
```
Only the owner procedure can hold the lock. Once it releases the lock, the lock entry pops the waiter from the queue and notifies the waiter procedure.
- #286
=> feat: Implement lock component for ProcedureManager

Cargo.lock, src/datanode/src/error.rs, src/datanode/src/instance/sql.rs, src/frontend/src/error.rs, src/frontend/src/instance.rs, src/frontend/src/instance/distributed.rs, src/frontend/src/instance/standalone.rs, src/query/src/datafusion.rs, src/query/src/datafusion/planner.rs, src/query/src/error.rs, src/query/src/parser.rs, src/query/src/plan.rs, src/query/src/query_engine.rs, src/servers/Cargo.toml, src/servers/src/error.rs, src/servers/src/http.rs, src/servers/src/postgres.rs, src/servers/src/postgres/handler.rs, src/servers/src/query_handler/sql.rs, src/servers/tests/http/influxdb_test.rs, src/servers/tests/http/opentsdb_test.rs, src/servers/tests/http/prometheus_test.rs, src/servers/tests/mod.rs, src/servers/tests/postgres/mod.rs, src/sql/src/statements/query.rs
This is a proof-of-concept implementation of prepare statement for our postgres protocol adapter. In prepared statement, or extended query as in postgres, it follows a parse-bind-describe-execute process to run a query:
- prepared statement are provided in parse phase, as well as type information of its parameters
- in bind phase, the value of parameters are provided
- describe request asks for schema of result set
- and execute request actually run the query
When statement is cached in server-side, parse and describe can be omitted. 
In order to support this process, we need a new ability to get schema out of a query statement without executing it. This implementation …
=> feat: Initial prepare statement support for Postgres protocol

docs/rfcs/2023-02-01-table-compaction.md
=> docs: rfc for table compaction

src/datanode/src/instance/script.rs, src/datanode/src/script.rs, src/frontend/src/instance.rs, src/script/src/manager.rs, src/script/src/table.rs, src/servers/src/http/script.rs, src/servers/src/query_handler.rs, src/servers/tests/http/http_handler_test.rs, src/servers/tests/mod.rs, src/servers/tests/py_script/mod.rs, tests-integration/tests/http.rs
#665 Scripts table should be created for each database/schema
- To fix this issue, we decided to add `schema column` to scripts table. Then all scripts can insert to  scripts table and use `schema column` to specify which schema the script belongs to.
- Currently, I still put scripts table in the default catalog. We will create another issue for supporting `show scripts`  sql command and support http access, this is a proper time to move the `scripts table to system catalog. If I move scripts table to the system catalog in this issue, the scripts isn't visible to users.
#665
=> refactor: add schema column to the scripts table

src/common/procedure/src/local.rs, src/common/procedure/src/local/lock.rs, src/common/procedure/src/local/runner.rs, src/common/procedure/src/procedure.rs, src/common/procedure/src/store.rs
This PR adds a procedure manager and implements its skeleton
- The manager runs a procedure in a dedicated Runner
- The runner acquires and releases lock for the procedure
- ManagerContext tracks all loaders, locks and procedures
- Recover
- Subprocedures
- Inherit locks from parent
- #286
=> feat: Add procedure manager LocalManager

.github/workflows/release.yml
Prevent the release job from running on the forked repo by [adding conditions](https://github.com/orgs/community/discussions/26704), so that I don't need to receive the report email every time it's triggered.
=> build(ci): disable release workflow for forked repo

src/api/build.rs, src/api/greptime/v1/meta/cluster.proto, src/meta-srv/src/bootstrap.rs, src/meta-srv/src/cluster.rs, src/meta-srv/src/error.rs, src/meta-srv/src/handler/persist_stats_handler.rs, src/meta-srv/src/keys.rs, src/meta-srv/src/lib.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/metasrv/builder.rs, src/meta-srv/src/mocks.rs, src/meta-srv/src/selector.rs, src/meta-srv/src/selector/load_based.rs, src/meta-srv/src/service.rs, src/meta-srv/src/service/admin.rs, src/meta-srv/src/service/admin/heartbeat.rs, src/meta-srv/src/service/cluster.rs, src/meta-srv/src/service/heartbeat.rs, src/meta-srv/src/service/router.rs, src/meta-srv/src/service/store.rs, src/meta-srv/src/service/store/ext.rs
This pr main change:
1. datanode stats is store in the mem_kv store of the meta leader, instead of etcd kv store.
2. add a cluster grpc service.
3. add an http api to query all heartbeat data(or datanode stats).
```
curl http://127.0.0.1:3002/admin/heartbeat
```
=> feat: datanode stats is stored in the mem_kv of meta leader

src/servers/Cargo.toml, src/servers/src/http/handler.rs, src/servers/tests/http/http_handler_test.rs
This patch fixes HTTP POST support in our sql api.  Now user can send params in query string or http form data.
cc @ZonaHex @alili
=> fix: add form data support for http sql api

.cargo/config.toml, .github/workflows/develop.yml, Makefile, tests/README.md
simplify the sqlness command to `cargo sqlness`. But the previous `cargo run --bin sqlness-runner` is still avaliable
=> chore: alias sqlness subcommand

Cargo.lock, src/servers/Cargo.toml, src/servers/src/postgres/handler.rs, src/servers/src/postgres/server.rs, src/session/src/context.rs
This is a design issue introduced in #914 and recent version of pgwire. In order to share state (reuse query context) between authenticator and query processors, we must ensure it's the same instance. The previous implementation recreate instance for each authenticator and query processor, causing the issue that it always uses default query context when processing query.
Content of this patch are mostly APIs changes in pgwire 0.9 -> 0.10. Key changes happen in:
- https://github.com/sunng87/pgwire/pull/51/files
- https://github.com/GreptimeTeam/greptimedb/pull/958/files#diff-e9848216200f785abc4e7134221158d9026b87896d50908b12aa407d6e973f48
=> fix: setting postgres query context

Cargo.lock, Cargo.toml, docs/rfcs/2023-02-01-table-compaction.md, src/log-store/Cargo.toml, src/storage/Cargo.toml, src/storage/src/compaction.rs, src/storage/src/compaction/dedup_deque.rs, src/storage/src/compaction/picker.rs, src/storage/src/compaction/rate_limit.rs, src/storage/src/compaction/scheduler.rs, src/storage/src/compaction/task.rs, src/storage/src/error.rs
This is the first part of work towards table compaction which contains:
- table compaction scheduler that polls and executes table compaction requests in a FIFO manner
- rate limiter framework to limit the resources used by compaction tasks;
- currently it only limits the max concurrently running tasks number
- compaction strategy (`Picker`) part is still working, but the tests involves the trait so a primitive trait is defined, but it's not the final trait definition.
=> feat: compaction scheduler and rate limiter

Cargo.lock, src/promql/src/extension_plan.rs, src/promql/src/extension_plan/planner.rs, src/promql/src/extension_plan/series_devide.rs, src/promql/src/extension_plan/series_divide.rs, src/promql/src/planner.rs
New plan `SeriesDivide` that helps to divide data into time-series organized format.
=> feat: SeriesDivide plan for PromQL

src/datanode/src/sql/create.rs, tests/cases/standalone/create/create.result, tests/cases/standalone/create/create.sql
Loop through the Column Options for CreateTableRequest to find the inline primary key
[issues/923](https://github.com/GreptimeTeam/greptimedb/issues/923)
=> fix: Sql Inline Primary Key definition

src/frontend/src/instance.rs, src/frontend/src/instance/distributed.rs, src/frontend/src/sql.rs, src/query/src/query_engine/options.rs, src/sql/src/statements.rs, src/sql/src/statements/alter.rs, src/sql/src/statements/insert.rs
This pr mainly removes the incorrect `table_idents_to_full_name` function and change usage to the right one using `query_ctx`
=> fix: remove incorrect `table_idents_to_full_name`

src/script/src/python.rs, src/script/src/python/coprocessor.rs, src/script/src/python/dataframe.rs, src/script/src/python/engine.rs, src/script/src/python/testcases.ron, src/script/src/python/utils.rs, src/script/src/python/vector.rs
Bind `DataFrame` API in python script, example as below:
```python
from data_frame import col
def test(number)->vector[u32]:
return df.filter((col("number")==col("number))).collect()[0][0]
```
this api is just a subset of DataFusion's `DataFrame` api.   `DataFrame` and `Expr` types are wrapped in corrseponding python types and exposed similiar api.
Sadly, the `collect()` is async, so this hack of calling from async to sync to async must be used again(Creating new thread and new runtime for blocking calls)
=> feat: bind DataFrame API into python script

src/servers/src/http/handler.rs
The API looks like
```
http://localhost:4000/v1/promql?query=abs(foo{bar!="bar"})&start=0&end=100&step=5s
```
All of these four params are required. It's derived from Prometheus' [range_query](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries) API, without the timeout param.
=> feat: add start, end and step to promql http api

src/sql/src/error.rs
Removed `backtrace` from `Error` enum.
- this is a cleanup task. As per https://github.com/GreptimeTeam/greptimedb/issues/855 most backtraces in `sql::error::Error` are unnecessary and might hurt performance since the parser would always return them while parsing an invalid SQL.
- Docs are not needed in this case
- Need a bit of a steer with the necessary unit tests and integration tests.
https://github.com/GreptimeTeam/greptimedb/issues/855
=> feat: remove backtrace from sql::error::Error

src/common/time/src/timestamp_millis.rs, src/storage/src/chunk.rs, src/storage/src/compaction.rs, src/storage/src/compaction/picker.rs, src/storage/src/compaction/scheduler.rs, src/storage/src/compaction/strategy.rs, src/storage/src/compaction/task.rs, src/storage/src/flush.rs, src/storage/src/manifest/test_utils.rs, src/storage/src/sst.rs, src/storage/src/sst/parquet.rs, src/storage/src/version.rs
Implement a simple compaction strategy that compacts SSTs in leve 0 to level 1. 
The strategy iterates all compactable files in level 0, finds the time span of these files and fits the span to a set of predefine time bucket (`TimeBucket`). 
According to this time bucket duration, those files are assigned to multiple buckets. For example, given a bucket of 10, a file with time range 1~15 is assigned with bucket 0 and 10. If a file does not contain time range, it will be assigned by a special bucket `i64::MAX` so that all files without time range can be compacted together.
The compaction strategy generates a set of `CompactionOutput`. Each `CompactionOutput` will scan its …
=> feat: L0 to L1 compaction strategy

Cargo.lock, docs/rfcs/2023-01-03-procedure-framework.md, src/common/procedure/Cargo.toml, src/common/procedure/src/local.rs, src/common/procedure/src/local/lock.rs, src/common/procedure/src/local/runner.rs, src/common/procedure/src/procedure.rs, src/common/procedure/src/store.rs
LocalManager now actually executes procedures submitted to it.
The Runner executes the procedure in the `execute_procedure_in_loop` method
```rust
loop {
match self.execute_once(&ctx).await {
ExecResult::Continue => (),
ExecResult::Done => return Ok(()),
ExecResult::RetryLater => {
self.wait_on_err().await;
}
ExecResult::Failed(e) => return Err(e),
}
}
```
The Runner now supports subprocedures:
- Procedure can return `Status::Suspended` to submit subprocedures
- The Runner submits the subprocedures in `Runner::submit_subprocedure`
- It inherits parent_locks from the parent procedure
- It setups the parent_id of the subprocedure's metadata and push the child to its parent's …
=> feat: Execute procedure in LocalManager

Cargo.lock, src/api/Cargo.toml, src/meta-client/examples/lock.rs, src/meta-client/src/client.rs, src/meta-client/src/client/lock.rs, src/meta-client/src/rpc.rs, src/meta-client/src/rpc/lock.rs, src/meta-srv/src/bootstrap.rs, src/meta-srv/src/election/etcd.rs, src/meta-srv/src/error.rs, src/meta-srv/src/lib.rs, src/meta-srv/src/lock.rs, src/meta-srv/src/lock/etcd.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/metasrv/builder.rs, src/meta-srv/src/service.rs, src/meta-srv/src/service/lock.rs, src/meta-srv/src/service/store/etcd.rs
This pr provides the ability to distribute locks.
Main change:
1. metasrv add a Lock grpc service.
2. metasrv add a Lock trait and EtcdLock implement.
3. meta client provides an API for distributed locks.
4. an example is provided to show how to use distributed locks.
=> feat: meta provides the ability to distribute lock

src/servers/src/http.rs
This pr fix: an error occurred when requesting the http doc api
#983
=> fix: an error occurred when requesting the http doc api

src/common/procedure/src/local.rs, src/common/procedure/src/local/runner.rs, src/common/procedure/src/store.rs
This PR implements `LocalManager::recover` that recover uncommitted procedures from `ProcedureStore` and re-submits them to execute.
- `LocalManager` loads messages of all uncommitted procedures from `ProcedureStore` and caches in memory.
- Instead of recovering each subprocedures, `LocalManager` just submit the root procedure to execute.
- Because each step of the procedure is idempotent, the root procedure should submits its subprocedures again.
- Then the manager can load the subprocedure from the cached message by the procedure id.
- Once the root procedure is finished, we can remove the cached message from the manager.
This simplify the recover process a lot as we don't …
=> feat: Implement LocalManager::recover

src/query/src/datafusion.rs, src/query/src/executor.rs
refactor execute_stream to non-async method
#940
=> refactor: refactor execute_stream to non-async method

src/frontend/src/instance.rs, src/query/src/query_engine/options.rs
`obj_name_to_tab_ref` was originally introduced as a helper function to deal with `TableReference`, which is one way to express full table name (see #559)
Since it's kinda confusing with `table_idents_to_full_name`, and all usage cases can be replaces with `table_idents_to_full_name` easily, `obj_name_to_tab_ref` is now removed for better maintainability
=> refactor: remove `obj_name_to_tab_ref`

src/storage/src/error.rs
Removed unused `FlushIo` variant .
https://github.com/GreptimeTeam/greptimedb/issues/855
=> refactor(storage): remove unused FlushIo variant

src/servers/tests/http/http_test.rs, src/servers/tests/http/mod.rs
add http's api and doc IT.
https://github.com/GreptimeTeam/greptimedb/issues/983
=> test: add api and doc http test

Cargo.lock, src/meta-srv/Cargo.toml, src/meta-srv/src/bootstrap.rs, src/meta-srv/src/cluster.rs, src/meta-srv/src/error.rs, src/meta-srv/src/service/cluster.rs
This pr mainly change:  add retry logic for MetaPeerClient.
=> feat: add retry logic for MetaPeerClient

src/common/telemetry/src/logging.rs
Signed-off-by: Zheming Li <nkdudu@126.com>
Duplicate error logs into a separate file.
#805
=> feat: duplicate error logs into separate file

src/servers/src/http/handler.rs, src/servers/src/http/script.rs, src/servers/tests/http/http_handler_test.rs, tests-integration/tests/http.rs
unify http handler db param name to `db` instead of `schema` to fit auth procedure
- change param name from `schema` to `db` in script handler
- add `db: Option<String>` in promql handler
=> fix: rename `schema` to `db` in http param

src/mito/src/engine.rs
Fixes #1004 
This patch adds catalog name to our s3 path.
=> feat: add catalog name to s3 path

src/datanode/src/tests/promql_test.rs, src/promql/src/planner.rs
Maintain tag columns, time index column and value columns to generate correct complex plan.
Fix complex binary op with aggregator case.
=> fix: update planner state according to output plan

.github/workflows/doc-issue.yml
Like our doc issue, this change adds a cloud followup label to create issue in our cloud mod.
=> ci: add cloud followup label

Cargo.lock, src/promql/Cargo.toml, src/promql/src/error.rs, src/promql/src/planner.rs, src/query/Cargo.toml
update [promql-parser](https://crates.io/crates/promql-parser) to v0.1.0
=> feat: update promql-parser to v0.1.0

Cargo.lock, src/common/time/src/date.rs, src/common/time/src/datetime.rs, src/common/time/src/timestamp.rs, src/servers/Cargo.toml, src/servers/src/postgres/handler.rs
This patch aligns date/time format with postgresql so that psycopg2 and psycopg3 can consume these types of date.
=> fix: correct date/time type format for postgresql

Cargo.lock, src/common/procedure/Cargo.toml, src/common/procedure/src/lib.rs, src/common/procedure/src/local.rs, src/common/procedure/src/local/runner.rs, src/common/procedure/src/procedure.rs, src/common/procedure/src/store.rs
This PR adds two minor features to the procedure framework:
- Allow procedures to acquire multiple locks.
- Allow procedures to query procedure's state via the `ContexProvider` in the `Context`.
- #286
=> feat(procedure): Support multi-lock keys and querying procedure state from context

src/catalog/src/error.rs, src/catalog/src/remote/manager.rs, src/catalog/src/system.rs, src/catalog/tests/remote_catalog_tests.rs, src/common/grpc-expr/src/alter.rs, src/common/grpc-expr/src/error.rs, src/common/substrait/src/df_logical.rs, src/datanode/src/error.rs, src/datanode/src/server/grpc.rs, src/datanode/src/sql/create.rs, src/datanode/src/tests/test_util.rs, src/datatypes/src/schema/raw.rs, src/mito/src/engine.rs, src/mito/src/error.rs, src/mito/src/table/test_util.rs, src/script/src/table.rs, src/table/src/requests.rs, src/table/src/test_util/empty_table.rs, tests-integration/src/test_util.rs
This PR use `RawSchema` as the type of `CreateTableRequest::schema` to make it easier to serialize and deserialize contents of `CreateTableRequest`.
This is useful for implementing a procedure that creates a table because it needs to serialize and deserialize the request and pass the request to the table engine. The subprocedure created by the table engine may again need to serialize it.
- #286
=> refactor: changes CreateTableRequest::schema to RawSchema

src/datanode/src/instance/script.rs, src/datanode/src/script.rs, src/frontend/src/instance.rs, src/script/src/engine.rs, src/script/src/manager.rs, src/script/src/python/builtins.rs, src/script/src/python/builtins/test.rs, src/script/src/python/coprocessor.rs, src/script/src/python/coprocessor/compile.rs, src/script/src/python/coprocessor/parse.rs, src/script/src/python/engine.rs, src/script/src/python/error.rs, src/script/src/python/test.rs, src/script/src/python/testcases.ron, src/script/src/python/vector.rs, src/servers/src/http/script.rs, src/servers/src/query_handler.rs, src/servers/tests/http/http_handler_test.rs, src/servers/tests/mod.rs
Main changes:
1. Supports passing user params into scripts, for example:
```python
@copr(returns = ["number"])
def test(**params)->vector[i64]:
return int(params['a']) + int(params['b'])
```
Or coprocessing with a query:
```python
@copr(sql='select uint32s as number from numbers limit 5', args=['number'], returns=['n'])
def test(n, **params)  -> vector[i64]:
return n + int(params['a'])
```
As above, the `args` and `sql` in the `@coprocessor` annotation are both optional now. 
2. Let `/run-script` API accepts these params by URL params such as `run-script?name=test&a=1&b=1`. The params is in the form of `HashMap<String, String>`, and passed into python script as `KwArgs` such …
=> feat: supports passing user params into coprocessor

src/mito/src/table/test_util/mock_engine.rs, src/storage/src/engine.rs, src/storage/src/error.rs, src/storage/src/region.rs, src/storage/src/region/tests.rs, src/storage/src/region/tests/close.rs, src/storage/src/region/tests/flush.rs, src/storage/src/region/writer.rs, src/storage/src/test_util.rs, src/storage/src/test_util/flush_switch.rs, src/store-api/src/storage/region.rs
Adds `close` method for `Region` trait and implements the`close` method for the corresponding structs. Therefore, the upper(e.g. `EngineInner`) can call the `close` method to release the region resources when closing or dropping regions.
Based on my understanding, in order to close a region,
1. (Frontend) The frontend sets a CLOSING flag for the target region in metasrv. After that, it will reject future writing / altering requests.
2. (Frontend) Sends the close request to datanode leader(s).
3. (Frontend) The frontend sets a CLOSED flag for the target region in metasrv.
(rejecting the write requests due to network delay)
#832
=> feat: add close method for the region trait

src/catalog/src/tables.rs, src/common/grpc-expr/src/insert.rs, src/datanode/src/sql/delete.rs, src/datanode/src/sql/insert.rs, src/datatypes/src/schema/column_schema.rs, src/datatypes/src/schema/constraint.rs, src/datatypes/src/vectors.rs, src/datatypes/src/vectors/binary.rs, src/datatypes/src/vectors/boolean.rs, src/datatypes/src/vectors/date.rs, src/datatypes/src/vectors/datetime.rs, src/datatypes/src/vectors/list.rs, src/datatypes/src/vectors/null.rs, src/datatypes/src/vectors/primitive.rs, src/datatypes/src/vectors/string.rs, src/frontend/src/sql.rs, src/mito/src/table/test_util/mock_engine.rs, src/partition/src/splitter.rs, src/script/src/python/vector.rs, src/servers/src/error.rs, src/servers/src/line_writer.rs, src/storage/src/memtable/btree.rs, src/storage/src/read.rs
Improve `MutableVector` usability
- introduce `try_push_value_ref()` to preserve the initial behaviour of former `push_value_ref()`
- perform unwrap of the result inside `push_value_ref()` 
- add `push_null` to make pushing null more convenient
close https://github.com/GreptimeTeam/greptimedb/issues/978
=> refactor(datatypes): enhance MutableVector methods

src/servers/src/http.rs, src/servers/src/http/authorize.rs, src/servers/src/http/influxdb.rs, src/servers/tests/http/influxdb_test.rs
This pr mainly simply support influxdb ping and health endpoint.  (Only status code as response.)
Related Links
1. https://docs.influxdata.com/influxdb/v1.8/tools/api/#ping-http-endpoint
2. https://docs.influxdata.com/influxdb/v1.8/tools/api/#health-http-endpoint
=> feat: support influxdb ping and health endpoint

src/servers/src/error.rs, src/servers/src/http/authorize.rs, src/servers/tests/http/influxdb_test.rs
This pr mainly supports InfluxDB specific auth protocol as #1032 mentioned. 
Discussion: 
1. should we support basic auth fallback if InfluxDB specified auth failed or not found
2. using v1 auth would try to parse http query string twice, should we optimize that in this patch
@sunng87 @Fengys123 
#1032
=> feat: support InfluxDB auth protocol

src/storage/src/memtable/btree.rs, src/storage/src/region.rs, src/storage/src/region/tests.rs, src/storage/src/schema/region.rs
Simplify debug output of some structs in storage crates
- RegionImpl
- BTreeMemtable
- RegionSchema
=> refactor(storage): Simplify debug output of some structs

src/datanode/src/error.rs, src/datanode/src/instance/sql.rs, src/datanode/src/sql.rs, src/datanode/src/sql/copy_table.rs, src/frontend/src/instance.rs, src/query/src/datafusion/planner.rs, src/sql/src/error.rs, src/sql/src/parser.rs, src/sql/src/parsers.rs, src/sql/src/parsers/copy_parser.rs, src/sql/src/statements.rs, src/sql/src/statements/copy.rs, src/sql/src/statements/statement.rs, src/table/src/requests.rs
To export the data from a table to a Parquet file, use the COPY statement.
```
COPY tbl TO '/xxx/xxx/output.parquet' WITH (FORMAT = 'parquet');
```
If the data is too large, it will be automatically split into multiple files, one file per 5 million rows.
=> feat: export the data from a table to parquet files

src/promql/src/error.rs, src/promql/src/planner.rs, src/servers/src/promql.rs
- Support bool keyword (`some_metric > bool 1`)
- Support unary expr (`-some_metric`)
- Support paren expr (`(some_metric)`)
- Do not report error when querying a nonexistent label/metric.
Part of #1042
=> feat: Support unary, paren, bool keyword and nonexistent metric/label in PromQL

src/common/procedure/src/lib.rs, src/common/procedure/src/local.rs, src/common/procedure/src/local/runner.rs, src/common/procedure/src/procedure.rs
Add a `Watcher` to watch the procedure state. Callers can use this watcher to wait until the procedure is done.
Also refactor the runner. Now it uses RAII style to ensure the lock is released and the procedure is clean up.
- #286
=> feat(procedure): Add procedure watcher

src/catalog/src/helper.rs, src/meta-srv/src/error.rs, src/meta-srv/src/service/admin.rs, src/meta-srv/src/service/admin/heartbeat.rs, src/meta-srv/src/service/admin/leader.rs, src/meta-srv/src/service/admin/meta.rs
support admin meta http api.
1. Query the catalog list. 
2. Query the schema list by catalog name. 
3. Query the table list by catalog name and schema name.
4. Query table info by full table name.
5. Query the information of the meta leader node.
6. Query heartbeat by ip.
=> feat: admin http api

src/promql/src/planner.rs
support filter expression like `some_metric > 1.2345` in PromQL.
#1042
=> feat: support filter expression in PromQL

src/sql/src/statements.rs
Due to sqlparser-rs's limitation, we don't support datetime type natively. Instead we need to using quoted string to create a datetime column:
```sql
CREATE TABLE monitor (
host STRING,
ts TIMESTAMP,
dt "DATETIME",
TIME INDEX (ts),
PRIMARY KEY(host)) ENGINE=mito WITH(regions=1);
```
If we use `dt DATETIME` then it will complain:
```bash
ERROR 1815 (HY000) at line 1: Failed to execute query: CREATE TABLE m_1677145596 (ts BIGINT, memory datetime, TIME INDEX (ts)) ENGINE=mito, source: Failed to parse SQL, source: SQL data type not supported yet: Datetime(None)
```
This PR fixes the native support for datetime types, and we can create datetime column in a natural way:
```sql …
```
=> fix: support datetime type parsing

.github/workflows/license.yaml
Looks like https://github.com/apache/skywalking-eyes/pull/149 breaks our license check. This PR use a fixed revision to workaround this.
=> ci: Use fixed skywalking-eyes revision

codecov.yml
Remove some blocks from codecov's comment. It contains many (maybe useful) contents, but is toooo loooong that I can merely put them within one screen. And, in my experience, they are very very inaccurate. So removing them might be a good choice. 
It currently looks like this, and I'm going to only preserve the first **red-green** block
=> ci: simplify codecov commment

Cargo.lock, config/datanode.example.toml, config/frontend.example.toml, src/cmd/src/datanode.rs, src/cmd/src/frontend.rs, src/cmd/src/standalone.rs, src/datanode/Cargo.toml, src/datanode/src/datanode.rs, src/datanode/src/instance.rs, src/frontend/Cargo.toml, src/frontend/src/error.rs, src/frontend/src/frontend.rs, src/frontend/src/instance.rs, src/meta-client/src/lib.rs, tests/conf/datanode-test.toml.template
This PR
- Renames MetaClientOpts to MetaClientOptions
- Reorders the fields in some options so we can use `toml::to_string()` to serialize them. See https://users.rust-lang.org/t/why-toml-to-string-get-error-valueaftertable/85903/2
**BREAKING CHANGE**: This PR renames `meta_client_opts` section in the toml file to `meta_client_options`
```
[meta_client_options]
metasrv_addrs = ['127.0.0.1:3002']
timeout_millis = 3000
connect_timeout_millis = 5000
```
=> chore: Rename MetaClientOpts to MetaClientOptions

.github/workflows/develop.yml, Cargo.lock, src/cmd/Cargo.toml, src/cmd/src/bin/greptime.rs, src/cmd/src/cli.rs, src/cmd/src/cli/cmd.rs, src/cmd/src/cli/helper.rs, src/cmd/src/cli/repl.rs, src/cmd/src/error.rs, src/cmd/src/lib.rs, src/cmd/tests/cli.rs
Before removing SQL interface from Datanode ( #1010 ), we need something as a substitute to mysql-cli. This REPL can serve the purpose. It's largely inspired by influx-iox. Simple, yet powerful, has history and hint, can directly execute SQL via our grpc interface.
Some screenshots:
start and help:
the subcommand is "cli" and then "attach"
hint based on history ("tab" to complete it):
multiline support:
executing sqls:
#1010
=> feat: a simple REPL for debugging purpose

Cargo.lock, src/client/Cargo.toml, src/client/examples/logical.rs, src/common/substrait/Cargo.toml, src/common/substrait/src/context.rs, src/common/substrait/src/df_expr.rs, src/common/substrait/src/df_logical.rs, src/common/substrait/src/schema.rs, src/common/substrait/src/types.rs
While working on an integration with our client and [vector](https://vector.dev), we are blocked by a version conflict on prost. This patch updates substrait and prost to resolve that.
=> feat: update substrait and prost version

src/frontend/src/catalog.rs
Now `CatalogManager` loads and parses all catalog names while checking `is_valid_schema`. If any parse fails, the whole connections is aborted even if the failed one is not related to the current connection's catalog name.
This pr mainly adds warning to the above case instead of throwing an error and aborting the whole connection.
=> fix: continue if parsing err catalog

src/catalog/src/remote/manager.rs
`RemoteCatalogManager` loads and parses all catalog names while booting datanode. If any parse fails, the booting process throws an error and crashes. 
This pr mainly adds error msg to the above case instead of throwing an error and crashing.
=> fix: fix catalog parsing issue

src/datanode/src/error.rs, src/datanode/src/sql/copy_table.rs, src/datanode/src/tests/instance_test.rs, src/datanode/src/tests/test_util.rs
After the OpenDAL was [bumped to v0.27](https://github.com/GreptimeTeam/greptimedb/commit/98ef74bff4507b730369b5a15ba69a31d3206903) , the fs backend builder [will panic if the root is not specified](https://github.com/datafuselabs/opendal/blob/91eebebee1b683659073f9cc751e25293a0fd974/src/services/fs/backend.rs#L147-L153).
=> fix: fix panic when the root is not specified

src/frontend/src/instance/opentsdb.rs, src/servers/src/http/influxdb.rs, src/servers/src/http/opentsdb.rs, src/servers/src/http/prometheus.rs, src/servers/src/mysql/handler.rs, src/servers/src/opentsdb/handler.rs, src/servers/src/query_handler.rs, src/servers/tests/http/opentsdb_test.rs, src/servers/tests/opentsdb.rs
This pr mainly uses `catalog` from connection parameters instead of using the default `greptime` catalog
see #909 
Some client protocols have been tested with `show tables`, `select from` and `insert` sql queries
1. MySQL
2. PostgreSQL
3. GRPC
4. HTTP api
5. influxdb line protocol
Further works and todos
1. openTSDB should be working but has not been tested yet
2. Prometheus remote config is working, but more thorough tests should be conducted
3. `scripts` interface will be refactored to accept `QueryContext`. This would be done in a separate patch refactoring `scripts` as a whole
4. add more unit test and integration test for custom catalog situation
#909
=> fix: use catalog from connection

src/common/procedure/src/error.rs, src/common/procedure/src/lib.rs, src/common/procedure/src/local.rs, src/common/procedure/src/local/runner.rs, src/common/procedure/src/procedure.rs, src/common/procedure/src/watcher.rs, src/datanode/src/error.rs, src/datanode/src/instance.rs, src/datanode/src/mock.rs, src/datanode/src/sql/create.rs, src/datanode/src/tests/instance_test.rs, src/datanode/src/tests/test_util.rs, src/mito/src/engine/procedure.rs, src/table-procedure/src/create.rs
This PR stores the procedure error in the `ProcedureState` so the watcher can use the error as source and expose the cause of failure to callers.
```rust
#[derive(Debug, Default, Clone)]
pub enum ProcedureState {
/// The procedure is running.
#[default]
Running,
/// The procedure is finished.
Done,
/// The procedure is failed and cannot proceed anymore.
Failed { error: Arc<Error> },
}
```
Since the `ProcedureState` should be cloneable so we need to use `Arc<Error>` to share the error.
This PR also adds a `watcher` mod to provide a helper method `wait()` to wait for a procedure and simplify the usage of the watcher.
```rust
pub async fn wait(watcher: &mut Watcher) -> …
```
=> feat: Store error in procedure state

config/datanode.example.toml, config/frontend.example.toml, config/metasrv.example.toml, config/standalone.example.toml
This PR adds comments to the config examples to document each option.
=> docs: Document fields in the config examples

Cargo.lock, tests/README.md, tests/runner/Cargo.toml, tests/runner/src/env.rs
Upgrade `sqlness` to [0.4](https://github.com/CeresDB/sqlness/releases).
From this PR, sqlness runner won't generate `.output` file to indicate errors. It would overwrite the result file directly. So you should check the git status to make sure everything works fine.
=> chore(deps): bump sqlness to v0.4

Cargo.lock, Cargo.toml, src/cmd/Cargo.toml, src/cmd/src/datanode.rs, src/cmd/src/frontend.rs, src/cmd/src/metasrv.rs
Fix test datanode::test_read_from_config_file, which depends on the example config file.
Also modify frontend and metasrv tests to construct toml file instead of read from example.
=> test: fix datanode::test_read_from_config_file

.github/pr-title-breaking-change-label-config.json
- change the regex to match all strings that DO NOT match `!:`
- never fails the CI for breaking-change label
=> ci: update breaking-change labeler

src/catalog/src/remote/manager.rs
This pr mainly removes incorrect `continue;` while datanode is initializing and pulling catalogs from remote meta srv.
=> fix: remove incorrect continue

src/mito/src/engine/procedure/create.rs
When creating a table using the Procedure framework, `ttl` and `write_buffer_size` options were not applied. The current PR improves that
https://github.com/GreptimeTeam/greptimedb/issues/1112
=> fix: apply ttl and write_buffer_size options when a table is created via procedure

Cargo.lock, src/catalog/Cargo.toml, src/catalog/src/remote/manager.rs
This pr simply fix:
In the GreptimeDB Cloud, when creating a table under a non-default catalog, an error is reported. As follows:
```
2023-03-02T09:16:22.951100Z ERROR servers::mysql::server: Internal error occurred during query exec, server actively close the channel to let client try next time. err.msg=Failed to collect recordbatch, source: Failed to poll stream, source: External error: Failed to init Recordbatch stream, source: External error: Failed to request Datanode, source: Failed to do Flight get, addr: greptimedb-datanode-0.greptimedb-datanode.greptimedb:4001, code: Internal error, source: Cannot find catalog by name: lyek6r2lmzmu err.code=Internal …
```
=> fix: can not find catalog when create table

src/meta-client/src/client.rs, src/meta-client/src/client/store.rs, src/meta-client/src/rpc.rs, src/meta-client/src/rpc/store.rs, src/meta-srv/src/cluster.rs, src/meta-srv/src/sequence.rs, src/meta-srv/src/service/cluster.rs, src/meta-srv/src/service/store.rs, src/meta-srv/src/service/store/etcd.rs, src/meta-srv/src/service/store/ext.rs, src/meta-srv/src/service/store/kv.rs, src/meta-srv/src/service/store/memory.rs
1. move the batch_get method to KvStore trait.
2. add some unit tests.
#1015
=> refactor: move the batch_get to KvStore trait

.github/workflows/develop.yml, Cargo.lock, Cargo.toml, docker/Dockerfile, src/common/function/src/scalars/udf.rs, src/script/Cargo.toml, src/script/src/python/engine.rs, src/script/src/python/ffi_types/copr.rs, src/script/src/python/ffi_types/pair_tests.rs, src/script/src/python/ffi_types/pair_tests/sample_testcases.rs, src/script/src/python/ffi_types/vector/tests.rs, src/script/src/python/pyo3/builtins.rs, src/script/src/python/pyo3/copr_impl.rs, src/script/src/python/pyo3/dataframe_impl.rs, src/script/src/python/pyo3/utils.rs, src/script/src/python/pyo3/vector_impl.rs, src/script/src/python/rspython/builtins.rs, src/script/src/python/rspython/copr_impl.rs, src/script/src/python/rspython/dataframe_impl.rs, src/script/src/python/rspython/testcases.ron, src/script/src/python/rspython/utils.rs, src/script/src/python/utils.rs, src/servers/tests/py_script/mod.rs, tests-integration/tests/http.rs
Added Integrated Test for Coprocessor, fix some minor bugs.
- Integrated tests for both RsPy and CPython backend
- fix `CoprStream` 's schema not set to it's output types' problem
- fix UDF have useless truncate of it's output's bug
- cache `Runtime` used in `block_on_async`
- added `lit` function for DataFrame API for both backend
- impl `rfloordiv`&`floordiv`&`filter` for pyo3 backend&tested
- added `to_pyarrow` and `from_to_pyarrow` for vector to convert to `pyarrow.array`
=> test: add Integrated Test for Coprocessor& fix minor bugs

src/mito/src/manifest/action.rs, src/storage/src/manifest/action.rs
Add table/region manifest compatibility tests to ensure future modifications to some deeply nested structs that are persisted to manifest won't cause compatibility issue.
=> test: add manifest compatibility tests

Cargo.lock, src/api/Cargo.toml, src/datanode/src/instance/grpc.rs, src/frontend/src/instance/distributed/grpc.rs
Bump `greptime-proto` to latest version
=> chore: bump greptime-proto to latest(ad01872)

Cargo.lock, Cargo.toml, src/cmd/Cargo.toml, src/cmd/src/bin/greptime.rs, src/common/mem-prof/Cargo.toml, src/common/mem-prof/README.md, src/common/mem-prof/src/error.rs, src/common/mem-prof/src/lib.rs, src/servers/Cargo.toml, src/servers/src/error.rs, src/servers/src/http.rs, src/servers/src/http/mem_prof.rs
Add memory profiling feature and HTTP handler to dump profiling data.
To enable memory profiling, try build binaries with feature `mem-prof`:
```bash
cargo build --features=mem-prof
```
and start GreptimeDB instance with env variables:
```bash
MALLOC_CONF=prof:true,lg_prof_interval:28 ./target/debug/greptime standalone start
```
To dump memory profiling data, use the HTTP API:
```bash
curl localhost:4000/v1/prof/mem > greptime.hprof
```
To create flamegraph according to dumped profiling data:
```bash
jeprof --svg <path_to_greptimedb_binary> --base=<baseline_prof> <profile_data> > output.svg
```
=> feat: memory profiling

src/datatypes/src/vectors/constant.rs, src/datatypes/src/vectors/operations.rs, src/datatypes/src/vectors/operations/take.rs
Add a new method `take` to `VectorOp`
closes #1054
=> feat(datatypes): implement VectorOp::take

Cargo.lock, src/servers/Cargo.toml, src/servers/src/error.rs, src/servers/src/mysql/handler.rs, src/servers/src/mysql/writer.rs, src/servers/tests/mysql/mod.rs, src/servers/tests/mysql/mysql_server_test.rs
support mysql prepared statement
- this initial version just cache sql for simplicity in `COM_STMT_PREPARE` 
- replace "?" placeholder with param in `COM_STMT_EXECUTE`
https://github.com/GreptimeTeam/greptimedb/issues/470
=> feat: mysql prepare replacing sql placeholder to param

src/storage/src/chunk.rs, src/storage/src/compaction/strategy.rs, src/storage/src/compaction/task.rs, src/storage/src/compaction/writer.rs, src/storage/src/file_purger.rs, src/storage/src/flush.rs, src/storage/src/manifest/action.rs, src/storage/src/manifest/region.rs, src/storage/src/manifest/test_utils.rs, src/storage/src/region/tests.rs, src/storage/src/sst.rs, src/storage/src/test_util/access_layer_util.rs
- Refactor region SST struct to hold an UUID as SST key to reduce overhead
- fix #1053
=> refactor(SST): UUID as id in FileMeta

src/promql/src/planner.rs
Ignore two cases `increase_aggr` and `count_over_time`
closes #1136
=> test: ignore two test cases due to arrow-datafusion#5513

.github/workflows/release.yml, Cargo.lock
Continue on error when building a release for non-x86 platform.
Refer to https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures
=> ci: Allow error when building release for non-x86 platform

.github/workflows/release.yml
Disable arm64 and macOS releases temporarily
=> ci: Disable arm64 release temporarily

.github/workflows/release.yml
tolerate error while building arm64 releases
Reference
- https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions
- [How to run a github-actions step, even if the previous step fails, while still failing the job](https://stackoverflow.com/a/75123818)
=> ci: tolerate error while building arm64 releases

src/common/mem-prof/Cargo.toml
Remove useless profile section in Cargo.toml of mem-prof crate.
fix #1144
=> fix: remove profile in mem-prof crate to suppress compiler warnings

src/store-api/src/logstore/entry_stream.rs
This pr mainly remove unnecessary braces around block return value.
=> fix: remove unnecessary braces around block return value

src/script/Cargo.toml
added `abi3` and `abi37` to `pyo3` so it can use a common abi which support >= Python 3.7, not a single Python Version anymore.
=> feat: `abi3` & `abi37`

Cargo.lock, Cargo.toml, src/script/Cargo.toml
As we enabled `pyarrow` feature on arrow by default, pyo3 is a required dependency. This patch updates the feature to be active only when `pyo3_backend` turned on.
=> fix: make pyo3 optional again

Cargo.lock, Cargo.toml
Bump version to 0.1.1 since 0.1.0 is released
=> chore: Bump version to 0.1.1

Cargo.lock, src/api/Cargo.toml, src/client/src/database.rs, src/datanode/src/instance/grpc.rs, src/frontend/src/instance/grpc.rs, src/servers/tests/mod.rs
This patch adds promql support for grpc service. This patch is based on a commit on https://github.com/GreptimeTeam/greptime-proto/pull/13, please merge the proto before this.
close #936
=> feat: implement promql query on grpc

src/catalog/tests/mock.rs, src/datanode/src/datanode.rs, src/datanode/src/error.rs, src/datanode/src/heartbeat.rs, src/datanode/src/instance.rs, src/datanode/src/server.rs, src/datanode/src/sql.rs, src/mito/src/engine.rs, src/mito/src/table.rs, src/table/src/engine.rs, src/table/src/table.rs, src/table/src/test_util/mock_engine.rs
Add `shutdown` method for datanode
#1158
=> feat: add shutdown for datanode

.github/workflows/release.yml, docker/aarch64/Dockerfile, docker/aarch64/compile-python.sh
fix cross compile script by replacing `${pwd}` with correct `$(pwd)`
=> fix: use correct env var

.github/workflows/release.yml
Add the separate GitHub Action job to push the image to the UCloud registry. The job can be continued on error and we can retry manually if it failed.
=> refactor: add the separate GitHub Action job to push the image to the UCloud registry

src/cmd/src/bin/greptime.rs, src/cmd/src/cli.rs, src/cmd/src/cli/repl.rs, src/cmd/src/datanode.rs, src/cmd/src/error.rs, src/cmd/src/frontend.rs, src/cmd/src/metasrv.rs, src/cmd/src/standalone.rs, src/meta-srv/src/bootstrap.rs
Make the cmd hold the application instance
#1158
=> refactor: make the cmd hold the application instance

.github/workflows/release.yml
1. Export 'PYO3_CROSS_LIB_DIR' when cargo build for aarch64-linux;
2. Move `-F pyo3_backend` to `matrix.opts`;
3. Delete `export` when compiling python(the shell env can't propagate to the new step);
=> fix: export 'PYO3_CROSS_LIB_DIR' when cargo build for aarch64-linux and refactor matrix opts

src/script/src/python/engine.rs, src/script/src/python/ffi_types/copr.rs, src/script/src/python/ffi_types/pair_tests.rs, src/script/src/python/ffi_types/pair_tests/sample_testcases.rs, src/script/src/python/ffi_types/vector/tests.rs, src/script/src/python/pyo3/builtins.rs, src/script/src/python/pyo3/copr_impl.rs, src/script/src/python/pyo3/dataframe_impl.rs, src/script/src/python/pyo3/utils.rs, src/script/src/python/pyo3/vector_impl.rs, src/script/src/python/rspython/builtins.rs, src/script/src/python/rspython/copr_impl.rs, src/script/src/python/rspython/dataframe_impl.rs, src/script/src/python/rspython/test.rs, src/script/src/python/rspython/testcases.ron
Put `dataframe` and `query` into `greptime` module
notice this currently only works for PyO3 backend, because RustPython doesn't support modifying modules after creation of interpreter(unless init interpreter per call of script, which is way too costy)
do this in python script(Only in pyo3) to get access to dataframe api and query in sql
`from greptime import dataframe, query`
added `dataframe` & `query`  into `greptime` module in pyo3 every time coprocessor is called with …
=> refactor: put `dataframe` & `query` into `greptime` module

src/catalog/src/error.rs, src/catalog/src/lib.rs, src/datanode/src/heartbeat.rs, src/mito/src/table.rs, src/table/src/table.rs
Report region disk usage stats to metasrv through heartbeat.
- Add `region_stats` on `table` trait.
- Collect region disk usage in heartbeat.
#1003
=> feat: Report disk usage stats to metasrv thru heartbeat

.github/workflows/release.yml
set 'continue-on-error' to false since the problem of compiling binary was resolved
=> ci: set 'continue-on-error' to false since the problem of compiling binary was resolved

src/datanode/src/server/grpc.rs, src/datanode/src/sql/flush_table.rs, src/frontend/src/server.rs, src/mito/src/engine/tests.rs, src/mito/src/table.rs, src/servers/src/error.rs, src/servers/src/http.rs, src/servers/src/http/admin.rs, src/servers/src/http/handler.rs, src/servers/tests/http/http_test.rs, src/servers/tests/http/influxdb_test.rs, src/servers/tests/http/opentsdb_test.rs, src/servers/tests/http/prometheus_test.rs, src/servers/tests/mod.rs, src/table/src/requests.rs, src/table/src/table.rs, tests-integration/src/test_util.rs
This PR allows users to manually flush table through HTTP API.
```bash
curl -XPOST 'localhost:4000/v1/admin/flush?catalog_name=greptime&schema_name=benchmark&table_name=tab&region=1'
curl -XPOST 'localhost:4000/v1/admin/flush?catalog_name=greptime&schema_name=benchmark&table_name=tab'
curl -XPOST 'localhost:4000/v1/admin/flush?catalog_name=greptime&schema_name=benchmark'
```
fixes 1087
=> feat: allow manual table flush through HTTP API

src/datanode/src/datanode.rs
derive serde default for Wal/CompactionConfig
=> chore(datanode): derive serde default for Wal/CompactionConfig

.github/workflows/release.yml
ci: disable run tests temporarily because of the tests are not stable now.
=> ci: disable run tests temporarily

.github/workflows/release.yml
- Release artifacts after binary and container is ready;
- Remove ucloud login in docker job;
=> ci: release artifacts after binary and container is ready

src/common/time/src/lib.rs, src/common/time/src/timestamp.rs, src/common/time/src/util.rs
When using our code base with those repos requires stable toolchains, like vector, unstable features block its compilation. This patch removes replaceable unstable feature in time module.
=> refactor: port div_ceil from stdlib to avoid unstable features

src/cmd/src/cli.rs, src/cmd/src/datanode.rs, src/cmd/src/error.rs, src/cmd/src/frontend.rs, src/cmd/src/metasrv.rs, src/cmd/src/standalone.rs, src/datanode/src/datanode.rs, src/meta-srv/src/bootstrap.rs, src/meta-srv/src/error.rs
Add `shutdown` method for standalone and metasrv
#1158
=> feat: add shutdown for standalone and metasrv

.github/workflows/release.yml, docker/ci/Dockerfile
1. Release the standalone binaries with pyo3 support for multiple platforms;
2. Install `python3`/`python3-dev`/`python3-pip`/`pyarrow`(**We release the images with pyo3 function**);
=> ci: release the standalone binaries with pyo3 and install python utils in images

.github/workflows/release.yml, docker/aarch64/compile-python.sh
1. Refactor the `compile-python.sh`(use shell function to make the logic more clean);
2. Use the same python version (3.10.10) to compile pyo3 binaries for the amd64 and arm64 platforms to keep version consistency with [docker image](https://github.com/GreptimeTeam/greptimedb/blob/develop/docker/ci/Dockerfile#L5-L6).
=> ci: refactor compile-python.sh and use the python310 to build amd64 binary

src/datanode/src/server/grpc.rs, src/datanode/src/sql/flush_table.rs, src/mito/src/engine/tests.rs, src/mito/src/table.rs, src/mito/src/table/test_util/mock_engine.rs, src/storage/src/region.rs, src/storage/src/region/tests/flush.rs, src/storage/src/region/writer.rs, src/store-api/src/storage.rs, src/store-api/src/storage/region.rs, src/table/src/requests.rs, src/table/src/table.rs
Add an argument to control whether `flush()` will wait until the flush is done
=> feat: wait flush until the flush is done

Cargo.lock, Cargo.toml, src/common/datasource/Cargo.toml, src/common/datasource/src/error.rs, src/common/datasource/src/lib.rs, src/common/datasource/src/lister.rs, src/common/datasource/src/object_store.rs, src/common/datasource/src/object_store/fs.rs, src/common/datasource/src/object_store/s3.rs, src/common/datasource/src/util.rs, src/datanode/Cargo.toml, src/datanode/src/error.rs, src/datanode/src/instance/sql.rs, src/datanode/src/sql.rs, src/datanode/src/sql/copy_table_from.rs, src/datanode/src/sql/copy_table_to.rs, src/sql/src/parsers/copy_parser.rs, src/sql/src/statements/copy.rs, src/table/src/requests.rs
1. Introduce common-datasource crate
2. Combine `Copy To` and `Copy From`
=> refactor: combine Copy To and Copy From

src/mito/src/engine/tests.rs, src/table/src/metadata.rs
After altering tables such as adding/removing columns, the `region_numbers` in table metadata is lost. Then after restarting the db instance, the altered table can't be scanned data at all, because it doesn't contain any regions.
=> fix: losing region numbers after altering table

src/datanode/src/tests/instance_test.rs, src/datanode/src/tests/test_util.rs, tests/cases/standalone/copy/copy_from_fs.result, tests/cases/standalone/copy/copy_from_fs.sql, tests/cases/standalone/copy/copy_to_fs.result, tests/cases/standalone/copy/copy_to_fs.sql
Add copy clause sqlness tests
#1081
=> test: add copy clause sqlness tests

Cargo.lock, src/api/Cargo.toml, src/servers/Cargo.toml, src/servers/src/error.rs, src/servers/src/grpc.rs
Add gRPC server reflection, suitable for debugging and illustrating purpose.
Use [grpcurl](https://github.com/fullstorydev/grpcurl):
```text
➜  ~ grpcurl -plaintext 127.0.0.1:4001 list
greptime.v1.GreptimeDatabase
➜  ~ grpcurl -plaintext 127.0.0.1:4001 list greptime.v1.GreptimeDatabase
greptime.v1.GreptimeDatabase.Handle
greptime.v1.GreptimeDatabase.HandleRequests
➜  ~ grpcurl -plaintext 127.0.0.1:4001 describe greptime.v1.GreptimeDatabase.Handle
greptime.v1.GreptimeDatabase.Handle is a method:
rpc Handle ( .greptime.v1.GreptimeRequest ) returns ( .greptime.v1.GreptimeResponse );
➜  ~ grpcurl -plaintext 127.0.0.1:4001 describe greptime.v1.GreptimeRequest …
```
=> feat: add gRPC reflection service

README.md
- use CDN URL instead of relative path for logos. When rendering README.md in https://greptimedb.rs relative path doesn't work
- fix the link to greptimedb.rs
=> docs: use CDN for logos

src/storage/src/chunk.rs, src/storage/src/sst.rs, src/storage/src/sst/parquet.rs, src/storage/src/test_util/access_layer_util.rs
Holds FileHandle in ParquetReader to avoid the purger purges it
- #1215
=> fix: Holds FileHandle in ParquetReader to avoid the purger purges it

src/script/src/python/ffi_types/copr.rs, src/script/src/python/ffi_types/pair_tests.rs, src/script/src/python/ffi_types/pair_tests/sample_testcases.rs, src/script/src/python/ffi_types/vector.rs, src/script/src/python/pyo3/builtins.rs, src/script/src/python/pyo3/copr_impl.rs, src/script/src/python/pyo3/dataframe_impl.rs, src/script/src/python/pyo3/vector_impl.rs, src/script/src/python/rspython/builtins.rs, src/script/src/python/rspython/dataframe_impl.rs
You can now slice PyVector in Pythonic ways, i.e:
`a[1:2]` `a[-2:-1]` `a[-1:-2:-1]`
And be able to create DataFrame from sql! This use `query().sql()` to get a `RecordBatch` and convert it to `Dataframe` :
```python
dataframe.from_sql(...)
```
=> feat: slicing PyVector&Create DataFrame from sql

src/storage/src/compaction/strategy.rs
This PR allows a larger compaction time bucket so that when compaction input involves a very wide time span, it won't be splitted into enumerous output files and exhaust file descriptors.
=> fix: allow larger compaction window to reduce parallel task num

src/storage/src/compaction/task.rs, src/storage/src/compaction/writer.rs, src/storage/src/file_purger.rs, src/storage/src/flush.rs, src/storage/src/sst.rs, src/storage/src/sst/parquet.rs, src/storage/src/test_util/access_layer_util.rs
Skip writing empty SST file if source does not contain any data.
=> fix: skip empty parquet

src/script/src/python/engine.rs, src/script/src/python/ffi_types.rs, src/script/src/python/ffi_types/copr.rs, src/script/src/python/ffi_types/vector.rs, src/script/src/python/pyo3/vector_impl.rs, src/script/src/python/rspython/builtins.rs, src/script/src/python/rspython/utils.rs
The current `sql` function in the coprocessor returns a list of lists such as `list[list[vector]]`. The query result is a list of `RecordBatch` and it converts each`RecordBatch` into a list of column vectors. It's not friendly to users and batch splitting is not necessary at all for the coprocessor.
So in this PR, I changed the return result type to `list[Vector]`: a list of column vectors. It concatenates all vectors from each batch into one vector for each column.
For example:
```python
import greptime
greptime.query().sql("select number as a, number as b from numbers limit 10")
```
It will return a list of two elements:
* The first one is `a` column and which is a vector. …
=> refactor: make sql function in scripts return a list of column vectors

src/table/src/table/numbers.rs
Add a no-op flush implementation to `NumbersTable` so that it won't complain "Unspported flush operation" when a full-flush is triggered during database shutdown.
fixes #1246
=> fix: noop flush impl for numbers table

src/script/src/python/ffi_types/pair_tests/sample_testcases.rs, src/script/src/python/pyo3/copr_impl.rs
set locals to py_main.dict(), so make executing CPython script just like normal CPython Interpreter, added testcases to confirm that
=> fix: set locals to main.dict too

.gitignore
This pr mainly modifies `.gitignore` to ignore dashboard's auto-downloaded files
=> chore: ignore dashboard files

Cargo.lock, src/api/Cargo.toml, src/client/src/client.rs, src/client/src/database.rs, src/servers/src/grpc.rs, src/servers/src/grpc/database.rs, src/servers/src/grpc/handler.rs, src/servers/src/lib.rs, tests-integration/tests/grpc.rs
Please merge https://github.com/GreptimeTeam/greptime-proto/pull/18 first.
This patch provides two new additions for our grpc protocol:
- new `dbname` field that compatible with naming rule with http/mysql/postgresql protocol servers, so that in multi-tenant environment we won't expose catalog/schema concepts to user. 
- a new health check service as it requires health probe in some environment
=> feat: add dbname and health check for grpc api

src/script/src/python/engine.rs, src/script/src/python/ffi_types/copr.rs, src/script/src/python/ffi_types/vector.rs, src/script/src/python/metric.rs, src/script/src/python/pyo3/builtins.rs, src/script/src/python/pyo3/copr_impl.rs, src/script/src/python/pyo3/utils.rs, src/script/src/python/rspython/builtins.rs, src/script/src/python/rspython/builtins/test.rs, src/script/src/python/rspython/copr_impl.rs
@MichaelScofield Found that script execution is really slow in debug build.
After some investigation, I found the issue is using `ok_or` in some places which will create an error with a backtrace even though it's not expected to be executed. 
Main changes:
* Adds some timer metrics for script execution.
* Replace all `ok_or` invocations by `ok_or_else`.
* Impl `data_type()` and `arrow_data_type()` for `PyVector`, refactor some code.
=> refactor: scripts perf and metrics

src/meta-srv/src/handler/failure_handler/runner.rs
Add an "else" arm to tokio::select, otherwise it panics with error "all branches are disabled and there is no else branch"
=> fix: a minor misuse of tokio::select

Cargo.lock, src/api/Cargo.toml, src/meta-client/examples/meta_client.rs, src/meta-client/src/client.rs, src/meta-client/src/client/store.rs, src/meta-client/src/rpc.rs, src/meta-client/src/rpc/store.rs, src/meta-srv/src/sequence.rs, src/meta-srv/src/service/store.rs, src/meta-srv/src/service/store/etcd.rs, src/meta-srv/src/service/store/kv.rs, src/meta-srv/src/service/store/memory.rs, src/servers/src/auth/user_provider.rs
This pr mainly implements `BatchDelete` on `kv_store`
#1249
=> feat: impl `BatchDelete`

src/servers/src/mysql/federated.rs, src/servers/src/mysql/handler.rs, src/servers/src/mysql/writer.rs
MySQL server supports sending multiple affected rows to the client. This is possible when the client is using JDBC to execute multiple insert statements.
=> feat: Support sending multiple affected rows

src/meta-srv/src/keys.rs
This pr mainly adds `build_table_route_prefix` for table route key, which returning prefix with given catalog and schema.
=> chore: add `build_table_route_prefix`

src/storage/src/error.rs
Remove backtrace to reduce CPU and mem consumption in high workload.
=> fix: remove backtrace from ratelimit error

benchmarks/src/bin/nyc-taxi.rs, src/storage/src/compaction/task.rs
- Limit max parallel compaction task number. Previously `join_all()`
- Fix schema mapping in nyc-taxi.
=> fix: nyc-taxi bench tools and limit max parallel compaction task number

src/datanode/src/instance/sql.rs, src/frontend/src/instance.rs, src/sql/src/lib.rs, src/sql/src/parsers/copy_parser.rs, src/sql/src/parsers/create_parser.rs, src/sql/src/statements/create.rs, src/sql/src/statements/statement.rs, src/sql/src/util.rs
Implement create external table parser
#1041
=> feat: implement create external table parser

.github/workflows/release.yml
only builds binaries for manually trigger workflow
=> ci: only builds binaries for manually trigger workflow

.github/workflows/release.yml
Cargo build all releases with dashboard embedded.
checked pre-built:
https://github.com/GreptimeTeam/image-builder-action/actions/runs/4561588733
=> ci: release binary with embedded dashboard enabled

Cargo.lock, src/datanode/Cargo.toml, src/datanode/src/instance/sql.rs, src/datanode/src/sql.rs, src/datanode/src/sql/create.rs, src/datanode/src/tests/test_util.rs, src/frontend/Cargo.toml, src/frontend/src/instance.rs, src/frontend/src/instance/distributed.rs, src/frontend/src/tests.rs, src/frontend/src/tests/instance_test.rs, src/frontend/src/tests/test_util.rs, tests/cases/standalone/alter/rename_table.result
Make "describe table" SQL executed at Frontend instance. 
Part of #1010.
After this PR, I think there are no more statements that should be rewritten to be executed in query engine. What's left stmts are all differently handled in distributed and standalone modes, can't be unified.
=> feat: unify describe table execution

tests/cases/standalone/alter/rename_table.result, tests/cases/standalone/alter/rename_table.sql, tests/runner/src/env.rs
- Able to restart during test execution. This uses the `ARG` interceptor from sqlness and listens on `restart` key. Example:
```sql
create table t1 values ();
-- SQLNESS ARG restart=true
select * from t1;
```
- Refactor sqlness-runner. Reuse some common util functions
=> feat: implement restart argument for sqlness-runner

src/datanode/src/instance.rs, src/mito/src/engine.rs, src/mito/src/engine/procedure.rs, src/mito/src/engine/procedure/alter.rs, src/mito/src/engine/procedure/create.rs, src/mito/src/error.rs, src/mito/src/table.rs, src/mito/src/table/test_util.rs, src/table/src/engine.rs, src/table/src/requests.rs
This PR implements procedure to alter a table in mito engine.
It adds an `alter_table_procedure` method to the `TableEngineProcedure` trait.
```rust
pub trait TableEngineProcedure: Send + Sync {
/// Returns a procedure that alters table by specific `request`.
fn alter_table_procedure(
&self,
ctx: &EngineContext,
request: AlterTableRequest,
) -> Result<BoxedProcedure>;
}
```
Now the procedure uses the version of the schema to check whether the alteration is applied.
It also fixes several issues:
- The procedure manager should not recover until the catalog manager is started since procedures might need to access the tables in the catalog manager
- The create table procedure …
=> feat: Implement procedure to alter a table for mito engine

Cargo.lock, src/common/runtime/src/repeated_task.rs, src/datanode/Cargo.toml, src/datanode/src/instance.rs
Fix #1292 #1235 
* Disable retry layer when using local file backend.
* Print expected error only in DEBUG level.
=> chore: improve opendal layers

src/promql/src/functions.rs, src/promql/src/functions/aggr_over_time.rs
Implemented the `stddev_over_time` function from PromQL, and added a corresponding test. Verified the calculation using [this](https://www.calculator.net/standard-deviation-calculator.html) page. 
https://github.com/GreptimeTeam/greptimedb/issues/1228
=> feat(stddev_over_time): add initial implementation

Cargo.lock, src/cmd/src/datanode.rs, src/common/base/src/readable_size.rs, src/datanode/src/datanode.rs, src/datanode/src/error.rs, src/datanode/src/sql/copy_table_to.rs, src/object-store/src/lib.rs, src/storage/Cargo.toml, src/storage/src/compaction/picker.rs, src/storage/src/compaction/scheduler.rs, src/storage/src/compaction/task.rs, src/storage/src/compaction/writer.rs, src/storage/src/config.rs, src/storage/src/file_purger.rs, src/storage/src/flush.rs, src/storage/src/lib.rs, src/storage/src/region/writer.rs, src/storage/src/sst.rs, src/storage/src/sst/parquet.rs, src/storage/src/sst/stream_writer.rs, tests/cases/standalone/copy/copy_from_fs.result, tests/cases/standalone/copy/copy_from_fs.sql
This PR proposed a buffered parquet writer to avoid writing whole parquet file into memory and flush to underlying storage at a time, which is caused by the gap between [ArrowWriter](https://docs.rs/parquet/34.0.0/parquet/arrow/arrow_writer/struct.ArrowWriter.html) which requires a `std::io::Write` and opendal's [`Writer`](https://docs.rs/opendal/0.30.4/opendal/struct.Writer.html), which implements `futures::AsyncWrite` only.
This PR can help to reduce the memory consumption during flush/compaction. 
Given an experiment that writes 1,000,000,000 rows into parquet file (target file size 1.2GB), original code uses up to 1.5GB ram while `BufferedWriter` uses at most 270MB. …
=> feat: buffered parquet writer

src/storage/src/manifest/region.rs
The old manifest logs may be deleted by GC task simultaneously with `do_checkpoint`, then cause checkpointing to fail. But it doesn't matter when deleting manifest logs fails in checkpointing, they will be purged by GC task.
=> fix: checkpoint fails when deleting old logs fails

src/common/function-macro/src/range_fn.rs, src/promql/src/extension_plan/empty_metric.rs, src/promql/src/functions.rs, src/promql/src/functions/quantile.rs, src/promql/src/planner.rs
Implement `quantile_over_time()` function in PromQL. This PR also fixes a schema bug with `time()` function
Ref to #1042
=> feat: impl quantile_over_time function

src/frontend/src/tests/instance_test.rs
This PR fixes the unit test that export table content to s3 and import the exported file back again, because #1263 changed the output file of table export into one single file instead of a set of parquet files.
fixes #1301
=> fix: unit test fails when try to copy table to s3 and copy back 

Cargo.lock, src/datanode/src/instance/sql.rs, src/datanode/src/tests.rs, src/datanode/src/tests/test_util.rs, src/frontend/Cargo.toml, src/frontend/src/instance.rs, src/frontend/src/lib.rs, src/frontend/src/tests.rs, src/frontend/src/tests/instance_test.rs, src/frontend/src/tests/promql_test.rs, src/frontend/src/tests/test_util.rs, src/servers/src/error.rs
part of #1010 
- make "instance_test.rs" also ran with distributed instance
- move promql exec to frontend
- also move "promql_test.rs" to frontend
=> refactor: move PromQL execution to Frontend

src/promql/src/functions/resets.rs
Implement the changes function resets from PromQL(references to [promql's document](https://prometheus.io/docs/prometheus/latest/querying/functions/#resets) and [the go implementation](https://github.com/prometheus/prometheus/blob/90b2f7a540b8a70d8d81372e6692dcbb67ccbaaa/promql/functions.go#L1004-L1021) for more details.)
https://github.com/GreptimeTeam/greptimedb/issues/1225
=> feat(resets): add initial implementation

src/promql/src/functions/changes.rs
Implement the `changes` function resets from PromQL(references to [promql's document](https://prometheus.io/docs/prometheus/latest/querying/functions/#changes) and [the go implementation](https://github.com/prometheus/prometheus/blob/90b2f7a540b8a70d8d81372e6692dcbb67ccbaaa/promql/functions.go#L1023-L1040))
https://github.com/GreptimeTeam/greptimedb/issues/1226
=> feat(changes): add initial implementation

src/frontend/src/instance/distributed.rs, src/mito/src/engine.rs, src/storage/src/compaction/task.rs, src/storage/src/engine.rs, src/storage/src/region/writer.rs, src/storage/src/sst.rs, src/storage/src/version.rs
Simplify log output #1217 
Not totally finished.
=> chore: tweak logs

Cargo.lock, benchmarks/src/bin/nyc-taxi.rs, src/api/Cargo.toml, src/client/examples/logical.rs, src/common/grpc-expr/src/alter.rs, src/common/grpc-expr/src/insert.rs, src/datanode/src/instance/grpc.rs, src/datanode/src/server/grpc.rs, src/frontend/src/catalog.rs, src/frontend/src/expr_factory.rs, src/frontend/src/instance.rs, src/frontend/src/instance/grpc.rs, tests-integration/tests/grpc.rs
1. support multi table engines in distributed mode
2. by default, it creates a MITO_ENGINE table if inserting data when the table does not exist   (in the `create_or_alter_table_on_demand` method)
#1272
=> feat: support multi table engines in distributed mode

src/promql/src/error.rs, src/promql/src/functions.rs, src/promql/src/functions/aggr_over_time.rs, src/promql/src/lib.rs, src/promql/src/planner.rs
Implement `__field__` special matcher. It can do projection on value columns under multi-value model. E.g.:
```sql
MySQL [(none)]> TQL eval (1667446797, 1667446807, '10s') system_metrics{ __field__="cpu_util"};
+----------+-------+-------+---------------------+
| cpu_util | host  | idc   | ts                  |
+----------+-------+-------+---------------------+
|     11.8 | host1 | idc_a | 2022-11-03 03:40:07 |
|       50 | host1 | idc_b | 2022-11-03 03:40:07 |
|     80.1 | host2 | idc_a | 2022-11-03 03:40:07 |
+----------+-------+-------+---------------------+
3 rows in set (0.005 sec)
MySQL [(none)]> TQL eval (1667446797, 1667446807, '10s') system_metrics{ …
```
=> feat: impl `__field__` special matcher to project value columns

src/frontend/src/server.rs, src/meta-srv/src/bootstrap.rs, src/meta-srv/src/error.rs
* The original `StartMetricsExport` error message was wrong.
* http server can not only expose metrics, so change `StartMetricsExport` to `StartHttp`
* After the HTTP metrics handler was changed to optional. Forget to add it in frontend.
=> chore: minor fix about metrics component 

config/datanode.example.toml, config/standalone.example.toml, src/cmd/src/datanode.rs, src/datanode/src/datanode.rs, src/storage/src/config.rs, src/storage/src/manifest/impl_.rs, src/storage/src/region.rs
Fix #1317 :
* Adds a new option to `[storage.manifest]`:
```toml
checkpoint_on_startup = false
```
* Adds function `ManifestImpl#may_do_checkpoint(version)`.
=> feat: try to do manifest checkpoint on opening region

src/promql/src/functions.rs, src/promql/src/functions/deriv.rs
I implement the `deriv` function in PromQL and add some unit test.
#1227
=> feat: implement deriv function

src/mito/src/engine.rs, src/mito/src/engine/procedure/create.rs, src/storage/benches/memtable/util/regiondesc_util.rs, src/storage/src/compaction/noop.rs, src/storage/src/compaction/picker.rs, src/storage/src/compaction/scheduler.rs, src/storage/src/compaction/strategy.rs, src/storage/src/compaction/task.rs, src/storage/src/engine.rs, src/storage/src/manifest/action.rs, src/storage/src/metadata.rs, src/storage/src/region.rs, src/storage/src/region/writer.rs, src/storage/src/test_util/config_util.rs, src/storage/src/test_util/descriptor_util.rs, src/store-api/src/storage/descriptors.rs, src/store-api/src/storage/engine.rs, src/store-api/src/storage/requests.rs, src/table/src/requests.rs
- add a field `compaction_time_window` in `TableOptions`.
-  persist the inferred time window to table manifest to avoid calculating it everytime.
https://github.com/GreptimeTeam/greptimedb/issues/1055
=> feat: initial changes for compaction_time_window field support

src/common/substrait/src/types.rs, src/datatypes/src/error.rs, src/datatypes/src/types/timestamp_type.rs, src/servers/src/mysql/writer.rs, src/sql/src/parser.rs, src/sql/src/statements.rs, tests/cases/standalone/common/timestamp/timestamp.result, tests/cases/standalone/common/timestamp/timestamp.sql
This PR enhances `Timestamp` to support specifying precision when creating tables, following the [fractional seconds syntax in MySQL](https://dev.mysql.com/doc/refman/8.0/en/fractional-seconds.html). 
Fractional seconds option now accepts:
- 0: no factional seconds, time unit is `TimeUnit::Second`
- 3: `TimeUnit::Millisecond`
- 6: `TimeUnit::Microsecond`
- 9: `TimeUnit::Nanosecond`
Also, this precision value is used in [substrait type variation](https://substrait.io/types/type_parsing/) to distinguish between different timestamp units:
> When expressing a type, a user can define the type based on a type variation. Some systems use type variations to describe different …
=> feat: support timestamp precision on creating table

src/datanode/src/sql/create.rs, src/frontend/src/tests/promql_test.rs, src/sql/src/parsers/create_parser.rs, tests/cases/standalone/common/create/create.result, tests/cases/standalone/common/create/create.sql, tests/cases/standalone/order/order_variable_size_payload.result, tests/cases/standalone/order/order_variable_size_payload.sql
Fix #1299 
After some investigation, I found that #1299 is hard to find a walkaround, without breaking any compatibilities to pg or mysql. However, I did find that both pg and mysql not allowed to create column name same with keyword without quoted. So I think we should do the same.
After this PR, create table like this is invalid: `create table my_table(user string, i bigint time index);`, the error msg is:
ERROR 1815 (HY000): Failed to execute query: create table my_table(user string, i bigint time index), source: Failed to parse SQL, source: Syntax error, sql: create table my_table(user string, i bigint time index), source: sql parser error: Cannot use keyword 'user' as …
=> fix!: not allowed to create column name same with keyword without quoted

src/cmd/src/datanode.rs, src/cmd/src/frontend.rs, src/cmd/src/metasrv.rs, src/servers/src/http.rs
Add disable_dashboard option and disable dashboard in metasrv and datanode.
Resolve #1337 
=> refactor: add disable_dashboard option and disable dashboard in metasrv and datanode

src/datanode/src/sql/copy_table_from.rs
This PR changes the behavior when copying data from external file into tables. 
Instead of reading all rows from all files into memory and writing them into tables at a time, now rows are written into tables as soon as memory consumption reaches a predefined threshold.
This may helps to reduce memory consumption when importing a large file like in [this thread](https://github.com/GreptimeTeam/greptimedb/discussions/1303).
=> fix: stream inserts when copying from external file

Cargo.lock, src/datanode/src/error.rs, src/datanode/src/sql/copy_table_from.rs, src/datatypes/Cargo.toml, src/datatypes/src/vectors/helper.rs, src/datatypes/src/vectors/primitive.rs
This PR allows users to import parquet files with explicit time zone info in schema by ignoring the time zone info and treating the `i64` value as time elapsed since UNIX epoch.
According to [Timezone Aware Timestamp Parsing - arrow-rs](https://github.com/apache/arrow-rs/issues/3794), the time zone info in schema is an indicator of the desired time zone, but the underlying value (the `i64` value) is always adjusted to UTC time. 
That is being to say, if we can a timestamp in secinds with value 28800 (8*60*60) and time zone "+08:00", what is the UTC time point of this timestamp? Is it "1970-01:01 00:00:00"? Actually no, it "1970-01:01 08:00:00" in UTC and "1970-01:01 …
=> feat: ignoring time zone info when import from external files

Makefile
1. Amend `fmt-toml`
2. Rename original `fmt-toml` to `check-toml` 
Format your TOML without tears 🥲
=> chore: amend fmt-toml

src/datanode/src/heartbeat.rs, src/meta-client/examples/meta_client.rs
* change metasrv and datanode heartbeat log level from info to trace. Now there are too many heartbeat logs. It may interfere with useful log viewing.
=> chore: set metasrv and datanode heartbeat log level to trace

src/mito/src/table.rs, src/table/src/error.rs
This PR prevents panicking when no regions are found in table during table scan.
fixes #1024
=> fix: avoid panic when no region found in table

src/servers/src/auth.rs, src/servers/src/grpc/handler.rs, src/servers/src/http/authorize.rs, src/servers/src/postgres/auth_handler.rs
This pr mainly introduces `auth` api, which is a simple combination of `authenticate` and `authorize`, but allow to be implemented for optimization. In most cases(other than MySQL auth process) it would be much easier to just use `auth` api. 
PostgreSQL, gRPC and HTTP auth process have been refactored to use the new `auth` api.
=> refactor: merge `authenticate` and `authorize` api

.cargo/config.toml, .github/workflows/develop.yml, CONTRIBUTING.md, Makefile, benchmarks/src/bin/nyc-taxi.rs, src/meta-client/src/rpc/lock.rs, src/meta-srv/src/service/admin/health.rs, src/meta-srv/src/service/store/etcd.rs, src/mito/src/table.rs, src/partition/src/splitter.rs, src/script/src/python/pyo3/copr_impl.rs, src/script/src/python/rspython/utils.rs, src/servers/src/mysql/handler.rs, src/servers/src/postgres/handler.rs, src/servers/tests/mysql/mod.rs, src/sql/src/statements.rs
Specify clippy denies (`-D clippy::print_stdout -D clippy::print_stderr`) in cargo config. Reduce duplicate settings.
=> build: specify clippy denies in cargo config

src/script/src/lib.rs, src/script/src/python/engine.rs, src/script/src/python/ffi_types.rs, src/script/src/python/ffi_types/copr.rs, src/script/src/python/ffi_types/pair_tests/sample_testcases.rs, src/script/src/python/ffi_types/py_recordbatch.rs, src/script/src/python/pyo3/builtins.rs, src/script/src/python/pyo3/copr_impl.rs, src/script/src/python/pyo3/dataframe_impl.rs, src/script/src/python/pyo3/vector_impl.rs, src/script/src/python/rspython/copr_impl.rs, src/script/src/python/rspython/dataframe_impl.rs
- from/to_numpy for `PyVector`
- PyDataFrame now `collect` to concated batch(So no `collect()[0][0]` just `collect()[0]`
- Added `PyRecordBatch` type as return values of `PyDataFrame.collect()` allowing indexing like `collected[0]` or `collected["number"]`
=> feat: from/to numpy&collect concat

Cargo.lock
Update dependency changes introduced in  #1356 so that nightly build won't fail 
https://github.com/GreptimeTeam/greptime-config/actions/runs/4684021761/jobs/8299707216#step:15:16
=> fix: update cargo lock

src/catalog/src/local/manager.rs, src/catalog/src/local/memory.rs
fix concurrent rename two table to same name may cause override
fixes #1369
=> fix: concurrent rename two table to same name may cause override

Cargo.lock, src/datanode/src/sql.rs, src/datanode/src/sql/alter.rs, src/table-procedure/Cargo.toml, src/table-procedure/src/alter.rs, src/table-procedure/src/create.rs, src/table-procedure/src/error.rs, src/table-procedure/src/lib.rs, src/table-procedure/src/test_util.rs
This PR adds a procedure `AlterTableProcedure` to alter a table.
- It invokes `TableEngineProcedure::alter_table_procedure()` to alter the metadata of the table
- If the alter request is renaming, it also renames the table in the catalog manager
- #286
=> feat: Add alter table procedure

Cargo.lock, src/frontend/Cargo.toml, src/servers/Cargo.toml
This patch updates our dependencies:
- rustls 0.21 and a few rustls related libaraies
- switched opensrv-mysql to upstream version
- updated pgwire to better empty query response, compatibility with recent versions of grafana
=> chore: update pgwire and rustls libraries

src/mito/src/engine.rs, src/mito/src/engine/procedure.rs, src/mito/src/engine/procedure/alter.rs, src/mito/src/engine/procedure/drop.rs, src/mito/src/table/test_util.rs, src/table/src/engine.rs, src/table/src/requests.rs
This PR adds a procedure to drop a table in the mito table engine.
- The procedure also closes the table (all regions) instead of just removing it from the engine.
- The original drop table implementation doesn't remove data actually so this procedure only removes the table from the memory map.
- #286
=> feat: Add drop table procedure to mito

src/frontend/src/instance.rs, src/servers/src/prom.rs
This pr mainly fixes a issue where prom handler uses `QueryContext::arc()` instead of actual input catalog and schema
@MichaelScofield 
Also, I think we should check every non-test call to `QueryContext::arc()`. It shouldn't  be called now that we have parsed catalog and schema from user input. I'll do this in a separate pr if you're ok with it
=> chore: query prom using input query context

Cargo.lock, src/servers/Cargo.toml
- mysql-async 0.32 was yanked, switch to a git deps until newer version released
- postgresql-tokio-rustls has a newer release, switch to crate.io version
=> chore: switch mysql_async to git dep

src/datanode/src/instance/sql.rs, src/datanode/src/metrics.rs, src/frontend/src/instance/distributed.rs, src/frontend/src/metrics.rs, src/mito/src/engine.rs, src/mito/src/lib.rs, src/mito/src/metrics.rs, src/mito/src/table.rs, src/storage/src/lib.rs, src/storage/src/metrics.rs, src/storage/src/region.rs
Add some metrics to monitor the elapsed time of creating/altering tables.
https://github.com/GreptimeTeam/greptimedb-cloud/issues/121
=> feat: add some metrics

.github/ISSUE_TEMPLATE/bug_report.yml
the last "how to reproduce" section in bug-report issue template will be rendered as `bash`. But it usually contains some extra descriptions along with commands. Thus it would be better to keep it as plain text and let others to write markdown.
E.g.: #1396
=> chore: don't render reproduce as shell in issue template

.github/workflows/release.yml, scripts/install.sh
1. Set whether it is the latest release by using 'ncipollo/release-action';
2. Modify greptimedb install script to use the latest nightly version binary;
=> ci: set whether it is the latest release by using 'ncipollo/release-action and update install.sh

Cargo.lock, Cargo.toml, src/client/src/database.rs, src/client/src/metrics.rs, src/common/runtime/Cargo.toml, src/common/telemetry/Cargo.toml, src/common/telemetry/src/metric.rs, src/datanode/Cargo.toml, src/query/Cargo.toml, src/servers/Cargo.toml
* add metrics for grpc client
* add the ability to set lables to an existing timer macro
* add `greptime` prefix for all metrics
=> chore: add some metrics for grpc client

Cargo.lock, src/object-store/Cargo.toml, src/object-store/src/cache_policy.rs, src/object-store/src/metrics.rs, src/object-store/tests/object_store_test.rs
Add two cache metrics to record cache hit/miss. #1276 
- Metric names:
- lru_cache.hit
- lru_cache.miss
- Metric labels:
- lru_cache.name: its value is set as "path"
- lru_cache.range: its value is set as the range in the read arguments.
- Add metrics to record cache hit/miss
Note: I'm not sure about these:
- Which labels should we use. I assume the cardinality of "range" is limited, and it's helpful to include it as a label. Let me know if my understanding is wrong.
- Naming convention about the metrics.
#1276
=> feat: Add metrics for cache hit/miss for object store cache

.github/workflows/release.yml
Remove "release" prefix from release name.
=> chore: remove Release prefix from release name

Cargo.lock, py_time_poc.md, src/script/Cargo.toml, src/script/src/python/error.rs, src/script/src/python/ffi_types/copr/compile.rs, src/script/src/python/ffi_types/copr/parse.rs, src/script/src/python/ffi_types/vector.rs, src/script/src/python/ffi_types/vector/tests.rs, src/script/src/python/rspython.rs, src/script/src/python/rspython/builtins.rs, src/script/src/python/rspython/builtins/test.rs, src/script/src/python/rspython/copr_impl.rs, src/script/src/python/rspython/dataframe_impl.rs, src/script/src/python/rspython/test.rs, src/script/src/python/rspython/utils.rs, src/script/src/python/rspython/vector_impl.rs, src/script/src/python/utils.rs
Update RustPython Version(with GC on) and fix compile errors
=> chore: update RustPython depend

src/catalog/src/information_schema/tables.rs, src/frontend/src/tests/instance_test.rs, src/frontend/src/tests/test_util.rs, tests/cases/standalone/common/system/information_schema.result, tests/cases/standalone/common/system/information_schema.sql
add `table_id` and `table_engine` to information_schema.TABLES
close #1355
=> feat: add table id and engine to information_schema.TABLES

src/common/datasource/src/error.rs, src/common/datasource/src/file_format.rs, src/common/datasource/src/file_format/csv.rs, src/common/datasource/src/file_format/json.rs, src/common/datasource/src/file_format/parquet.rs, src/common/datasource/src/object_store.rs, src/common/datasource/src/object_store/s3.rs, src/common/datasource/src/test_util.rs, src/frontend/src/statement/copy_table_from.rs, src/frontend/src/statement/copy_table_to.rs
- Implement parsing format from hashmap
- Split #1372 into small PRs, particularly the shared code, for not to block other feature PRs.
=> feat: implement parsing format from hashmap

.github/workflows/develop.yml, tests-integration/Cargo.toml, tests-integration/tests/http.rs
Prevent accident break of builtin dashboard
=> test: add integration case to check dashboard path

.github/workflows/release.yml
It might be stable after weeks (I hope 🫥
=> ci: enable test on release

src/datanode/src/sql/alter.rs, src/datanode/src/sql/drop_table.rs, src/table-procedure/src/alter.rs, src/table-procedure/src/drop.rs, src/table-procedure/src/lib.rs
This PR
- adds a procedure `DropTableProcedure` to the `table-procedure` crate
- supports dropping a table by procedure on datanode
- #286
=> feat: Drop table by procedure

src/catalog/src/remote/manager.rs, src/catalog/tests/mock.rs, src/meta-srv/src/error.rs, src/meta-srv/src/lib.rs, src/meta-srv/src/metadata_service.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/metasrv/builder.rs, src/meta-srv/src/mocks.rs
This pr mainly change: 
Default catalog and schema are created at Metasrv, instead of datanode.
close #1265
=> refactor: default catalog and schema are created at Metasrv

src/common/query/src/physical_plan.rs, src/table/src/table/numbers.rs, src/table/src/table/scan.rs, tests/cases/standalone/common/optimizer/order_by.result, tests/cases/standalone/common/optimizer/order_by.sql
Provide information regarding the output ordering in our `TableScan` plan to enable optimization of the `Sort` plan when feasible.
=> feat: expose output_ordering on scan plan

Cargo.lock, Cargo.toml, src/common/procedure-test/Cargo.toml, src/common/procedure-test/src/lib.rs, src/file-table-engine/Cargo.toml, src/file-table-engine/src/engine.rs, src/file-table-engine/src/engine/immutable.rs, src/file-table-engine/src/engine/procedure.rs, src/file-table-engine/src/engine/procedure/create.rs, src/file-table-engine/src/engine/procedure/drop.rs, src/file-table-engine/src/engine/tests.rs, src/mito/Cargo.toml, src/mito/src/engine/procedure.rs, src/mito/src/engine/procedure/alter.rs, src/mito/src/engine/procedure/create.rs, src/mito/src/engine/procedure/drop.rs, src/table/src/requests.rs
This PR implements procedures for the immutable file table engine:
- Adds `CreateImmutableFileTable` for creating a table
- Adds `DropImmutableFileTable` for dropping a table
- ImmutableFileTableEngine now implements the `TableEngineProcedure` trait
- Adds a `common-procedure-test` crate for common test utilities for procedures
- #286
=> feat: procedures for file table engine

src/datanode/src/sql/create.rs, src/frontend/src/expr_factory.rs, src/sql/src/lib.rs, src/sql/src/statements/create.rs, src/sql/src/util.rs
move stmt_options_to_table_options to query crate
#1010
=> refactor: refactor stmt_options_to_table_options

src/common/datasource/src/file_format/parquet.rs, src/common/datasource/src/file_format/tests.rs, src/object-store/src/lib.rs
Implement `DefaultParquetFileReaderFactory`. 
The upstream `ParquetExec` supports decoupling with `object_store::ObjectStore` using the `ParquetFileReaderFactory`. (However, `CsvExec` and `NdJsonExec` doesn't support the feature, and I checked the source code to implement similar features will be a little tricky)
- #1372 
- #1041
=> feat: implement ParquetFileReaderFactory

src/datanode/src/datanode.rs, src/datanode/src/error.rs, src/datanode/src/instance.rs, src/datanode/src/sql.rs, src/datanode/src/sql/alter.rs, src/datanode/src/sql/create.rs, src/datanode/src/sql/drop_table.rs, src/datanode/src/tests/test_util.rs, src/frontend/src/tests.rs, src/table-procedure/src/alter.rs, src/table-procedure/src/create.rs, src/table-procedure/src/drop.rs, src/table-procedure/src/error.rs, src/table/src/engine/manager.rs, src/table/src/test_util/mock_engine.rs
Add multi-engine support to the table engine manager. The `SqlHandler` now gets the engine procedure from the engine manager according to the engine type of a table.
The `TableEngineManager` now has an `engine_procedure()` method to get the `TableEngineProcedure` by name.
```rust
#[async_trait::async_trait]
pub trait TableEngineManager: Send + Sync {
fn engine_procedure(&self, name: &str) -> Result<TableEngineProcedureRef>;
}
```
We can use `with_engine_procedures()` to attach to the `MemoryTableEngineManager`.
```rust
/// Attach the `engine_procedures` to the manager.
pub fn with_engine_procedures(
mut self,
engine_procedures: HashMap<String, TableEngineProcedureRef>,
) -> …
```
=> feat: manage multiple engine procedure in the engine manager

src/cmd/src/frontend.rs, src/cmd/src/standalone.rs, src/frontend/src/instance.rs
Remove plugins from `build_servers` as instance already holds plugins
=> refactor: remove redundant plugins argument

src/common/datasource/src/error.rs, src/common/datasource/src/file_format.rs, src/common/datasource/src/file_format/parquet.rs, src/common/datasource/src/file_format/tests.rs, src/common/datasource/src/lib.rs, src/frontend/src/statement.rs, src/sql/src/error.rs, src/sql/src/parsers/copy_parser.rs, src/sql/src/statements/copy.rs, src/table/src/requests.rs
Replace the `Copy` Format with `datasource` Format.
The prelude of #1305,  after merging this, some duplicated code in the #1424  also can be refactored
- #1305 
- #1424
=> refactor: replace Copy Format with datasource Format

src/meta-srv/src/election/etcd.rs, src/meta-srv/src/metasrv.rs
Just add a log to avoid panic when metasrv leader step down.
And when it has been a leader before and the lease renewal fails, a step-down message will be sent out.
=> fix: add log on leader stepdown

config/datanode.example.toml, config/standalone.example.toml, src/catalog/src/error.rs, src/catalog/tests/local_catalog_tests.rs, src/cmd/src/datanode.rs, src/cmd/src/standalone.rs, src/datanode/src/datanode.rs, src/datanode/src/instance.rs, src/datanode/src/instance/sql.rs, src/datanode/src/sql.rs, src/datanode/src/sql/alter.rs, src/datanode/src/sql/create.rs, src/datanode/src/sql/drop_table.rs, src/datanode/src/tests/test_util.rs, src/frontend/src/error.rs, src/frontend/src/tests.rs, src/mito/src/engine/procedure/create.rs, src/mito/src/engine/procedure/drop.rs, src/table-procedure/src/alter.rs, src/table-procedure/src/error.rs, tests-integration/src/test_util.rs, tests-integration/tests/http.rs, tests/cases/distributed/alter/rename_table.result, tests/cases/standalone/alter/rename_table.result, tests/cases/standalone/common/catalog/schema.result, tests/conf/datanode-test.toml.template, tests/conf/standalone-test.toml.template, tests/runner/src/env.rs
This PR enables the procedure framework and uses procedures to perform DDL.
It fixes all failed tests after switching to the procedure framework:
- Unifies the error message of table not found
- Fixes table options not persisted while using the procedure to create a table
- Allow dropping a table that isn't in the engine
- Fix temp dir drops before the test finishes (unrelated)
Remove create_table/drop_table/alter_table from `TableEngine` trait as we have `TableEngineProcedure` to perform DDL.
- #286
=> feat: Switch to the procedure framework

Cargo.lock, src/client/Cargo.toml
Client still dependent on substrait v0.4. This PR update it to v0.7
=> chore(deps): update substrait dep in client

src/object-store/src/cache_policy.rs, tests-integration/src/test_util.rs, tests-integration/tests/main.rs
Fix #1466  and add integration tests for s3 storage with cache enabled.
=> fix: object store caching bug, #1466

Cargo.lock, src/common/telemetry/src/panic_hook.rs, src/frontend/src/catalog.rs, src/meta-srv/Cargo.toml, src/meta-srv/src/metadata_service.rs, src/meta-srv/src/metrics.rs, src/servers/src/http/handler.rs, src/servers/src/lib.rs, src/servers/src/metrics.rs, src/servers/src/mysql/server.rs
This patch adds:
- timer for http sql/promql apis
- metrics for catalog/schema creation on meta
- counter for panic hook
- log level improvement for mysql handler, change non-fatal error to `warn`
=> feat: improve metrics and log level

Cargo.lock, src/catalog/src/error.rs, src/script/Cargo.toml, src/script/src/error.rs, src/script/src/manager.rs, src/script/src/python/engine.rs, src/script/src/python/error.rs, src/script/src/python/utils.rs, src/script/src/table.rs, src/servers/tests/mod.rs
Recompile and re-register scripts on reboot
register scripts in create `scripts` table's callback
currently insert new row into `scripts` table wouldn't trigger compile and register of new python script, so sqlness tests can't be done yet, might impl it later
=> fix: recompile&register scripts as UDF on reboot

Cargo.lock, src/object-store/Cargo.toml, src/storage/src/sst/stream_writer.rs
Bump opendal to 0.33 https://github.com/apache/incubator-opendal/releases
=> feat: bump opendal to 0.33

scripts/fetch-dashboard-assets.sh, src/servers/build.rs
Also remove the output from the build script and only print the output on failure
Download assets to cargo output dir and only print message on failure.
Now the error message looks like this
```bash
error: failed to run custom build command for `servers v0.2.0 (/xxx/greptime/greptimedb/src/servers)`
Caused by:
process didn't exit successfully: `/xxx/greptime/greptimedb/target/debug/build/servers-8dc45d9bbbf1d1ce/build-script-build` (exit status: 101)
--- stderr
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2066k  100 …
```
=> build: Download assets to cargo output dir

src/object-store/tests/object_store_test.rs, tests-integration/README.md, tests-integration/src/test_util.rs
=> fix: add s3 region info

src/common/time/src/util.rs, src/servers/src/grpc/prom_query_gateway.rs, src/servers/src/prom.rs
- Fill the current server time if it's not specified in instant query
- Remove hard-coded result type
It's tested locally:
```
❯ curl --location --request POST 'http://localhost:4004/api/v1/query?query=system_metrics' \
--header 'Content-Type: application/x-www-form-urlencoded'
{"status":"success","data":{"resultType":"instant vector","result":[]}}%
```
Closes #1471 
Closes #1472
=> feat: use server time if it's not specified

src/cmd/Cargo.toml
Disable default dashboard feature
=> fix: disable dashboard

src/file-table-engine/src/engine/immutable.rs, src/mito/src/engine.rs, src/mito/src/engine/procedure.rs, src/mito/src/engine/procedure/alter.rs, src/mito/src/engine/procedure/create.rs, src/mito/src/engine/procedure/drop.rs, src/mito/src/engine/tests.rs, src/mito/src/table.rs
Combines the original and procedure's implementation
- Adds a struct `TableCreator` to create a mito table. Both the procedure and the engine use this creator
- Adds `MitoTable::alter_regions()` and `MitoTable::info_and_op_for_alter()` to reuse code
- Simplifies drop table procedure by calling the engine inner to drop the table
- #286
=> feat(mito): Combine the original and procedure's implementation

config/datanode.example.toml, config/standalone.example.toml, src/cmd/src/datanode.rs, src/common/procedure/src/local/runner.rs, src/common/procedure/src/store.rs, src/datanode/src/datanode.rs, src/datanode/src/instance.rs, src/datanode/src/tests/test_util.rs, src/frontend/src/tests.rs, tests-integration/src/test_util.rs
Remove `store` from procedure config and reuse the object store of the storage engine as the state store of the procedure framework.
The procedure store will use `procedure` as key prefix to store data.
- #286
=> feat: Remove store from procedure config

src/servers/src/grpc/handler.rs, src/servers/src/grpc/prom_query_gateway.rs, src/servers/src/http/authorize.rs, src/servers/src/http/handler.rs, src/servers/src/http/influxdb.rs, src/servers/src/http/prometheus.rs, src/servers/src/metrics.rs, src/servers/src/mysql/handler.rs, src/servers/src/mysql/server.rs, src/servers/src/opentsdb/handler.rs, src/servers/src/postgres/auth_handler.rs, src/servers/src/postgres/handler.rs, src/servers/src/postgres/server.rs, src/session/src/context.rs
This patch adds metrics for various protocol interfaces including;
- prometheus remote read/writes
- influxdb writes
- opentsdb writes
- mysql/postgres
- connections
- queries
- prepared statements
- grpc
- database/flight requests
- prom requests
- authentication failures
=> feat: add metrics for protocol interfaces

src/storage/src/error.rs, src/storage/src/manifest/impl_.rs, src/storage/src/manifest/region.rs, src/storage/src/manifest/storage.rs, src/store-api/src/manifest/storage.rs
The checkpoint GC task also deletes the file with the last version. To avoid the last checkpoint file being deleted, we add a `keep_last_checkpoint` option to `delete_until`
This PR also adjusts the level of the log when do_checkpoint() is unable to delete manifest files as it is an expected behavior.
- fixes #1490
=> fix: checkpoint GC task also deletes the file with the last version

Cargo.lock, src/servers/Cargo.toml
Update pgwire to 0.14 with tcp_nodelay turned on by default.
=> feat: update pgwire to 0.14

src/catalog/src/information_schema.rs, src/catalog/src/information_schema/columns.rs, src/catalog/src/information_schema/tables.rs, src/frontend/src/tests/instance_test.rs, tests/cases/standalone/common/system/information_schema.result, tests/cases/standalone/common/system/information_schema.sql
Fixes #1390 
This patch add a very basic `information_schema.columns` view support in order to fit grafana mysql plugin's query builder.
=> feat: add support for information_schema.columns

Cargo.lock, src/datanode/src/error.rs, src/datanode/src/instance.rs, src/object-store/Cargo.toml, src/object-store/src/cache_policy.rs, src/object-store/tests/object_store_test.rs
Main changes:
* Recover LRU cache keys from local file cache path.
* Set `atomic_write_dir` for local file cache.
* Fixed reading cache file.
* Fixed writing cache file.
Fix #1458
=> fix: object store cache bug

src/common/time/src/timestamp.rs, src/servers/src/mysql/writer.rs
=> fix: respect MySQL timestamp format

src/query/src/sql/show.rs, src/sql/src/statements/create.rs, tests/cases/standalone/show/show_create.result
When running `show create table` on an external table, this PR fixes `greptimedb` showing `IMMUTABLE_TABLE_META`.
close #1459
=> fix: incorrect show create table output

CONTRIBUTING.md, src/catalog/src/remote/manager.rs, src/common/catalog/src/consts.rs
fix max_table_id bug and update link in CONTRIBUTING.md
close #1513
=> fix: wrong max_table_id log in remote catalog manager

Cargo.lock, src/catalog/Cargo.toml, src/catalog/src/lib.rs, src/catalog/src/local/manager.rs, src/catalog/src/local/memory.rs, src/catalog/src/metrics.rs, src/catalog/src/remote/manager.rs, src/common/catalog/src/lib.rs, src/session/src/context.rs, tests-integration/tests/http.rs
This patch adds catalog/schema/table count as metrics.
=> feat: add catalog/schema/table count as catalog metrics

src/servers/src/error.rs, src/servers/src/grpc/prom_query_gateway.rs, src/servers/src/prom.rs, tests-integration/tests/grpc.rs
Fix the query result of prometheus compatible interfaces. Results from `query` and `query_range` should use different result type and different fields for data
=> fix: vector and matrix in Prometheus use different field

.cargo/config.toml, .github/workflows/apidoc.yml, .github/workflows/develop.yml, .github/workflows/release.yml, rust-toolchain.toml, src/common/recordbatch/src/util.rs, src/servers/src/auth/user_provider.rs, src/store-api/src/manifest/action.rs, src/table-procedure/src/lib.rs
Bump rust toolchain to 2023-05-23, inspired by https://www.reddit.com/r/rust/comments/136z613/sudden_99_build_time_improvement_going_from_1661/ This version is rust 1.71, which uses LLVM 16
Cold build in my env has slightly improved, but most of the time is occupied by non-rust deps (like before). 
After: 
Before:
=> chore(toolchain): update rust-toolchain to 2023-05-03

src/catalog/src/system.rs, src/mito/src/table.rs, src/store-api/src/storage.rs, src/store-api/src/storage/region.rs, src/table/src/lib.rs, src/table/src/stats.rs, src/table/src/table.rs, src/table/src/test_util/memtable.rs
Add some statistics for `Table` trait, and impl one for `MemTable`, this should be useful for future opt with tables.
Add some statistics that similiar to DataFusion's statistics.
#1431 #1473
=> feat: table metrics

src/catalog/src/information_schema/columns.rs, src/common/catalog/src/consts.rs, src/frontend/src/tests/instance_test.rs, src/query/src/sql.rs, tests/cases/standalone/common/system/information_schema.result, tests/cases/standalone/common/system/information_schema.sql
This patch adds semantic type column to information_schema.columns
=> feat: add semantic_type to information_schema.columns

src/meta-srv/src/keys.rs, src/meta-srv/src/selector/load_based.rs
Problems encountered:
When starting greptimedb cluster,  frontend will report an error, “no active datanode”. In addition metasrv uses loadbase selector. 
In the current loadbase selector implementation, when the region count of a datanode cannot be obtained, we will exclude the datanode.
When frontend starts, some system tables need to be created. At this time, metasrv does not receive the heartbeat of datanode. So, frontend report an error "no active datanode".
This PR mainly fix this problem.
When the region number of the datanode cannot be obtained and the datanode alive, we give the node largest region count and lower its priority.
=> fix: no active datanode when frontend start

src/meta-srv/src/keys.rs
We have cached the latest 10 heartbeat messages for each node as Stat. When we need to obtain the most accurate information, we should retrieve it from the newest Stat.
=> fix: the latest number of regions

src/common/procedure/src/local.rs, src/common/procedure/src/local/runner.rs, src/common/procedure/src/store.rs, src/common/procedure/src/store/state_store.rs, src/meta-srv/src/procedure/state_store.rs
This PR cleans the procedure's state in `ProcedureStore` and memory after it is done
- Add `delete_procedure()` method to `ProcedureStore`
- After a root procedure is done, the runner cleans all the state files related to this procedure and its children
- Removes the metadata in memory after `META_TTL`. When we submit a procedure to the manager or query a procedure's state, the manager tries to clean the outdated metadata
- Cleans finished procedures during recovery
- #1509
=> feat: clean procedure's state after it is done

src/common/runtime/src/error.rs, src/common/runtime/src/lib.rs, src/common/runtime/src/repeated_task.rs, src/log-store/src/raft_engine/log_store.rs, src/storage/src/manifest/impl_.rs
Some refactor:
- Remove async from start(), also make start() concurrent safe
- Cancel task in drop
- Allow TaskFunction::call taking `&mut self` so we could maintain state in the TaskFunction
=> refactor: remove unnecessary async from RepeatedTask::start

src/common/datasource/src/compression.rs, src/common/datasource/src/file_format/csv.rs, src/common/datasource/src/file_format/json.rs, src/common/datasource/src/file_format/tests.rs, src/common/datasource/src/test_util.rs
Make `CompressionType` follow the style of the guide
=> chore(datasource): make CompressionType follow the style of the guide

src/query/src/lib.rs, src/query/src/query_engine/options.rs, src/table-procedure/src/lib.rs
This patch allows cross schema query on information_schema.
=> feat: add information_schema as exception of cross schema check

src/meta-srv/src/handler/collect_stats_handler.rs, src/meta-srv/src/handler/persist_stats_handler.rs, src/meta-srv/src/handler/response_header_handler.rs
If the heartbeat is a mailbox message, it may have no other valid information, so we don't need to collect stats.
=> feat: ignore mailbox message into stat

src/servers/src/http.rs, src/servers/src/http/dashboard.rs
fix #1552 
Now "/dashboard", "/dashboard/" and "/dashboard/query" all works as expected. However, "/dashboard/not/existed" still returns 404.
=> fix: refreshing Dashboard returns 404

src/servers/src/prom.rs
When I use  `curl '127.0.0.1:4004/api/v1/query_range?query=up&start=0&end=100&step=10s'` query a multi-field table which have NULL value. I get a error of `unwrap()` a `Option`. the table look like
```
mysql> select * from up;
+------+------+--------+---------------------+
| host | cpu  | memory | ts                  |
+------+------+--------+---------------------+
| h1   | 66.6 |   1024 | 1970-01-01 08:00:00 |
| h1   | 66.6 |   2048 | 1970-01-01 08:00:02 |
| h1   | 66.6 |   4096 | 1970-01-01 08:00:05 |
| h3   | NULL | 8764.8 | 1970-01-01 08:00:15 |
| h3   | NULL | 754.99 | 1970-01-01 08:00:20 |
| h3   | NULL |   64.8 | 1970-01-01 08:00:30 | …
```
=> fix:  unwrap() `None` in NULL value exist multi-field table during prometheus `query_range`

src/storage/benches/memtable/util/mod.rs, src/storage/benches/memtable/util/regiondesc_util.rs, src/storage/benches/wal/util/mod.rs, src/storage/src/compaction/writer.rs, src/storage/src/file_purger.rs, src/storage/src/manifest/action.rs, src/storage/src/memtable/btree.rs, src/storage/src/memtable/inserter.rs, src/storage/src/memtable/tests.rs, src/storage/src/metadata.rs, src/storage/src/region/tests.rs, src/storage/src/region/tests/alter.rs, src/storage/src/region/tests/basic.rs, src/storage/src/region/tests/close.rs, src/storage/src/region/tests/compact.rs, src/storage/src/region/tests/flush.rs, src/storage/src/sst/parquet.rs, src/storage/src/test_util/descriptor_util.rs, src/storage/src/test_util/read_util.rs, src/storage/src/version.rs, src/storage/src/write_batch.rs, src/storage/src/write_batch/codec.rs, src/store-api/src/storage/consts.rs, src/store-api/src/storage/descriptors.rs
This PR removes the reserved column `__version` so that we can always assume the timestamp index is the last column of row key. 
The `__version` column is now only used in tests and users cannot enable this column when creating tables, so it's not a breaking change and shall not cause data corruption.
- #233
=> refactor: remove version column

Cargo.lock, src/api/Cargo.toml, src/datanode/src/heartbeat.rs, src/datanode/src/instance.rs, src/datanode/src/mock.rs, src/frontend/src/error.rs, src/frontend/src/heartbeat.rs, src/frontend/src/instance.rs, src/frontend/src/lib.rs, src/meta-client/examples/lock.rs, src/meta-client/examples/meta_client.rs, src/meta-client/src/client.rs, src/meta-client/src/client/heartbeat.rs, src/meta-client/src/client/lock.rs, src/meta-client/src/client/router.rs, src/meta-client/src/client/store.rs, src/meta-client/src/mocks.rs, src/meta-srv/Cargo.toml, src/meta-srv/src/error.rs, src/meta-srv/src/handler.rs, src/meta-srv/src/handler/response_header_handler.rs, src/meta-srv/src/service/heartbeat.rs, tests-integration/src/tests.rs
This pr mainly support the heartbeat mechanism between frontend and meta.
=> feat: support frontend-meta heartbeat

.github/workflows/release.yml, Makefile
I noticed from the discussion on https://github.com/GreptimeTeam/greptimedb/discussions/1570 that this could be the cause of the test failure in the release CI. This PR
- Change Makefile to use nextest
- Install nextest in corresponding jobs
I'm afraid our unit test can only run by nextest for now, due to those global variables.
=> fix: uses nextest in the Release CI

src/datanode/src/instance/sql.rs, src/frontend/src/statement/tql.rs, src/promql/src/planner.rs, src/query/src/error.rs, src/query/src/parser.rs, src/sql/src/parsers/tql_parser.rs, src/sql/src/statements/tql.rs, tests-integration/src/tests/promql_test.rs, tests/cases/standalone/common/tql/analyze.result, tests/cases/standalone/common/tql/analyze.sql, tests/cases/standalone/common/tql/explain.result, tests/cases/standalone/common/tql/explain.sql
Add support for `TQL EXPLAIN`/ `TQL ANALYZE` clauses
- `TQL EXPLAIN` (similar to `EXPLAIN` from `SQL`) doesn't execute the query but tells how the query would be executed.
- `TQL ANALYZE`(similar to `ANALYZE` from `SQL`) executes the plan and tells the detailed per-step execution time.
- The implementation introduces a wrapper for Explain or Analyze node over the existing logical plan. 
https://github.com/GreptimeTeam/greptimedb/issues/986
=> feat(tql): add initial implementation for explain & analyze

src/common/procedure/src/error.rs, src/common/procedure/src/local.rs, src/common/procedure/src/procedure.rs, src/datanode/src/error.rs, src/datanode/src/instance.rs, src/table-procedure/src/test_util.rs
This PR makes a `RepeatedTask` invoke the `remove_outdated_meta` method.
#1509
=> feat: make RepeatedTask invoke remove_outdated_meta method

Cargo.lock, src/cmd/src/datanode.rs, src/datanode/src/datanode.rs, src/datanode/src/instance.rs, src/mito/Cargo.toml, src/mito/src/config.rs, src/mito/src/engine.rs, src/mito/src/engine/procedure/create.rs, src/mito/src/manifest.rs, src/mito/src/table.rs, src/storage/src/config.rs, src/storage/src/engine.rs, src/storage/src/manifest.rs, src/storage/src/manifest/impl_.rs, src/storage/src/manifest/region.rs, src/storage/src/manifest/storage.rs, src/storage/src/region/tests.rs, src/storage/src/test_util/config_util.rs
Expose ManifestLogStorage compress configuration to user
Manifest log now supports compression but it is not enabled by default. I hope to expose the option to users whether to enable Manifest log compression.
expose a config `use_compress` to user whether to use Manifest log compression.
```toml
[storage.manifest]
checkpoint_on_startup = true
use_compress = true # false by default
```
Closes https://github.com/GreptimeTeam/greptimedb/issues/1394
Follow-up of https://github.com/GreptimeTeam/greptimedb/pull/1497
=> feat: support user config manifest compression

src/mito/src/engine.rs, src/mito/src/engine/tests.rs
Remove region number validation.
=> fix: remove region number validation

src/common/time/src/timestamp.rs, src/datatypes/src/value.rs, src/storage/benches/memtable/mod.rs, src/storage/src/compaction/picker.rs, src/storage/src/compaction/writer.rs, src/storage/src/memtable.rs, src/storage/src/memtable/btree.rs, src/storage/src/memtable/inserter.rs, src/storage/src/memtable/tests.rs, src/storage/src/memtable/version.rs, src/storage/src/schema/region.rs, src/storage/src/schema/store.rs
This PR:
- add `stats` method to `Memtable` trait to retrieve memtable's statistical info
- add `timestamp_index` method to `RegionSchema` and `StoreSchema`, these two schema should by all means be aware of timestamp column index, which is the last column in the row key
- for `KeyValues` struct, move timestamp out of `row_key` field to a separate field.
This is a prerequisite work for infering time windows from memtables and SST files so that we can precisely determine the scan window in TopK scenario.
=> feat: memtable stats

src/cmd/src/datanode.rs, src/cmd/src/frontend.rs, src/cmd/src/metasrv.rs, src/cmd/src/options.rs, src/cmd/src/standalone.rs, src/datanode/src/datanode.rs, src/frontend/src/frontend.rs
1. Use `config-rs` to support parsing env list, for example, `GREPTIMEDB_METASRV__META_CLIENT_OPTIONS__METASRV_ADDRS=127.0.0.1:3001,127.0.0.1:3002`;
Passing [`list_parse_keys`](https://github.com/zyy17/greptimedb/blob/refactor/support-parse-env-list/src/datanode/src/datanode.rs#L286) seems ugly since config-rs limit it. Using some derive will be better. I will try to add the function to upstream later.
3. Use `multiple = true` in clap derive and remove duplicated string list parsing;
(btw, maybe the name `metasrv_addrs` is better than `metasrv_addr` in cli options.)
- Summarize your change …
=> refactor: support parsing env list

src/meta-srv/src/error.rs, src/meta-srv/src/handler.rs, src/meta-srv/src/handler/check_leader_handler.rs, src/meta-srv/src/metasrv/builder.rs, src/meta-srv/src/sequence.rs, src/meta-srv/src/service/heartbeat.rs
1. Out of range checking in Sequence
2. use `message_id = 0` to mark a Message as a one-way call
3. Add log in CheckLeaderHandler
=> fix: sequence out of range

src/catalog/src/lib.rs
add `table engine` to attrs in regionStat when datanode sends heartbeat to Metasrv.
https://github.com/GreptimeTeam/greptimedb/issues/1583
=> refactor: add "table engine" to datanode heartbeat.

Cargo.lock, src/common/procedure-test/src/lib.rs, src/common/procedure/src/procedure.rs, src/mito/src/engine/procedure/create.rs, src/mito/src/table.rs, src/table-procedure/Cargo.toml, src/table-procedure/src/create.rs, src/table-procedure/src/test_util.rs
Open the created table in the `CreateTable::RegisterCatalog` state so the procedure can execute correctly after recovery.
To test this case, it adds the following helper functions to execute the procedure without the procedure manager
- execute_parent_procedure
- execute_procedure_once
fix #1614
=> fix(table-procedure): Open table in RegisterCatalog state

config/datanode.example.toml, config/standalone.example.toml, src/datanode/src/datanode.rs, src/storage/src/config.rs, src/storage/src/engine.rs, src/storage/src/flush.rs, src/storage/src/flush/picker.rs, src/storage/src/flush/scheduler.rs, src/storage/src/memtable.rs, src/storage/src/memtable/btree.rs, src/storage/src/memtable/inserter.rs, src/storage/src/memtable/version.rs, src/storage/src/metrics.rs, src/storage/src/region.rs, src/storage/src/region/tests/compact.rs, src/storage/src/region/tests/flush.rs, src/storage/src/region/writer.rs, src/storage/src/test_util/config_util.rs, src/storage/src/test_util/flush_switch.rs, src/store-api/src/storage/region.rs
This PR adds a new option `global_write_buffer_size` that triggers flush when the write buffer size of all regions is larger than it. This feature is disabled by default.
The whole design is similar to RocksDB's [WriteBufferManager](https://github.com/facebook/rocksdb/blob/5fc57eec2b44337289f25c1b5687beb54ad709a2/include/rocksdb/write_buffer_manager.h#L37), except that we don't stall the write thread when the global write buffer is full.
It adds some methods to `FlushStrategy` so the strategy can track the total memory usage. The `should_flush` method returns whether we should flush the current region or other regions in the engine.
```rust
pub trait FlushStrategy: Send + …
```
=> feat: Trigger flush based on global write buffer size

src/cmd/src/cli.rs, src/cmd/src/datanode.rs, src/cmd/src/frontend.rs, src/cmd/src/metasrv.rs, src/cmd/src/standalone.rs, src/common/telemetry/src/logging.rs, src/meta-client/src/lib.rs
Fixes #1628
This patch applies `RUST_LOG` environment variable patterns to our logging level configuration items and how we interpret `RUST_LOG`. Now you can configure greptime by `./greptime --log-level info,opendal=debug` or `RUST_LOG=info,opendal=debug greptime`
In previous builds, if you provide `--log-level=info` we will still add our built-in rules to configure 3rd-party libraries like opendal to info, hyper to warn. In this change, our built-in rules are applied only when no configuration provided from cli/env/file or `RUST_LOG` envvar. 
For example, if you run `greptime --log-level=info`, 
- in previous builds, it won't log hyper's info messages 
- in this build, it …
=> feat: more configurable logging levels

Cargo.lock, src/catalog/Cargo.toml, src/catalog/src/error.rs, src/catalog/src/lib.rs, src/catalog/src/metrics.rs, src/catalog/src/remote.rs, src/catalog/src/remote/client.rs, src/catalog/tests/mock.rs, src/catalog/tests/remote_catalog_tests.rs, src/cmd/src/cli/repl.rs, src/datanode/src/instance.rs, src/frontend/src/catalog.rs, src/frontend/src/instance.rs, src/frontend/src/instance/distributed.rs
This pr mainly add cache for catalog kv backend. 
After this pr is merged, the load of meta will be reduced.
`Datanode` and `Frontend` invalidate catalog kv cache differently. 
- Datanode only needs to maintain a local cache. `RemoteCatalogManager` can manage the cache itself.
- Frontend cache is a distributed cache and the instruction to invalidate the cache is issued by meta. So FrontedCatalogManager needs to provide an InvalidCache interface.
Take `alter table` as an example:
alter table to datanode   -> datanode.kv_backend.del()/set() (The cache invalidation will be called inside the del/set method)
alter table in procedure -> metasrv broadcast invalidate cache …
=> feat: add cache for catalog kv backend

src/meta-srv/src/error.rs, src/servers/src/error.rs
#1624 removes some of the error we use for custom error map. This pr mainly adds two error back with `#[allow(dead_code)]` to prevent future mis-delete.
=> chore: add boxed error for custom error map

src/common/telemetry/src/logging.rs
Previous PR https://github.com/GreptimeTeam/greptimedb/pull/1629 seems ignored the filters for testing logs, making them too verbose. I think we can move the filters to testing logs only.
=> refactor: set the filters for testing logs

src/servers/src/error.rs, src/servers/src/http.rs, src/servers/src/metrics.rs, src/servers/src/prom.rs
This PR
- Adds a common metrics layer for HTTP servers
- log error returned by HTTP handlers
=> feat(servers): Add metrics based on axum's example

docker/Dockerfile
When I use docker build to build the image, I get an error that pip is missing. 
Add install python3-pip in Dockerfile.
Fixes: #1643
=> fix: install python3-pip in Dockerfile

Cargo.lock, src/frontend/Cargo.toml, src/frontend/src/metrics.rs, src/frontend/src/table/insert.rs
Add a counter to track ingested rows
=> feat: add metrics for ingested row count

Cargo.lock, Cargo.toml, src/common/telemetry/Cargo.toml, src/common/telemetry/src/metric.rs, src/meta-srv/src/service/router.rs, src/meta-srv/src/service/store/etcd.rs, src/servers/Cargo.toml, src/servers/src/grpc/handler.rs, src/servers/src/grpc/prom_query_gateway.rs, src/servers/src/http/handler.rs, src/servers/src/http/influxdb.rs, src/servers/src/http/prometheus.rs, src/servers/src/mysql/handler.rs, src/servers/src/postgres/handler.rs
The `histogram!` macro actually calls `register_histogram` to get a `Histogram` struct and record value to it.
https://github.com/metrics-rs/metrics/blob/c15c0ed663685251330213182c72ee303ec698b0/metrics-macros/src/lib.rs#L248-L271
This PR creates the `Histogram` struct and keeps it in the `Timer` to avoid the `Timer` allocate the `Vec` and clone the labels if possible.
It also downgrades the `metrics-process` crate to keep using the same metrics version as OpenDAL.
=> refactor: Holds histogram in the timer to avoid clone labels if possible

src/frontend/src/catalog.rs, src/frontend/src/instance/distributed.rs
This pr mainly reduce the number of requests for meta.
=> chore: reduce the number of requests for meta

src/meta-srv/src/handler.rs
=> refactor: move code out of loop

Cargo.lock, src/common/time/src/range.rs, src/common/time/src/timestamp.rs, src/datatypes/src/data_type.rs, src/datatypes/src/types/timestamp_type.rs, src/storage/Cargo.toml, src/storage/src/lib.rs, src/storage/src/memtable.rs, src/storage/src/memtable/btree.rs, src/storage/src/memtable/inserter.rs, src/storage/src/read/windowed.rs, src/storage/src/region/tests.rs, src/storage/src/window_infer.rs
Window inferer is used to infer a set of time windows that can be used to optimize queries if:
- timestamp column is the left-most column in ORDER-BY clause
- queries have explicit time window selection.
This PR defines a `WindowInference` trait and add a plain implementation that simply find the minimum time span of all SST files and memtables, matches that window into a set of predefined orthodox time windows and generate time windows for all SST files and memtables according to the infered time window.
=> feat: window inferer

src/meta-srv/src/handler.rs, src/meta-srv/src/service/mailbox.rs
In some cases, we need to send broadcast messages, such as to notify all frontend nodes that some metadata cache has expired, these broadcast messages should not wait for return values, even if the notification fails,（The subsequent process will allow the frontend to correct its cache, so this broadcast message is just an optimization and can tolerate not being received), we should pay more attention to efficient broadcasting.
So I added the broadcast feature to Mailbox, no need to generate message_id (using reserved 0 to represent one-way message), no need …
=> feat: broadcast with mailbox

src/storage/src/region/tests.rs, tests/cases/distributed/common
- CI breaks due to #1639 
- Restore the removed symlink to sqlness common cases in #1577
=> fix: clippy warning

src/meta-srv/src/lock.rs, src/meta-srv/src/lock/keys.rs, src/meta-srv/src/lock/memory.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/metasrv/builder.rs, src/meta-srv/src/procedure/region_failover.rs, src/meta-srv/src/procedure/region_failover/activate_region.rs, src/meta-srv/src/procedure/region_failover/deactivate_region.rs, src/meta-srv/src/procedure/region_failover/failover_start.rs, src/meta-srv/src/procedure/region_failover/update_metadata.rs, src/meta-srv/src/service/lock.rs, src/meta-srv/src/test_util.rs, tests-integration/tests/region_failover.rs
Using distributed lock to guard against the concurrent updating of table metadatas in region failover procedure.
#1126
=> feat: update table metadata in lock

src/api/src/helper.rs, src/common/error/src/status_code.rs, src/servers/src/error.rs, src/servers/src/grpc/handler.rs, src/servers/src/http.rs, src/servers/src/metrics.rs
Add `type` and `status` to `greptime_servers_grpc_db_request_elapsed` metric
```
greptime_servers_grpc_db_request_elapsed{code="public",type="query.sql",status="Success",quantile="0"} 0.001190166
greptime_servers_grpc_db_request_elapsed{code="public",type="query.sql",status="Success",quantile="0.5"} 0.0011901213200353528
greptime_servers_grpc_db_request_elapsed{code="public",type="query.sql",status="Success",quantile="0.9"} 0.0011901213200353528
greptime_servers_grpc_db_request_elapsed{code="public",type="query.sql",status="Success",quantile="0.95"} 0.0011901213200353528
greptime_servers_grpc_db_request_elapsed{code="public",type="query.sql",status="Success",quantile="0.99"} …
```
=> feat: Add request type and result code to grpc metrics

src/common/meta/src/instruction.rs, src/datanode/src/heartbeat/handler/close_region.rs, src/datanode/src/heartbeat/handler/open_region.rs, src/datanode/src/tests.rs, src/frontend/src/heartbeat/handler/tests.rs, src/meta-srv/src/error.rs, src/meta-srv/src/handler.rs, src/meta-srv/src/handler/failure_handler.rs, src/meta-srv/src/handler/failure_handler/runner.rs, src/meta-srv/src/lock/keys.rs, src/meta-srv/src/procedure/region_failover.rs, src/meta-srv/src/procedure/region_failover/invalidate_cache.rs, src/meta-srv/src/procedure/region_failover/update_metadata.rs, src/meta-srv/src/sequence.rs, src/meta-srv/src/service/mailbox.rs, tests-integration/tests/region_failover.rs
Add invalidate cache step.
```
///                       ┌───────────────────┐
///                       │RegionFailoverStart│
///                       └─────────┬─────────┘
///                                 │
///                                 │ Selects a candidate(Datanode)
///                  ┌─────────┐    │ to place the failed region
///                  │         │    │
///  If replied with │     ┌───▼────▼───────┐
///  "Close region   │     │DeactivateRegion│
///  failed"         │     └───┬────┬───────┘
///                  │         │    │
///                  └─────────┘    │ Sends "Close Region" request
///                                 │ to the failed …
```
=> feat: add invalidate cache step

src/meta-srv/src/handler/failure_handler.rs, src/table/src/engine.rs
1. Acquire `table_id` from `region_id`
close #1566
=> feat: acquire table_id from region_id

Cargo.lock, benchmarks/src/bin/nyc-taxi.rs, src/api/Cargo.toml, src/client/examples/logical.rs, src/common/grpc-expr/src/alter.rs, src/common/grpc-expr/src/insert.rs, src/datanode/src/instance/grpc.rs, src/datanode/src/server/grpc.rs, src/frontend/src/catalog.rs, src/frontend/src/expr_factory.rs, src/frontend/src/instance/distributed.rs, src/meta-srv/src/service/router.rs, src/servers/src/http/admin.rs, src/table/src/engine.rs, tests-integration/src/grpc.rs, tests-integration/tests/grpc.rs
Update greptime-proto to latest.
It rename `region_id` in some exprs to `region_number`, which is the correct name.
=> refactor: update proto and rename incorrect region_id fields

Cargo.lock, src/datanode/Cargo.toml, src/datanode/src/store.rs, src/object-store/Cargo.toml, src/object-store/src/layers/lru_cache.rs
This PR will bump OpenDAL to v0.36
All changes could be found here: https://opendal.apache.org/docs/rust/opendal/docs/changelog/index.html
Related to https://github.com/GreptimeTeam/greptimedb/pull/1677
=> chore: Bump OpenDAL to v0.36

src/mito/src/table.rs, src/storage/src/chunk.rs, src/storage/src/lib.rs, src/storage/src/read/windowed.rs, src/storage/src/region/tests.rs, src/storage/src/snapshot.rs, src/storage/src/window_infer.rs
This PR brigdges order-rules with windowed reader. Now we can infer scan windows by order options.
If The first column in order-by clause is timestamp, we can optimize it into a windowed table scan so that it can terminate as soon as we found enough records.
#1286
=> feat: adapt window reader to order rules

config/datanode.example.toml, config/standalone.example.toml, src/cmd/src/frontend.rs, src/cmd/src/standalone.rs, src/datanode/src/datanode.rs, src/storage/src/config.rs, src/storage/src/engine.rs
This PR adds an option `global_ttl` to the `StorageConfig` so users can configure a global TTL for all tables on the current machine.
If a table already has a TTL specified in table options, the storage engine uses that TTL. Otherwise, the `global_ttl` takes effect.
The `global_ttl` is disabled (set to `None`) by default.
=> feat: Add a global TTL option for all tables

src/common/procedure/src/error.rs, src/table-procedure/src/alter.rs, src/table-procedure/src/create.rs, src/table-procedure/src/drop.rs, src/table-procedure/src/error.rs
This PR prints the source error in the error variant `SubprocedureFailed`. It also moves this variant to `common_procedure::error::Error` and shortens the final error message.
=> fix: Print source error in subprocedure failure message

Cargo.lock, src/cmd/Cargo.toml, src/cmd/build.rs, src/cmd/src/bin/greptime.rs
Adds metric `greptime_app_version`
```
greptime_app_version{short_version="0.2.0",version="greptimedb-feat/more-metrics-fc623b5"} 1
```
The version contains the app name, the branch name, and the git commit. The example above doesn't have a short version. But in our formal release build, the branch (tag) name will contain a short version.
=> feat: Add app version metric

Cargo.lock, src/meta-srv/src/procedure/region_failover.rs, tests-integration/Cargo.toml, tests-integration/tests/region_failover.rs
Enable the disabled region failover tests(#1660). 
In #1660 introduces a limitation, if a table in the datanode contains multiple regions, then the scan will lead to an incorrect result, Which means we can only tolerate `n` node failures in an `m` nodes cluster, and the number of regions the table contains should be less than or equal `m-n`.
#1660
=> fix: enable region failover test

src/meta-srv/src/error.rs, src/meta-srv/src/service/store/ext.rs
Add `exists` API for KVStore to check if a key exists, it does not return the value.
=> feat: exists API for KVStore

src/storage/src/compaction/task.rs, src/storage/src/flush.rs
This PR avoids manifest and wal writes when no files are flushed so that meaningless sequence bumping is prevented.
=> fix: avoid writing manifest and wal if no files are actually flushed

Cargo.lock, src/common/grpc-expr/Cargo.toml, src/common/grpc-expr/src/insert.rs
An error reported: failed to inserting data with u8 field.  
Error msg:
```
mysql> desc table dist_table;
+--------+----------------------+------+---------------------+---------------+
| Field  | Type                 | Null | Default             | Semantic Type |
+--------+----------------------+------+---------------------+---------------+
| ts     | TimestampMillisecond | NO   | current_timestamp() | TIME INDEX    |
| n      | Int32                | YES  |                     | FIELD         |
| row_id | Int8                 | YES  |                     | FIELD         |
+--------+----------------------+------+---------------------+---------------+
3 rows in set (0.02 sec) …
```
=> fix: failed to insert data with u8

src/common/grpc-expr/src/delete.rs, src/common/grpc-expr/src/insert.rs, src/datatypes/src/vectors/binary.rs, src/datatypes/src/vectors/primitive.rs
Simplify the conversion from gRPC `Values` to `VectorRef` for the case without null value
=> feat: convert values to vector directly

src/servers/src/error.rs, src/servers/src/prometheus.rs
Merges prometheus insert requests by metric name.
This PR reuses the `LinesWriter` introduced to convert InfluxDB's line protocol to simplify the process.
=> feat(servers): collect samples by metric

Cargo.lock, Cargo.toml
This PR bumps greptimedb project version from 0.2.0 to 0.4.0
=> chore: bump greptimedb version 0.4.0

Cargo.lock, src/mito/Cargo.toml, src/mito/src/metrics.rs, src/mito/src/table.rs, src/storage/src/flush.rs, src/storage/src/manifest/region.rs, src/storage/src/memtable/inserter.rs, src/storage/src/metrics.rs, src/storage/src/region/writer.rs
This PR adds the following metrics
- write elapsed time of a mito table
- write batch size of a mito table
- memtable/preprocess elapsed time
- flushed bytes
=> feat: Adds some metrics for write path and flush

src/servers/src/grpc/prom_query_gateway.rs, src/servers/src/prom.rs, tests-integration/tests/grpc.rs
Fix the `resultType` field will be an empty string when the result is empty
=> fix: empty result type on prom query endpoint

src/meta-srv/src/service/admin.rs, src/meta-srv/src/service/admin/route.rs
Since the table route stored in etcd is encoded by protobuf, it is difficult to understand. 
So this pr provides an api to query table route information.
for example: 
```shell
curl "localhost:3002/admin/route?full_table_name=greptime.public.dist_table"
```
=> feat: add route admin api in metasrv

Cargo.lock, src/storage/src/region/tests.rs, src/storage/src/region/tests/alter.rs, src/storage/src/region/tests/basic.rs, src/storage/src/region/tests/close.rs, src/storage/src/region/tests/compact.rs, src/storage/src/region/tests/flush.rs, src/storage/src/sst/parquet.rs
Fixes panics when building time range predicate in parquet reader.
This PR also changes the `TesterBase`'s region schema to `[Timestamp, String, Int64]` which is more generic.
fixes #1640
=> fix: parquet time range predicate panic

Cargo.lock, src/cmd/Cargo.toml, src/cmd/src/bin/greptime.rs, src/servers/Cargo.toml, src/servers/src/error.rs, src/servers/src/http/handler.rs, src/servers/src/metrics.rs
This PR makes jemalloc as the default memory allocator for GreptimeDB. Also it adds two jemalloc metrics:
- `greptime_sys_jemalloc_allocated`: the memory footprint in bytes allocated by jemalloc
- `greptime_sys_jemalloc_resident`: the resident set of allocated memory
=> feat: make jemalloc the default allocator

.github/workflows/release.yml
This patch allows us to trigger nightly builds from github workflow_dispatch. It introduces a new env variable `DRY_RUN` to control whether to publish the release or not. The workflow_dispatch menu now contains two new inputs to customize test and dry-run
=> ci: allow triggering nightly release manually

README.md
Correct the wrong document links in README.md
Please wait for
=> chore: update document links in README.md

.github/workflows/release.yml
Followup for #1746 as github doesn't allow `env` in `jobs.<id>.if` context: https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
=> ci: fix using env in job.if context

src/cmd/src/bin/greptime.rs
Log binary version and command line arguments
```
2023-06-08T03:38:50.237197Z  INFO greptime: short_version: 0.4.0, full_version: greptimedb-chore/log-version-4e71ce4
2023-06-08T03:38:50.237461Z  INFO greptime: command line arguments
2023-06-08T03:38:50.237518Z  INFO greptime: argument: target/debug/greptime
2023-06-08T03:38:50.237593Z  INFO greptime: argument: standalone
2023-06-08T03:38:50.237666Z  INFO greptime: argument: start
2023-06-08T03:38:50.237703Z  INFO greptime: argument: --config-file=./config/standalone.example.toml
```
=> chore: Log version and arguments

src/servers/src/mysql/federated.rs
make `select version()` show greptime info.
just like this.
```
mysql> select version();
+----------------+
| version()      |
+----------------+
| 0.4.0-greptime |
+----------------+
1 row in set (0.04 sec)
```
close https://github.com/GreptimeTeam/greptimedb/issues/1711
=> feat:make version() show greptime info.

src/servers/Cargo.toml
This PR fixes the error that complains jemallocs's Error does not implement `std::Error`.
=> fix: jemalloc error does not implement Error

.github/workflows/release.yml
Folowup changes for #1751 
- Booleans in `github.event.inputs.*` are converted to string, so we always got `True` for booleans. This patch changes context to `inputs.*` which reserves boolean type. https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
- Corrected more event type check
=> ci: correct data type for input and event check

src/common/time/src/range.rs, src/common/time/src/timestamp.rs, src/servers/Cargo.toml, src/servers/src/error.rs, src/storage/benches/memtable/util/bench_context.rs, src/storage/src/chunk.rs, src/storage/src/compaction/writer.rs, src/storage/src/file_purger.rs, src/storage/src/flush.rs, src/storage/src/memtable.rs, src/storage/src/memtable/btree.rs, src/storage/src/memtable/inserter.rs, src/storage/src/memtable/tests.rs, src/storage/src/metrics.rs, src/storage/src/read/windowed.rs, src/storage/src/region/tests.rs, src/storage/src/region/tests/flush.rs, src/storage/src/sst.rs, src/storage/src/sst/parquet.rs, src/storage/src/window_infer.rs, tests-integration/src/tests/instance_test.rs
This PR fixes issues related to order-by rule.
- avoid actual IO during plan stage by wrap `ParquetReader` with a `LazyParquetReader`
- when time windows does not yield a valid record batch, replace it with a record batch of empty vectors to avoid panic.
#1750
=> fix: order by optimization

src/storage/src/sst/parquet.rs
Optimize some parquet writer parameter:
- disable dictionary for `__sequence` column,
- enable DELTA_BINARY_PACKED encoding for `__sequence` and timestamp column.
=> feat: optimize some parquet writer parameter

src/catalog/src/remote.rs
=> chore: make MetaKvBackend public

src/storage/src/engine.rs, src/storage/src/region.rs, src/storage/src/region/writer.rs
Respect `EngineConfig::region_write_buffer_size` instead of the constant `DEFAULT_REGION_WRITE_BUFFER_SIZE`.
=> fix(storage): Use region_write_buffer_size as default value

src/storage/src/flush/scheduler.rs, src/storage/src/region/tests.rs, src/storage/src/region/tests/compact.rs, src/storage/src/region/tests/flush.rs
Fix failing unit tests caused by unstopped flush and compaction scheduler, for real, this time.
=> chore: fix compaction caused race condition

src/catalog/src/remote.rs, src/catalog/src/remote/mock.rs, src/catalog/src/remote/region_alive_keeper.rs
Part of #1737
A countdown task that is able to close the region. It's intended to be used in region keep alive in Datanode (done in next PR).
=> feat: a countdown task for closing region in Datanode

src/cmd/src/metasrv.rs, src/meta-srv/src/handler/collect_stats_handler.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/metasrv/builder.rs
In some scenarios, we don't need to enable region failover, such as when the data is stored on local disks and we don't currently support data migration. If a failover occurs, it will result in data loss, so region failover should be disabled in this case.
I added a startup option called `disable_region_failover`, which defaults to false(enable region failover) and allows users to choose to turn it on(disable region failover).
=> feat: disable_region_failover option for metasrv

src/common/datasource/src/buffered_writer.rs, src/common/datasource/src/file_format.rs, src/storage/src/sst/parquet.rs, src/storage/src/sst/stream_writer.rs
This PR fixes two issues:
- `ParquetWriter::close` returns the bytes during last flush attempt when closing underlying writer instead of the size of whole file: https://github.com/GreptimeTeam/greptimedb/pull/1785/files#diff-051f815e4fa71f86735dd28136c0d475fa75dceb4903a7ab47c93b60576ad970L56
- [`stream_to_file`](https://github.com/GreptimeTeam/greptimedb/pull/1785/files#diff-423117cc93ea8a8d6deed211495ad49b92650c130e6932d1d9282c4eff8b52c9L184-L188) and [`BufferedWriter::try_new`](https://github.com/GreptimeTeam/greptimedb/pull/1785/files#diff-23b04e5dea6eef5d5101622d0d8d2046da2f0331c97474c484cc647ddaf6f4dfL50-L53) eagerly create underlying files even if there's no row has …
=> fix: abort parquet writer 

Cargo.lock, Cargo.toml, src/catalog/src/remote.rs, src/catalog/src/remote/manager.rs, src/catalog/src/remote/region_alive_keeper.rs, src/catalog/tests/remote_catalog_tests.rs, src/common/meta/src/error.rs, src/common/meta/src/ident.rs, src/common/meta/src/instruction.rs, src/common/meta/src/lib.rs, src/datanode/src/heartbeat.rs, src/datanode/src/heartbeat/handler/close_region.rs, src/datanode/src/heartbeat/handler/open_region.rs, src/datanode/src/instance.rs, src/datanode/src/tests.rs, src/frontend/src/heartbeat/handler/invalidate_table_cache.rs, src/frontend/src/heartbeat/handler/tests.rs, src/meta-client/Cargo.toml, src/meta-srv/Cargo.toml, src/meta-srv/src/handler.rs, src/meta-srv/src/handler/failure_handler.rs, src/meta-srv/src/handler/failure_handler/runner.rs, src/meta-srv/src/handler/response_header_handler.rs, src/meta-srv/src/procedure/region_failover.rs, src/meta-srv/src/procedure/region_failover/failover_start.rs, src/meta-srv/src/procedure/region_failover/invalidate_cache.rs, src/table/src/test_util/empty_table.rs, src/table/src/test_util/memtable.rs, tests-integration/tests/region_failover.rs
Part of #1737 
Region alive keeper for starting close countdown for the region in Datanode. It only spawns the countdown task but not starts it. So the region is safe, for now.
=> feat: region alive keeper in Datanode

Cargo.lock, Cargo.toml, src/datanode/src/heartbeat.rs, src/meta-srv/src/handler/node_stat.rs, src/meta-srv/src/handler/persist_stats_handler.rs, src/meta-srv/src/service/store/ext.rs
Deal with node epoch.
If the node is redeployed and the `member_id`, `peer` are reused, 
metasrv must clear the old information to ensure that the scheduling will not be wrong.
=> feat: deal with node epoch

src/catalog/src/remote/manager.rs, src/catalog/src/remote/region_alive_keeper.rs, src/catalog/tests/remote_catalog_tests.rs, src/datanode/src/heartbeat.rs, src/datanode/src/heartbeat/handler/close_region.rs, src/datanode/src/instance.rs, src/datanode/src/tests.rs, src/datanode/src/tests/test_util.rs, src/table/src/test_util/empty_table.rs, src/table/src/test_util/memtable.rs
fix #1737 
- start region alive keepers when table registered or region opened
- add more tests
=> feat: start region alive keepers

src/catalog/src/remote/manager.rs
The table regional values could be multiple, we need to filter them with the current node id when iter table names in RemoteCatalogManager. Otherwise we could end with incorrect stats.
=> fix: filter table regional values with the current node id

Cross.toml
Add support for cross compilation targeting aarch64-unknown-linux-gnu, thanks to [cross-rs(https://github.com/cross-rs/cross).
You can produce a GreptimeDB binary for aarch-unknown-linux-gnu by following steps:
- Install docker
- Install cross-rs by `cargo install cross --git https://github.com/cross-rs/cross`
- Under GreptimeDB repository, run `cross build --target aarch64-unknown-linux-gnu`
Honestly I really don't suggest cross compilation on macOS in that it uses QEMU to run containers, which will make the compilation painfully slow.
=> feat: support cross compilation to aarch64 linux

Cargo.lock, src/catalog/src/remote/region_alive_keeper.rs
=> fix: drop region alive countdown tasks when deregistering table

Cargo.lock, config/datanode.example.toml, config/standalone.example.toml, src/datanode/src/datanode.rs
Change default logstore config.
=> chore: change logstore default config

Cargo.lock, src/catalog/src/local/manager.rs, src/catalog/src/remote/manager.rs, src/catalog/src/tables.rs, src/table-procedure/src/drop.rs, src/table-procedure/src/error.rs
This PR adds result check when invoking `CatalogManager::deregister_table`. We should remove the return value of this API in #1803 .
=> chore: check catalog deregister result

src/query/src/dist_plan/commutativity.rs, tests/cases/distributed/optimizer/filter_push_down.result, tests/cases/standalone/common/select/like.result, tests/cases/standalone/common/select/like.sql
Prevent pushing down filter plan in distributed planner since `Like` expr is not supported in substrait now
=> fix: prevent filter pushdown in distributed planner

src/file-table-engine/src/table/format.rs
=> refactor: remove redundant code

.dockerignore, docker/Dockerfile
#1685 introduced build info which requires git command and `.git` directory to be present during compile time. But the default base image does not have a built in git command, and the `.git` directory is intentionally ignored when copying files into container.
=> fix: docker build

Cargo.lock, src/common/query/src/physical_plan.rs, src/common/recordbatch/src/adapter.rs, src/table/src/table/scan.rs
Count metrics for `Scan` plan. It contains number of rows and elapsed times. E.g.:
```sql
MySQL [(none)]> explain analyze select count(*) from tsdg;
+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
=> feat: implement metrics for Scan plan

src/catalog/src/helper.rs, src/catalog/src/remote/manager.rs, src/catalog/src/remote/mock.rs, src/catalog/src/remote/region_alive_keeper.rs, src/common/grpc-expr/src/alter.rs, src/datanode/src/heartbeat/handler/close_region.rs, src/datanode/src/instance/sql.rs, src/datanode/src/server/grpc.rs, src/datanode/src/sql/alter.rs, src/file-table-engine/src/engine/immutable.rs, src/file-table-engine/src/engine/procedure/create.rs, src/file-table-engine/src/engine/tests.rs, src/frontend/src/instance/distributed.rs, src/frontend/src/table.rs, src/mito/src/engine.rs, src/mito/src/engine/procedure/alter.rs, src/mito/src/engine/procedure/create.rs, src/mito/src/engine/procedure/drop.rs, src/mito/src/engine/tests.rs, src/mito/src/table/test_util.rs, src/table-procedure/src/alter.rs, src/table-procedure/src/create.rs, src/table-procedure/src/drop.rs, src/table-procedure/src/test_util.rs, src/table/src/engine.rs, src/table/src/requests.rs, src/table/src/test_util/mock_engine.rs
This PR uses table id instead of the table name to index tables in table engines. It adds the table id to table requests so engines can use it to locate the table.
The remote catalog manager doesn't store a table id in the `TableRegionalValue` so we add an `Option<TableId>` to the `TableRegionValue`. Then we can use the table id to find the table. This might be a breaking change.
```rust
pub struct TableRegionalValue {
pub table_id: Option<TableId>,
pub version: TableVersion,
pub regions_ids: Vec<u32>,
pub engine_name: Option<String>,
}
```
However, the remote catalog always registers the table to the `RemoteSchemaProvider` in `initiate_tables()` …
=> refactor!: Uses table id to locate tables in table engines

docker/aarch64/Dockerfile
The similar change that was done in https://github.com/greptimeTeam/greptimedb/pull/1822 to add `git` command that is required for build info
https://github.com/greptimeTeam/greptimedb/pull/1822
https://github.com/GreptimeTeam/greptimedb/pull/1685
=> fix: docker build for aarch64

src/datanode/src/datanode.rs, src/datanode/src/instance.rs, src/datanode/src/lib.rs, src/datanode/src/mock.rs, src/datanode/src/tests/test_util.rs, tests-integration/src/cluster.rs, tests-integration/src/test_util.rs, tests-integration/src/tests.rs
move Instance heartbeat to Datanode struct
=> refactor(datanode): move Instance heartbeat task to Datanode struct

src/servers/src/http.rs, src/servers/src/http/influxdb.rs
This pr mainly improve influxdb v2 api compability.
- Write using the curl command as shown below
```shell
curl -i -XPOST "http://localhost:4000/v1/influxdb/api/v2/write?bucket=public&precision=ms" \
--data-binary \
'monitor,host=127.0.0.1 cpu=0.1,memory=0.4 1667446797450
monitor,host=127.0.0.2 cpu=0.2,memory=0.3 1667446798450
monitor,host=127.0.0.1 cpu=0.5,memory=0.2 1667446798450'
```
- Write using Go sdk, an example [here](https://github.com/Fengys123/influxdb_write_example/blob/main/main.go)
fix https://github.com/GreptimeTeam/greptimedb/issues/1815
=> feat: improve influxdb v2 api compability

src/meta-srv/src/keys.rs, src/meta-srv/src/service/admin.rs, src/meta-srv/src/service/admin/node_lease.rs, tests/cases/distributed/show/show_create.result
Add http API to get Node-lease time
example:
```
[
{
"name": {
"cluster_id": 0,
"node_id": 3
},
"human_time": "2023-06-28 18:24:03+0800",
"lease": {
"timestamp_millis": 1687947843382,
"node_addr": "127.0.0.1:3001"
}
}
]
```
=> feat: http api for node-lease

Cargo.lock, src/common/datasource/Cargo.toml
Support to read the orc format files with the zstd compression.
=> chore: bump orc-rust to 0319acd

.cargo/config.toml, tests/cases/standalone/common/system/information_schema.result, tests/cases/standalone/common/system/information_schema.sql
- fix Sqlness CI caused by #1858
- that pr is auto merged before I push 2ea71568c77bf3c5adcc481eab57646055f7e5e1 😵‍💫
- remove flag `-Wunused_results` introduced in #1825
- `let _` may lead to other errors like forgetting to `.await` a future etc
=> fix: break CI again 🥲

docker/Dockerfile-centos7-builder
This PR adds a dockerfile to support compilation to CentoOS 7 machines that only have glibc 2.17
To build CentOS 7 compatible binaries:
- `docker buildx build -f ./docker/Dockerfile-centos7 -t greptime-centos7-builder .` to build a builder image
- `docker run --rm -v .:/greptimedb greptime-centos7-builder` using that builder image to build binaries.
GreptimeDB requires Python >= 3.8. For CentOS 7 platform, we need to install extra dependencies like
```bash
$ yum install -y centos-release-scl rh-python38 rh-python38-python-devel
$ source /opt/rh/rh-python38/enable
```
And then GreptimeDB built with PyO3 backend should now work.
#1271
=> feat: support building binary for centos7

src/servers/src/mysql/handler.rs
This pr mainly changes from suspending MySQL session to returning an error msg if user tries to switch to an invalid database using `use` syntax.
=> fix: return err msg if use wrong database in MySQL

Cargo.lock, src/catalog/src/error.rs, src/catalog/src/remote.rs, src/catalog/src/remote/client.rs, src/catalog/src/remote/manager.rs, src/catalog/src/remote/mock.rs, src/catalog/tests/remote_catalog_tests.rs, src/common/meta/Cargo.toml, src/common/meta/src/error.rs, src/common/meta/src/key.rs, src/common/meta/src/key/table_info.rs, src/common/meta/src/key/table_region.rs, src/common/meta/src/kv_backend.rs, src/common/meta/src/kv_backend/memory.rs, src/common/meta/src/lib.rs, src/frontend/src/catalog.rs, src/frontend/src/error.rs, src/frontend/src/instance/distributed/inserter.rs, src/frontend/src/table.rs, tests-integration/tests/region_failover.rs
Add TableInfoKey and TableRegion, prepare to split TableGlobalKey.
#1728
=> refactor: add TableInfoKey and TableRegionKey

Cross.toml
This PR fixes the error `/usr/bin/ld: cannot find -lz` when cross compiling to some platforms.
=> fix: libz dependency

src/cmd/Cargo.toml, src/servers/Cargo.toml, src/servers/src/http/handler.rs, src/servers/src/metrics.rs
This pr add feature for metrics-process crate, default enable. Since the [metrics-process](https://github.com/lambdalisue/rs-metrics-process) crate does not support the android platform.
https://github.com/GreptimeTeam/greptimedb/issues/1766
=> chore: add feature for metrics-process, default enable

src/meta-srv/src/election.rs, src/meta-srv/src/handler/on_leader_start_handler.rs, src/meta-srv/src/handler/persist_stats_handler.rs, src/meta-srv/src/handler/response_header_handler.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/metasrv/builder.rs, src/meta-srv/src/service/store.rs, src/meta-srv/src/service/store/cached_kv.rs
Currently we store the metadata in etcd, but some scenarios require querying a large amount of data from etcd, and these operations are usually initiated by the leader node. The purpose of this PR is to cache some metadata to avoid etcd becoming a bottleneck.
A cache dedicated to a Leader node, in order to cache some metadata.
To use this cache, the following constraints must be followed:
1. The leader node can create this metadata.
2. The follower node can create this metadata. The leader node can lazily retrieve
the corresponding data through the caching loading mechanism.
3. Only the leader node can update this metadata, as the cache cannot detect
modifications made to …
=> feat: add leader kv store cache for metadata

src/catalog/src/local/manager.rs, src/catalog/src/system.rs, src/catalog/src/tables.rs, tests/cases/standalone/common/tql/operator.result, tests/cases/standalone/common/tql/operator.sql, tests/cases/standalone/create/recover_created.result, tests/cases/standalone/create/recover_created.sql
Change system catalog's behavior on deleting table. It will remove the entire entry in previous, which may cause "jump back" of max table id. This pr changes it to mark-deletion, thus the allocated table id would never disappear.
fixes #1797
=> fix: use mark-deletion for system catalog

Cargo.toml
=> chore: bump version 0.3.2

src/catalog/src/remote/client.rs, src/common/meta/src/error.rs, src/frontend/src/instance.rs, src/frontend/src/instance/distributed.rs, tests-integration/tests/region_failover.rs
1. stop caching `None` value in `CachedMetaKvBackend` by @Fengys123 
- Caching `None` would cause table not found error while concurrently creating table
3. throw error while creating table
=> chore: stop caching `None` in `CachedMetaKvBackend`

Cargo.lock, Cargo.toml, src/mito2/Cargo.toml, src/mito2/README.md, src/mito2/src/engine.rs, src/mito2/src/lib.rs
This PR is a part of #1869. It initializes a new crate `mito2` to experiment with refactoring the old `mito` engine to a region engine.
- #1869
=> chore: initialize mito2 crate

Cargo.lock, tests/cases/distributed/alter/rename_table.result, tests/cases/distributed/optimizer/filter_push_down.result, tests/cases/distributed/tql-explain-analyze/analyze.result, tests/cases/distributed/tql-explain-analyze/explain.result, tests/cases/standalone/common/aggregate/distinct_order_by.result, tests/cases/standalone/common/insert/insert.result, tests/cases/standalone/common/order/nulls_first.result, tests/cases/standalone/common/order/order_by.result, tests/cases/standalone/common/order/order_by_exceptions.result, tests/cases/standalone/common/tql/aggr_over_time.result, tests/cases/standalone/common/tql/basic.result, tests/cases/standalone/common/tql/operator.result, tests/cases/standalone/common/types/blob.result, tests/cases/standalone/cte/cte.result, tests/cases/standalone/cte/cte_in_cte.result, tests/cases/standalone/optimizer/filter_push_down.result, tests/cases/standalone/tql-explain-analyze/analyze.result, tests/cases/standalone/tql-explain-analyze/explain.result, tests/runner/Cargo.toml
Bump sqlness to `0.5.0`. Those diff are comments
=> chore: bump sqlness to 0.5.0

Cargo.lock, src/table-procedure/src/create.rs, src/table-procedure/src/drop.rs, src/table-procedure/src/error.rs, tests/cases/standalone/alter/rename_table.result
This PR fixes that create table procedure doesn't check table existence before actually creating a region.
PR #1817 replaces the keys in the table engine and we should not use table's name to build the procedure's lock key.
=> fix: check table existence in create table procedure

Cargo.lock, src/common/meta/src/key/table_route.rs, src/frontend/src/table.rs, src/meta-srv/src/procedure/region_failover/update_metadata.rs, src/meta-srv/src/service/router.rs, src/meta-srv/src/table_routes.rs
implement `Display` for `TableRouteKey`
=> refactor: implement Display for TableRouteKey

.github/workflows/release.yml
Only push `*.tgz` to s3 bucket.
=> refactor: release push binary

.github/workflows/release.yml
Sets `allowUpdates` to `true` and disable release note generation when the release ci is triggered manually.
=> ci: allow update release (except release note) if it already exists

Cargo.lock, Cargo.toml, src/common/grpc-expr/src/alter.rs, src/common/meta/src/rpc/ddl.rs, src/datanode/src/instance/grpc.rs, src/frontend/src/expr_factory.rs, src/frontend/src/instance.rs, src/frontend/src/instance/distributed.rs, src/servers/src/http/admin.rs, tests-integration/src/grpc.rs, tests-integration/tests/grpc.rs
=> chore: bump proto to 917ead6

src/catalog/src/information_schema.rs, src/common/substrait/src/df_substrait.rs, src/common/substrait/src/lib.rs, src/datanode/src/instance/grpc.rs, src/frontend/src/instance/prometheus.rs, src/query/src/dist_plan/planner.rs, tests/cases/standalone/common/create/upper_case_table_name.result, tests/cases/standalone/common/create/upper_case_table_name.sql
Currently the planner will fill default catalog/schema when converting plan.
This case is originally for tables that don't have actual data like `information_schema.table` because they don't have route info. But when the catalog/schema change to other strings, filling the default catalog/schema will lead to wrong route info.
Elegant designs encountered:
- table in `information_schema` doesn't have table info. Workaround: only try to retrieve table info when table type is `Base`
- `DataFrame` will fill `?table?` as the table identifier when constructing it from an existing table source. Workaround: overwrite the fully resolved table name into the `TableScan` plan
=> fix: resolve catalog and schema in dist planner

Cargo.lock, src/common/datasource/Cargo.toml
=> chore: bump orc-rust to 0.2.4

src/query/src/datafusion.rs, src/query/src/error.rs, src/query/src/sql.rs, tests-integration/src/tests/instance_test.rs, tests/cases/standalone/common/catalog/schema.result, tests/cases/standalone/common/catalog/schema.sql
This PR adds support for executing `SHOW TABLES WHERE ~`:
```sql
SHOW TABLES WHERE tables='monitor'
```
close #1722
=> feat: support where in show

.github/workflows/docs.yml
#1900 didn't set `sqlness` job's name 😅 so we couldn't pass the sqlness test.
=> ci: fix sqlness action in docs.yml doesn't have same name as develop.yml

docs/rfcs/2023-07-06-table-engine-refactor.md, src/common/datasource/src/object_store/s3.rs
rename WITH parameter ENDPOINT_URL to ENDPOINT
=> feat!: rename WITH parameter ENDPOINT_URL to ENDPOINT

.github/workflows/docs.yml, docs/rfcs/2023-07-06-table-engine-refactor.md
=> ci: fix typo and check typo in docs ci

.github/workflows/release.yml
Use enterprise ACR to make the registry service more reliable.
=> ci: use enterprise ACR

src/catalog/src/lib.rs, src/catalog/src/local/manager.rs, src/catalog/src/local/memory.rs, src/catalog/src/remote/manager.rs, src/frontend/src/catalog.rs
This PR adds `deregister_schema` method to `CatalogManager`, and implements it for `MemoryCatalogManager`.
Part of #825
=> feat: add `deregister_schema` to `CatalogManager`

src/query/Cargo.toml, src/query/src/dist_plan/analyzer.rs
Add test case to cover `LogicalPlan::Limit` for distributed planner
=> test: add unit test for distributed limit pushdown

docker/Dockerfile-centos7-builder
Remove useless mirror subsitution and RUN command from CentOS-7 builder docker file.
=> fix: remove useless mirror subsitution and RUN command 

src/client/src/client_manager.rs, src/meta-srv/src/mocks.rs, src/storage/src/flush.rs, src/storage/src/memtable.rs, src/storage/src/memtable/btree.rs, src/storage/src/memtable/tests.rs
This PR removes `for_flush` option from `IterContext` and always dedup rows while flushing.
It also enlarges the timeout in meta client and datanode client to avoid the following errors during integration tests
```
2023-07-10T04:44:09.872390Z ERROR client::database: Failed to do Flight get, addr: 127.0.0.1:3001, code: The operation was cancelled, source: Failed to do Flight get, code: The operation was cancelled, source: status: Cancelled, message: "Timeout expired", details: [], metadata: MetadataMap { headers: {} }
```
- fixes #1897
=> feat: dedup rows while flushing memtables

src/frontend/src/instance.rs, src/servers/src/interceptor.rs, src/servers/tests/interceptor.rs
This pr mainly adds `PromQueryInterceptor` to `PromHandler` while processing prometheus query requests. `PromHandler` covers requests from grpc server(prom query) and prom http server.
todo:
- check requests from `remote_read` too
=> chore: add interceptor for prometheus query

Cargo.lock, Cargo.toml, src/api/src/helper.rs, src/catalog/src/lib.rs, src/datanode/src/instance/grpc.rs, src/frontend/src/instance/distributed.rs, src/meta-srv/src/cluster.rs, src/meta-srv/src/handler/node_stat.rs, src/meta-srv/src/keys.rs
=> chore: bump latest greptime-proto version

src/common/datasource/src/file_format/orc.rs, src/frontend/src/statement/copy_table_from.rs
Cast orc data against output schema
=> fix: cast orc data against output schema 

src/api/src/helper.rs, src/catalog/src/remote/manager.rs, src/client/src/database.rs, src/client/src/metrics.rs, src/datanode/src/error.rs, src/datanode/src/instance/grpc.rs, src/datanode/src/server/grpc.rs, src/datanode/src/sql.rs, src/datanode/src/sql/compact_table.rs, src/datanode/src/sql/flush_table.rs, src/frontend/src/instance/distributed.rs, src/mito/src/table.rs, src/mito/src/table/test_util/mock_engine.rs, src/servers/src/http.rs, src/servers/src/http/admin.rs, src/storage/src/compaction/task.rs, src/storage/src/region.rs, src/storage/src/region/tests/compact.rs, src/store-api/src/storage.rs, src/store-api/src/storage/region.rs, src/table/src/requests.rs, src/table/src/table.rs
Add HTTP API for manual table compaction.
This should be merged after #1882.
=> feat: manual compact api

Cargo.lock, src/common/grpc/src/channel_manager.rs
Change grpc request-timeout and connect-timeout to 10s
=> chore: grpc-timeput = 10s

src/common/telemetry/Cargo.toml, src/common/telemetry/src/macros.rs, src/servers/src/metrics.rs, src/servers/src/mysql/writer.rs
This patch changed error logging of mysql protocol to level `WARN`. 
It also includes a metrics to track error count so that we can count error rate later.
More error count for other protocols to come in next patches.
=> refactor: change logging level for mysql error log

src/datanode/src/instance/grpc.rs, src/frontend/src/instance/standalone.rs, src/meta-srv/src/lib.rs, src/servers/src/query_handler/grpc.rs, src/servers/tests/mod.rs
There is an actual struct named `GreptimeRequest`. And their relationship is
```rust
struct GreptimeRequest {
Request request
}
```
=> refactor: remove misdirectional alias "Request as GreptimeRequest"

Cargo.lock, src/meta-srv/src/lib.rs, src/mito2/Cargo.toml, src/mito2/src/error.rs, src/mito2/src/manifest.rs, src/mito2/src/manifest/action.rs, src/mito2/src/manifest/gc_task.rs, src/mito2/src/manifest/helper.rs, src/mito2/src/manifest/impl_.rs
There are too many abstractions around manifest. They were needed when we had region manifest and table manifest. In #1869 we are going to merge these two manifests. By doing this the implementation can also be simplified. Major change:
- trait `Checkpoint` -> struct `RegionCheckpoint`
- trait `MetaAction` -> struct `RegionMetaActionList`
- trait `MetaActionIterator` -> struct `MetaActionIteratorImpl`
The next step is to port `manifest/region.rs` and `manifest/storage.rs`
=> refactor(mito): define manifest related API

Cargo.lock, Cargo.toml, src/cmd/Cargo.toml, src/common/base/Cargo.toml, src/datanode/Cargo.toml, src/frontend/Cargo.toml, src/meta-srv/Cargo.toml
```rust
impl FrontendOptions {
pub fn env_list_keys() -> Option<&'static [&'static str]> {
Some(&["meta_client_options.metasrv_addrs"])
}
pub fn to_toml_string(&self) -> String {
toml::to_string(&self).unwrap()
}
}
```
`toml::to_string(&self).unwrap()` would cause `ValueAfterTable`, see [here](https://github.com/toml-rs/toml/issues/395)
This pr mainly upgrades `toml` version to fix this.
=> chore: upgrade toml version

src/sql/src/parser.rs, tests/cases/standalone/common/describe/describe_table.result, tests/cases/standalone/common/describe/describe_table.sql
Make the keyword `TABLE` in `DESCRIBE` clause optional. SQL like `desc <table_name>` is supported after this patch
fixes https://github.com/GreptimeTeam/greptimedb/issues/1941
=> feat: support desc [table] <table_name>

src/frontend/src/instance.rs, src/frontend/src/statement.rs, src/sql/src/parser.rs, src/sql/src/parsers/truncate_parser.rs, src/sql/src/statements.rs, src/sql/src/statements/statement.rs, src/sql/src/statements/truncate.rs
Implement truncate table parser
=> feat: implement truncate table parser

src/mito2/src/error.rs, src/mito2/src/manifest.rs, src/mito2/src/manifest/storage.rs
rewrite note:
- trait `LogIterator` -> struct `ObjectStoreLogIterator`
- trait `ManifestLogStorage` -> struct `ManifestObjectStore`
Those two traits can be removed afterward
=> refactor(mito): port manifest storage to mito2

Cargo.lock, src/client/src/client_manager.rs, src/common/grpc/Cargo.toml, src/common/grpc/src/channel_manager.rs, src/datanode/src/instance.rs, src/frontend/src/catalog.rs, src/frontend/src/instance.rs
Simplify the usage of ﻿channel_manager by avoiding the external invocation of ﻿start.
=> feat: simplify the usage of channel_manage

src/frontend/src/instance/distributed.rs
Invalidate table cache after altering
=> feat: invalidate table cache after altering

src/meta-srv/src/metasrv.rs, src/meta-srv/src/service/admin.rs, src/meta-srv/src/service/ddl.rs, src/meta-srv/src/service/heartbeat.rs, src/meta-srv/src/service/router.rs, tests-integration/src/cluster.rs, tests-integration/tests/region_failover.rs
Metasrv has many fields, we defined some getters, some return a clone internally, some return a reference, we should unify the behavior.
=> refactor: let metasrv returns ref always

src/mito2/src/lib.rs, src/mito2/src/metadata.rs, src/mito2/src/region.rs
Simplify the region metadata. In this version `StoreSchema` and `RegionSchema` are deprecated
Before 
```mermaid
classDiagram
class RegionMetadata {
+RegionId region_id
+VersionNumber version
+SchemaRef table_schema
+Vec~usize~ primary_key_indices
+Vec~usize~ value_indices
+ColumnId next_column_id
+TableOptions region_options
+DateTime~Utc~ created_on
+RegionSchemaRef region_schema
}
class RegionSchema {
-SchemaRef user_schema
-StoreSchemaRef store_schema
-ColumnsMetadataRef columns
}
class Schema
class StoreSchema {
-Vec~ColumnMetadata~ columns
-SchemaRef schema
-usize row_key_end
-usize user_column_end
}
class ColumnsMetadata {
-Vec~ColumnMetadata~ columns …
```
=> refactor(mito): define region metadata

src/log-store/src/error.rs, src/log-store/src/noop.rs, src/log-store/src/raft_engine.rs, src/log-store/src/raft_engine/log_store.rs, src/store-api/src/logstore.rs, src/store-api/src/logstore/namespace.rs
This PR: 
- adds support for appending entries from multiple regions at a time
- removes the return value of `append_batch` in that underlying impl should guarantee the atomicity of `append_batch`.
fixes #1958
=> feat: support append entries from multiple regions at a time

config/metasrv.example.toml, src/client/src/client_manager.rs, src/common/grpc/src/channel_manager.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/metasrv/builder.rs
Expose metasrv `datanode_client_options`
=> feat: expose metasrv `datanode_client_options`

README.md
The image link keeps changing after website build, here we remove the broken image and use link temporarily
=> docs: fix playground section

config/datanode.example.toml, config/frontend.example.toml, src/datanode/src/datanode.rs, src/datanode/src/instance.rs, src/frontend/src/frontend.rs, src/frontend/src/heartbeat.rs, src/frontend/src/instance.rs, src/servers/src/heartbeat_options.rs, src/servers/src/lib.rs, tests-integration/tests/http.rs
move heartbeat configuration into an independent section in config file, add a new HeartbeatOptions struct, use it instead heartbeat_interval_millis and retry_interval_millis, change HeartbeatTask::new() to take it as argument, and change corresponding test cases and example files.
* refactor: move heartbeat configuration into an independent section in config file
* feat: add HeartbeatOptions struct
* test: modify corresponding test case
* chore: modify corresponding example file
close #1936
=> refactor: move heartbeat configuration into an independent section

Cargo.lock, src/catalog/src/remote/manager.rs, src/cmd/Cargo.toml, src/cmd/src/cli.rs, src/cmd/src/cli/upgrade.rs, src/cmd/src/error.rs, src/common/meta/src/key.rs, src/common/meta/src/key/datanode_table.rs, src/common/meta/src/key/table_info.rs, src/common/meta/src/key/table_name.rs, src/common/meta/src/key/table_region.rs, src/meta-srv/src/bootstrap.rs, src/meta-srv/src/service/store/etcd.rs
Scan etcd values to create new table metadata values from old (the old values are not deleted). Necessary when upgrading to version 0.4.
Example usage and output:
With `--dryrun`, no values are actually updated:
```txt
~ ./greptime cli upgrade --help                             
greptime-cli-upgrade 
USAGE:
greptime cli upgrade [OPTIONS] --etcd-addr <ETCD_ADDR>
OPTIONS:
--dryrun                   
--etcd-addr <ETCD_ADDR>    
-h, --help                     Print help information
~ ./greptime cli upgrade --etcd-addr=127.0.0.1:2379 --dryrun
2023-07-15T06:46:50.075788Z  INFO greptime: short_version: 0.3.2, full_version: greptimedb-develop-d975126
2023-07-15T06:46:50.076061Z …
```
=> feat: tool to migrate table metadata values

src/cmd/src/cli/upgrade.rs, src/frontend/src/instance/distributed.rs, src/meta-srv/src/procedure/alter_table.rs, src/meta-srv/src/procedure/region_failover.rs
Move AlterProcedure `DatanodeAlterTable` step after `InvalidateTableCache`
=> refactor: move DatanodeAlterTable after InvalidateTableCache

Cargo.lock, Cargo.toml, src/frontend/Cargo.toml, src/frontend/src/frontend.rs, src/frontend/src/instance.rs, src/frontend/src/instance/otlp.rs, src/frontend/src/metrics.rs, src/frontend/src/server.rs, src/frontend/src/service_config/otlp.rs, src/servers/Cargo.toml, src/servers/src/error.rs, src/servers/src/http.rs, src/servers/src/http/authorize.rs, src/servers/src/http/header.rs, src/servers/src/http/otlp.rs, src/servers/src/lib.rs, src/servers/src/metrics.rs, src/servers/src/otlp.rs, src/servers/src/query_handler.rs
After some investigation we found OTLP might be the most promising push-based protocol for metrics. We are going to add OTLP based examples on our cloud onboarding process. This patch is going to add otlp/http support on greptimedb.
Reference:
- OTLP: https://opentelemetry.io/docs/specs/otlp/#otlphttp
- Java Demo: https://github.com/sunng87/opentelemetry-java-examples/blob/metric-otlp-example/metrics/src/main/java/io/opentelemetry/example/metrics/GaugeExample.java
- Gauge
- Every attribute are stored as tag
- value is stored as field `greptime_value` following the convention of prometheus interface
- timestamp is stored as `greptime_timestamp` too
- Sum
- Same as gauge. 
- …
=> feat: initial implementation for OpenTelemetry otlp/http

src/frontend/src/instance.rs, src/frontend/src/metrics.rs, src/servers/src/metrics.rs, src/servers/src/prometheus.rs
This patch adds timers for various promql apis
=> feat: add timers for promql query

Cargo.lock, src/servers/src/otlp.rs, tests-integration/Cargo.toml, tests-integration/src/lib.rs, tests-integration/src/otlp.rs
This patch includes more attributes from `Resource` and `InstrumentalScope` as tag fields.
It also prefixes "greptime_" for columns generated from `Summary`.
Integration tests are added.
As requested by @nicecui
=> feat: Add more tags for OTLP metrics protocol

src/servers/src/mysql/handler.rs, src/servers/src/postgres/auth_handler.rs, src/servers/src/postgres/handler.rs, src/session/src/lib.rs
This patch is to ensure the scope of `Session` and `QueryContext` to prepare for placing trace id into `QueryContext`. After this change, session will not hold `QueryContext`, but become a factory of it.
=> refactor: improve semantics of session and query context

src/mito2/src/config.rs, src/mito2/src/engine.rs, src/mito2/src/engine/tests.rs, src/mito2/src/error.rs, src/mito2/src/manifest/manager.rs, src/mito2/src/manifest/options.rs, src/mito2/src/memtable.rs, src/mito2/src/metadata.rs, src/mito2/src/region.rs, src/mito2/src/region/opener.rs, src/mito2/src/region/version.rs, src/mito2/src/sst/version.rs, src/mito2/src/test_util.rs, src/mito2/src/worker.rs, src/mito2/src/worker/handle_create.rs, src/mito2/src/worker/request.rs, src/object-store/src/util.rs
This PR implements `create_region()` for the mito2 engine.
- #1869
=> feat(mito): create region in mito2 engine

README.md
I changed the documentation links for 'protocols and clients' because when I tried to open them earlier, they showed a 404 PAGE NOT FOUND error.
=> docs: fix incorrect document URL

src/catalog/src/remote/client.rs, src/common/meta/src/ident.rs, src/common/meta/src/kv_backend.rs, src/common/meta/src/kv_backend/memory.rs, src/meta-srv/src/error.rs, src/meta-srv/src/handler/collect_stats_handler.rs, src/meta-srv/src/handler/failure_handler.rs, src/meta-srv/src/handler/node_stat.rs, src/meta-srv/src/handler/region_lease_handler.rs, src/meta-srv/src/inactive_node_manager.rs, src/meta-srv/src/keys.rs, src/meta-srv/src/lib.rs, src/meta-srv/src/metasrv/builder.rs, src/meta-srv/src/procedure/region_failover.rs, src/meta-srv/src/procedure/region_failover/activate_region.rs, src/meta-srv/src/procedure/region_failover/deactivate_region.rs, src/meta-srv/src/selector/load_based.rs, src/meta-srv/src/sequence.rs, src/meta-srv/src/service/store/cached_kv.rs, src/meta-srv/src/service/store/etcd.rs, src/meta-srv/src/service/store/kv.rs, src/meta-srv/src/test_util.rs, tests-integration/tests/region_failover.rs
Currently we need to query remote metadata when handling datanode heartbeats and renewing leases, which will become the bottleneck of metasrv.
The current design can be optimized, no metadata query is required, just renew the lease according to the information in the heartbeat, except for those nodes that are performing failover.
=> feat: region lease improve

.github/workflows/release.yml
Upload to s3 need `TAG` GITHUB_ENV, but now is `IMAGE_TAG`.
`aws s3 cp target/${{ matrix.arch }}/${{ env.CARGO_PROFILE }} s3://${{ secrets.GREPTIMEDB_RELEASE_BUCKET_NAME }}/releases/${TAG} --recursive --exclude "*" --include "*.tgz"`
=> chore: rename tag github env

src/object-store/src/layers/lru_cache.rs
Don't cache `__last_checkpoint` file when enabling object store cache. It would cause SST files metadata error in region just like #2013 
Close #2013
=> fix: checkpoint metadata file dirty caching

Cargo.lock, src/mito2/Cargo.toml, src/mito2/src/error.rs, src/mito2/src/lib.rs, src/mito2/src/metadata.rs, src/mito2/src/read.rs, src/mito2/src/sst.rs, src/mito2/src/sst/file.rs, src/mito2/src/sst/parquet.rs, src/mito2/src/sst/parquet/reader.rs, src/mito2/src/sst/parquet/writer.rs, src/mito2/src/sst/stream_writer.rs, src/object-store/src/util.rs
This PR ports `ParquetWriter` and `ParquetReader` to mito2.
Modifications need to be aware:
- It removes `StoreSchema` and stores `RegionMetadata` to parquet file's metadata
- Adds `ParquetReaderBuilder` to build `ParquetReader`
- `ParquetReader` is lazily initialized
- Statistics are collected from sources.
=> feat(mito): Port parquet writer and reader to mito2

src/common/telemetry/Cargo.toml
Fix the unresolved `parking_log` issue.
```
Features of dependencies can also be enabled in the [features] table. The syntax is "package-name/feature-name".
```
https://doc.rust-lang.org/cargo/reference/features.html
=> fix: fix parking_lot unresolved

src/meta-srv/src/selector/lease_based.rs
This pr mainly change: arrange lease kvs randomly in lease_based selector, instead of pushing the latest lease kv to the forefront.
=> refactor: arrange lease kvs randomly in lease_based selector

src/storage/src/window_infer.rs
This PR changes the `min_duration_to_window_size` function in window inferer to ensure that the SST file or memtable will only be splitted to at most 128 (2^7) time windows, so that we won't stuck in iterating windows.
fixes #2023
=> fix: window inferer

src/datatypes/src/schema/constraint.rs, src/datatypes/src/vectors.rs
using `VectorOp::cast` refactor `create_current_timestamp_vector` function.
#2030
=> refactor: create_current_timestamp_vector by using VectorOp::cast 

src/common/grpc/src/writer.rs, src/servers/src/influxdb.rs, tests-integration/src/influxdb.rs
This PR allows `greptimedb` to accept influxdb request without timestamp even if a corresponding table doesn't exist.
close #1997
=> feat: accept influxdb request without timestamp even if table doesn't exist

docker/aarch64/compile-python.sh
The current release CI needs `aarch64/compile-python.sh` when compiling the arm64 greptime with pyo3 feature. However, the #2015 deletes this script because the new release ci(https://github.com/GreptimeTeam/greptimedb/pull/2038, unmerged and still take some time to review) doesn't need the script anymore. In order to fix the current failed releasing job, we need to restore the deleted file `aarch64/compile-python.sh`. 
**NOTE**: It's a **temporary fix** and will delete the file again when https://github.com/GreptimeTeam/greptimedb/pull/2038 merged.
=> fix: restore 'aarch64/compile-python.sh' to fix the failed release temporarily

.github/actions/build-dev-builder-image/action.yml, .github/actions/build-greptime-binary/action.yml, .github/actions/build-greptime-images/action.yml, .github/actions/build-images/action.yml, .github/actions/build-linux-artifacts/action.yml, .github/actions/build-macos-artifacts/action.yml, .github/actions/release-artifacts/action.yml, .github/actions/start-runner/action.yml, .github/actions/stop-runner/action.yml, .github/actions/upload-artifacts/action.yml, .github/scripts/create-version.sh, .github/workflows/release.yml, docker/centos/Dockerfile, docker/ubuntu/Dockerfile
It's almost the **rewrite** of `release.yml`.
The original `release.yml` has the following disadvantages:
- All the logic is coupled in one big yaml file, and hard to add the new artifact release;
- Lots of redundant logic, and always copy and paste the same logic;
- Lack of reproducible builds: the original `release.yml` uses cross-compiling to build the artifacts instead of Dockerfile;
- Don't support AWS EC2 instances to use larger instances;
The new `release.yml` use [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) to decouple the logic in `.github/actions/`
- **Start/Stop EC2 runners**
- `.github/actions/start-runner` …
=> feat: rewrite the release pipeline to make it clean

src/common/meta/src/key/table_name.rs, src/frontend/src/catalog.rs, src/meta-srv/src/service/admin/meta.rs
This pr mainly makes `tables()` method in `TableNameManager` return table name and table id at the same time.
=> chore: make `tables()` return kv instead of key only

.github/workflows/develop.yml
Pipeline before this change:
Where the sqlness and coverage will wait clippy to start. But they can be run in parallel.
Those requires were added in https://github.com/GreptimeTeam/greptimedb/pull/1093
=> chore(ci): run clippy, coverage and sqlness in parallel

src/mito2/src/config.rs, src/mito2/src/engine.rs, src/mito2/src/engine/tests.rs, src/mito2/src/error.rs, src/mito2/src/lib.rs, src/mito2/src/manifest/action.rs, src/mito2/src/manifest/manager.rs, src/mito2/src/manifest/storage.rs, src/mito2/src/region.rs, src/mito2/src/region/opener.rs, src/mito2/src/sst/parquet/writer.rs, src/mito2/src/test_util.rs, src/mito2/src/worker.rs, src/mito2/src/worker/handle_close.rs, src/mito2/src/worker/handle_create.rs, src/mito2/src/worker/handle_open.rs, src/mito2/src/worker/request.rs
This PR implements `open_region` and `close_region` for mito2 engine.
It also stops all regions while stopping the engine.
- #1869
=> feat(mito): Implement open and close for mito2 regions

docs/rfcs/2023-07-10-metric-engine.md
A new metric engine that can significantly enhance our ability to handle the tremendous number of small tables in scenarios like Prometheus metrics, by leveraging a synthetic wide table that offers storage and metadata multiplexing capabilities over the existing engine.
[rendered](https://github.com/waynexia/greptimedb/blob/rfc-metric-engine/docs/rfcs/2023-07-10-metric-engine.md)
=> docs: rfc of metric engine

Cargo.toml
This error casually occurs:
```
cargo build --locked --profile nightly --features servers/dashboard
Updating crates.io index
Updating git repository `https://github.com/waynexia/arrow-datafusion.git`
Updating git submodule `https://github.com/apache/parquet-testing.git`
Updating git submodule `https://github.com/apache/arrow-testing`
Updating git repository `https://github.com/GreptimeTeam/greptime-proto.git`
error: failed to get `greptime-proto` as a dependency of package `api v0.3.2 (/Users/runner/work/greptimedb/greptimedb/src/api)`
Caused by:
failed to load source for dependency `greptime-proto`
Caused by:
Unable to update …
```
=> fix(deps): update greptime-proto rev to the one after merge

Makefile
Add the missing 'TARGET' in Makefile.
=> fix: add the missing 'TARGET' in Makefile

Cargo.lock, src/common/greptimedb-telemetry/Cargo.toml, src/common/greptimedb-telemetry/src/lib.rs, src/common/meta/Cargo.toml
This patch removes openssl that introduced with reqwest
=> fix: remove openssl from reqwest and use rustls instead

.github/actions/build-macos-artifacts/action.yml
fix: incorrect argument name: 'disable_run_tests' -> 'disable-run-tests'
=> fix: incorrect argument name: 'disable_run_tests' -> 'disable-run-tests'

scripts/install.sh
The release CI(#2038) uses the different release package format:
1. Use `tar.gz` instead of `tgz`;
2. Use different directory layout, like:
```
greptime-darwin-arm64-v0.4.0-nightly-20230802
└── greptime
```
=> chore!: modify install.sh to adapt the new release package format

.github/actions/build-greptime-images/action.yml, .github/actions/build-images/action.yml, .github/scripts/create-version.sh, .github/workflows/nightly-build.yml
In order to make the release pipeline clean, I decided to add an independently scheduled workflow to build greptimedb every day of the week from Monday through Friday.
For the nightly build, the version is `nightly-YYYYMMDD-$(git rev-parse --short HEAD)`, like `nightly-20230712-e5b243c`. The build will run the integration tests and build binaries and images but not create a release. The build result will inform the Greptime team from Slack webhook.
Nightly build only do the following things:
1. **Run integration tests**;
2. Build binaries and images(**it doesn't push the latest tag**) for `linux-amd64` and `linux-arm64` platform;
=> ci: add nightly build workflow

src/common/catalog/src/lib.rs, src/datanode/src/instance.rs, src/datanode/src/instance/grpc.rs, src/datanode/src/server/grpc.rs, src/script/src/python/engine.rs, src/script/src/python/ffi_types/copr.rs, src/script/src/table.rs, src/servers/src/grpc/handler.rs, src/servers/src/http.rs, src/servers/src/http/admin.rs, src/servers/src/http/authorize.rs, src/servers/src/http/influxdb.rs, src/servers/src/http/opentsdb.rs, src/servers/src/http/otlp.rs, src/servers/src/http/prom_store.rs, src/servers/src/lib.rs, src/servers/src/mysql/handler.rs, src/servers/src/postgres/auth_handler.rs, src/servers/src/prometheus.rs, src/session/src/context.rs
1. move `parse_catalog_and_schema_from_client_database_name` to `common-catalog`
2. remove `QueryContext::arc()` usage in non-test code
#2083
=> fix: `arc()` usage in non-test code

.github/workflows/nightly-build.yml
Add the missing 'NIGHTLY_RELEASE_PREFIX' and fail fast in 'allocate-runners' job.
=> fix: add the missing 'NIGHTLY_RELEASE_PREFIX' and fail fast in 'allocate-runners' job

.github/workflows/develop.yml, Cargo.lock
Require cargo.lock up to date on `cargo check`
=> ci: require cargo.lock up to date

tests/runner/src/env.rs
Region failover makes the sqlness result unstable. It should be covered in chaos test instead of sqlness. I've verified this flag works:
```
24   │ 2023-08-04T08:15:47.597656Z  INFO cmd::metasrv: MetaSrv options: MetaSrvOptions {
25   │     bind_addr: "127.0.0.1:3002",
26   │     server_addr: "127.0.0.1:3002",
27   │     store_addr: "127.0.0.1:2379",
28   │     datanode_lease_secs: 15,
29   │     selector: LoadBased,
30   │     use_memory_store: true,
31   │     disable_region_failover: true,
32   │     http_opts: HttpOptions {
33   │         addr: "0.0.0.0:5001",
34   │         timeout: 30s,
35   │         disable_dashboard: true,
36   │         body_limit: ReadableSize(
37 …
```
=> fix: disable region failover in sqlness test

.github/workflows/nightly-build.yml
fix: fix version output empty error: '$GITHUB_ENV' -> '$GITHUB_OUTPUT'.
=> fix: fix version output empty error: '$GITHUB_ENV' -> '$GITHUB_OUTPUT'

src/catalog/src/remote/mock.rs, src/file-table-engine/src/engine/immutable.rs, src/mito/src/engine.rs, src/mito/src/engine/tests.rs, src/mito/src/table.rs, src/mito/src/table/test_util.rs, src/mito/src/table/test_util/mock_engine.rs, src/storage/src/engine.rs, src/storage/src/manifest/action.rs, src/storage/src/manifest/region.rs, src/storage/src/manifest/test_utils.rs, src/storage/src/region.rs, src/storage/src/region/tests.rs, src/storage/src/region/tests/truncate.rs, src/storage/src/region/writer.rs, src/storage/src/sst.rs, src/storage/src/version.rs, src/store-api/src/storage/engine.rs, src/store-api/src/storage/region.rs, src/table/src/engine.rs, src/table/src/table.rs, src/table/src/test_util/mock_engine.rs
1.  Implement reset version. 
2.  Implement truncate region.
1.  Acquires the `RegionWriter` lock.
2.  Create `RegionMetaAction::Truncate` to store `committed_sequence` and persist it for recovery from the manifest.
3.  Mark all data in the WAL as `obsolete`.
4.  Mark all SSTs as deleted.
5.  Reset Version. 
3.  Recover from `RegionMetaAction::Truncate`.
1.  Mark all SSTs as deleted.
2.  Reset the Version and set the `committed_sequence` from `RegionMetaAction::Truncate` as the Version's `flushed_sequence`.
=> feat: truncate region

src/cmd/src/cli/upgrade.rs, src/cmd/src/error.rs, src/common/meta/src/util.rs
1. add schema & catalog key migration tool
2. fix range pagination might lose keys bug
=> feat: add schema and catalog key migration tool

src/catalog/src/information_schema.rs, src/catalog/src/lib.rs, src/catalog/src/table_factory.rs, src/table/src/data_source.rs
* Add `DataSource` trait
* impl `DataSource` for `InformationTable`
* impl `table_factory` method for `InformationTable`
https://github.com/GreptimeTeam/greptimedb/issues/2065
=> feat(information_schema): implement `table_factory` method

src/meta-client/src/client.rs, src/meta-client/src/client/heartbeat.rs
1. Return metasrv leader address. 
It's used for test purposes, e.g., killing the leader's service after figuring out the leader's address.
=> feat: return metasrv leader addr

src/log-store/src/raft_engine/log_store.rs
This PR changes the prefix of reserved keys of logstore implementation based on raft-engine, in that later raft-engine releases use `__sys_` as their reserved prefix.
This is a breaking change that may corrupt existing data.
=> chore!: change logstore namespace prefix

.github/actions/build-greptime-binary/action.yml, .github/actions/build-linux-artifacts/action.yml, .github/actions/upload-artifacts/action.yml, .github/workflows/dev-build.yml
ci: add 'upload-to-s3' option and disable it in dev build
=> ci: add 'upload-to-s3' option and disable it in dev build

src/catalog/src/table_source.rs, src/datanode/src/instance/grpc.rs, src/datanode/src/instance/sql.rs, src/datanode/src/sql/create.rs, src/frontend/src/instance.rs, src/frontend/src/instance/distributed.rs, src/frontend/src/instance/prom_store.rs, src/query/src/datafusion.rs, src/query/src/sql.rs, src/servers/src/grpc/handler.rs, src/servers/src/mysql/federated.rs, src/servers/tests/http/influxdb_test.rs, src/servers/tests/http/prom_store_test.rs, src/session/src/context.rs
Change current `schema` and `catalog` to borrow, clone only when necessary.
There are breaking changes, so I leave the decision up to you.
Breaking changes: 
src/session/src/context.rs
```rust
#[inline]
pub fn current_schema(&self) -> String {
self.current_schema.clone()
}
#[inline]
pub fn current_catalog(&self) -> String {
self.current_catalog.clone()
}
```
into 
```rust
#[inline]
pub fn current_schema(&self) -> &str {
&self.current_schema
}
#[inline]
pub fn current_catalog(&self) -> &str {
&self.current_catalog
}
```
=> perf: change current schema and catalog to borrow, clone only necessary

src/mito2/src/manifest/manager.rs, src/mito2/src/memtable.rs, src/mito2/src/memtable/key_values.rs, src/mito2/src/metadata.rs, src/mito2/src/request.rs
Adds the `write()` method to the `Memtable` trait.
The `write()` method takes `KeyValues` as input. `KeyValues` helps the memtable view the rows in key (primary key,  or tags) and value (fields) form.
It also validates the semantic type of each column to ensure all tag columns are primary key columns.
=> feat: Add write method to memtable trait

src/datanode/src/lib.rs
Fix compilation flag for mock module
=> test: add conditional compilation flag for datanode mock module

.github/workflows/dev-build.yml
fix: set the correct working dir before building the artifacts
=> fix: set the correct working dir before building the artifacts

src/query/Cargo.toml, src/query/src/optimizer/type_conversion.rs
`TypeConversionRule` used to get schema by `all_schemas` which is incorrect. It will resolve some column types to None and skip the rule. The new case `test_retrieve_type_from_aggr_plan` provides an example.
And this PR fixes the misuse of `assert!(matches!())` in tests BTW
=> fix: correct the schema used by TypeConversionRule

src/catalog/src/information_schema.rs, src/catalog/src/system.rs, src/frontend/src/table.rs, src/query/src/dist_plan/analyzer.rs, src/query/src/tests/time_range_filter_test.rs, src/table/src/table.rs, src/table/src/table/numbers.rs, src/table/src/test_util/empty_table.rs, src/table/src/test_util/memtable.rs, tests-integration/src/tests/instance_test.rs, tests/cases/distributed/optimizer/order_by.result
* remove default impl of `table_type` method
* check and reimplement `table_type` for `Table`s
- `numbers` as temporary table
- `schema_information` as temporary table
=> fix(table): return correct table types

Cargo.lock, Cargo.toml, src/common/function/src/scalars/function_registry.rs, src/common/function/src/scalars/math.rs, src/frontend/Cargo.toml, src/frontend/src/instance.rs, src/query/Cargo.toml, src/query/src/error.rs, src/query/src/planner.rs, src/query/src/query_engine/state.rs, src/query/src/range_select.rs, src/query/src/range_select/plan.rs, src/query/src/range_select/plan_rewrite.rs, src/query/src/range_select/planner.rs, src/sql/src/statements/statement.rs
Support RangeSelect in greptimedb
- Change sqlparser  to newer version which can parse range select grammar
- use `Into` trait implement by newer sqlparser to convert sqlparser structure to datafusion's sqlparser structure, so we can still use datafusion to gererate logical plan
- Implement Logical plan rewriter, It will:
1. recursive trace the logical plan tree, find projection plan with scalar udf function `range_fn`
2. collect all argument in `range_fn` to generate RangeSelect plan
3. insert RangeSelect plan to logical plan tree
4. finish logical plan rewrite
5. notice: if a logical plan …
=> feat: Support RangeSelect LogicalPlan rewrite

src/servers/src/grpc/handler.rs, src/servers/src/http.rs, src/servers/src/metrics.rs
This patch fixes metric label regression:
- fix db label for grpc database requests (misconfigured on `code` now)
- unified `status` and `code` labels, which have same semantic
=> fix: correct grpc metric labels

.github/actions/upload-artifacts/action.yml
ci: add retry for uploading artifacts to s3.
=> ci: add retry for uploading artifacts to s3

src/common/time/src/duration.rs, src/common/time/src/lib.rs
Add `Duration` type in `common-time`.
=> feat: impl duration type

src/catalog/src/information_schema.rs, src/catalog/src/information_schema/columns.rs, src/catalog/src/information_schema/tables.rs, src/catalog/src/lib.rs, src/catalog/src/local/manager.rs, src/catalog/src/local/memory.rs, src/catalog/src/remote/manager.rs, src/catalog/src/table_source.rs, src/catalog/tests/remote_catalog_tests.rs, src/common/catalog/src/consts.rs, src/datanode/src/instance.rs, src/frontend/src/catalog.rs, src/frontend/src/instance/distributed.rs, src/promql/src/planner.rs, src/query/src/dist_plan/planner.rs, src/query/src/range_select/plan_rewrite.rs, src/query/src/sql.rs, src/query/src/sql/show_create_table.rs, src/query/src/tests.rs, src/script/benches/py_benchmark.rs, src/script/src/python/engine.rs, src/servers/tests/mod.rs, src/table-procedure/src/test_util.rs, tests-integration/src/tests.rs, tests-integration/src/tests/instance_test.rs, tests/cases/standalone/common/show/show_databases_tables.result, tests/cases/standalone/common/show/show_databases_tables.sql, tests/cases/standalone/common/system/information_schema.result, tests/cases/standalone/common/system/information_schema.sql
makes `SHOW DATABASES`/`information_schema.tables`/`information_schema.columns` know themselves.
There are some dumb if-else branches for `FrontendCatalogManager`.
=> fix: let information_schema know itself

.github/workflows/develop.yml
=> fix: runs sqlness test on windows-latest-8-cores

src/servers/src/postgres/types.rs, src/servers/src/postgres/types/interval.rs
implement `common_time::interval` convert to/from `postgres interval` using `PgInterval`
https://github.com/GreptimeTeam/greptimedb/pull/1952#discussion_r1272953575
Closes: https://github.com/GreptimeTeam/greptimedb/issues/2098
=> feat: compatible with postgres interval type

Makefile, src/meta-srv/src/bootstrap.rs, src/script/src/python/pyo3/builtins.rs, src/script/src/python/pyo3/copr_impl.rs, src/servers/src/lib.rs, src/servers/src/postgres/auth_handler.rs
- Fix clippy errors in pyo3 module
- Fix warnings `clippy::needless-pass-by-ref-mut`
rust toolchain is upgraded in https://github.com/GreptimeTeam/greptimedb/pull/2049
=> fix: several clippy error/warnings after upgrading toolchain

Cargo.lock, config/datanode.example.toml, config/metasrv.example.toml, config/standalone.example.toml, src/cmd/Cargo.toml, src/cmd/src/datanode.rs, src/cmd/src/standalone.rs, src/common/greptimedb-telemetry/Cargo.toml, src/common/greptimedb-telemetry/src/lib.rs, src/datanode/Cargo.toml, src/datanode/src/datanode.rs, src/datanode/src/greptimedb_telemetry.rs, src/datanode/src/instance.rs, src/datanode/src/lib.rs, src/datanode/src/store.rs, src/datanode/src/store/fs.rs, src/datanode/src/tests/test_util.rs, src/meta-srv/Cargo.toml, src/meta-srv/src/greptimedb_telemetry.rs, src/meta-srv/src/lib.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/metasrv/builder.rs, tests-integration/src/cluster.rs, tests-integration/src/test_util.rs, tests-integration/src/tests.rs, tests-integration/tests/http.rs, tests-integration/tests/region_failover.rs
Main changes:
* Remove the `greptimedb-telemetry` feature in metasrv and datanode.
* Adds new option `enable_telemetry` to datanode and metasrv configurations, `true` by default.
* Move `data_home` from `FileConfig` to `StorageConfig` in datanode.
* Adds `data_home` to metasrv options.
* Store the installation uuid into `data_home` directory in datanode and metasrv.
* Print warning log when enabling telemetry.
=> feat!: enable telemetry by default

Cargo.lock, src/log-store/Cargo.toml
So, the story is that I want to build the greptimedb on my computer(Apple M1 & macOS 13.4.1 & libprotoc 23.4),
and I got an Error!
```
--- stderr
thread 'main' panicked at 'No suitable `protoc` (>= 3.1.0) found in PATH', 
/Users/xiezheng/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/protobuf-build-0.14.1/src/protobuf_impl.rs:35:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I go checked the source code in protobuf-build(v0.14.1)
```rust
// The bundled protoc should always match the version
let protoc_bin_name = match (env::consts::OS, env::consts::ARCH) {
("linux", "x86") => "protoc-linux-x86_32",
("linux", "x86_64") => …
```
=> build: update protobuf-build to support apple silicon

src/mito2/src/engine.rs, src/mito2/src/error.rs, src/mito2/src/memtable.rs, src/mito2/src/memtable/key_values.rs, src/mito2/src/memtable/version.rs, src/mito2/src/proto_util.rs, src/mito2/src/region.rs, src/mito2/src/region/version.rs, src/mito2/src/request.rs, src/mito2/src/worker.rs, src/mito2/src/worker/handle_write.rs
This PR writes data into WAL and memtables. It validates write requests before writing them.
The worker collects requests from different regions and writes them to the WAL in one batch.
To handle schema change, it fills default values before sending the request to the writer. Inside the writer, if the request still misses some columns, the writer pads default values again. This is possible if the write request comes during altering schema.
- #1869
=> feat(mito): Write wal and memtable

src/cmd/src/metasrv.rs, src/meta-srv/src/error.rs, tests/runner/src/env.rs
Before this patch, `use_memory_store` and `disable_region_failover` cannot be set via config file or env because they will always be overwritten by cli options, even if it's not provided in cli args.
=> fix(metasrv)!: do not overwrite boolean options unconditionally

src/catalog/src/error.rs, src/catalog/src/remote/manager.rs, src/catalog/tests/remote_catalog_tests.rs, src/cmd/src/cli.rs, src/common/meta/src/helper.rs, src/common/meta/src/key.rs, src/common/meta/src/key/catalog_name.rs, src/common/meta/src/key/schema_name.rs, src/common/meta/src/lib.rs, src/datanode/src/instance.rs, src/frontend/src/catalog.rs, src/frontend/src/instance/distributed.rs, src/frontend/src/instance/distributed/inserter.rs, src/meta-srv/src/error.rs, src/meta-srv/src/metadata_service.rs, src/meta-srv/src/metasrv/builder.rs, src/meta-srv/src/mocks.rs, src/meta-srv/src/service/admin.rs, src/meta-srv/src/service/admin/meta.rs, tests-integration/src/cluster.rs
switch to new catalog/schema key
close #2024
=> feat!: switch to new catalog/schema key

Cargo.lock, src/cmd/Cargo.toml, src/cmd/src/cli/upgrade.rs, src/common/meta/src/error.rs, src/common/meta/src/key.rs, src/common/meta/src/key/table_route.rs, src/common/meta/src/rpc/router.rs, src/common/meta/src/rpc/store.rs, src/frontend/src/table.rs
1. Add table route manager (for the new implementation, i.e., `__table_route/{TableId}`)
2. Add table route  upgrade tool
close #1986
=> feat: add table route manager and upgrade tool

Cargo.lock, src/frontend/src/instance.rs, src/servers/src/mysql/handler.rs, src/servers/src/mysql/writer.rs, src/sql/Cargo.toml, src/sql/src/lib.rs, src/sql/src/util.rs
The SQL will be printed in logs as is when it executes with an error, this could leak sensetive secrets. For example, the following SQL contains access key to S3:
```sql
COPY 'my_table' FROM '/test.orc' WITH (FORMAT = 'orc') CONNECTION(ENDPOINT = 's3.storage.site', REGION = 'hz', ACCESS_KEY_ID='my_key_id', SECRET_ACCESS_KEY="my_access_key");
```
This PR redacted the secrets in sql when logging. After redacted, the above sql is seen as
```sql
COPY 'my_table' FROM '/test.orc' WITH (FORMAT = 'orc') CONNECTION(ENDPOINT = 's3.storage.site', REGION = 'hz', ACCESS_KEY_ID='******', SECRET_ACCESS_KEY="******");
```
in logs.
Redaction is simply done by regex pattern matching on common …
=> feat: redact secrets in sql when logging

Cargo.lock, src/common/time/src/timestamp.rs, src/datatypes/src/value.rs, src/mito2/Cargo.toml, src/mito2/src/error.rs, src/mito2/src/lib.rs, src/mito2/src/row_converter.rs
This PR:
- implements memory comparable encoding/decoding for time series keys.
=> feat: row wise converter

src/common/greptimedb-telemetry/src/lib.rs
Print the disclaimer at the wrong place, it must be printed only when enabling telemetry.
=> fix: print_anonymous_usage_data_disclaimer at wrong place

src/servers/src/otlp.rs, tests-integration/src/otlp.rs
Fixes a bug that some column name didn't get normalized. Test cases added.
=> fix: normalize otlp string keys

src/common/meta/src/rpc/router.rs, src/frontend/src/instance/distributed.rs, src/partition/src/partition.rs
Add custom deserializer for `Partition`
=> feat!: add deserializer for Partition

src/mito2/src/error.rs, src/mito2/src/read.rs, src/mito2/src/sst/parquet/writer.rs, src/mito2/src/sst/stream_writer.rs
Defines the new read Batch struct. This struct can hold rows for the same time series.
It also replaces `SchemaRef` and `Batch` in `BufferedWriter` with arrow's `SchemaRef` and `RecordBatch`. I plan to implement the conversion between `Batch` and `RecordBatch` outside of the `BufferedWriter`.
- #1869
=> feat(mito): Defines the read Batch struct for mito2

Cargo.lock, Cargo.toml, src/api/src/helper.rs, src/client/src/database.rs, src/common/grpc-expr/src/delete.rs, src/datanode/src/instance/grpc.rs, src/frontend/src/error.rs, src/frontend/src/instance/distributed.rs, src/frontend/src/instance/distributed/deleter.rs, src/frontend/src/instance/grpc.rs, src/frontend/src/table.rs, src/frontend/src/table/delete.rs, src/frontend/src/table/scan.rs, src/mito/src/engine/tests.rs, src/mito/src/table.rs, src/partition/src/manager.rs, src/partition/src/splitter.rs, src/query/src/datafusion.rs, src/servers/tests/mod.rs, src/table/src/requests.rs, tests-integration/src/grpc.rs
This PR allows `greptimedb` to handle multiple grpc deletes.
close #1708
=> feat: handle multiple grpc deletes

docs/rfcs/2023-08-13-metadata-txn.md
The RFC of update metadata in single txn
#1715
=> docs: rfc of update metadata in single txn

src/datanode/src/greptimedb_telemetry.rs, src/meta-srv/src/greptimedb_telemetry.rs
Don't enable telemetry for debug builds.
=> feat: don't enable telemetry for debug building

.github/workflows/develop.yml
Cancel in-progress actions on new commit is pushed. Try to save some 💸
Ref:
https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
=> ci: cancel in-progress actions on new commit

.github/workflows/develop.yml
According to https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
And https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
We should use
```
${{ github.workflow }}-${{ github.head_ref || github.run_id }}
```
> For example, github.head_ref is only defined on pull_request events. If your workflow responds to other events in addition to pull_request events, you will need to provide a fallback to avoid a syntax error. The following concurrency group cancels in-progress jobs or runs on pull_request events only; if github.head_ref is undefined, the concurrency group …
=> ci: fallback to run_id to avoid cancelling other jobs

src/catalog/src/lib.rs
This pr mainly fixes invoking `region_stat()` on information schema
=> chore: fix collect region stat on non-base table

src/common/recordbatch/src/adapter.rs, src/frontend/src/statement/copy_table_from.rs, tests-integration/src/tests/instance_test.rs
Support to copy from parquet with typecast
fix #2199
=> fix: support to copy from parquet with typecast

src/meta-client/src/client.rs, src/meta-client/src/client/ask_leader.rs, src/meta-client/src/client/ddl.rs, src/meta-client/src/client/heartbeat.rs, src/meta-client/src/error.rs
Fix DDL client can not update leader address
=> fix: fix ddl client can not update leader addr

src/common/meta/src/key.rs, src/frontend/src/instance/distributed.rs, src/meta-srv/src/procedure/create_table.rs, tests-integration/src/tests/instance_test.rs, tests/cases/distributed/show/show_create.result
This PR fixes that table options can't be found in distributed mode.
close #1433
=> fix: table options can't be found in distributed mode

src/frontend/src/error.rs, src/frontend/src/instance/distributed.rs, src/frontend/src/statement.rs, src/frontend/src/statement/copy_table_from.rs, src/frontend/src/statement/insert.rs, src/frontend/src/table.rs
In the frontend, for all `table.insert` operations, either directly use DistInserter if the table is a DistTable, or wrap the call with `send_insert_request` to await further refactoring in the future.
For the frontend statement executor, manual handling of subqueries is needed for insert operations to avoid direct invocation of the query engine, eliminating the need for a call to table.insert.
=> refactor(table): eliminate calls to DistTable.insert

src/datanode/src/region_server.rs, src/mito2/src/engine.rs, src/mito2/src/engine/tests.rs, src/mito2/src/request.rs, src/mito2/src/test_util.rs, src/mito2/src/worker.rs, src/mito2/src/worker/handle_write.rs, src/store-api/src/region_request.rs
#2160 breaks implementation of `write_region()`. This PR support writing a region again.
It reuses the old `WriteRequest` as it is more friendly to implementing write than the plain `RegionWriteRequest`. The `RegionTask` now holds a `RequestBody` and we convert `RegionWriteRequest` to `WriteRequest` before sending it to the worker. As a result, we can do some validation outside of the worker.
This PR also fixes all engine tests.
- #1869 
- #2160
=> feat(mito): Support handling RegionWriteRequest

config/datanode.example.toml, config/standalone.example.toml, src/cmd/src/datanode.rs, src/cmd/src/options.rs, src/cmd/src/standalone.rs, src/datanode/src/datanode.rs, src/storage/src/config.rs, src/storage/src/manifest/region.rs, src/storage/src/region.rs, tests-integration/tests/http.rs
* Removed `checkpoint_on_startup`, it's an outdated option. When introducing the checkpoint feature for manifest, we want to trigger a checkpoint at startup.
* Added some logs for debugging #2013
=> feat: remove checkpoint_on_startup

src/mito2/src/error.rs, src/mito2/src/memtable/time_series.rs
Use `Batch::sort_and_dedup` to sort the batches yielded by `TimeSeriesMemtable` instead of `Values::sort_in_place` and add some tests for this.
=> refactor: use Batch::sort_and_dedup instead of Values::sort_in_place

src/catalog/src/remote/region_alive_keeper.rs, src/catalog/tests/remote_catalog_tests.rs, src/datanode/src/tests.rs
use table id instead of table ident
=> refactor: use table id instead of table ident

src/datatypes/src/error.rs, src/datatypes/src/value.rs
Add some `try_from` for Value's different variants, also add `from` for OrderedFloat32/64
add convenient methods to convert between values and primitive datatypes.
- Summarize your change
i.e. `i64::try_from(value)` is possible now
=> chore: try from value

src/frontend/src/instance/distributed.rs
Invalidate cache after altering
=> fix: invalidate cache after altering

src/script/src/error.rs, src/script/src/table.rs
parse-plan-execute instead of directly calling the removing `scan_to_stream`
https://github.com/GreptimeTeam/greptimedb/issues/2065
=> refactor(script): not to call `scan_to_stream` on table

src/frontend/src/statement.rs, src/frontend/src/statement/backup.rs, src/frontend/src/statement/copy_table_to.rs, src/table/src/engine.rs
Similar to #2241, replace the invocation of `scan_to_stream` with constructing a TableScan LogicalPlan, and then execute it using the query engine.
https://github.com/GreptimeTeam/greptimedb/issues/2065
=> refactor(frontend): TableScan instead of `scan_to_stream` for `COPY TO`

src/mito2/src/schedule/scheduler.rs
if  parameter await_termination of fn stop in LocalScheduler is true, scheduler will wait all tasks finished before stopping.
=> fix: fix test_scheduler_continuous_stop in scheduler

src/catalog/src/remote/manager.rs
Fix RegionAliveKeeper does not find the table after restarting
=> fix: fix RegionAliveKeeper does not find the table after restarting

src/mito2/src/error.rs, src/mito2/src/memtable/time_series.rs
- Use `arrow::compute::concat` to concat vectors in memtable
- Respect projection
=> feat(mito2): concat and projection

src/datanode/src/instance/sql.rs, src/frontend/src/instance/distributed.rs, src/query/src/sql.rs, src/query/src/sql/show_create_table.rs, src/servers/src/error.rs, src/sql/src/error.rs, src/sql/src/statements/create.rs, tests-integration/src/tests/instance_test.rs, tests/cases/distributed/show/show_create.result, tests/cases/standalone/show/show_create.result
When the table name or column name is a keyword, it should be quoted for escaping in `SHOW CREATE TABLE`. This patch adds quotes to every ident *unconditionally*. E.g.:
```sql
CREATE TABLE IF NOT EXISTS `xxx` (
`ts` TIMESTAMP(3) NOT NULL,
`mid` STRING NULL,
`bvid` STRING NULL,
`cid` DOUBLE NULL,
`up` STRING NULL,
`view` DOUBLE NULL,
`danmaku` DOUBLE NULL,
`favorite` DOUBLE NULL,
`coin` DOUBLE NULL,
`reply` DOUBLE NULL,
`share` DOUBLE NULL,
`like` DOUBLE NULL,
`fans` DOUBLE NULL,
`watchingcount` DOUBLE NULL,
TIME INDEX (`ts`),
PRIMARY KEY (`mid`, `bvid`)
)
ENGINE=mito
WITH(
regions = 1
)
```
=> fix: quote ident on rendered SQL

src/frontend/src/instance.rs, src/servers/src/grpc.rs, src/servers/src/grpc/prom_query_gateway.rs, src/servers/src/http.rs, src/servers/src/http/admin.rs, src/servers/src/http/authorize.rs, src/servers/src/http/handler.rs, src/servers/src/http/influxdb.rs, src/servers/src/http/opentsdb.rs, src/servers/src/http/otlp.rs, src/servers/src/http/prom_store.rs, src/servers/src/http/prometheus.rs, src/servers/src/lib.rs, src/servers/src/prometheus.rs, src/servers/src/prometheus_handler.rs, src/servers/tests/http/authorize.rs, src/servers/tests/http/http_handler_test.rs, tests-integration/tests/grpc.rs, tests-integration/tests/http.rs
1. change from `Extension<UserInfoRef>` to `Extension<QueryContextRef>` in http Axum handler's signature. `QueryContext` shouldn't be constructed in normal logic code, it should be setup carefully in framework code.
2. move Axum handler related code from `servers/src/prometheus` to `servers/src/http/prometheus` and rename origin file to `prometheus_handler`
=> refactor: query_ctx from http middleware

Cargo.lock, Cargo.toml, src/servers/src/mysql/federated.rs
Change the db version in develop branch to `0.4.0-nightly`.
=> chore: change version to 0.4.0-nightly

src/mito/src/table.rs
Align region numbers to real regions
=> fix: align region numbers to real regions

config/metasrv.example.toml, src/meta-srv/src/metasrv.rs
Set default metasrv procedure retry times to 12
| Delay(s) | Time | Retry Delay(s) | Acc Delay(s) | Procedure(s) | Start(s) | End(s) | Start(m) | End(m) |
| -------- | ---- | -------------- | ------------ | ------------ | -------- | ------ | -------- | ------ |
| 0.5      | 1    | 0.5            | 1            | 30           | 1        | 31     | 0.0      | 0.5    |
|          | 2    | 1              | 1.5          | 60           | 1.5      | 61.5   | 0.0      | 1.0    |
|          | 3    | 2              | 3.5          | 90           | 3.5      | 93.5   | 0.1      | 1.6    |
|          | 4    | 4              | 7.5          | 120          | 7.5      | 127.5  | 0.1      | …
=> refactor: set default metasrv procedure retry times to 12

src/meta-srv/src/procedure/region_failover.rs, src/meta-srv/src/procedure/region_failover/activate_region.rs, src/meta-srv/src/procedure/region_failover/deactivate_region.rs, src/meta-srv/src/procedure/region_failover/failover_end.rs, src/meta-srv/src/procedure/region_failover/failover_start.rs, src/meta-srv/src/procedure/region_failover/invalidate_cache.rs, src/meta-srv/src/procedure/region_failover/update_metadata.rs
Change the region failover procedure state transition from owned `self` to borrowed `&mut self`. To prevent the state from not being correctly set if any error happened during procedure execution. See the test.
=> fix: keep region failover state not changed upon failure

src/catalog/src/local/memory.rs, src/datanode/src/heartbeat/handler/open_region.rs, src/datanode/src/tests.rs
open region does not register catalog/schema
=> fix: open region does not register catalog/schema

Cargo.lock, Cargo.toml, src/api/src/helper.rs, src/client/Cargo.toml, src/client/src/client.rs, src/client/src/lib.rs, src/client/src/metrics.rs, src/client/src/region.rs, src/common/catalog/src/consts.rs, src/common/datasource/Cargo.toml, src/common/error/Cargo.toml, src/frontend/src/instance.rs, src/frontend/src/row_inserter.rs, src/meta-srv/Cargo.toml, src/meta-srv/src/error.rs, src/meta-srv/src/metrics.rs, src/meta-srv/src/procedure/create_table.rs, src/meta-srv/src/procedure/region_failover/update_metadata.rs, src/meta-srv/src/table_routes.rs, src/meta-srv/src/test_util.rs, src/mito2/Cargo.toml, src/servers/Cargo.toml, src/servers/src/grpc.rs, src/servers/src/grpc/greptime_handler.rs, src/servers/src/grpc/region_server.rs, src/sql/src/parsers/create_parser.rs, src/table/src/engine.rs
Create distributed Mito2 table.
If "`engine = mito2`" is in the create table SQL, create the Mito2 table. Otherwise create the original Mito table.
Note that since the Mito2 region is not able to be actually created on Datanodes now, there are no complete create Mito2 table tests. I only mock the region server's grpc interfaces in the unit tests. Once the region server is ready on Datanode, it's easy to really test it.
This PR also ships with a region server client.
#2213
=> feat: create distributed Mito2 table

src/frontend/src/instance/distributed.rs, src/meta-srv/src/procedure/region_failover/update_metadata.rs, src/meta-srv/src/service/ddl.rs
use RegionId region number instead
=> fix: use RegionId region number instead

src/catalog/src/local/manager.rs, src/catalog/src/system.rs, src/catalog/src/tables.rs
* Remove `impl Table for SystemCatalogTable`
* Move down methods like `register_table` to `SystemCatalogTable`
https://github.com/GreptimeTeam/greptimedb/issues/2065
=> refactor(table): remove Table impl for system

.github/actions/build-greptime-binary/action.yml, .github/actions/build-linux-artifacts/action.yml, .github/actions/upload-artifacts/action.yml, .github/workflows/nightly-build.yml
Upload the latest artifacts to 'latest/' directory of S3 bucket in scheduled and formal release. It's easy to download the latest binary from S3 without any GitHub APIs or list operations.
=> ci: upload the latest artifacts to 'latest/' directory of S3 bucket in scheduled and formal release

src/catalog/src/local/memory.rs, src/catalog/src/remote/manager.rs, src/catalog/src/remote/region_alive_keeper.rs, src/datanode/src/tests.rs
Deregister table after keeper closes the table
=> fix: deregister table after keeper closes table

Cargo.lock, Cargo.toml, src/cmd/src/cli/upgrade.rs, src/common/meta/Cargo.toml, src/common/meta/src/error.rs, src/common/meta/src/key/schema_name.rs, src/common/procedure/Cargo.toml, src/datanode/Cargo.toml, src/datanode/src/instance/grpc.rs, src/frontend/Cargo.toml, src/frontend/src/instance/distributed.rs, src/frontend/src/instance/distributed/inserter.rs, src/meta-srv/src/metadata_service.rs, src/servers/Cargo.toml, src/table/Cargo.toml, tests-integration/src/grpc.rs
This pr mainly adds
1. `SchemaNameValue` which contains `ttl` option for schema(persisted at etcd)
2. merge ttl option while creating table
**discussion: should we rename `SchemaNameValue` to something else?**
wait for https://github.com/GreptimeTeam/greptime-proto/pull/93 to be merge first
=> feat: schema level opts

src/mito2/src/access_layer.rs, src/mito2/src/config.rs, src/mito2/src/engine.rs, src/mito2/src/flush.rs, src/mito2/src/lib.rs, src/mito2/src/read/scan_region.rs, src/mito2/src/read/seq_scan.rs, src/mito2/src/region.rs, src/mito2/src/region/opener.rs, src/mito2/src/schedule/scheduler.rs, src/mito2/src/sst/file_purger.rs, src/mito2/src/sst/parquet/writer.rs, src/mito2/src/test_util.rs, src/mito2/src/worker.rs, src/mito2/src/worker/handle_create.rs, src/mito2/src/worker/handle_open.rs
This PR integrates `AccessLayer` and `FilePurger` to each mito region.
- #1869
=> feat(mito): Integrate access layer and file purger to region

Cargo.lock, src/mito2/Cargo.toml, src/mito2/src/error.rs, src/mito2/src/schedule/scheduler.rs
Replace flume with async channel. `flume` might lose the last message and hang the test `test_scheduler_many()`. See https://github.com/zesterer/flume/issues/124 for a similar issue.
- https://github.com/zesterer/flume/issues/124
=> fix: flume bug

src/common/error/src/status_code.rs, src/meta-srv/src/error.rs, src/meta-srv/src/metrics.rs, src/meta-srv/src/procedure/create_table.rs, src/meta-srv/src/procedure/drop_table.rs, src/meta-srv/src/procedure/utils.rs, src/servers/src/error.rs
Drop distributed Mito2 table.
If "`engine = mito2`" is in the table info, drop the Mito2 table. Otherwise drop the original Mito table.
Note that since the Mito2 region is not able to be actually created on Datanodes now, there are no complete drop Mito2 table tests. I only mock the region server's grpc interfaces in the unit tests. Once the region server is ready on Datanode, it's easy to really test it.
#2254
=> feat: drop distributed Mito2 table

Cargo.lock, Cargo.toml, src/catalog/src/lib.rs, src/catalog/src/remote/region_alive_keeper.rs, src/datanode/src/heartbeat.rs, src/meta-srv/src/handler.rs, src/meta-srv/src/handler/failure_handler.rs, src/meta-srv/src/handler/node_stat.rs, src/meta-srv/src/handler/persist_stats_handler.rs, src/meta-srv/src/handler/region_lease_handler.rs, src/meta-srv/src/keys.rs, src/meta-srv/src/selector/load_based.rs
New heartbeat
See https://github.com/GreptimeTeam/greptime-proto/pull/96
=> feat: new heartbeat

Cargo.lock, src/common/meta/src/kv_backend/memory.rs, src/log-store/Cargo.toml, src/log-store/src/error.rs, src/log-store/src/lib.rs, src/log-store/src/raft_engine.rs, src/log-store/src/raft_engine/backend.rs, src/log-store/src/raft_engine/log_store.rs
This PR implements `KvBackend` based on kv-api provided by raft-engine.
closes #2215
=> feat: impl kv backend for raft engine

src/mito2/src/engine/tests.rs, src/mito2/src/request.rs
This PR supports deleting rows by primary key and time index in mito2.
It also adds tests for deleting and overwriting rows.
- #1869
=> feat(mito): Support deleting rows in mito2

Cargo.lock, Cargo.toml, src/meta-srv/src/handler/node_stat.rs, src/meta-srv/src/handler/region_lease_handler.rs, src/meta-srv/src/inactive_node_manager.rs, src/meta-srv/src/keys.rs
use region_id instead of table_id&region_num
=> refactor: inactive node manager

src/mito2/src/lib.rs, src/mito2/src/memtable.rs, src/mito2/src/memtable/time_series.rs, src/mito2/src/metrics.rs
This PR:
- adds `stats` method for `MemTable` trait
- implements `stats` method for `TimeSeriesMemtable`
=> feat(mito2): add alloc_tracker for memtable

src/mito2/src/flush.rs, src/mito2/src/memtable.rs, src/mito2/src/memtable/time_series.rs, src/mito2/src/read/seq_scan.rs
Remove ScanRequest from Memtable API
=> feat: remove memtable request

src/mito2/src/manifest/storage.rs
Return an empty result if the manifest directory is not created when scanning actions.
Try to fix #2288 
Close #2288
=> fix: don't raise an error when manifest directory is not created

src/mito2/src/flush.rs, src/mito2/src/memtable.rs, src/mito2/src/memtable/time_series.rs, src/mito2/src/memtable/version.rs, src/mito2/src/worker.rs, src/mito2/src/worker/handle_flush.rs
This PR ports the `WriteBufferManager` from the old mito engine to mito2.
- #1869
=> feat: Impl write buffer manager for mito2

src/common/meta/src/instruction.rs, src/meta-srv/src/error.rs, src/meta-srv/src/handler/region_lease_handler.rs, src/meta-srv/src/inactive_region_manager.rs, src/meta-srv/src/keys.rs, src/meta-srv/src/lib.rs, src/meta-srv/src/procedure/region_failover/activate_region.rs, src/meta-srv/src/procedure/region_failover/deactivate_region.rs, src/meta-srv/src/service/admin.rs, src/meta-srv/src/service/admin/inactive_regions.rs, src/meta-srv/src/service/admin/node_lease.rs, src/meta-srv/src/service/admin/util.rs
1. Add metric for InactiveRegionKey
2. Add admin(http api) for view and clear
=> feat: add metric and manage tool for InactiveRegionKey

src/common/error/src/status_code.rs, src/mito2/src/engine.rs, src/mito2/src/engine/close_test.rs, src/mito2/src/engine/create_test.rs, src/mito2/src/engine/drop_test.rs, src/mito2/src/engine/open_test.rs, src/mito2/src/engine/tests.rs, src/mito2/src/error.rs, src/servers/src/error.rs
Finish those todos in `impl RegionEngine for MitoEngine`
=> feat: adapt methods from RegionEngine for MitoEngine

src/common/time/src/timestamp.rs, src/datatypes/src/schema/column_schema.rs, src/datatypes/src/schema/constraint.rs
This PR avoids allocating a vector to get a default value for a column. It creates the default value directly.
=> feat: avoid using vector to get default value

src/api/src/helper.rs, src/frontend/src/error.rs, src/frontend/src/inserter.rs, src/frontend/src/inserter/req_convert.rs, src/frontend/src/inserter/req_convert/column_to_row.rs, src/frontend/src/inserter/req_convert/row_to_region.rs, src/frontend/src/inserter/req_convert/stmt_to_region.rs, src/frontend/src/inserter/req_convert/table_to_region.rs, src/frontend/src/instance/distributed.rs, src/frontend/src/instance/distributed/inserter.rs, src/frontend/src/statement.rs
* Move all converters of insert request to `frontend::inserter::req_convert::*`
* Add Statement to Region Request converter
https://github.com/GreptimeTeam/greptimedb/pull/2318#discussion_r1314519281
=> feat(frontend): reorg insert converters and introduce stmt_to_region

src/mito2/src/engine.rs, src/mito2/src/lib.rs, src/mito2/src/manifest.rs, src/mito2/src/manifest/action.rs, src/mito2/src/manifest/manager.rs, src/mito2/src/manifest/storage.rs, src/mito2/src/manifest/tests/checkpoint.rs, src/mito2/src/region.rs, src/mito2/src/schedule/scheduler.rs, src/mito2/src/worker/handle_flush.rs
Remove `#[allow(xxx)]` in mito2 as much as possible
Fix: update region flushed time on flush is finished.
=> refactor: clean unnecessary disabled lints

src/catalog/src/remote/client.rs, src/client/src/region.rs, src/common/meta/src/error.rs, src/common/meta/src/lib.rs, src/common/meta/src/state_store.rs, src/log-store/src/raft_engine/backend.rs, src/meta-client/src/client.rs, src/meta-srv/src/cache_invalidator.rs, src/meta-srv/src/metasrv/builder.rs, src/meta-srv/src/procedure.rs, src/meta-srv/src/service/store/etcd.rs, src/meta-srv/src/service/store/kv.rs, src/meta-srv/src/table_creator.rs, src/meta-srv/src/test_util.rs
1. refactor RaftEngineBackend Error to common_meta::error::Error
2. refactor state store
=> refactor: refactor raft engine backend and state store

src/catalog/src/error.rs, src/catalog/src/lib.rs, src/catalog/src/local/manager.rs, src/catalog/src/local/memory.rs, src/frontend/src/catalog.rs, src/frontend/src/error.rs, src/frontend/src/instance.rs, src/frontend/src/script.rs, src/script/src/manager.rs, src/script/src/table.rs
This PR: 
1. remove method `register_system_table` from CatalogManager
2. the creation of ScriptTable (as a system table) is removed from CatalogManager. Instead, the ScriptTable is created when Frontend instance is starting; and is created by calling Frontend instance's grpc handler.
=> refactor: script table creation

src/cmd/src/cli/upgrade.rs, src/common/catalog/src/error.rs, src/common/catalog/src/lib.rs, src/common/meta/src/key.rs, src/common/meta/src/key/table_route.rs, src/frontend/src/catalog.rs, src/frontend/src/heartbeat/handler/invalidate_table_cache.rs, src/meta-srv/src/error.rs, src/meta-srv/src/keys.rs, src/meta-srv/src/procedure/region_failover/update_metadata.rs, src/meta-srv/src/service/admin.rs, src/meta-srv/src/service/admin/meta.rs, src/meta-srv/src/service/admin/route.rs
1. rename NEXT_TABLE_ROUTE_PREFIX to TABLE_ROUTE_PREFIX
2. fix parsing `full_table_name` incorrectly
=> refactor: rename NEXT_TABLE_ROUTE_PREFIX to TABLE_ROUTE_PREFIX

src/mito2/src/compaction/twcs.rs, src/mito2/src/engine.rs, src/mito2/src/engine/alter_test.rs, src/mito2/src/engine/compaction_test.rs, src/mito2/src/engine/flush_test.rs, src/mito2/src/error.rs, src/mito2/src/flush.rs, src/mito2/src/manifest/action.rs, src/mito2/src/manifest/tests/checkpoint.rs, src/mito2/src/memtable/version.rs, src/mito2/src/read/scan_region.rs, src/mito2/src/read/seq_scan.rs, src/mito2/src/region/opener.rs, src/mito2/src/region/version.rs, src/mito2/src/test_util.rs, src/mito2/src/worker.rs, src/mito2/src/worker/handle_alter.rs, src/mito2/src/worker/handle_compaction.rs, src/mito2/src/worker/handle_flush.rs, src/mito2/src/worker/handle_write.rs, src/store-api/src/metadata.rs, src/store-api/src/region_request.rs
This PR implements a skeleton to alter a region. Steps to alter a region's schema are:
1. Flushes all memtables. It ensures no data with old schema in WAL and memtables so we don't need to deal with these data during replay
2. Writes the alteration to the manifest and applies it to the `Version` after the flush job is finished
Minor fixes
- Removes flushed memtables after a flush job is done.
- Compaction picker doesn't notify waiters if it returns None.
- #1869
- closes https://github.com/GreptimeTeam/greptimedb/issues/1977
=> feat(mito): Implement skeleton for alteration

src/table/src/table.rs, src/table/src/table/metrics.rs, src/table/src/table/scan.rs
This pr mainly replaces `BaselineMetrics` to a customized metrics struct in order to hold memory usage during scan plan, indicating the returning size of the dataset to the corresponding query request.
=> refactor: collecting memory usage during scan

src/datanode/src/datanode.rs, src/datanode/src/error.rs, src/datanode/src/region_server.rs, src/mito2/src/engine.rs, src/store-api/src/region_engine.rs
Make region server be able to be stopped.
=> feat: stop region server

Cargo.lock, Cargo.toml, src/cmd/src/error.rs, src/cmd/src/standalone.rs, src/common/meta/Cargo.toml, src/common/meta/src/ddl_manager.rs, src/common/meta/src/key.rs, src/common/meta/src/key/catalog_name.rs, src/common/meta/src/key/schema_name.rs, src/common/meta/src/metrics.rs, src/datanode/src/datanode.rs, src/frontend/src/instance.rs, src/frontend/src/instance/distributed.rs, src/meta-srv/src/error.rs, src/meta-srv/src/lib.rs, src/meta-srv/src/metadata_service.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/metasrv/builder.rs, src/meta-srv/src/metrics.rs, src/meta-srv/src/mocks.rs
fix start issues under standalone mode
=> fix: fix start issues under standalone mode

src/mito2/src/engine/alter_test.rs, src/mito2/src/engine/flush_test.rs, src/mito2/src/engine/open_test.rs, src/mito2/src/flush.rs, src/mito2/src/manifest/action.rs, src/mito2/src/manifest/tests/checkpoint.rs, src/mito2/src/region/opener.rs, src/mito2/src/region/version.rs, src/mito2/src/request.rs, src/mito2/src/test_util.rs, src/mito2/src/worker/handle_compaction.rs, src/mito2/src/worker/handle_flush.rs
This PR fixes the issue that the engine doesn't store and recover the flushed sequence:
- If we only store the flushed entry in the manifest, we can't recover the committed sequence if there is no data in the WAL
- It maintains a flushed sequence in the version and recovers it from the manifest
- It adds a test to check this
- #1869
=> fix(mito): Stores and recovers flushed sequence

Cargo.lock, Cargo.toml
=> chore: bump raft-engine to 22dfb4

src/sql/src/statements.rs
Convert `SqlValue` to GreptimeDB's `Value` with target type. Before this patch, it will only generate primitive types (from the `Value::from` method)
=> feat: convert sql number to values with target type

tests/runner/src/env.rs, tests/runner/src/main.rs
- no fail fast for sqlness runner
- change `disable-region-failover` to `enable-region-failover`
- remove `wal-dir`
=> feat: use the latest command line options for sqlness runner

src/client/src/client.rs, src/common/grpc/src/channel_manager.rs, src/servers/src/grpc.rs
The gRPC limits the maximum size of a message to 4MB.  We change to 512MB by default in this PR.
It will fix some sqlness failed tests like:
```
Error, message length too large: found 8300299 bytes, the limit is: 4194304 bytes
```
#2367
=> fix: gRPC max mesage size limitation

src/frontend/src/delete.rs, src/frontend/src/error.rs, src/frontend/src/insert.rs, src/frontend/src/req_convert/insert/stmt_to_region.rs, tests/cases/standalone/common/insert/insert_default.result, tests/cases/standalone/common/insert/insert_invalid.result
Fixed `insert_default` and `insert_invalid` sqlness cases.
#2367
=> chore: change error messages

src/datanode/src/datanode.rs, src/datanode/src/heartbeat.rs, src/datanode/src/region_server.rs
Puts the correct engine name in the heartbeat packet
=> feat: engine name in heartbeat

src/query/src/dist_plan/planner.rs
This patch fixes `information_schema` doesn't return anything.
It might also fix errors on `numbers` table.
- https://github.com/GreptimeTeam/greptimedb/issues/2367
=> fix: querying temporary table

src/common/meta/src/ddl/alter_table.rs, src/common/meta/src/ddl_manager.rs, src/frontend/src/statement/ddl.rs, src/meta-srv/src/procedure/tests.rs, src/mito2/src/error.rs, src/mito2/src/request.rs, src/sql/src/error.rs, src/store-api/src/metadata.rs, tests/cases/standalone/common/alter/add_col.result, tests/cases/standalone/common/alter/add_col.sql, tests/cases/standalone/common/alter/drop_col_not_null_next.result, tests/cases/standalone/common/alter/drop_col_not_null_next.sql
This PR stores the next column id in the `AlterTableProcedure` and updates `next_column_id` of the table meta.
It fixes the issue that the frontend always assigns the same column id to a new column.
- #2367
=> fix: alter table procedure forgets to update next column id

tests/cases/standalone/optimizer/order_by.result
this order_by case works after https://github.com/GreptimeTeam/greptimedb/pull/2388.
- https://github.com/GreptimeTeam/greptimedb/issues/2367
=> fix: update sqlness result for order_by

src/cmd/src/cli/upgrade.rs, src/common/meta/src/key.rs, src/common/meta/src/key/datanode_table.rs, src/meta-srv/src/procedure/region_failover/update_metadata.rs
Add the engine name to DatanodeTableValue because datanodes do not know how to open a region upon start.
=> feat!: add engine name to DatanodeTableValue

src/common/meta/src/ddl/alter_table.rs, tests-integration/src/grpc.rs, tests-integration/tests/grpc.rs
This PR fixes panics while using the `AlterTableProcedure` to rename a table.
It fixes integration tests for renaming. It also fixes grpc tests that use incorrect semantic type. Now the following tests pass:
- test_create_table_after_rename_table
- test_rename_table
- test_standalone_insert_and_query
- test_distributed_insert_delete_and_query
- https://github.com/GreptimeTeam/greptimedb/issues/2386
=> fix: alter table procedure panics while renaming table

src/common/meta/src/key/datanode_table.rs
This is a compatible patch to #2395 for upgrading with existing meta values.
=> chore: add `#[serde(default)]` to new added `engine` field

src/promql/src/planner.rs
Those cases are already fixed. I forget to remove `#[ignore]`s
=> fix: enable ignored promql unit tests

Cargo.lock, Cargo.toml, src/cmd/src/cli/upgrade.rs, src/common/meta/src/ddl/create_table.rs, src/common/meta/src/ddl/utils.rs, src/common/meta/src/key.rs, src/common/meta/src/key/datanode_table.rs, src/file-table-engine/src/engine/immutable.rs, src/file-table-engine/src/test_util.rs, src/meta-srv/src/error.rs, src/meta-srv/src/procedure/region_failover/update_metadata.rs, src/meta-srv/src/procedure/tests.rs, src/mito/src/engine.rs, src/mito/src/engine/procedure/create.rs, src/mito/src/engine/tests.rs, src/store-api/src/path_utils.rs, src/store-api/src/region_request.rs
In the past, we put the `catalog` and `schema` into the `CreateRegionRequest` and sent the request to the datanode to create regions, but in fact the datanode does not understand the meaning of the catalog and schema, it just uses this information to create the storage directory, we should directly pass in the "path"
Upgrade the Proto synchronously : https://github.com/GreptimeTeam/greptime-proto/pull/102
=> feat: region storage path

src/frontend/src/error.rs, src/frontend/src/instance/grpc.rs, src/sql/src/statements/create.rs, tests-integration/src/cluster.rs, tests-integration/src/grpc.rs, tests-integration/src/instance.rs, tests-integration/src/standalone.rs, tests-integration/src/test_util.rs, tests-integration/src/tests/instance_test.rs, tests-integration/tests/grpc.rs, tests-integration/tests/http.rs, tests-integration/tests/region_failover.rs, tests-integration/tests/sql.rs
=> fix: resolve more integration tests

src/store-api/src/metadata.rs, src/store-api/src/storage/consts.rs
The column name created by user cannot be the name of the reserved column.
Closes #2392
#2392
=> feat: reserve internal column

src/datanode/src/datanode.rs
https://github.com/GreptimeTeam/greptimedb/pull/2399 misuses the region storage path prefix. After this fix the server can re-open previous created regions:
```sql
MySQL [(none)]> show tables;
+---------+
| Tables  |
+---------+
| numbers |
| scripts |
+---------+
2 rows in set (0.013 sec)
MySQL [(none)]> create table t(ts timestamp time index);
Query OK, 0 rows affected (0.005 sec)
MySQL [(none)]> show tables;
+---------+
| Tables  |
+---------+
| numbers |
| scripts |
| t       |
+---------+
3 rows in set (0.001 sec)
MySQL [(none)]> show tables;
ERROR 2013 (HY000): Lost connection to server during query
MySQL [(none)]> show tables;
ERROR 2006 (HY000): Server has gone away …
```
=> fix: generate region path with given prefix

Cargo.lock, tests/runner/Cargo.toml, tests/runner/src/main.rs, tests/runner/src/util.rs
Added clap to the `sqlness` runner to improve the interface by providing help messages and allowing configurations.
`sqlness` can now accept arguments to be configured with when running tests. Below is the result of the help command after running: `cargo sqlness -h`
```
SQL Harness for GrepTimeDB
Usage: sqlness-runner [OPTIONS]
Options:
-c, --case-dir <CASE_DIR>                Directory of test cases
-f, --fail-fast...                       Fail this run as soon as one case fails if true
-e, --env-config-file <ENV_CONFIG_FILE>  Environment Configuration File [default: config.toml]
-t, …
```
=> feat: clap wrapper around sqlness 

src/datanode/src/config.rs, src/datanode/src/heartbeat.rs, src/frontend/src/frontend.rs, src/frontend/src/heartbeat.rs, src/meta-srv/src/handler/node_stat.rs, src/meta-srv/src/handler/response_header_handler.rs, src/servers/src/heartbeat_options.rs
When sending heartbeat request, set header because metasrv requires this.
=> feat: heartbeat request with header

config/datanode.example.toml, config/frontend.example.toml, config/standalone.example.toml, src/cmd/src/datanode.rs, src/cmd/src/frontend.rs, src/cmd/src/metasrv.rs, src/cmd/src/options.rs, src/cmd/src/standalone.rs, src/datanode/src/config.rs, src/datanode/src/datanode.rs, src/datanode/src/server.rs, src/frontend/src/frontend.rs, src/frontend/src/instance.rs, src/frontend/src/server.rs, src/meta-srv/src/bootstrap.rs, src/meta-srv/src/metasrv.rs
Our current rules for naming options are highly inconsistent, with the presence of xxxOpts, xxxOptions, and simply xxx.
This PR will ensure a consistent usage of xxx throughout.
=> feat!: unify naming with options

src/datanode/src/datanode.rs, src/datanode/src/event_listener.rs, src/datanode/src/heartbeat.rs, src/datanode/src/lib.rs, src/datanode/src/region_server.rs, src/datanode/src/tests.rs
1. Add `RegionServerEventListener`
2. Sync `Region` between RegionServer and RegionAliveKeeper
=> feat: sync regions between RegionServer and RegionAliveKeeper

src/datanode/src/heartbeat.rs, src/frontend/src/heartbeat.rs, src/frontend/src/instance.rs, src/meta-srv/src/handler/keep_lease_handler.rs, src/meta-srv/src/handler/node_stat.rs, src/meta-srv/src/selector/load_based.rs
=> fix: missing datanode id on keep lease

src/common/meta/src/ddl/alter_table.rs, src/datanode/src/region_server.rs, src/servers/src/grpc/flight.rs, src/servers/src/grpc/flight/stream.rs, src/servers/src/grpc/greptime_handler.rs, src/servers/src/grpc/region_server.rs
Scope some `spawn()`s with existing trace id. I don't find a good way to test this behavior. I'm afraid the only way is to find and add missing `.scope()` call on debugging 😖
=> feat: scope spawned task with trace id

src/mito2/src/compaction.rs, src/mito2/src/compaction/twcs.rs, src/mito2/src/engine/compaction_test.rs, src/mito2/src/error.rs, src/mito2/src/flush.rs, src/mito2/src/memtable.rs, src/mito2/src/read/scan_region.rs, src/mito2/src/read/seq_scan.rs, src/mito2/src/request.rs, src/mito2/src/test_util.rs, src/mito2/src/test_util/memtable_util.rs, src/mito2/src/test_util/scheduler_util.rs, src/mito2/src/test_util/version_util.rs, src/mito2/src/worker.rs, src/mito2/src/worker/handle_alter.rs, src/mito2/src/worker/handle_close.rs, src/mito2/src/worker/handle_compaction.rs, src/mito2/src/worker/handle_drop.rs, src/mito2/src/worker/handle_flush.rs, src/mito2/src/worker/handle_truncate.rs
This PR implements the compaction scheduler for mito2. The `CompactionScheduler`
- tracks region that is compacting and its pending compaction requests
- ensures only one compaction task is running for a region, and merge compaction request waiters
- cancels compaction tasks and notifies waiters if compaction is failed or the region is dropped/closed/truncated
It adds some tests for compaction and flush schedulers. I'll add more tests in later PRs.
Other changes
- schedules compaction after a flush job is finished
- fixes an incorrect debug assertion in FlushScheduler
- #1869
=> feat(mito): Implements compaction scheduler

tests/cases/distributed/optimizer/order_by.result, tests/cases/distributed/show/show_create.result, tests/cases/distributed/show/show_create.sql
Numbers table is a temporary table and should be scanned locally. We don't support to define partition rule on non-primary keys.
- #2367
=> fix: update several sqlness results

Cargo.lock, config/metasrv.example.toml, src/cmd/src/metasrv.rs, src/common/meta/src/distributed_time_constants.rs, src/common/meta/src/lib.rs, src/meta-srv/src/handler/region_lease_handler.rs, src/meta-srv/src/metasrv.rs, src/meta-srv/src/metasrv/builder.rs, src/servers/Cargo.toml, src/servers/src/heartbeat_options.rs
Make all the distributed xxx_time variables together: lease_time, failover_time, heartbeat_interval_time ...
And use `HEARTBEAT_INTERVAL_MILLIS` as the base unit for these times, with other times being multiples of it.
By doing this, we can modify these values in a single location to prevent inconsistencies caused by their scattered placement.
=> feat: all distributed time together

config/datanode.example.toml, src/datanode/src/alive_keeper.rs, src/datanode/src/config.rs, src/datanode/src/datanode.rs, src/datanode/src/heartbeat.rs, tests/conf/datanode-test.toml.template
Start services after the first heartbeat response is processed
=> feat: start services after first heartbeat response processed

src/client/src/error.rs, src/client/src/region.rs, src/datanode/src/alive_keeper.rs, src/datanode/src/error.rs
=> fix: fix incorrect matches

config/datanode.example.toml, src/datanode/src/config.rs, src/datanode/src/datanode.rs, src/mito2/src/worker/handle_alter.rs, tests/conf/datanode-test.toml.template
rename coordination to require_lease_before_startup
=> refactor: rename coordination to require_lease_before_startup

Cargo.lock, src/frontend/Cargo.toml, src/frontend/src/instance.rs, src/frontend/src/instance/script.rs, src/frontend/src/script.rs, src/script/Cargo.toml, src/script/src/error.rs, src/script/src/lib.rs, src/script/src/manager.rs, src/script/src/python/engine.rs, src/script/src/table.rs, src/script/src/test.rs, src/servers/src/http/script.rs, src/servers/src/query_handler.rs, src/servers/tests/mod.rs, src/servers/tests/py_script/mod.rs, src/table/src/metadata.rs
The final PR to make the scripts table work again.
Main changes:
* Create `scripts` table in the `public` schema for every catalog 
* Create `scripts` table lazily only when inserting or executing scripts by HTTP APIs.
* Create or insert scripts by the new APIs instead of table APIs.
* Changed the `scripts` table schema, remove `gmt_created` and set `schema, name, engine` as primary key.
todo:
* We need a hook that will be executed after table regions are all opened. The script manager will recompile and register all scripts as  SQL UDF in that hook. cc @waynexia
=> feat: make scripts table work again

src/mito2/src/worker/handle_alter.rs
check version before alter region
=> fix: check version before alter region

tests-integration/src/grpc.rs, tests-integration/tests/grpc.rs
The `ColumnDef` has a new field `comment`, we have to resolve the compile errors.
=> fix: compile error after updating protos

src/common/time/src/date.rs, src/common/time/src/datetime.rs, src/common/time/src/time.rs, src/common/time/src/timestamp.rs, src/datatypes/src/data_type.rs, src/datatypes/src/types.rs, src/datatypes/src/types/binary_type.rs, src/datatypes/src/types/boolean_type.rs, src/datatypes/src/types/cast.rs, src/datatypes/src/types/date_type.rs, src/datatypes/src/types/datetime_type.rs, src/datatypes/src/types/dictionary_type.rs, src/datatypes/src/types/duration_type.rs, src/datatypes/src/types/interval_type.rs, src/datatypes/src/types/list_type.rs, src/datatypes/src/types/null_type.rs, src/datatypes/src/types/primitive_type.rs, src/datatypes/src/types/string_type.rs, src/datatypes/src/types/time_type.rs, src/datatypes/src/types/timestamp_type.rs
1. add `try_cast()` in `datatype` trait.
2. implement the cast for `date/time/timestamp/datetime` types.
3. implement primitive types `u8,u16,u32,u64,i8,i16,i32,i64,f32,f64` cast.
4. impl `cast_with_opt` method which supports two mode which can be set with `CastOption` for casting type(for cast failed: `strict mode` will return error and `non-strict` mode will return Null).
Closes https://github.com/GreptimeTeam/greptimedb/issues/2376
=> feat: type conversion between Values

Cargo.lock, src/client/src/lib.rs, src/frontend/src/instance.rs, src/frontend/src/instance/region_query.rs, src/frontend/src/instance/standalone.rs, src/query/Cargo.toml, src/query/src/dist_plan/merge_scan.rs, src/query/src/dist_plan/planner.rs, src/query/src/error.rs, src/query/src/lib.rs, src/query/src/query_engine.rs, src/query/src/query_engine/state.rs, src/query/src/region_query.rs
try to make things clearer
* Rename `RegionRequestHandler` to `RegionQueryHandler`, and move it from `client` to `query`
* Rename `frontend::DistRegionRequestHandler` to `FrontendRegionQueryHandler`
* Rename `StandaloneRegionRequestHandler` to `RegionInvoker`, and remove the implementation of `RegionRequestHandler`
=> refactor: RegionRequestHandler -> RegionQueryHandler

src/sql/src/statements.rs
parse i64 to TimestampSecond, TimestampMillisecond, TimestampMicrosecond, TimestampNanosecond.
=> fix: parse i64 to different kinds of timestamp

src/common/meta/src/instruction.rs, src/datanode/src/heartbeat/handler.rs, src/datanode/src/tests.rs, src/meta-srv/src/procedure/region_failover.rs, src/meta-srv/src/procedure/region_failover/activate_region.rs, src/meta-srv/src/procedure/region_failover/deactivate_region.rs, src/meta-srv/src/procedure/region_failover/invalidate_cache.rs, src/meta-srv/src/procedure/region_failover/update_metadata.rs
=> fix: fix open region missing path

src/common/meta/src/ddl/alter_table.rs, src/common/meta/src/ddl/create_table.rs, src/common/meta/src/ddl/drop_table.rs, src/meta-srv/src/procedure/tests.rs, src/table/src/error.rs, src/table/src/metadata.rs
1. fix alter table verification
2.  move AlterTable UpdateMetadata to last step
fix #2425
=> fix: fix alter table verification

src/meta-srv/src/procedure/region_failover.rs, src/meta-srv/src/procedure/region_failover/activate_region.rs, src/meta-srv/src/procedure/region_failover/deactivate_region.rs
If the meta leader node dies during the execution of the procedure, the new leader node needs to remark the failed region as "inactive" to prevent it from renewing the lease.
Close #2332
=> fix: remark region as inactive on leader changed

src/datanode/src/datanode.rs
Open region in parallel. The default parallelism is 16, we can make it configurable later.
=> feat: open region in parallel

src/sql/src/statements.rs
Supports binary sql data type.
=> feat: supports binary data type

tests-integration/src/opentsdb.rs, tests-integration/src/tests/instance_test.rs
Revert two ignored tests.
#2401
=> test: revert ignored tests

src/catalog/src/kvbackend.rs, src/catalog/src/kvbackend/client.rs, src/catalog/src/kvbackend/manager.rs, src/cmd/src/standalone.rs, src/common/meta/src/cache_invalidator.rs, src/frontend/src/heartbeat/handler/invalidate_table_cache.rs, src/frontend/src/heartbeat/handler/tests.rs, tests-integration/src/standalone.rs
unify table metadata cache invalidator
=> refactor: unify table metadata cache invalidator

src/store-api/src/path_utils.rs
```sql
MySQL [(none)]> show tables;
+---------+
| Tables  |
+---------+
| numbers |
| scripts |
| t       |
+---------+
3 rows in set (0.013 sec)
MySQL [(none)]> drop table t;
Query OK, 1 row affected (0.004 sec)
MySQL [(none)]> show tables;
+---------+
| Tables  |
+---------+
| numbers |
| scripts |
+---------+
2 rows in set (0.001 sec)
```
closes https://github.com/GreptimeTeam/greptimedb/issues/2457
=> fix: add slash after generated region_dir

.github/actions/upload-artifacts/action.yml
ci: expand upload retry timeout
=> ci: expand upload retry timeout

Cargo.lock, src/object-store/Cargo.toml
bump opendal to 0.40
- https://github.com/apache/incubator-opendal/issues/2788
=> chore: bump opendal to 0.40

src/datanode/src/lib.rs, src/datanode/src/tests.rs, src/query/src/query_engine.rs
`SqlStatementExecutor` is no longer needed
=> refactor: remove SqlStatementExecutor

src/client/src/client.rs, src/common/grpc/src/channel_manager.rs, src/datanode/src/config.rs, src/datanode/src/server.rs, src/frontend/src/server.rs, src/frontend/src/service_config/grpc.rs, src/servers/src/grpc.rs, tests-integration/src/cluster.rs, tests-integration/src/test_util.rs, tests-integration/tests/grpc.rs, tests-integration/tests/http.rs
Limit grpc client/server message size
- Make grpc client `max_decoding_message_size`/`max_encoding_message_size` configurable
- Make grpc server `max_decoding_message_size`/`max_encoding_message_size` configurable
https://github.com/GreptimeTeam/greptimedb/issues/2220
=> feat: limit grpc message size

src/catalog/src/lib.rs, src/table/src/table.rs
=> chore: remove unused region_stats method form table

Cargo.lock, Cargo.toml, src/common/meta/src/ddl/create_table.rs, src/file-engine/src/engine.rs, src/file-engine/src/error.rs, src/file-engine/src/region.rs, src/meta-srv/src/procedure/tests.rs, src/mito2/src/error.rs, src/mito2/src/test_util.rs, src/store-api/src/region_request.rs
This PR updates proto and removes create_if_not_exists from RegionCreateRequest. 
Creating a region needs to be idempotent so `create_if_not_exists` is always `true`, we don't need a flag for this.
=> feat: update proto and remove create_if_not_exists

src/mito2/src/compaction.rs, src/mito2/src/compaction/twcs.rs, src/mito2/src/manifest/action.rs, src/mito2/src/manifest/tests/checkpoint.rs, src/mito2/src/region/opener.rs, src/mito2/src/region/version.rs, src/mito2/src/request.rs, src/mito2/src/test_util/scheduler_util.rs, src/mito2/src/test_util/version_util.rs, src/mito2/src/worker/handle_compaction.rs, tests/cases/standalone/common/select/like.result, tests/cases/standalone/common/select/like.sql
Fix the issue that the compaction scheduler may schedule more tasks than expected
- When a compaction task is finished, `on_compaction_finished()` tries to schedule the next job but doesn't mark the region as compacting.
- Next time we invoke `schedule_compaction()` will trigger one more compaction task.
This PR removes `compacting` since the region status map containing the region already indicates whether the region is compacting.
This PR also stores the compaction time window to the manifest and recovers it while opening the region. If we don't keep the inferred time window in the version, the region may always infer a larger time window than the last compaction.
=> fix(mito): compaction scheduler schedules more tasks than expected
